TOP = ..
include $(TOP)/configure/CONFIG
include $(TOP)/configure/RELEASE.gemini
DIRS += src
DIRS += lib
DIRS += pointlib
DIRS += scriptlib
DIRS += tcclib
DIRS += tsdlib
include $(TOP)/configure/RULES_DIRS

