#+
# PointObs
#
# A PointObs object sequences the actions needed to execute a
# sequence of pointing observations.
#
#    Methods:
#
#       slew   Slews to the next star
#
#       log    Logs the pointing data
#
#    Options:
#
#       guidedelay     The number of seconds to wait before enabling guiding.
#
#       logdelay       The number of seconds to wait after enabling guiding
#                      before loging the pointing.
#
#       logafterslew   If true, the pointing is logged at the end of a slew.
#
#       nextstyle      The method for selecting the next star.
#
#       offloaddelay   The number of seconds to wait before offloading
#                      m2 tip/tilt to the mount.
#
#       selectafterlog If true, slew to the next star after logging.
#
#       guide          If true, guiding is enabled before logging and
#                      disabled afterwards.
#
#       wfs            Which WFS to use for guiding.
#
#       zlpm           If true, zero the local pointing model when slewing.
#
#       logrepeats     The number of time to log each star
#
#  D Terrett 20 January 2004
#
#  Copyright CCLRC
#+

itcl::class PointObs {
   constructor {sourceentry args} {}
   destructor {}
   common ActuatorsMoving
   common InPosition
   common DomeVignette
   public {
      method slew {}
      method log {}
      method updateAoMoving {args}
      method checkDomeVignette {args}
      method checkInPosition {args}
      variable logdelay 0
      variable guidedelay
      variable offloaddelay
      variable logafterslew 0
      variable nextstyle minslew
      variable selectafterlog 0
      variable guideafterslew 0
      variable zlpm 0
      variable wfs PWFS2
      variable logrepeats
   }
   private {
      method nextstar {args}
      method nextaction {args}
      method reporterror {message}
      method start {action}
      method onerror {message}
      method isinposition {} 
      method novignette {}
      method actuatorsmoving {}
      method isguiding {}
      variable SlewAction
      variable Guide1Action
      variable Guide2Action
      variable MountGuideAction
      variable GuideOffAction
      variable DomeWaitAction
      variable PcsWaitAction
      variable LogAction
      variable SourceEntry
      variable AzElPlot
      variable Catalogue
      variable Guiding 0
#      variable InPosition
#      variable DomeVignette
#      variable ActuatorsMoving
      variable IsGuiding
      variable LogCount 0
   }
}

itcl::body PointObs::constructor {sourceentry azelplot catalogue args} {

# Store the source entry etc object.
   set SourceEntry $sourceentry
   set AzElPlot $azelplot
   set Catalogue $catalogue

# Create the action that slews the telescope.
   set SlewAction [seq::Action #auto tcs -timeout 300 \
         -onok [itcl::code $this nextaction slew] \
         -onerror [itcl::code $this onerror] \
         -ontimeout [itcl::code $this onerror "Slew timed out"] \
         -oktest [itcl::code $this isinposition] \
         -waitvar [itcl::scope InPosition(value)]]
   sa tcssad proc inPosition  "$this checkInPosition"
#   sa tcssad link inPosition [itcl::scope InPosition]
   $SlewAction set slew pointing Off

# Create action that waits for the dome vignetting to go to zero.
   set DomeWaitAction [seq::Action #auto tcs -timeout 300 \
         -onok [itcl::code $this nextaction domewait] \
         -ontimeout [itcl::code $this onerror "timed out waiting for dome"] \
         -oktest [itcl::code $this novignette] \
         -waitvar [itcl::scope DomeVignette(value)]]
   sa tcssad proc domeVignette "$this checkDomeVignette"
#   sa tcssad link domeVignette [itcl::scope DomeVignette]

# Create action that waits for the PCS to settle.
   set aoWaitAction [seq::Action #auto tcs -timeout 300 \
         -onok [itcl::code $this nextaction pcswait] \
         -ontimeout [itcl::code $this onerror "timed out waiting for PCS to settle"] \
         -oktest [itcl::code $this actuatorsmoving] \
         -waitvar [itcl::scope ActuatorsMoving(value)]]   
   sa pcssad proc aoMoving "$this updateAoMoving"
#   sa pcssad link aoMoving [itcl::scope ActuatorsMoving]

# Create actions for enabling and disabling guiding.
   set MountGuideAction [seq::Action #auto tcs \
         -onerror [itcl::code $this onerror] \
         -oktest [itcl::code $this isguiding] \
         -ontimeout [itcl::code $this onerror "Attempt to guide timed out"] \
         -waitvar [itcl::scope IsGuiding(value)]]
   $MountGuideAction set mountGuide mode On 
   set Guide1Action [seq::Action #auto tcs \
         -onerror [itcl::code $this onerror]]
   $Guide1Action set m2Guide state On
   $Guide1Action set pwfs1Observe noexp -1

   set Guide2Action [seq::Action #auto tcs \
         -onerror [itcl::code $this onerror]]
   $Guide2Action set m2Guide state On
   $Guide2Action set pwfs2Observe noexp -1

   set GuideOffAction [seq::Action #auto tcs \
         -onok [itcl::code $this nextaction guideoff] \
         -onerror [itcl::code $this onerror] \
         -ontimeout [itcl::code $this onerror \
         "Attempt to disable guiding timed out"]]
   $GuideOffAction set m2Guide state Off
   $GuideOffAction set mountGuide mode Off 
   $GuideOffAction set pwfs1StopObserve dummy 1
   $GuideOffAction set pwfs2StopObserve dummy 1

# Create the action that logs the pointing.
   set LogAction [seq::Action #auto tcs -timeout 300 \
         -onok [itcl::code $this nextaction log] \
         -onerror [itcl::code $this onerror] \
         -ontimeout [itcl::code $this onerror "Logging pointing timed out"] \
         -oktest [itcl::code $this isinposition] \
         -waitvar [itcl::scope InPosition(value)]]

# Set the pointLog parameter to mark the CAD.
   $LogAction set pointLog log Off

   eval configure $args
}

itcl::body PointObs::destructor {} {
   sa pcssad unproc aoMoving "$this updateAoMoving"
   sa tcssad unproc domeVignette "$this checkDomeVignette"
   sa tcssad unproc inPosition  "$this checkInPosition"
}

itcl::body PointObs::checkDomeVignette {name alarm time values} {
        global DomeVignette

        set tname [lrange [split $name "." ] 1 1 ]
        set tnamev [format "%s%s" $tname "(value)"]
        set $tnamev $values
        if {([string is digit [set $tnamev]] || [string is double [set $tnamev]]) && [string length [set $tnamev]]>0 } {
                set DomeVignette($tname) [format "%.0f" [set $tnamev]]
#                puts "set DomeVignette($tname) to $DomeVignette($tname)"
        }
        return
}

itcl::body PointObs::checkInPosition {name alarm time values} {
        global InPosition

        set tname [lrange [split $name "." ] 1 1 ]
        set tnamev [format "%s%s" $tname "(value)"]
        set $tnamev $values
        if {([string is digit [set $tnamev]] || [string is double [set $tnamev]]) && [string length [set $tnamev]]>0 } {
                set InPosition($tname) [format "%.0f" [set $tnamev]]
#                puts "set InPosition($tname) to $InPosition($tname)"
        }
        return
}

itcl::body PointObs::updateAoMoving {name alarm time values} {
        global ActuatorsMoving

        set tname [lrange [split $name "." ] 1 1 ]
        set tnamev [format "%s%s" $tname "(value)"]
        set $tnamev $values
        if {([string is digit [set $tnamev]] || [string is double [set $tnamev]]) && [string length [set $tnamev]]>0 } {
                set ActuatorsMoving($tname) [format "%.0f" [set $tnamev]]
#                puts "set ActuatorsMoving($tname) to $ActuatorsMoving($tname)"
        }
        return
}

itcl::body PointObs::slew {} {

   $SlewAction set sourceA objName [[$SourceEntry component objname] get]
   $SlewAction set sourceA system [[$SourceEntry component frame] get]
   $SlewAction set sourceA theta1 [[$SourceEntry component ra] get]
   $SlewAction set sourceA theta2 [[$SourceEntry component dec] get]
   $SlewAction set sourceA equinox [[$SourceEntry component equinox] get]
   $SlewAction set sourceA epoch [[$SourceEntry component epoch] get]
   $SlewAction set sourceA parallax [[$SourceEntry component parallax] get]
   $SlewAction set sourceA dtheta1 [[$SourceEntry component pmra] get]
   $SlewAction set sourceA dtheta2 [[$SourceEntry component pmdec] get]
   $SlewAction set sourceA rv [[$SourceEntry component rv] get]

   start $SlewAction
}

itcl::body PointObs::log {} {

# Look at the guide ca/ce to check that some guiding has taken place and that
# it isn't an excessive amount.
   set ca [sa tcssad get caguide]
   set ce [sa tcssad get ceguide]
   if { $ca == 0.0 && $ce == 0.0 } {
      set ans [tk_messageBox -icon question -parent . -type yesno \
         -message "No guiding has taken place. Log this star ?"]
   } elseif { $ca * $ca + $ce * $ce > 100.0 } {
      set ans [tk_messageBox -icon question -parent . -type yesno \
         -message "guiding correction is excessive. Log this star ?"]
   } else {
      set ans yes
   }
 
   if { [string equal $ans yes] } {
      start $LogAction
   } else {
      nextaction logall
   }
}

itcl::body PointObs::nextaction {after} {
   switch $after {
      slew {
         set LogCount 0
         start $DomeWaitAction
      }
      domewait {
         start $PcsWaitAction
      }
      pcswait {
         set LogCount 0
         if { $guideafterslew } {
            set Guiding 1
            switch $wfs {
               PWFS1 {
                  start $Guide1Action
               }
               PWFS2 {
                  start $Guide2Action
               }
            }
         } elseif { $logafterslew } {
            log
         }
      }
      m2guide {
         set xtilt [sa m2ssad get xtilt value]
         set ytilt [sa m2ssad get ytilt value]
         cs collAdjust set frame 0
         cs collAdjust set size [expr {$xtilt / 3.86956518}]
         cs collAdjust set angle 0.0
         cs tcsApply post
         cs collAdjust set size [expr {$ytilt / 3.86956518}]
         cs collAdjust set angle 90.0
         cs tcsApply post
         $MountGuideAction start
      }
      guideon {
         set LogCount 0
         if { $logafterslew } {
            log
         }
      }
      guideoff {
         set LogCount 0
         if { $selectafterlog } {
            set Guiding 0
            nextstar
         }
      }
      log {
         incr LogCount
         if { $LogCount < $logrepeats } {
            after 100 [namespace code "$LogAction start"]
         } else {
            set LogCount 0
            nextaction logall
         }
      }
      logall {
         if { $Guiding } {
            start $GuideOffAction
         } elseif { $selectafterlog } {
            nextstar
         }
      }
   }
}

itcl::configbody PointObs::zlpm {
   if { $zlpm } {
      $SlewAction set slew pointing On
   } else {
      $SlewAction set slew pointing Off
   }
}

itcl::body PointObs::nextstar {args} {
   set tag [$AzElPlot next $nextstyle]
   $Catalogue select $tag
   $AzElPlot select pointing $tag
}

itcl::body PointObs::reporterror {message} {
   tk_messageBox -icon error -message $message -type ok \
         -title "Point Test Error"
}


itcl::body PointObs::start {action} {
   if { [catch {$action start} message] } {
      reporterror $message
   }
}

itcl::body PointObs::onerror {message} {
   reporterror $message
}

itcl::configbody PointObs::logdelay {
   $MountGuideAction configure -onok "after [expr {$logdelay * 1000}] \
         [itcl::code $this nextaction guideon]" 
}

itcl::body PointObs::isinposition {} {
   set val [sa tcssad get inPosition]
   return [string equal $val TRUE]
}

itcl::body PointObs::novignette {} {
   set val [sa tcssad get domeVignette]
   return [expr { $val <= 0.1 }]
}

itcl::body PointObs::actuatorsmoving {} {
   set val [sa pcssad get aoMoving]
   return [expr { $val < 7 }]
}

itcl::body PointObs::isguiding {} {
   switch $wfs {
      PWFS1 {
         set val [sa agssad get p1guiding]
      }
      PWFS2 {
         set val [sa agssad get p2guiding]
      }
   }
#   return [expr { $val == 0 }]
   return 1
}

itcl::configbody PointObs::guidedelay {
   $SlewAction configure -onok "after [expr {$guidedelay * 1000}] \
         [itcl::code $this nextaction slew]"
}

itcl::configbody PointObs::offloaddelay {
   $Guide1Action configure -onok "after [expr {$offloaddelay * 1000}] \
         [itcl::code $this nextaction m2guide]"
   $Guide2Action configure -onok "after [expr {$offloaddelay * 1000}] \
         [itcl::code $this nextaction m2guide]"
}
