variables:
  SCRIPTS_BRANCH: "softTCS_mk"
  CI_SCRIPTS_DIR: "ci"
  GIT_SUBMODULE_FORCE_HTTPS: "true"
  GIT_SUBMODULE_STRATEGY: "recursive"

include:
  - project: 'nsf-noirlab/gemini/rtsw/user-tools/gemini-rtsw-ci'
    ref: 'softTCS_mk'
    file: '.imported-ci.yml'

stages:
  - build
  - deploy
