# This file is for Gemini South
#
# The x/y/z position that corresponds to the A&G PWFS1 probeSel center
# command.

set pwfs1_center_x -1.330
set pwfs1_center_y -15.102
set pwfs1_center_z  0.0 

# The pointing origin that corresponds to the P1 probe at its center 
# position.

set pwfs1_hotspot_x  1.86
set pwfs1_hotspot_y -16.44

# The x/y/z position that corresponds to the A&G PWFS2 probeSel center
# command.

set pwfs2_center_x -0.567
set pwfs2_center_y 0.771
set pwfs2_center_z  0.0

# The pointing origin that corresponds to the P2 probe at its center 
# position.

set pwfs2_hotspot_x 1.86
set pwfs2_hotspot_y 0.62

