# This file is for Mauna Kea

# The name of the OCS session soap server.
set ocs_proxy http://scott:9000/axis/services

# The root of the directory in when WFS images are stored.
set wfs_image_root /net/tyle/export/data/astrodata

# The x/y/z position that corresponds to the A&G PWFS1 probeSel center
# command.

set pwfs1_center_x   2.324
set pwfs1_center_y -12.213
set pwfs1_center_z   0.0

# The x/y/z position that corresponds to the A&G PWFS2 probeSel center
# command.

set pwfs2_center_x -3.493
set pwfs2_center_y -2.480
set pwfs2_center_z  0.0

# The center position for the Acquisition camera window
set acqcam_x 518
set acqcam_y 519

