# This file is for Mauna Kea

# The x/y/z position that corresponds to the A&G PWFS1 probeSel center
# command.

set pwfs1_center_x   2.324
set pwfs1_center_y -12.213
set pwfs1_center_z   0.0

# The x/y/z position that corresponds to the A&G PWFS2 probeSel center
# command.

set pwfs2_center_x -3.493
set pwfs2_center_y -2.480
set pwfs2_center_z  0.0

# The center position for the Acquisition camera window
set acqcam_x 479
set acqcam_y 513

