# This file is for Mauna Kea

# The x/y/z position that corresponds to the A&G PWFS1 probeSel center
# command.

set pwfs1_center_x   2.324
set pwfs1_center_y -12.213
set pwfs1_center_z   0.0

# The pointing origin that corresponds to the P1 probe at its center 
# position.

set pwfs1_hotspot_x  -0.00
set pwfs1_hotspot_y -15.20

# The x/y/z position that corresponds to the A&G PWFS2 probeSel center
# command.

set pwfs2_center_x -3.493
set pwfs2_center_y -2.480
set pwfs2_center_z  0.0

# The pointing origin that corresponds to the P2 probe at its center 
# position.

set pwfs2_hotspot_x 0.0
set pwfs2_hotspot_y 0.0

