# Options database for the tcc & tsd - this version is for Mauna Kea

# Labels for ISS ports.
*graphicDisplay.port1Label:	
*graphicDisplay.port2Label:	CurvWFS
*graphicDisplay.port3Label:     QUIRC/Hokupa'a
*graphicDisplay.port4Label:     A&G cabinet
*graphicDisplay.port5Label:	CurvWFS

# Names of Science fold positions used by A & G.
#   sky to port 3
*graphicDisplay.scfoldPos0:	Hokupaa
#   sky to port 2
*graphicDisplay.scfoldPos1:	cfwfs
#   sky to port 5
*graphicDisplay.scfoldPos2:	CurvWFS
#   sky to port 4
*grapicsDisplay.scfoldPos4:
#   cal unit to port 3
*grapicsDisplay.scfoldPos5:
#   cal unit to port 5
*grapicsDisplay.scfoldPos9:
#   cal unit to port 1
*grapicsDisplay.scfoldPos11:	GcaltoAC

# Foreground for all windows.
*foreground:				Black

# Background for displays.
*numericDisplay.background:	Wheat
*graphicDisplay.background:	Wheat

# Background for the "direct action" panels.
*observePanel*background:		PeachPuff1
*ecsPanel*background:		PeachPuff1
*guideLoopPanel*background:	PeachPuff1
*guideHandsetPanel*background:	PeachPuff1
*mcsPanel*background:		PeachPuff1
*targetHandsetPanel*background:	PeachPuff1
*poHandsetPanel*background:		PeachPuff1
*crsPanel*background:		PeachPuff1
*tcsPanel*background:		PeachPuff1

# Background for the configuration editing panels.
*CosysPanel*background:		LightGray
*GuidePanel*background:		LightGrey
*InstrumentPanel*background:		LightGray
*PointOrigPanel*background:		LightGray
*ChopPanel*background:		LightGray
*RotatorPanel*background:		LightGray
*SciTargetPanel*background:		LightGray
*SlewOptionsPanel*background:	LightGray
*WfsTargetPanel*background:		LightGray
*TcsConfigPanel*background:		LightGray
*TrackFramePanel*background:		LightGray
*TrackRatePanel*background:		LightGray
*WavelengthPanel*background:		LightGray

# Font for "major" tcc items.
*majorFont:			-*-*-bold-r-normal-sans-14-*-*-*-*-*-*-*

# Fonts for tsd displays.
*numericDisplay.Font:		-*-*-bold-r-normal-sans-18-*-*-*-*-*-*-*
*graphicDisplay.Font:		-*-*-bold-r-normal-sans-18-*-*-*-*-*-*-*
