# Options database for the tcc & tsd - this version is for Mauna Kea

# Labels for ISS ports.
*graphicDisplay.port1Label:	OSCIR
*graphicDisplay.port2Label:	
*graphicDisplay.port3Label:     QUIRC/Hokupa'a
*graphicDisplay.port4Label:     GCAL
*graphicDisplay.port5Label:	NIRI

# Foreground for all windows.
*foreground:				Black

# Background for displays.
*numericDisplay.background:	Wheat
*graphicDisplay.background:	Wheat

# Background for the "direct action" panels.
*observePanel*background:		PeachPuff1
*ecsPanel*background:		PeachPuff1
*guideLoopPanel*background:	PeachPuff1
*mcsPanel*background:		PeachPuff1
*handsetPanel*background:	PeachPuff1
*crsPanel*background:		PeachPuff1
*tcsPanel*background:		PeachPuff1

# Background for the configuration editing panels.
*CosysPanel*background:		LightGray
*GuidePanel*background:		LightGrey
*InstrumentPanel*background:		LightGray
*PointOrigPanel*background:		LightGray
*ChopPanel*background:		LightGray
*RotatorPanel*background:		LightGray
*FieldPanel*background:		LightGray
*SlewOptionsPanel*background:	LightGray
*TcsConfigPanel*background:		LightGray
*TrackFramePanel*background:		LightGray
*TrackRatePanel*background:		LightGray
*WavelengthPanel*background:		LightGray

# Font for "major" tcc items.
*majorFont:			-*-*-bold-r-normal-sans-14-*-*-*-*-*-*-*

# Fonts for tsd displays.
*numericDisplay.Font:		-*-*-bold-r-normal-sans-18-*-*-*-*-*-*-*
*graphicDisplay.Font:		-*-*-bold-r-normal-sans-18-*-*-*-*-*-*-*
