#!/bin/sh
# the next line restarts using ocswish \
exec $HLPG_INSTALL_BASE/bin/solaris/ocswish "$0" "$@"

#+
#  pointupdate
#
#  D Terrett 17 September 1999
#
#  Copyright CCLRC
#-
set tcl_precision 14

# Define the root directory for locating libraries.
global ROOT
set ROOT [file dirname [info script]]
if { [string compare [file pathtype $ROOT] relative] == 0 } {
   set ROOT [pwd]/$ROOT
}
lappend auto_path $ROOT/lib

# The pointupdate application procedures live in the pointlib subdirectory.
lappend auto_path $ROOT/pointlib

# Load the tcctime and sla extensions to tcl.
load $ROOT/lib/solaris/tcctime.so

package require Itcl
namespace import itcl::*
package require Itk
package require Iwidgets
package require Ocspkg

# Set the name of the epics service configuration file.
if { [info exists env(TCC_TCSNAME)] } {
   puts "Using $env(TCC_TCSNAME)"
   set ext .$env(TCC_TCSNAME)
} else {
   set ext ""
}
appData add configPath $ROOT/ca_config$ext
appData add configFile pointupdate.ca

appData add appKind Tcs
appData add appName pointUpdate

service epics

# Set application title
wm title . "Gemini pointing update"
wm iconname . "Gemini pointing update"
wm resizable . 1 1

pointUpdateMain {}
