#!/bin/sh
# the next line restarts using ocswish \
exec $HLPG_INSTALL_BASE/bin/ocswish "$0" "$@"

#  FILENAME
#  pointtest
#
#+
#  Purpose:
#  Utility to run a pointing test
#
#  Description:
#  This utility executes a series of pointing observations on a set of
#  star positions stored in a file and writes a log that can be processed
#  into a TPOINT data file.
#
#  D Terrett 5 November 2002
#
#  Copyright CCLRC
#-

set tcl_precision 14

# Define the root directory for locating libraries.
global ROOT
set ROOT [file dirname [info script]]
if { [string compare [file pathtype $ROOT] relative] == 0 } {
   set ROOT [pwd]/$ROOT
}

# temporat location of seq package
set auto_path [concat $ROOT/../templibs/lib $auto_path]

lappend auto_path $ROOT/lib

# Define the default location for catalogue file.
global CATALOG_DIR
set CATALOG_DIR $ROOT/pointcats

# Define the default location for storing pointing test results.
global SAVE_FILE_DIR
set SAVE_FILE_DIR /gemini/files

# The pointtest application procedures live in the pointlib subdirectory.
lappend auto_path $ROOT/pointlib

# Load the tcctime and sla extensions to tcl.
load $ROOT/lib/solaris/tcctime.so
load $ROOT/tcclib/solaris/tccext.so
load $ROOT/lib/solaris/slaext.so

package require Itcl
package require Itk
package require Iwidgets
package require Ocspkg
package require Seq

# Set the name of the epics service configuration file.
if { [info exists env(TCC_TCSNAME)] && \
         ( ! [string equal $env(TCC_TCSNAME) tcs] ) } {
   puts "Using $env(TCC_TCSNAME)"
   set ext .$env(TCC_TCSNAME)
} else {
   set ext ""
}
appData add configPath $ROOT/ca_config$ext
appData add configFile pointtest.ca

appData add appKind Tcs
appData add appName pointTest

service epics

# Set application title
wm title . "Gemini pointing test"
wm iconname . "Gemini pointing test"
wm resizable . 1 1

pointTestMain {}
