#!/bin/sh
# the next line restarts using ocswish \
exec $HLPG_INSTALL_BASE/bin/solaris/ocswish "$0" "$@"

# Define the root directory for locating libraries and applications.
global ROOT
set ROOT [file dirname [info script]]
if { [string compare [file pathtype $ROOT] relative] == 0 } {
   set ROOT [pwd]/$ROOT
}

package require Itcl
package require Itk
package require Iwidgets
package require Ocspkg

# Set the name of the epics service configuration file.
if { [info exists env(TCC_TCSNAME)] } {
   puts "Using $env(TCC_TCSNAME)"
   set ext .$env(TCC_TCSNAME)
} else {
   set ext ""
}
appData add configPath $ROOT/ca_config$ext
appData add configFile sequencer.ca

service epics

# Add the sequencer specific packages and libraries
lappend auto_path $ROOT/seqpkg
package require Seq
lappend auto_path $ROOT/seqlib

# Create a principle system object for the tcs.
seq::PrincipalSystem tcs tcsApply

# Create a principle system object for niri
seq::PrincipalSystem niri niriApply

# Create the tcs sad.
epics sa tcssad

# Create NIRI sad.
epics sa niri

# Create the user interface.
pack [SeqControl .main]

# Create haku
if { [catch {Haku haku taurus 8123}] } {
   tk_messageBox -parent .main -icon info -type ok -message \
         "Unable to connect to Haku - QUIRC/Hokuppa control disabled"
   [.main component menus].menubar.file.menu entryconfigure \
      "Load QUIRC/Hokupaa sequence..." -state disabled
}
   
# Set the Step class common data.
Step::platescale 1.611

# Create the base step object that sets the telescope back to the base
# position.
Step base -To {0.0 0.0} -Expose 0

# Create a step that moves the telescope to the start of the sequence.
Step first -To {0.0 0.0} -Expose 0

# Connect up the interface.
[.main component menus].menubar.file.menu entryconfigure Exit -command exit
[.main component menus].menubar.file.menu entryconfigure \
      "Load manual sequence..." -command {loadseq Step}
[.main component menus].menubar.file.menu entryconfigure \
      "Load QUIRC/Hokupaa sequence..." -command {loadseq HakuStep}
[.main component menus].menubar.file.menu entryconfigure \
      "Load NIRI sequence..." -command {loadseq NiriStep}
[.main component base] configure -command "Step::stop; Step::start base"
[.main component start] configure -command "Step::stop; Step::start first"
[.main component pause] configure -command Step::pause
[.main component continue] configure -command Step::start
[.main component step] configure -command Step::step
[.main component displayp] configure -textvariable Step::CurrentP
[.main component displayq] configure -textvariable Step::CurrentQ
[.main component message] configure -textvariable Step::ProgressMessage

proc loadseq {steptype} {

# Prompt for a file.
   set file [tk_getOpenFile]

   if { [string length $file] } {

# Delete the current sequence.
      if { [llength [itcl::find object sequence]] } {
         itcl::delete object sequence
      }

# Open the file
      set chanid [open $file RDONLY]

# Read in the sequence
      if { [catch {Sequence sequence $steptype $chanid \
            [.main component canvas] [.main component list]} msg] } {
         tk_messageBox -icon error -type ok -message $msg
         close $chanid
      } else {
         close $chanid
         wm title . [sequence cget -Title]

# Configure the run button to start the sequence from the first step.
         [.main component run] configure \
               -command "Step::start [sequence cget -First]"

# Update the start step to move to the start position of the sequence
         first configure -To [[sequence cget -First] cget -To]
      }
   }
}
