#!/bin/sh
# the next line restarts using ocswish \
exec $HLPG_INSTALL_BASE/bin/solaris/ocswish "$0" "$@"

#  FILENAME
#  starselect
#
#+
#  Purpose:
#  Utility plot a star catalogue and slew to a selected star.
#
#  Description:
#
#  D Terrett 21 July 2000
#
#  Copyright CCLRC
#-

set tcl_precision 14

# Define the root directory for locating libraries.
global ROOT
set ROOT [file dirname [info script]]
if { [string compare [file pathtype $ROOT] relative] == 0 } {
   set ROOT [pwd]/$ROOT
}
lappend auto_path $ROOT/lib

# Define the default location for catalogue file.
global CATALOG_DIR
set CATALOG_DIR $ROOT/pointcats

# The starselect application procedures live in the pointlib subdirectory.
lappend auto_path $ROOT/pointlib

# The Seq package is in the seqpck subdirectory
lappend auto_path seqpkg

# Load the tcctime and sla extensions to tcl.
load $ROOT/lib/solaris/tcctime.so
load $ROOT/lib/solaris/slaext.so

package require Itcl
package require Itk
package require Iwidgets
package require Ocspkg
package require Seq

# Set the name of the epics service configuration file.
if { [info exists env(TCC_TCSNAME)] } {
   puts "Using $env(TCC_TCSNAME)"
   set ext .$env(TCC_TCSNAME)
} else {
   set ext ""
}
appData add configPath $ROOT/ca_config$ext
appData add configFile starselect.ca

appData add appKind Tcs
appData add appName starSelect

service epics

# Set application title
wm title . "Gemini star selector"
wm iconname . "Gemini star selector"
wm resizable . 1 1

starSelectMain {}
