#!/bin/sh
# the next line restarts using ocswish \
exec $HLPG_INSTALL_BASE/bin/solaris/ocswish "$0" "$@"

#+
#  tsd
#
#  This script starts the Gemini telescope status display. It contains all
#  the messy stuff involved in finding the tcl packages and libraries that
#  the tsd uses. It is probably installation dependent and will need to be
#  hacked to get it to work.
#
#  D Terrett 5 December 2000
#
#  Copyright CCLRC
#-


# Define the root directory for locating libraries and extensions.
global ROOT
set ROOT [file dirname [info script]]
if { [string compare [file pathtype $ROOT] relative] == 0 } {
   set ROOT [pwd]/$ROOT
}


# The tsd library files live in the lib subdirectory of the directory 
# containing this script.
lappend auto_path $ROOT/lib
lappend auto_path $ROOT/tsdlib

# Load the tcctime, sla and tsd extensions to tcl.
load $ROOT/lib/solaris/tcctime.so
load $ROOT/tsdlib/solaris/tsdext.so
load $ROOT/lib/solaris/slaext.so

# Define images.
image create photo chile_flag -file $ROOT/lib/chile_flag-small.gif
image create photo hawaii_flag -file $ROOT/lib/hawaii_flag-small.gif

# Load all the packages required by the tsd.
package require Itcl
package require Itk
package require Iwidgets
package require Ocspkg

# Set the name of the epics service configuration file.
if { [info exists env(TCC_TCSNAME)] } {
   puts "Using $env(TCC_TCSNAME)"
   set ext .$env(TCC_TCSNAME)
} else {
   set ext ""
}
appData add configPath $ROOT/ca_config$ext
appData add configFile tsd.ca

# Load options database.
option readfile $ROOT/options userDefault

# Set the display background.
. configure -background wheat

# Start the tsd
tsdMain $argv
