#+
#  Acqcam
#
#  A Acqcam is a object for controlling the Acquisition camera/HRWFS
#
#  Options:
#           lenssel name
#           ndsel name
#           colsel name
#           window size
#           expose time
#           start nexpose
#           stop 
#
#  Methods:
#
#  D Terrett  26 October 2002
#
#  Copyright CCLRC
#+

itcl::class Acqcam {
   constructor {} {}
   public {
      method lenssel {name}
      method ndsel {name}
      method colsel {name}
      method window {size}
      method expose {time}
      method start {nexpose}
      method stop {}
   }
}

itcl::body Acqcam::constructor {} {

# Create required command senders.
   if { [catch {cs acqcam::lensSel info}] } {
      epics cs acqcam::lensSel
   }
   if { [catch {cs acqcam::ndfilterSel info}] } {
      epics cs acqcam::ndfilterSel
   }
   if { [catch {cs acqcam::clfilterSel info}] } {
      epics cs acqcam::clfilterSel
   }
   if { [catch {cs acqcam::detExposure info}] } {
      epics cs acqcam::detExposure
   }
   if { [catch {cs acqcam::detFrameSize info}] } {
      epics cs acqcam::detFrameSize
   }
   if { [catch {cs acqcam::setDhsInfo info}] } {
      epics cs acqcam::setDhsInfo
   }
   if { [catch {cs acqcam::setObserve info}] } {
      epics cs acqcam::setObserve
   }
   if { [catch {cs acqcam::observe info}] } {
      epics cs acqcam::observe
   }
   if { [catch {cs acqcam::stop info}] } {
      epics cs acqcam::stop
   }
}

itcl::body Acqcam::lenssel {name} {
   cs acqcam::lensSel set name $name
   aclogger command acqcam::lensSel
   cs acqcam::apply post
}

itcl::body Acqcam::ndsel {name} {
   cs acqcam::ndfilterSel set name $name
   aclogger command acqcam::ndfilterSel
   cs acqcam::apply post
}

itcl::body Acqcam::colsel {name} {
   cs acqcam::clfilterSel set name $name
   aclogger command acqcam::clfilterSel
   cs acqcam::apply post
}

itcl::body Acqcam::window {size} {
   cs acqcam::stop set dummy 1
   aclogger command acqcam::stop
   cs acqcam::apply postWait
   after 1000
   switch $size {
      full {
         cs acqcam::detFrameSize set binning 0
         cs acqcam::detFrameSize set windowing 0
      }
      200x200 {
         cs acqcam::detFrameSize set binning 0
         cs acqcam::detFrameSize set windowing 1
         cs acqcam::detFrameSize set x [calparam cget -acqcam_x]
         cs acqcam::detFrameSize set y [calparam cget -acqcam_y]
         cs acqcam::detFrameSize set width 200
         cs acqcam::detFrameSize set height 200
      }
      100x100 {
         cs acqcam::detFrameSize set binning 0
         cs acqcam::detFrameSize set windowing 1
         cs acqcam::detFrameSize set x [calparam cget -acqcam_x]
         cs acqcam::detFrameSize set y [calparam cget -acqcam_y]
         cs acqcam::detFrameSize set width 100
         cs acqcam::detFrameSize set height 100
      }
   }
   aclogger command acqcam::detFrameSize
   cs acqcam::apply post
}

itcl::body Acqcam::expose {time} {
   cs acqcam::stop set dummy 1
   aclogger command acqcam::stop
   cs acqcam::apply postWait
   after 10
   cs acqcam::detExposure set exposure $time
   aclogger command acqcam::detExposure
   cs acqcam::apply post
}

itcl::body Acqcam::stop {} {
   cs acqcam::stop set dummy 1
   aclogger command acqcam::stop
   cs acqcam::apply post
}

itcl::body Acqcam::start {nframe} {
   cs acqcam::stop set dummy 1
   aclogger command acqcam::stop
   cs acqcam::apply postWait
   after 10
   cs acqcam::detExposure set nframe $nframe
   aclogger command acqcam::detExposure
   cs acqcam::apply postWait
   after 10
   cs acqcam::setDhsInfo stream hrwfsScience
   cs acqcam::setDhsInfo option 2
   aclogger command acqcam::setDhsInfo
   cs acqcam::apply postWait
   after 10
   cs acqcam::setObserve output 1
   cs acqcam::setObserve dir .
   cs acqcam::setObserve file hrwfs.fits
   cs acqcam::setObserve simfile NONE
   aclogger command acqcam::setObserve
   cs acqcam::apply postWait
   after 10
   cs acqcam::observe set label NONE
   aclogger command acqcam::observe
   cs acqcam::apply post
}
