#+
# ActiveOptics
#
# An ActiveOptics object controls the state of the active optics (M2 tip/tilt,
# coma correction, M1 figure). 
#
# D Terrett  24 October 2002
#
# Copyright CLRC
#+

itcl::class ActiveOptics {
   constructor {args} {}
   public {
      method enable {}
      method disable {}
      method state {component}
      method source {component src}
      variable scssource none
      variable comacorr 0
      variable m1figure none
      variable probeguide none
      variable mountguide none
      variable pwfs1Expose 0.005
      variable pwfs1Quicklook 0
      variable pwfs1Active 0
      variable pwfs2Expose 0.005
      variable pwfs2Quicklook 0
      variable pwfs2Active 0
      variable oiwfsExpose 0.005
      variable oiwfsQuicklook 0
      variable oiwfsActive 0
   }
}

itcl::body ActiveOptics::constructor {args} {

# Create command senders.
   if { [catch {cs m1Guide info}] } {
      epics cs m1Guide
   }
   if { [catch {cs m1GuideConfig info}] } {
      epics cs m1GuideConfig
   }
   if { [catch {cs mountGuide info}] } {
      epics cs mountGuide
   }
   if { [catch {cs m2Guide info}] } {
      epics cs m2Guide
   }
   if { [catch {cs m2GuideConfig info}] } {
      epics cs m2GuideConfig
   }
   if { [catch {cs m2GuideMode info}] } {
      epics cs m2GuideMode
   }
   if { [catch {cs wfsGuideMode info}] } {
      epics cs wfsGuideMode
   }
   if { [catch {cs pwfs1Observe info}] } {
      epics cs pwfs1Observe
   }
   if { [catch {cs pwfs1StopObserve info}] } {
      epics cs pwfs1StopObserve
   }
   if { [catch {cs pwfs2Observe info}] } {
      epics cs pwfs2Observe
   }
   if { [catch {cs pwfs2StopObserve info}] } {
      epics cs pwfs2StopObserve
   }
   if { [catch {cs oiwfsObserve info}] } {
      epics cs oiwfsObserve
   }
   if { [catch {cs oiwfsStopObserve info}] } {
      epics cs oiwfsStopObserve
   }
   if { [catch {sa guideConfig info}] } {
      epics sa guideConfig
   }

   eval configure $args
}

itcl::body ActiveOptics::enable {} {

# Set parameters according to the current state...

# M2 tip/tilt is on and we want it off.
   if { $scssource == "none" } {
      if { [state m2] } {

# Turn guiding off.
         cs m2Guide set state Off
         logger command m2Guide
      }
   } else { 

# See if the current M2 source matches what we want.
      set needchange 0
      foreach source {PWFS1 PWFS2 OIWFS} {
         if { $scssource == $source } {
            if { ! [source m2 $source] } {
               set needchange 1
            }
         } else {
            if { [source m2 $source] } {
               set needchange 1
            }
         }
      }
   
      if { $needchange } {

# We need to change the setup of M2. Turn it off first.
         cs m2Guide set state Off
         logger command m2Guide
         if { [catch {cs m2Guide post} msg] } {
            tk_messageBox -icon error -message \
                  "Error posting m2Guide command: TCS reports \
                  \"$msg\""
         }

# Now set the source we want.
         cs m2GuideConfig set samplefreq 200
         cs m2GuideConfig set filter raw
         cs m2GuideConfig set freq1 ""
         cs m2GuideConfig set freq2 ""
         cs m2GuideConfig set beam A
         cs m2GuideConfig set reset On
         cs m2GuideConfig set source $scssource
         logger command m2GuideConfig
         if { [catch {cs m2GuideConfig post} msg] } {
            tk_messageBox -icon error -message \
                  "Error posting m2GuideConfig command: TCS reports \
                  \"$msg\""
         }

# This delay is needed to allow M2 to action the reset before the command
# is resent with reset = off. Maybe this won't be needed when the M2 BUSY/IDLE
# is connected.
         after 1000
         cs m2GuideConfig set reset Off
         logger command m2GuideConfig
         if { [catch {cs m2GuideConfig post} msg] } {
            tk_messageBox -icon error -message \
                  "Error posting m2GuideConfig command: TCS reports \
                  \"$msg\""
         }

# Turn guiding on.
         cs m2Guide set state On
         logger command m2Guide
      } elseif { ! [state m2] } {

# Just need to turn it on if it is off.
         cs m2Guide set state On
           logger command m2Guide
      }
   }

# Coma correction.
   if { [state coma] &&  ! $comacorr } {
      cs m2GuideMode set coma Off
      logger command m2GuideMode
   } elseif {  ! [state coma] &&  $comacorr } {
      cs m2GuideMode set coma On
      logger command m2GuideMode
   }

# Mount guide mode.
   if { [state mount] && $mountguide == "none" } {
      cs mountGuide set mode Off
      logger command mountGuide
   } elseif { $mountguide != "none" } {
      switch $mountguide {
         SCS {
             cs mountGuide set mode On
             cs mountGuide set source SCS
         }
         PWFS1 {
             cs mountGuide set mode On
             cs mountGuide set source AG
             cs mountGuide set p1weight 1.0
             cs mountGuide set p2weight 0.0
         }
         PWFS2 {
             cs mountGuide set mode On
             cs mountGuide set source AG
             cs mountGuide set p1weight 0.0
             cs mountGuide set p2weight 1.0
         }
      }
      logger command mountGuide
   }

# M1 figure.
   if { [state m1] && $m1figure == "none" } {
      cs m1Guide set mode Off
      logger command m1Guide
   } elseif { $m1figure != "none" } {
      switch $m1figure {
         PWFS1 {
             cs m1Guide set mode On
             cs m1GuideConfig set weighting none
             cs m1GuideConfig set source PWFS1
             cs m1GuideConfig set frames 1
         }
         PWFS2 {
             cs m1Guide set mode On
             cs m1GuideConfig set weighting none
             cs m1GuideConfig set source PWFS2
             cs m1GuideConfig set frames 1
         }
         OIWFS {
             cs m1Guide set mode On
             cs m1GuideConfig set weighting none
             cs m1GuideConfig set source OIWFS
             cs m1GuideConfig set frames 1
         }
      }
      logger command m1GuideConfig
      logger command m1Guide
   }

# Probe guiding.
   if { $probeguide == "none" && ( [state p1guide] || [state p2guide] ) } {
      cs wfsGuideMode set state Off
      logger command wfsGuideMode
   } elseif { $probeguide != "none" } {
      cs wfsGuideMode set state On
      cs wfsGuideMode set probe $probeguide
      logger command wfsGuideMode
   }

# Start wave-front sensors.
   foreach wfs {pwfs1 pwfs2 oiwfs} {
      if { [set ${wfs}Active] && ! [state $wfs] } {
        cs ${wfs}Observe set noexp -1
        cs ${wfs}Observe set int [set ${wfs}Expose]
         if { [set ${wfs}Quicklook] } {
            cs ${wfs}Observe set outopt DHS
            cs ${wfs}Observe set output QL
         } else {
            cs ${wfs}Observe set outopt NONE
            cs ${wfs}Observe set output ""
         }
         logger command ${wfs}Observe
      } elseif { ! [set ${wfs}Active] && [state $wfs] } {
         cs ${wfs}StopObserve set dummy 1
         logger command ${wfs}StopObserve
      }
   }

# Post the commands.
   if { [catch {cs tcsApply post} msg] } {
      tk_messageBox -icon error -message \
            "Error posting guide commands: TCS reports \
            \"$msg\""
   }
}

itcl::body ActiveOptics::disable {} {

# Stop the wave-front sensors.
   cs pwfs1StopObserve set dummy 1
   logger command pwfs1StopObserve
   cs pwfs2StopObserve set dummy 1
   logger command pwfs2StopObserve
   cs oiwfsStopObserve set dummy 1
   logger command oiwfsStopObserve

# Turn off M2.
   cs m2Guide set state Off
   logger command m2Guide
   cs m2GuideMode set coma Off
   logger command m2GuideMode

# Turn off probe guiding.
   cs wfsGuideMode set state Off
   logger command wfsGuideMode

# Turn off mount guiding.
   cs mountGuide set mode Off
   logger command mountGuide

# Turn off M1 AO
   cs m1Guide set mode Off
   logger command m1Guide

# Post the command.
   if { [catch {cs tcsApply post} msg] } {
      tk_messageBox -icon error -message \
            "Error posting guide commands: TCS reports \
            \"$msg\""
   }
}

itcl::body ActiveOptics::state {component} {

# Returns the current state of a component.

   switch $component {
      pwfs1 {
         if { [sa guideConfig get p1state value] == "Yes" } {
            return 1
         } else {
            return 0
         }
      }
      pwfs2 {
         if { [sa guideConfig get p2state value] == "Yes" } {
            return 1
         } else {
            return 0
         }
      }
      oiwfs {
         if { [sa guideConfig get oistate value] == "Yes" } {
            return 1
         } else {
            return 0
         }
      }
      p1guide {
         if { [sa guideConfig get p1guide value] == "1" } {
            return 1
         } else {
            return 0
         }
      }
      p2guide {
         if { [sa guideConfig get p2guide value] == "1" } {
            return 1
         } else {
            return 0
         }
      }
      m1 {
         if { [sa guideConfig get m1state value] == "On" } {
            return 1
         } else {
            return 0
         }
      }
      m2 {
         if { [sa guideConfig get m2state value] == "On" } {
            return 1
         } else {
            return 0
         }
      }
      mount {
         set flag [sa guideConfig get absorbtilt value]
         if { [string is integer -strict $flag] } {
            if { $flag > 0 } {
               return 1
            } else {
               return 0
            }
         } else {
            return 0
         }
      }
      coma {
         if { [sa guideConfig get coma value] == "On" } {
            return 1
         } else {
            return 0
         }
      }
   }
}

itcl::body ActiveOptics::source {component src} {

# Returns the source of input signals for the specified component.

   switch $component {
      m1 {
         if { [sa guideConfig get m1source value] == $src } {
            return 1
         }
      }
      m2 {
         if { $src == "PWFS1" && [sa guideConfig get m2p1guide] != "OFF" } {
            return 1
         }
         if { $src == "PWFS2" && [sa guideConfig get m2p2guide] != "OFF" } {
            return 1
         }
         if { $src == "OIWFS" && [sa guideConfig get m2oiguide] != "OFF" } {
            return 1
         }
      }
      mount {
         switch [sa guideConfig get absorbtilt value] {
            3 {
               if { $src == "M2" } {
                  return 1
               }
            }
            4 {
               set w [sa guideConfig get p1mweight value]
               if { [string is double -strict $w] } {
                  if { $w > 0.0 && $src == "PWFS1" } {
                     return 1
                  }
               }
               set w [sa guideConfig get p2mweight value]
               if { [string is double -strict $w] } {
                  if { $w > 0.0 && $src == "PWFS2" } {
                     return 1
                  }
               }
            }
         }
         return 0
      }
   }
   return 0
}
