#+
# Activeoptics
#
# An ActiveOptics object controls the state of the active optics (M2 tip/tilt,
# coma correction, M1 figure). 
#
# D Terrett  29 April 2004
#
# Copyright CLRC
#+

itcl::class ActiveOptics {
   constructor {args} {}
   public {
      method enable {}
      method disable {}
      method state {component}
      method source {component src {beam A}}
      variable enabled 0
      variable p1guide ""
      variable p2guide ""
      variable aoguide ""
      variable oiguide ""
      variable oiblend 0
      variable comacorr 0
      variable m1source ""
      variable m1filename ""
      variable probeguide none
      variable mountguide none
      variable gaos 0
      variable pwfs1Expose 0.01
      variable pwfs1Active 0
      variable pwfs2Expose 0.005
      variable pwfs2Active 0
      variable oiwfsExpose 0.005
      variable oiwfsActive 0
   }
}

itcl::body ActiveOptics::constructor {args} {

# Create command senders.
   if { [catch {cs m1Guide info}] } {
      epics cs m1Guide
   }
   if { [catch {cs m1GuideConfig info}] } {
      epics cs m1GuideConfig
   }
   if { [catch {cs mountGuide info}] } {
      epics cs mountGuide
   }
   if { [catch {cs m2Guide info}] } {
      epics cs m2Guide
   }
   if { [catch {cs m2GuideConfig info}] } {
      epics cs m2GuideConfig
   }
   if { [catch {cs m2GuideReset info}] } {
      epics cs m2GuideReset
   }
   if { [catch {cs m2GuideMode info}] } {
      epics cs m2GuideMode
   }
   if { [catch {cs wfsGuideMode info}] } {
      epics cs wfsGuideMode
   }
   if { [catch {cs oiwfsSelect info}] } {
      epics cs oiwfsSelect
   }
   if { [catch {cs oiwfsOut info}] } {
      epics cs oiwfsOut
   }
   if { [catch {sa guideConfig info}] } {
      epics sa guideConfig
   }

# Create GAOS command senders.
   if { [catch {cs aoFlatten info}] } {
      epics cs aoFlatten
   }
   if { [catch {cs aoCentreWfs info}] } {
      epics cs aoCentreWfs
   }
   if { [catch {cs aoCorrect info}] } {
      epics cs aoCorrect
   }
   if { [catch {cs aoOiwfsSource info}] } {
      epics cs aoOiwfsSource
   }

   eval configure $args
}

itcl::body ActiveOptics::enable {} {

# check to make sure we're not using OI probe guiding with GMOS
    if { ($probeguide == "OIWFS") && [string match "*GMOS*" $::Config(tcs.instrument,value)]} {
	tk_messageBox -icon error \
	    -message "You cannot use OIWFS probe guiding with GMOS"
	return
    }

# Set parameters according to the current state...

# Start GAOS
    if { $gaos && ![state gaos]} {
	#puts "turning GAOS On"
	# Flatten.
	cs aoFlatten set dummy 1
	logger command aoFlatten
	
	# Disable guiding.
	# Stop the wave-front sensors.
	Pwfs1 stop
	Pwfs2 stop
	Oiwfs stop
	
	# Turn off M2.
	cs m2Guide set state Off
	logger command m2Guide
	cs m2GuideMode set coma Off
	logger command m2GuideMode
	
	# Turn off probe guiding.
	cs wfsGuideMode set state Off
	logger command wfsGuideMode
	
	# Turn off mount guiding.
	cs mountGuide set mode Off
	logger command mountGuide
	
	# Turn off M1 AO
	cs m1Guide set mode Off
	logger command m1Guide
	
	# Post the command.
	if { [catch {cs tcsApply post} msg] } {
	    tk_messageBox -icon error -message \
		"Error posting guide commands: TCS reports \
            \"$msg\""
	    return
	}
	
	# Post ALTAIR correct command.
	cs aoCorrect set correct ON
	cs aoCorrect set matrix 0
	cs aoCorrect set gains 0
	logger command aoCorrect
	if { [catch {cs tcsApply post} msg] } {
            tk_messageBox -icon error -parent $itk_interior -message $msg
	}
	after 10
		
    } elseif { !$gaos && [state gaos] } {
       #puts "turning GAOS off"
       # Post ALTAIR correct command.
       cs aoCorrect set correct OFF
       logger command aoCorrect
       if { [catch {cs tcsApply post} msg] } {
	   tk_messageBox -icon error -parent $itk_interior -message $msg
       }
       after 10
       
       # Flatten.
       cs aoFlatten set dummy 1
       logger command aoFlatten
    }

    # Configure OIWFS Blending in AO
    if { $oiblend } {
       # need to ensure that OIWFS Guide Output is set to AO
#        if {[sa aossad get oiOutGuide] == "SCS"} {
# 	   puts "changing OIWFS Output to AO"
# 	   if {$oiwfsActive} { 
# 	       Oiwfs stop 
# 	       cs oiwfsOut set detSigOutput 1
# 	       cs oiwfsOut set detSigOutputDir 3
# 	       Oiwfs start -1
# 	   } else {
# 	       cs oiwfsOut set detSigOutput 1
# 	       cs oiwfsOut set detSigOutputDir 3
# 	   }
#        }
       # wait for the altair loop to settle
       # make sure correctM is Busy, otherwise it will never settle
	if {[sa aossad get correctBusy] == "BUSY"} {
	    while {[sa aossad get aoSettled] == "0"} { after 200 }   
	}
	cs aoOiwfsSource set state ON
    } else {
	# need to ensure that OIWFS Guide Output is set to SCS
#        if {[sa aossad get oiOutGuide] == "AO"} {
# 	   puts "changing OIWFS Output to SCS"
# 	   if {$oiwfsActive} { 
# 	       Oiwfs stop 
# 	       cs oiwfsOut set detSigOutput 0
# 	       cs oiwfsOut set detSigOutputDir 3
# 	       Oiwfs start -1
# 	   } else {
# 	       cs oiwfsOut set detSigOutput 0
# 	       cs oiwfsOut set detSigOutputDir 3
# 	   }
#        }
        cs aoOiwfsSource set state OFF
	cs aoOiwfsSource set bandwidth -1
   }
   logger command aoOiwfsSource

# Post the Blending Command.
# The blending command must be finished before the loops are closed.
   if { [catch {cs tcsApply post} msg] } {
      tk_messageBox -icon error -message \
            "Error posting guide commands: TCS reports \
           \"$msg\""
      return
   }

# need to wait for aoOiwfsSource to go idle
   after 500
   #puts "Oi Blend Busy: [sa aossad get oiblendBusy]"
   while {[sa aossad get oiblendBusy] == "BUSY"} { after 200 }   
   #puts "Oi Blend Busy: [sa aossad get oiblendBusy]"

# The probe guide states can either be A, B, AB or on. If it is the latter
# then we must first determine which chop states it will be active in
# according to the probe chop/nod flags and modify the state accordingly.
   foreach sa [list pwfs1Guide pwfs2Guide oiwfsGuide pwfs2Guide] \
         statevar [list m2p1guide m2p2guide m2oiguide m2aoguide] \
         state [list $p1guide $p2guide $oiguide $aoguide] {

      set $statevar ""
      if { $state eq "On" } {
         switch [sa tcssad get nodState] {
            A {
               if { [sa $sa get nodachopa] eq "On" } {
                  append $statevar A
               } 
               if { [sa $sa get nodachopb] eq "On" } {
                  append $statevar B
               } 
            }
            B {
               if { [sa $sa get nodbchopa] eq "On" } {
                  append $statevar A
               } 
               if { [sa $sa get nodbchopb] eq "On" } {
                  append $statevar B
               } 
            }
         }
      }
   }

# M2 tip/tilt is on and we want it off.
   if { $m2p1guide eq "" && $m2p2guide eq "" && $m2aoguide eq "" && \
            $m2oiguide eq "" } {
      if { [state m2] } {

# Turn guiding off.
         cs m2Guide set state Off
         logger command m2Guide
      }
   } else { 

# See if the current M2 source matches what we want.
      set needreset 0
      set addlist [list]
      foreach source [list PWFS1 PWFS2 GAOS OIWFS] \
            guide [list $m2p1guide $m2p2guide $m2aoguide $m2oiguide] {
         foreach beam [list A B] {
            if { [source m2 $source $beam] } {
               if { $guide ne $beam } {
                  set needreset 1
               }
            } else {
               if { $guide eq $beam } {
                  lappend addlist [list $source $beam]
               }
            }
         }
      }
   
      if { $needreset || [llength $addlist] != 0 } {

# We need to change the setup of M2. Turn it off first.
         cs m2Guide set state Off
         logger command m2Guide
         if { [catch {cs m2Guide post} msg] } {
            tk_messageBox -icon error -message \
                  "Error posting m2Guide command: TCS reports \
                  \"$msg\""
            return
         }

# Reset M2 if required.
         if { $needreset } {
            cs m2GuideReset set dummy 1
            logger command m2GuideReset
            if { [catch {cs m2GuideReset post} msg] } {
               tk_messageBox -icon error -message \
                     "Error posting m2GuideReset command: TCS reports \
                     \"$msg\""
               return
            }
         }

# Add the desired guide sources.
         foreach source [list PWFS1 PWFS2 GAOS OIWFS] \
                  beam [list $m2p1guide $m2p2guide $m2aoguide $m2oiguide] {
            if {$source eq "GAOS" } {
               if { $beam ne "" } {
                 cs oiwfsSelect set output AO
               } else {
                 cs oiwfsSelect set output WFS
               }
               logger command oiwfsSelect
               if { [catch { cs oiwfsSelect post} msg] } {
                 tk_messageBox -icon error -message \
                     "Error posting oiwfsSelect command: TCS reports \
                     \"$msg\""
                  return
               }
            }
            if { $beam ne "" } {
               cs m2GuideConfig set reset Off
               cs m2GuideConfig set samplefreq 200
               cs m2GuideConfig set filter raw
               cs m2GuideConfig set freq1 ""
               cs m2GuideConfig set freq2 ""
               cs m2GuideConfig set beam $beam
               cs m2GuideConfig set source $source

# A delay is needed here so that we don't over-write the inputs of the
# m2guideConfig CAD before the previous command has executed.
               after 1000
               logger command m2GuideConfig
               if { [catch {cs m2GuideConfig post} msg] } {
                  tk_messageBox -icon error -message \
                        "Error posting m2GuideConfig command: TCS reports \
                        \"$msg\""
                  return
               }
            }
         }

# Turn guiding on.
         cs m2Guide set state On
         logger command m2Guide

      } elseif { ! [state m2] } {

# Just need to turn it on if it is off.
         cs m2Guide set state On
           logger command m2Guide
      }
   }

# Coma correction.
   if { [state coma] &&  ! $comacorr } {
      cs m2GuideMode set coma Off
      logger command m2GuideMode
   } elseif {  ! [state coma] &&  $comacorr } {
      cs m2GuideMode set coma On
      logger command m2GuideMode
   }

# Mount guide mode.
   if { [state mount] && $mountguide == "none" } {
      cs mountGuide set mode Off
      logger command mountGuide
   } elseif { $mountguide != "none" } {
      switch $mountguide {
         SCS {
             cs mountGuide set mode On
             cs mountGuide set source SCS
         }
         PWFS1 {
             cs mountGuide set mode On
             cs mountGuide set source AG
             cs mountGuide set p1weight 1.0
             cs mountGuide set p2weight 0.0
         }
         PWFS2 {
             cs mountGuide set mode On
             cs mountGuide set source AG
             cs mountGuide set p1weight 0.0
             cs mountGuide set p2weight 1.0
         }
      }
      logger command mountGuide
   }

# M1 figure.
   if { [state m1] && $m1source eq "" } {
      cs m1Guide set mode Off
      logger command m1Guide
   } elseif { $m1source ne "" } {
      cs m1Guide set mode On
      cs m1GuideConfig set weighting none
      cs m1GuideConfig set frames 1
      switch $m1source {
         PWFS1 {
             cs m1GuideConfig set source PWFS1
         }
         PWFS2 {
             cs m1GuideConfig set source PWFS2
         }
         OIWFS {
             cs m1GuideConfig set source OIWFS
         }
         GAOS {
             cs m1GuideConfig set source Altair
         }
         HRWFS {
             cs m1GuideConfig set source HRWFS
             cs m1GuideConfig set filename $m1filename
         }
      }
      logger command m1GuideConfig
      logger command m1Guide
   }

# Probe guiding.
   if { $probeguide == "none" && ( [state p1guide] || [state p2guide] ) } {
      cs wfsGuideMode set state Off
      logger command wfsGuideMode
   } elseif { $probeguide != "none" } {
      cs wfsGuideMode set state On
      cs wfsGuideMode set probe $probeguide
      logger command wfsGuideMode
   }

   foreach wfs [list pwfs1 pwfs2 oiwfs] \
         active [list $pwfs1Active $pwfs2Active $oiwfsActive] \
         wfsobj [list Pwfs1 Pwfs2 Oiwfs] \
         guide [list $m2p1guide $m2p2guide $m2oiguide] {

# Stop the WFS we don't want.
      if { [state $wfs] && ! $active } {
         $wfsobj stop
      }

# Start all the active ones.
      if { $active } {

# Determine which processing mode to set the WFS to depending on whether
# or not it is being used for M2 tip/tilt & focus.
         if { $guide eq "" } {
            set mode seqnz
         } else {
            set mode seq
         }
         $wfsobj configure -exposetime [set ${wfs}Expose] \
               -mode $mode -quicklook 0
         $wfsobj start -1
      }
   }

# Post the commands.
   if { [catch {cs tcsApply post} msg] } {
      tk_messageBox -icon error -message \
            "Error posting guide commands: TCS reports \
            \"$msg\""
      return
   }

# Set the state to "enabled"
   set enabled 1
}

itcl::body ActiveOptics::disable {} {

# Turn off OI Blending in AO
#   cs aoOiwfsSource set state OFF
#   cs aoOiwfsSource set bandwidth 0
#   logger command aoOiwfsSource

# Post the Blending Command.
# The blending command must be finished before the loops are closed.
#   if { [catch {cs tcsApply post} msg] } {
#      tk_messageBox -icon error -message \
            "Error posting guide commands: TCS reports \
            \"$msg\""
#      return
#   }

# need to wait for aoOiwfsSource to go idle
#   after 500
   #puts "Oi Blend Busy: [sa aossad get oiblendBusy]"
#   while {[sa aossad get oiblendBusy] == "BUSY"} { after 200 }   
   #puts "Oi Blend Busy: [sa aossad get oiblendBusy]"

# Stop the wave-front sensors.
   Pwfs1 stop
   Pwfs2 stop
   Oiwfs stop

# Turn off M2.
   cs m2Guide set state Off
   logger command m2Guide
   cs m2GuideMode set coma Off
   logger command m2GuideMode

# Turn off probe guiding.
   cs wfsGuideMode set state Off
   logger command wfsGuideMode

# Turn off mount guiding.
   cs mountGuide set mode Off
   logger command mountGuide

# Turn off M1 AO
   cs m1Guide set mode Off
   logger command m1Guide

# need to ensure that OIWFS Guide Output is set to SCS
#    if {[sa aossad get oiOutGuide] == "AO"} {
#        puts "changing OIWFS Output to SCS"
#        cs oiwfsOut set detSigOutput 0
#        cs oiwfsOut set detSigOutputDir 3
#    }

# Post the command.
   if { [catch {cs tcsApply post} msg] } {
      tk_messageBox -icon error -message \
            "Error posting guide commands: TCS reports \
            \"$msg\""
      return
   }

# Stop GAOS
   if { [state gaos] } {
       #puts "turning GAOS off"
       # Post ALTAIR correct command.
       cs aoCorrect set correct OFF
       logger command aoCorrect
       if { [catch {cs tcsApply post} msg] } {
	   tk_messageBox -icon error -parent $itk_interior -message $msg
       }
       after 10
       
       # Flatten.
       cs aoFlatten set dummy 1
       logger command aoFlatten
   }

# Set the state to "disabled"
   set enabled 0
}

itcl::body ActiveOptics::state {component} {

# Returns the current state of a component.

   switch $component {
      pwfs1 {
         if { [sa guideConfig get p1state value] == "Yes" } {
            return 1
         } else {
            return 0
         }
      }
      pwfs2 {
         if { [sa guideConfig get p2state value] == "Yes" } {
            return 1
         } else {
            return 0
         }
      }
      oiwfs {
         if { [sa guideConfig get oistate value] == "Yes" } {
            return 1
         } else {
            return 0
         }
      }
      gaos {
         if { [sa guideConfig get aostate] == "On" } {
            return 1
         } else {
            return 0
         }
      }
      oiblend {
	  if {( [sa aossad get oiblend] == "1") || ([sa aossad get oiblend] == "ON") } {
            return 1
         } else {
            return 0
         }
      }
      p1guide {
         if { [sa guideConfig get p1guide value] == "1" } {
            return 1
         } else {
            return 0
         }
      }
      p2guide {
         if { [sa guideConfig get p2guide value] == "1" } {
            return 1
         } else {
            return 0
         }
      }
      oiguide {
         if { [sa guideConfig get oiguide value] == "1" } {
            return 1
         } else {
            return 0
         }
      }
      m1 {
         if { [sa guideConfig get m1state value] == "On" } {
            return 1
         } else {
            return 0
         }
      }
      m2 {
         if { [sa guideConfig get m2state value] == "On" } {
            return 1
         } else {
            return 0
         }
      }
      mount {
         set flag [sa guideConfig get absorbtilt value]
         if { [string is integer -strict $flag] } {
            if { $flag > 0 } {
               return 1
            } else {
               return 0
            }
         } else {
            return 0
         }
      }
      coma {
         if { [sa guideConfig get coma value] eq "On" } {
            return 1
         } else {
            return 0
         }
      }
   }
}

itcl::body ActiveOptics::source {component src {beam A}} {

# Returns the source of input signals for the specified component.

   switch $component {
      m1 {
         if { [sa guideConfig get m1source value] == $src } {
            return 1
         }
      }
      m2 {
         switch $src {
            PWFS1 {
               set guide [sa guideConfig get m2p1guide]
               if { $guide ne "OFF" && \
                     [lsearch -exact $guide ${beam}-AUTO] != -1 } {
                  return 1
               }
            }
            PWFS2 {
               set guide [sa guideConfig get m2p2guide]
               if { $guide ne "OFF" && \
                     [lsearch -exact $guide ${beam}-AUTO] != -1 } {
                  return 1
               }
            }
            OIWFS {
               set guide [sa guideConfig get m2oiguide]
               if { $guide ne "OFF" && \
                     [lsearch -exact $guide ${beam}-AUTO] != -1 } {
                  return 1
               }
            }
            GAOS {
               set guide [sa guideConfig get m2aoguide]
               if { $guide ne "OFF" && \
                     [lsearch -exact $guide ${beam}-AUTO] != -1 } {
                  return 1
               }
            }
         }
      }
      mount {
         switch [sa guideConfig get absorbtilt value] {
            3 {
               if { $src == "M2" } {
                  return 1
               }
            }
            4 {
               set w [sa guideConfig get p1mweight value]
               if { [string is double -strict $w] } {
                  if { $w > 0.0 && $src == "PWFS1" } {
                     return 1
                  }
               }
               set w [sa guideConfig get p2mweight value]
               if { [string is double -strict $w] } {
                  if { $w > 0.0 && $src == "PWFS2" } {
                     return 1
                  }
               }
            }
         }
         return 0
      }
   }
   return 0
}
