#+
#  AltairPanel <- Panel
#
#  Implements the AltairPanel widget. A Panel widget with a 
#  AltairControl widget packed into its interior.
#
#  Methods:
#           none
#
#  D Terrett 1 November 2002
#
#  Copyright CCLRC
#+

itcl::class AltairPanel {
   inherit Panel
   constructor args {}
   public {
      method sync {component name} {$itk_component(control) sync $name}
   }
}

itk::usual AltairPanel {
   keep -background -cursor
}

itcl::body AltairPanel::constructor args {

   setWidgetColors $itk_interior \
         $itk_option(-background) $itk_option(-foreground)

   itk_component add control {
      AltairControl $itk_interior.control
   } {
      usual
      rename -component -components components Components
   }
   setWidgetColors "$itk_component(menubar) $itk_component(control)" \
         $itk_option(-background) $itk_option(-foreground)

   pack $itk_component(control) -fill both -expand y

   eval itk_initialize $args
}
