#+
#  Gaos <- Paramset
#
#  Implements the Gaos class. A Gaos object stores various parameters
#  that are needed for the initial setup of GAOS when the telescope is
#  slewed.
#
#  Options:
#
#          -ndFilter     Neutral Density Filter position
#
#          -fldLens      Field Lens Position
#
#          -deployAdc    ADC position
#
#          -adjustAdc    Adjust ADC during exposure.
#
#          -gsmag        Guide star magnitude
#
#          -seeing       Seeing estimate.
#
#          -windspeed    Wind speed aloft.
#
#  Methods:
#          apply comp    Applies the Gaos configuration to the TCS by 
#                        setting the values of the command parameters.
#                        The argument is ignored.
#
#          init          Returns the Gaos object to its initial state.
#
#          save node     Saves the values of the Gaos configuration
#                        to the xml node
#
#  D Terrett 15 May 2003
#
#  Copyright CCLRC
#+

itcl::class Gaos {
   inherit Paramset
   destructor {$this init}
   public {
      method apply {comp}
      method init {}
      method save {node}
      variable adjustAdc {}
      variable deployAdc {}
      variable ndFilter {} {
	  # update the GAOS Config screen if it exists
	  #puts "setting ndFilter to $ndFilter"
	  if { [winfo exists .tcsGaosPanel.frame.control] } {
	      .tcsGaosPanel.frame.control configure -ndFilter $ndFilter
	  }
      }
      variable fldLens {} {
	  # update the GAOS Config screen if it exists
	  #puts "setting fldLens to $fldLens"
	  if { [winfo exists .tcsGaosPanel.frame.control] } {
	      .tcsGaosPanel.frame.control configure -fldLens $fldLens
	  }
      }
      variable gsmag {} {
	  # update the gsmag entry if it exists
	  if { [winfo exists .tcsGaosPanel.frame.control.chop.gsmag] } {
	      .tcsGaosPanel.frame.control.chop.gsmag clear
	      .tcsGaosPanel.frame.control.chop.gsmag insert end $gsmag
	  }
      }
      variable lgs {}
      variable seeing {}
      variable windspeed {}
   }
}

itcl::body Gaos::apply {comp} {
#puts "Gaos::apply comp: $comp name: $::Config($comp,value)"
# Don't do anything if empty or No AO"
    if { ($::Config($comp,value) == "") || ($::Config($comp,value) == "No AO") } {
	return
    }

# In order to configure GAOS we need know the Cass rotator position and
# guide start X/Y. If we are being called as part of an overall TCS
# configuration then we must predict what these are going to be using the
# Preview functions. If not, we use the current values from the telescope.
   if { [uplevel 1 \$this isa TcsConfig] } {

# Call the configuration's preview method.
      set view [Preview ::#auto]
      uplevel 1 preview $view
      $view slew 0.0

# Fetch the predictions.
      set rotpos [lindex [$view cget -rma1] 0]
      set zd [$view cget -zd]
      set xy [$view cget -p2xy]
      if { [llength $xy] == 0 } {
         error "Configuration must contain an GAOS guide star"
      }
      set x [lindex $xy 0]
      set y [lindex $xy 1]

# There is a zero point correcting that is currently applied by the TCS
# so we have to make this adjustment here as well.
      set x [expr { $x - [sa tcssad get aoXoffset] }]
      set y [expr { $y - [sa tcssad get aoYoffset] }]

# Delete the preview.
      itcl::delete object $view
   } else {
      set rotpos [sa tcssad get demandRma]
      scan [sa tcssad get demandEl] "%d:%d:%f" d m s
      set el [expr { $d + $m / 60.0 + $s / 3600 }]
      set zd [expr { 90.0 - $el }]
      set x [sa tcssad get aoDemandx]
      set y [sa tcssad get aoDemandy]
   }

# Turn on aoUseLwfs if neccesary
   if {$lgs} {
       cs aoUseLwfs set state ON
   } else {
       cs aoUseLwfs set state OFF
   }
   logger command aoUseLwfs

# Select GAOS ND filter IN/OUT 
# this writes directly to Altair ... will be replaced by tcs interface
# Update the WfsConfig in the A&G screen at the same time, if it exists
   if {[winfo exists .observePanel.frame.control.botframe.wfsconfig.tabs.canvas.notebook.cs.page5.cs.aowfs.nd]} {
       .observePanel.frame.control.botframe.wfsconfig.tabs.canvas.notebook.cs.page5.cs.aowfs.nd select $ndFilter
   } else {
       #puts "Gaos::apply setting ndfilter to $ndFilter"
       cs aoNDFilter set pos $ndFilter
       cs aoNDFilter set mode 1
       cs aoNDFilter set dir 3
   }

# Select GAOS Field Lens IN/OUT
# this writes directly to Altair ... will be replaced by tcs interface
# Update the WfsConfig in the A&G screen at the same time, if it exists

   if {[winfo exists .observePanel.frame.control.botframe.wfsconfig.tabs.canvas.notebook.cs.page5.cs.aowfs.flens]} {
       .observePanel.frame.control.botframe.wfsconfig.tabs.canvas.notebook.cs.page5.cs.aowfs.flens select $fldLens
   } else {
       #puts "Gaos::apply setting fldlens to $fldLens"
       switch $fldLens {
	   IN {
	       cs aoFLens set pos FLENS
	       cs aoFLens set mode 1
	       cs aoFLens set dir 3
	       cs aoFLens set flens 1
	       cs aoFLens set create 0
	       cs aoFLens set create 3
	   }
	   OUT {
	       cs aoFLens set pos PARK
	       cs aoFLens set mode 1
	       cs aoFLens set dir 3
	       cs aoFLens set flens 0
	       cs aoFLens set create 0
	       cs aoFLens set create 3
	   }
       }
   }

# Deploy (or not) the ADC.
   cs aoDeployAdc set position $deployAdc
   logger command aoDeployAdc

# Configure ADC.
   cs aoMoveAdc set rotpos [expr { $rotpos < 0.0 ? $rotpos + 360.0 : $rotpos }]
   cs aoMoveAdc set zd $zd
   cs aoMoveAdc set adjust $adjustAdc

# Assume that the central wavelength is always the same as the sourceA
# wavelength.
   set wavel [cs wavelSourceA get wavel]
   if { ! ( [string equal $wavel "No Value"] || [string equal $wavel ""] ) } {
      cs aoMoveAdc wavel [expr { $wavel * 1000.0 }]
   }
   logger command aoMoveAdc

# Prepare control matrix.
   cs aoPrepareCm set x $x
   cs aoPrepareCm set y $y
   cs aoPrepareCm set gsmag $gsmag
   cs aoPrepareCm set seeing $seeing
   cs aoPrepareCm set windspeed $windspeed
   logger command aoPrepareCm

# write the exposure time to the A&G screen if it exists
   switch $gsmag {
       11 -
       11.0 { set exp 0.001}
       12 -
       12.0 { set exp 0.002}
       13 -
       13.0 { set exp 0.005}
       14 -
       14.0 { set exp 0.01}
       15 -
       15.0 { set exp 0.02}
       default { set exp 0.001}
   }
   if [winfo exists .observePanel] {
       #puts "have exp: $exp"
       .observePanel.frame.control.guideloop.canv.gaos_ex clear entry
       .observePanel.frame.control.guideloop.canv.gaos_ex insert entry end $exp
   }
   AO configure -gaosExpose $exp

# Flatten the mirror.
   cs aoFlatten dummy 1
   logger command aoFlatten

# Set filter 1 to limit the speed of offsets.
   cs filter1 set shortCircuit Open
   cs filter1 set bandwidth 200
   cs filter1 set grab 0.1
   cs filter1 set maxv 2.0
   logger command filter1
}

itcl::body Gaos::save {node} {
   set node [paramset $node gaos]
   param $node adjustAdc $adjustAdc
   param $node deployAdc $deployAdc
   param $node ndFilter $ndFilter
   param $node fldLens $fldLens
   param $node lgs $lgs
   param $node gsmag $gsmag
   param $node seeing $seeing
   param $node windspeed $windspeed
}

itcl::body Gaos::init {} {
   set adjustAdc ""
   set deployAdc ""
   set gsmag ""
   set seeing ""
   set lgs ""
   set windspeed ""
   set ndFilter ""
   set fldLens ""
}
