#+
#  AoControl <- itk::Widget
#
#  An AoControl widget contains various widget for controlling the 
#  active optics control system.
#
#  Options:
#           none
#
#  Methods:
#           none
#
#  D Terrett  17 December 2002
#
#  Copyright CCLRC
#+

itcl::class AoControl {
   inherit itk::Widget
   constructor {args} {}
   destructor {}
   private {
      method centre {}
      method correct {arg}
      method loop {state}
      method onerror {msg}
      method aoenable {}
      method preparecm {}
      variable dmh 0
   }
}

itk::usual AoControl {
#   keep -cursor -font -highlightthickness -activeborderwidth -borderwidth \
#         -labelfont -popupcursor -insertborderwidth -insertofftime \
#         -insertontime -insertwidth -textfont -selectborderwidth
}

itcl::body AoControl::constructor args {

   set w $itk_interior
   itk_component add frame {
      frame $w.frame -borderwidth 2 -relief ridge
   }
   pack $itk_component(frame)
   set w $itk_component(frame)

# Label.
   itk_component add label {
      label $w.label -text ALTAIR
   }

# Flatten.
   itk_component add flatten {
      ApplyButton $w.flatten -text Flatten -command aoFlatten
   }

# Take Picture.
   itk_component add takepic {
      button $w.takepic -text "Take Picture" -state disabled
   }

# Centre WFS.
   itk_component add centre {
      LiveButton $w.centre -text "Center WFS" -command [itcl::code $this centre]
   }

# Close loop.
   itk_component add loop {
      frame $w.loop
   }
   set w $itk_component(loop)
   itk_component add dmh {
      checkbutton $w.dmh -variable [itcl::scope dmh] \
            -command [itcl::code $this aoenable]
   }
   itk_component add aom2 {
      OnOffButton $w.aom2 -text "AO + M2"  -state disabled \
            -onproc [itcl::code $this loop ON] \
            -offproc [itcl::code $this loop OFF] \
            -onvalue 1 \
            -offvalue 0 \
            -sadrecord {guideConfig aostate}
   }
   pack $itk_component(dmh) $itk_component(aom2) -side right
   set w $itk_component(frame)

# Prepare control matrix
   itk_component add prepare {
      LiveButton $w.prepare -text "Prepare Mtx" \
            -command [itcl::code $this preparecm]
   }

# Correct.
   itk_component add correct {
      OnOffButton $w.correct -text "Correct Only" \
            -onproc [itcl::code $this correct ON] \
            -offproc [itcl::code $this correct OFF] \
            -onvalue 1 \
            -offvalue 0 \
            -sadrecord {guideConfig aostate}
   }

# Create command senders.
   if { [catch {cs aoFlatten info}] } {
      epics cs aoFlatten
   }
   if { [catch {cs aoCentreWfs info}] } {
      epics cs aoCentreWfs
   }
   if { [catch {cs aoCorrect info}] } {
      epics cs aoCorrect
   }
   if { [catch {cs aoOiwfsSource info}] } {
      epics cs aoOiwfsSource
   }

   grid $itk_component(label) -padx 5 -sticky ew
   grid $itk_component(flatten) -padx 5 -sticky ew
   grid $itk_component(takepic) -padx 5 -sticky ew
   grid $itk_component(centre) -padx 5 -sticky ew
   grid $itk_component(loop) -padx 5 -sticky ew
   grid $itk_component(prepare) -padx 5 -sticky ew
   grid $itk_component(correct) -padx 5 -sticky ew

   eval itk_initialize $args
}

itcl::body AoControl::centre {} {
   preparecm
   cs aoFlatten set dummy 1
   logger command aoFlatten
   cs aoCentreWfs set retain 0
   logger command aoCentreWfs
   if { [catch {cs tcsApply post} msg] } {
      tk_messageBox -icon error -parent $itk_interior -message $msg
   }
}

itcl::body AoControl::correct {arg} {
   switch $arg {
      ON {
         cs aoCorrect set correct ON
         cs aoCorrect set matrix 0
         cs aoCorrect set gains 0
         cs aoOiwfsSource set state OFF
         logger command aoOiwfsSource
      }
      OFF {
         cs aoCorrect set correct OFF
      }
   }
   logger command aoCorrect
   if { [catch {cs tcsApply post} msg] } {
      tk_messageBox -icon error -parent $itk_interior -message $msg
   }
}

itcl::body AoControl::loop {state} {

   switch $state {
      ON {

# Flatten.
         cs aoFlatten set dummy 1
         logger command aoFlatten

# Disable guiding.
         AO disable

# Post ALTAIR correct command.
         cs aoCorrect set correct ON
         cs aoCorrect set matrix 0
         cs aoCorrect set gains 0
         logger command aoCorrect
         if { [catch {cs tcsApply post} msg] } {
            tk_messageBox -icon error -parent $itk_interior -message $msg
         }
         after 10

# OIWFS source.
         cs aoOiwfsSource set state ON
         cs aoOiwfsSource set bandwidth 0
         logger command aoOiwfsSource

# Change M2 settup to AOS.
         AO configure -scssource GAOS
      }
      OFF {

# Disable guiding.
         AO disable

# Post ALTAIR correct command.
         cs aoCorrect set correct OFF
         logger command aoCorrect
         if { [catch {cs tcsApply post} msg] } {
            tk_messageBox -icon error -parent $itk_interior -message $msg
         }
         after 10

# Flatten.
         cs aoFlatten set dummy 1
         logger command aoFlatten

# Change M2 settup to OIWFS.
         AO configure -scssource OIWFS
      }
   }

# Re-enable guiding.
   AO enable
}

itcl::body AoControl::aoenable {} {
   if { $dmh } {
      $itk_component(aom2) configure -state normal
   } else {
      $itk_component(aom2) configure -state disabled
   }
}

itcl::body AoControl::preparecm {} {
   cs aoPrepareCm set x [sa tcssad get aoDemandx]
   cs aoPrepareCm set y [sa tcssad get aoDemandy]
   logger command aoPrepareCm
}

itcl::body AoControl::onerror {msg} {
   tk_messageBox -icon error -parent $itk_interior -message \
         "Error posting commands: TCS reports \
         \"$msg\""
}

