#+
#  ApplyButton <- itk::Widget
#
#  An ApplyButton is a push button that sends a simple epics ocs command and
#  sends a message to the logger.
#
#  Options:
#           -command        The ocs command that the button posts.
#
#           -confirm        A message to display in a confirmation dialog box
#                           before posting the command. If blank, no 
#                           confirmation dialog is displayed
#
#           -parcommand     A command executed to obtain the value of each 
#                           parameter.
#
#           -text           The label for the button. Defaults to the 
#                           description string of the TCS command specified
#                           by the -command option.
#
#  Methods:
#           none
#
#  Notes:
#        o  If -parcommand option is not set, each parameter of the ocs
#           command is set the value "mark" in order to mark the CAD record.
#
#        o  If the epics command sender doesn't exist it is created.
#
#  D Terrett 5 June 2000
#
#  Copyright CCLRC
#+

itcl::class ApplyButton {
   inherit itk::Widget

   constructor args {}

   itk_option define -command command Command ""
   itk_option define -confirm confirm Confirm ""
   itk_option define -parcommand parCommand Command ""
   itk_option define -text text Text ""

   private method apply
}

itk::usual ApplyButton {
   keep -activeforeground -background -cursor -disabledforeground -font \
         -foreground -highlightcolor -highlightthickness
}

itcl::body ApplyButton::constructor args {

   itk_component add lbutton {
      LiveButton $itk_interior.lbutton -command [code $this apply]
   }

   pack $itk_component(lbutton) -fill both -expand y

   eval itk_initialize $args
}

itcl::configbody ApplyButton::command {

# Create the sender for this command if it doesn't already exist.
   if [catch {cs $itk_option(-command) info}] {
      epics cs $itk_option(-command)
   }

# Configure the -text and -logcommand options of the LiveButton.
   if { [string length $itk_option(-text)] == 0 } {
      $itk_component(lbutton) configure \
            -text [lindex [cs $itk_option(-command) info] 1]
   }
   $itk_component(lbutton) configure -logcommand $itk_option(-command)
}

itcl::configbody ApplyButton::text {
   if { [string length $itk_option(-text)] } {
      $itk_component(lbutton) configure -text $itk_option(-text)
   }
}

itcl::body ApplyButton::apply {} {

   if { [string length $itk_option(-confirm)] } {

# Display the confirmation dialog.
      if { ! [winfo exists $itk_interior.confirm] } {
         iwidgets::messagedialog $itk_interior.confirm \
               -text $itk_option(-confirm) -bitmap warning \
               -modality application -master $itk_interior
         $itk_interior.confirm hide Help
      }
      $itk_interior.confirm center
      if { [$itk_interior.confirm activate] == 0 } {
         return
      }
   }

# Set the command parameters.
   foreach par [lindex [cs $itk_option(-command) info] 3] {
      if { [string length $itk_option(-parcommand)] == 0 } {
         cs $itk_option(-command) set $par mark
      } else {
         cs $itk_option(-command) set $par \"[$itk_option(-parcommand) $par]\"
      }
   }
   if [catch {cs $itk_option(-command) post} msg] {
      error "Error posting $itk_option(-command) command: TCS reports \"$msg\""
   }
}
