#+
#  ApplyButton.itk
#
#  Implements the ApplyButton widget. A push button that applies a simple 
#  command to the TCS.
#
#  D Terrett 28 October 1998
#
#  Options:
#
#     -command
#
#        The TCS command that the button posts.
#
#     -parcommand
#
#        A command executed to obtain the value of each parameter.
#
#     -confirm
#
#        A message to display in a confirmation dialog box before sending
#        the command. If blank, no confirmation is required.
#
#     -logmessage
#
#        Text of the message sent to the logger.
#
#  Copyright CCLRC
#+

itcl::class ApplyButton {
   inherit itk::Widget

   constructor args {}

   itk_option define -command command Command {}
   itk_option define -parcommand parCommand Command {}
   itk_option define -confirm confirm Confirm {}
   itk_option define -text text Text {}

   private method apply
}

itk::usual ApplyButton {
   keep -background -cursor -foreground -font
   keep -activeforeground -disabledforeground
   keep -highlightcolor -highlightthickness
}

itcl::body ApplyButton::constructor args {

   itk_component add lbutton {
      LiveButton $itk_interior.lbutton -command [code $this apply]
   }

   pack $itk_component(lbutton) -fill both -expand y

   eval itk_initialize $args
}

itcl::configbody ApplyButton::command {
#+
# Sets the button's text to the command description returned by the epics
# command sender's info command.
#-

# Create the sender for this command if it doesn't already exist.
   if [catch {cs $itk_option(-command) info}] {
      epics cs $itk_option(-command)
   }
   if { $itk_option(-text) == "" } {
      $itk_component(lbutton) configure \
            -text [lindex [cs $itk_option(-command) info] 1]
   }
   $itk_component(lbutton) configure \
      -logmessage [lindex [cs $itk_option(-command) info] 1]
}

itcl::configbody ApplyButton::text {
   if { $itk_option(-text) != "" } {
      $itk_component(lbutton) configure -text $itk_option(-text)
   }
}

itcl::body ApplyButton::apply {} {
#+
# Invoked when the button is pressed. Posts the associated command to the TCS
# and sends the log message to the logger. If -parcommand is not set, each 
# parameter is set the value "mark" in order to mark the CAD record.
#-
   if { $itk_option(-confirm) != "" } {
      if { ! [winfo exists $itk_interior.confirm] } {
         iwidgets::messagedialog $itk_interior.confirm \
               -text $itk_option(-confirm) -bitmap warning \
               -modality application -master $itk_interior
         $itk_interior.confirm hide Help
      }
      $itk_interior.confirm center
      if { [$itk_interior.confirm activate] == 0 } {
         return
      }
   }

   foreach par [lindex [cs $itk_option(-command) info] 3] {
      if { $itk_option(-parcommand) == "" } {
         cs $itk_option(-command) set $par mark
      } else {
         cs $itk_option(-command) set $par \"[$itk_option(-parcommand) $par]\"
      }
   }
   if [catch {cs $itk_option(-command) post} msg] {
      error "Error posting $itk_option(-command) command: TCS reports \"$msg\""
   }
}
