#+
#  ChopPanel <- Panel
#
#  Implements the ChopPanel widget. A Panel widget with a 
#  ChopControl widget packed into its interior.
#
#  Methods:
#           none
#
#  D Terrett 6 March 2002
#
#  Copyright CCLRC
#+

itcl::class ChopPanel {
   inherit Panel
   constructor args {}
   public {
      method sync {component name} {$itk_component(control) sync $name}
   }
}

itk::usual ChopPanel {
   keep -background -cursor
}

itcl::body ChopPanel::constructor args {

   setWidgetColors $itk_interior \
         $itk_option(-background) $itk_option(-foreground)

   itk_component add control {
      ChopControl $itk_interior.control
   } {
      usual
      rename -component -components components Components
   }

   pack $itk_component(control) -fill both -expand y

   eval itk_initialize $args
}
