#+
#  ChopControl <- ComponentControl
#
#  A Chop control is a ComponentControl widget with widgets for the 
#  instrument position angle, coordinate system throw, frequency, duty
#  cycle, and chop source.
#
#  Options:
#           -component         The name of the component that this control
#                              edits.
#
#  D Terrett 13 June 2003
#
#  Copyright CCLRC
#+

itcl::class ChopControl {
   inherit ComponentControl
   constructor args {}
   itk_option define -component component Component {}
   public {
      method load {name}
      method reset {}
      method save {name}
   }
   private {
      method checkcosys {}
      method setdir {}
      variable refdir
   }
}

itk::usual ChopControl {
   keep -borderwidth -cursor -font -highlightthickness -insertborderwidth \
         -insertofftime -insertontime -insertwidth -labelfont -popupcursor \
         -selectborderwidth -textfont -title
}

itcl::body ChopControl::constructor args {

# Frame.
   itk_component add chop {
      frame $itk_interior.chop -bd 2 -relief ridge
   }
   pack $itk_component(chop) -fill x -expand y
   set w $itk_component(chop)

# Throw
   itk_component add throw {
      iwidgets::entryfield $w.throw \
            -labeltext [lindex [cs chopRelative info throw] 2] -width 8
   }
   pack $itk_component(throw) -anchor e -pady 4

# Entry field for angle.
   itk_component add pa {
      iwidgets::entryfield $w.pa \
            -labeltext [lindex [cs chopRelative info angle] 2] -width 8
   }
   pack $itk_component(pa) -anchor e -pady 4

# Frame for reference direction.
   itk_component add refdir {
      frame $w.refdir -bd 2 -relief ridge
   }
   pack $itk_component(refdir) -fill x -expand y

# Title
   itk_component add title {
      label $w.label -text "Reference direction"
   }
   pack $itk_component(title) -anchor w

# Radiobuttons.
   itk_component add buttons {
      frame $w.buttons
   }
   set w $itk_component(buttons)
   pack $itk_component(buttons) -fill x -expand yes
   itk_component add north {
      radiobutton $w.north -text North -variable [itcl::scope refdir] \
            -value north -command [itcl::code $this setdir]
   }
   itk_component add vertical {
      radiobutton $w.vertical -text Up -variable [itcl::scope refdir] \
            -value vertical -command [itcl::code $this setdir]
   }
   pack $itk_component(north) -side left -padx 20
   pack $itk_component(vertical) -side right -padx 40
   set w [winfo parent $w]

# Control for selecting a coordinate frame.
   itk_component add cosys {
      SubComponentSelector $w.cosys -labeltext "Coordinate system" \
            -labelpos nw -selectioncommand [itcl::code $this checkcosys]
   }
   pack $itk_component(cosys) -anchor w

# Control for frequency.
   itk_component add freq {
      iwidgets::entryfield $w.freq \
            -labeltext [lindex [cs chopConfig info frequency] 2] -width 8
   }
   pack $itk_component(freq) -anchor e -pady 4

# Control for duty cycle.
   itk_component add duty {
      iwidgets::entryfield $w.duty \
            -labeltext [lindex [cs chopConfig info dutycycle] 2] -width 8
   }
   pack $itk_component(duty) -anchor e -pady 4

# Control for sync source.
   itk_component add source {
      iwidgets::optionmenu $w.source \
            -labeltext [lindex [cs chopConfig info source] 2]
   }
   $itk_component(source) insert end SCS ICS0 ICS1 ICS2 ICS3 ICS4
   pack $itk_component(source) -anchor e -pady 4

# Sequence Closed Loop parameters
   itk_component add seqtitle {
      label $w.seqtitle -text "Sequence Closed Loop"
   }
   pack $itk_component(seqtitle) -anchor w

   # Control for average frames for AO
   itk_component add average {
      iwidgets::entryfield $w.ave \
            -labeltext "Average Frames for AO" -width 8
   }
   pack $itk_component(average) -anchor e -pady 4

   # Control for mult coeff for image rms
   itk_component add mult {
      iwidgets::entryfield $w.mult \
            -labeltext "Mult Coeff rms" -width 8
   }
   pack $itk_component(mult) -anchor e -pady 4

# Sequence Target to Mount Filter Parameters
   itk_component add mnttitle {
      label $w.mnttitle -text "Target to Mount Filter"
   }
   pack $itk_component(mnttitle) -anchor w
   # Control for A Weight
   itk_component add aweight {
      iwidgets::entryfield $w.aweight \
            -labeltext "A Weight" -width 4
   }
   pack $itk_component(aweight) -anchor e -pady 4

   # Control for B Weight
   itk_component add bweight {
      iwidgets::entryfield $w.bweight \
            -labeltext "b Weight" -width 4
   }
   pack $itk_component(bweight) -anchor e -pady 4

   # Control for Short Circuit
   itk_component add shortc {
      iwidgets::optionmenu $w.shortc \
            -labeltext "Short Circuit"
   }
   $itk_component(shortc) insert end Closed Open {One Shot} ""
   pack $itk_component(shortc) -anchor e -pady 4


# Set initial state.
   set refdir north
   set ::Config($itk_option(-component).cosys,value) FK5/J2000

# Set the object description.
   set description "chop configuration"

   eval itk_initialize $args
}

itcl::configbody ChopControl::component {
   if { $itk_option(-component) != "" } {
      $itk_component(cosys) configure -component $itk_option(-component).cosys
   }
}

itcl::body ChopControl::reset {} {
   $itk_component(throw) clear
   $itk_component(pa) clear
   $itk_component(freq) clear
   $itk_component(duty) clear
   $itk_component(source) select SCS
   $itk_component(average) clear
   $itk_component(mult) clear
   $itk_component(aweight) clear
   $itk_component(bweight) clear
   $itk_component(shortc) select ""
}

itcl::body ChopControl::load {name} {
# Copy the contents of the specified chop object into the edit
# controls.
   $itk_component(average) insert end [$name cget -average]
	$itk_component(mult) insert end [$name cget -mult]
   $itk_component(throw) insert end [$name cget -throw]
   $itk_component(pa) insert end [$name cget -angle]
   $itk_component(freq) insert end [$name cget -frequency]
   $itk_component(duty) insert end [$name cget -dutycycle]
   $itk_component(source) select [$name cget -source]
   $itk_component(aweight) insert end [$name cget -weight_a]
   $itk_component(bweight) insert end [$name cget -weight_b]
   $itk_component(shortc) select [$name cget -shortCircuit]
   set cosys [$name cget -cosys]
   if { [string equal $cosys AzEl] } {
      set refdir vertical
      set ::Config($itk_option(-component).cosys,value) ""
   } else {
      set refdir north
      if { [string is space $cosys] } {
         set ::Config($itk_option(-component).cosys,value) FK5/J2000
      } else {
         set ::Config($itk_option(-component).cosys,value) $cosys
      }
   }
   setdir
}

itcl::body ChopControl::save {name} {
   $name configure -throw [$itk_component(throw) get]
   $name configure -angle [$itk_component(pa) get]
   $name configure -frequency [$itk_component(freq) get]
   $name configure -dutycycle [$itk_component(duty) get]
   $name configure -source [$itk_component(source) get]
   $name configure -average [$itk_component(average) get]
   $name configure -mult [$itk_component(mult) get]
   $name configure -weight_a [$itk_component(aweight) get]
   $name configure -weight_b [$itk_component(bweight) get]
   $name configure -shortCircuit [$itk_component(shortc) get]

   if { [string equal $refdir north] } {
      $name configure -cosys [$itk_component(cosys) get]
   } else {
      $name configure -cosys AzEl
   }
}

itcl::body ChopControl::setdir {} {
   if { [string equal $refdir north] } {
      $itk_component(cosys) configure -state normal
   } else {
      $itk_component(cosys) configure -state disabled
   }
}

itcl::body ChopControl::checkcosys {} {
   set cosys [$itk_component(cosys) get]
   if { $cosys ne "" } {
      set frame [CosysNames::$cosys cget -frame]
      if { [string equal $frame AzEl] } {
         set refdir vertical
      } else {
         set refdir north
      }
   }
}
