#+
#  ChopPanel <- Panel
#
#  Implements the ChopPanel widget. A Panel widget with a 
#  ChopControl widget packed into its interior.
#
#  Methods:
#           none
#
#  D Terrett 28 March 2001
#
#  Copyright CCLRC
#+

itcl::class ChopPanel {
   inherit Panel
   constructor args {}
}

itk::usual ChopPanel {
   keep -background -cursor
}

itcl::body ChopPanel::constructor args {
   itk_component add control {
      ChopControl $itk_interior.control
   }
   setWidgetColors "$itk_component(menubar) $itk_component(control)" \
         $itk_option(-background) $itk_option(-foreground)

   pack $itk_component(control) -fill both -expand y

   set itk_option(-windows) $itk_component(control)

   eval itk_initialize $args
}
