#+
#  ChopPanel <- Panel
#
#  Implements the ChopPanel widget. A Panel widget with a 
#  ChopControl widget packed into its interior.
#
#  Options:
#           -componentlist - The -componentlist option of the Cosys control
#
#           -namespace -     The -namespace option of the Cosys control
#
#           -component -
#
#  Methods:
#           none
#
#  D Terrett 22 May 2000
#
#  Copyright CCLRC
#+

itcl::class ChopPanel {
   inherit Panel
   constructor args {}
   itk_option define -componentlist componentList ComponentList {}
   itk_option define -namespace namespace Namespace {}
   itk_option define -component component Component {}
}

itk::usual ChopPanel {
   keep -background -cursor
}

itcl::body ChopPanel::constructor args {
   itk_component add control {
      ChopControl $itk_interior.control
   }
   setWidgetColors "$itk_component(menubar) $itk_component(control)" \
         $itk_option(-background) $itk_option(-foreground)

   pack $itk_component(control) -fill both -expand y

   set itk_option(-windows) $itk_component(control)

   eval itk_initialize $args
}

itcl::configbody ChopPanel::componentlist {
   $itk_component(control) configure -componentlist $itk_option(-componentlist)
}

itcl::configbody ChopPanel::namespace {
   $itk_component(control) configure -namespace $itk_option(-namespace)
}
