#+
#  Chop <- Paramset
#
#  Implements the Chop class. A Chop object stores a chop configuration.
#
#  Options:
#
#          -angle        The chop position angle.
#
#          -cosys        The chop tracking frame.
#
#          -dutycycle    The duty cycle.
#
#          -frequency    The chop frequency.
#
#          -source       The chop sync source.
#
#          -throw        The chop throw.
#
#  Methods:
#          apply comp    Applies the chop configuration to the TCS by 
#                        setting the values of the command parameters.
#                        The argument is ignored.
#
#          init          Returns the chop object to its initial state.
#
#          save node     Saves the values of the chop configuration
#                        to the xml node
#
#  D Terrett 10 June 2003
#
#  Copyright CCLRC
#+

itcl::class Chop {
   inherit Paramset
   destructor {$this init}
   public {
      method apply {comp}
      method init {}
      method save {node}
      variable angle {}
      variable cosys {}
      variable dutycycle {}
      variable frequency {}
      variable source {}
      variable throw {}
   }
   private {
      variable current_cosys {}
   }
}

itcl::body Chop::apply {comp} {

# Set relative chop parameters.
   cs chopRelative set angle [list $angle]
   cs chopRelative set throw [list $throw]
   if { [string equal $cosys ""] } {
      cs chopRelative set system FK5
      cs chopRelative set equinox J2000
      logger command chopRelative
   } else {
      CosysNames::$cosys apply $comp.cosys
   }

# Set chop configuration parameters.
   cs chopConfig set type 2posn
   cs chopConfig set source [list $source]
   cs chopConfig set frequency [list $frequency]
   cs chopConfig set dutycycle [list $dutycycle]
   logger command chopConfig

# Set the source B wavelength to the same as source A.
   set wavel [cs wavelSourceA get wavel]
   if { ! ( [string equal $wavel "No Value"] || [string equal $wavel ""] ) } {
      cs wavelSourceB set wavel $wavel
      logger command wavelSourceB
   }
}

itcl::body Chop::save {node} {
   set node [paramset $node chop]
   param $node angle $angle
   param $node cosys $cosys
   param $node dutycycle $dutycycle
   param $node frequency $frequency
   param $node source $source
   param $node throw $throw
}

itcl::body Chop::init {} {
   set angle ""
   $this configure -cosys ""
   set throw ""
   set frequency ""
   set dutycycle ""
   set source ""
}

itcl::configbody Chop::cosys {
   if { ! [string equal $current_cosys ""] } {
      CosysNames::$current_cosys refdec
   }
   set current_cosys ""
   if { ! [string equal $cosys ""] } {
      if { [catch {CosysNames::$cosys refinc}] } {
         error "Coordinate frame \"$cosys\" does not exist"
      } else {
         set current_cosys $cosys
      }
   }
}
