#+
#  ChopComponent <- Chop, Component
#
#  A ChopComponent object is a Chop object that is stored in a 
#  configuration list.
#
#
#  Options:
#           none
#
#  Methods:
#           constructor list  Creates the Chop object and puts it onto
#                           "list".
#
#  D Terrett 19 September 2001
#
#  Copyright CCLRC
#+

itcl::class ChopComponent {
   inherit Component Chop
   constructor {list args} {
      Component::constructor $list
   } {
      eval configure $args
   }
}
