#+
#  Chop
#
#  Implements the Chop class. A Chop object stores a chop configuration.
#
#  Options:
#
#          -angle        The chop position angle.
#
#          -cosys        The chop tracking frame.
#
#          -dutycycle    The dutly cycle.
#
#          -frequency    The chop frequency.
#
#          -source       The chop sync source.
#
#          -throw        The chop throw.
#
#  Methods:
#          apply args    Applies the chop configuration to the TCS by 
#                        setting the values of the command parameters. Any
#                        arguments are ignored.
#
#          init          Returns the chop object to its initial state.
#
#          save file     Writes the values of the chop configuration
#                        to the channel identifier "file".
#
#  Procs:
#         subcomponents  Returns a list of the chop classes subcomponents.
#
#  D Terrett 15 March 2001
#
#  Copyright CCLRC
#+

itcl::class Chop {
   destructor {$this init}
   public proc subcomponents {}
   public {
      method apply {args}
      method init {}
      method save {file}
      variable angle {}
      variable cosys {}
      variable dutycycle {}
      variable frequency {}
      variable source {}
      variable throw {}
   }
   private {
      variable current_cosys {}
   }
}

itcl::body Chop::subcomponents {} {
   return { \
      {cosys Cosys CosysNames CosysList {Coordinate system} chop} \
   }
}

itcl::body Chop::apply args {
   cs chopRelative set angle [list $angle]
   if { [string equal $cosys ""] } {
      cs chopRelative set system FK5
      cs chopRelative set equinox J2000
   } else {
      CosysNames::$cosys apply chopRelative
   }
   cs chopRelative set throw [list $throw]
   cs chopConfig set type 2posn
   cs chopConfig set source [list $source]
   cs chopConfig set frequency [list $frequency]
   cs chopConfig set dutycycle [list $dutycycle]
   logger command chopRelative
   logger command chopConfig
}

itcl::body Chop::save file {
   puts $file "   -angle [list $angle] \\"
   puts $file "   -cosys [list $cosys] \\"
   puts $file "   -dutycycle [list $dutycycle] \\"
   puts $file "   -frequency [list $frequency] \\"
   puts $file "   -source [list $source] \\"
   puts $file "   -throw [list $throw]"
}

itcl::body Chop::init {} {
   set angle ""
   $this configure -cosys ""
   set throw ""
   set frequency ""
   set dutycycle ""
   set source ""
}

itcl::configbody Chop::cosys {
   if { ! [string equal $current_cosys ""] } {
      CosysNames::$current_cosys refdec
   }
   set current_cosys ""
   if { ! [string equal $cosys ""] } {
      if { [catch {CosysNames::$cosys refinc}] } {
         error "Coordinate frame \"$cosys\" does not exist"
      } else {
         set current_cosys $cosys
      }
   }
}
