#+
#  ComponentSelector.itk
#
#  Implements the ComponentSelector widget.
#
#  Options:
#
#     -active
#
#        The state of the active flag controlled by the checkbutton.
#
#     -componentlist
#
#        The component list that the component is selected from
#
#     -source
#
#        The source configuration of the component
#
#  D Terrett  9 September 1998
#
#  Copyright CCLRC
#+

itcl::class ComponentSelector {
   inherit itk::Widget

   constructor args {}
   destructor {}

   itk_option define -active active Active 0
   itk_option define -source source Source {}

   private method enableTrace {n1 n2 op}
   public method select name
}

itk::usual ComponentSelector {
   keep -highlightcolor -highlightthickness -selectcolor
   keep -activebackground -activeforeground -disabledforeground
   keep -background -borderwidth -cursor -foreground -highlightcolor
   keep -insertbackground -insertborderwidth
   keep -insertofftime -insertontime -insertwidth -labelfont -popupcursor
   keep -selectbackground -selectborderwidth -selectforeground
   keep -textbackground -textfont -font
}

itcl::body ComponentSelector::constructor args {

   set w $itk_interior

   itk_component add source {
      label $w.source -bd 2 -relief groove -width 10
   }

   set checkvariable ${itk_interior}._enable
   itk_component add enable {
      checkbutton $w.enable -variable $checkvariable
   }

# Set a trace on the variable to detect changes in the state of the 
# checkbutton.
   global $checkvariable
   trace variable $checkvariable w [code $this enableTrace]

   itk_component add selector {
      SubComponentSelector $w.selector
   } {
      usual
      keep -labeltext
      keep -componentlist
      keep -editcontrol
      keep -shadow
      keep -component
   }

   pack $itk_component(source) $itk_component(enable) -side left
   pack $itk_component(selector) -side right

   eval itk_initialize $args
}

itcl::body ComponentSelector::enableTrace {n1 n2 op} {
#+
# Sets the state of the active option on changes in the checkbutton variable.
#-
   upvar #0 [$itk_component(enable) cget -variable] var
   set itk_option(-active) $var
}

itcl::body ComponentSelector::select name {
#+
# Called when a component is selected in the combobox. Clears the source
# label.
#-
   $itk_component(source) configure -text ""
   set $itk_option(-source) ""
   $itk_component(selector) select $name
}

itcl::configbody ComponentSelector::active {
#+
# Sets the state of the checkbutton.
#-
   upvar #0 [$itk_component(enable) cget -variable] val
   set val $itk_option(-active)
}

itcl::configbody ComponentSelector::source {
#+
# Sets the state of the label in the source widget.
#-
   $itk_component(source) configure -text $itk_option(-source)
}
