#+
#  Component.itcl
#
#  Implements the Component class, a virtual base class for all the
#  specific configuration component classes. It provides the functionality
#  of adding itself to a componentList object when it is created and 
#  removing itself when it is deleted.
#
#  D Terrett 15 April 1998
#
#  Copyright CCLRC
#+

itcl::class Component {

   constructor list {}
   destructor {}

   protected variable componentList
}

itcl::body Component::constructor list {
   set i [expr [string last :: $this] + 2]
   $list add [string range $this $i end] end
   set componentList $list
}

itcl::body Component::destructor {} {
   set i [expr [string last :: $this] + 2]
   $componentList remove [string range $this $i end]
}
