#+
#  ComponentControl <- itk::Widget
#
#  A ComponentControl widget is a widget with controls for selecting a 
#  configuration component. This class is intended to be inherited by the 
#  panels for specific components.
#
#  Options:
#           -component      The class of component that the widget selects.
#
#           -namespace      The namespace in which the components are
#                           defined.
#
#  Methods:
#           scratchobj      Returns the name of the scratch object used by 
#                           the control.
#
#           select name     Selects the component "name".
#
#           store name      Stores the widget contents in a new or existing 
#                           component object.
#
#           subselect component subcomponent
#
#  Notes:
#        o <useful stuff>
#
#  D Terrett 3 November 1998
#
#  Copyright CCLRC
#+

itcl::class ComponentControl {
   inherit itk::Widget

   constructor args {}
   destructor {}

   itk_option define -component component Component {}
   itk_option define -namespace namespace Namespace {}

   public method scratchobj {} {return $scratchobj}
   public method select name
   public method store name
   public method subselect {component name}

   protected method apply args
   protected method delselected

   protected variable description
   protected variable objclass
   protected variable scratchobj

   private method selectioncommand
}

itk::usual ComponentControl {
   keep -activebackground -activeforeground -background -borderwidth \
         -cursor -disabledforeground -font -foreground -highlightcolor \
         -highlightthickness -insertbackground -insertborderwidth \
         -insertofftime -insertontime -insertwidth -labelfont -popupcursor \
         -selectbackground -selectborderwidth -selectforeground \
         -textbackground -textfont -title -vt
}

itcl::body ComponentControl::constructor args {

   itk_component add top {
      frame $itk_interior.top
   }
   pack $itk_component(top) -fill x -expand y
   set w $itk_component(top)

   itk_component add label {
      label $w.label -width 1
   } {
      usual
      rename -text -title title Title
   }
   bind $itk_component(label) <Configure> {%W configure -wraplength %w}
   pack $itk_component(label) -fill x -expand yes

   itk_component add delete {
      button $w.delete -bitmap delete
   }
   itk_component add selector {
      ListManager $w.selector
   } {
      usual
      keep -componentlist
   }
   pack $itk_component(delete) $itk_component(selector) -side left
   set w [winfo parent $w]
   itk_component add interior {
      frame $w.interior
   }
   pack $itk_component(interior) -fill both -expand y

# Store and apply buttons.
   itk_component add storeapply {
      StoreApply $w.storeapply -combobox $itk_component(selector) \
            -control [code $this]
   } {
      usual
      keep -shadow
   }
   pack $itk_component(storeapply) -fill x -pady 4

# Configure the selector and delete button.
   $itk_component(selector) configure \
         -selectioncommand [code $this selectioncommand]
   $itk_component(delete) configure -command [code $this delselected]

# Bind the store button action to the return key in the component selector
# combo box.
   $itk_component(selector) configure -returncommand \
         "[$itk_component(storeapply) component store] invoke"

   set itk_interior $itk_component(interior)

   eval itk_initialize $args
}

itcl::body ComponentControl::destructor {} {

# Delete the scratch object.
   delete object $scratchobj
}

itcl::body ComponentControl::select name {

# Set the selector to "name" and load its contents into the edit controls.
   $itk_component(selector) select $name
   if { [string length $name] } {
      $this selectobj $itk_option(-namespace)::$name
   } else {
      $this selectobj ""
   }
}

itcl::body ComponentControl::store name {

# Determine the full name of the object to be updated.
   if { [string length $name] } {
      set fullname ::$itk_option(-namespace)::$name
   } else {
      set fullname $scratchobj
   }

# If the object doesn't exist.
   if { [info commands $fullname] == "" } {

# Create it.
      $objclass $fullname $itk_option(-componentlist)

# Update the object with the contents of the widget, catching any errors
# due to invalid data.
      if { [catch {$this updateobj $fullname} msg] } {

# Delete the bad object and report the error.
         delete object $fullname
         $itk_component(selector) insert $name
         tk_messageBox -icon error -parent $itk_interior -message \
               "Error creating $description \"$name\": $msg"
         return 0
      }
   } else {

# Update the existing object with data from the widget.
      if { [catch {$this updateobj $fullname} msg] } {
         if { [string length $name] } {
            tk_messageBox -icon error -parent $itk_interior -message \
                  "Error updating $description \"$name\": $msg"
            return 0
         } else {
            tk_messageBox -icon error -parent $itk_interior -message \
                  "Error updating $description: $msg"
            return 0
         }
      }
   } 

# Select the new object in the shadow.
   if { [string length $name] } {
      $itk_option(-shadow) select $name
   }
   return 1
}

itcl::body ComponentControl::subselect {component name} {
   $itk_component($component) select $name
}

itcl::body ComponentControl::apply args {

# Save the values in the control in the scratch object.
   if { [store ""] } {

# Apply the object
      eval $scratchobj apply $args

# Post the command.
      if [catch {cs tcsApply post} msg] {
         error "TCS reports \"$msg\""
      }
   }
}

itcl::body ComponentControl::delselected {} {
#+
# Deletes the currently selected component object.
#-
   set name [$itk_component(selector) get]
   if { [string length $name] } {
      delete object $itk_option(-namespace)::$name
   }
}

itcl::body ComponentControl::selectioncommand {} {
#+
#  Updates the EditShadow with the new object name.
#-
   set name [$itk_component(selector) get]
   $itk_option(-shadow) select $name
}
