#+
#  ConfigComponent.itcl
#
#  Implements the ConfigComponent class. A ConfigComponent object 
#  is a TcsConfig object that is stored in a configuration list.
#
#  D Terrett 26 January 1999
#
#  Copyright CCLRC
#+

itcl::class ConfigComponent {
   inherit TcsConfig Component

   constructor {list args} {
      Component::constructor $list
   } {
      eval configure $args
   }

   public method save file
}

itcl::body ConfigComponent::save file {
   set objname [namespace tail $this]
   set namespace [info namespace qualifiers $this]
   puts $file "catch {delete object \"$namespace::$objname\"}"
   puts $file "ConfigComponent \"$namespace::$objname\"  $componentList \\"
   TcsConfig::save $file
}
