#+
#  CosysPanel <- Panel
#
#  A CosysPanel is a Panel widget with a CosysControl widget packed into 
#  its interior.
#
#  Methods:
#           none
#
#  D Terrett 6 March 2002
#
#  Copyright CCLRC
#+

itcl::class CosysPanel {
   inherit Panel
   constructor args {}
   public {
      method sync {component name} {$itk_component(control) sync $name}
   }
}

itk::usual CosysPanel {
   keep -background -cursor
}

itcl::body CosysPanel::constructor args {
   itk_component add control {
      CosysControl $itk_interior.control
   } {
      usual
      rename -component -components components Components
   }
   setWidgetColors "$itk_component(menubar) $itk_component(control)" \
         $itk_option(-background) $itk_option(-foreground)

   pack $itk_component(control) -fill both -expand y

   eval itk_initialize $args
}
