#+
#  CosysPanel <- tcclib::Panel
#
#  A CosysPanel is a Panel widget with a CosysControl widget packed into 
#  its interior.
#
#  Methods:
#           none
#
#  D Terrett 29 March 2001
#
#  Copyright CCLRC
#+

itcl::class CosysPanel {
   inherit tcclib::Panel
   constructor args {}
   itk_option define -componentlist componentList ComponentList {}
   itk_option define -namespace namespace Namespace {}
}

itk::usual CosysPanel {
   keep -background -cursor
}

itcl::body CosysPanel::constructor args {
   itk_component add control {
      CosysControl $itk_interior.control
   }
   setWidgetColors "$itk_component(menubar) $itk_component(control)" \
         $itk_option(-background) $itk_option(-foreground)

   pack $itk_component(control) -fill both -expand y

   eval itk_initialize $args
}
