#+
#  Cosys
#
#  A Cosys object stores a frame and an equinox.
#
#  Options:
#           -frame          The coordinate frame 
#
#           -equinox        The equinox of the frame
#
#  Methods:
#           apply cs        Sets the system and equinox paramters of the
#                           command sender "cs".
#
#           save file       Writes the values of the options to the file
#                           descriptor "file".
#
#  Procs:
#           subcomponents   Returns a list of the subcomponents of the 
#                           Cosys objects (an empty list).
#
#  D Terrett 22 September 1998
#
#  Copyright CCLRC
#+

itcl::class Cosys {

   public proc subcomponents {} {return {}}

   public method apply cs
   public method save file

   public variable frame {}
   public variable equinox {}
}

itcl::body Cosys::apply cs {
   cs $cs set system \"$frame\"
   cs $cs set equinox \"$equinox\"
}

itcl::body Cosys::save file {
   puts $file "   -frame \"$frame\" \\"
   puts $file "   -equinox \"$equinox\""
}
