#+
#  CosysControl <- tcclib::ComponentControl
#
#  A Cosys control is a ComponentControl widget with an optionmenu for the 
#  frame and an entryfield widget for the equinox.
#
#  Options:
#           none
#
#  Methods:
#           selectobj name  Copies the contents of the Cosys object "name"
#                           into the edit controls.
#
#           updateobj name  Stores the contents of the edit controls in the
#                           Cosys object "name".
#
#  D Terrett 28 March 2001
#
#  Copyright CCLRC
#+

itcl::class CosysControl {
   inherit tcclib::ComponentControl
   constructor args {}
   public {
      method selectobj {name}
      method updateobj {name}
   }
}

itk::usual CosysControl {
   keep -borderwidth -cursor -font -highlightthickness -insertborderwidth \
         -insertofftime -insertontime -insertwidth -labelfont -popupcursor \
         -selectborderwidth -textfont -title -applyarg -namespace -componentlist
}

itcl::body CosysControl::constructor args {

   itk_component add cframe {
      frame $itk_interior.cframe -bd 2 -relief ridge
   }
   pack $itk_component(cframe)
   set w $itk_component(cframe)

# Option menu for the frame
   itk_component add frame {
      iwidgets::optionmenu $w.frame \
            -labeltext [lindex [cs sourceA info system] 2]
   }
   $itk_component(frame) insert end FK5 FK4 Appt AzEl

# Entryfield for the equinox.
   itk_component add equinox {
      iwidgets::entryfield $w.equinox \
            -labeltext [lindex [cs sourceA info equinox] 2] \
            -width 8
   }
   pack $itk_component(frame) $itk_component(equinox) -padx 4 -pady 4

# Create the scrathc cosys object used by apply.
   set scratchobj [namespace which -command [Cosys #auto]]

# Set the object class.
   set objclass CosysComponent
   set description "Coordinate system"

   eval itk_initialize $args
}

itcl::body CosysControl::selectobj name {

# Copy the contents of the Cosys object selected in the combobox
# into the edit controls.
   $itk_component(equinox) clear

   if { ! [string equal $name ""] } {
      $itk_component(frame) select [$name cget -frame]
      $itk_component(equinox) insert end [$name cget -equinox]
   }
}

itcl::body CosysControl::updateobj name {

# Load the control with data from the named cosys object.
   $name configure -frame [$itk_component(frame) get] \
         -equinox [$itk_component(equinox) get]
}
