#+
#  CosysComponent.itcl
#
#  Implements the CosysComponent class. A CosysComponent object 
#  is a Cosys object that is stored in a configuration.
#
#  D Terrett 19 August 1999
#
#  Copyright CCLRC
#+

itcl::class CosysComponent {
   inherit Cosys Component

   constructor {list args} {
      Component::constructor $list
   } {
      eval configure $args
   }

   public method save file
}

itcl::body CosysComponent::save file {
   set objname [namespace tail $this]
   set namespace [namespace qualifiers $this]
   puts $file "catch {delete object \"${namespace}::$objname\"}"
   puts $file "CosysComponent \"${namespace}::$objname\"  $componentList \\"
   Cosys::save $file
}
