#+
#  CosysComponent <- Cosys, Component
#
#  A CosysComponent object is a Cosys object that is stored in a 
#  configuration list.
#
#
#  Options:
#           none
#
#  Methods:
#           constructor list  Creates the Cosys object and puts it onto
#                           "list".
#
#           save file       Writes commands to re-create the object to the
#                           channel identifier "file" and then calls the
#                           Cosys save method to add the objects data.
#
#  D Terrett 15 March 2001
#
#  Copyright CCLRC
#+

itcl::class CosysComponent {
   inherit Cosys Component
   constructor {list args} {
      Component::constructor $list
   } {
      eval configure $args
   }
   public {
      method save {file}
   }
}

itcl::body CosysComponent::save file {
   set obj [namespace tail $this]
   set namespace [namespace qualifiers $this]
   puts $file \
         "catch {CosysComponent [list ${namespace}::$obj]  $componentList}"
   puts $file "[list ${namespace}::$obj] init"
   puts $file "[list ${namespace}::$obj] configure \\"
   Cosys::save $file
}
