#+
#  CosysControl <- ComponentControl
#
#  A Cosys control is a ComponentControl widget with an optionmenu for the 
#  frame and an entryfield widget for the equinox.
#
#  Options:
#           none
#
#  D Terrett 14 March 2002
#
#  Copyright CCLRC
#+

itcl::class CosysControl {
   inherit ComponentControl
   constructor {args} {}
   public {
      method load {name}
      method reset {}
      method save {name}
   }
}

itk::usual CosysControl {
   keep -borderwidth -cursor -font -highlightthickness -insertborderwidth \
         -insertofftime -insertontime -insertwidth -labelfont -popupcursor \
         -selectborderwidth -textfont -title
}

itcl::body CosysControl::constructor {args} {

   itk_component add cframe {
      frame $itk_interior.cframe -bd 2 -relief ridge
   }
   pack $itk_component(cframe)
   set w $itk_component(cframe)

# Option menu for the frame
   itk_component add frame {
      iwidgets::optionmenu $w.frame \
            -labeltext [lindex [cs sourceA info system] 2]
   }
   $itk_component(frame) insert end FK5 FK4 Appt AzEl ""

# Entryfield for the equinox.
   itk_component add equinox {
      iwidgets::entryfield $w.equinox \
            -labeltext [lindex [cs sourceA info equinox] 2] \
            -width 8
   }
   pack $itk_component(frame) $itk_component(equinox) -padx 4 -pady 4

# Set the object description.
   set description "Coordinate system"

   eval itk_initialize $args
}

itcl::body CosysControl::reset {} {
   $itk_component(equinox) clear
}

itcl::body CosysControl::load {name} {
   $itk_component(frame) select [$name cget -frame]
   $itk_component(equinox) insert end [$name cget -equinox]
}

itcl::body CosysControl::save {name} {
   $name configure -frame [$itk_component(frame) get] \
         -equinox [$itk_component(equinox) get]
}
