#+
#  CrsControl <- itk::Widget
#
#  An CrsControl widget contains various widgets for controlling the 
#  mount control system.
#
#  Options:
#           none
#
#  Methods:
#           none
#
#  D Terrett  11 October 2003
#
#  Copyright CCLRC
#+

itcl::class CrsControl {
   inherit itk::Widget
   constructor args {}
   private {
      method getParVal {par}
      variable brakes
   }
}

itk::usual CrsControl {
   keep -cursor -font -highlightthickness -activeborderwidth -borderwidth \
         -labelfont -popupcursor -insertborderwidth -insertofftime \
         -insertontime -insertwidth -textfont -selectborderwidth
}

itcl::body CrsControl::constructor args {

# Divide the window into five frames
   itk_component add f1 {
      frame $itk_interior.f1 -bd 2 -relief ridge
   }
   itk_component add f2 {
      frame $itk_interior.f2 -bd 2 -relief ridge
   }
   itk_component add f3 {
      frame $itk_interior.f3 -bd 2 -relief ridge
   }
   itk_component add f4 {
      frame $itk_interior.f4 -bd 2 -relief ridge
   }
   itk_component add f5 {
      frame $itk_interior.f5 -bd 2 -relief ridge
   }
   pack $itk_component(f1) $itk_component(f2) $itk_component(f3) \
         $itk_component(f4) $itk_component(f5) -expand y -fill both

# Move command.
   set w $itk_component(f1)
   itk_component add move {
      ApplyButton $w.move -command rotMove \
            -parcommand [itcl::code $this getParVal]
   }
   pack $itk_component(move) -side left -expand y -fill x -padx 4 -pady 4

   itk_component add rma {
      iwidgets::entryfield $w.rma -labeltext Angle -width 6
   }
   pack $itk_component(rma) -side left -padx 4 -pady 4

# Tolerance control.
   set w $itk_component(f2)
   itk_component add rotTolerance {
      ApplyButton $w.rotTolerance -command rotTolerance \
            -parcommand [itcl::code $this getParVal]
   }
   itk_component add posError {
      iwidgets::entryfield $w.posError -width 5 -labeltext "Position (deg)"
   }
   itk_component add velError {
      iwidgets::entryfield $w.velError -width 5 -labeltext "Velocity (deg/s)"
   }
   pack $itk_component(rotTolerance) -expand y -fill x -padx 4 -pady 4
   pack $itk_component(posError) $itk_component(velError) -side left -pady 4

# CentreWrap, Park, Stop and Datum buttons.
   set w $itk_component(f3)
   itk_component add cenwrap {
      ApplyButton $w.cenwrap -command rotCentre
   }
   itk_component add rotpark {
      ApplyButton $w.rotpark -command rotPark
   }
   pack $itk_component(cenwrap) $itk_component(rotpark) -side left \
         -padx 4 -pady 4 -expand y -fill x
   set w $itk_component(f4)
   itk_component add rotdatum {
      ApplyButton $w.rotdatum -command rotDatum \
            -parcommand [itcl::code $this getParVal]
   }
   itk_component add device {
      iwidgets::optionmenu $w.device -labeltext Device
   }
   $itk_component(device) insert end Switch Head1 Head2 Head3 Head4
   pack $itk_component(rotdatum) $itk_component(device) -side left \
         -padx 4 -pady 4
   set w $itk_component(f5)
   itk_component add rotstop {
      ApplyButton $w.rotstop -command rotStop \
            -parcommand [itcl::code $this getParVal]
   }
   itk_component add brakes {
      checkbutton $w.brakes -onvalue Yes -offvalue No \
            -variable [itcl::scope brakes] -text brake
   }
   pack $itk_component(rotstop) -fill x -expand y -side left \
         -padx 4 -pady 4
   pack $itk_component(brakes) -side left -padx 4 -pady 4
   eval itk_initialize $args
}

itcl::body CrsControl::getParVal par {
   switch $par {
      brakes {
         return $brakes
      }
      default {
         return [$itk_component($par) get]
      }
   }
}
