#+
#  Dark
#
#  A Dark object implements a sequence of operations to take a new dark
#  (more properly called a sky) frame with one of the peripheral wave-
#  front sensors.
#
#  The steps are are follows:
#
#     1. Disable guiding.
#
#     2. Offset the WFS RA/Dec of the guide star
#
#     3. Take a WFS frame
#
#     4. Zero the offset
#
#     5. Re-enable guiding (if it was enabled at the start).
#
#  D Terrett 20 February 2004
#
#  Copyright CCLRC
#-

itcl::class Dark {
   constructor {wfs} {}
   destructor {}
   public {
      method take {} {}
   }
   private {
      method offset {}
      method expose {}
      method zero {}
      method reenable {}
      method isinposition {}
      method isexposedone {}
      variable guideenabled
      variable wfsname
      variable wfsobj
      variable seqdark
      variable disableaction
      variable offsetaction
      variable exposeaction
      variable resetaction
      variable InPosition
      variable Exposing
   }
}

itcl::body Dark::constructor {wfs} {

# Create action for disabling guiding.
   set disableaction [seq::Action #auto tcs \
      -onstart "AO disable" \
      -onok [itcl::code $this offset]]

# Create action for offsetting the probe
   set offsetaction [seq::Action #auto tcs \
      -waitvar [itcl::scope InPosition(value)] \
      -onok [itcl::code $this expose] \
      -oktest [itcl::code $this isinposition]]
   $offsetaction set targetAdjust frame 1
   $offsetaction set targetAdjust angle 0.0
   $offsetaction set targetAdjust size 60.0
   $offsetaction set targetAdjust vt -2
   switch $wfs {
      p1 {
         set wfsname pwfs1
         set wfsobj Pwfs1
      }
      p2 {
         set wfsname pwfs2
         set wfsobj Pwfs2
      }
   }

# Create action for taking the dark frame.
   set exposeaction [seq::Action #auto tcs \
      -waitvar [itcl::scope Exposing(value)] \
      -onok [itcl::code $this zero] \
      -oktest [itcl::code $this isexposedone] \
      -onstart "$wfsobj start"]

# Create action for zeroing the offset.
   set resetaction [seq::Action #auto tcs \
      -waitvar [itcl::scope InPosition(value)] \
      -onok [itcl::code $this reenable] \
      -oktest [itcl::code $this isinposition]]
   $resetaction set targetAdjust size -60.0
}

itcl::body Dark::destructor {} {
   itcl::delete object $disableaction
   itcl::delete object $offsetaction
   itcl::delete object $exposeaction
   itcl::delete object $resetaction
}

itcl::body Dark::take {} {
# Record the current state of guiding
   set guideenabled [AO cget -enabled]

# Disable guiding.
   $disableaction start
}

itcl::body Dark::offset {} {
# Link to TCS in position flag.
   sa tcssad link inPosition [itcl::scope InPosition]

# Offset probe
   $offsetaction start
   logger command targetAdjust
}
   
itcl::body Dark::expose {} {

# mbec - 9 Mar 2004
# wait some extra time to make sure the probes actually got there
#   after 1000
# Link to WFS exposing flag.
   switch $wfsname {
      pwfs1 {
         sa guideConfig link p1state [itcl::scope Exposing]
      }
      pwfs2 {
         sa guideConfig link p2state [itcl::scope Exposing]
      }
   }

# Configure the WFS object.
   $wfsobj configure -mode sky

# Take the dark.
   $exposeaction start
}

itcl::body Dark::zero {} {
# Link to TCS in position flag.
   sa tcssad link inPosition [itcl::scope InPosition]

# Reverse the probe offset.
   $resetaction start
}

itcl::body Dark::isinposition {} {
   after 2000
   set val [sa tcssad get inPosition]
   return [string equal $val TRUE]
}

itcl::body Dark::isexposedone {} {
   switch $wfsname {
      pwfs1 {
         set val [sa guideConfig get p1state]
      }
      pwfs2 {
         set val [sa guideConfig get p2state]
      }
   }
   return [string equal $val No]
}

itcl::body Dark::reenable {} {

# Set the processing mode to seq to be safe (in case someone starts an exposure
# from elsewhere which would overwrite the sky frame).
   $wfsobj configure -mode seq
   $wfsobj start 0

# Re-enable guiding if it was on when we started.
   if { $guideenabled } {
      AO enable
   }
}
