#+
#  Dark
#
#  A Dark object implements a sequence of operations to take a new dark
#  (more properly called a sky) frame with one of the peripheral wave-
#  front sensors.
#
#  The steps are are follows:
#
#     1. Disable guiding.
#
#     2. Offset the WFS RA/Dec of the guide star
#
#     3. Take a WFS frame
#
#     4. Zero the offset
#
#  D Terrett 16 January 2004
#
#  Copyright CCLRC
#-

itcl::class Dark {
   constructor {wfs} {}
   destructor {}
   public {
      method take {} {}
   }
   private {
      method offset {}
      method expose {} {}
      method zero {} {}
      method isinposition {}
      method isexposedone {}
      variable wfsname
      variable wfsobj
      variable seqdark
      variable disableaction
      variable offsetaction
      variable exposeaction
      variable InPosition
      variable Exposing
   }
}

itcl::body Dark::constructor {wfs} {

# Create action for disabling guiding.
   set disableaction [seq::Action #auto tcs \
      -onstart "AO disable" \
      -onok [itcl::code $this offset]]

# Create action for offsetting the probe
   set offsetaction [seq::Action #auto tcs \
      -waitvar [itcl::scope InPosition(value)] \
      -onok [itcl::code $this expose] \
      -oktest [itcl::code $this isinposition]]
   $offsetaction set targetAdjust frame 1
   $offsetaction set targetAdjust size 30.0
   $offsetaction set targetAdjust angle 0.0
   switch $wfs {
      p1 {
         $offsetaction set targetAdjust vt -16
         set wfsname pwfs1
         set wfsobj Pwfs1
      }
      p2 {
         $offsetaction set targetAdjust vt -32
         set wfsname pwfs2
         set wfsobj Pwfs2
      }
   }

# Create action for taking the dark frame.
   set exposeaction [seq::Action #auto tcs \
      -waitvar [itcl::scope Exposing(value)] \
      -onok [itcl::code $this zero] \
      -oktest [itcl::code $this isexposedone] \
      -onstart "$wfsobj start 1"]
}

itcl::body Dark::destructor {} {
   itcl::delete object $disableaction
   itcl::delete object $offsetaction
   itcl::delete object $exposeaction
}

itcl::body Dark::take {} {

# Disable guiding.
   $disableaction start
}

itcl::body Dark::offset {} {

# Link to TCS in position flag.
   sa tcssad link inPosition [itcl::scope InPosition]

# Offset probe
   $offsetaction start
   logger command targetAdjust
}
   
itcl::body Dark::expose {} {

# Link to WFS exposing flag.
   switch $wfsname {
      pwfs1 {
         sa guideConfig link p1state [itcl::scope Exposing]
      }
      pwfs2 {
         sa guideConfig link p2state [itcl::scope Exposing]
      }
   }

# Configure the WFS object.
   $wfsobj configure -mode sky

# Take the dark.
   $exposeaction start
}

itcl::body Dark::zero {} {

# Reverse the probe offset.
   cs targetAdjust set size -30.0
   logger command targetAdjust
   cs targetAdjust post
}

itcl::body Dark::isinposition {} {
   set val [sa tcssad get inPosition]
   return [string equal $val TRUE]
}

itcl::body Dark::isexposedone {} {
   switch $wfsname {
      pwfs1 {
         set val [sa guideConfig get p1state]
      }
      pwfs2 {
         set val [sa guideConfig get p2state]
      }
   }
   return [string equal $val No]
}
