#+
#  EcsControl.itk
#
#  Implements the EcsControl widget.
#
#  D Terrett  5 August 1998
#
#  Copyright CCLRC
#+

itcl::class EcsControl {
   inherit itk::Widget

   constructor args {}

   private method getParVal par
}

itk::usual EcsControl {
   keep -cursor -foreground -font -background
   keep -activebackground -activeforeground -disabledforeground
   keep -highlightcolor -highlightthickness
   keep -activeborderwidth -borderwidth
   keep -labelfont -popupcursor
   keep -insertborderwidth  -insertofftime -insertontime -insertwidth
   keep -textbackground -textfont -insertbackground
   keep -selectbackground -selectborderwidth -selectforeground
}

itcl::body EcsControl::constructor args {

# Divide the window into 2 vertically.
   itk_component add row1 {
      frame $itk_interior.row1
   }
   itk_component add row2 {
      frame $itk_interior.row2
   }
   pack $itk_component(row1) $itk_component(row2) -fill x -expand y

# The bottom frame has 4 frames packed 2 to a row.
   set w $itk_component(row2)
   itk_component add row2f1 {
      frame $w.row2f1 -bd 2 -relief ridge
   }
   itk_component add row2f2 {
      frame $w.row2f2 -bd 2 -relief ridge
   }
   itk_component add row3f1 {
      frame $w.row3f1 -bd 2 -relief ridge
   }
   itk_component add row3f2 {
      frame $w.row3f2 -bd 2 -relief ridge
   }
   grid $itk_component(row2f1) $itk_component(row2f2) -sticky nsew
   grid $itk_component(row3f1) $itk_component(row3f2) -sticky nsew

# Stop, Park and Datum commands.
   set w $itk_component(row1)
   itk_component add stop {
      ApplyButton $w.stop -command enclosureStop
   }
   itk_component add park {
      ApplyButton $w.park -command enclosurePark
   }
   itk_component add datum {
      ApplyButton $w.datum -command enclosureDatum
   }
   pack $itk_component(stop) $itk_component(park) \
         $itk_component(datum) -side left -fill x -expand y -padx 4 -pady 4

# Shutter control.
   set w $itk_component(row2f1)
   itk_component add shutterStop {
      ApplyButton $w.stop -command shutterStop
   }
   itk_component add shutterPark {
      ApplyButton $w.park -command shutterPark
   }
   itk_component add shutterMove {
      ApplyButton $w.shutterMove -command shutters \
            -parcommand [code $this getParVal]
   }
   itk_component add top {
      iwidgets::entryfield $w.top -width 4 \
            -labeltext [lindex [cs shutters info top] 2]
   }
   itk_component add bottom {
      iwidgets::entryfield $w.bottom -width 4 \
            -labeltext [lindex [cs shutters info bottom] 2]
   }
   pack $itk_component(shutterStop) $itk_component(shutterPark) \
         $itk_component(shutterMove) $itk_component(top) \
         $itk_component(bottom) -side top -fill x -expand y -padx 4 -pady 4

# Carousel control.
   set w $itk_component(row2f2)
   itk_component add carouselStop {
      ApplyButton $w.stop -command carouselStop
   }
   itk_component add carouselPark {
      ApplyButton $w.park -command carouselPark \
            -parcommand [code $this getParVal]
   }
   itk_component add carouselMove {
      ApplyButton $w.carouselMove -command carouselMove \
            -parcommand [code $this getParVal]
   }
   itk_component add azimuth {
      iwidgets::entryfield $w.azimuth \
         -labeltext [lindex [cs carouselPark info azimuth] 2] -width 6
   }
   itk_component add parkpos {
      iwidgets::optionmenu $w.parkpos \
            -labeltext [lindex [cs carouselPark info parkpos] 2]
   }
   $itk_component(parkpos) insert end access1 access2
   pack $itk_component(carouselStop) $itk_component(carouselPark) \
         $itk_component(carouselMove) $itk_component(azimuth) \
         $itk_component(parkpos) -side top -fill x -expand y -padx 4 -pady 4

# Vent gates control.
   set w $itk_component(row3f1)
   itk_component add ventgateStop {
      ApplyButton $w.stop -command ventgatesStop
   }
   itk_component add ventgatePark {
      ApplyButton $w.park -command ventgatesPark
   }
   itk_component add ventgateMove {
      ApplyButton $w.ventgateMove -command ventgates \
            -parcommand [code $this getParVal]
   }
   itk_component add east {
      iwidgets::entryfield $w.east \
            -labeltext [lindex [cs ventgates info east] 2] -width 10
   }
   itk_component add west {
      iwidgets::entryfield $w.west \
            -labeltext [lindex [cs ventgates info west] 2] -width 10
   }
   pack $itk_component(ventgateStop) $itk_component(ventgatePark) \
         $itk_component(ventgateMove) $itk_component(east) \
         $itk_component(west) -side top -fill x -expand y -padx 4 -pady 4

# Thermal control.
   set w $itk_component(row3f2)
   itk_component add thermal {
      ApplyButton $w.thermal -command encThermal \
            -parcommand [code $this parget]
   }
   itk_component add mode {
      iwidgets::optionmenu $w.mode \
            -labeltext [lindex [cs encThermal info mode] 2] \
   }
   $itk_component(mode) insert end Passive Active
   itk_component add setpoint {
      iwidgets::entryfield $w.setpoint \
            -labeltext [lindex [cs encThermal info setpoint] 2] -width 8
   }
   itk_component add wind {
      iwidgets::entryfield $w.wind -labelpos nw \
            -labeltext [lindex [cs encThermal info wind] 2]
   }
   pack $itk_component(thermal) $itk_component(mode) \
         $itk_component(setpoint) $itk_component(wind) -pady 4
   eval itk_initialize $args
}

itcl::body EcsControl::getParVal par {
   return [$itk_component($par) get]
}
