#+
#  EcsPanel.itk
#
#  Implements the EcsPanel widget. A Panel widget with a EcsControl
#  widget packed into its interior
#
#  D Terrett 26 April 1999
#
#  Copyright CCLRC
#+

itcl::class EcsPanel {
   inherit Panel

   constructor args {}
}

itk::usual EcsPanel {
   keep -background -cursor
}

itcl::body EcsPanel::constructor args {

# Withdraw the top level window so that we don't see geometry changes as
# we wait for sa to connect.
   set toplevel [winfo toplevel $itk_interior]
   wm withdraw $toplevel

   itk_component add control {
      EcsControl $itk_interior.control
   } {
      usual
      ignore -disabledforeground
      ignore -highlightcolor
      ignore -selectbackground
      ignore -selectforeground
      ignore -activebackground
      ignore -insertbackground
      ignore -textbackground
      ignore -activeforeground
   }
   setWidgetColors "$itk_component(menubar) $itk_component(control)" \
         $itk_option(-background) $itk_option(-foreground)

   pack $itk_component(control) -fill both -expand y

   set itk_option(-windows) $itk_component(control)

   eval itk_initialize $args

   wm deiconify $toplevel
}
