#+
#  EditPanelMgr.itcl
#
#  Implements the EditPanelMgr class. An EditPanelMgr is a PanelMgr with the
#  addition of an option for configuring the componentList that the
#  panel edits.
#
#  D Terrett 8 September 1998
#
#  Copyright CCLRC
#+

itcl::class EditPanelMgr {
   inherit PanelMgr

   constructor args {
      eval configure $args
   }

   public method map

   public variable component {}
   public variable componentlist {}
   public variable controls {}
   public variable namespace {}
   public variable vt {}
}

itcl::configbody EditPanelMgr::componentlist {
   if [winfo exists $name] {
      foreach c $componentlist {
         $name configure -componentlist $c
      }
   }
}

itcl::configbody EditPanelMgr::namespace {
   if [winfo exists $name] {
      foreach n $namespace {
         $name configure -namespace $n
      }
   }
}

itcl::configbody EditPanelMgr::component {
   if [winfo exists $name] {
      foreach n $component {
         $name configure -component $n
      }
   }
}

itcl::configbody EditPanelMgr::vt {
   if [winfo exists $name] {
      foreach n $vt {
         $name configure -vt $n
      }
   }
}


itcl::body EditPanelMgr::map {} {
   if { [$this PanelMgr::map] } {

# Configure each of the control objects that the panel contains.
      foreach control $controls l $componentlist n $namespace \
            c $component v $vt {
         $name configure -componentlist $l -namespace $n -component $c -vt $v
      }
      return 1
   }
   return 0
}
