#+
#  Field <- Paramset
#
#  Implements the Field class. A Field contains a list of targets, guide
#  and rotator configurations and an airmass limit and a gemini program
#  id.
#
#  Options:
#           -sciencetarget  The name of the science target
#
#           -pwfs1target    The name of the pwfs1 target
#
#           -pwfs2target    The name of the pwfs2 target
#
#           -oiwfstarget    The name of the oiwfs target
#
#           -altairtarget    The name of the altair target
#
#           -rotator        The name of the rotator confguration
#
#           -guide          The name of the guide configuration
#
#           -airmassLimit   The airmass limit to
#
#           -programid      Gemini Program ID
#
#           -observationid  Gemini Observation ID
#
#           -wavelength     The observing wavelength
#
#  Methods:
#          apply comp   Applies all the active components to the TCS.
#
#          init         Sets the tcs config object to its initial state.
#
#          preview      Sets all the active components in the preview.
#
#          save node    Saves the values of all the component options to
#                       the xml node.
#
#          add type name  Adds a new target or track rate.
#
#          remove type name  Removes a target or track rate
#
#          subconfigure type name  Configures a target or track rate.
#
#          subinit type name       Inits a target or track rate.
#
#          subcget type name option Gets a target or track rate option.
#
#          plot azelplot Plots the field position on an azelplot.
#
#  D Terrett 14 March 2003
#
#  Copyright CCLRC
#+

itcl::class Field {
   inherit Paramset
   constructor {args} {}
   destructor {}
   public {
      method apply {comp}
      method init {}
      method preview {view}
      method save {node}
      method add {type name args}
      method remove {type name}
      method subconfigure {type name args}
      method subinit {type name}
      method subcget {type name option}
      method plot {azelplot} {puts "plotting $this on $azelplot"}
      variable sciencetarget ""
      variable pwfs1target ""
      variable pwfs2target ""
      variable oiwfstarget ""
      variable altairtarget ""
      variable rotator ""
      variable guide ""
      variable wavelength ""
      variable programid ""
      variable observationid ""
      variable airmassLimit ""
      variable targetns
      variable targetlist
      variable trackratens
      variable trackratelist
      variable posAngle
   }
   private {
      variable current_sciencetarget ""
      variable current_pwfs1target ""
      variable current_pwfs2target ""
      variable current_oiwfstarget ""
      variable current_altairtarget ""
      variable current_guide ""
      variable current_rotator ""
      variable current_wavelength ""
   }
}

itcl::body Field::constructor {args} {

# Create the list and namespace for targets.
   set targetlist [ComponentList ${this}TargetList]
   set targetns ${this}TargetNames
   namespace eval $targetns {}

# Create the list and namespace for track rates.
   set trackratelist [ComponentList ${this}TrackRateList]
   set trackratens ${this}TrackRateNames
   namespace eval $trackratens {}

   eval configure $args
}

itcl::body Field::destructor {} {

# Set the object back to its default so that all the targets can be deleted.
   $this init

# Delete all the targets.
   set n [$targetlist length]
   set targets ""
   for {set i 0} {$i < $n} {incr i} {
      lappend targets [$targetlist get $i]
   }
   foreach name $targets {
      if { ![string equal $name ""] } {
         itcl::delete object ${targetns}::$name
      }
   }

# Delete the list and the namespace.
   itcl::delete object $targetlist
   namespace delete ${targetns}

# Repeat for the track rates.
   set n [$trackratelist length]
   set trackrates ""
   for {set i 0} {$i < $n} {incr i} {
      lappend trackrates [$trackratelist get $i]
   }
   foreach name $trackrates {
      if { ![string equal $name ""] } {
         itcl::delete object ${trackratens}::$name
      }
   }

# Delete the list and the namespace.
   itcl::delete object $trackratelist
   namespace delete $trackratens
}

itcl::body Field::apply {comp} {

# Call the apply method of all the components that have a value.
   if { ! [string equal $sciencetarget ""] } {
      ${targetns}::$sciencetarget apply $comp.sciencetarget
   }
   if { ! [string equal $pwfs1target ""] } {
      ${targetns}::$pwfs1target apply $comp.pwfs1target
   }
   if { ! [string equal $pwfs2target ""] } {
      ${targetns}::$pwfs2target apply $comp.pwfs2target
   }
   if { ! [string equal $oiwfstarget ""] } {
      ${targetns}::$oiwfstarget apply $comp.oiwfstarget
   }
   if { ! [string equal $altairtarget ""] } {
      ${targetns}::$altairtarget apply $comp.altairtarget
   }
   if { ! [string equal $guide ""] } {
      ::GuideNames::$guide apply $comp.guide
       if {[string equal $guide "OIWFS only"]} {
	   set inst $::Config(tcs.instrument,value)
	   #puts "OIWFS only, choosing oiwfs based on instrument: $inst"
	   if {[string match "*GMOS*" $inst]} {
	       #puts "found GMOS"
	       cs oiwfsSelect set oiwfs GMOS
	       logger command oiwfsSelect
	   } elseif {[string match "*NIFS*" $inst]} {
	       #puts "found NIRS"
	       cs oiwfsSelect set oiwfs NIRS
	       logger command oiwfsSelect
	   } elseif {[string match "*NIRI*" $inst]} {
	       #puts "found NIRI"
	       cs oiwfsSelect set oiwfs NIRI
	       logger command oiwfsSelect
	   } else {
	       #puts "no OIWFS"
	       cs oiwfsSelect set oiwfs None
	       logger command oiwfsSelect
	   }
       } else {
	   #puts "no OIWFS"
	   cs oiwfsSelect set oiwfs None
	   logger command oiwfsSelect
       }
   }
   if { ! [string equal $rotator ""] } {
      ::RotatorNames::$rotator apply $comp.rotator
   }
   if { ! [string equal $wavelength ""] } {
      ::WavelengthNames::$wavelength apply $comp.wavelength
   }
   if { ![string is space $airmassLimit] } {
      cs airmassLimit set limit $airmassLimit
      logger command airmassLimit
   }
   if { ![string is space $programid] } {
      ss $::env(TCC_TCSNAME):sad:programID set value [list $programid]
      ss $::env(TCC_TCSNAME):sad:programID post
   }
   if { ![string is space $observationid] } {
      ocssession obsStart $observationid
   }
}

itcl::body Field::init {} {
   $this configure -sciencetarget ""
   $this configure -pwfs1target ""
   $this configure -pwfs2target ""
   $this configure -oiwfstarget ""
   $this configure -altairtarget ""
   $this configure -guide ""
   $this configure -rotator ""
   $this configure -wavelength ""
   set programid ""
   set airmassLimit ""
}

itcl::body Field::preview {view} {

# Call the preview method of all the components that have a value.
   if { ! [string equal $sciencetarget ""] } {
      ${targetns}::$sciencetarget preview $view sourceA
   }
   if { ! [string equal $pwfs1target ""] } {
      ${targetns}::$pwfs1target preview $view pwfs1
   }
   if { ! [string equal $pwfs2target ""] } {
      ${targetns}::$pwfs2target preview $view pwfs2
   }
   if { ! [string equal $oiwfstarget ""] } {
      ${targetns}::$oiwfstarget preview $view oiwfs
   }
   if { ! [string equal $altairtarget ""] } {
      ${targetns}::$altairtarget preview $view altair
   }
   if { ! [string equal $guide ""] } {
      ::GuideNames::$guide preview $view
   }
   if { ! [string equal $rotator ""] } {
      ::RotatorNames::$rotator preview $view
   }
   if { ! [string equal $wavelength ""] } {
      ::WavelengthNames::$wavelength preview $view science
   }
}

itcl::body Field::save {node} {
   set node [paramset $node field]
   param $node sciencetarget $sciencetarget
   param $node pwfs1target $pwfs1target
   param $node pwfs2target $pwfs2target
   param $node oiwfstarget $oiwfstarget
   param $node altairtarget $altairtarget
   param $node guide $guide
   param $node rotator $rotator
   param $node wavelength $wavelength
   param $node programid $programid
   param $node airmassLimit $airmassLimit

   for {set i 0} {$i < [$targetlist length]} {incr i} {
      set target [$targetlist get $i]
      if { ! [string equal $target ""] } {
         ${targetns}::$target save $node
      }
   }
   for {set i 0} {$i < [$trackratelist length]} {incr i} {
      set trackrate [$trackratelist get $i]
      if { ! [string equal $trackrate ""] } {
         ${trackratens}::$trackrate save $node
      }
   }
}

itcl::configbody Field::sciencetarget {
   if { ! [string equal $current_sciencetarget ""] } {
      ${targetns}::$current_sciencetarget refdec
   }
   set current_sciencetarget ""
   if { ! [string equal $sciencetarget ""] } {
      if { [catch {${targetns}::$sciencetarget refinc}] } {
         error "Target \"$sciencetarget\" does not exist"
      } else {
         set current_sciencetarget $sciencetarget
      }
   }
}

itcl::configbody Field::pwfs1target {
   if { ! [string equal $current_pwfs1target ""] } {
      ${targetns}::$current_pwfs1target refdec
   }
   set current_pwfs1target ""
   if { ! [string equal $pwfs1target ""] } {
      if { [catch {${targetns}::$pwfs1target refinc}] } {
         error "Target \"$pwfs1target\" does not exist"
      } else {
         set current_pwfs1target $pwfs1target
      }
   }
}

itcl::configbody Field::pwfs2target {
   if { ! [string equal $current_pwfs2target ""] } {
      ${targetns}::$current_pwfs2target refdec
   }
   set current_pwfs2target ""
   if { ! [string equal $pwfs2target ""] } {
      if { [catch {${targetns}::$pwfs2target refinc}] } {
         error "Target \"$pwfs2target\" does not exist"
      } else {
         set current_pwfs2target $pwfs2target
      }
   }
}

itcl::configbody Field::oiwfstarget {
   if { ! [string equal $current_oiwfstarget ""] } {
      ${targetns}::$current_oiwfstarget refdec
   }
   set current_oiwfstarget ""
   if { ! [string equal $oiwfstarget ""] } {
      if { [catch {${targetns}::$oiwfstarget refinc}] } {
         error "Target \"$oiwfstarget\" does not exist"
      } else {
         set current_oiwfstarget $oiwfstarget
      }
   }
}

itcl::configbody Field::altairtarget {
   if { ! [string equal $current_altairtarget ""] } {
      ${targetns}::$current_altairtarget refdec
   }
   set current_altairtarget ""
   if { ! [string equal $altairtarget ""] } {
      if { [catch {${targetns}::$altairtarget refinc}] } {
         error "Target \"$altairtarget\" does not exist"
      } else {
         set current_altairtarget $altairtarget
      }
   }
}

itcl::configbody Field::guide {
   if { ! [string equal $current_guide ""] } {
      GuideNames::$current_guide refdec
   }
   set current_guide ""
   if { ! [string equal $guide ""] } {
      if { [catch {GuideNames::$guide refinc}] } {
         error "Guide configuration \"$guide\" does not exist"
      } else {
         set current_guide $guide
      }
   }
}

itcl::configbody Field::rotator {
   if { ! [string equal $current_rotator ""] } {
      RotatorNames::$current_rotator refdec
   }
   set current_rotator ""
   if { ! [string equal $rotator ""] } {
      if { [catch {RotatorNames::$rotator refinc}] } {
         error "Field orientation \"$rotator\" does not exist"
      } else {
         set current_rotator $rotator
      }
   }
}

itcl::configbody Field::wavelength {
   if { ! [string equal $current_wavelength ""] } {
      WavelengthNames::$current_wavelength refdec
   }
   set current_wavelength ""
   if { ! [string equal $wavelength ""] } {
      if { [catch {WavelengthNames::$wavelength refinc}] } {
         error "Wavelength definition \"$wavelength\" does not exist"
      } else {
         set current_wavelength $wavelength
      }
   }
}

itcl::body Field::add {type name args} {
   switch $type {
      target {
         set targetname [TargetComponent ${targetns}::$name $targetlist]
         $targetname configure -trackratens $trackratens
         eval [list $targetname] configure $args
         return $targetname
      }
      trackrate {
         return [eval TrackRateComponent [list ${trackratens}::$name] \
               [list $trackratelist] $args]
      }
      default {
         error "\"$type\" is not a valid field component"
      }
   }
}

itcl::body Field::subconfigure {type name args} {
   switch $type {
      target {
         eval [list ${targetns}::$name] configure $args
      }
      trackrate {
         eval [list ${trackratens}::$name] configure $args
      }
      default {
         error "\"$type\" is not a valid field component"
      }
   }
}

itcl::body Field::subinit {type name} {
   switch $type {
      target {
         ${targetns}::$name init
      }
      trackrate {
         ${trackratens}::$name init
      }
      default {
         error "\"$type\" is not a valid field component"
      }
   }
}

itcl::body Field::subcget {type name option} {
   switch $type {
      target {
         return [${targetns}::$name cget $option]
      }
      trackrate {
         return [${trackratens}::$name cget $option]
      }
      default {
         error "\"$type\" is not a valid field component"
      }
   }
}

itcl::body Field::remove {type name} {
   switch $type {
      target {
         itcl::delete object ${targetns}::$name
      }
      trackrate {
         itcl::delete object ${trackratens}::$name
      }
      default {
         error "\"$type\" is not a valid field component"
      }
   }
}

# The posAngle config body sets the rotator option, creating the rotator 
# component if there isn't one that matches the posAngle definition. The
# frame is assumed to be FK5/J2000.

itcl::configbody Field::posAngle {

# Do nothing if posAngle is empty.
   if { ! [string is space $posAngle] } {

# Construct the rotator component name.
      set rotator "$posAngle ([namespace tail $this])"
   
# See if it already exists.
      if { [lsearch -exact [itcl::find objects -class RotatorComponent] \
            ::RotatorNames::$rotator] < 0 } {

# Create it.
         RotatorComponent ::RotatorNames::$rotator ::RotatorList \
               -cosys FK5/J2000 -ipa $posAngle
      }
   }
}
