#+
#  FieldPanel <- Panel
#
#  Implements the FieldPanel widget. A Panel widget with a 
#  SciTargetControl widget and a StarSelector widget packed into its interior.
#
#  Options:
#           -components -    The -component options of the controls
#
#  Methods:
#           none
#
#  D Terrett 18 March 2002
#
#  Copyright CCLRC
#+

itcl::class FieldPanel {
   inherit Panel
   constructor args {}
   public {
      method show {component}
      method sync {component name} {
         $itk_component(control) sync component $name
      }
      method newtarget {args} {
         eval $itk_component(control) newtarget $args
      }
   }
}

itk::usual FieldPanel {
   keep -background -cursor
}

itcl::body FieldPanel::constructor args {

# Field control.
   itk_component add control {
      FieldControl $itk_interior.field -menubar $itk_component(menubar)
   } {
      usual
      rename -component -components components Components
   }
   pack $itk_component(control) -side left

# Add the StarSelectControl load and command to the File menu.
   $itk_component(menubar) insert .file.move command load \
         -command "[$itk_component(control) component starselect] load" \
         -label "Load catalog"

# Add the view and unload menus
   $itk_component(menubar) insert .file.move cascade view \
         -label "View catalog"
   $itk_component(menubar) insert .file.move cascade unload \
         -label "Unload catalog"
   $itk_component(menubar) insert .file.move separator separator

   setWidgetColors [list $itk_component(menubar) \
         $itk_component(control)] $itk_option(-background) \
         $itk_option(-foreground)

   eval itk_initialize $args
}

itcl::body FieldPanel::show {component} {
   switch $component {
      sciencetarget {
         [$itk_component(control) component targets] select Science
      }
      pwfs1target {
         [$itk_component(control) component targets] select PWFS1
      }
      pwfs2target {
         [$itk_component(control) component targets] select PWFS2
      }
      oiwfstarget {
         [$itk_component(control) component targets] select OIWFS
      }
   }
}
