#+
#  GuideLoop <- itk::Widget
#
#  A GuideLoop is a diagram of the various guiding loops with control
#  for setting them up and enabling them
#
#  Options:
#           none
#
#  Methods:
#           none
#
#  D Terrett  8 April 2002
#
#  Copyright CCLRC
#+

itcl::class GuideLoop {
   inherit itk::Widget
   constructor args {}
   destructor {}
   private {
      method recolour {args}
      method comacorr {val}
      method m1mode {val}
      method m2mode {val}
      method mtmode {val}
      method probemode {val}
      method wfsmode {wfs val}
      method enable {}
   }
}

itk::usual GuideLoop {
   keep -cursor -foreground -background
}

itcl::body GuideLoop::constructor args {

# Create canvas.
   itk_component add canv {
      canvas $itk_interior.canv -width 630 -height 497 -borderwidth 2 \
            -relief sunken
   }
   pack $itk_component(canv)
   set w $itk_component(canv)

# WFS boxes
   foreach sys {pwfs1 pwfs2 oiwfs} {
      itk_component add $sys {
         tcclib::SelectButton $w.$sys -orient vertical \
            -command [itcl::code $this wfsmode $sys]
      } {
         usual
         rename -offbackground -background background Background
      }
      $w create window 32 34 -width 60 -window $w.$sys -tags $sys
      $itk_component($sys) add ON -pady 0
      $itk_component($sys) add OFF -pady 0
      $itk_component($sys) add Q/L -pady 0
      itk_component add ${sys}_label {
         label $w.${sys}_label -text [string toupper $sys]
      }
      $w create rectangle 0 0 132 67 -fill white -tags "active ${sys} ${sys}_bg"

# WFS controls.
      itk_component add ${sys}_ex {
         iwidgets::combobox $w.${sys}_ex -arrowrelief flat -width 5 \
               -validate real -labeltext "exp(s)"
      }
      $w create window 60 80 -window $w.${sys}_ex -tag $sys
      $w.${sys}_ex insert list end 1.0 0.5 0.1 0.05 0.02 0.01 0.005
      $w.${sys}_ex insert entry end [AO cget -${sys}Expose]
      [$w.${sys}_ex component list] configure -hscrollmode none \
            -vscrollmode none
   }

# Find the name of the font used for the buttons and use it for all text.
   set font [$w.oiwfs cget -font]

   foreach sys {pwfs1 pwfs2 oiwfs} label {PWFS1 PWFS2 OIWFS} {
      $w create text 92 35 -text $label -tags $sys -font $font
   }

# M1, M2 and Mount boxes.
   $w create rectangle 0 0 132 89 -fill white -tags "active m2 m2_bg"
   $w create text 32 65 -text M2 -tags m2 -font $font
   $w create rectangle 0 0 132 89 -fill white -tags "active m1 m1_bg"
   $w create text 92 45 -text "M1 FIG" -tags m1 -font $font
   $w create rectangle 0 0 132 89 -fill white -tags "active mount mount_bg"
   $w create text 92 44 -text MOUNT -tags mount -font $font

# Controls for M1.
   itk_component add m1 {
      tcclib::SelectButton $w.m1 -orient vertical \
            -command [itcl::code $this m1mode]
   } {
      usual
      rename -offbackground -background background Background
   }
   $w create window 32 44 -width 60 -window $w.m1 -tags m1
   $itk_component(m1) add OFF -pady 0
   $itk_component(m1) add P1 -pady 0
   $itk_component(m1) add P2 -pady 0
   $itk_component(m1) add OIWFS -pady 0

# Controls for M2
   itk_component add m2 {
      tcclib::SelectButton $w.m2 -orient vertical \
            -command [itcl::code $this m2mode]
   } {
      usual
      rename -offbackground -background background Background
   }
   $w create window 102 45 -width 60 -window $itk_component(m2) -tags m2
   $itk_component(m2) add P1 -pady 0
   $itk_component(m2) add P2 -pady 0
   $itk_component(m2) add OIWFS -pady 0
   $itk_component(m2) add OFF -pady 0
   itk_component add m2coma {
      tcclib::SelectButton $w.m2coma -orient vertical \
            -command [itcl::code $this comacorr]
   } {
      usual
      rename -offbackground -background background Background
   }
   $w create window 32 24 -width 60 -window $itk_component(m2coma) -tags m2
   $itk_component(m2coma) add COMA -pady 0
   $itk_component(m2coma) add OFF -pady 0

# Controls for Mount.
   itk_component add mt {
      tcclib::SelectButton $w.mt -orient vertical \
            -command [itcl::code $this mtmode]
   } {
      usual
      rename -offbackground -background background Background
   }
   $w create window 32 45 -width 60 -window $itk_component(mt) -tags mount
   $itk_component(mt) add M2 -pady 0
   $itk_component(mt) add P1 -pady 0
   $itk_component(mt) add P2 -pady 0
   $itk_component(mt) add OFF -pady 0

# Box for WFS probes.
   $w create rectangle 0 0 132 67 -fill white -tags "active probes probes_bg"
   $w create text 92 35 -text PROBES -tags probes -font $font

# Controls for probes.
   itk_component add pr {
      tcclib::SelectButton $w.pr -orient vertical \
            -command [itcl::code $this probemode]
   } {
      usual
      rename -offbackground -background background Background
   }
   $w create window 32 34 -width 60 -window $w.pr -tags probes
   $itk_component(pr) add P1 -pady 0
   $itk_component(pr) add P2 -pady 0
   $itk_component(pr) add OFF -pady 0

# Move boxes into position.
   $w move m2 250 10
   $w move m1 250 115
   $w move pwfs1 50 222
   $w move oiwfs 250 222
   $w move pwfs2 450 222
   $w move probes 250 322
   $w move mount 250 402

# PWFS to M1
   $w create line 150 223 150 160 252 160 -width 3 -fill white \
         -tags {active pwfs1_m1} -arrow last -arrowshape {20 20 7}
   $w create line 381 242 410 242 410 140 381 140 -width 3 -fill white \
         -tags {active oiwfs_m1} -arrow last -arrowshape {20 20 7}
   $w create line 530 223 530 180 381 180 -width 3 -fill white \
         -tags {active pwfs2_m1} -arrow last -arrowshape {20 20 7}

# WFS to M2
   $w create line 100 223 100  60 252  60 -width 3 -fill white \
         -tags {active pwfs1_m2} -arrow last -arrowshape {20 20 7}
   $w create line 381 262 430 262 430  60 381  60 -width 3 -fill white \
         -tags {act1ve oiwfs_m2} -arrow last -arrowshape {20 20 7}
   $w create line 582 237 610 237 610  40 381  40 -width 3 -fill white \
         -tags {active pwfs2_m2} -arrow last -arrowshape {20 20 7}

# WFS to Probes
   $w create line 182 242 220 242 220 352 251 352 -width 3 -fill white \
         -tags {active pwfs1_pr} -arrow last -arrowshape {20 20 7}
   $w create line 582 272 590 272 590 352 381 352 -width 3 -fill white \
         -tags {active pwfs2_pr} -arrow last -arrowshape {20 20 7}

# PWFS to mount
   $w create line 182 262 200 262 200 422 251 422 -width 3 -fill white \
         -tags {active pwfs1_mt} -arrow last -arrowshape {20 20 7}
   $w create line 582 255 610 255 610 422 381 422 -width 3 -fill white \
         -tags {active pwfs2_mt} -arrow last -arrowshape {20 20 7}

# M2 to mount
   $w create line 252  40  20  40  20 442 251 442 -width 3 -fill white \
         -tags {active m2_mt} -arrow last -arrowshape {20 20 7}

# ENABLE/DISABLE buttons.
   itk_component add on {
      tcclib::LiveButton $w.on -text ENABLE -command [itcl::code $this enable]
   }
   itk_component add off {
      tcclib::LiveButton $w.off -text DISABLE -command {AO disable}
   }
   $w create window 450 462 -window $itk_component(on)
   $w create window 550 462 -window $itk_component(off)

# Monitor the guide states
   foreach rec {p1state p2state oistate m2state absorbtilt m1state \
         m1source p1guide p1guide p1mweight p2mweight} {
      sa guideConfig proc $rec [itcl::code $this recolour]
   }

# Schedule an update once the channels have connected.
   after 1000 [itcl::code $this recolour]

   eval itk_initialize $args
}

itcl::body GuideLoop::destructor {} {
   foreach rec {p1state p2state oistate m2state absorbtilt m1state \
         wfsstate wfsprobe} {
      sa guideConfig unproc $rec [itcl::code $this recolour]
   }
}

body GuideLoop::recolour args {

   set w $itk_component(canv)

# Assume no signal to mount
   set mount 0

# Set everything to white.
   $w itemconfigure active -fill white

# P1 signals.
   if { [AO state pwfs1] } {
      $w itemconfigure pwfs1_bg -fill green
      if { [AO state m1] && [AO source m1 PWFS1] } {
         $w itemconfigure pwfs1_m1 -fill green
      } else {
         $w itemconfigure pwfs1_m1 -fill yellow
      }
      if { [AO state m2] && [AO source m2 PWFS1] } {
         $w itemconfigure pwfs1_m2 -fill green
      } else {
         $w itemconfigure pwfs1_m2 -fill yellow
      }
      if { [AO state p1guide] } {
         $w itemconfigure pwfs1_pr -fill green
      } else {
         $w itemconfigure pwfs1_pr -fill yellow
      }
      if { [AO state mount] && [AO source mount PWFS1] } {
         $w itemconfigure pwfs1_mt -fill green
         set mount 1
      } else {
         $w itemconfigure pwfs1_mt -fill yellow
      }
   }

# P2 signals
   if { [AO state pwfs2] } {
      $w itemconfigure pwfs2_bg -fill green
      if { [AO state m1] && [AO source m1 PWFS2] } {
         $w itemconfigure pwfs2_m1 -fill green
      } else {
         $w itemconfigure pwfs2_m1 -fill yellow
      }
      if { [AO state m2] && [AO source m2 PWFS2] } {
         $w itemconfigure pwfs2_m2 -fill green
      } else {
         $w itemconfigure pwfs2_m2 -fill yellow
      }
      if { [AO state p2guide] } {
         $w itemconfigure pwfs2_pr -fill green
      } else {
         $w itemconfigure pwfs2_pr -fill yellow
      }
      if { [AO state mount] && [AO source mount PWFS2] } {
         $w itemconfigure pwfs2_mt -fill green
         set mount 1
      } else {
         $w itemconfigure pwfs2_mt -fill yellow
      }
   }

# OIWFS signals
   if { [AO state oiwfs] } {
      $w itemconfigure oiwfs_bg -fill green
      if { [AO state m1] && [AO source m1 OIWFS] } {
         $w itemconfigure oiwfs_m1 -fill green
      } else {
         $w itemconfigure oiwfs_m1 -fill yellow
      }
      if { [AO state m2] && [AO source m2 OIWFS] } {
         $w itemconfigure oiwfs_m2 -fill green
      } else {
         $w itemconfigure oiwfs_m2 -fill yellow
      }
      if { [AO state mount] && [AO source mount OIWFS] } {
         $w itemconfigure oiwfs_mt -fill green
      } else {
         $w itemconfigure oiwfs_mt -fill yellow
      }
   }

# M1
   if { [AO state m1] } {
      if { ( [AO source m1 PWFS1] && [AO state pwfs1] ) ||
            ( [AO source m1 PWFS2] && [AO state pwfs2] ) ||
            ( [AO source m1 OIWFS] && [AO state oiwfs] ) } {
         $w itemconfigure m1_bg -fill green
      } else {
         $w itemconfigure m1_bg -fill yellow
      }
   }

# M2
   if { [AO state m2] } {
      if { ( [AO source m2 PWFS1]  && [AO state pwfs1] ) ||
            ( [AO source m2 PWFS2] && [AO state pwfs2] ) ||
            ( [AO source m2 OIWFS] && [AO state oiwfs] ) } {
         $w itemconfigure m2_bg -fill green
         if { [AO source mount M2] && [AO state mount] } {
            $w itemconfigure m2_mt -fill green
            set mount 1
         } else {
            $w itemconfigure m2_mt -fill yellow
         }
      } else {
         $w itemconfigure m2_bg -fill yellow
         $w itemconfigure m2_mt -fill yellow
      }
   }

# Mount
   if { [AO state mount] } {
      if { $mount } {
         $w itemconfigure mount_bg -fill green
      } else {
         $w itemconfigure mount_bg -fill yellow
      }
   }

# WFS probes
   if { ( [AO state p1guide] && [AO state pwfs1] ) ||
         ( [AO state p2guide] && [AO state pwfs2] ) } {
      $w itemconfigure probes_bg -fill green
   } elseif { [AO state p1guide] || [AO state p2guide] } {
      $w itemconfigure probes_bg -fill yellow
   }
}

itcl::body GuideLoop::comacorr {val} {
   switch $val {
      COMA {
         AO configure -comacorr 1
      }
      OFF {
         AO configure -comacorr 0
      }
   }
}

itcl::body GuideLoop::m2mode {val} {
   switch $val {
      P1 {
         AO configure -scssource PWFS1
      }
      P2 {
         AO configure -scssource PWFS2
      }
      OIWFS {
         AO configure -scssource OIWFS
      }
      OFF {
         AO configure -scssource none
      }
   }
}

itcl::body GuideLoop::m1mode {val} {
   switch $val {
      OFF {
         AO configure -m1figure none
      }
      P1 {
         AO configure -m1figure PWFS1
      }
      P2 {
         AO configure -m1figure PWFS2
      }
      OIWFS {
         AO configure -m1figure OIWFS
      }
   }
}

itcl::body GuideLoop::mtmode {val} {
   switch $val {
      P1 {
         AO configure -mountguide PWFS1
      }
      P2 {
         AO configure -mountguide PWFS2
      }
      M2 {
         AO configure -mountguide SCS
      }
      OFF {
         AO configure -mountguide none
      }
   }
}

itcl::body GuideLoop::probemode {val} {
   switch $val {
      P1 {
         AO configure -probeguide PWFS1
      }
      P2 {
         AO configure -probeguide PWFS2
      }
      OFF {
         AO configure -probeguide none
      }
   }
}

itcl::body GuideLoop::wfsmode {wfs val} {
   switch $val {
      ON {
         AO configure -${wfs}Active 1
         AO configure -${wfs}Quicklook 0
      }
      Q/L {
         AO configure -${wfs}Active 1
         AO configure -${wfs}Quicklook 1
      }
      OFF {
         AO configure -${wfs}Active 0
      }
   }
}

itcl::body GuideLoop::enable {} {
   AO configure -pwfs1Expose [$itk_component(pwfs1_ex) get]
   AO configure -pwfs2Expose [$itk_component(pwfs2_ex) get]
   AO configure -oiwfsExpose [$itk_component(oiwfs_ex) get]
   AO enable
}
