#+
#  GuideLoop <- itk::Widget
#
#  A GuideLoop is a diagram of the various guiding loops with control
#  for setting them up and enabling them
#
#  Options:
#           none
#
#  Methods:
#           none
#
#  D Terrett  29 April 2004
#
#  Copyright CCLRC
#+

itcl::class GuideLoop {
   inherit itk::Widget
   constructor args {}
   destructor {}
   public {
      method reset {}
   }
   private {
      method recolour {args}
      method comacorr {val}
      method m2mode {probe val}
      method mtmode {val}
      method probemode {val}
      method wfsmode {wfs val}
      method enable {}
      method m1mode {state}
      variable monids
   }
}

itk::usual GuideLoop {
   keep -cursor -foreground -background
}

itcl::body GuideLoop::constructor args {

# Create canvas.
   itk_component add canv {
#AWE      canvas $itk_interior.canv -width 630 -height 497 -borderwidth 2 
      canvas $itk_interior.canv -width 630 -height 455 -borderwidth 2 \
            -relief sunken
   }
   pack $itk_component(canv)
   set w $itk_component(canv)

# WFS boxes
   foreach sys {pwfs1 pwfs2 oiwfs} {
      itk_component add $sys {
         SelectButton $w.$sys -orient vertical \
            -command [itcl::code $this wfsmode $sys]
      } {
         usual
         rename -offbackground -background background Background
      }
      $w create window 32 24 -width 60 -window $w.$sys -tags $sys
      $itk_component($sys) add ON -pady 0
      $itk_component($sys) add OFF -pady 0
      itk_component add ${sys}_label {
         label $w.${sys}_label -text [string toupper $sys]
      }
      $w create rectangle 0 0 132 67 -fill white -tags "active ${sys} ${sys}_bg"

# WFS controls.
      itk_component add ${sys}_ex {
         iwidgets::combobox $w.${sys}_ex -arrowrelief flat -width 5 \
               -validate real -labeltext "exp(s)"
      }
      $w create window 62 55 -window $w.${sys}_ex -tag $sys
      $w.${sys}_ex insert list end 1.0 0.5 0.1 0.05 0.02 0.01 0.005
      $w.${sys}_ex insert entry end [AO cget -${sys}Expose]
      [$w.${sys}_ex component list] configure -hscrollmode none \
            -vscrollmode none
   }

# Find the name of the font used for the buttons and use it for all text.
   set font [$w.oiwfs cget -font]

   foreach sys {pwfs1 pwfs2 oiwfs} label {PWFS1 PWFS2 OIWFS} {
      $w create text 92 25 -text $label -tags $sys -font $font
   }

# GAOS
   $w create rectangle 0 0 62 67 -fill white -tags "active gaos gaos_bg"
   $w create text 32 33 -text GAOS -tags gaos -font $font

# M1, M2 and Mount boxes.
   $w create rectangle 0 0 200 89 -fill white -tags "active m2 m2_bg"
   $w create text 168 15 -text M2 -tags m2 -font $font
   $w create text 168 35 -text TIP/TILT -tags m2 -font $font
   $w create text 168 55 -text FOCUS -tags m2 -font $font
   $w create rectangle 0 0 84 89 -fill white -tags "active m2xy m2xy_bg"
   $w create text 42 15 -text "M2 COMA" -tags m2xy -font $font
   $w create rectangle 0 0 132 109 -fill white -tags "active m1 m1_bg"
   $w create text 92 45 -text M1 -tags m1 -font $font
   $w create text 92 65 -text FIGURE -tags m1 -font $font
#AWE   $w create rectangle 0 0 132 89 -fill white -tags "active mount mount_bg"
   $w create rectangle 0 23 132 66 -fill white -tags "active mount mount_bg"
   $w create text 92 44 -text MOUNT -tags mount -font $font

# Controls for M1.
   itk_component add m1src {
      SelectButton $w.m1src -orient vertical \
            -command [itcl::code $this m1mode]
   } {
      usual
      rename -offbackground -background background Background
   }
   $w create window 32 55 -width 60 -window $w.m1src -tags m1
   $itk_component(m1src) add PWFS1 -pady 0
   $itk_component(m1src) add PWFS2 -pady 0
   $itk_component(m1src) add OIWFS -pady 0
   $itk_component(m1src) add GAOS -pady 0
   $itk_component(m1src) add OFF -pady 0

# Controls for M2
   itk_component add m2p1 {
      SelectButton $w.m2p1 -orient horizontal \
            -command [itcl::code $this m2mode p1]
   } {
      usual
      rename -offbackground -background background Background
   }
   $w create text 12 12 -text P1 -tags m2 -font $font
   $w create window 80 12 -width 110 -window $itk_component(m2p1) -tags m2
   $itk_component(m2p1) add ON -pady 0 -padx 0
   $itk_component(m2p1) add OFF -pady 0 -padx 0

   itk_component add m2p2 {
      SelectButton $w.m2p2 -orient horizontal \
            -command [itcl::code $this m2mode p2]
   } {
      usual
      rename -offbackground -background background Background
   }
   $w create text 12 34 -text P2 -tags m2 -font $font
   $w create window 80 34 -width 110 -window $itk_component(m2p2) -tags m2
   $itk_component(m2p2) add ON -pady 0 -padx 0
   $itk_component(m2p2) add OFF -pady 0 -padx 0

   itk_component add m2ao {
      SelectButton $w.m2ao -orient horizontal \
            -command [itcl::code $this m2mode ao]
   } {
      usual
      rename -offbackground -background background Background
   }
   $w create text 12 56 -text AO -tags m2 -font $font
   $w create window 80 56 -width 110 -window $itk_component(m2ao) -tags m2
   $itk_component(m2ao) add ON -pady 0 -padx 0
   $itk_component(m2ao) add OFF -pady 0 -padx 0

   itk_component add m2oi {
      SelectButton $w.m2oi -orient horizontal \
            -command [itcl::code $this m2mode oi]
   } {
      usual
      rename -offbackground -background background Background
   }
   $w create text 12 78 -text OI -tags m2 -font $font
   $w create window 80 78 -width 110 -window $itk_component(m2oi) -tags m2
#AWE   $itk_component(m2oi) add A -pady 0 -padx 0
#AWE   $itk_component(m2oi) add B -pady 0 -padx 0
   $itk_component(m2oi) add ON -pady 0 -padx 0
   $itk_component(m2oi) add OFF -pady 0 -padx 0

   itk_component add m2coma {
      SelectButton $w.m2coma -orient vertical \
            -command [itcl::code $this comacorr]
   } {
      usual
      rename -offbackground -background background Background
   }
   $w create window 42 54 -width 60 -window $itk_component(m2coma) -tags m2xy
   $itk_component(m2coma) add ON -pady 0
   $itk_component(m2coma) add OFF -pady 0

# Controls for Mount.
   itk_component add mt {
      SelectButton $w.mt -orient vertical \
            -command [itcl::code $this mtmode]
   } {
      usual
      rename -offbackground -background background Background
   }
   $w create window 32 45 -width 60 -window $itk_component(mt) -tags mount
   $itk_component(mt) add M2 -pady 0
#   $itk_component(mt) add P1 -pady 0
#   $itk_component(mt) add P2 -pady 0
   $itk_component(mt) add OFF -pady 0

# Box for WFS probes.
   $w create rectangle 0 0 132 67 -fill white -tags "active probes probes_bg"
   $w create text 92 35 -text PROBES -tags probes -font $font

# Controls for probes.
   itk_component add pr {
      SelectButton $w.pr -orient vertical \
            -command [itcl::code $this probemode]
   } {
      usual
      rename -offbackground -background background Background
   }
   $w create window 32 34 -width 60 -window $w.pr -tags probes
   $itk_component(pr) add P1 -pady 0
   $itk_component(pr) add P2 -pady 0
   $itk_component(pr) add OFF -pady 0

# Move boxes into position.
   $w move m2 182 10
   $w move m2xy 70 80
   $w move m1 250 115
   $w move gaos 500 90
   $w move pwfs1 50 242
   $w move oiwfs 250 242
   $w move pwfs2 450 242
   $w move probes 250 322
#AWE   $w move mount 250 402
   $w move mount 250 380

# PWFS to M1
   $w create line 170 243 170 180 252 180 -width 3 -fill white \
         -tags {active pwfs1_m1} -arrow last -arrowshape {20 20 7}
   $w create line 381 262 410 262 410 160 381 160 -width 3 -fill white \
         -tags {active oiwfs_m1} -arrow last -arrowshape {20 20 7}
   $w create line 530 243 530 190 381 190 -width 3 -fill white \
         -tags {active pwfs2_m1} -arrow last -arrowshape {20 20 7}
   $w create line 501 130 381 130 -width 3 -fill white \
         -tags {active gaos_m1} -arrow last -arrowshape {20 20 7}

# WFS to M2
   $w create line 60 243 60  60 183  60 -width 3 -fill white \
         -tags {active pwfs1_m2} -arrow last -arrowshape {20 20 7}
   $w create line  120 243  120 168 -width 3 -fill white \
         -tags {active pwfs1_m2xy} -arrow last -arrowshape {20 20 7}
   $w create line 381 282 430 282 430  88 381  88 -width 3 -fill white \
         -tags {active oiwfs_m2} -arrow last -arrowshape {20 20 7}
   $w create line 582 257 610 257 610  44 381  44 -width 3 -fill white \
         -tags {active pwfs2_m2} -arrow last -arrowshape {20 20 7}
   $w create line 530 91 530 65 381 65  -width 3 -fill white \
         -tags {active gaos_m2} -arrow last -arrowshape {20 20 7}
   $w create line 501 107 152 107 -width 3 -fill white \
         -tags {active gaos_m2xy} -arrow last -arrowshape {20 20 7}

# WFS to Probes
   $w create line 182 262 220 262 220 352 251 352 -width 3 -fill white \
         -tags {active pwfs1_pr} -arrow last -arrowshape {20 20 7}
   $w create line 582 292 590 292 590 352 381 352 -width 3 -fill white \
         -tags {active pwfs2_pr} -arrow last -arrowshape {20 20 7}

# PWFS to mount
#AWE   $w create line 182 282 200 282 200 422 251 422 -width 3 -fill white \
#AWE         -tags {active pwfs1_mt} -arrow last -arrowshape {20 20 7}
#AWE   $w create line 582 275 610 275 610 422 381 422 -width 3 -fill white \
#AWE         -tags {active pwfs2_mt} -arrow last -arrowshape {20 20 7}

# M2 to mount
#AWE   $w create line 183  40  20  40  20 442 251 442 -width 3 -fill white
   $w create line 183  40  20  40  20 412 251 412 -width 3 -fill white \
         -tags {active m2_mt} -arrow last -arrowshape {20 20 7}

# ENABLE/DISABLE/RESET buttons.
   itk_component add on {
      LiveButton $w.on -text Enable -command [itcl::code $this enable]
   }
   itk_component add off {
      LiveButton $w.off -text Disable -command {AO disable}
   }
   itk_component add reset {
      button $w.reset -text Reset -command [itcl::code $this reset]
   }
#AWE   $w create window 430 462 -window $itk_component(on)
#AWE   $w create window 510 462 -window $itk_component(off)
#AWE   $w create window 590 462 -window $itk_component(reset)
   $w create window 430 439 -window $itk_component(on)
   $w create window 510 439 -window $itk_component(off)
   $w create window 590 439 -window $itk_component(reset)

# Monitor the guide states
   foreach rec {p1state p2state oistate aostate m2state absorbtilt m1state \
         m1source p1guide p1guide p1mweight p2mweight m2p1guide m2p2guide \
         m2oiguide m2aoguide coma} {
      if { [llength [itcl::find objects ::guideConfig.$rec]] == 0 } {
         RecordMonitor ::guideConfig.$rec guideConfig $rec
      }
      lappend monids [::guideConfig.$rec add [itcl::code $this recolour]]
   }

# Schedule an update once the channels have connected.
   after 1000 [itcl::code $this recolour]

   eval itk_initialize $args
}

itcl::body GuideLoop::destructor {} {
   foreach rec {p1state p2state oistate aostate m2state absorbtilt m1state \
         m1source p1guide p1guide p1mweight p2mweight m2p1guide m2p2guide \
         m2oiguide m2aoguide coma} mon $monids {
      ::guideConfig.$rec remove $mon
   }
}

itcl::body GuideLoop::recolour args {

   set w $itk_component(canv)

# Assume no signal to mount
   set mount 0

# Set everything to white.
   $w itemconfigure active -fill white

# P1 signals.
   if { [AO state pwfs1] } {
      $w itemconfigure pwfs1_bg -fill green
      if { [AO state m1] && [AO source m1 PWFS1] } {
         $w itemconfigure pwfs1_m1 -fill green
      } else {
         $w itemconfigure pwfs1_m1 -fill yellow
      }
      if { [AO state m2] && ([AO source m2 PWFS1 A] || \
            [AO source m2 PWFS1 B]) } {
         $w itemconfigure pwfs1_m2 -fill green
      } else {
         $w itemconfigure pwfs1_m2 -fill yellow
      }
      if { [AO state coma] } {
         $w itemconfigure pwfs1_m2xy -fill green
      } else {
         $w itemconfigure pwfs1_m2xy -fill yellow
      }
      if { [AO state p1guide] } {
         $w itemconfigure pwfs1_pr -fill green
      } else {
         $w itemconfigure pwfs1_pr -fill yellow
      }
      if { [AO state mount] && [AO source mount PWFS1] } {
         $w itemconfigure pwfs1_mt -fill green
         set mount 1
      } else {
         $w itemconfigure pwfs1_mt -fill yellow
      }
   }

# P2 signals
   if { [AO state pwfs2] } {
      $w itemconfigure pwfs2_bg -fill green
      if { [AO state m1] && [AO source m1 PWFS2] } {
         $w itemconfigure pwfs2_m1 -fill green
      } else {
         $w itemconfigure pwfs2_m1 -fill yellow
      }
      if { [AO state m2] && ([AO source m2 PWFS2 A] || \
            [AO source m2 PWFS2 B]) } {
         $w itemconfigure pwfs2_m2 -fill green
      } else {
         $w itemconfigure pwfs2_m2 -fill yellow
      }
      if { [AO state p2guide] } {
         $w itemconfigure pwfs2_pr -fill green
      } else {
         $w itemconfigure pwfs2_pr -fill yellow
      }
      if { [AO state mount] && [AO source mount PWFS2] } {
         $w itemconfigure pwfs2_mt -fill green
         set mount 1
      } else {
         $w itemconfigure pwfs2_mt -fill yellow
      }
   }

# OIWFS signals
   if { [AO state oiwfs] } {
      $w itemconfigure oiwfs_bg -fill green
      if { [AO state m1] && [AO source m1 OIWFS] } {
         $w itemconfigure oiwfs_m1 -fill green
      } else {
         $w itemconfigure oiwfs_m1 -fill yellow
      }
      if { [AO state m2] && ([AO source m2 OIWFS A] || \
            [AO source m2 OIWFS B]) } {
         $w itemconfigure oiwfs_m2 -fill green
      } else {
         $w itemconfigure oiwfs_m2 -fill yellow
      }
   }

# GAOS signals
   if { [AO state gaos] } {
      $w itemconfigure gaos_bg -fill green
      if { [AO state m1] && [AO source m1 Altair] } {
         $w itemconfigure gaos_m1 -fill green
      } else {
         $w itemconfigure gaos_m1 -fill yellow
      }
      if { [AO state m2] && ([AO source m2 GAOS A] || \
            [AO source m2 GAOS B]) } {
         $w itemconfigure gaos_m2 -fill green
      } else {
         $w itemconfigure gaos_m2 -fill yellow
      }
      if { [AO state coma] } {
         $w itemconfigure gaos_m2xy -fill green
      } else {
         $w itemconfigure gaos_m2xy -fill yellow
      }
   }

# M1
   if { [AO state m1] } {
      if { ( [AO source m1 PWFS1] && [AO state pwfs1] ) ||
            ( [AO source m1 PWFS2] && [AO state pwfs2] ) ||
            ( [AO source m1 OIWFS] && [AO state oiwfs] ) ||
            ( [AO source m1 Altair] && [AO state gaos] ) } {
         $w itemconfigure m1_bg -fill green
      } else {
         $w itemconfigure m1_bg -fill yellow
      }
   }

# M2
   if { [AO state m2] } {
      if { (( [AO source m2 PWFS1 A] || [AO source m2 PWFS1 B] ) && \
            [AO state pwfs1] ) || \
            (( [AO source m2 PWFS2 A] || [AO source m2 PWFS2 B] ) && \
            [AO state pwfs2] ) || \
            (( [AO source m2 OIWFS A] || [AO source m2 OIWFS B] ) && \
            [AO state oiwfs] ) || \
            (( [AO source m2 GAOS A] || [AO source m2 GAOS B] ) && \
            [AO state gaos] ) } {
         $w itemconfigure m2_bg -fill green
         if { [AO source mount M2] && [AO state mount] } {
            $w itemconfigure m2_mt -fill green
            set mount 1
         } else {
            $w itemconfigure m2_mt -fill yellow
         }
      } else {
         $w itemconfigure m2_bg -fill yellow
         $w itemconfigure m2_mt -fill yellow
      }
   }

# M2 Coma
   if { [AO state coma] } {
      if { [AO state pwfs1] || [AO state gaos] } {
         $w itemconfigure m2xy_bg -fill green
      } else {
         $w itemconfigure m2xy_bg -fill yellow
      }
   }

# M2 guide source buttons.
   if { [AO source m2 PWFS1] } {
      $itk_component(m2p1) configure -background green
   }
   if { [AO source m2 PWFS2] } {
      $itk_component(m2p2) configure -background green
   }
   if { [AO source m2 OIWFS] } {
      $itk_component(m2oi) configure -background green
   }
   if { [AO source m2 GAOS] } {
      $itk_component(m2ao) configure -background green
   }

# Mount
   if { [AO state mount] } {
      if { $mount } {
         $w itemconfigure mount_bg -fill green
      } else {
         $w itemconfigure mount_bg -fill yellow
      }
   }

# WFS probes
   if { ( [AO state p1guide] && [AO state pwfs1] ) ||
         ( [AO state p2guide] && [AO state pwfs2] ) } {
      $w itemconfigure probes_bg -fill green
   } elseif { [AO state p1guide] || [AO state p2guide] } {
      $w itemconfigure probes_bg -fill yellow
   }
}

itcl::body GuideLoop::comacorr {val} {
   switch $val {
      ON {
         AO configure -comacorr 1
      }
      OFF {
         AO configure -comacorr 0
      }
   }
}

itcl::body GuideLoop::m2mode {probe val} {
   if { $val eq "OFF"} {
      AO configure -${probe}guide ""
   } else {
      AO configure -${probe}guide On
   }
}

itcl::body GuideLoop::mtmode {val} {
   switch $val {
      P1 {
         AO configure -mountguide PWFS1
      }
      P2 {
         AO configure -mountguide PWFS2
      }
      M2 {
         AO configure -mountguide SCS
      }
      OFF {
         AO configure -mountguide none
      }
   }
}

itcl::body GuideLoop::probemode {val} {
   switch $val {
      P1 {
         AO configure -probeguide PWFS1
      }
      P2 {
         AO configure -probeguide PWFS2
      }
      OFF {
         AO configure -probeguide none
      }
   }
}

itcl::body GuideLoop::wfsmode {wfs val} {
   switch $val {
      ON {
         AO configure -${wfs}Active 1
      }
      OFF {
         AO configure -${wfs}Active 0
      }
   }
}

itcl::body GuideLoop::enable {} {
   AO configure -pwfs1Expose [$itk_component(pwfs1_ex) get]
   AO configure -pwfs2Expose [$itk_component(pwfs2_ex) get]
   AO configure -oiwfsExpose [$itk_component(oiwfs_ex) get]
   AO enable
}

itcl::body GuideLoop::m1mode {state} {
   if { $state eq "OFF" } {
      AO configure -m1source ""
   } else {
      AO configure -m1source $state
   }
}

itcl::body GuideLoop::reset {} {

# Disable 
   AO disable

# Simulate pushing all the "off" buttons.
   $itk_component(pwfs1) select OFF
   $itk_component(pwfs2) select OFF
   $itk_component(oiwfs) select OFF
   $itk_component(m1src) select OFF
   $itk_component(m2p1) select OFF
   $itk_component(m2p2) select OFF
   $itk_component(m2ao) select OFF
   $itk_component(m2oi) select OFF
   $itk_component(m2coma) select OFF
   $itk_component(mt) select OFF
   $itk_component(pr) select OFF
}
