#+
#  GuideComponent <- Guide, Component
#
#  A GuideComponent object is a Guide object that is stored in a 
#  configuration list.
#
#  Options:
#           none
#
#  Methods:
#           constructor list  Creates the Guide object and puts it onto
#                           "list".
#
#  D Terrett 19 September 2001
#
#  Copyright CCLRC
#+

itcl::class GuideComponent {
   inherit Component Guide
   constructor {list args} {
      Component::constructor $list
   } {
      eval configure $args
   }
}
