#+
#  GuideLoop <- itk::Widget
#
#  A GuideLoop is a diagram of the various guiding loops with control
#  for setting them up and enabling them
#
#  Options:
#           none
#
#  Methods:
#           none
#
#  D Terrett  28 September 2000
#
#  Copyright CCLRC
#+

itcl::class GuideLoop {
   inherit itk::Widget

   constructor args {}
   destructor {}

   private method m1mode state
   private method mtmode state
   private method m2mode state
   private method prmode state
   private method wfsstart {wfs ql}
   private method wfsstop wfs
   private method recolour args

   private variable m1Weight
}

itk::usual GuideLoop {
   keep -cursor
}

itcl::body GuideLoop::constructor args {

# Create canvas.
   itk_component add canv {
      canvas $itk_interior.canv -width 630 -height 430 -borderwidth 2 \
            -relief sunken
   }
   pack $itk_component(canv)
   set w $itk_component(canv)

# WFS boxes
   foreach sys {pwfs1 pwfs2 oiwfs} {
      itk_component add ${sys}_off {
         LiveButton $w.${sys}_off -text OFF -command [code $this wfsstop $sys]
      }
      itk_component add ${sys}_on {
         LiveButton $w.${sys}_on -text ON -command [code $this wfsstart $sys 0]
      }
      itk_component add ${sys}_ql {
         LiveButton $w.${sys}_ql -text QL -command [code $this wfsstart $sys 1]
      }
#      itk_component add ${sys}_setup {
#         button $w.${sys}_setup -text SETUP
#      }
      itk_component add $sys {
         label $w.${sys} -text [string toupper $sys]
      }

      $w create rectangle 0 0 132 63 -fill white -tags "active ${sys} ${sys}_bg"
      $w create window 32 12 -width 60 -height 20 -window $w.${sys}_off \
            -tags $sys
      $w create window 32 32 -width 60 -height 20 -window $w.${sys}_on \
            -tags $sys
      $w create window 32 52 -width 60 -height 20 -window $w.${sys}_ql \
            -tags $sys
#      $w create window 32 52 -width 60 -height 20 -window $w.${sys}_setup \
            -tags $sys

# WFS controls.
      itk_component add ${sys}_ex {
         iwidgets::combobox $w.${sys}_ex -arrowrelief flat -width 5 \
               -validate real -labeltext "exp(s)"
      }
      $w create window 60 74 -window $w.${sys}_ex -tag $sys
      $w.${sys}_ex insert list end 1.0 0.5 0.1 0.05 0.01 0.005
      $w.${sys}_ex insert entry end 0.05
      [$w.${sys}_ex component list] configure -hscrollmode none \
            -vscrollmode none
   }

# Find the name of the font used for the buttons and use it for all text.
   set font [$w.oiwfs_off cget -font]

   foreach sys {pwfs1 pwfs2 oiwfs} {
      $w create text 92 32 -text [string toupper $sys] -tags $sys -font $font
   }

# M1, M2 and Mount boxes.
   foreach sys {m2 m1 mount} {
      $w create rectangle 0 0 132 63 -fill white -tags "active ${sys} ${sys}_bg"
      $w create text 92 32 -text [string toupper $sys] -tags $sys -font $font
   }

# Controls for M2
   itk_component add m2open {
      LiveButton $w.m2open -text OFF -command [code $this m2mode 0]
   }
   itk_component add m2close {
      LiveButton $w.m2close -text ON -command [code $this m2mode 1]
   }
   $w create window 32 12 -width 60 -height 20 -window $w.m2open -tags m2
   $w create window 32 32 -width 60 -height 20 -window $w.m2close -tags m2

# Controls for M1.
   itk_component add m1Weight {
      checkbutton $w.m1Weight -text Weighting -variable [scope m1Weight] \
            -onvalue Errors -offvalue None
   }
   $w create window 170 10 -window $itk_component(m1Weight) -anchor nw -tags m1
   itk_component add m1Frames {
      iwidgets::entryfield $w.m1Frames -labeltext "frames" \
            -width 5
   }
   $itk_component(m1Frames) insert end 60
   $w create window 170 30 -window $itk_component(m1Frames) -anchor nw -tags m1
   itk_component add m1open {
      LiveButton $w.m1open -text OFF -command [code $this m1mode 0]
   }
   itk_component add m1close {
      LiveButton $w.m1close -text ON -command [code $this m1mode 1]
   }
   $w create window 32 12 -width 60 -height 20 -window $w.m1open -tags m1
   $w create window 32 32 -width 60 -height 20 -window $w.m1close -tags m1


# Controls for Mount.
   itk_component add mtWeight {
      scale $w.mtWeight -from 0.0 -to 1.0 -resolution 0.1 -orient horizontal \
            -showvalue 0 -length 120 -borderwidth 1 -label "WFS weight"
   }
   $w create window 170 25 -window $itk_component(mtWeight) -anchor nw \
         -tags mount
   $w create text 155 55 -text P1 -tags mount -font $font
   $w create text 310 55 -text P2 -tags mount -font $font
   itk_component add mtopen {
      LiveButton $w.mtopen -text OFF -command [code $this mtmode 0]
   }
   itk_component add mtm2 {
      LiveButton $w.mtm2 -text M2 -command [code $this mtmode 1]
   }
   itk_component add mtwfs {
      LiveButton $w.mtpwfs -text WFS -command [code $this mtmode -1]
   }
   $w create window 32 52 -width 60 -height 20 -window $w.mtm2 -tags mount
   $w create window 32 32 -width 60 -height 20 -window $w.mtopen -tags mount
   $w create window 32 12 -width 60 -height 20 -window $w.mtpwfs -tags mount

# Box for WFS probes.
   $w create rectangle 0 0 132 63 -fill white -tags "active probes probes_bg"
   $w create text 92 32 -text PROBES -tags probes -font $font

# Controls for probes.
   itk_component add propen {
      LiveButton $w.propen -text OFF -command [code $this prmode 0]
   }
   itk_component add prp1 {
      LiveButton $w.prp1 -text P1 -command [code $this prmode 1]
   }
   itk_component add prp2 {
      LiveButton $w.prp2 -text P2 -command [code $this prmode 2]
   }
   $w create window 32 52 -width 60 -height 20 -window $w.prp1 -tags probes
   $w create window 32 32 -width 60 -height 20 -window $w.prp2 -tags probes
   $w create window 32 12 -width 60 -height 20 -window $w.propen -tags probes

# Move boxes into position.
   $w move m2 250 20
   $w move m1 250 100
   $w move pwfs1 50 180
   $w move oiwfs 250 180
   $w move pwfs2 450 180
   $w move probes 250 280
   $w move mount 250 360

# PWFS1 to M1
   $w create line 150 182 150 130 252 130 -width 3 -fill white \
         -tags {active pwfs1_m1} -arrow last -arrowshape {20 20 7}

# WFS to M2
   $w create line 100 182 100  60 252  60 -width 3 -fill white \
         -tags {active pwfs1_m2} -arrow last -arrowshape {20 20 7}
   $w create line 379 210 410 210 410  60 379  60 -width 3 -fill white \
         -tags {active oiwfs_m2} -arrow last -arrowshape {20 20 7}
   $w create line 580 190 610 190 610  40 379  40 -width 3 -fill white \
         -tags {active pwfs2_m2} -arrow last -arrowshape {20 20 7}

# WFS to Probes
   $w create line 180 200 220 200 220 310 251 310 -width 3 -fill white \
         -tags {active pwfs1_pr} -arrow last -arrowshape {20 20 7}
   $w create line 580 230 590 230 590 310 379 310 -width 3 -fill white \
         -tags {active pwfs2_pr} -arrow last -arrowshape {20 20 7}

# PWFS to mount
   $w create line 180 220 200 220 200 380 251 380 -width 3 -fill white \
         -tags {active pwfs1_mt} -arrow last -arrowshape {20 20 7}
   $w create line 580 210 610 210 610 380 379 380 -width 3 -fill white \
         -tags {active pwfs2_mt} -arrow last -arrowshape {20 20 7}

# M2 to mount
   $w create line 252  40  20  40  20 400 251 400 -width 3 -fill white \
         -tags {active m2_mt} -arrow last -arrowshape {20 20 7}

# Create the command senders required by this screen.
   if { [catch {cs m1Guide info}] } {
      epics cs m1Guide
   }
   if { [catch {cs m1GuideConfig info}] } {
      epics cs m1GuideConfig
   }
   if { [catch {cs mountGuide info}] } {
      epics cs mountGuide
   }
   if { [catch {cs m2Guide info}] } {
      epics cs m2Guide
   }
   if { [catch {cs wfsGuideMode info}] } {
      epics cs wfsGuideMode
   }
   if { [catch {cs pwfs1Observe info}] } {
      epics cs pwfs1Observe
   }
   if { [catch {cs pwfs1StopObserve info}] } {
      epics cs pwfs1StopObserve
   }
   if { [catch {cs pwfs2Observe info}] } {
      epics cs pwfs2Observe
   }
   if { [catch {cs pwfs2StopObserve info}] } {
      epics cs pwfs2StopObserve
   }
   if { [catch {cs oiwfsObserve info}] } {
      epics cs oiwfsObserve
   }
   if { [catch {cs oiwfsStopObserve info}] } {
      epics cs oiwfsStopObserve
   }

# Create status acceptor for guide state
   if { [catch {sa guideConfig info}] } {
      epics sa guideConfig
   }

# Monitor the guide states
   foreach rec {p1state p2state oistate m2state absorbtilt m1state \
         wfsstate wfsprobe} {
      sa guideConfig proc $rec [code $this recolour]
   }

   eval itk_initialize $args
}

itcl::body GuideLoop::destructor {} {
   foreach rec {p1state p2state oistate m2state absorbtilt m1state \
         wfsstate wfsprobe} {
      sa guideConfig unproc $rec [code $this recolour]
   }
}

body GuideLoop::recolour args {

   set w $itk_component(canv)

# Set state variables according to the values in the guideConfig status
# acceptor.
   switch [sa guideConfig get p1state value] {
      Yes {
         set pwfs1 1
      }
      No -
      default {
         set pwfs1 0
      }
   }
   switch [sa guideConfig get p2state value] {
      Yes {
         set pwfs2 1
      }
      No -
      default {
         set pwfs2 0
      }
   }
   switch [sa guideConfig get oistate value] {
      Yes {
         set oiwfs 1
      }
      No -
      default {
         set oiwfs 0
      }
   }
   switch [sa guideConfig get m1state value] {
      On {
         set m1_sw 1
      }
      Off -
      default {
         set m1_sw 0
      }
   }
   switch [sa guideConfig get m2state value] {
      On {
         set m2_sw 1
      }
      Off -
      default {
         set m2_sw 0
      }
   }
   switch [sa guideConfig get absorbtilt value] {
      3 {
         set mt_sw 1
      }
      4 {
         set mt_sw -1
      }
      0 -
      default {
         set mt_sw 0
      }
   }
   switch [sa guideConfig get wfsstate value] {
      On {
         switch [sa guideConfig get wfsprobe value] {
            PWFS1 {
               set wfs_sw 1
            }
            PWFS2 {
               set wfs_sw 2
            }
            default {
               set wfs_sw 0
            }
         }
      }
      Off -
      default {
         set wfs_sw 0
      }
   }

   set m2 0
   set m1 0

# Set everything to white.
   $w itemconfigure active -fill white

   if { $pwfs1 } {
      set pwfs 1
      $w itemconfigure pwfs1_bg -fill green
      $w itemconfigure pwfs1_m1 -fill green
      $w itemconfigure pwfs1_m2 -fill green
      $w itemconfigure pwfs1_pr -fill green
      $w itemconfigure pwfs1_mt -fill green
      if { $m1_sw } {
         $w itemconfigure m1_bg -fill green
      }
   }
   if { $pwfs2 } {
      set pwfs 1
      $w itemconfigure pwfs2_bg -fill green
      $w itemconfigure pwfs2_m2 -fill green
      $w itemconfigure pwfs2_pr -fill green
      $w itemconfigure pwfs2_mt -fill green
   }
   if { $oiwfs } {
      set wfs 1
      $w itemconfigure oiwfs_bg -fill green
      $w itemconfigure oiwfs_m2 -fill green
   }
   if { $m2_sw } {
      if { $oiwfs || $pwfs1 || $pwfs2 } {
         $w itemconfigure m2_bg -fill green
         $w itemconfigure m2_mt -fill green
         set m2 1
      } else {
         $w itemconfigure m2_bg -fill yellow
         $w itemconfigure m2_mt -fill yellow
      }
   }
   if { $mt_sw == 1 } {
      if { $m2 } {
         $w itemconfigure mount_bg -fill green
      } else {
         $w itemconfigure mount_bg -fill yellow
      }
   } elseif { $mt_sw == -1 } {
      if { $pwfs1 || $pwfs2 } {
         $w itemconfigure mount_bg -fill green
      } else {
         $w itemconfigure mount_bg -fill yellow
      }
   }
   if { $m1_sw } {
      if { $pwfs1} {
         $w itemconfigure m1_bg -fill green
         set m2 1
      } else {
         $w itemconfigure m1_bg -fill yellow
      }
   }
   if { $wfs_sw } {
      if { ($wfs_sw == 1 && $pwfs1) || ($wfs_sw == 2 && $pwfs2) } {
         $w itemconfigure probes_bg -fill green
      } else {
         $w itemconfigure probes_bg -fill yellow
      }
   }
}

body GuideLoop::m1mode state {

   if { $state } {
      cs m1GuideConfig set frames [$itk_component(m1Frames) get]
      cs m1GuideConfig set weighting $m1Weight
      logger command m1GuideConfig
      cs m1Guide set mode On
   } else {
      cs m1Guide set mode Off
   }
   logger command m1Guide

   if { [catch {cs tcsApply post} msg] } {
      tk_messageBox -icon error -parent $itk_interior -message \
            "Error posting m1Guide command: TCS reports \
            \"$msg\""
   }
}

body GuideLoop::mtmode state {

   cs mountGuide set mode [expr {$state ? "On" : "Off"}]
   if { $state == -1 } {
      cs mountGuide set source AG 
   } else {
      cs mountGuide set source SCS 
   } 
   set p1 [$itk_component(mtWeight) get]
   cs mountGuide set p1weight $p1
   cs mountGuide set p2weight [expr {1 - $p1}]
   logger command mountGuide

   if { [catch {cs mountGuide post} msg] } {
      tk_messageBox -icon error -parent $itk_interior -message \
            "Error posting mountGuide command: TCS reports \
            \"$msg\""
   }
}

body GuideLoop::m2mode state {

   cs m2Guide set state [expr {$state ? "On" : "Off"}]
   logger command m2Guide

   if { [catch {cs m2Guide post} msg] } {
      tk_messageBox -icon error -parent $itk_interior -message \
            "Error posting m2GuideControl command: TCS reports \
            \"$msg\""
   }
}

body GuideLoop::prmode state {

   cs wfsGuideMode set state [expr {$state ? "On" : "Off"}]
   switch $state {
      1 {
         cs wfsGuideMode set probe PWFS1
      }
      2 {
         cs wfsGuideMode set probe PWFS2
      }
   }
   logger command wfsGuideMode

   if { [catch {cs wfsGuideMode post} msg] } {
      tk_messageBox -icon error -parent $itk_interior -message \
            "Error posting wfsGuideMode command: TCS reports \
            \"$msg\""
   }
}

body GuideLoop::wfsstart {wfs ql} {

   cs ${wfs}Observe set noexp -1
   cs ${wfs}Observe set int [$itk_component(${wfs}_ex) get]
   if { $ql } {
      cs ${wfs}Observe set outopt DHS
      cs ${wfs}Observe set output QL
   } else {
      cs ${wfs}Observe set outopt NONE
      cs ${wfs}Observe set output ""
   }
   logger command ${wfs}Observe

   if { [catch {cs ${wfs}Observe post} msg] } {
      tk_messageBox -icon error -parent $itk_interior -message \
            "Error posting ${wfs}Observe command: TCS reports \
            \"$msg\""
   }
}

body GuideLoop::wfsstop wfs {

   cs ${wfs}StopObserve set dummy MARK
   logger command ${wfs}StopObserve

   if { [catch {cs ${wfs}StopObserve post} msg] } {
      tk_messageBox -icon error -parent $itk_interior -message \
            "Error posting ${wfs}StopObserve command: TCS reports \
            \"$msg\""
   }
}
