#+
#  GuideComponent <- Guide, Component
#
#  A GuidComponent object is a Guide object that is stored in a 
#  configuration list.
#
#  Options:
#           none
#
#  Methods:
#           constructor list  Creates the Guide object and puts it onto
#                           "list".
#
#           save file       Writes commands to re-create the object to the
#                           channel identifier "file" and then calls the
#                           Guide save method to add the objects data.
#
#  D Terrett 25 September 2000
#
#  Copyright CCLRC
#+

itcl::class GuideComponent {
   inherit Guide Component

   constructor {list args} {
      Component::constructor $list
   } {
      eval configure $args
   }

   public method save file
}

itcl::body GuideComponent::save file {
   set obj [namespace tail $this]
   set namespace [namespace qualifiers $this]
   puts $file \
         "catch {GuideComponent \"${namespace}::$obj\"  $componentList}"
   puts $file "\"${namespace}::$obj\" init"
   puts $file "\"${namespace}::$obj\" configure \\"
   Guide::save $file
}
