#+
#  Guide
#
#  A guide component contains the names of the targes for the 3 wavefront 
#  sensors and which chop and nod states they should be active in.
#
#  Options:
#           -oiwfsTarget    The target for the on-instrument wavefront sensor.
#
#           -oiwfsActive    The chop states in which the guide star is
#                           active
#
#           -oiwfsNodState  The nod states in which the probe follows
#                           the star.
#
#           -pwfs1Target    The target for peripheral wavefront sensor 1.
#
#           -pwfs1Active    The chop states in which the guide star is
#                           active
#
#           -pwfs1NodState  The nod states in which the probe follows
#                           the star.
#
#           -pwfs2Target    The target for peripheral wavefront sensor 2.
#
#           -pwfs2Active    The chop states in which the guide star is
#                           active
#
#           -pwfs2NodState  The nod states in which the probe follows
#                           the star.
#
#  Methods:
#           apply cs        Sets the system and equinox paramters of the
#                           command sender "cs".
#
#           init            Returns the guide object to its initial state.
#
#           preview         Sets the guide information in the preview.
#
#           save file       Writes the values of the options to the file
#                           descriptor "file".
#
#  Procs:
#           subcomponents   Returns a list of the Guide components 
#                           subcomponents.
#
#  D Terrett 15 March 2001
#
#  Copyright CCLRC
#+

itcl::class Guide {
   constructor {} {}
   destructor {$this init}
   public proc subcomponents {}
   public {
      method apply {args}
      method init {}
      method preview {}
      method save {file}
      variable oiwfsTarget "" {newTarget oiwfs $oiwfsTarget}
      variable pwfs1Target "" {newTarget pwfs1 $pwfs1Target}
      variable pwfs2Target "" {newTarget pwfs2 $pwfs2Target}
      variable pwfs1Active A
      variable pwfs2Active A
      variable oiwfsActive A
      variable pwfs1NodState AB
      variable pwfs2NodState AB
      variable oiwfsNodState AB

# These variables are retained so as not to break existing configuration
# definition files.
      variable oiwfsChop
      variable oiwfsNod
      variable pwfs1Chop
      variable pwfs1Nod
      variable pwfs2Chop
      variable pwfs2Nod
   }
   private {
      method setEnableFlags {wfs active nodstate}
      method newTarget {wfs name}
      method park {wfs}
      variable current_target
   }
}

itcl::body Guide::constructor {} {
   set current_target(oiwfs) ""
   set current_target(pwfs1) ""
   set current_target(pwfs2) ""
}

itcl::body Guide::subcomponents {} {
   return { \
      {pwfs1Target WfsTarget WfsTargetNames WfsTargetList {PWFS1 Target} pwfs1} \
      {pwfs2Target WfsTarget WfsTargetNames WfsTargetList {PWFS2 Target} pwfs2} \
      {oiwfsTarget WfsTarget WfsTargetNames WfsTargetList {OIWFS Target} oiwfs} \
   }
}

itcl::body Guide::apply args {

# Call the apply method of all the targets that have a value and set the
# enable flags.
   if { ![string is space $pwfs1Target] } {
      ::WfsTargetNames::$pwfs1Target apply pwfs1
      setEnableFlags pwfs1 $pwfs1Active $pwfs1NodState
   } else {
      setEnableFlags pwfs1 "" ""
      park pwfs1
   }
   if { ![string is space $pwfs2Target] } {
      ::WfsTargetNames::$pwfs2Target apply pwfs2
      setEnableFlags pwfs2 $pwfs2Active $pwfs2NodState
   } else {
      setEnableFlags pwfs2 "" ""
      park pwfs2
   }
   if { ![string is space $oiwfsTarget] } {
      ::WfsTargetNames::$oiwfsTarget apply oiwfs
      setEnableFlags oiwfs $oiwfsActive $oiwfsNodState
   } else {
      setEnableFlags oiwfs "" ""
   }
}

itcl::body Guide::init {} {
   $this configure -oiwfsTarget ""
   set oiwfsActive A
   set oiwfsNodState AB
   $this configure -pwfs1Target ""
   set pwfs1Active A
   set pwfs1NodState AB
   $this configure -pwfs2Target ""
   set pwfs2Active A
   set pwfs2NodState AB
}

itcl::body Guide::preview {} {
   if { ! [string equal $pwfs1Target ""] } {
      ::WfsTargetNames::$pwfs1Target preview pwfs1
   }
   if { ! [string equal $pwfs2Target ""] } {
      ::WfsTargetNames::$pwfs2Target preview pwfs2
   }
   if { ! [string equal $oiwfsTarget ""] } {
      ::WfsTargetNames::$oiwfsTarget preview oiwfs
   }
}

itcl::body Guide::save file {
   puts $file "   -pwfs1Target [list $pwfs1Target] \\"
   puts $file "   -pwfs1Active $pwfs1Active \\"
   puts $file "   -pwfs1NodState $pwfs1NodState \\"
   puts $file "   -pwfs2Target [list $pwfs2Target] \\"
   puts $file "   -pwfs2Active $pwfs2Active \\"
   puts $file "   -pwfs2NodState $pwfs2NodState \\"
   puts $file "   -oiwfsTarget [list $oiwfsTarget] \\"
   puts $file "   -oiwfsActive $oiwfsActive \\"
   puts $file "   -oiwfsNodState $oiwfsNodState"
}

itcl::body Guide::setEnableFlags {wfs active nodstate} {
   switch $active {
      A {
         switch $nodstate {
            A {
               cs ${wfs}Guide set nodachopa On
               cs ${wfs}Guide set nodachopb Off
               cs ${wfs}Guide set nodbchopa Off
               cs ${wfs}Guide set nodbchopb Off
            }
            B {
               cs ${wfs}Guide set nodachopa Off
               cs ${wfs}Guide set nodachopb Off
               cs ${wfs}Guide set nodbchopa On
               cs ${wfs}Guide set nodbchopb Off
            }
            AB {
               cs ${wfs}Guide set nodachopa On
               cs ${wfs}Guide set nodachopb Off
               cs ${wfs}Guide set nodbchopa On
               cs ${wfs}Guide set nodbchopb Off
            }
         }
      }
      B {
         switch $nodstate {
            A {
               cs ${wfs}Guide set nodachopa Off
               cs ${wfs}Guide set nodachopb On
               cs ${wfs}Guide set nodbchopa Off
               cs ${wfs}Guide set nodbchopb Off
            }
            B {
               cs ${wfs}Guide set nodachopa Off
               cs ${wfs}Guide set nodachopb Off
               cs ${wfs}Guide set nodbchopa Off
               cs ${wfs}Guide set nodbchopb On
            }
            AB {
               cs ${wfs}Guide set nodachopa Off
               cs ${wfs}Guide set nodachopb On
               cs ${wfs}Guide set nodbchopa Off
               cs ${wfs}Guide set nodbchopb On
            }
         }
      }
      Nod {
         switch $nodstate {
            A {
               cs ${wfs}Guide set nodachopa On
               cs ${wfs}Guide set nodachopb Off
               cs ${wfs}Guide set nodbchopa Off
               cs ${wfs}Guide set nodbchopb Off
            }
            B {
               cs ${wfs}Guide set nodachopa Off
               cs ${wfs}Guide set nodachopb Off
               cs ${wfs}Guide set nodbchopa Off
               cs ${wfs}Guide set nodbchopb On
            }
            AB {
               cs ${wfs}Guide set nodachopa On
               cs ${wfs}Guide set nodachopb Off
               cs ${wfs}Guide set nodbchopa Off
               cs ${wfs}Guide set nodbchopb On
            }
         }
      }
      antiNod {
         switch $nodstate {
            A {
               cs ${wfs}Guide set nodachopa Off
               cs ${wfs}Guide set nodachopb On
               cs ${wfs}Guide set nodbchopa Off
               cs ${wfs}Guide set nodbchopb Off
            }
            B {
               cs ${wfs}Guide set nodachopa Off
               cs ${wfs}Guide set nodachopb Off
               cs ${wfs}Guide set nodbchopa On
               cs ${wfs}Guide set nodbchopb Off
            }
            AB {
               cs ${wfs}Guide set nodachopa Off
               cs ${wfs}Guide set nodachopb On
               cs ${wfs}Guide set nodbchopa On
               cs ${wfs}Guide set nodbchopb Off
            }
         }
      }
      default {
         cs ${wfs}Guide set nodachopa Off
         cs ${wfs}Guide set nodachopb Off
         cs ${wfs}Guide set nodbchopa Off
         cs ${wfs}Guide set nodbchopb Off
      }
   }
   logger command ${wfs}Guide
}

itcl::body Guide::newTarget {wfs name} {
   if { ! [string equal $current_target($wfs) ""] } {
      WfsTargetNames::$current_target($wfs) refdec
   }
   set current_target($wfs) ""
   if { ! [string is space $name] } {
      if { [catch {WfsTargetNames::$name refinc}] } {
         error "Guide target \"$name\" does not exist"
      } else {
         set current_target($wfs) $name
      }
   }
}

itcl::body Guide::park {wfs} {
   switch $wfs {
      pwfs1 {
         cs pwfs1Park set dummy value 1
         logger command pwfs1Park
      }
      pwfs2 {
         cs pwfs2Park set dummy value 1
         logger command pwfs2Park
      }
   }
}
