#+
#  GuideHandsetControl <- itk::Widget
#
#  A GuideHandsetControl implements a software handset for guiding.
#
#  Options:
#           none
#
#  Methods:
#           none
#
#  D Terrett 25 May 2000
#
#  Copyright CCLRC
#+

itcl::class GuideHandsetControl {
   inherit itk::Widget

   constructor args {}
   destructor {after cancel $refid}

   private method offset dir
   private method newstep size
   private method refresh

   private variable refid
}

itk::usual GuideHandsetControl {
   keep -borderwidth -cursor -font -highlightthickness -insertborderwidth \
         -insertofftime -insertontime -insertwidth -labelfont \
         -selectborderwidth -textfont
}

itcl::body GuideHandsetControl::constructor args {

# StepSize widget for setting the step associated with the paddle buttons.
   itk_component add top {
      frame $itk_interior.top -bd 2 -relief groove
   }
   pack $itk_component(top)

   set w $itk_component(top)
   itk_component add stepsize {
      StepSize $w.stepsize -text "Step size (arcsec)" \
            -command [code $this newstep]
   }
   pack $itk_component(stepsize)

# Set the default step size in the TCS.
   newstep 1.0

# Paddle buttons.
   itk_component add paddle {
      HandPaddleButtons $itk_interior.paddle \
            -upcommand [code $this offset U] -uplabel +El\
            -downcommand [code $this offset D] -downlabel -El\
            -leftcommand [code $this offset L] -leftlabel -Az \
            -rightcommand [code $this offset R] -rightlabel +Az
   }
   pack $itk_component(paddle)

# Slider for adjusting the angle of the buttons.
   itk_component add slider {
      scale $itk_interior.slider -orient horizontal -to [expr 3.14159 * 2] \
            -command "$itk_component(paddle) configure -angle" \
            -resolution .01 -showvalue no
   }
   pack $itk_component(slider) -fill x -expand y

# Display of current adjustments.
   itk_component add disp {
      frame $itk_interior.disp -bd 10
   }
   pack $itk_component(disp)
   set w $itk_component(disp)
   itk_component add ca {
      label $w.ca -text CA
   }
   itk_component add ce {
      label $w.ce -text CE
   }
   itk_component add local {
      label $w.local -text Local
   }
   itk_component add guide {
      label $w.guide -text Guide
   }
   itk_component add calocal {
      label $w.calocal -relief groove -bd 2 -width 8 -anchor e
   }
   itk_component add celocal {
      label $w.celocal -relief groove -bd 2 -width 8 -anchor e
   }
   itk_component add caguide {
      label $w.caguide -relief groove -bd 2 -width 8 -anchor e
   }
   itk_component add ceguide {
      label $w.ceguide -relief groove -bd 2 -width 8 -anchor e
   }
   grid x $itk_component(ca) $itk_component(ce)
   grid $itk_component(local) $itk_component(calocal) $itk_component(celocal)
   grid $itk_component(guide) $itk_component(caguide) $itk_component(ceguide)

# Buttons for zeroing and absorbing the guide adjustments.
   itk_component add bot {
      frame $itk_interior.bot
   }
   pack $itk_component(bot) -expand yes -fill x
   set w $itk_component(bot)
   itk_component add absorb {
      ApplyButton $w.absorb -command absorbGuide -text Absorb -width 8
   }
   itk_component add clear {
      ApplyButton $w.clear -command zeroGuide -text Clear -width 8
   }
   pack $itk_component(absorb) $itk_component(clear) -expand y \
         -pady 4 -side left

# Schedule update of CA & CE displays.
   set refid [after 1000 [code $this refresh]]

   eval itk_initialize $args
}

itcl::body GuideHandsetControl::offset dir {
   cs guideHandset set direction $dir
#   if [catch {cs tcsApply post} msg] {
#      tk_messageBox -icon error -parent $itk_interior -message \
#            "Error adjusting pointing: TCS reports \"$msg\""
#   }
   catch {cs tcsApply post}
#   if [catch {cs tcsApply post} msg] {
#      tk_messageBox -icon error -parent $itk_interior -message \
#            "Error adjusting pointing: TCS reports \"$msg\""
#   }
}

itcl::body GuideHandsetControl::newstep size {
   cs guideHandConfig set step $size
   catch {cs tcsApply post}
#   if [catch {cs tcsApply post} msg] {
#      tk_messageBox -icon error -parent $itk_interior -message \
#            "Error setting step size: TCS reports \"$msg\""
#   }
}

itcl::body GuideHandsetControl::refresh {} {

# Update the displays of CA and CE.
   $itk_component(calocal) configure -text [sa tcssad get calocal value]
   $itk_component(celocal) configure -text [sa tcssad get celocal value]
   $itk_component(caguide) configure -text [sa tcssad get caguide value]
   $itk_component(ceguide) configure -text [sa tcssad get ceguide value]

# Reschedule
   set refid [after 1000 [code $this refresh]]
}
