#+
#  GuidePanel <- Panel
#
#  Implements the GuidePanel widget. A Panel widget with a 
#  GuideControl widget packed into its interior.
#
#  Options:
#           -componentlist - The -componentlist option of the Cosys control
#
#           -namespace -     The -namespace option of the Cosys control
#
#           -component -
#
#  Methods:
#          none
#
#  D Terrett 24 Novemeber 1999
#
#  Copyright CCLRC
#+

itcl::class GuidePanel {
   inherit Panel
   constructor args {}
   itk_option define -componentlist componentList ComponentList {}
   itk_option define -namespace namespace Namespace {}
   itk_option define -component component Component {}
}

itk::usual GuidePanel {
   keep -background -cursor
}

itcl::body GuidePanel::constructor args {
   itk_component add control {
      GuideControl $itk_interior.control
   }
   setWidgetColors "$itk_component(menubar) $itk_component(control)" \
         $itk_option(-background) $itk_option(-foreground)

   pack $itk_component(control) -fill both -expand y

   set itk_option(-windows) $itk_component(control)

   eval itk_initialize $args
}

itcl::configbody GuidePanel::componentlist {
   $itk_component(control) configure -componentlist $itk_option(-componentlist)
}

itcl::configbody GuidePanel::namespace {
   $itk_component(control) configure -namespace $itk_option(-namespace)
}

itcl::configbody GuidePanel::component {
   $itk_component(control) configure -component $itk_option(-component)
}
