#+
#  GuideLoopPanel.itk
#
#  Implements the GuideLoopPanel widget. A Panel widget with a 
#  GuideLoopControl widget packed into its interior.
#
#  D Terrett 22 November 1999
#
#  Copyright CCLRC
#+

itcl::class GuideLoopPanel {
   inherit Panel

   constructor args {}
}

itk::usual GuideLoopPanel {
   keep -background -cursor
}

itcl::body GuideLoopPanel::constructor args {

   itk_component add control {
      GuideLoopControl $itk_interior.control
   } {
      usual
      ignore -insertbackground
      ignore -selectforeground
      ignore -selectbackground
      ignore -highlightcolor
   }
   setWidgetColors "$itk_component(menubar) $itk_component(control)" \
         $itk_option(-background) $itk_option(-foreground)

   pack $itk_component(control) -fill both -expand y

   set itk_option(-windows) $itk_component(control)

   eval itk_initialize $args
}
