#+
#  GuidePanel <- Panel
#
#  Implements the GuidePanel widget. A Panel widget with a 
#  GuideControl widget packed into its interior.
#
#  Methods:
#          none
#
#  D Terrett 29 March 2001
#
#  Copyright CCLRC
#+

itcl::class GuidePanel {
   inherit Panel
   constructor args {}
}

itk::usual GuidePanel {
   keep -background -cursor
}

itcl::body GuidePanel::constructor args {
   itk_component add control {
      GuideControl $itk_interior.control
   }
   setWidgetColors "$itk_component(menubar) $itk_component(control)" \
         $itk_option(-background) $itk_option(-foreground)

   pack $itk_component(control) -fill both -expand y

   eval itk_initialize $args
}
