#+
#  guideAlarm <- itk::Widget
#
# Implements a guide Count alarm which will sound if guiding and the counts drop below a given threshhold.
#
#  Methods:
#
# AWEbbers  January, 2005
#

itcl::class GuideAlarm {
    inherit itk::Widget
    constructor {args} {}
    destructor {}
    common guideCounts
    common guideCentroid
    common alarmEnabled
    common alarmOn
    public {
        method updateProc { name alarm time values }
        method updateProc2 { name alarm time values }
        method scanLoop {}
        method setSilent {wfs}
        method alarmCheck {wfs}
        variable flash 0
        variable pwfs1Limit 2000.0
        variable pwfs2Limit 1000.0
        variable oiwfsLimit 1000.0
        variable gaosLimit 500.0
        variable pwfs1Silent 0
        variable pwfs2Silent 0
        variable oiwfsSilent 0
        variable gaosSilent 0
        variable exitnow 0
    }
    private {
        method ringBell {}
        method setWfsColor {wfs color}
        variable tid 0
    }
}

itk::usual GuideAlarm {
    keep -background -cursor -foreground -font \
            -highlightcolor -highlightthickness \
        }

itcl::body GuideAlarm::constructor {args} {
    global guideCounts pwfs1CountLimit pwfs2CountLimit oiwfsCountLimit gaosCountLimit
    global pwfs1silent pwfs2silent oiwfssilent gaossilent guideCentroid
    
    #puts "GuideAlarm this: $this"
    
    itk_component add frame {
        frame $itk_interior.fr
    }
    
    itk_component add title {
        label $itk_component(frame).title -text "Guide Alarm"
    } {
        usual
        rename -font -majorfont majorFont Font
    }
    
    itk_component add desc {
        message $itk_component(frame).desc -text "Alarm will sound if counts are below limit while wfs is in use.  \
                Click on silent to disable audible alarm." -justify center -aspect 100
    }
    
    grid $itk_component(frame) -sticky news
    
    foreach wfs {pwfs1 pwfs2 oiwfs gaos} {
        #puts "setting up wfs: $wfs"
        set guideCounts($wfs) [sa guidects get $wfs]
        if {$wfs != "gaos"} {
            set guideCentroid($wfs) [sa guidects get ${wfs}cent]
	    if {![string is boolean $guideCentroid($wfs)]} {
		set guideCentroid($wfs) 0
	    }
        } else  {
            set guideCentroid($wfs) 0
        }
        set alarmEnabled($wfs) 0
        set alarmOn($wfs) 0
        set ${wfs}CountLimit [set ${wfs}Limit]
        # puts "guideCounts($wfs) = $guideCounts($wfs)"
        
        # create the display widgets
        
        itk_component add ${wfs}frame {
            frame $itk_component(frame).${wfs}frame -relief ridge -bd 2
        }
        set w $itk_component(${wfs}frame)
        #  puts "w: $w"
        itk_component add ${wfs}title {
            label $w.lab -text $wfs
        } {
            usual
            rename -font -majorfont majorFont Font
        }
        itk_component add ${wfs}silent { checkbutton $w.sil -variable ${wfs}silent -onvalue 1 -offvalue 0 -text silent -command "$this setSilent $wfs"}
        itk_component add ${wfs}clab { label $w.clab -text "Counts:" }
        itk_component add ${wfs}cnts { label $w.cnts -textvariable guideCounts($wfs) }
        itk_component add ${wfs}limlab { label $w.limlab -text "Limit:" }
        itk_component add ${wfs}liment { entry $w.liment -textvariable ${wfs}CountLimit -width 5 }
        itk_component add ${wfs}centroid { label $w.cent -text "Subaperture OK"}

        if {$guideCentroid($wfs)} {
            $itk_component(${wfs}centroid) configure -text "Subaperture BAD"
        }

        bind $itk_component(${wfs}liment) <KeyPress-Return> "$this configure -${wfs}Limit \[set ${wfs}CountLimit\] ; $this alarmCheck $wfs"
        
        grid $itk_component(${wfs}title) $itk_component(${wfs}silent) -sticky news
        grid $itk_component(${wfs}clab) $itk_component(${wfs}cnts) -sticky news
        grid $itk_component(${wfs}limlab) $itk_component(${wfs}liment) -sticky news
        grid $itk_component(${wfs}centroid) - -sticky news
    }
    pack $itk_component(title) $itk_component(pwfs1frame) $itk_component(pwfs2frame) $itk_component(oiwfsframe) $itk_component(gaosframe) -side top -padx 3 -pady 3 -ipadx 3 -ipady 3
    
    sa guidects proc pwfs1 "$this updateProc"
    sa guidects proc pwfs2 "$this updateProc"
    sa guidects proc oiwfs "$this updateProc"
    sa guidects proc gaos  "$this updateProc"
    sa guidects proc pwfs1cent "$this updateProc2"
    sa guidects proc pwfs2cent "$this updateProc2"
    sa guidects proc oiwfscent "$this updateProc2"

    # start the scan task ...
    $this scanLoop
    
    eval itk_initialize $args
}

itcl::body GuideAlarm::destructor {} {
    after cancel $tid
    sa guidects unproc pwfs1 "$this updateProc"
    sa guidects unproc pwfs2 "$this updateProc"
    sa guidects unproc oiwfs "$this updateProc"
    sa guidects unproc gaos  "$this updateProc"
    sa guidects unproc pwfs1cent "$this updateProc2"
    sa guidects unproc pwfs2cent "$this updateProc2"
    sa guidects unproc oiwfscent "$this updateProc2"
}

itcl::body GuideAlarm::setWfsColor {wfs color} {
    
    foreach wid {frame title silent clab cnts limlab liment centroid} {
        $itk_component(${wfs}${wid}) configure -bg $color
    }
}

itcl::body GuideAlarm::setSilent {wfs} {
    global pwfs1silent pwfs2silent oiwfssilent gaossilent
    
    #puts "setSilent wfs: $wfs val: [set ${wfs}silent]"
    set ${wfs}Silent [set ${wfs}silent]
}

itcl::body GuideAlarm::alarmCheck {wfs} {
    global guideCounts guideCentroid
    
    if {$alarmEnabled($wfs)} {
        #puts "gonna compare  $guideCounts($wfs) [set ${wfs}Limit]"
        if { ($guideCounts($wfs) < [set ${wfs}Limit]) || $guideCentroid($wfs) } {
            set alarmOn($wfs) 1
            #puts "alarm for $wfs ON"
        } else {
            set alarmOn($wfs) 0
            #puts "alarm for $wfs OFF"
        }
    }
}

itcl::body GuideAlarm::updateProc {name alarm time values} {
    global guideCounts
    
    #puts [format "updateProc: %s %-20s\n%s\n" $time $name $values]
    set tname [lrange [split $name "." ] 1 1 ]
    set tnamev [format "%s%s" $tname "(value)"]
    set $tnamev $values
    set guideCounts($tname) [format "%.0f" [set $tnamev]]
    #puts "set guideCounts($tname) to $guideCounts($tname)"
    alarmCheck $tname
 
    return
}

itcl::body GuideAlarm::updateProc2 {name alarm time values} {
    global guideCentroid
    
    #puts [format "updateProc: %s %-20s\n%s\n" $time $name $values]
    set tname [lrange [split $name "." ] 1 1 ]
    set tnamev [format "%s%s" $tname "(value)"]
    set $tnamev $values
    set tname [string trimright $tname "cent"]
    set guideCentroid($tname) [format "%.0f" [set $tnamev]]
    #puts "set guideCentroid($tname) to $guideCentroid($tname)"

    if {$guideCentroid($tname)} {
        $itk_component(${tname}centroid) configure -text "Subaperture BAD"
    } else  {
        $itk_component(${tname}centroid) configure -text "Subaperture OK"
    }
    alarmCheck $tname
 
    return
}

itcl::body GuideAlarm::ringBell {} {
    
    set makeNoise 0
    
    foreach wfs {pwfs1 pwfs2 oiwfs gaos} {
        if {$alarmEnabled($wfs) && $alarmOn($wfs)} {
            #puts "in ring bell wfs: $wfs silent: [set ${wfs}Silent]"
            if {![set ${wfs}Silent]} {
                set makeNoise 1
            }
            if { $flash } {
                setWfsColor $wfs red
            } else {
                setWfsColor $wfs yellow
            }
        }
    }
    if { $makeNoise } {
        bell
        after 100
        bell
    }
    set flash [expr { ! $flash}]
}

itcl::body GuideAlarm::scanLoop {} {
    
    set num_enabled 0
    set gottaRingBell 0
    
    set canguide [expr {[AO state mount] && [AO state m2]}]
    
    foreach wfs {pwfs1 pwfs2 oiwfs gaos} {
        if {[AO state $wfs] && $canguide} {
            if {!$alarmEnabled($wfs)} {
                set alarmEnabled($wfs) 1
                alarmCheck $wfs
            } else  {
                set alarmEnabled($wfs) 1
            }
            incr num_enabled
        } else {
            set alarmEnabled($wfs) 0
            setWfsColor $wfs PeachPuff1
        }
    }
    
    if {$num_enabled > 0} {
        foreach wfs {pwfs1 pwfs2 oiwfs gaos} {
            if {$alarmOn($wfs) == 1} {
                set gottaRingBell 1
            } elseif {$alarmEnabled($wfs)} {
                setWfsColor $wfs lightgreen
            }
        }
        if {$gottaRingBell} {
            ringBell
        }
    }
    set tid [after 500 "$this scanLoop"]
    update
}
