#+
#  GuideControl <- tcclib::ComponentControl
#
#  A GuideControl is a ComponentControl widget with widgets for the target 
#  name and chop and node states for each of the wavefront sensors.
#
#  Options:
#           -shadow         The names of this control's shadow.
#
#  D Terrett 30 Novemeber 2001
#
#  Copyright CCLRC
#+

itcl::class GuideControl {
   inherit tcclib::ComponentControl
   constructor args {}
   itk_option define -shadow shadow Shadow {}
   public {
      method load {name}
      method save {name}
   }
}

itk::usual GuideControl {
   keep -borderwidth -cursor -font -highlightthickness -insertborderwidth \
         -insertofftime -insertontime -insertwidth -labelfont -popupcursor \
         -selectborderwidth -textfont -title -applyarg -namespace -componentlist
}

itcl::body GuideControl::constructor args {

# Create 3 panels, one for each of the wave front sensors.
   set w $itk_interior
   foreach wfs {pwfs1 pwfs2 oiwfs} {
      itk_component add $wfs {
         frame $w.$wfs -bd 2 -relief sunken
      }
   }
   pack $itk_component(pwfs1) $itk_component(pwfs2) $itk_component(oiwfs)

   foreach wfs {pwfs1 pwfs2 oiwfs} {
      set w $itk_component($wfs)

# Target selector.
      itk_component add ${wfs}Target {
         tcclib::SubComponentSelector $w.target \
               -labeltext "[string toupper $wfs] Target" \
               -componentlist WfsTargetList -labelpos nw \
               -component ${wfs}Target
      }

# Chop state
      itk_component add ${wfs}chop {
         iwidgets::optionmenu $w.chop
      }
      [$itk_component(${wfs}chop) component menuBtn] configure -anchor w
      $itk_component(${wfs}chop) insert end "guide when in beam A" \
            "guide when in beam B" "guide when chop matches nod" \
            "guide when chop doesn't match nod" "no guiding with this WFS"

# Nod setting
      itk_component add ${wfs}nod {
         iwidgets::optionmenu $w.nod -labeltext "and in"
      }
      [$itk_component(${wfs}nod) component menuBtn] configure -anchor w
      $itk_component(${wfs}nod) insert end \
            "nod A only" "nod B only" "both nod states"
      pack $itk_component(${wfs}Target) $itk_component(${wfs}chop) \
            $itk_component(${wfs}nod) -padx 5 -pady 2 -anchor w
}

# Define the object class
   set objclass GuideComponent
   set description "guide configuration"

   eval itk_initialize $args

# Create guide object used by apply
   set scratchobj [namespace which -command [Guide #auto]]
}

itcl::body GuideControl::save {name} {
#+
# Updates the named guide object.
#-
   foreach wfs {pwfs1 pwfs2 oiwfs} {
      switch [$itk_component(${wfs}nod) index \
            [$itk_component(${wfs}nod) get]] {
         0 {set nod AB}
         1 {set nod A}
         2 {set nod B}
      }
      switch [$itk_component(${wfs}chop) index \
            [$itk_component(${wfs}chop) get]] {
         0 {set chop A}
         1 {set chop B}
         2 {set chop Nod}
         3 {set chop antiNod}
         4 {set chop never}
      }
      $name configure -${wfs}Target [$itk_component(${wfs}Target) get] \
             -${wfs}Active $chop -${wfs}NodState $nod
   }
}

itcl::body GuideControl::load {name} {

# Copy the contents of the guide object selected in the combobox
# into the edit control.
   foreach wfs {pwfs1 pwfs2 oiwfs} {
      $itk_component(${wfs}Target) configure -state normal
      $itk_component(${wfs}Target) select [$name cget -${wfs}Target]
      switch [$name cget -${wfs}Active] {
         A {$itk_component(${wfs}chop) select 0}
         B {$itk_component(${wfs}chop) select 1}
         Nod {$itk_component(${wfs}chop) select 2}
         antiNod {$itk_component(${wfs}chop) select 3}
         default {$itk_component(${wfs}chop) select 4}
      }
      switch [$name cget -${wfs}NodState] {
         AB {$itk_component(${wfs}nod) select 0}
         A {$itk_component(${wfs}nod) select 1}
         B {$itk_component(${wfs}nod) select 2}
      }
   }
}

itcl::configbody GuideControl::shadow {
   foreach wfs {pwfs1 pwfs2 oiwfs} {
      $itk_component(${wfs}Target) configure -editcontrol \
               $itk_option(-shadow)${wfs}Target -shadow $itk_option(-shadow)
   }
}
