#+
#  Guide <- Paramset
#
#  A guide component contains which chop and nod states the wave-front
#  sensors should be active in.
#
#  Options:
#           -oiwfsActive    The chop states in which the guide star is
#                           active
#
#           -oiwfsNodState  The nod states in which the probe follows
#                           the star.
#
#           -oiwfsWavelength The OIWFS guiding wavelength component
#
#           -pwfs1Active    The chop states in which the guide star is
#                           active
#
#           -pwfs1Filter    The PWFS1 filter.
#
#           -pwfs1NodState  The nod states in which the probe follows
#                           the star.
#
#           -pwfs1Wavel     The PFWS1 guiding wavelength
#
#           -pwfs2Active    The chop states in which the guide star is
#                           active
#
#           -pwfs2Filter    The PWFS2 filter.
#
#           -pwfs2NodState  The nod states in which the probe follows
#                           the star.
#
#           -pwfs2Wavel     The PFWS2 guiding wavelength
#
#  Methods:
#           apply comp      Sets the chop/nod flags
#
#           init            Returns the guide object to its initial state.
#
#           save node       Saves the values of the options to the xml
#                           node.
#
#  D Terrett 21 February 2003
#
#  copyright CCLRC
#+

itcl::class Guide {
   inherit Paramset
   constructor {} {}
   public {
      method apply {comp}
      method init {}
      method preview {view}
      method save {node}
      variable pwfs1Active never
      variable pwfs2Active never
      variable oiwfsActive never
      variable pwfs1NodState AB
      variable pwfs2NodState AB
      variable oiwfsNodState AB
      variable pwfs1Filter ""
      variable pwfs2Filter ""
      variable pwfs1Wavel ""
      variable pwfs2Wavel ""
      variable oiwfsWavelength ""
   }
   private {
      method setEnableFlags {wfs active nodstate}
   }
}

itcl::body Guide::apply {comp} {
   setEnableFlags pwfs1 $pwfs1Active $pwfs1NodState
   setEnableFlags pwfs2 $pwfs2Active $pwfs2NodState
   setEnableFlags oiwfs $oiwfsActive $oiwfsNodState
   if { ! [string equal $pwfs1Filter ""] } {
      cs pwfs1Filter set filter $pwfs1Filter
      logger command pwfs1Filter
   }
   if { ! ( [string equal $pwfs2Filter ""] || \
         [string equal $pwfs2Filter ALTAIR] ) } {
      cs pwfs2Filter set filter $pwfs2Filter
      logger command pwfs2Filter
   }
   if { ! [string equal $pwfs1Wavel ""] } {
      cs wavelPwfs1 set wavel $pwfs1Wavel
      logger command wavelPwfs1
   }
   if { ! [string equal $pwfs2Wavel ""] } {
      cs wavelPwfs2 set wavel $pwfs2Wavel
      logger command wavelPwfs2
   }
   if { ! [string equal $oiwfsWavelength ""] } {
      ::OIWFSWavelengthNames::$oiwfsWavelength apply $comp.oiwfswavelength
   }
}

itcl::body Guide::init {} {
   set oiwfsActive A
   set oiwfsNodState AB
   set oiwfsWavelength ""
   set pwfs1Active A
   set pwfs1Filter ""
   set pwfs1NodState AB
   set pwfs1Wavel ""
   set pwfs2Active A
   set pwfs2Filter ""
   set pwfs2NodState AB
   set pwfs2Wavel ""
}

itcl::body Guide::save {node} {
   set node [paramset $node guide]
   param $node pwfs1Active $pwfs1Active
   param $node pwfs1NodState $pwfs1NodState
   param $node pwfs1Filter $pwfs1Filter
   param $node pwfs1Wavelength $pwfs1Wavel
   param $node pwfs2Active $pwfs2Active
   param $node pwfs2NodState $pwfs2NodState
   param $node pwfs2Filter $pwfs2Filter
   param $node pwfs2Wavelength $pwfs1Wavel
   param $node oiwfsActive $oiwfsActive
   param $node oiwfsNodState $oiwfsNodState
   param $node oiwfsWavelength $oiwfsWavelength
}

itcl::body Guide::setEnableFlags {wfs active nodstate} {
   switch $active {
      A {
         switch $nodstate {
            A {
               cs ${wfs}Guide set nodachopa On
               cs ${wfs}Guide set nodachopb Off
               cs ${wfs}Guide set nodbchopa Off
               cs ${wfs}Guide set nodbchopb Off
            }
            B {
               cs ${wfs}Guide set nodachopa Off
               cs ${wfs}Guide set nodachopb Off
               cs ${wfs}Guide set nodbchopa On
               cs ${wfs}Guide set nodbchopb Off
            }
            AB {
               cs ${wfs}Guide set nodachopa On
               cs ${wfs}Guide set nodachopb Off
               cs ${wfs}Guide set nodbchopa On
               cs ${wfs}Guide set nodbchopb Off
            }
         }
      }
      B {
         switch $nodstate {
            A {
               cs ${wfs}Guide set nodachopa Off
               cs ${wfs}Guide set nodachopb On
               cs ${wfs}Guide set nodbchopa Off
               cs ${wfs}Guide set nodbchopb Off
            }
            B {
               cs ${wfs}Guide set nodachopa Off
               cs ${wfs}Guide set nodachopb Off
               cs ${wfs}Guide set nodbchopa Off
               cs ${wfs}Guide set nodbchopb On
            }
            AB {
               cs ${wfs}Guide set nodachopa Off
               cs ${wfs}Guide set nodachopb On
               cs ${wfs}Guide set nodbchopa Off
               cs ${wfs}Guide set nodbchopb On
            }
         }
      }
      Nod {
         switch $nodstate {
            A {
               cs ${wfs}Guide set nodachopa On
               cs ${wfs}Guide set nodachopb Off
               cs ${wfs}Guide set nodbchopa Off
               cs ${wfs}Guide set nodbchopb Off
            }
            B {
               cs ${wfs}Guide set nodachopa Off
               cs ${wfs}Guide set nodachopb Off
               cs ${wfs}Guide set nodbchopa Off
               cs ${wfs}Guide set nodbchopb On
            }
            AB {
               cs ${wfs}Guide set nodachopa On
               cs ${wfs}Guide set nodachopb Off
               cs ${wfs}Guide set nodbchopa Off
               cs ${wfs}Guide set nodbchopb On
            }
         }
      }
      antiNod {
         switch $nodstate {
            A {
               cs ${wfs}Guide set nodachopa Off
               cs ${wfs}Guide set nodachopb On
               cs ${wfs}Guide set nodbchopa Off
               cs ${wfs}Guide set nodbchopb Off
            }
            B {
               cs ${wfs}Guide set nodachopa Off
               cs ${wfs}Guide set nodachopb Off
               cs ${wfs}Guide set nodbchopa On
               cs ${wfs}Guide set nodbchopb Off
            }
            AB {
               cs ${wfs}Guide set nodachopa Off
               cs ${wfs}Guide set nodachopb On
               cs ${wfs}Guide set nodbchopa On
               cs ${wfs}Guide set nodbchopb Off
            }
         }
      }
      default {
         cs ${wfs}Guide set nodachopa Off
         cs ${wfs}Guide set nodachopb Off
         cs ${wfs}Guide set nodbchopa Off
         cs ${wfs}Guide set nodbchopb Off
      }
   }
   logger command ${wfs}Guide
}

itcl::body Guide::preview {view} {
   if { ! [string equal $pwfs1Wavel ""] } {
      $view configure -p1Wavel $pwfs1Wavel
   }
   if { ! [string equal $pwfs2Wavel ""] } {
      $view configure -p2Wavel $pwfs2Wavel
   }
   if { ! [string equal $oiwfsWavelength ""] } {
      ::OIWFSWavelengthNames::$oiwfsWavelength preview $view oiwfs
   }
}
