#+
#  HandsetPanel <- Panel
#
#  Implements the HandsetPanel widget. A Panel widget with various
#  HandsetControl widgets packed into its interior.
#
#  Options:
#          none
#
#  Methods:
#          none
#
#  D Terrett 1 May 2001
#
#  Copyright CCLRC
#+

itcl::class HandsetPanel {
   inherit Panel
   constructor args {}
}

itk::usual HandsetPanel {
   keep -background -cursor
}

itcl::body HandsetPanel::constructor args {

# Notebook for the handset controls.
   itk_component add handsets {
      iwidgets::tabnotebook $itk_interior.targets -height 610 -width 450 \
            -tabpos n -equaltabs no
   } {
      ignore -background -tabbackground
   }

   setWidgetColors "$itk_component(menubar) $itk_component(handsets)" \
         $itk_option(-background) $itk_option(-foreground)

# Target handset
   set w [$itk_component(handsets) add -label Targets -background pink \
         -tabbackground pink]
   itk_component add targets {
      TargetHandsetControl $w.targets -background pink
   }
   pack $itk_component(targets)

# Guiding handset
   set w [$itk_component(handsets) add -label Guiding -background yellow \
         -tabbackground yellow ]
   itk_component add guiding {
      GuideHandsetControl $w.guiding -background yellow
   } {
      ignore -background
   }
   pack $itk_component(guiding)

# Pointing origin handset
   set w [$itk_component(handsets) add -label "Instrument Origins" \
         -background yellowgreen -tabbackground yellowgreen]
   itk_component add po {
      PoHandsetControl $w.po -background yellowgreen
   }
   pack $itk_component(po)

   $itk_component(handsets) select Targets

   pack $itk_component(handsets) -fill both -expand y

   eval itk_initialize $args
}
