#+
#  HandsetPanel <- Panel
#
#  Implements the HandsetPanel widget. A Panel widget with various
#  HandsetControl widgets packed into its interior.
#
#  Options:
#          none
#
#  Methods:
#          none
#
#  D Terrett 11 June 2001
#
#  Copyright CCLRC
#+

itcl::class HandsetPanel {
   inherit Panel
   constructor args {}
   
# $itk_component(handsets) config -background achieves this
# but reconfigures the whole widget, which look bad on the screen
# this avoid annoying flashing and does the job
   private method pageSelectCB { color } {
      [$itk_component(handsets) component tabset] config \
            -selectbackground $color
      [$itk_component(handsets) component canvas] config -bg $color
   }
}

itk::usual HandsetPanel {
   keep -background -cursor
}

itcl::body HandsetPanel::constructor args {

# Notebook for the handset controls.
   itk_component add handsets {
      iwidgets::tabnotebook $itk_interior.targets -height 610 -width 450 \
            -tabpos n -equaltabs no
   } {
      ignore -background -tabbackground
   }

   setWidgetColors "$itk_component(menubar) $itk_component(handsets)" \
         $itk_option(-background) $itk_option(-foreground)

# Target handset
   set w [$itk_component(handsets)  add -label "Targets" \
         -background "#add8e6" -tabbackground  "#add8e6" \
         -command [code $this pageSelectCB #add8e6]]
   itk_component add targets {
      TargetHandsetControl $w.targets -background "#add8e6"
   }
   pack $itk_component(targets)

# Guiding handset
   set w [$itk_component(handsets) add -label "Pointing" -background "#ffdab9" \
         -tabbackground "#ffdab9"  -command [code $this pageSelectCB #ffdab9]]
   itk_component add guiding {
      GuideHandsetControl $w.guiding -background "#ffdab9"
   }
   pack $itk_component(guiding)
   
# fix the 'radiobox buttons are not red' problem
# not sure why this happens in the first place
   [[$itk_component(guiding) component handset ] component orient] configure \
         -selectcolor #b03060

# Pointing origin handset
   set w [$itk_component(handsets) add -label "Instrument Origins" \
         -background "#fffacd" -tabbackground "#fffacd" \
         -command [code $this pageSelectCB #fffacd]]
   itk_component add po {
      PoHandsetControl $w.po -background "#fffacd"
   }
   pack $itk_component(po)

   $itk_component(handsets) select Targets

   pack $itk_component(handsets) -fill both -expand y

   eval itk_initialize $args
}
