#+
#  Instrument
#
#  Implements the Instrument class. An Instrument object stores an 
#  instrument alignment angle.
#
#  Options:
#          -centralBaffle     The position of the M2 central baffle ("open"
#                             "closed" or "").
#
#          -deployableBaffle  The position of the M2 deployable baffle
#                             ("thermal IR", "near IR", "optical",
#                             "maintenance" or "").
#
#          -focusOffset       The focus offset to apply.
#
#          -iaa               The instrument alignment angle.
#
#          -issFace           The ISS face on which the instrument is 
#                             mounted ("port 1", "port 3" or "port 5").
#
#  Methods:
#          apply args  Applies the iaa to the TCS by setting the values of 
#                      the command parameters. Any method arguments are 
#                      ignored.
#
#          init        Returns the instrument object to its initial state.
#
#          preview     Sets the preview instrument configuration.
#
#          save        Writes the values of the options to the channel 
#                      identifier "file".
#
#  Procs:
#           subcomponents   Returns a list of the subcomponents of the
#                           Instrument objects (an empty list).
#
#  D Terrett 27 September 2000
#
#  Copyright CCLRC
#+

itcl::class Instrument {

   public proc subcomponents {} {return {}}

   public method apply args
   public method init
   public method preview
   public method save file

   public variable iaa ""
   public variable issFace "port 1"
   public variable centralBaffle ""
   public variable deployableBaffle ""
   public variable focusOffset ""
}

itcl::body Instrument::apply args {

# Set iaa and focus.
   if { ![string is space $iaa] } {
      cs rotator set iaa \"$iaa\"
      logger command rotator
   }
   if { ![string is space $focusOffset] } {
      cs dtelFocus set focusOffset \"$focusOffset\"
      logger command dtelFocus
   }

# Configure ISS object.
   switch $centralBaffle {
      closed {cs m2Baffle set centralBaffle POS1}
      open {cs m2Baffle set centralBaffle POS2}
   }
   switch $deployableBaffle {
      "thermal IR" {cs m2Baffle set deployBaffle RETRACTED}
      "near IR" {cs m2Baffle set deployBaffle POS1}
      optical {cs m2Baffle set deployBaffle POS2}
      maintenance {cs m2Baffle set deployBaffle EXTENDED}
   }
   if { !( [string is space $centralBaffle] && \
         [string is space $deployableBaffle] ) } {
      logger command m2Baffle
   }
   switch $issFace {
      "port 1" {iss configure -port 1}
      "port 3" {iss configure -port 3}
      "port 5" {iss configure -port 5}
   }

# Update ISS with new configuration.
   iss update
}

itcl::body Instrument::init {} {
   set iaa 0
   set issFace "port 1"
   set centralBaffle ""
   set deployableBaffle ""
   set focusOffset 0
}

itcl::body Instrument::preview {} {
   tccPreview set iaa $iaa
}

itcl::body Instrument::save file {
   puts $file "   -iaa \"$iaa\" \\"
   puts $file "   -issFace \"$issFace\" \\"
   puts $file "   -centralBaffle \"$centralBaffle\" \\"
   puts $file "   -deployableBaffle \"$deployableBaffle\" \\"
   puts $file "   -focusOffset \"$focusOffset\""
}
