#+
#  Instrument
#
#  Implements the Instrument class. An Instrument object stores an 
#  instrument alignment angle.
#
#  Options:
#          -centralBaffle     The position of the M2 central baffle ("open"
#                             "closed" or "").
#
#          -deployableBaffle  The position of the M2 deployable baffle
#                             ("thermal IR", "near IR", "visible",
#                             "maintenance" or "").
#
#          -focusOffset       The focus offset to apply.
#
#          -iaa               The instrument alignment angle.
#
#          -issPort           The ISS port on which the instrument is 
#                             mounted.
#
#          -name              The name of the instrument (as know to the A&G).
#
#  Methods:
#          apply args  Applies the iaa to the TCS by setting the values of 
#                      the command parameters. Any method arguments are 
#                      ignored.
#
#          init        Returns the instrument object to its initial state.
#
#          preview     Sets the preview instrument configuration.
#
#          save        Writes the values of the options to the channel 
#                      identifier "file".
#
#  Procs:
#           subcomponents   Returns a list of the subcomponents of the
#                           Instrument objects (an empty list).
#
#  D Terrett 17 July 2001
#
#  Copyright CCLRC
#+

itcl::class Instrument {
   public proc subcomponents {} {return {}}
   public {
      method apply {args}
      method init {}
      method preview {}
      method save {file}
      variable iaa ""
      variable issPort 1
      variable centralBaffle open
      variable deployableBaffle ""
      variable focusOffset ""
      variable name ""
   }
}

itcl::body Instrument::apply args {

# Set iaa and focus.
   if { ![string is space $iaa] } {
      cs rotator set iaa [list $iaa]
      logger command rotator
   }
   if { ![string is space $focusOffset] } {
      cs dtelFocus set focusOffset [list $focusOffset]
      logger command dtelFocus
   }

# Configure ISS object.
   switch $centralBaffle {
      closed {cs m2Baffle set centralBaffle Closed}
      open {cs m2Baffle set centralBaffle Open}
   }
   switch $deployableBaffle {
      "thermal IR" {cs m2Baffle set deployBaffle Retracted}
      "near IR" {cs m2Baffle set deployBaffle [list "Near IR"]}
      visible {cs m2Baffle set deployBaffle Visible}
      maintenance {cs m2Baffle set deployBaffle Extended}
   }
   if { !( [string is space $centralBaffle] && \
         [string is space $deployableBaffle] ) } {
      logger command m2Baffle
   }
   iss configure -port $issPort -instrument $name

# Update ISS with new configuration.
   iss update
}

itcl::body Instrument::init {} {
   set iaa 0
   set issFace 1
   set centralBaffle ""
   set deployableBaffle ""
   set focusOffset 0
   set name ""
}

itcl::body Instrument::preview {} {
   if { [string length $iaa] } {
      tccPreview set iaa $iaa
   } else {
      tccPreview set iaa 0.0
   }
}

itcl::body Instrument::save file {
   puts $file "   -iaa [list $iaa] \\"
   puts $file "   -issPort [list $issPort] \\"
   puts $file "   -centralBaffle [list $centralBaffle] \\"
   puts $file "   -deployableBaffle [list $deployableBaffle] \\"
   puts $file "   -focusOffset [list $focusOffset] \\"
   puts $file "   -name [list $name]"
}
