#+
#  InstrumentPanel <- Panel
#
#  Implements the InstrumentPanel widget. A Panel widget with a 
#  InstrumentControl widget packed into its interior.
#
#  Methods:
#          none
#
#  D Terrett 28 March 2001
#
#  Copyright CCLRC
#+

itcl::class InstrumentPanel {
   inherit Panel
   constructor args {}
}

itk::usual InstrumentPanel {
   keep -background -cursor
}

itcl::body InstrumentPanel::constructor args {
   itk_component add control {
      InstrumentControl $itk_interior.control
   }
   setWidgetColors "$itk_component(menubar) $itk_component(control)" \
            $itk_option(-background) $itk_option(-foreground)

   pack $itk_component(control) -fill both -expand y

   set itk_option(-windows) $itk_component(control)

   eval itk_initialize $args
}
