#+
#  InstrumentComponent <- Instrument, tcclib::Component
#
#  An InstrumentComponent object is a Instrument object that is stored in a 
#  configuration list.
#
#  Options:
#           none
#
#  Methods:
#           constructor list  Creates the Instrument object and puts it onto
#                           "list".
#
#           save file       Writes commands to re-create the object to the
#                           channel identifier "file" and then calls the
#                           Instrument save method to add the objects data.
#
#  D Terrett 15 March 2001
#
#  Copyright CCLRC
#+

itcl::class InstrumentComponent {
   inherit Instrument tcclib::Component
   constructor {list args} {
      tcclib::Component::constructor $list
   } {
      eval configure $args
   }
   public {
      method save {file}
   }
}

itcl::body InstrumentComponent::save file {
   set obj [namespace tail $this]
   set namespace [namespace qualifiers $this]
   puts $file \
         "catch {InstrumentComponent [list ${namespace}::$obj]  $componentList}"
   puts $file "[list ${namespace}::$obj] init"
   puts $file "[list ${namespace}::$obj] configure \\"
   Instrument::save $file
}
