#+
#  InstrumentComponent.itcl
#
#  Implements the InstrumentComponent class. An InstrumentComponent object 
#  is an Instrument object that is stored in a configuration.
#
#  D Terrett 19 August 1999
#
#  Copyright CCLRC
#+

itcl::class InstrumentComponent {
   inherit Instrument Component

   constructor {list args} {
      Component::constructor $list
   } {
      eval configure $args
   }

   public method save file
}

itcl::body InstrumentComponent::save file {
   set objname [namespace tail $this]
   set namespace [namespace qualifiers $this]
   puts $file "catch {delete object \"${namespace}::$objname\"}"
   puts $file "InstrumentComponent \"${namespace}::$objname\"  $componentList \\"
   Instrument::save $file
}
