#+
#  ISS
#
#  Implements the ISS class. An ISS object (of which only one is expected to
#  exist) maps the observing mode (Sky, Calibration or TV) and AO
#  configuration (in or out) into the necessary configuration of the fold
#  mirrors in the instrument support structure. The "update" method actually
#  moves the mirrors to the desired positions.
#
#  Options:
#          -mode   The current mode of operation (SKY - the instrument can
#                  see the sky, TV - the aquisition TV/HRWFS can see the
#                  sky or CAL - the instrument can see the calibration unit.
#
#          -ao     The state of the AO fold mirror (IN or OUT).
#
#          -port   The ISS port on which the currently active instrument
#                  is mounted (1-5). Port 1 is the upward looking port.
#
#          -instrument  The name of the instrument as known to the A&G.
#
#  Methods:
#          update  Moves the science fold mirror, AO pickoff mirror and
#                  HRWFS mirrors into the correct position to realise the
#                  settings ofthe -mode, -ao and -port options.
#
#  D Terrett 3 May 2002
#
#  Copyright CCLRC
#+

itcl::class ISS {
   public {
      method update {}
      proc gpolwait {}
      variable mode SKY position
      variable ao OUT position
      variable port 1 position
      variable instrument "" position
   }
   private {
      method position {}
      common waitid ""
      variable scfold ""
      variable hwfold ""
      variable aofold ""
   }
}

itcl::body ISS::position {} {

# Assume that we won't need to move the HRWFS or AO fold.
   set hwfold ""
   set aofold ""

# The pseudo port AC is a special case where the Acquisition Camera is
# being treaded as a instrument.
   if { [string equal $port AC] } {

# The HRWFS fold is always in.
      set hwfold IN
      switch $mode {
         TV {

# Park the science fold and AO fold.
            set scfold OUT
            set aofold OUT
         }
         SKY {
 
# Park the science fold and set the AO fold according to whether ao is on 
# or off.
            set scfold OUT
            if { [string equal $ao IN] } {
               set aofold IN
            } else {
               set aofold OUT
            }
         }
         CAL {

# Position the science fold.
            set scfold gcal2ac
         }
      }
   } else {
      switch $mode {

# If the mode is TV then the HRWFS fold must be IN and the science fold
# and AO fold out.
         TV {
            set hwfold IN
            set scfold OUT
            set aofold OUT
         }
         SKY {
   
# If the active ISS port is the upward looking one then the HRWFS fold must
# be OUT and the Science fold positioned according to the instrument name
# and port.
            if { $port == 1 } {
               set hwfold OUT
               if { [string equal $ao IN] } {
                  set aofold IN
                  set scfold ao2${instrument}${port}
               } else {
                  set aofold OUT
                  set scfold OUT
               }
            } else {
   
# Otherwise the the HRWFS fold can be left where it is and the science fold
# position just depends on whether the AO is in or out.
               if { [string equal $ao IN] } {
                  set aofold IN
                  set scfold ao2${instrument}${port}
               } else {
                  set aofold OUT
                  set scfold ${instrument}${port}
               }
            }
         }
         CAL {

# For the calibration source we just need to set the science fold position
# and if the port is port 1 remove the HRWFS fold.
            if { $port == 1 } {
               set hwfold OUT
            }
            set scfold gcal2${instrument}${port}
         }
      }
   }
}

itcl::body ISS::update {} {

# Kill off any pending attempt to deploy the HRWFS pickoff mirror.
   after cancel $waitid

# Position HRWFS pickoff mirror. Before moving it into the beam we must
# check that GPOL is parked.
   switch $hwfold {
      IN {
         if { [sa gpolsad get upperParkSwitch] == "OPEN" ||
               [sa gpolsad get middleParkSwitch] == "OPEN" ||
               [sa gpolsad get lowerParkSwitch] == "OPEN" } {

# Park GPOL. This takes a long time and we can't move the HRWFS mirror
# until it is ready.
            cs gpolPark set dummy value MARK
            logger command gpolPark

# Start a background task that polls GPOL until it is parked.
            set waitid [after 1000 ISS::gpolwait]
         } else {
            cs hrwfs set hwfold value $hwfold
            logger command hrwfs
         }
      }
      OUT {
         cs hrwfsPark set dummy value MARK
         logger command hrwfsPark
      }
   }
#   if { ! [string equal $aofold ""] } {
#      cs aoFold set aofold value $aofold
#      logger command aoFold
#   }
   if { ! [string equal $scfold ""] } {
      if { [string equal $scfold "OUT"] } {
         cs scienceFoldPark set dummy value MARK
         logger command scienceFoldPark
      } else {
         cs scienceFold set scfold value $scfold
         logger command scienceFold
      }
   }
}

itcl::body ISS::gpolwait {} {
puts gpolwait
   if { [sa gpolsad get upperParkSwitch] == "OPEN" ||
        [sa gpolsad get middleParkSwitch] == "OPEN" ||
        [sa gpolsad get lowerParkSwitch] == "OPEN" } {

# Not ready yet so try again later.
     set waitid [after 1000 ISS::gpolwait]
   } else {

# GPOL is parked so we can put the HRWFS fold in.
      cs hrwfs set hwfold value IN
      logger command hrwfs
      if { [catch {cs hrwfs post} msg] } {
         tk_messageBox -icon error -message \
               "Error posting commands: TCS reports \"$msg\""
      }
   }
}
