#+
#  ISS
#
#  Implements the ISS class. An ISS object (of which only one is expected to
#  exist) maps the observing mode (Sky, Calibration or TV) and AO
#  configuration (in or out) into the necessary configuration of the fold
#  mirrors in the instrument support structure. The "update" method actually
#  moves the mirrors to the desired positions.
#
#  Options:
#          -mode   The current mode of operation (SKY - the instrument can
#                  see the sky, TV - the aquisition TV/HRWFS can see the
#                  sky or CAL - the instrument can see the calibration unit.
#
#          -ao     The state of the AO fold mirror (IN or OUT).
#
#          -port   The ISS port on which the currently active instrument
#                  is mounted (1-5). Port 1 is the upward looking port.
#
#  Methods:
#          update  Moves the science fold mirror, AO pickoff mirror and
#                  HRWFS mirrors into the correct position to realise the
#                  settings ofthe -mode, -ao and -port options.
#
#  D Terrett 5 February 2001
#
#  Copyright CCLRC
#+

itcl::class ISS {
   public {
      method update {}
      variable mode SKY position
      variable ao OUT position
      variable port 1 position
   }
   private {
      method position {}
      variable scfold ""
      variable hwfold ""
      variable aofold ""
   }
}

itcl::body ISS::position {} {

# Assume that we won't need to move the HRWFS or AO fold.
   set hrfold ""
   set aofold ""

# The position of the AO fold depends only on the AO configuration
   set aofold $ao

# If the mode is TV then the HRWFS fold must be IN and the science fold 
# either retracted (no AO) or set to reflect port 2 (which is where the AO 
# unit is attached) to port 1 (the upward looking port).
   if { [string compare $mode "TV"] == 0 } {
      set hwfold IN
      if { [string compare $ao "IN"] == 0 } {
         set scfold 8
      } else {
         set scfold "OUT"
      }
   } elseif { [string compare $mode "SKY"] == 0 } {

# If the active ISS port is the upward looking one then the HRWFS fold must
# be either OUT (no AO) or set to reflect port 2 to the port 1.
      if { $port == 1 } {
         set hwfold OUT
         if { [string compare $ao "IN"] == 0 } {
            set scfold 8
         } else {
            set scfold OUT
         }
      } else {

# Otherwise the the HRWFS fold can be left where it is and the science fold
# position just depends on whether the AO is in or out.
         if { [string compare $ao "IN"] == 0 } {
            switch $port {
               3 {set scfold 4}
               4 {set scfold OUT}
               5 {set scfold 7}
            }
         } else {
            switch $port {
               2 {set scfold 1}
               3 {set scfold 0}
               4 {set scfold 4}
               5 {set scfold 2}
            }
         }
      }
   } else {

# Remaning mode is CAL.
      switch $port {
         1 {set scfold 11}
         2 {set scfold OUT}
         3 {set scfold 5}
         5 {set scfold 9}
      }
   }
}

itcl::body ISS::update {} {
   if { $hwfold != "" } {
      cs hrwfs set hwfold value $hwfold
      logger command hrwfs
   }
#   if { $aofold != "" } {
#      cs aoFold set aofold value $aofold
#      logger command aoFold
#   }
   if { $scfold != "" } {
      if { $scfold == "OUT" } {
         cs scienceFoldPark set dummy value MARK
         logger command scienceFoldPark
      } else {
         cs scienceFold set scfold value $scfold
         logger command scienceFold
      }
   }
}
