#+
#  LiveButton <- itk::Widget
#
#  Implements the LiveButton class. A LiveButton is simply a push button
#  that in some way sends a command to the telescope. It is a distinct class
#  so that all such buttons can be made distinctive in some way and can
#  have additional behaviour (such as a confirmation dialog or a locked state
#  that prevents the telescope being moved). An optional message is sent to
#  the logger when the button is pressed.
#
#  The distinctive feature at present is that the active background colour
#  is red.
#
#  Options:
#          -command      A command to be executed when the button is pressed.
#
#          -logmessage - The message to send to the logger when the command 
#                        is executed.
#
#  Methods:
#          none
#
#  D Terrett 27 October 1998
#
#  Copyright CCLRC
#-

itcl::class LiveButton {
   inherit itk::Widget

   constructor args {}

   itk_option define -command command Command {}
   itk_option define -logmessage logMessage LogMessage {}

   private method command
}

itk::usual LiveButton {
   keep -activeforeground -background -cursor -disabledforeground \
         -foreground -font -highlightcolor -highlightthickness -width
}

itcl::body LiveButton::constructor args {

   itk_component add button {
      button $itk_interior.button -activebackground red \
         -command [code $this command]
   } {
      usual
      keep -state -text -width
      ignore -activebackground
   }
   pack $itk_component(button) -fill both -expand y

   eval itk_initialize $args
}

itcl::body LiveButton::command {} {
   if { $itk_option(-command) != "" } {
      if { [catch {uplevel #0 $itk_option(-command)} msg] } {
         logger log "$itk_option(-logmessage) rejected..."
         logger log $msg
         tk_messageBox -icon error -parent $itk_interior -message $msg
      } else {
         if { $itk_option(-logmessage) != "" } {
            logger log $itk_option(-logmessage)
         }
      }
   }
}
