#+
#  LogControl <- itk::Widget
#
#  A LogControl is a window that displays log messages.
#
#  Options:
#           none
#
#  Methods:
#           add text        Adds a line of text to the window.
#
#
#  D Terrett 24 November 1999
#
#  Copyright CCLRC
#+

itcl::class LogControl {
   inherit itk::Widget

   constructor args {}

   public method add text
}

itk::usual LogControl {
   keep -activebackground -activerelief -background -borderwidth -cursor \
         -elementborderwidth -foreground -highlightcolor -highlightthickness \
         -insertbackground -insertborderwidth -insertofftime -insertontime \
         -insertwidth -jump -labelfont -selectbackground -selectborderwidth \
         -selectforeground -textbackground -textfont -troughcolor 
}

itcl::body LogControl::constructor args {

   itk_component add display {
      iwidgets::scrolledtext $itk_interior.display
   }
   pack $itk_component(display) -fill both -expand y
   eval itk_initialize $args
}

itcl::body LogControl::add text {
   $itk_component(display) insert end \n$text
   $itk_component(display) see end
}
