#+
#  ObservePanel <- tcclib::Panel
#
#  Implements the ObservePanel widget. A Panel widget with a ObserveControl
#  widget packed into its interior
#
#  Options:
#          none
#
#  Methods:
#          none
#
#  D Terrett 29 March 2001
#
#  Copyright CCLRC
#+

itcl::class ObservePanel {
   inherit tcclib::Panel
   constructor args {}
}

itk::usual ObservePanel {
   keep -background -cursor
}

itcl::body ObservePanel::constructor args {

   itk_component add control {
      ObserveControl $itk_interior.control
   }

   setWidgetColors "$itk_component(menubar) $itk_component(control)" \
         $itk_option(-background) $itk_option(-foreground)

   pack $itk_component(control) -fill both -expand y

   eval itk_initialize $args
}
