#+
#  ObserveControl <- itk::Widget
#
#  Options:
#           none
#
#  Methods:
#           none
#
#  D Terrett  2 July 2001
#
#  Copyright CCLRC
#+

itcl::class ObserveControl {
   inherit itk::Widget
   constructor args {}
   private {
      method setfold {state}
      method setnod {state}
      method center {p par}
   }
}

itk::usual ObserveControl {
   keep -cursor -highlightthickness -onbackground
}

itcl::body ObserveControl::constructor args {

   set w $itk_interior

   itk_component add guideloop {
      GuideLoop $w.guideloop
   }
   pack $itk_component(guideloop)

# Acquisition Camera/HRWFS controls.
   itk_component add acqcam {
      Acqcam $w.acqcam
   }

   itk_component add buttons {
      frame $w.buttons
   }
   pack $itk_component(acqcam) $itk_component(buttons) -side left
   set w $itk_component(buttons)

# Selectbutton for configuring the A & G fold mirrors.
   itk_component add foldlab {
      label $w.foldlab -text "Fold mirrors"
   }
   itk_component add fold {
      SelectButton $w.fold -command [code $this setfold] -orient vertical
   } {
      usual
      rename -offbackground -background background Background
   }
   $itk_component(fold) add Sky->Instr 
   $itk_component(fold) add Cal->Instr
   $itk_component(fold) add Sky->AC/WFS

# Buttons for controlling chopping and M2 beam.
   itk_component add choplab {
      label $w.choplab -text Chop/Nod
   }
   itk_component add beam {
      BeamSelector $w.beam
   }
   itk_component add chop {
      OnOffButton $w.chop -text Chop -oncommand {chop chop On} \
            -offcommand {chop chop off} -sadrecord {m2ssad chopping} \
            -onvalue YES -offvalue NO
   }
   itk_component add noda {
      StateButton $w.noda -text "Nod A" -setcommand {nod nod A} \
            -sadrecord {tcssad nodState} -setvalue A
   }
   itk_component add nodb {
      StateButton $w.nodb -text "Nod B" -setcommand {nod nod B} \
            -sadrecord {tcssad nodState} -setvalue B
   }

# PWFS1 controls.
   itk_component add p1lab {
      label $w.p1lab -text "P1 probe"
   }
   itk_component add p1follow {
      OnOffButton $w.p1follow -text Follow \
            -oncommand {p1Follow followState On} \
            -offcommand {p1Follow followState Off} \
            -onvalue {ON On} -offvalue {OFF Off} \
            -sadrecord {agssad p1FollowS}
   }
   itk_component add p1flip {
      tcclib::ApplyButton $w.p1flip -command pwfs1Flip -text "Flip arm"
   }
   itk_component add p1unwrap {
      tcclib::ApplyButton $w.p1unwrap -command pwfs1Unwrap -text Unwrap
   }
   itk_component add p1center {
      tcclib::ApplyButton $w.p1center -command pwfs1Move -text Center \
            -parcommand [code $this center 1]
   }
   itk_component add p1park {
      tcclib::ApplyButton $w.p1park -command pwfs1Park -text Park
   }

# PWFS2 controls.
   itk_component add p2lab {
      label $w.p2lab -text "P2 probe"
   }
   itk_component add p2follow {
      OnOffButton $w.p2follow -text Follow \
            -oncommand {p2Follow followState On} \
            -offcommand {p2Follow followState Off} \
            -onvalue {ON On} -offvalue {OFF Off} \
            -sadrecord {agssad p2FollowS}
   }
   itk_component add p2flip {
      tcclib::ApplyButton $w.p2flip -command pwfs2Flip -text "Flip arm"
   }
   itk_component add p2unwrap {
      tcclib::ApplyButton $w.p2unwrap -command pwfs2Unwrap -text Unwrap
   }
   itk_component add p2park {
      tcclib::ApplyButton $w.p2park -command pwfs2Park -text Park
   }
   itk_component add p2center {
      tcclib::ApplyButton $w.p2center -command pwfs2Move -text Center \
            -parcommand [code $this center 2]
   }

   grid $itk_component(foldlab) \
         $itk_component(choplab) $itk_component(p1lab) \
         $itk_component(p2lab) -sticky ew -padx 5
   grid $itk_component(fold) $itk_component(chop) \
         $itk_component(p1follow) $itk_component(p2follow) -sticky ew -padx 5
   grid x $itk_component(beam) $itk_component(p1flip) \
         $itk_component(p2flip) -sticky ew -padx 5
   grid x x $itk_component(p1unwrap) \
         $itk_component(p2unwrap) -sticky ew -padx 5
   grid x $itk_component(noda) $itk_component(p1center) \
         $itk_component(p2center) -sticky ew -padx 5
   grid x $itk_component(nodb) $itk_component(p1park) $itk_component(p2park) \
         -sticky ew -padx 5
   grid configure $itk_component(fold) -rowspan 3
   grid configure $itk_component(beam) -rowspan 2

# Create command senders.
   if { [catch {cs chop info}] } {
      epics cs chop
   }
   if { [catch {cs m2beam info}] } {
      epics cs m2beam
   }
   if { [catch {cs nod info}] } {
      epics cs nod
   }

   eval itk_initialize $args
}

itcl::body ObserveControl::setfold state {
   switch $state {
      Sky->Instr {iss configure -mode SKY}
      Cal->Instr {iss configure -mode CAL}
      Sky->AC/WFS {iss configure -mode TV}
   }
   iss update
   if { [catch {cs tcsApply post} msg] } {
      tk_messageBox -icon error -parent $itk_interior -message $msg
   }
}

itcl::body ObserveControl::setnod state {
   switch $state {
      "Nod A" {
         cs nod set nod value A
       }
      "Nod B" {
         cs nod set nod value B
       }
   }
   logger command nod
   if { [catch {cs tcsApply post} msg] } {
      tk_messageBox -icon error -parent $itk_interior -message $msg
   }
}

itcl::body ObserveControl::center {p par} {
   switch $par {
      x {
         return [calparam cget -pwfs${p}_center_x]
      }
      y {
         return [calparam cget -pwfs${p}_center_y]
      }
      z {
         return [calparam cget -pwfs${p}_center_z]
      }
   }
}
