#+
#  ObserveControl <- itk::Widget
#
#  Options:
#           none
#
#  Methods:
#           none
#
#  D Terrett  16 January 2004
#
#  Copyright CCLRC
#+

itcl::class ObserveControl {
   inherit itk::Widget
   constructor args {}
   destructor {}
   public {
      method reset {} {$itk_component(guideloop) reset}
   }
   private {
      method setfold {path}
      method setnod {state}
      method center {p par}
      method wfssky {}
      method wfsql {}
      method wfsstop {}
      method selwfs {}
      variable wfs Pwfs1   
      variable Pwfs1Dark
      variable Pwfs2Dark
   }
}

itk::usual ObserveControl {
   keep -cursor -highlightthickness
}

itcl::body ObserveControl::constructor args {

   set w $itk_interior

# Guiding control picture.
   itk_component add guideloop {
      GuideLoop $w.guideloop
   }
   grid $itk_component(guideloop) -columnspan 5

# Sky offset control.
   itk_component add offframe {
      frame $w.offframe -borderwidth 2 -relief sunken
   }
   itk_component add offset {
      Sky $itk_component(offframe).offset
   }
   pack $itk_component(offset)
   grid $itk_component(offframe) -sticky ew -pady 5 -columnspan 5

# Acquisition Camera/HRWFS controls.
   itk_component add acqcam {
      AcqcamControl $w.acqcam
   }

# Fold mirrors.
   itk_component add mirrors {
      frame $w.mirrors  -bd 2 -relief ridge
   }

# WFS controls
   itk_component add wfs {
      frame $w.wfs -bd 2 -relief ridge
   }

# Various chop/node and WFS probe controls.
   itk_component add buttons {
      frame $w.buttons -bd 2 -relief ridge
   }

# Altair controls.
   itk_component add altair {
      AoControl $w.altair
   }

   grid $itk_component(acqcam) $itk_component(mirrors) $itk_component(wfs) \
         $itk_component(altair) -pady 5 -padx 5 -sticky s
   grid ^ ^ $itk_component(buttons) ^ -pady 5

# WFS controls.
   set w $itk_component(wfs)
   itk_component add wfssel {
      iwidgets::optionmenu $w.wfssel -command [itcl::code $this selwfs]
   }
   $itk_component(wfssel) insert end P1 P2 OI
   itk_component add dark {
      LiveButton $w.dark -text SKY -command [itcl::code $this wfssky]
   }
   itk_component add ql {
      LiveButton $w.ql -text Q/L -command [itcl::code $this wfsql]
   }
   itk_component add stop {
      LiveButton $w.stop -text STOP -command [itcl::code $this wfsstop]
   }
   grid $itk_component(wfssel) $itk_component(ql) $itk_component(dark) \
         $itk_component(stop)

# Button and option menu for configuring the A & G fold mirrors.
   set w $itk_component(mirrors)
   itk_component add lpath {
      SelectButton $w.lpath -command [itcl::code $this setfold] \
            -orient vertical
   } {
      usual
      rename -offbackground -background background Background
   }
   $itk_component(lpath) add "Sky>Instr"
   $itk_component(lpath) add "Sky>AO>Inst"
   $itk_component(lpath) add "GCAL>Instr"
   $itk_component(lpath) add "Sky>AC/HR"
   $itk_component(lpath) add "Sky>AO>AC/HR"
   $itk_component(lpath) add "AO cal>Instr"
   $itk_component(lpath) add "AO cal>AC/HR"
   pack $itk_component(lpath)

# Buttons for controlling chopping and M2 beam.
   set w $itk_component(buttons)
   itk_component add choplab {
      label $w.choplab -text Chop/Nod
   }
   itk_component add beam {
      BeamSelector $w.beam
   }
   itk_component add chop {
      OnOffButton $w.chop -text Chop -oncommand {chop chop On chop decs On} \
            -offcommand {chop chop Off chop decs Off} \
            -sadrecord {m2ssad chopping} -onvalue YES -offvalue NO
   }
   itk_component add noda {
      StateButton $w.noda -text "Nod A" -command {Nodder state A} \
            -sadrecord {tcssad nodState} -setvalue A
   }
   itk_component add nodb {
      StateButton $w.nodb -text "Nod B" -command {Nodder state B} \
            -sadrecord {tcssad nodState} -setvalue B
   }

# OIWFS follow and Park
   itk_component add oiwfs {
      frame $w.oiwfs
   }
   set w $itk_component(oiwfs)
   itk_component add oilab {
      label $w.lab -text OI   
   }
   itk_component add oifollow {
      OnOffButton $w.oifollow -text Follow \
            -oncommand {oiFollow followState On} \
            -offcommand {oiFollow followState Off} \
            -onvalue {ON On} -offvalue {OFF Off} \
            -sadrecord {agssad oiFollowS}
   }
   itk_component add oipark {
      ApplyButton $w.oipark -text Park -command oiwfsPark
   }
   pack $itk_component(oilab) $itk_component(oifollow) $itk_component(oipark) \
      -side left -fill x -padx 3

# PWFS1 controls.
   set w $itk_component(buttons)
   itk_component add p1lab {
      label $w.p1lab -text "P1 probe"
   }
   itk_component add p1follow {
      OnOffButton $w.p1follow -text Follow \
            -oncommand {p1Follow followState On} \
            -offcommand {p1Follow followState Off} \
            -onvalue {ON On} -offvalue {OFF Off} \
            -sadrecord {agssad p1FollowS}
   }
#   itk_component add p1flip {
#      ApplyButton $w.p1flip -command pwfs1Flip -text "Flip arm"
#   }
   itk_component add p1unwrap {
      ApplyButton $w.p1unwrap -command pwfs1Unwrap -text Unwrap
   }
#   itk_component add p1center {
#      ApplyButton $w.p1center -command pwfs1Move -text Center \
#            -parcommand [itcl::code $this center 1]
#   }
   itk_component add p1park {
      ApplyButton $w.p1park -command pwfs1Park -text Park
   }

# PWFS2 controls.
   itk_component add p2lab {
      label $w.p2lab -text "P2 probe"
   }
   itk_component add p2follow {
      OnOffButton $w.p2follow -text Follow \
            -oncommand {p2Follow followState On} \
            -offcommand {p2Follow followState Off} \
            -onvalue {ON On} -offvalue {OFF Off} \
            -sadrecord {agssad p2FollowS}
   }
#   itk_component add p2flip {
#      ApplyButton $w.p2flip -command pwfs2Flip -text "Flip arm"
#   }
   itk_component add p2unwrap {
      ApplyButton $w.p2unwrap -command pwfs2Unwrap -text Unwrap
   }
   itk_component add p2park {
      ApplyButton $w.p2park -command pwfs2Park -text Park
   }
#   itk_component add p2center {
#      ApplyButton $w.p2center -command pwfs2Move -text Center \
#            -parcommand [itcl::code $this center 2]
#   }

   grid $itk_component(choplab) $itk_component(p1lab) \
         $itk_component(p2lab) -sticky ew -padx 5
   grid $itk_component(chop) $itk_component(p1follow) \
         $itk_component(p2follow) -sticky ew -padx 5
   grid $itk_component(beam) $itk_component(p1unwrap) \
         $itk_component(p2unwrap) -sticky ew -padx 5
   grid $itk_component(noda) $itk_component(p1park) \
         $itk_component(p2park) -sticky ew -padx 5
   grid $itk_component(nodb) $itk_component(oiwfs) -sticky ew -padx 5
   grid configure $itk_component(beam) -rowspan 2
   grid configure $itk_component(oiwfs) -columnspan 2

# Create command senders.
   if { [catch {cs chop info}] } {
      epics cs chop
   }
   if { [catch {cs m2beam info}] } {
      epics cs m2beam
   }
   if { [catch {cs nod info}] } {
      epics cs nod
   }

# Create the objects for taking darks.
   set Pwfs1Dark [Dark #auto p1]
   set Pwfs2Dark [Dark #auto p2]

   eval itk_initialize $args
}

itcl::body ObserveControl::destructor {} {
   itcl::delete object $Pwfs1Dark
   itcl::delete object $Pwfs2Dark
}

itcl::body ObserveControl::setfold {path} {
   switch $path {
      "Sky>Instr" {iss configure -source SKY -sink INSTR -ao OUT}
      "Sky>AO>Inst" {iss configure -source AO -sink INSTR -ao IN}
      "GCAL>Instr" {iss configure -source CAL -sink INSTR}
      "Sky>AC/HR" {iss configure -source SKY -sink HRWFS -ao OUT}
      "Sky>AO>AC/HR" {iss configure -source AO -sink HRWFS -ao IN}
      "AO cal>Instr" {iss configure -source AO -sink HRWFS}
      "AO cal>AC/HR" {iss configure -source AO -sink HRWFS}
   }
   iss update
   if { [catch {cs tcsApply post} msg] } {
      tk_messageBox -icon error -parent $itk_interior -message $msg
   }
}

itcl::body ObserveControl::setnod state {
   switch $state {
      "Nod A" {
         cs nod set nod value A
       }
      "Nod B" {
         cs nod set nod value B
       }
   }
   logger command nod
   if { [catch {cs tcsApply post} msg] } {
      tk_messageBox -icon error -parent $itk_interior -message $msg
   }
}

itcl::body ObserveControl::center {p par} {
   switch $par {
      x {
         return [calparam cget -pwfs${p}_center_x]
      }
      y {
         return [calparam cget -pwfs${p}_center_y]
      }
      z {
         return [calparam cget -pwfs${p}_center_z]
      }
   }
}

itcl::body ObserveControl::wfssky {} {

# Take a dark with the selected WFS
   [set ${wfs}Dark] take
}

itcl::body ObserveControl::wfsstop {} {

# Stop the selected WFS.
   $wfs stop
}

itcl::body ObserveControl::wfsql {} {

# Start the selected WFS with the quick-look tool.
   $wfs configure -quicklook 1
   $wfs start -1
}

itcl::body ObserveControl::selwfs {} {
   switch [$itk_component(wfssel) get] {
      P1 {
         set wfs Pwfs1
         $itk_component(dark) configure -state normal
      }
      P2 {
         set wfs Pwfs2
         $itk_component(dark) configure -state normal
      }
      OI {
         set wfs Oiwfs
         $itk_component(dark) configure -state disabled
      }
   }
}
