#+
#  ObserveControl <- itk::Widget
#
#  Options:
#           none
#
#  Methods:
#           none
#
#  D Terrett  28 April 2003
#
#  Copyright CCLRC
#+

itcl::class ObserveControl {
   inherit itk::Widget
   constructor args {}
   private {
      method setfold {path}
      method setnod {state}
      method center {p par}
   }
}

itk::usual ObserveControl {
   keep -cursor -highlightthickness
}

itcl::body ObserveControl::constructor args {

   set w $itk_interior

# Guiding control picture.
   itk_component add guideloop {
      GuideLoop $w.guideloop
   }
   pack $itk_component(guideloop)

# Sky offset control.
   itk_component add offframe {
      frame $w.offframe -borderwidth 2 -relief sunken
   }
   itk_component add offset {
      Sky $itk_component(offframe).offset
   }
   pack $itk_component(offset)
   pack $itk_component(offframe) -fill x -expand yes -pady 5

# Acquisition Camera/HRWFS controls.
   itk_component add acqcam {
      AcqcamControl $w.acqcam
   }

# Fold mirrors.
   itk_component add mirrors {
      frame $w.mirros  -bd 2 -relief ridge
   }

# Various chop/node and WFS probe controls.
   itk_component add buttons {
      frame $w.buttons -bd 2 -relief ridge
   }

# Altair controls.
   itk_component add altair {
      AoControl $w.altair
   }

   pack $itk_component(acqcam) $itk_component(mirrors) $itk_component(buttons) \
         $itk_component(altair) -side left -pady 10 -padx 5 -anchor s

# Button and option menu for configuring the A & G fold mirrors.
   set w $itk_component(mirrors)
   itk_component add foldlab {
      label $w.foldlab -text "Light Path:"
   }
   itk_component add si {
      button $w.si -text "Sky>Instr" \
            -command [itcl::code $this setfold "Sky>Instr"]
   }
   itk_component add sai {
      button $w.sai -text "Sky>AO>Inst" \
            -command [itcl::code $this setfold "Sky>AO>Inst"]
   }
   itk_component add gi {
      button $w.gi -text "GCAL>Instr" \
            -command [itcl::code $this setfold "GCAL>Instr"]
   }
   itk_component add sh {
      button $w.sh -text "Sky>AC/HR" \
            -command [itcl::code $this setfold "Sky>AC/HR"]
   }
   itk_component add sah {
      button $w.sah -text "Sky>AO>AC/HR" \
            -command [itcl::code $this setfold "Sky>AO>AC/HR"]
   }
   itk_component add agi {
      button $w.agi -text "AO cal>Instr" \
            -command [itcl::code $this setfold "AO cal>Instr"]
   }
   itk_component add agh {
      button $w.agh -text "AO cal>AC/HR" \
            -command [itcl::code $this setfold "AO cal>AC/HR"]
   }
   pack $itk_component(si) $itk_component(sai) $itk_component(gi) \
         $itk_component(sh) $itk_component(sah) $itk_component(agi) \
         $itk_component(agh) -expand y -fill x

# Buttons for controlling chopping and M2 beam.
   set w $itk_component(buttons)
   itk_component add choplab {
      label $w.choplab -text Chop/Nod
   }
   itk_component add beam {
      BeamSelector $w.beam
   }
   itk_component add chop {
      OnOffButton $w.chop -text Chop -oncommand {chop chop On} \
            -offcommand {chop chop off} -sadrecord {m2ssad chopping} \
            -onvalue YES -offvalue NO
   }
   itk_component add noda {
      StateButton $w.noda -text "Nod A" -setcommand {nod nod A} \
            -sadrecord {tcssad nodState} -setvalue A
   }
   itk_component add nodb {
      StateButton $w.nodb -text "Nod B" -setcommand {nod nod B} \
            -sadrecord {tcssad nodState} -setvalue B
   }

# OIWFS follow
   itk_component add oifollow {
      OnOffButton $w.oifollow -text "OIWFS Follow" \
            -oncommand {oiFollow followState On} \
            -offcommand {oiFollow followState Off} \
            -onvalue {ON On} -offvalue {OFF Off} \
            -sadrecord {agssad oiFollowS}
   }

# PWFS1 controls.
   itk_component add p1lab {
      label $w.p1lab -text "P1 probe"
   }
   itk_component add p1follow {
      OnOffButton $w.p1follow -text Follow \
            -oncommand {p1Follow followState On} \
            -offcommand {p1Follow followState Off} \
            -onvalue {ON On} -offvalue {OFF Off} \
            -sadrecord {agssad p1FollowS}
   }
#   itk_component add p1flip {
#      ApplyButton $w.p1flip -command pwfs1Flip -text "Flip arm"
#   }
   itk_component add p1unwrap {
      ApplyButton $w.p1unwrap -command pwfs1Unwrap -text Unwrap
   }
#   itk_component add p1center {
#      ApplyButton $w.p1center -command pwfs1Move -text Center \
#            -parcommand [itcl::code $this center 1]
#   }
   itk_component add p1park {
      ApplyButton $w.p1park -command pwfs1Park -text Park
   }

# PWFS2 controls.
   itk_component add p2lab {
      label $w.p2lab -text "P2 probe"
   }
   itk_component add p2follow {
      OnOffButton $w.p2follow -text Follow \
            -oncommand {p2Follow followState On} \
            -offcommand {p2Follow followState Off} \
            -onvalue {ON On} -offvalue {OFF Off} \
            -sadrecord {agssad p2FollowS}
   }
#   itk_component add p2flip {
#      ApplyButton $w.p2flip -command pwfs2Flip -text "Flip arm"
#   }
   itk_component add p2unwrap {
      ApplyButton $w.p2unwrap -command pwfs2Unwrap -text Unwrap
   }
   itk_component add p2park {
      ApplyButton $w.p2park -command pwfs2Park -text Park
   }
#   itk_component add p2center {
#      ApplyButton $w.p2center -command pwfs2Move -text Center \
#            -parcommand [itcl::code $this center 2]
#   }

   grid $itk_component(choplab) $itk_component(p1lab) \
         $itk_component(p2lab) -sticky ew -padx 5
   grid $itk_component(chop) $itk_component(p1follow) \
         $itk_component(p2follow) -sticky ew -padx 5
   grid $itk_component(beam) $itk_component(p1unwrap) \
         $itk_component(p2unwrap) -sticky ew -padx 5
   grid $itk_component(noda) $itk_component(p1park) \
         $itk_component(p2park) -sticky ew -padx 5
   grid $itk_component(nodb) $itk_component(oifollow) -sticky ew -padx 5
   grid x $itk_component(oifollow) - -pady 3
   grid configure $itk_component(beam) -rowspan 2
   grid configure $itk_component(oifollow) -rowspan 2

# Create command senders.
   if { [catch {cs chop info}] } {
      epics cs chop
   }
   if { [catch {cs m2beam info}] } {
      epics cs m2beam
   }
   if { [catch {cs nod info}] } {
      epics cs nod
   }

   eval itk_initialize $args
}

itcl::body ObserveControl::setfold {path} {
   switch $path {
      "Sky>Instr" {iss configure -source SKY -sink INSTR -ao OUT}
      "Sky>AO>Inst" {iss configure -source AO -sink INSTR -ao IN}
      "GCAL>Instr" {iss configure -source CAL -sink INSTR}
      "Sky>AC/HR" {iss configure -source SKY -sink HRWFS -ao OUT}
      "Sky>AO>AC/HR" {iss configure -source AO -sink HRWFS -ao IN}
      "AO cal>Instr" {iss configure -source AO -sink HRWFS}
      "AO cal>AC/HR" {iss configure -source AO -sink HRWFS}
   }
   iss update
   if { [catch {cs tcsApply post} msg] } {
      tk_messageBox -icon error -parent $itk_interior -message $msg
   }
}

itcl::body ObserveControl::setnod state {
   switch $state {
      "Nod A" {
         cs nod set nod value A
       }
      "Nod B" {
         cs nod set nod value B
       }
   }
   logger command nod
   if { [catch {cs tcsApply post} msg] } {
      tk_messageBox -icon error -parent $itk_interior -message $msg
   }
}

itcl::body ObserveControl::center {p par} {
   switch $par {
      x {
         return [calparam cget -pwfs${p}_center_x]
      }
      y {
         return [calparam cget -pwfs${p}_center_y]
      }
      z {
         return [calparam cget -pwfs${p}_center_z]
      }
   }
}
