#+
#  ObservePanel.itk
#
#  Implements the ObservePanel widget. A Panel widget with a ObserveControl
#  widget packed into its interior
#
#  D Terrett 26 April 1999
#
#  Copyright CCLRC
#+

itcl::class ObservePanel {
   inherit Panel

   constructor args {}
}

itk::usual ObservePanel {
   keep -background -cursor
}

itcl::body ObservePanel::constructor args {

   itk_component add control {
      ObserveControl $itk_interior.control
   } {
      usual
      ignore -disabledforeground
      ignore -highlightcolor
      ignore -activebackground
      ignore -activeforeground
   }

   setWidgetColors "$itk_component(menubar) $itk_component(control)" \
         $itk_option(-background) $itk_option(-foreground)

   pack $itk_component(control) -fill both -expand y

   set itk_option(-windows) $itk_component(control)

   eval itk_initialize $args
}
