#+
#  OffsetHandsetPanel <- Panel
#
#  Implements the OffsetHandsetPanel widget. A Panel widget with a 
#  OffsetHandsetControl widget packed into its interior.
#
#  Options:
#          none
#
#  Methods:
#          none
#
#  D Terrett 24 November 1999
#
#  Copyright CCLRC
#+

itcl::class OffsetHandsetPanel {
   inherit Panel

   constructor args {}
}

itk::usual OffsetHandsetPanel {
   keep -background -cursor
}

itcl::body OffsetHandsetPanel::constructor args {

   itk_component add control {
      OffsetHandsetControl $itk_interior.control
   }
   setWidgetColors "$itk_component(menubar) $itk_component(control)" \
         $itk_option(-background) $itk_option(-foreground)

   pack $itk_component(control) -fill both -expand y

   set itk_option(-windows) $itk_component(control)

   eval itk_initialize $args
}
