#+
#  OffsetHandsetControl <- itk::Widget
#
#  A OffsetHandsetControl implements a software handset for adjusting
#  target positions.
#
#
#  Options:
#           none
#
#  Methods:
#           none
#
#  D Terrett 12 July 2000
#
#  Copyright CCLRC
#+

itcl::class OffsetHandsetControl {
   inherit itk::Widget

   constructor args {}

   private method offset dir
   private method offpars par
   private method setvt
   private method settang
   private method getOffset

   private variable tangent
   private variable currentstep -1
}

itk::usual OffsetHandsetControl {
   keep -borderwidth -cursor -font -highlightthickness -insertborderwidth \
         -insertofftime -insertontime -insertwidth -labelfont \
         -selectborderwidth -textbackground -textfont
}

itcl::body OffsetHandsetControl::constructor args {

# StepSize widget for setting the step associated with the paddle buttons.
   itk_component add top {
      frame $itk_interior.top -bd 2 -relief groove
   }
   pack $itk_component(top)

   set w $itk_component(top)
   itk_component add stepsize {
      StepSize $w.stepsize -text "Step size (arcsec)"
   }
   pack $itk_component(stepsize)

   itk_component add one {
      frame $itk_interior.one
   }
   pack $itk_component(one)
   set w $itk_component(one)

# Radio buttons for selecting which offset to adjust.
   itk_component add sel {
      iwidgets::radiobox $w.sel -command [code $this setvt]
   }
   $itk_component(sel) add Mount -text Mount
   $itk_component(sel) add A -text A
   $itk_component(sel) add B -text B
#   $itk_component(sel) add C -text C
   $itk_component(sel) add PWFS1 -text PWFS1
   $itk_component(sel) add PWFS2 -text PWFS2
   $itk_component(sel) add OIWFS -text OIWFS
   $itk_component(sel) add Source -text A+B
   $itk_component(sel) select Source
   pack $itk_component(sel) -side right

# Paddle buttons.
   itk_component add paddle {
      HandPaddleButtons $w.paddle \
            -upcommand [code $this offset D] -uplabel N\
            -downcommand [code $this offset U] -downlabel S \
            -leftcommand [code $this offset R] -leftlabel E \
            -rightcommand [code $this offset L] -rightlabel W
   }
   pack $itk_component(paddle)

# Check button for selecting tangent plane
   itk_component add tang {
      checkbutton $w.tang -text "Tangent Plane" -variable [scope tangent] \
            -command [code $this settang]
   }
   pack $itk_component(tang)
   set tangent 1
   settang

# Slider for adjusting the angle of the buttons.
   itk_component add slider {
      scale $itk_interior.slider -orient horizontal -to [expr 3.14159 * 2] \
            -command "$itk_component(paddle) configure -angle" \
            -resolution .01 -showvalue no
   }
   pack $itk_component(slider) -fill x -expand y

# Entry fields for entering an offset.
   itk_component add two {
      frame $itk_interior.two
   }
   pack $itk_component(two) -expand yes -fill x
   set w $itk_component(two)
   itk_component add theta1 {
      iwidgets::entryfield $w.theta1 -labeltext RA: -width 10
   }
   itk_component add theta2 {
      iwidgets::entryfield $w.theta2 -labeltext Dec: -width 10
   }
   itk_component add apply {
      ApplyButton $w.apply -text Apply -command incrOffset \
         -parcommand [code $this getOffset]
  }
   pack $itk_component(theta1) $itk_component(theta2) $itk_component(apply) \
      -side left

# Buttons for clearing and absorbing the offsets.
   itk_component add bot {
      frame $itk_interior.bot
   }
   pack $itk_component(bot) -expand yes -fill x
   set w $itk_component(bot)
   itk_component add absorb {
      ApplyButton $w.absorb -command absorbOffset -text "Absorb" -width 8 \
            -parcommand [code $this offpars]
   }
   itk_component add clear {
      ApplyButton $w.clear -command clearOffset -text "Clear" -width 8 \
            -parcommand [code $this offpars]
   }
   pack $itk_component(absorb) $itk_component(clear) -side left -expand y \
         -pady 4

   eval itk_initialize $args
}

itcl::body OffsetHandsetControl::offset dir {

# Set the step size if different from current.
   set step [$itk_component(stepsize) get]
   if { $step != $currentstep } {
      cs tarHandConfig set step $step
      logger command tarHandConfig
   }
   cs tarHandset set direction $dir
   logger command tarHandset
   if { [catch {cs tcsApply post} msg] } {
      tk_messageBox -icon error -parent $itk_interior -message \
            "Error adjusting offset: TCS reports \"$msg\""
   }
   set currentstep $step
}

itcl::body OffsetHandsetControl::offpars par {
   switch $par {
      vt {
         set vt [$itk_component(sel) get]
         switch $vt {
            Mount {return Mount}
            A {return "Source A"}
            B {return "Source B"}
            C {return "Source C"}
            PWFS1 {return PWFS1}
            PWFS2 {return PWFS2}
            OIWFS {return OIWFS}
            Source {return Source}
         }
      }
      index {return all}
   }
}

itcl::body OffsetHandsetControl::setvt {} {
   set vt [$itk_component(sel) get]
   switch $vt {
      Mount { cs tarHandConfig set tel Mount }
      A { cs tarHandConfig set tel "\"Source A\"" }
      B { cs tarHandConfig set tel "\"Source B\"" }
      C { cs tarHandConfig set tel "\"Source C\"" }
      PWFS1 { cs tarHandConfig set tel PWFS1 }
      PWFS2 { cs tarHandConfig set tel PWFS2 }
      OIWFS { cs tarHandConfig set tel OIWFS }
      Source { cs tarHandConfig set tel Source }
   }
   logger command tarHandConfig
   if { [catch {cs tcsApply post} msg] } {
      tk_messageBox -icon error -parent $itk_interior -message \
            "Error setting virtual telescope: TCS reports \"$msg\""
   }
}

itcl::body OffsetHandsetControl::settang {} {
   switch $tangent {
      1 { cs tarHandConfig set inctype "\"TANGENT PLANE\"" }
      0 { cs tarHandConfig set inctype "\"RADEC\"" }
   }
   logger command tarHandConfig
   if { [catch {cs tcsApply post} msg] } {
      tk_messageBox -icon error -parent $itk_interior -message \
            "Error setting increment type: TCS reports \"$msg\""
   }
}

itcl::body OffsetHandsetControl::getOffset par {
   switch $par {
      theta1 {
         return [$itk_component(theta1) get]
      }
      theta2 {
         return [$itk_component(theta2) get]
      }
      vt {
         set vt [$itk_component(sel) get]
         switch $vt {
            Mount { return Mount }
            A { return "Source A" }
            B { return ""Source B" }
            C { return "Source C" }
            PWFS1 { return PWFS1 }
            PWFS2 { return PWFS2 }
            OIWFS { return OIWFS }
            Source { return Source }
         }
      }
      type {
         switch $tangent {
            1 { return "TANGENT PLANE" }
            0 { return "RADEC" }
         }
      }
      ind {
         return 0
      }
   }
}
