#+
#  OnOffButton <- itk::Widget
#
#  Implements the OnOffButton class. A OnOffButton is a push button that
#  toggles the state of some mechanism. The current state of the
#  mechanism, is indicated by the background colour (red for Off, green for
#  On, yellow for unknown). When the button is pressed it goes yellow intil
#  the mechanism has changed state.
#
#  Options:
#          -oncommand      The command sender, parameter and value that turns
#                          the mechanism on.
#
#          -onvalue        A list of the sad record values that indicate that
#                          the mechanism is on.
#
#          -offcommand     The command sender, parameter and value that turns
#                          the mechanism off.
#
#          -offvalue       A list of the sad record values that indicate that
#                          the mechanism is off.
#
#          -sadrecord      The name of the sa that indicates the mechanism
#                          state.
#
#  Methods:
#          none
#
#  D Terrett 12 June 2000
#
#  Copyright CCLRC
#-

itcl::class OnOffButton {
   inherit itk::Widget
   constructor args {}
   destructor {}
   itk_option define -oncommand onCommand Command {}
   itk_option define -offcommand offCommand Command {}
   itk_option define -onvalue onValue Value {} checkstate
   itk_option define -offvalue offValue Value {} checkstate
   itk_option define -sadrecord sadrecord SadRecord {} checkstate
   private {
      method pressed {}
      method monitor {record value}
      method checkstate {}
      variable state 0
      variable monid
   }
}

itk::usual OnOffButton {
   keep -activeforeground -cursor -disabledforeground \
         -foreground -font -highlightcolor -highlightthickness -width
}

itcl::body OnOffButton::constructor args {

   itk_component add button {
      button $itk_interior.button -command [itcl::code $this pressed]
   } {
      usual
      keep -state -text -width
      ignore -activebackground
      ignore -background
   }
   pack $itk_component(button) -fill both -expand y

   eval itk_initialize $args
}

itcl::body OnOffButton::destructor {} {

# If the sad record has been set then remove the monitor.
   if { [llength $itk_option(-sadrecord)] } {
      [lindex $itk_option(-sadrecord) 0].[lindex $itk_option(-sadrecord) 1] \
         remove $monid
   }
}

itcl::body OnOffButton::pressed {} {

# Assume no command sender available
   set cs ""

# Set the command sender parameter appropriate for the current state.
   if { $state } {
      if { ! [string equal $itk_option(-offcommand) ""] } {
         foreach {cs par val} $itk_option(-offcommand) {}
         cs $cs set $par $val
      }
   } else {
      if { ! [string equal $itk_option(-oncommand) ""] } {
         foreach {cs par val} $itk_option(-oncommand) {}
         cs $cs set $par $val
      }
   }

# If there is a commmand sender then log and post the command.
   if { ! [string equal $cs ""] } {
      logger command $cs
      if { [catch {cs tcsApply post} msg] } {
         tk_messageBox -icon error -parent $itk_interior -message $msg
      }

# Set the button background to indicate that a state change is in progress.
      $itk_component(button) configure -background yellow \
            -activebackground yellow
   }
}

itcl::configbody OnOffButton::oncommand {
   if { ! [string equal $itk_option(-oncommand) ""] } {

      set cs [lindex $itk_option(-oncommand) 0]

# Create the command sender if it doesn't already exist.
      if { [catch {cs $cs info}] } {
         epics cs $cs
      }
   }
}

itcl::configbody OnOffButton::offcommand {
   if { ! [string equal $itk_option(-offcommand) ""] } {

      set cs [lindex $itk_option(-offcommand) 0]

# Create the command sender if it doesn't already exist.
      if { [catch {cs $cs info}] } {
         epics cs $cs
      }
   }
}

itcl::body OnOffButton::checkstate {} {
   if { [llength $itk_option(-sadrecord)] } {

# Extract the staus acceptor and record names.
      foreach {sa rec} $itk_option(-sadrecord) {}

# Create the status acceptor if it doesn't already exist.
      if { [llength [itcl::find objects ::$sa.$rec]] == 0 } {
         RecordMonitor ::$sa.$rec $sa $rec
      }

# Monitor the record.
      set monid [$sa.$rec add [itcl::code $this monitor]]

# Call the monitor routine to update the state.
      monitor $sa.$rec [sa $sa get $rec]
   }
}

itcl::body OnOffButton::monitor {record value} {

# Determine the state of the mechanism and set the colour.
   if { [lsearch -exact $itk_option(-onvalue) $value] >= 0 } {
      set state 1
      $itk_component(button) configure -background green \
            -activebackground green
   } elseif { [lsearch -exact $itk_option(-offvalue) $value] >= 0 } {
      set state 0
      $itk_component(button) configure -background red \
            -activebackground red
   } else {
      $itk_component(button) configure -background yellow \
            -activebackground yellow
   }
}
