#+
#  Panel <- itk:TopLevel
#
#  A Panel widget is a toplevel widget with the addition of a file menu with
#  Move, Hide and Exit entries. It has options that list the window names 
#  of the controls that the panel contains and the name of the PanelMgr that 
#  created this Panel.
#
#  Options:
#           -panelmgr       The name of the panel manager object managing
#                           this panel.
#
#  Methods:
#           show component  Makes component visible
#
#  D Terrett 7 January 2002
#
#  Copyright CCLRC
#+

itcl::class Panel {
   inherit itk::Toplevel
   constructor args {}
   itk_option define -panelmgr panelMgr PanelMgr ""
   public {
      method show {component} {}
   }
   protected {
      method setWidgetColors {widgets background foreground}
   }
   private {
      method exit {}
      method hide {}
      method move {}
   }
}

itk::usual Panel {
   keep -background -cursor
}

itcl::body Panel::constructor args {

# Menu bar and menus.
   itk_component add menubar {
      iwidgets::menubar $itk_interior.menubar -menubuttons {
         menubutton file -text File -menu {
            command move -label Move... -command \"[itcl::code $this move]\"
            command hide -label Hide -command \"[itcl::code $this hide]\"
            command exit -label Exit -command \"[itcl::code $this exit]\"
         }
      }
   }

# Frame.
   itk_component add frame {
      frame $itk_interior.frame
   }

   pack $itk_component(menubar) -fill x
   pack $itk_component(frame) -fill both -expand y

# Make the window not resizable.
   wm resizable $itk_interior 0 0

   set itk_interior $itk_component(frame)

   eval itk_initialize $args
}

itcl::body Panel::exit {} {
   destroy [winfo toplevel $itk_interior]
}

itcl::body Panel::hide {} {
   wm withdraw [winfo toplevel $itk_interior]
}

itcl::body Panel::move {} {

# Create the dialog box.
   set dialog [tcclib::MoveDialog $itk_interior.moveDialog \
         -title "Window Position Dialog" -modality application \
         -master $itk_interior -panelmgr $itk_option(-panelmgr)]

# Set the colours.
   setWidgetColors $dialog $itk_option(-background) $itk_option(-foreground)

# Hide the help and apply buttons.
   $dialog hide Help
   $dialog hide Apply

# Center and activate the dialog.
   $dialog center
   $dialog activate

# If the screen was changed the dialog will have been deleted when the
# parent panel was deleted so destroy the dialog with care.
   catch {destroy $dialog}
}

#  setWidgetColors is a method that sets the colour related options
#  of a list of widgets on the basis of the supplied background and foreground
#  colours. The algorithms for generating the colour values come from
#  pallet.tcl in the tk distribution.

itcl::body Panel::setWidgetColors {widgets background foreground} {

   set new(background) $background
   set new(foreground) $foreground

   set bg [winfo rgb . $background]
   set fg [winfo rgb . $foreground]

   set darkerBg [format #%02x%02x%02x [expr (9*[lindex $bg 0])/2560] \
         [expr (9*[lindex $bg 1])/2560] [expr (9*[lindex $bg 2])/2560]]

   foreach i {activeforeground insertbackground selectforeground \
         highlightcolor} {
      set new($i) $new(foreground)
   }

   set new(disabledforeground) [format #%02x%02x%02x \
         [expr (3*[lindex $bg 0] + [lindex $fg 0])/1024] \
         [expr (3*[lindex $bg 1] + [lindex $fg 1])/1024] \
         [expr (3*[lindex $bg 2] + [lindex $fg 2])/1024]]

   foreach i {0 1 2} {
      set light($i) [expr [lindex $bg $i]/256]
      set inc1 [expr ($light($i)*15)/100]
      set inc2 [expr (255-$light($i))/3]
      if {$inc1 > $inc2} {
         incr light($i) $inc1
      } else {
         incr light($i) $inc2
      }
      if {$light($i) > 255} {
         set light($i) 255
      }
   }
   set new(activebackground) [format #%02x%02x%02x $light(0) \
         $light(1) $light(2)]

   set new(selectbackground) $darkerBg
   set new(troughcolor) $darkerBg
   set new(textbackground) $darkerBg
   set new(selectcolor) #b03060

   foreach option [array names new] {
      foreach w $widgets {
            if {![catch {$w config -$option}]} {
            $w configure -$option $new($option)
         }
      }
   }
}
