#+
#  PoHandsetControl <- itk::Widget
#
#  A PoHandsetControl implements a software handset for adjusting
#  pointing origin positions.
#
#
#  Options:
#           none
#
#  Methods:
#           none
#
#  D Terrett 23 June 2001
#
#  Copyright CCLRC
#+

itcl::class PoHandsetControl {
   inherit itk::Widget
   constructor args {}
   destructor {after cancel $refid}
   private {
      method offpars {par}
      method setvt {}
      method getOffset {par}
      method refresh {}
      method update {}
      variable vt
      variable refid
   }
}

itk::usual PoHandsetControl {
   keep -borderwidth -cursor -font -labelfont 
}

itcl::body PoHandsetControl::constructor args {

   set w $itk_interior

# Frame for the handset.
   itk_component add hsframe {
      frame $w.hsframe
   }
   pack $itk_component(hsframe)
   set w $itk_component(hsframe)

   itk_component add sel {
      frame $w.sel -borderwidth 2 -relief groove
   }
   pack $itk_component(sel) -padx 5 -pady 5
   set w $itk_component(sel)

# Column headings.
   itk_component add adjust {
      label $w.adjust -text Adjust
   }
   itk_component add xy {
      label $w.xy -text "X (arcsec) Y"
   }
   itk_component add offset {
      label $w.offset -text offset
   }

# Radio buttons for selecting which offset to adjust.
   itk_component add asel {
      radiobutton $w.asel -variable [itcl::scope vt] -value sourceA \
            -command [itcl::code $this setvt]
   }
   itk_component add bsel {
      radiobutton $w.bsel -variable [itcl::scope vt] -value sourceB \
            -command [itcl::code $this setvt]
   }

# Labels.
   itk_component add alab {
      label $w.alab -text "Chop A"
   }
   itk_component add blab {
      label $w.blab -text "Chop B"
   }

# Display of positions and offsets.
   itk_component add ax {
      label $w.ax -width 8 -borderwidth 2 -relief groove
   }
   itk_component add ay {
      label $w.ay -width 8 -borderwidth 2 -relief groove
   }
   itk_component add aoff1 {
      label $w.aoff1 -width 8 -borderwidth 2 -relief groove
   }
   itk_component add aoff2 {
      label $w.aoff2 -width 8 -borderwidth 2 -relief groove
   }
   itk_component add bx {
      label $w.bx -width 8 -borderwidth 2 -relief groove
   }
   itk_component add by {
      label $w.by -width 8 -borderwidth 2 -relief groove
   }
   itk_component add boff1 {
      label $w.boff1 -width 8 -borderwidth 2 -relief groove
   }
   itk_component add boff2 {
      label $w.boff2 -width 8 -borderwidth 2 -relief groove
   }

   grid $itk_component(adjust) - $itk_component(xy) - \
         $itk_component(offset) -
   grid $itk_component(alab) $itk_component(asel) $itk_component(ax) \
         $itk_component(ay) $itk_component(aoff1) $itk_component(aoff2)
   grid $itk_component(blab) $itk_component(bsel) $itk_component(bx) \
         $itk_component(by) $itk_component(boff1) $itk_component(boff2)

# Handset
   set w $itk_component(hsframe)
   itk_component add handset {
      Handset $w.handset -adjust instr
   }
   pack $itk_component(handset)

# Select the default virtual telescope.
   set vt sourceA

# Buttons for clearing and update the offsets.
   itk_component add bot {
      frame $w.bot
   }
   pack $itk_component(bot) -expand yes -fill x
   set w $itk_component(bot)
   itk_component add absorb {
      LiveButton $w.update -text Absorb -width 8 \
            -command [itcl::code $this update]
   }
   itk_component add reset {
      ApplyButton $w.reset -command clearPoOffset -text Reset -width 8 \
            -parcommand [itcl::code $this offpars]
   }
   pack $itk_component(absorb) $itk_component(reset) -side left -expand y \
         -pady 10

# Pointing origin manager.
   set w $itk_interior
   itk_component add pomgr {
      PoManager $w.pomgr
   }
   pack $itk_component(pomgr) -pady 5

   set refid [after 1000 [itcl::code $this refresh]]

   eval itk_initialize $args
}

itcl::body PoHandsetControl::offpars par {
   switch $par {
      vt {
         switch $vt {
            sourceA {return "SOURCE A"}
            sourceB {return "SOURCE B"}
            sourceC {return "SOURCE C"}
         }
      }
      index {
         switch $vt {
            sourceA -
            sourceB -
            sourceC {return all}
         }
      }
   }
}

itcl::body PoHandsetControl::getOffset {par} {
   switch $par {
      theta1 {
         return [$itk_component(theta1) get]
      }
      theta2 {
         return [$itk_component(theta2) get]
      }
      vt {
         switch $vt {
            sourceA { return "Source A" }
            sourceB { return "Source B" }
            sourceC { return "Source C" }
         }
      }
      ind {
         return 0
      }
   }
}

itcl::body PoHandsetControl::setvt {} {
   $itk_component(handset) configure -vt $vt
}

itcl::body PoHandsetControl::refresh {} {

# Update the fields.
   foreach {src w} {A a B b} {
      set target [sa tcssad get target$src]
      $itk_component(${w}x) configure \
            -text [format %6.2f [expr {[lindex $target 4] / 0.62056151}]]
      $itk_component(${w}y) configure \
            -text [format %6.2f [expr {[lindex $target 5] / 0.62056151}]]
      $itk_component(${w}off1) configure \
            -text [format %6.2f [expr {[lindex $target 6] / 0.62056151}]]
      $itk_component(${w}off2) configure \
            -text [format %6.2f [expr {[lindex $target 7] / 0.62056151}]]
   }

   set refid [after 1000 [itcl::code $this refresh]]
}

itcl::body PoHandsetControl::update {} {
   $itk_component(pomgr) update $vt
}
