#+
#  PoHandsetPanel <- Panel
#
#  Implements the PoHandsetPanel widget. A Panel widget with a 
#  PoHandsetControl widget packed into its interior.
#
#  Options:
#          none
#
#  Methods:
#          none
#
#  D Terrett 29 March 2001
#
#  Copyright CCLRC
#+

itcl::class PoHandsetPanel {
   inherit Panel
   constructor args {}
}

itk::usual PoHandsetPanel {
   keep -background -cursor
}

itcl::body PoHandsetPanel::constructor args {

   itk_component add control {
      PoHandsetControl $itk_interior.control
   }
   setWidgetColors "$itk_component(menubar) $itk_component(control)" \
         $itk_option(-background) $itk_option(-foreground)

   pack $itk_component(control) -fill both -expand y

   eval itk_initialize $args
}
