#+
#  PointOrigControl <- ComponentControl
#
#  A PointOrigControl is a ComponentControl widget with entryfield widgets for 
#  X and Y.
#
#  Options:
#
#  Methods:
#           selectobj name  Copies the contents of the PointOrig object "name"
#                           into the edit controls.
#
#           updateobj name  Stores the contents of the edit controls in the
#                           PointOrig object "name".
#
#  D Terrett 28 March 2001
#
#  Copyright CCLRC
#+

itcl::class PointOrigControl {
   inherit ComponentControl
   constructor args {}
   public {
      method selectobj {name}
      method updateobj {name}
   }
}

itk::usual PointOrigControl {
   keep -borderwidth -cursor -font -highlightthickness -insertborderwidth \
         -insertofftime -insertontime -insertwidth -labelfont -popupcursor \
         -selectborderwidth -textfont -title -vt -namespace -componentlist
}

itcl::body PointOrigControl::constructor args {

   set w $itk_interior

# Entryfields for the pointing origin X & Y.
   itk_component add xy {
      frame $w.xy -bd 2 -relief ridge
   }
   pack $itk_component(xy) -fill x -expand y
   set w $itk_component(xy)
   itk_component add x {
      iwidgets::entryfield $w.x -labeltext [lindex [cs poriginA info x] 2] \
            -width 8
   }
   itk_component add y {
      iwidgets::entryfield $w.y -labeltext [lindex [cs poriginA info y] 2] \
            -width 8
   }
   pack $itk_component(x) $itk_component(y) -side left -padx 4 -pady 4

# Create the instrument object used by apply.
   set scratchobj [namespace which -command [PointOrig #auto]]

# Set the object class.
   set objclass PointOrigComponent
   set description "pointing origin"

   eval itk_initialize $args
}

itcl::body PointOrigControl::selectobj name {
#
# Copy the contents of the PointOrig object selected in the combobox
# into the edit controls.
   $itk_component(x) clear
   $itk_component(y) clear
   if { ! [string equal $name ""] } {
      $itk_component(x) insert end [$name cget -x]
      $itk_component(y) insert end [$name cget -y]
   }
}

itcl::body PointOrigControl::updateobj name {

# Update the named pointing origin object.
   $name configure -x [$itk_component(x) get] -y [$itk_component(y) get]
}
