#+
#  PointOrig
#
#  Implements the PointOrig class. A PointOrig object stores all the parameters 
#  needed to specify a pointing origin and knows how to load the pointing
#  origin into the TCS.
#
#  Options:
#          -x           The X value of the pointing origin.
#
#          -y           The Y value of the pointing origin.
#
#  Methods:
#          apply vt      Applies the pointing origin to virtual telescope "vt".
#
#          init          Returns the pointing origin object to its initial 
#                        state.
#
#          preview item  Sets "item" in the preview.
#
#          save file     Writes the values of the pointing origin options
#                        to the channel identifier "file".
#
#  D Terrett 15 March 2001
#
#  Copyright CCLRC
#+

itcl::class PointOrig {
   public proc subcomponents {} {return {}}
   public {
      method apply {vt}
      method init {}
      method preview {item}
      method save {file}
      variable x 0.0
      variable y 0.0
   }
}

itcl::body PointOrig::apply vt {
   switch $vt {
      sourceA {
         cs poriginA set x [list $x]
         cs poriginA set y [list $y]
         logger command poriginA
      }
      sourceB {
         cs poriginB set x [list $x]
         cs poriginB set y [list $y]
         logger command poriginB
      }
      sourceC {
         cs poriginC set x [list $x]
         cs poriginC set y [list $y]
         logger command poriginC
      }
      all {
         $this apply sourceA
         $this apply sourceB
         $this apply sourceC
      }
   }
}

itcl::body PointOrig::init {} {
   set x 0.0
   set y 0.0
}

itcl::body PointOrig::preview item {
   tccPreview set $item $x $y
}

itcl::body PointOrig::save file {
   puts $file "   -x [list $x] \\"
   puts $file "   -y [list $y]"
}
