#+
#  PointOrigPanel <- tcclib::Panel
#
#  Implements the PointOrigPanel widget. A Panel widget with a 
#  PointOrigControl widget packed into its interior.
#
#  Methods:
#          none
#
#  D Terrett 29 March 2001
#
#  Copyright CCLRC
#+

itcl::class PointOrigPanel {
   inherit tcclib::Panel
   constructor args {}
}

itk::usual PointOrigPanel {
   keep -background -cursor
}

itcl::body PointOrigPanel::constructor args {
   itk_component add control {
      PointOrigControl $itk_interior.control
   }
   setWidgetColors "$itk_component(menubar) $itk_component(control)" \
         $itk_option(-background) $itk_option(-foreground)

   pack $itk_component(control) -fill both -expand y

   eval itk_initialize $args
}
