#+
#  PointOrigComponent <- PointOrig, tcclib::Component
#
#  A PointOrigComponent object is a PointOrig object that is stored in a 
#  configuration list.
#
#
#  Options:
#           none
#
#  Methods:
#           constructor list  Creates the Cosys object and puts it onto
#                           "list".
#
#  D Terrett 19 September 2001
#
#  Copyright CCLRC
#+

itcl::class PointOrigComponent {
   inherit tcclib::Component PointOrig
   constructor {list args} {
      tcclib::Component::constructor $list
   } {
      eval configure $args
   }
}
