#+
#  PointOrigPanel <- Panel
#
#  Implements the PointOrigPanel widget. A Panel widget with a 
#  PointOrigControl widget packed into its interior.
#
#  Options:
#          -componentlist - The -componentlist option of the pointing
#                           origin control
#
#          -namespace -     The -namespace option of the pointing
#                           origin control
#
#  Methods:
#          none
#
#  D Terrett 27 March 2001
#
#  Copyright CCLRC
#+

itcl::class PointOrigPanel {
   inherit Panel
   constructor args {}
   itk_option define -componentlist componentList ComponentList {}
   itk_option define -namespace namespace Namespace {}
}

itk::usual PointOrigPanel {
   keep -background -cursor
}

itcl::body PointOrigPanel::constructor args {
   itk_component add control {
      PointOrigControl $itk_interior.control
   }
   setWidgetColors "$itk_component(menubar) $itk_component(control)" \
         $itk_option(-background) $itk_option(-foreground)

   pack $itk_component(control) -fill both -expand y

   set itk_option(-windows) $itk_component(control)

   eval itk_initialize $args
}

itcl::configbody PointOrigPanel::componentlist {
   $itk_component(control) configure -componentlist $itk_option(-componentlist)
}

itcl::configbody PointOrigPanel::namespace {
   $itk_component(control) configure -namespace $itk_option(-namespace)
}
