#+
#  PointOrig
#
#  Implements the PointOrig class. A PointOrig object stores all the parameters 
#  needed to specify a pointing origin and knows how to load the pointing
#  origin into the TCS.
#
#  PointOrig components with the name "Rotator Axis" are a special case
#  with x & y fixed at zero.
#
#  Options:
#          -x           The X value of the pointing origin.
#
#          -y           The Y value of the pointing origin.
#
#  Methods:
#          apply vt      Applies the pointing origin to virtual telescope "vt".
#
#          init          Returns the pointing origin object to its initial 
#                        state.
#
#          preview item  Sets "item" in the preview.
#
#          save file     Writes the values of the pointing origin options
#                        to the channel identifier "file".
#
#  D Terrett 22 April 2001
#
#  Copyright CCLRC
#+

itcl::class PointOrig {
   public proc subcomponents {} {return {}}
   public {
      method apply {vt}
      method init {}
      method preview {item}
      method save {file}
      variable x 0.0
      variable y 0.0
   }
}

itcl::body PointOrig::apply vt {
   set xmm [expr {$x * 0.62056151}]
   set ymm [expr {$y * 0.62056151}]
   switch $vt {
      sourceA {
         cs poriginA set x [list $xmm]
         cs poriginA set y [list $ymm]
         logger command poriginA
      }
      sourceB {
         cs poriginB set x [list $xmm]
         cs poriginB set y [list $ymm]
         logger command poriginB
      }
      sourceC {
         cs poriginC set x [list $xmm]
         cs poriginC set y [list $ymm]
         logger command poriginC
      }
      all {
         $this apply sourceA
         $this apply sourceB
         $this apply sourceC
      }
   }
}

itcl::body PointOrig::init {} {
   set x 0.0
   set y 0.0
}

itcl::body PointOrig::preview item {
   tccPreview set $item [expr {$x * 0.62056151}] [expr {$y * 0.62056151}]
}

itcl::body PointOrig::save file {
   puts $file "   -x [list $x] \\"
   puts $file "   -y [list $y]"
}

itcl::configbody PointOrig::x {
   if { [string is double -strict $x] } {
      if { [string equal [namespace tail $this] "Rotator axis"] } {
         if { $x != 0.0 } {
            error "Rotator Axis must have X = 0.0"
         }
      }
   } else {
      error "Instrument origin X \"$x\" is not a number"
   }
}

itcl::configbody PointOrig::y {
   if { [string is double -strict $y] } {
      if { [string equal [namespace tail $this] "Rotator axis"] } {
         if { $y != 0.0 } {
            error "Rotator Axis must have Y = 0.0"
         }
      }
   } else {
      error "Instrument origin Y \"$y\" is not a number"
   }
}
