#+
#  PoManager <- itk::Widget
#
#  Implement a widget for managing an array of pointing origins.
#
#  Methods:
#
#     update    Updates the currently selected pointing origin with
#                new values.
#
#  D Terrett  31 January 2001
#
#  Copyright CCLRC
#+

itcl::class PoManager {
   inherit itk::Widget
   constructor {args} {}
   public {
      method update {chop}
   }
   private {
      method selectcmd {po}
      method selecta {po}
      variable achop ra
      variable bchop ra
   }
}

itk::usual PoManager {
}

itcl::body PoManager::constructor {args} {

   set w $itk_interior

# Column labels.
   itk_component add alab {
      label $w.alab -text A
   }
   itk_component add blab {
      label $w.blab -text B
   }
   itk_component add xlab {
      label $w.xlab -text X
   }
   itk_component add ylab {
      label $w.ylab -text Y
   }
   grid $itk_component(alab) $itk_component(blab) x $itk_component(xlab) \
         $itk_component(ylab)

# First row of table is for the fixed rotator axis.
   itk_component add ara {
      radiobutton $w.ara -variable [scope achop] -value ra \
            -command [itcl::code $this selecta ra]
   }
   itk_component add bra {
      radiobutton $w.bra -variable [scope bchop] -value ra \
            -command [itcl::code $this selectcmd ra]
   }
   itk_component add raname {
      label $w.raname -text "Rotator axis" -relief sunken
   }
   itk_component add xra {
      label $w.xra -text " 0.00" -relief groove -width 8
   }
   itk_component add yra {
      label $w.yra -text " 0.00" -relief groove -width 8
   }
   grid $itk_component(ara) $itk_component(bra) $itk_component(raname) \
         $itk_component(xra) $itk_component(yra) -sticky ew

# Remaining rows.
   foreach po {v w x y z} {

# Chop state radiobuttons.
      itk_component add a$po {
         radiobutton $w.a$po -variable [scope achop] -value $po \
               -command [itcl::code $this selecta $po]
      }
      itk_component add b$po {
         radiobutton $w.b$po -variable [scope bchop] -value $po \
               -command [itcl::code $this selectcmd $po]
      }

# Subcomponent selector.
      itk_component add sel$po {
         ListManager $w.sel$po -componentlist PointOrigList \
               -selectioncommand [code $this selectcmd $po] \
      }

# Display of X & Y.
      itk_component add x$po {
         label $w.x$po -width 8 -relief groove -text "  0.00"
      }
      itk_component add y$po {
         label $w.y$po -width 8 -relief groove -text "  0.00"
      }
      grid $itk_component(a$po) $itk_component(b$po) $itk_component(sel$po) \
            $itk_component(x$po) $itk_component(y$po)
   }

   if { [catch {cs absorbPoOffset info}] } {
      epics cs absorbPoOffset
   }
   if { [catch {cs poriginA info}] } {
      epics cs poriginA
   }
   if { [catch {cs poriginB info}] } {
      epics cs poriginB
   }
   eval itk_initialize $args
}

itcl::body PoManager::selectcmd {po} {
   if { [string equal $po ra] } {
      set name ""
   } else {
      set name [$itk_component(sel$po) get]
   }
   if { [string length $name] } {

# There is a name in the combobox; check that it is the name of an existing
# component.
      if { [catch {::PointOrigNames::$name cget -x}] } {

# It isn't so create it and set its values from the text widgets.
         PointOrigComponent ::PointOrigNames::$name PointOrigList \
               -x [$itk_component(x$po) cget -text] \
               -y [$itk_component(y$po) cget -text]
      } else {

# It is so Load its values into the X & Y display columns.
         $itk_component(x$po) configure \
               -text [format %6.2f [::PointOrigNames::$name cget -x]]
         $itk_component(y$po) configure \
               -text [format %6.2f [::PointOrigNames::$name cget -y]]
      }
   }

# If one of the chop states is selected for this pointing origin then 
# absorb any offsets and send the X/Y to the TCS.

   if { $achop == $po } {
      cs absorbPoOffset set vt "\"SOURCE A\""
      cs absorbPoOffset set index all
      logger command absorbPoOffset
      if { [catch {cs tcsApply post} msg] } {
         tk_messageBox -icon error -parent $itk_interior -message \
               "Error absorbing pointing origin offsets: TCS reports \"$msg\""
      }
   }
   if { $bchop == $po } {
      cs absorbPoOffset set vt "\"SOURCE B\""
      cs absorbPoOffset set index all
      logger command absorbPoOffset
      if { [catch {cs tcsApply post} msg] } {
         tk_messageBox -icon error -parent $itk_interior -message \
               "Error absorbing pointing origin offsets: TCS reports \"$msg\""
      }
   }
   if {  $achop == $po ||  $bchop == $po } {
      if { $achop == $po } {
         cs poriginA set x [$itk_component(x$po) cget -text]
         cs poriginA set y [$itk_component(y$po) cget -text]
         logger command poriginA
      }
      if { $bchop == $po } {
         cs poriginB set x [$itk_component(x$po) cget -text]
         cs poriginB set y [$itk_component(y$po) cget -text]
         logger command poriginB
      }
      if { [catch {cs tcsApply post} msg] } {
         tk_messageBox -icon error -parent $itk_interior -message \
               "Error setting pointing origin: TCS reports \"$msg\""
      }
   }
}

itcl::body PoManager::update {chop} {
   switch $chop {
      sourceA {
         set po $achop
         set target targetA
      }
      sourceB {
         set po $bchop
         set target targetB
      }
   }

# The ra pointing origin is a special case.
   if { [string equal $po ra] } {
   } else {

# Get the current values of the appropriate pointing origin.
      set tar [sa tcssad get $target]
      set x [expr {[lindex $tar 4] + [lindex $tar 6]}]
      set y [expr {[lindex $tar 5] + [lindex $tar 7]}]
   
      set name [$itk_component(sel$po) get]
      if { [string length $name] } {

# Update the pointing origin component, creating it if necessary.
         if { [catch {::PointOrigNames::$name configure -x $x -y $y}] } {
            PointOrigComponent ::PointOrigNames::$name PointOrigList \
                   -x $x -y $y
         }
      } else {

# Update the X/Y display.
         $itk_component(x$po) configure -text [format %6.2f $x]
         $itk_component(y$po) configure -text [format %6.2f $y]
      }

# Select the pointing origin.
      selectcmd $po
   }
}

itcl::body PoManager::selecta {po} {

# Set the chop B pointing origin to the same as A and then select it.
   set bchop $achop
   selectcmd $po
}
