#+
#  RotatorComponent <- Rotator, Component
#
#  A RotatorComponent object is a Rotator object that is stored in a 
#  configuration list.
#
#
#  Options:
#           none
#
#  Methods:
#           constructor list  Creates the Rotator object and puts it onto
#                           "list".
#
#           save file       Writes commands to re-create the object to the
#                           channel identifier "file" and then calls the
#                           Rotator save method to add the objects data.
#
#  D Terrett 25 September 2000
#
#  Copyright CCLRC
#+

itcl::class RotatorComponent {
   inherit Rotator Component

   constructor {list args} {
      Component::constructor $list
   } {
      eval configure $args
   }

   public method save file
}

itcl::body RotatorComponent::save file {
   set obj [namespace tail $this]
   set namespace [namespace qualifiers $this]
   puts $file \
         "catch {RotatorComponent \"${namespace}::$obj\"  $componentList}"
   puts $file "\"${namespace}::$obj\" init"
   puts $file "\"${namespace}::$obj\" configure \\"
   Rotator::save $file
}
