#+
#  RotatorPanel <- Panel
#
#  Implements the RotatorPanel widget. A Panel widget with a 
#  RotatorControl widget packed into its interior.
#
#  Methods:
#           none
#
#  D Terrett 29 March 2001
#
#  Copyright CCLRC
#+

itcl::class RotatorPanel {
   inherit Panel

   constructor args {}
}

itk::usual RotatorPanel {
   keep -background -cursor
}

itcl::body RotatorPanel::constructor args {
   itk_component add control {
      RotatorControl $itk_interior.control
   }
   setWidgetColors "$itk_component(menubar) $itk_component(control)" \
         $itk_option(-background) $itk_option(-foreground)

   pack $itk_component(control) -fill both -expand y

   eval itk_initialize $args
}
