#+
#  Rotator
#
#  Implements the Rotator class. A Rotator object stores the configuration 
#  of the cass rotator.
#
#  Options:
#          -cosys        The rotator tracking frame.
#
#          -ipa          The instrument position angle.
#
#  Methods:
#          apply args    Applies the rotator configuration to the TCS by 
#                        setting the values of the command parameters. Any
#                        arguments are ignored.
#
#          init          Returns the rotator object to its initial state.
#
#          preview       Sets the rotator configuration in the preview.
#
#          save file     Writes the values of the rotator configuration
#                        to the channel identifier "file".
#
#  Procs:
#         subcomponents  Returns a list of the rotator classes subcomponents.
#
#  D Terrett 2 February 2001
#
#  Copyright CCLRC
#+

itcl::class Rotator {
   destructor {$this init}
   public {
      proc subcomponents {}
      method apply {args}
      method init {}
      method preview {}
      method save {file}
      variable ipa {}
      variable cosys {}
   }
   private {
      variable current_cosys {}
   }
}

itcl::body Rotator::subcomponents {} {
   return { \
      {cosys Cosys CosysNames CosysList {Coordinate system} rotator} \
   }
}

itcl::body Rotator::apply args {
   cs rotator set ipa \"$ipa\"
   if { [string equal $cosys ""] } {
      cs rotator set system FK5
      cs rotator set equinox J2000
   } else {
      CosysNames::$cosys apply rotator
   }
   logger command rotator
}

itcl::body Rotator::preview {} {
   if { [string equal $cosys ""] } {
      set frame FK5
      set equinox J2000
   } else {
      set frame [CosysNames::$cosys cget -frame]
      set equinox [CosysNames::$cosys cget -equinox]
   }
   if { [string equal $ipa ""] } {
      set a 0.0
   } else {
      set a $ipa
   }
   tccPreview set ipa $a $frame $equinox
}

itcl::body Rotator::save file {
   puts $file "   -ipa \"$ipa\" \\"
   puts $file "   -cosys \"$cosys\""
}

itcl::body Rotator::init {} {
   set ipa ""
   $this configure -cosys ""
}

itcl::configbody Rotator::cosys {
   if { ! [string equal $current_cosys ""] } {
      CosysNames::$current_cosys refdec
   }
   set current_cosys ""
   if { ! [string equal $cosys ""] } {
      if { [catch {CosysNames::$cosys refinc}] } {
         error "Coordinate frame \"$cosys\" does not exist"
      } else {
         set current_cosys $cosys
      }
   }
}
