#+
#  RotatorComponent <- Rotator, tcclib::Component
#
#  A RotatorComponent object is a Rotator object that is stored in a 
#  configuration list.
#
#
#  Options:
#           none
#
#  Methods:
#           constructor list  Creates the Rotator object and puts it onto
#                           "list".
#
#  D Terrett 19 September 2001
#
#  Copyright CCLRC
#+

itcl::class RotatorComponent {
   inherit tcclib::Component Rotator
   constructor {list args} {
      tcclib::Component::constructor $list
   } {
      eval configure $args
   }
}
