#+
#  RotatorComponent.itcl
#
#  Implements the RotatorComponent class. A RotatorComponent object 
#  is a Rotator object that is stored in a configuration.
#
#  D Terrett 21 August 1998
#
#  Copyright CCLRC
#+

itcl::class RotatorComponent {
   inherit Rotator Component

   constructor {list args} {
      Component::constructor $list
   } {
      eval configure $args
   }

   public method save file
}

itcl::body RotatorComponent::save file {
   set objname [namespace tail $this]
   set namespace [info namespace qualifiers $this]
   puts $file "catch {delete object \"$namespace::$objname\"}"
   puts $file "RotatorComponent \"$namespace::$objname\"  $componentList \\"
   Rotator::save $file
}
