#+
#  Rotator
#
#  Implements the Rotator class. A Rotator object stores the configuration 
#  of the cass rotator.
#
#  Options:
#          -cosys        The rotator tracking frame.
#
#          -ipa          The instrument position angle.
#
#  Methods:
#          apply args    Applies the rotator configuration to the TCS by 
#                        setting the values of the command parameters. Any
#                        arguments are ignored.
#
#          init          Returns the rotator object to its initial state.
#
#          preview       Sets the rotator configuration in the preview.
#
#          save file     Writes the values of the rotator configuration
#                        to the channel identifier "file".
#
#  Procs:
#         subcomponents  Returns a list of the rotator classes subcomponents.
#
#  D Terrett 21 February 2000
#
#  Copyright CCLRC
#+

itcl::class Rotator {

   destructor {$this init}

   public proc subcomponents {}

   public method apply args
   public method init
   public method preview
   public method save file

   public variable ipa {}
   public variable cosys {}

   private variable current_cosys {}
}

itcl::body Rotator::subcomponents {} {
   return { \
      {cosys Cosys CosysNames CosysList {Coordinate system} rotator} \
   }
}

itcl::body Rotator::apply args {
   cs rotator set ipa \"$ipa\"
   if { $cosys == "" } {
      cs rotator set system AZEL_TOPO
      cs rotator set equinox ""
   } else {
      CosysNames::$cosys apply rotator
   }
}

itcl::body Rotator::preview {} {
   if { $cosys == "" } {
      tccPreview set ipa $ipa AZEL_TOPO {}
   } else {
      tccPreview set ipa $ipa [CosysNames::$cosys cget -frame] \
            [CosysNames::$cosys cget -equinox]
   }
}

itcl::body Rotator::save file {
   puts $file "   -ipa \"$ipa\" \\"
   puts $file "   -cosys \"$cosys\""
}

itcl::body Rotator::init {} {
   set ipa ""
   $this configure -cosys ""
}

itcl::configbody Rotator::cosys {
   if { $current_cosys != "" } {
      CosysNames::$current_cosys refdec
   }
   set current_cosys ""
   if { $cosys != "" } {
      if { [catch {CosysNames::$cosys refinc}] } {
         error "Coordinate frame \"$cosys\" does not exist"
      } else {
         set current_cosys $cosys
      }
   }
}
