#+
#  RotatorControl <- tcclib::ComponentControl
#
#  A Rotator control is a ComponentControl widget with widgets for the 
#  instrument position angle and coordinate system.
#
#  Options:
#           -shadow         The name of the control's edit shadow.
#
#  Methods:
#           selectobj name  Copies the contents of the Rotator object "name"
#                           into the edit controls.
#
#           updateobj name  Stores the contents of the edit controls in the
#                           Rotator object "name".
#
#  D Terrett 28 March 2001
#
#  Copyright CCLRC
#+

itcl::class RotatorControl {
   inherit tcclib::ComponentControl

   constructor args {}

   itk_option define -shadow shadow Shadow {}

   public method selectobj name
   public method updateobj name

   private method checkcosys
   private variable refdir
   private method setdir
}

itk::usual RotatorControl {
   keep -borderwidth -cursor -font -highlightthickness -insertborderwidth \
         -insertofftime -insertontime -insertwidth -labelfont -popupcursor \
         -selectborderwidth -textfont -title -applyarg -componentlist -namespace
}

itcl::body RotatorControl::constructor args {

# Frame for angle.
   itk_component add angle {
      frame $itk_interior.angle -bd 2 -relief ridge
   }
   pack $itk_component(angle) 

# Entry field for angle.
   set w $itk_component(angle)
   itk_component add ipa {
      iwidgets::entryfield $w.ipa -labeltext [lindex [cs rotator info ipa] 2] \
            -width 8
   }
   pack $itk_component(ipa) -padx 5 -pady 5

# Frame for reference direction.
   itk_component add refdir {
      frame $itk_interior.refdir -bd 2 -relief ridge
   }
   pack $itk_component(refdir) -fill x -expand y -pady 5

# Title
   itk_component add title {
      label $w.label -text "Reference direction"
   }
   pack $itk_component(title) -anchor w

# Radiobuttons.
   itk_component add north {
      radiobutton $w.north -text "Rotator tracking" -variable [scope refdir] \
            -value north -command [code $this setdir]
   }
   itk_component add vertical {
      radiobutton $w.vertical -text "Rotator fixed" -variable [scope refdir] \
            -value vertical -command [code $this setdir]
   }
   pack $itk_component(vertical) $itk_component(north) -pady 5 -anchor w \
         -padx 5

# Control for selecting a coordinate frame.
   itk_component add cosys {
      tcclib::SubComponentSelector $w.cosys -labeltext "Coordinate system" \
            -labelpos nw -componentlist CosysList -component cosys \
            -selectioncommand [code $this checkcosys]
   }
   pack $itk_component(cosys) -anchor w -padx 5 -pady 5
   set w [winfo parent $w]

# Set initial state.
   set refdir vertical

# Create rotator object used by apply
   set scratchobj [namespace which -command [Rotator #auto]]

# Set the object class.
   set objclass RotatorComponent
   set description "field orientation"

   eval itk_initialize $args
}

itcl::configbody RotatorControl::shadow {
   $itk_component(cosys) configure -editcontrol \
            $itk_option(-shadow)cosys
   $itk_component(cosys) configure -shadow $itk_option(-shadow)
}

itcl::body RotatorControl::selectobj name {

# Copy the contents of the specified rotator object into the edit
# controls.
   $itk_component(ipa) clear

   if { ! [string equal [namespace tail $name] ""] } {
      $itk_component(ipa) insert end [$name cget -ipa]
      set cosys [$name cget -cosys]
      if { [string equal $cosys AzEl] } {
         set refdir vertical
         $itk_component(cosys) select ""
      } else {
         set refdir north
         if { [string is space $cosys] } {
            $itk_component(cosys) select FK5/J2000
         } else {
            $itk_component(cosys) select $cosys
         }
      }
      setdir
   }
}

itcl::body RotatorControl::updateobj name {
   $name configure -ipa [$itk_component(ipa) get]
   if { [string equal $refdir north] } {
      $name configure -cosys [$itk_component(cosys) get]
   } else {
      $name configure -cosys AzEl
   }
}

itcl::body RotatorControl::setdir {} {
   if { [string equal $refdir vertical] } {
      $itk_component(cosys) select AzEl
   } else {
      if { [string equal [$itk_component(cosys) get] AzEl] } {
         $itk_component(cosys) select ""
      }
   }
}

itcl::body RotatorControl::checkcosys {} {
   set cosys [$itk_component(cosys) get]
   if { ![string equal $cosys ""] } {
      if { [CosysNames::$cosys cget -isazel] } {
         set refdir vertical
      } else {
         set refdir north
      }
   }
}
