#+
#  SciTargetControl <- TargetControl
#
#  A SciTarget control is a TargetControl widget with widgets for
#  the target position etc.
#
#  D Terrett 16 March 2001
#
#  Copyright CCLRC
#+

itcl::class SciTargetControl {
   inherit TargetControl
   constructor args {}
   public {
      method selectobj {name}
      method updateobj {name}
   }
   private {
      method copy {createproc wfs}
      method orbtype {}
      method selplanet {}
      variable planet
   }
}

itk::usual SciTargetControl {
   keep -borderwidth -cursor -font -highlightthickness -insertborderwidth \
         -insertofftime -insertontime -insertwidth -labelfont -popupcursor \
         -selectborderwidth -textfont -title -vt
}

itcl::body SciTargetControl::constructor args {

# Set colour of highlight frame.
   $itk_component(highlight) configure -background black

# Add page for planets
   set w [$itk_component(notebook) add -label "Planets" \
         -command "$itk_component(copy) configure -state disabled"] 

# Radiobuttons for selecting a planet.
   itk_component add moon {
      radiobutton $w.moon -text Moon -variable [scope planet] -value moon \
            -command [itcl::code $this selplanet]
   }
   itk_component add mercury {
      radiobutton $w.mercury -text Mercury -variable [scope planet] \
            -value mercury -command [itcl::code $this selplanet]
   }
   itk_component add venus {
      radiobutton $w.venus -text Venus -variable [scope planet] -value venus \
            -command [itcl::code $this selplanet]
   }
   itk_component add mars {
      radiobutton $w.mars -text Mars -variable [scope planet] -value mars \
            -command [itcl::code $this selplanet]
   }
   itk_component add jupiter {
      radiobutton $w.jupiter -text Jupiter -variable [scope planet] \
            -value jupiter -command [itcl::code $this selplanet]
   }
   itk_component add saturn {
      radiobutton $w.saturn -text Saturn -variable [scope planet] \
            -value saturn -command [itcl::code $this selplanet]
   }
   itk_component add uranus {
      radiobutton $w.uranus -text Uranus -variable [scope planet] \
            -value uranus  -command [itcl::code $this selplanet]
   }
   itk_component add neptune {
      radiobutton $w.neptune -text Neptune -variable [scope planet] \
            -value neptune -command [itcl::code $this selplanet]
   }
   itk_component add pluto {
      radiobutton $w.pluto -text Pluto -variable [scope planet] -value pluto \
            -command [itcl::code $this selplanet]
   }
   grid $itk_component(moon) $itk_component(mars) $itk_component(uranus) \
         -padx 10 -pady 10 -sticky w
   grid $itk_component(mercury) $itk_component(jupiter) \
         $itk_component(neptune) -padx 10 -pady 10 -sticky w
   grid $itk_component(venus) $itk_component(saturn) $itk_component(pluto) \
         -padx 10 -pady 10 -sticky w

# Add page for orbits
   set w [$itk_component(notebook) add -label "Orbits" \
         -command "$itk_component(copy) configure -state disabled"] 

# Option menu for the orbit type.
   itk_component add eltype {
      iwidgets::optionmenu $w.eltype -command [code $this orbtype]
   }
   $itk_component(eltype) insert end "Major planet orbital elements" \
         "Minor planet orbital elements" "Comet orbital elements"

# Entry widgets for each element.
   itk_component add epochofel {
      iwidgets::entryfield $w.epochofel -labeltext \
            [lindex [cs orbit info epochofel] 2]
   }
   itk_component add inclination {
      iwidgets::entryfield $w.inclination -labeltext \
            [lindex [cs orbit info inclination] 2]
   }
   itk_component add longascnode {
      iwidgets::entryfield $w.longascnode -labeltext \
            [lindex [cs orbit info longascnode] 2]
   }
   itk_component add xxxofper {
      iwidgets::entryfield $w.xxxofper -labeltext \
            [lindex [cs orbit info longofper] 2]
   }
   itk_component add xxxdist {
      iwidgets::entryfield $w.xxxdist -labeltext \
            [lindex [cs orbit info meandist] 2]
   }
   itk_component add eccentricity {
      iwidgets::entryfield $w.eccentricity -labeltext \
            [lindex [cs orbit info eccentricity] 2]
   }
   itk_component add meanxxxx {
      iwidgets::entryfield $w.meanxxxx -labeltext \
            [lindex [cs orbit info meanlong] 2]
   }
   itk_component add dailymot {
      iwidgets::entryfield $w.dailymot -labeltext \
            [lindex [cs orbit info dailymot] 2]
   }
   grid $itk_component(eltype) -pady 1
   grid $itk_component(epochofel) -sticky e -pady 1
   grid $itk_component(inclination) -sticky e -pady 1
   grid $itk_component(longascnode) -sticky e -pady 1
   grid $itk_component(xxxofper) -sticky e -pady 1
   grid $itk_component(xxxdist) -sticky e -pady 1
   grid $itk_component(eccentricity) -sticky e -pady 1
   grid $itk_component(meanxxxx) -sticky e -pady 1
   grid $itk_component(dailymot) -sticky e -pady 1

# Re-enable the copy menu when either the radec or azel pages are selected.
   $itk_component(notebook) pageconfigure RA/Dec \
         -command "$itk_component(copy) configure -state normal"
   $itk_component(notebook) pageconfigure Az/El \
         -command "$itk_component(copy) configure -state normal"

# Add control for airmass limit.
   itk_component add airmass {
      iwidgets::entryfield $itk_component(frame).airmass \
            -labeltext "Airmass limit" -width 8
   }
   pack $itk_component(airmass) -anchor w


# Add destinations to the copy menu.
   $itk_component(copymenu) add command -label "PWFS1 targets" \
         -command [code $this copy createWfsTarget pwfs1]
   $itk_component(copymenu) add command -label "PWFS2 targets" \
         -command [code $this copy createWfsTarget pwfs2]
   $itk_component(copymenu) add command -label "OIWFS targets" \
         -command [code $this copy createWfsTarget oiwfs]

# Unpack Apply button and checkbutton so that new science targets have to be
# applied from the main configuration window.
   pack forget  [$itk_component(storeapply) component lock]
   pack forget  [$itk_component(storeapply) component apply]
   set store  [$itk_component(storeapply) component store]

# Create the scatch target object used by apply.
   set scratchobj [namespace which -command [SciTarget #auto]]

# Define the object class
   set objclass SciTargetComponent
   set description target

   eval itk_initialize $args
}

itcl::body SciTargetControl::selectobj name {

   $this TargetControl::selectobj $name
   $itk_component(epochofel) clear
   $itk_component(inclination) clear
   $itk_component(longascnode) clear
   $itk_component(xxxofper) clear
   $itk_component(xxxdist) clear
   $itk_component(eccentricity) clear
   $itk_component(meanxxxx) clear
   $itk_component(dailymot) clear
   $itk_component(airmass) clear

   if { ! [string equal $name ""] } {
      switch [$name cget -type] {
         planet {
            $itk_component(notebook) select Planets
            set planet [$name cget -planet]
         }
         orbit {
            $itk_component(notebook) select Orbits
            set eltype [$name cget -eltype]
            $itk_component(eltype) select [expr {$eltype - 1}]
            orbtype
            $itk_component(epochofel) insert end [$name cget -epochofel]
            $itk_component(inclination) insert end [$name cget -inclination]
            $itk_component(longascnode) insert end [$name cget -longascnode]
            if { $eltype == 1 } {
               $itk_component(xxxofper) insert end [$name cget -longofper]
            } else {
               $itk_component(xxxofper) insert end [$name cget -argofper]
            }
            if { $eltype == 3 } {
               $itk_component(xxxdist) insert end [$name cget -perdist]
            } else {
               $itk_component(xxxdist) insert end [$name cget -meandist]
            }
            $itk_component(eccentricity) insert end [$name cget -eccentricity]
            if { $eltype == 1 } {
               $itk_component(meanxxxx) insert end [$name cget -meanlong]
            } elseif { $eltype == 2 } {
               $itk_component(meanxxxx) insert end [$name cget -meananom]
            }
            if { $eltype == 1 } {
               $itk_component(dailymot) insert end [$name cget -dailymot]
            }
         }
      }
      $itk_component(airmass) insert end [$name cget -airmassLimit]
   }
}

itcl::body SciTargetControl::updateobj name {
#+
# Updates a target object with the values currently entered in the
# control window.
#-
   $this TargetControl::updateobj $name
   set page [lindex [$itk_component(notebook) pageconfigure \
         [$itk_component(notebook) select select] -label] 4]
   switch $page {
      Planets {
         $name configure \
               -objName [$itk_component(selector) get] \
               -planet $planet
      }
      Orbits {
         set eltype [expr {[$itk_component(eltype) index \
               [$itk_component(eltype) get]] + 1}]
         $name configure \
               -objName [$itk_component(selector) get] \
               -eltype $eltype \
               -epochofel [$itk_component(epochofel) get] \
               -inclination [$itk_component(inclination) get] \
               -longascnode [$itk_component(longascnode) get] \
               -eccentricity [$itk_component(eccentricity) get]
         switch $eltype {
            1 {
               $name configure \
                     -longofper [$itk_component(xxxofper) get] \
                     -argofper "" \
                     -meandist [$itk_component(xxxdist) get] \
                     -perdist "" \
                     -meanlong [$itk_component(meanxxxx) get] \
                     -dailymot [$itk_component(dailymot) get]
            }
            2 {
               $name configure \
                     -longofper "" \
                     -argofper [$itk_component(xxxofper) get] \
                     -meandist [$itk_component(xxxdist) get] \
                     -perdist "" \
                     -meananom [$itk_component(meanxxxx) get] \
                     -dailymot ""
            }
            3 {
               $name configure \
                     -longofper "" \
                     -argofper [$itk_component(xxxofper) get] \
                     -meandist "" \
                     -perdist [$itk_component(xxxdist) get] \
                     -meananom "" \
                     -dailymot ""
            }
         }
      }
   }
   $name configure -airmassLimit [$itk_component(airmass) get]
}

itcl::body SciTargetControl::orbtype {} {
   switch [$itk_component(eltype) get] {
      "Major planet orbital elements" {
         $itk_component(xxxofper) configure -labeltext \
               [lindex [cs orbit info longofper] 2]
         $itk_component(xxxdist) configure -labeltext \
               [lindex [cs orbit info meandist] 2]
         $itk_component(meanxxxx) configure -state normal -labeltext \
               [lindex [cs orbit info meanlong] 2]
         $itk_component(dailymot) configure -state normal
      }
      "Minor planet orbital elements" {
         $itk_component(xxxofper) configure -labeltext \
               [lindex [cs orbit info argofper] 2]
         $itk_component(xxxdist) configure -labeltext \
               [lindex [cs orbit info meandist] 2]
         $itk_component(meanxxxx) configure -state normal -labeltext \
               [lindex [cs orbit info meananom] 2]
         $itk_component(dailymot) configure -state disabled
      }
      "Comet orbital elements" {
         $itk_component(xxxofper) configure -labeltext \
               [lindex [cs orbit info argofper] 2]
         $itk_component(xxxdist) configure -labeltext \
               [lindex [cs orbit info perdist] 2]
         $itk_component(meanxxxx) configure -state disabled
         $itk_component(dailymot) configure -state disabled
      }
   }
}

itcl::body SciTargetControl::copy {createproc wfs} {
   set name [$itk_component(selector) get]
   if { [string is space $name] } {
      tk_messageBox -icon error -parent $itk_interior \
         -message "A name is required to copy a target"
   } else {
      store $name
      ScienceTargetNames::$name copy $createproc
      tcsconfigguide${wfs}Target select $name
   }
}

itcl::body SciTargetControl::selplanet {} {

# Create the Science target object.
   createScienceTarget $planet -planet $planet -objName $planet

# Select it in the list manager.
   $itk_component(selector) select $planet
}
