#+
#  SciTarget <- Target
#
#  Implements the SciTarget class. A SciTarget object stores all
#  the parameters needed to specify a science target.
#
#  Options:
#
#           The following options apply when -type is planet.
#
#              -planet        The planet name.
#
#           The following options apply when -type is orbit.
#
#              -eltype        Type of elements
#
#              -epochofel     Epoch of elements.
#
#              -inclination   Inclination.
#
#              -longascnode   Longitude of ascending node.
#
#              -longofper     Longitude of perihelion.
#
#              -argofper      Argument of perihelion.
#
#              -meandist      Mean distance.
#
#              -perdist       Perihelion distance.
#
#              -eccentricity  Eccentricity.
#
#              -meanlong      Mean longitude.
#
#              -meananom      Mean anomoly.
#
#              -dailymot      Daily motion.
#
#  Methods:
#           apply vt      Applies the target definition to the TCS by 
#                         setting the values of the command parameters
#                         for virtual telescope "vt".
#
#           init          Sets the science target to its initial state.
#
#           preview item  Sets the preview target for "item".
#
#           save file     Writes the values of the target options to the
#                         channel identifier "file".
#
#  Procs:
#           subcomponents Returns a list of the target classes subcomponents.
#
#  D Terrett 21 February 2000
#
#  Copyright CCLRC
#+

itcl::class SciTarget {
   inherit Target

   constructor args {}

   public proc subcomponents {}

   public method apply vt {}
   public method init
   public method preview vt {}
   public method save file

# Type "planet"
   public variable planet {} {if {$planet != ""} {set type planet}}

# Type "orbit"
   public variable eltype {} {if {$eltype != ""} {set type orbit}}
   public variable epochofel {}
   public variable inclination {}
   public variable longascnode {}
   public variable longofper {}
   public variable argofper {}
   public variable meandist {}
   public variable perdist {}
   public variable eccentricity {}
   public variable meanlong {}
   public variable meananom {}
   public variable dailymot {}
}

itcl::body SciTarget::subcomponents {} {
   return { \
      {cosys Cosys CosysNames CosysList {Coordinate System} {}} \
      {wavelength Wavelength WavelengthNames WavelengthList {Wavelength} {}} \
      {trackrate TrackRate TrackRateNames TrackRateList {Differential Track Rate} {}} \
   }
}

itcl::body SciTarget::constructor args {
   eval configure $args
}

itcl::body SciTarget::apply vt {

   switch $type {
      radec {
         cs $vt set objName \"$objName\"
         if { $cosys == "" } {
            cs $vt set system FK5
            cs $vt set equinox J2000
         } else {
            CosysNames::$cosys apply $vt
         }
         cs $vt set theta1 \"[lindex $radec 0]\"
         cs $vt set theta2 \"[lindex $radec 1]\"
         cs $vt set epoch \"$epoch\"
         cs $vt set parallax \"$parallax\"
         if { $pm != "" } {
            cs $vt set dtheta1 \"[lindex $pm 0]\"
            cs $vt set dtheta2 \"[lindex $pm 1]\"
         } else {
            cs $vt set dtheta1 \"\"
            cs $vt set dtheta2 \"\"
         }
         cs $vt set rv \"$rv\"
      }
      azel {
         cs $vt set objName \"$objName\"
         cs $vt set system \"AZEL_TOPO\"
         cs $vt set equinox \"\"
         cs $vt set theta1 \"[lindex $azel 0]\"
         cs $vt set theta2 \"[lindex $azel 1]\"
         cs $vt set epoch \"\"
         cs $vt set parallax \"\"
         cs $vt set dtheta1 \"\"
         cs $vt set dtheta2 \"\"
         cs $vt set rv \"\"
      }
      planet {
         cs $vt set planet $planet
      }
      orbit {
         cs orbit set objName \"$objName\"
         cs orbit set eltype \"$eltype\"
         cs orbit set epochofel \"$epochofel\"
         cs orbit set inclination \"$inclination\"
         cs orbit set longascnode \"$longascnode\"
         if { $eltype == 1 } {
            cs orbit set longofper \"$longofper\"
         } else {
            cs orbit set argofper \"$argofper\"
         }
         if { $eltype == 3 } {
            cs orbit set perdist \"$perdist\"
         } else {
            cs orbit set meandist \"$meandist\"
         }
         cs orbit set eccentricity \"$eccentricity\"
         if { $eltype == 1 } {
            cs orbit set meanlong \"$meanlong\"
         } elseif { $eltype == 2 } {
            cs orbit set meananom \"$meananom\"
         } else {
            cs orbit set meananom \"\"
         }
         if { $eltype == 1 } {
            cs orbit set dailymot \"$dailymot\"
         } else {
            cs orbit set dailymot \"\"
         }
      }
   }
   if { $wavelength_name != "" } {
      if { [info commands ::WavelengthNames::$wavelength_name] != "" } {
         ::WavelengthNames::$wavelength_name apply $vt
      }
   } else {
      if { $wavelength_value != "" } {
         Target::$Wavelength configure -wavel $wavelength_value
         Target::$Wavelength apply $vt
      }
   }
   if { [info commands ::TrackRateNames::$trackrate] != "" } {
      ::TrackRateNames::$trackrate apply $vt
   }
}

itcl::body SciTarget::init {} {
   $this Target::init
   set planet {}
   set eltype {}
   set epochofel {}
   set inclination {}
   set longascnode {}
   set longofper {}
   set argofper {}
   set meandist {}
   set perdist {}
   set eccentricity {}
   set meanlong {}
   set meananom {}
   set dailymot {}
}

itcl::body SciTarget::preview vt {

   if { $cosys == "" } {
      set system FK5
      set equinox J2000
   } else {
      set system [CosysNames::$cosys cget -frame]
      set equinox [CosysNames::$cosys cget -equinox]
   }
   switch $type {
      radec {
         tccPreview set $vt $system [lindex $radec 0] [lindex $radec 1] \
               $equinox $epoch
      }
      azel {
         tccPreview set $vt AZEL_TOPO [lindex $azel 0] [lindex $azel 1]
      }
      planet {
         tccPreview set planet $planet
      }
      orbit {
         switch $eltype {
            1 {
               tccPreview set orbit 1 $epochofel $inclination $longascnode \
                     $longofper $meandist $eccentricity $meanlong $dailymot
            }
            2 {
               tccPreview set orbit 2 $epochofel $inclination $longascnode \
                     $argofper $meandist $eccentricity $meananom
            }
            3 {
               tccPreview set orbit 3 $epochofel $inclination $longascnode \
                     $argofper $perdist $eccentricity
            }
         }
      }
   }
   if { $wavelength_name != "" } {
      if { [info commands ::WavelengthNames::$wavelength_name] != "" } {
         ::WavelengthNames::$wavelength_name preview $vt
      }
   } else {
      if { $wavelength_value != "" } {
         Target::$Wavelength configure -wavel $wavelength_value
         Target::$Wavelength preview $vt
      }
   }
   if { [info commands ::TrackRateNames::$trackrate] != "" } {
      ::TrackRateNames::$trackrate preview $vt
   }
}

itcl::body SciTarget::save file {
   puts $file "   -objName \"$objName\" \\"
   switch $type {
      radec {
         puts $file "   -cosys \"$cosys\" \\"
         puts $file "   -radec \"$radec\" \\"
         puts $file "   -epoch \"$epoch\" \\"
         puts $file "   -parallax \"$parallax\" \\"
         puts $file "   -pm \"$pm\" \\"
         puts $file "   -rv \"$rv\" \\"
      }
      azel {
         puts $file "   -azel \"$azel\" \\"
      }
      planet {
         puts $file "   -planet \"$planet\" \\"
      }
      orbit {
         puts $file "   -eltype \"$eltype\" \\"
         puts $file "   -epochofel \"$epochofel\" \\"
         puts $file "   -inclination \"$inclination\" \\"
         puts $file "   -longascnode \"$longascnode\" \\"
         if { $eltype == 1 } {
            puts $file "   -longofper \"$longofper\" \\"
         } else {
            puts $file "   -argofper \"$argofper\" \\"
         }
         puts $file "   -meandist \"$meandist\" \\"
         puts $file "   -perdist \"$perdist\" \\"
         puts $file "   -eccentricity \"$eccentricity\" \\"
         puts $file "   -meanlong \"$meanlong\" \\"
         if { $eltype == 1 || $eltype == 2 } {
            puts $file "   -meananom \"$meananom\" \\"
         }
         if { $eltype == 1 } {
            puts $file "   -dailymot \"$dailymot\" \\"
         }
      }
   }
   puts $file "   -wavelength_name \"$wavelength_name\" \\"
   puts $file "   -wavelength_value \"$wavelength_value\" \\"
   puts $file "   -trackrate \"$trackrate\""
}
