#+
#  SciTargetComponent <- SciTarget, tcclib::Component
#
#  A SciTargetComponent object is a SciTarget object that is stored in a 
#  configuration list.
#
#
#  Options:
#           none
#
#  Methods:
#           constructor list  Creates the SciTarget object and puts it onto
#                           "list".
#
#           save file       Writes commands to re-create the object to the
#                           channel identifier "file" and then calls the
#                           SciTarget save method to add the objects data.
#
#  D Terrett 15 March 2001
#
#  Copyright CCLRC
#+

itcl::class SciTargetComponent {
   inherit SciTarget tcclib::Component
   constructor {list args} {
      tcclib::Component::constructor $list
   } {
      eval configure $args
   }
   public {
      method save {file}
   }
}

itcl::body SciTargetComponent::save file {
   set obj [namespace tail $this]
   set namespace [namespace qualifiers $this]
   puts $file \
         "catch {SciTargetComponent [list ${namespace}::$obj]  $componentList}"
   puts $file "[list ${namespace}::$obj] init"
   puts $file "[list ${namespace}::$obj] configure \\"
   SciTarget::save $file
}
