#+
#  SciTarget <- Target
#
#  Implements the SciTarget class. A SciTarget object stores all
#  the parameters needed to specify a science target.
#
#  Options:
#              -airmassLimit  The airmass limit to apply when using the
#                             instrument.
#
#           The following options apply when -type is planet.
#
#              -planet        The planet name.
#
#           The following options apply when -type is orbit.
#
#              -eltype        Type of elements
#
#              -epochofel     Epoch of elements.
#
#              -inclination   Inclination.
#
#              -longascnode   Longitude of ascending node.
#
#              -longofper     Longitude of perihelion.
#
#              -argofper      Argument of perihelion.
#
#              -meandist      Mean distance.
#
#              -perdist       Perihelion distance.
#
#              -eccentricity  Eccentricity.
#
#              -meanlong      Mean longitude.
#
#              -meananom      Mean anomoly.
#
#              -dailymot      Daily motion.
#
#  Methods:
#           apply vt      Applies the target definition to the TCS by 
#                         setting the values of the command parameters
#                         for virtual telescope "vt".
#
#           grab vt       Grabs the current science target from the tcs.
#
#           init          Sets the science target to its initial state.
#
#           preview item  Sets the preview target for "item".
#
#           save file     Writes the values of the target options to the
#                         channel identifier "file".
#
#  Procs:
#           subcomponents Returns a list of the target classes subcomponents.
#
#  D Terrett 26 June 2000
#
#  Copyright CCLRC
#+

itcl::class SciTarget {
   inherit Target
   public {
      proc subcomponents {} {return [Target::subcomponents]}
      method apply {vt}
      method grab {vt}
      method init {}
      method preview {vt}
      method save {file}
      variable airmassLimit {}

# Type "planet"
      variable planet {} {if { ! [string equal $planet ""] } {set type planet}}

# Type "orbit"
      variable eltype {} {if { ! [string equal $eltype ""] } {set type orbit}}
      variable epochofel {}
      variable inclination {}
      variable longascnode {}
      variable longofper {}
      variable argofper {}
      variable meandist {}
      variable perdist {}
      variable eccentricity {}
      variable meanlong {}
      variable meananom {}
      variable dailymot {}
   }
}

itcl::body SciTarget::apply vt {

   $this Target::apply $vt

   if { ![string is space $airmassLimit] } {
      cs airmassLimit set limit $airmassLimit
      logger command airmassLimit
   }

   switch $type {
      planet {
         cs planet set object $planet
         logger command planet
      }
      orbit {
         cs orbit set objName \"$objName\"
         cs orbit set eltype \"$eltype\"
         cs orbit set epochofel \"$epochofel\"
         cs orbit set inclination \"$inclination\"
         cs orbit set longascnode \"$longascnode\"
         if { $eltype == 1 } {
            cs orbit set longofper \"$longofper\"
         } else {
            cs orbit set argofper \"$argofper\"
         }
         if { $eltype == 3 } {
            cs orbit set perdist \"$perdist\"
         } else {
            cs orbit set meandist \"$meandist\"
         }
         cs orbit set eccentricity \"$eccentricity\"
         if { $eltype == 1 } {
            cs orbit set meanlong \"$meanlong\"
         } elseif { $eltype == 2 } {
            cs orbit set meananom \"$meananom\"
         } else {
            cs orbit set meananom \"\"
         }
         if { $eltype == 1 } {
            cs orbit set dailymot \"$dailymot\"
         } else {
            cs orbit set dailymot \"\"
         }
         logger command orbit
      }
   }
}

itcl::body SciTarget::init {} {
   $this Target::init
   set airmassLimit ""
   set planet {}
   set eltype {}
   set epochofel {}
   set inclination {}
   set longascnode {}
   set longofper {}
   set argofper {}
   set meandist {}
   set perdist {}
   set eccentricity {}
   set meanlong {}
   set meananom {}
   set dailymot {}
}

itcl::body SciTarget::preview vt {

   $this Target::preview $vt
   switch $type {
      planet {
         tccPreview set planet $planet
      }
      orbit {
         switch $eltype {
            1 {
               tccPreview set orbit 1 $epochofel $inclination $longascnode \
                     $longofper $meandist $eccentricity $meanlong $dailymot
            }
            2 {
               tccPreview set orbit 2 $epochofel $inclination $longascnode \
                     $argofper $meandist $eccentricity $meananom
            }
            3 {
               tccPreview set orbit 3 $epochofel $inclination $longascnode \
                     $argofper $perdist $eccentricity
            }
         }
      }
   }
}

itcl::body SciTarget::save file {
   $this Target::save $file
   puts $file "\"$this\" configure \\"
   switch $type {
      planet {
         puts $file "   -planet \"$planet\""
      }
      orbit {
         puts $file "   -eltype \"$eltype\" \\"
         puts $file "   -epochofel \"$epochofel\" \\"
         puts $file "   -inclination \"$inclination\" \\"
         puts $file "   -longascnode \"$longascnode\" \\"
         if { $eltype == 1 } {
            puts $file "   -longofper \"$longofper\" \\"
         } else {
            puts $file "   -argofper \"$argofper\" \\"
         }
         puts $file "   -meandist \"$meandist\" \\"
         puts $file "   -perdist \"$perdist\" \\"
         puts $file "   -eccentricity \"$eccentricity\" \\"
         puts $file "   -meanlong \"$meanlong\" \\"
         if { $eltype == 1 || $eltype == 2 } {
            puts $file "   -meananom \"$meananom\" \\"
         }
         if { $eltype == 1 } {
            puts $file "   -dailymot \"$dailymot\" \\"
         }
      }
   }
   puts $file "   -airmassLimit \"$airmassLimit\""
}

itcl::body SciTarget::grab vt {
   Target::grab $vt
   set airmassLimit [sa tcssad get airMassLimit]
}
