#+
#  SciTargetPanel <- Panel
#
#  Implements the SciTargetPanel widget. A Panel widget with a 
#  SciTargetControl widget packed into its interior.
#
#  Methods:
#           none
#
#  D Terrett 28 March 2001
#
#  Copyright CCLRC
#+

itcl::class SciTargetPanel {
   inherit Panel
   constructor args {}
}

itk::usual SciTargetPanel {
   keep -background -cursor
}

itcl::body SciTargetPanel::constructor args {
   itk_component add control {
      SciTargetControl $itk_interior.control
   }
   setWidgetColors "$itk_component(menubar) $itk_component(control)" \
         $itk_option(-background) $itk_option(-foreground)

   pack $itk_component(control) -fill both -expand y

   set itk_option(-windows) $itk_component(control)

   eval itk_initialize $args
}
