#+
#  SlewOptions <- tcclib::Paramset
#
#  Implements the SlewOptions class. A SlewOptions object stores all the 
#  flags of the Slew CAD command.
#
#  Options:
#          All the following options specify whether the corresponding
#          element in the TCS configuration should be reset.
#
#          -chopThrow        Chop throw.
#
#          -sourceOffset     Source offsets.
#
#          -sourceDifTr      Source differential tracking.
#
#          -mountOffset      Mount offsets
#
#          -mountDifTr       Mount differential tracking.
#
#          -filter1          Filter 1.
#
#          -filter2          Filter 2.
#
#          -pointing         Local pointing offsets.
#
#          -guiding          Guiding.
#
#          -guideOffset      Guide star offsets.
#
#  Methods:
#           apply comp Applies the slew options to the TCS by setting 
#                      the values of the command parameters.
#
#           init       Returns the slew options object to its initial state.
#
#           preview    Does nothing. The method exist so that all components
#                      have a preview method.
#
#           save node  Saves all the slew option values to the xml node.
#
#  D Terrett 21 March 2002
#
#  Copyright CCLRC
#+

itcl::class SlewOptions {
   inherit tcclib::Paramset
   public {
      method apply {comp}
      method init {}
      method preview {}
      method save {node}
      variable chopThrow {}
      variable sourceOffset {}
      variable sourceDifTr {}
      variable mountOffset {}
      variable mountDifTr {}
      variable filter1 {}
      variable filter2 {}
      variable pointing {}
      variable guiding {}
      variable guideOffset {}
   }
}

itcl::body SlewOptions::apply {comp} {
   cs slew set chopThrow [list $chopThrow]
   cs slew set sourceOffset [list $sourceOffset]
   cs slew set sourceDifTr [list $sourceDifTr]
   cs slew set mountOffset [list $mountOffset]
   cs slew set mountDifTr [list $mountDifTr]
   cs slew set filter1 [list $filter1]
   cs slew set filter2 [list $filter2]
   cs slew set pointing [list $pointing]
   cs slew set guiding [list $guiding]
   cs slew set guideOffset [list $guideOffset]
   logger command slew
}

itcl::body SlewOptions::init {} {
   set  chopThrow {}
   set  sourceOffset {}
   set  sourceDifTr {}
   set  mountOffset {}
   set  mountDifTr {}
   set  filter1 {}
   set  filter2 {}
   set  pointing {}
   set  guiding {}
   set  guideOffset {}
}

itcl::body SlewOptions::preview {} {}

body SlewOptions::save {node} {
   set node [paramset $node slew_options]
   param $node chopThrow $chopThrow
   param $node sourceOffset $sourceOffset
   param $node sourceDifTr $sourceDifTr
   param $node mountOffset $mountOffset
   param $node mountDifTr $mountDifTr
   param $node filter1 $filter1
   param $node filter2 $filter2
   param $node pointing $pointing
   param $node guiding $guiding
   param $node guideOffset $guideOffset
}
