#+
#  SlewOptionsComponent.itcl
#
#  Implements the SlewOptionsComponent class. A SlewOptionsComponent object 
#  is a SlewOptions object that is stored in a configuration.
#
#  D Terrett 19 August 1999
#
#  Copyright CCLRC
#+

itcl::class SlewOptionsComponent {
   inherit SlewOptions Component

   constructor {list args} {
      Component::constructor $list
   } {
      eval configure $args
   }

   public method save file
}

itcl::body SlewOptionsComponent::save file {
   set objname [namespace tail $this]
   set namespace [namespace qualifiers $this]
   puts $file "catch {delete object \"${namespace}::$objname\"}"
   puts $file "SlewOptionsComponent \"${namespace}::$objname\"  $componentList \\"
   SlewOptions::save $file
}
