#+
#  SlewOptionsPanel <- tcclib::Panel
#
#  Implements the SlewOptionsPanel widget. A Panel widget with a 
#  SlewOptionsControl widget packed into its interior.
#
#  Methods:
#           none
#
#
#  D Terrett 29 March 2000
#
#  Copyright CCLRC
#+

itcl::class SlewOptionsPanel {
   inherit tcclib::Panel
   constructor args {}
}

itk::usual SlewOptionsPanel {
   keep -background -cursor
}

itcl::body SlewOptionsPanel::constructor args {
   itk_component add control {
      SlewOptionsControl $itk_interior.control
   }
   setWidgetColors "$itk_component(menubar) $itk_component(control)" \
         $itk_option(-background) $itk_option(-foreground)

   pack $itk_component(control) -fill both -expand y

   eval itk_initialize $args
}
