#+
#  SlewOptionsComponent <- SlewOptions, tcclib::Component
#
#  A SlewOptionsComponent object is a SlewOptions object that is stored in a 
#  configuration list.
#
#
#  Options:
#           none
#
#  Methods:
#           constructor list  Creates the SlewOptions object and puts it onto
#                           "list".
#
#           save file       Writes commands to re-create the object to the
#                           channel identifier "file" and then calls the
#                           SlewOptions save method to add the objects data.
#
#  D Terrett 15 March 2001
#
#  Copyright CCLRC
#+

itcl::class SlewOptionsComponent {
   inherit SlewOptions tcclib::Component
   constructor {list args} {
      tcclib::Component::constructor $list
   } {
      eval configure $args
   }
   public {
      method save {file}
   }
}

itcl::body SlewOptionsComponent::save file {
   set obj [namespace tail $this]
   set namespace [namespace qualifiers $this]
   puts $file \
         "catch {SlewOptionsComponent [list ${namespace}::$obj]  $componentList}"
   puts $file "[list ${namespace}::$obj] init"
   puts $file "[list ${namespace}::$obj] configure \\"
   SlewOptions::save $file
}
