#+
#  SlewOptionsControl.itk
#
#  Implements the SlewOptionsControl widget. A ComponentControl widget with
#  checkbutton widgets for each of the Slew CAD parameters.
#
#  D Terrett 3 November 1998
#
#  Copyright CCLRC
#+

itcl::class SlewOptionsControl {
   inherit ComponentControl

   constructor args {}

   public method selectobj name
   public method updateobj name
}

itk::usual SlewOptionsControl {
   keep -activebackground -activeforeground -disabledforeground
   keep -background -borderwidth -cursor -foreground -highlightcolor
   keep -highlightthickness -insertbackground -insertborderwidth
   keep -insertofftime -insertontime -insertwidth -labelfont -popupcursor
   keep -selectbackground -selectborderwidth -selectforeground
   keep -textbackground -textfont -font
   keep -vt -title
}

itcl::body SlewOptionsControl::constructor args {

# Frame for all the options.
   itk_component add options {
      frame $itk_interior.options -bd 2 -relief ridge
   }
   pack $itk_interior.options -fill x -expand y

# Checkbuttons for the options.
   set w $itk_component(options)
   itk_component add chopThrow {
      checkbutton $w.chopThrow -variable $w._chopThrow \
            -onvalue On -offvalue Off \
            -text [lindex [cs slew info chopThrow] 2]
   }
   itk_component add sourceOffset {
      checkbutton $w.sourceOffset -variable $w._sourceOffset \
            -onvalue On -offvalue Off \
            -text [lindex [cs slew info sourceOffset] 2]
   }
   itk_component add sourceDifTr {
      checkbutton $w.sourceDifTr -variable $w._sourceDifTr \
            -onvalue On -offvalue Off \
            -text [lindex [cs slew info sourceDifTr] 2]
   }
   itk_component add mountOffset {
      checkbutton $w.mountOffset -variable $w._mountOffset \
            -onvalue On -offvalue Off \
            -text [lindex [cs slew info mountOffset] 2]
   }
   itk_component add mountDifTr {
      checkbutton $w.mountDifTr -variable $w._mountDifTr \
            -onvalue On -offvalue Off \
            -text [lindex [cs slew info mountDifTr] 2]
   }
   itk_component add filter1 {
      checkbutton $w.filter1 -variable $w._filter1 \
            -onvalue On -offvalue Off \
            -text [lindex [cs slew info filter1] 2]
   }
   itk_component add filter2 {
      checkbutton $w.filter2 -variable $w._filter2 \
            -onvalue On -offvalue Off \
            -text [lindex [cs slew info filter2] 2]
   }
   itk_component add pointing {
      checkbutton $w.pointing -variable $w._pointing \
            -onvalue On -offvalue Off \
            -text [lindex [cs slew info pointing] 2]
   }
   itk_component add guiding {
      checkbutton $w.guiding -variable $w._guiding \
            -onvalue On -offvalue Off \
            -text [lindex [cs slew info guiding] 2]
   }
   pack $itk_component(chopThrow) $itk_component(sourceOffset) \
          $itk_component(sourceDifTr) $itk_component(mountOffset) \
          $itk_component(mountDifTr) $itk_component(filter1) \
          $itk_component(filter2) $itk_component(pointing) \
          $itk_component(guiding) -pady 2 -anchor w

# Set the apply log message.
   $itk_component(storeapply) configure -logmessage "Slew options"

# Create the slewOptions object used by apply.
   set scratchobj [namespace which -command [SlewOptions #auto]]

# Set the object class
   set objclass SlewOptionsComponent
   set description "slew options"

   eval itk_initialize $args
}

itcl::body SlewOptionsControl::updateobj name {
#+
# Updates the named slew options object.
#-
   upvar #0 [$itk_component(chopThrow) cget -variable] chopThrow
   upvar #0 [$itk_component(sourceOffset) cget -variable] sourceOffset
   upvar #0 [$itk_component(sourceDifTr) cget -variable] sourceDifTr
   upvar #0 [$itk_component(mountOffset) cget -variable] mountOffset
   upvar #0 [$itk_component(mountDifTr) cget -variable] mountDifTr
   upvar #0 [$itk_component(filter1) cget -variable] filter1
   upvar #0 [$itk_component(filter2) cget -variable] filter2
   upvar #0 [$itk_component(pointing) cget -variable] pointing
   upvar #0 [$itk_component(guiding) cget -variable] guiding

   $name configure \
         -chopThrow $chopThrow -sourceOffset $sourceOffset \
         -sourceDifTr $sourceDifTr -mountOffset $mountOffset \
         -mountDifTr $mountDifTr -filter1 $filter1 \
         -filter2 $filter2 -pointing $pointing \
         -guiding $guiding
}

itcl::body SlewOptionsControl::selectobj name {
#+
# Copies the contents of the SlewOptions object selected in the combobox
# into the checkbuttons.
#-
   if { $name != "" } {
      upvar #0 [$itk_component(chopThrow) cget -variable] chopThrow
      upvar #0 [$itk_component(sourceOffset) cget -variable] sourceOffset
      upvar #0 [$itk_component(sourceDifTr) cget -variable] sourceDifTr
      upvar #0 [$itk_component(mountOffset) cget -variable] mountOffset
      upvar #0 [$itk_component(mountDifTr) cget -variable] mountDifTr
      upvar #0 [$itk_component(filter1) cget -variable] filter1
      upvar #0 [$itk_component(filter2) cget -variable] filter2
      upvar #0 [$itk_component(pointing) cget -variable] pointing
      upvar #0 [$itk_component(guiding) cget -variable] guiding

      set chopThrow [$name cget -chopThrow]
      set sourceOffset [$name cget -sourceOffset]
      set sourceDifTr [$name cget -sourceDifTr]
      set mountOffset [$name cget -mountOffset]
      set mountDifTr [$name cget -mountDifTr]
      set filter1 [$name cget -filter1]
      set filter2 [$name cget -filter2]
      set pointing [$name cget -pointing]
      set guiding [$name cget -guiding]
   }
}
