#+
#  SlewOptionsControl <- ComponentControl
#
#  A SlewOptionsControl is a ComponentControl widget with checkbutton widgets 
#  for each of the Slew CAD parameters.
#
#  Options:
#           none
#
#  Methods:
#           selectobj name  Copies the contents of the SlewOptions object "name"
#                           into the edit controls.
#
#           updateobj name  Stores the contents of the edit controls in the
#                           SlewOptions object "name".
#
#  D Terrett 1 December 2000
#
#  Copyright CCLRC
#+

itcl::class SlewOptionsControl {
   inherit ComponentControl
   constructor args {}
   public {
      method selectobj {name}
      method updateobj {name}
   }
   private {
      variable chopThrow
      variable sourceOffset
      variable sourceDifTr
      variable mountOffset
      variable mountDifTr
      variable filter1
      variable filter2
      variable pointing
      variable guiding
      variable guideOffset
   }
}

itk::usual SlewOptionsControl {
   keep -borderwidth -cursor -font -highlightthickness -insertborderwidth \
         -insertofftime -insertontime -insertwidth -labelfont -popupcursor \
         -selectborderwidth -textfont -title -vt
}

itcl::body SlewOptionsControl::constructor args {

# Frame for all the options.
   itk_component add options {
      frame $itk_interior.options -bd 2 -relief ridge
   }
   pack $itk_interior.options -fill x -expand y

# Checkbuttons for the options.
   set w $itk_component(options)
   itk_component add chopThrow {
      checkbutton $w.chopThrow -variable [scope chopThrow] \
            -onvalue On -offvalue Off \
            -text [lindex [cs slew info chopThrow] 2]
   }
   itk_component add sourceOffset {
      checkbutton $w.sourceOffset -variable [scope sourceOffset] \
            -onvalue On -offvalue Off \
            -text [lindex [cs slew info sourceOffset] 2]
   }
   itk_component add sourceDifTr {
      checkbutton $w.sourceDifTr -variable [scope sourceDifTr] \
            -onvalue On -offvalue Off \
            -text [lindex [cs slew info sourceDifTr] 2]
   }
   itk_component add mountOffset {
      checkbutton $w.mountOffset -variable [scope mountOffset] \
            -onvalue On -offvalue Off \
            -text [lindex [cs slew info mountOffset] 2]
   }
   itk_component add mountDifTr {
      checkbutton $w.mountDifTr -variable [scope mountDifTr] \
            -onvalue On -offvalue Off \
            -text [lindex [cs slew info mountDifTr] 2]
   }
   itk_component add filter1 {
      checkbutton $w.filter1 -variable [scope filter1] \
            -onvalue On -offvalue Off \
            -text [lindex [cs slew info filter1] 2]
   }
   itk_component add filter2 {
      checkbutton $w.filter2 -variable [scope filter2] \
            -onvalue On -offvalue Off \
            -text [lindex [cs slew info filter2] 2]
   }
   itk_component add pointing {
      checkbutton $w.pointing -variable [scope pointing] \
            -onvalue On -offvalue Off \
            -text [lindex [cs slew info pointing] 2]
   }
   itk_component add guiding {
      checkbutton $w.guiding -variable [scope guiding] \
            -onvalue On -offvalue Off \
            -text [lindex [cs slew info guiding] 2]
   }
   itk_component add guideOffset {
      checkbutton $w.guideOffset -variable [scope guideOffset] \
            -onvalue On -offvalue Off \
            -text [lindex [cs slew info guideOffset] 2]
   }
   pack $itk_component(chopThrow) $itk_component(sourceOffset) \
          $itk_component(sourceDifTr) $itk_component(mountOffset) \
          $itk_component(mountDifTr) $itk_component(filter1) \
          $itk_component(filter2) $itk_component(pointing) \
          $itk_component(guiding) $itk_component(guideOffset) -pady 2 -anchor w

# Create the slewOptions object used by apply.
   set scratchobj [namespace which -command [SlewOptions #auto]]

# Set the object class
   set objclass SlewOptionsComponent
   set description "slew options"

   eval itk_initialize $args
}

itcl::body SlewOptionsControl::selectobj name {

# Copy the contents of the SlewOptions object selected in the combobox
# into the checkbuttons.
   if { ! [string equal $name ""] } {
      set chopThrow [$name cget -chopThrow]
      set sourceOffset [$name cget -sourceOffset]
      set sourceDifTr [$name cget -sourceDifTr]
      set mountOffset [$name cget -mountOffset]
      set mountDifTr [$name cget -mountDifTr]
      set filter1 [$name cget -filter1]
      set filter2 [$name cget -filter2]
      set pointing [$name cget -pointing]
      set guiding [$name cget -guiding]
      set guideOffset [$name cget -guideOffset]
   }
}

itcl::body SlewOptionsControl::updateobj name {

# Update the named slew options object.
   $name configure \
         -chopThrow $chopThrow -sourceOffset $sourceOffset \
         -sourceDifTr $sourceDifTr -mountOffset $mountOffset \
         -mountDifTr $mountDifTr -filter1 $filter1 \
         -filter2 $filter2 -pointing $pointing \
         -guiding $guiding -guideOffset $guideOffset
}
