#+
#  SlewOptions
#
#  Implements the SlewOptions class. A SlewOptions object stores all the 
#  flags of the Slew CAD command.
#
#  Options:
#          All the following options specify whether the corresponding
#          element in the TCS configuration should be reset.
#
#          -chopThrow        Chop throw.
#
#          -sourceOffset     Source offsets.
#
#          -sourceDifTr      Source differential tracking.
#
#          -mountOffset      Mount offsets
#
#          -mountDifTr       Mount differential tracking.
#
#          -filter1          Filter 1.
#
#          -filter2          Filter 2.
#
#          -pointing         Local pointing offsets.
#
#          -guiding          Guiding.
#
#          -guideOffset      Guide star offsets.
#
#  Methods:
#           apply     Applies the slew options to the TCS by setting 
#                     the values of the command parameters.
#
#           init      Returns the slew options object to its initial state.
#
#           preview   Does nothing. The method exist so that all components
#                     have a preview method.
#
#           save file Writes all the slew option values to the channel
#                     identifier "file".
#
#  D Terrett 1 December 2000
#
#  Copyright CCLRC
#+

itcl::class SlewOptions {
   public {
      proc subcomponents {} {return {}}
      method apply {args}
      method init {}
      method preview {}
      method save {file}
      variable chopThrow {}
      variable sourceOffset {}
      variable sourceDifTr {}
      variable mountOffset {}
      variable mountDifTr {}
      variable filter1 {}
      variable filter2 {}
      variable pointing {}
      variable guiding {}
      variable guideOffset {}
   }
}

itcl::body SlewOptions::apply args {
   cs slew set chopThrow \"$chopThrow\"
   cs slew set sourceOffset \"$sourceOffset\"
   cs slew set sourceDifTr \"$sourceDifTr\"
   cs slew set mountOffset \"$mountOffset\"
   cs slew set mountDifTr \"$mountDifTr\"
   cs slew set filter1 \"$filter1\"
   cs slew set filter2 \"$filter2\"
   cs slew set pointing \"$pointing\"
   cs slew set guiding \"$guiding\"
   cs slew set guideOffset \"$guideOffset\"
   logger command slew
}

itcl::body SlewOptions::init {} {
   set  chopThrow {}
   set  sourceOffset {}
   set  sourceDifTr {}
   set  mountOffset {}
   set  mountDifTr {}
   set  filter1 {}
   set  filter2 {}
   set  pointing {}
   set  guiding {}
   set  guideOffset {}
}

itcl::body SlewOptions::preview {} {}

body SlewOptions::save file {
   puts $file "   -chopThrow \"$chopThrow\" \\"
   puts $file "   -sourceOffset \"$sourceOffset\" \\"
   puts $file "   -sourceDifTr \"$sourceDifTr\" \\"
   puts $file "   -mountOffset \"$mountOffset\" \\"
   puts $file "   -mountDifTr \"$mountDifTr\" \\"
   puts $file "   -filter1 \"$filter1\" \\"
   puts $file "   -filter2 \"$filter2\" \\"
   puts $file "   -pointing \"$pointing\" \\"
   puts $file "   -guiding \"$guiding\""
   puts $file "   -guideOffset \"$guideOffset\""
}
