#+
#  StarSelectControl.itk
#
#  Implements the StarSelectControl widget.
#
#  D Terrett 17 January 2004
#
#  Copyright CCLRC
#-

itcl::class StarSelectControl {
   inherit itk::Widget
   constructor args {}
   destructor {}
   itk_option define -menubar menubar Menubar {}
   public {
      method load {}
      method unload {cat}
   }
   private {
      method selectstar {cat tag}
      variable StarCats
   }
}

itk::usual StarSelectControl {
   keep -menubar
}

itcl::body StarSelectControl::constructor args {

# AzElPlot.
   itk_component add azelplot {
      AzElPlot $itk_interior.azelplot \
            -selectioncommand [itcl::code $this selectstar]
   }
   pack $itk_component(azelplot)

# Configure the field list with the name of the AzElPlot. This causes the
# field to be plotted in the widget so it must be posponed until the
# widget has been created.
#   after idle FieldList configure -azelplot $itk_component(azelplot)

   eval itk_initialize $args
}

itcl::body StarSelectControl::destructor {} {
   foreach cat [array names StarCats] {
      itcl::delete object $StarCats($cat)
   }
}

itcl::body StarSelectControl::selectstar {cat tag} {
#+
# If the name of the object being selected matches an existing field then
# that field is selected; otherwise a new target is created in the current
# field.
#-

# Get the object name.
   set object [$StarCats($cat) extract $tag]
   set name [lindex $object 0]

# Get the full name of the field with the same name.
   set field $::Config(tcs.field,namespace)::$name

# See if a field with the same name as the object exists.
   if { [lsearch -exact [itcl::find objects -class FieldComponent] \
         $field] < 0 } {

# Field did not exist so create it.
      FieldComponent $field $::Config(tcs.field,list)
   }

# Select the field
   tcsFieldPanel map
   set ::Config(tcs.field,value) $name

   $::Config(tcs.field,panel) map sciencetarget
   [$::Config(tcs.field,panel) cget -name] \
         newtarget [lindex $object 0] sciencetarget \
         -objname [lindex $object 0] \
         -type hmsdegTarget \
         -c1 [lindex $object 1] \
         -c2 [lindex $object 2] \
         -system [lindex $object 3] \
         -epoch [lindex $object 4] \
         -pmunits [lindex $object 5] \
         -pm1 [lindex $object 6] \
         -pm2 [lindex $object 7] \
         -parallax [lindex $object 8] \
         -rv [lindex $object 9] \
         -brightness [lindex $object 10]
}

itcl::body StarSelectControl::load {} {

# cd to the catalogue directory
   set pwd [pwd]
   global CATALOG_DIR
   cd $CATALOG_DIR

# Create a dialog box for selecting the file and center it.
   set dialog  $itk_interior.catloaddialog
   if { ! [winfo exists $dialog] } {
      set dialog [CatLoadDialog $dialog \
            -modality application -title "Catalog File Selection Dialog" \
            -master $itk_interior -mask *.dat]
      $dialog center
   }

# Activate the dialog
   if { [$dialog activate] } {

# Get the colour for ploting.
      set catcolour [[$dialog component colour] get]

# Check that it is a valid colour.
      if { [catch {winfo rgb . $catcolour}] } {
         [$dialog component colour] clear entry
         if { ! [catch { [$dialog component colour] get $catcolour}] } {
            [$dialog component colour] delete list $catcolour
         }
         tk_messageBox -icon error -message \
          "\"$catcolour\" is not a valid color"
      } else {

# Open the file.
         set filename [$dialog get]
         if { [catch {set file [open $filename RDONLY]} msg] } {
            tk_messageBox -icon error -message $msg
         } else {

# Extract the file name to use as the catalogue name.
            set catname [file rootname [file tail $filename]]

# Create the catalogue if it doesn't exist.
            if { [string is space [array names StarCats $catname]] } {
               set StarCats($catname) [Catalogue #auto $catname \
                     $itk_component(azelplot) $catcolour]

# Add commands to the view and unload menus.
               $itk_option(-menubar) add command .file.view.$catname \
                    -command "[namespace code $StarCats($catname)] view" \
                    -label $catname
               $itk_option(-menubar) add command .file.unload.$catname \
                    -command [itcl::code $this unload $catname] \
                    -label $catname
            }

# Load it.
            $StarCats($catname) load $file

# Close the file.
            close $file
         }
      }
   }
   $dialog deactivate

# restore the default directory
   cd $pwd
}

itcl::body StarSelectControl::unload {cat} {
   itcl::delete object $StarCats($cat)
   unset StarCats($cat)
   $itk_option(-menubar) delete .file.view.$cat
   $itk_option(-menubar) delete .file.unload.$cat
}
