#+
#  TargetHandsetPanel <- Panel
#
#  Implements the TargetHandsetPanel widget. A Panel widget with a 
#  TargetHandsetControl widget packed into its interior.
#
#  Options:
#          none
#
#  Methods:
#          none
#
#  D Terrett 12 January 2001
#
#  Copyright CCLRC
#+

itcl::class TargetHandsetPanel {
   inherit Panel
   constructor args {}
}

itk::usual TargetHandsetPanel {
   keep -background -cursor
}

itcl::body TargetHandsetPanel::constructor args {

   itk_component add control {
      TargetHandsetControl $itk_interior.control
   }
   setWidgetColors "$itk_component(menubar) $itk_component(control)" \
         $itk_option(-background) $itk_option(-foreground)

   pack $itk_component(control) -fill both -expand y

   set itk_option(-windows) $itk_component(control)

   eval itk_initialize $args
}
