#+
#  Target
#
#  Implements the Target class. A Target object stores all
#  the parameters needed to specify a target.
#
#  Options:
#           -objName       The object name
#
#           -type          The type of the coordinate (radec, or azel).
#
#           -wavelength_name
#
#           -wavelength_value
#
#           The following options apply when -type is radec.
#
#              -cosys         The target coordinate system.
#
#              -epoch         The epoch of the position.
#
#              -parallax      The parallax.
#
#              -radec         Right ascension and declination.
#
#              -pm            Proper motions in ra and dec
#
#              -rv            Radial velocity.
#
#           The following options apply when -type is radec.
#
#              -azel          Azimuth and elevation.
#
#  Methods:
#           apply vt      Applies the target definition to the TCS by 
#                         setting the values of the command parameters
#                         for virtual telescope "vt".
#
#           grab vt       Grabs the current tracking position of the
#                         virtual telescope vt.
#
#           init          Returns the rotator object to its initial state.
#
#           preview item  Sets the preview target for "item".
#
#           save file     Writes the values of the target options to the
#                         channel identifier "file".
#
#  Procs:
#           subcomponents Returns a list of the target classes subcomponents.
#
#  D Terrett 2 February 2001
#
#  Copyright CCLRC
#+

itcl::class Target {
   constructor args {}
   destructor {$this init}
   public {
      proc subcomponents {}
      method apply {vt}
      method copy {createproc}
      method grab {vt}
      method init {}
      method preview {vt}
      method save {file}
      variable type {}
      variable objName {}

# Type "radec"
      variable radec {} {if { ![string equal $radec ""] } {set type radec}}
      variable cosys {}
      variable epoch {}
      variable parallax 0
      variable pm {}
      variable rv 0

# Type "azel"
      variable azel {} {if { ! [string equal $azel ""] } {set type azel}}

      variable wavelength_name {}
      variable wavelength_value {} {
         set wavelength_value [valWavelength $wavelength_value]
      }
      variable trackrate {}
   }
   protected {
      common Wavelength ""
   }
   private {
      variable current_cosys {}
      variable current_wavelength_name {}
      variable current_trackrate {}
   }
}

itcl::body Target::subcomponents {} {
   return { \
      {cosys Cosys CosysNames CosysList {Coordinate System} {}} \
      {wavelength Wavelength WavelengthNames WavelengthList {Wavelength} {}} \
      {trackrate TrackRate TrackRateNames TrackRateList {Differential Track Rate} {}} \
   }
}

itcl::body Target::constructor args {

# Create the scratch wavelength object if it doesn't already exist.
   if { [info commands $Wavelength] == "" } {
      set Wavelength [Wavelength #auto]
   }
   eval configure $args
}

itcl::body Target::apply vt {

   switch $type {
      radec {
         cs $vt set objName \"$objName\"
         if { [string equal $cosys ""] } {
            cs $vt set system FK5
            cs $vt set equinox J2000
         } else {
            CosysNames::$cosys apply $vt
         }
         cs $vt set theta1 \"[lindex $radec 0]\"
         cs $vt set theta2 \"[lindex $radec 1]\"
         cs $vt set epoch \"$epoch\"
         cs $vt set parallax \"$parallax\"
         if { [string equal $pm ""] } {
            cs $vt set dtheta1 \"\"
            cs $vt set dtheta2 \"\"
         } else {
            cs $vt set dtheta1 \"[lindex $pm 0]\"
            cs $vt set dtheta2 \"[lindex $pm 1]\"
         }
         cs $vt set rv \"$rv\"
      }
      azel {
         cs $vt set objName \"$objName\"
         cs $vt set system \"AZEL_TOPO\"
         cs $vt set equinox \"\"
         cs $vt set theta1 \"[lindex $azel 0]\"
         cs $vt set theta2 \"[lindex $azel 1]\"
         cs $vt set epoch \"\"
         cs $vt set parallax \"\"
         cs $vt set dtheta1 \"\"
         cs $vt set dtheta2 \"\"
         cs $vt set rv \"\"
      }
   }
   logger command $vt
   if { [string equal $wavelength_name ""] } {
      if { ! [string equal $wavelength_value ""] } {
         $Wavelength configure -wavel $wavelength_value
         $Wavelength apply $vt
      }
   } else {
      if { ! [string equal $wavelength_name ""] } {
         ::WavelengthNames::$wavelength_name apply $vt
      }
   }
   if { ! [string equal $trackrate ""] } {
      ::TrackRateNames::$trackrate apply $vt
   }
}

itcl::body Target::init {} {

   set type {}
   set objName {}
   set radec {}
   $this configure -cosys {}
   set epoch {}
   set parallax 0
   set pm {}
   set rv 0
   set azel {}
   $this configure -wavelength_name {}
   set wavelength_value {}
   $this configure -trackrate {}
}

itcl::body Target::preview vt {

   if { [string equal $cosys ""] } {
      set system FK5
      set equinox J2000
   } else {
      set system [CosysNames::$cosys cget -frame]
      set equinox [CosysNames::$cosys cget -equinox]
   }
   switch $type {
      radec {
         tccPreview set $vt $system [lindex $radec 0] [lindex $radec 1] \
               $equinox $epoch
      }
      azel {
         tccPreview set $vt AZEL [lindex $azel 0] [lindex $azel 1]
      }
   }
      
   if { [string equal $wavelength_name ""] } {
      if { ! [string equal $wavelength_value ""] } {
         $Wavelength configure -wavel $wavelength_value
         $Wavelength preview $vt
      }
   } else {
      ::WavelengthNames::$wavelength_name preview $vt
   }
   if { ! [string equal $trackrate ""] } {
      ::TrackRateNames::$trackrate preview $vt
   }
}

itcl::body Target::save file {
   puts $file "   -objName \"$objName\" \\"
   puts $file "   -cosys \"$cosys\" \\"
   puts $file "   -radec \"$radec\" \\"
   puts $file "   -epoch \"$epoch\" \\"
   puts $file "   -parallax \"$parallax\" \\"
   puts $file "   -pm \"$pm\" \\"
   puts $file "   -rv \"$rv\" \\"
   puts $file "   -azel \"$azel\" \\"
   puts $file "   -wavelength_name \"$wavelength_name\" \\"
   puts $file "   -wavelength_value \"$wavelength_value\" \\"
   puts $file "   -trackrate \"$trackrate\""
}

body Target::grab vt {

# Clear current state.
   init

# Get the target position.
   switch $vt {
      sourceA {set target [sa tcssad get targetA]}
      sourceB {set target [sa tcssad get targetB]}
      sourceC {set target [sa tcssad get targetC]}
      pwfs1 {set target [sa tcssad get targetPwfs1]}
      pwfs2 {set target [sa tcssad get targetPwfs2]}
      oiwfs {set target [sa tcssad get targetOiwfs]}
      mount {set target [sa tcssad get targetMount]}
   }

# Get the wavelength.
   set wavelength_name ""
   set wavelength_value [expr [sadVal tcssad ${vt}Wavelength 5000.0] / 10000.0]

# And frame.
   set frame [sa tcssad get ${vt}TrackFrame]
   if { [string is space $frame] } {
      set frame FK5
   }
   set eqx [formatEpoch $frame [sa tcssad get ${vt}TrackEq]]
   createCosys ${frame}/$eqx -frame $frame -equinox $eqx
   set cosys ${frame}/$eqx

# Store the RA/Dec.
   set type radec
   set ra [slaDr2tf 3 [lindex $target 0]]
   set dec [slaDr2af 2 [lindex $target 1]]
   set radec [list \
         [format "%02d:%02d:%02d.%03d" [lindex $ra 1] [lindex $ra 2] \
         [lindex $ra 3] [lindex $ra 4]] \
         [format "%s%02d:%02d:%02d.%02d" [lindex $dec 0] [lindex $dec 1] \
         [lindex $dec 2] [lindex $dec 3] [lindex $dec 4]]]

}

itcl::configbody Target::cosys {
   if { ! [string equal $current_cosys ""] } {
      CosysNames::$current_cosys refdec
   }
   set current_cosys ""
   if { ! [string equal $cosys ""] } {
      if { [catch {CosysNames::$cosys refinc}] } {
         error "Coordinate frame \"$cosys\" does not exist"
      } else {
         set current_cosys $cosys
      }
   }
}

itcl::configbody Target::wavelength_name {
   if { ! [string equal $current_wavelength_name ""] } {
      WavelengthNames::$current_wavelength_name refdec
   }
   set current_wavelength_name ""
   if { ! [string equal $wavelength_name ""] } {
      if { [catch {WavelengthNames::$wavelength_name refinc}] } {
         error "Wavelength \"$wavelength_name\" does not exist"
      } else {
         set current_wavelength_name $wavelength_name
      }
   }
}

itcl::configbody Target::trackrate {
   if { ! [string equal $current_trackrate ""] } {
      TrackRateNames::$current_trackrate refdec
   }
   set current_trackrate ""
   if { ! [string equal $trackrate ""] } {
      if { [catch {TrackRateNames::$trackrate refinc}] } {
         error "Differential track rate \"$trackrate\" does not exist"
      } else {
         set current_trackrate $trackrate
      }
   }
}

itcl::body Target::copy createproc {
   $createproc [namespace tail $this] \
      -objName $objName \
      -cosys $cosys \
      -radec $radec \
      -epoch $epoch \
      -parallax $parallax \
      -pm $pm \
      -rv $rv \
      -azel $azel \
      -wavelength_name $wavelength_name \
      -wavelength_value $wavelength_value \
      -trackrate $trackrate
}
