#+
#  Target <- Paramset
#
#  Implements the Target class. A Target object stores all
#  the parameters needed to specify a target.
#
#  Options:
#
#           -brightness    The object brightness (can be any character string
#                          as the tcc doesn't do anyting with it except 
#                          display it.)
#
#           -objname       The object name
#
#           -type          The type of the coordinate (hmsdegTarget, 
#                          degdegTarget namedTarget or conicTarget).
#
#           The following options apply when -type is hmsdegTarget.
#
#              -cosys         The target coordinate system.
#
#              -epoch         The epoch of the position.
#
#              -parallax      The parallax.
#
#              -c1            Right ascension.
#
#              -c1            Declination.
#
#              -pmunits       The units of the proper motions.
#
#              -pm1           Proper motion in ra.
#
#              -pm2           Proper motion in dec.
#
#              -rv            Radial velocity.
#
#           The following options apply when -type is degdegTarget.
#
#              -c1            Azimuth.
#
#              -c2            Elevation.
#
#           The following options apply when -type is namedTarget.
#
#              -planet        The planet name.
#
#           The following options apply when -type is conicTarget.
#
#              -format        The element format
#
#              -epochofel     Epoch of elements.
#
#              -orbinc        Orbital inclination.
#
#              -longascnode   Longitude of ascending node.
#
#              -longofperi    Longitude of perihelion.
#
#              -argofperi     Argument of perihelion.
#
#              -meandist      Mean distance.
#
#              -peridist      Perihelion distance.
#
#              -eccentricity  Orbital eccentricity.
#
#              -meanlong      Mean longitude.
#
#              -meananom      Mean anomaly.
#
#              -epochofperi   Epoch of perihelion.
#
#              -dailymot      Daily motion.
#
#  Methods:
#           apply comp    Applies the target definition to the TCS by 
#                         setting the values of the command parameters
#                         for appropriate virtual telescope.
#
#           grab comp     Grabs the current tracking position of the
#                         appropriate virtual telescope.
#
#           init          Returns the rotator object to its initial state.
#
#           preview item  Sets the preview target for "item".
#
#           save node     Saves the values of the target options to the
#                         xml node.
#
#  D Terrett 11 July 2002
#
#  Copyright CCLRC
#+

itcl::class Target {
   inherit Paramset
   destructor {$this init}
   public {
      method apply {comp}
      method grab {comp}
      method init {}
      method preview {vt}
      method save {node}
      variable type {}
      variable objname {}
      variable brightness {}
      variable cosys {}
      variable epoch {}
      variable parallax {}
      variable pmunits {}
      variable pm1 {}
      variable pm2 {}
      variable rv {}
# Synonym for cosys
      variable system {}
      variable c1 {}
      variable c2 {}
      variable planet {}
      variable format {}
      variable epochofel {}
      variable orbinc {}
      variable longascnode {}
      variable longofperi {}
      variable argofperi {}
      variable meandist {}
      variable peridist {}
      variable eccentricity {}
      variable meanlong {}
      variable meananom {}
      variable epochofperi {}
      variable dailymot {}
      variable trackrate {}
      variable trackratens
   }
   private {
      method pmconvert {c1 c2 pm1 pm2 pmunits}
      variable current_cosys {}
      variable current_trackrate {}
   }
}

itcl::body Target::apply {comp} {

   switch $comp {
      tcs.field.sciencetarget {
         set vt sourceA
      }
      tcs.field.pwfs1target {
         set vt pwfs1
      }
      tcs.field.pwfs2target {
         set vt pwfs2
      }
      tcs.field.oiwfstarget {
         set vt oiwfs
      }
   }

   switch $type {
      hmsdegTarget {
         cs $vt set objName [list $objname]
         if { [string equal $cosys ""] } {
            cs $vt set system FK5
            cs $vt set equinox J2000
         } else {
            CosysNames::$cosys apply $comp.cosys
         }
         cs $vt set theta1 [list $c1]
         cs $vt set theta2 [list $c2]
         cs $vt set epoch [list $epoch]
         cs $vt set parallax [list $parallax]
         if { [catch {set pm [pmconvert $c1 $c2 $pm1 $pm2 $pmunits]} ] } {
            error "Unable to convert proper motions to sec & arcsec/year"
         }
         cs $vt set dtheta1 [list [lindex $pm 0]]
         cs $vt set dtheta2 [list [lindex $pm 1]]
         cs $vt set rv [list $rv]
         logger command $vt
      }
      degdegTarget {
         cs $vt set objName [list $objname]
         cs $vt set system AZEL_TOPO
         cs $vt set equinox ""
         cs $vt set theta1 [list $c1]
         cs $vt set theta2 [list $c2]
         cs $vt set epoch ""
         cs $vt set parallax ""
         cs $vt set dtheta1 ""
         cs $vt set dtheta2 ""
         cs $vt set rv ""
         logger command $vt
      }
      namedTarget {
         if { [string equal $vt sourceA] } {
            cs planet set object $planet
            logger command planet
         }
      }
      conicTarget {
         if { [string equal $vt sourceA] } {
            cs orbit set objName [list $objname]
            switch $format {
               "AsA major planet" {
                  cs orbit set eltype 1
                  cs orbit set epoch [list $epochofel]
                  cs orbit set inclination [list $orbinc]
                  cs orbit set anode [list $longascnode]
                  cs orbit set perihelion [list $longofperi]
                  cs orbit set aorq [list $meandist]
                  cs orbit set LorM [list $meanlong]
                  cs orbit set e [list $eccentricity]
                  cs orbit set n [list $dailymot]
               }
               "JPL major planet" {
                  if { ! [string is double -strict $longascnode] } {
                     error "expecting floating point number but got
                           \"$longascnode\""
                  }
                  if { ! [string is double -strict $argofperi] } {
                     error "expecting floating point number but got
                           \"$argofperi\""
                  }
                  if { ! [string is double -strict $meananom] ) } {
                     error "expecting floating point number but got
                           \"$longascnode\""
                  }
                  cs orbit set eltype 1
                  cs orbit set epoch [list $epochofel]
                  cs orbit set inclination [list $orbinc]
                  cs orbit set anode [list $longascnode]
                  cs orbit set perihelion [expr { $longascnode + $argofperi }]
                  cs orbit set aorq [list $meandist]
                  cs orbit set LorM \
                        [expr { $longascnode + $argofperi + $meananom }]
                  cs orbit set e [list $eccentricity]
                  cs orbit set n [list $dailymot]
               }
               "AsA minor planet" -
               "MPC minor planet" {
                  foreach {epoch1 inclination1 anode1 perihelion1 a1 e1 M1} \
                        [slaPertel 2 $epochofel $epochofel $orbinc \
                              $longascnode $argofperi $meandist $eccentricity \
                              $meananom] {}
                  cs orbit set eltype 2
                  cs orbit set epoch $epoch1
                  cs orbit set inclination $inclination1
                  cs orbit set anode $anode1
                  cs orbit set perihelion $perihelion1
                  cs orbit set aorq $a1
                  cs orbit set LorM $M1
                  cs orbit set e $e1
                  cs orbit set n ""
               }
               "AsA comet" -
               "JPL minor body" -
               "MPC comet" {
                  foreach {epoch1 inclination1 anode1 perihelion1 q1 e1} \
                        [slaPertel 3 $epochofel $epochofperi $orbinc \
                              $longascnode $argofperi $peridist \
                              $eccentricity] {}
                  cs orbit set eltype 3
                  cs orbit set epoch $epoch1
                  cs orbit set inclination $inclination1
                  cs orbit set anode $anode1
                  cs orbit set perihelion $perihelion1
                  cs orbit set aorq $q1
                  cs orbit set e $e1
                  cs orbit set LorM ""
                  cs orbit set n ""
               }
            }
            logger command orbit
         }
      }
   }
   if { ! [string equal $trackrate ""] } {
      ${trackratens}::$trackrate apply $comp.trackrate
   }
}

itcl::body Target::init {} {

   set type {}
   set objname {}
   $this configure -cosys {}
   set epoch {}
   set parallax 0
   set pm1 {}
   set pm2 {}
   set rv 0
   set c1 {}
   set c2 {}
   $this configure -trackrate {}
   set planet {}
   set format {}
   set epochofel {}
   set orbinc {}
   set longascnode {}
   set perihlion {}
   set meandist {}
   set peridist {}
   set eccentricity {}
   set meanlong {}
   set meananom {}
   set epochofperi {}
   set dailymot {}
   set brightness {}
}

itcl::body Target::preview vt {
   if { [string equal $cosys ""] } {
      set system FK5
      set equinox J2000
   } else {
      set system [CosysNames::$cosys cget -frame]
      set equinox [CosysNames::$cosys cget -equinox]
   }
   switch $type {
      hmsdegTarget {
         tccPreview set $vt $system $c1 $c2 $equinox $epoch
      }
      degdegTarget {
         tccPreview set $vt AZEL $c1 $c2
      }
      namedTarget {
         if { [string equal $vt sourceA] } {
            tccPreview set planet $planet
         }
      }
      conicTarget {
         if { [string equal $vt sourceA] } {
            switch $format {
               "AsA major planet" {
                  tccPreview set orbit 1 $epochofel $orbinc $longascnode \
                        $longofperi $meandist $eccentricity $meanlong $dailymot
               }
               "JPL major planet" {
                  if { ! [string is double -strict $longascnode] } {
                     error "expecting floating point number but got
                           \"$longascnode\""
                  }
                  if { ! [string is double -strict $argofperi] } {
                     error "expecting floating point number but got
                           \"$argofperi\""
                  }
                  if { ! [string is double -strict $meananom] ) } {
                     error "expecting floating point number but got
                           \"$longascnode\""
                  }
                  tccPreview set orbit 1 $epochofel $orbinc $longascnode \
                        [expr { $longascnode + $argofperi }] $meandist \
                        $eccentricity  \
                        [expr { $longascnode + $argofperi + $meananom }] \
                        $dailymot
               }
               "AsA minor planet" -
               "MPC minor planet" {
                  foreach {epoch1 inclination1 anode1 perihelion1 a1 e1 M1} \
                        [slaPertel 2 $epochofel $epochofel $orbinc \
                              $longascnode $argofperi $meandist $eccentricity \
                              $meananom] {}
                  tccPreview set orbit 2 $epoch1 $inclination1 $anode1 \
                        $perihelion1 $a1 $e1 $M1
               }
               "AsA comet" -
               "JPL minor body" -
               "MPC comet" {
                  foreach {epoch1 inclination1 anode1 perihelion1 q1 e1} \
                        [slaPertel 3 $epochofel $epochofperi $orbinc \
                              $longascnode $argofperi $peridist \
                              $eccentricity] {}
                  tccPreview set orbit 3 $epoch1 $inclination1 $anode1 \
                        $perihelion1 $q1 $e1
               }
            }
         }
      }
   }
      
   if { ! [string equal $trackrate ""] } {
      ${trackratens}::$trackrate preview $vt
   }
}

itcl::body Target::save {node} {
   switch $type {
      hmsdegTarget {
          set node [paramset $node hmsdegTarget]
          param $node cosys $cosys
          param $node c1 $c1
          param $node c2 $c2
          set node1 [paramset $node properMotion]
          param $node1 epoch $epoch
          param $node1 parallax $parallax
          param $node1 pm1 $pm1
          param $node1 pm2 $pm2
          param $node1 rv $rv
          if { ! [dom::node hasChildNodes $node1] } {
             dom::node removeChild $node $node1
          }
          param $node trackrate $trackrate
      }
      degdegTarget {
         set node [paramset $node degdegTarget]
         param $node c1 $c1
         param $node c2 $c2
      }
      namedTarget {
         set node [paramset $node namedTarget]
         param $node planet $planet
      }
      conicTarget {
         set node [paramset $node conicTarget]
         switch $format {
            "AsA major planet" -
            "MPC major planet" {
               param $node format $format
               param $node epochofel $epochofel
               param $node orbinc $orbinc
               param $node longascnode $longascnode
               param $node longofperi $longofperi
               param $node meandist $meandist
               param $node eccentricity $eccentricity
               param $node meanlong $meanlong
               param $node dailymot $dailymot
            }
            "JPL major planet" {
               param $node format $format
               param $node epochofel $epochofel
               param $node orbinc $orbinc
               param $node longascnode $longascnode
               param $node argofperi $argofperi
               param $node meandist $meandist
               param $node eccentricity $eccentricity
               param $node meananom $meananom
               param $node dailymot $dailymot
            }
            "AsA minor planet" -
            "MPC minor planet" {
               param $node format $format
               param $node epochofel $epochofel
               param $node orbinc $orbinc
               param $node longascnode $longascnode
               param $node argofperi $argofperi
               param $node meandist $meandist
               param $node eccentricity $eccentricity
               param $node meananom $meananom
            }
            "AsA comet" -
            "JPL minor body" -
            "MPC comet" {
               param $node format $format
               param $node epochofel $epochofel
               param $node orbinc $orbinc
               param $node longascnode $longascnode
               param $node peridist $peridist
               param $node argofperi $argofperi
               param $node eccentricity $eccentricity
               param $node epochofperi $epochofperi
            }
         }
      }
   }
   param $node objname $objname
   param $node brightness $brightness
}

itcl::body Target::grab {comp} {

# Determine name of the virtual telescope.
   switch $comp {
      tcs.field.sciencetarget {
         set vt sourceA
      }
      tcs.field.pwfs1target {
         set vt pwfs1
      }
      tcs.field.pwfs2target {
         set vt pwfs2
      }
      tcs.field.oiwfstarget {
         set vt oiwfs
      }
   }


# Clear current state.
   init

# Get the target position.
   switch $vt {
      sourceA {set target [sa tcssad get targetA]}
      sourceB {set target [sa tcssad get targetB]}
      sourceC {set target [sa tcssad get targetC]}
      pwfs1 {set target [sa tcssad get targetPwfs1]}
      pwfs2 {set target [sa tcssad get targetPwfs2]}
      oiwfs {set target [sa tcssad get targetOiwfs]}
      mount {set target [sa tcssad get targetMount]}
   }

# Get frame.
   set frame [sa tcssad get ${vt}TrackFrame]
   if { [string is space $frame] } {
      set frame FK5
   }

# Set coordinate system.
   if { $frame == "FK5" || $frame == "FK4" } {
      set eqx [formatEpoch $frame [sa tcssad get ${vt}TrackEq]]
      createCosys ${frame}/$eqx -frame $frame -equinox $eqx
      set cosys ${frame}/$eqx
   } elseif { $frame == "APPT" } {
      set cosys Apparent
   } else {
      set cosys AzEl
   }
    
      
   if { $frame == "AZEL_TOPO" } {
      set type degdegTarget
      set az [slaDr2af 2 [lindex $target 0]]
      set el [slaDr2af 2 [lindex $target 1]]
      set c1 [list \
            [format "%02d:%02d:%02d.%03d" [lindex $az 1] [lindex $az 2] \
            [lindex $az 3] [lindex $az 4]]]
      set c2 [list \
            [format "%s%02d:%02d:%02d.%02d" [lindex $el 0] [lindex $el 1] \
            [lindex $el 2] [lindex $el 3] [lindex $el 4]]]
   } else {
      set type hmsdegTarget
      set ra [slaDr2tf 3 [lindex $target 0]]
      set dec [slaDr2af 2 [lindex $target 1]]
      set c1 [list \
            [format "%02d:%02d:%02d.%03d" [lindex $ra 1] [lindex $ra 2] \
            [lindex $ra 3] [lindex $ra 4]]]
      set c2 [list\
            [format "%s%02d:%02d:%02d.%02d" [lindex $dec 0] [lindex $dec 1] \
            [lindex $dec 2] [lindex $dec 3] [lindex $dec 4]]]
   }
   set epoch ""
   set pmunits ""
   set pm1 ""
   set pm2 ""
   set rv ""
   set parallax ""
   set trackrate ""
}

itcl::configbody Target::cosys {
   if { ! [string equal $current_cosys ""] } {
      CosysNames::$current_cosys refdec
   }
   set current_cosys ""
   if { ! [string equal $cosys ""] } {
      if { [catch {CosysNames::$cosys refinc}] } {
         error "Coordinate frame \"$cosys\" does not exist"
      } else {
         set current_cosys $cosys
      }
   }
}

itcl::configbody Target::trackrate {
   if { ! [string equal $current_trackrate ""] } {
      ${trackratens}::$current_trackrate refdec
   }
   set current_trackrate ""
   if { ! [string equal $trackrate ""] } {
      if { [catch {${trackratens}::$trackrate refinc}] } {
         error "Differential track rate \"$trackrate\" does not exist"
      } else {
         set current_trackrate $trackrate
      }
   }
}

itcl::configbody Target::pm1 {
   if { ! [string is double $pm1 ] } {
      error "Proper motion not a number"
   }
}

itcl::configbody Target::pm2 {
   if { ! [string is double $pm2 ] } {
     error "Proper motion not a number"
   }
}

itcl::configbody Target::pmunits {
   if { [lsearch -exact [list mas/year mas/century arcsec/year arcsec/century \
         "sec-arcsec/year" "sec-arcsec/century" ""] $pmunits] == -1 } {
      error "invalid proper motion units"
   }
}

# The system config body sets the cosys option, creating the cosys component
# if there isn't one that matches the system definition.
itcl::configbody Target::system {

# Do nothing if system is empty.
   if { ! [string is space $system] } {

# Construct the cosys component name.
      set system [string trim $system]
      switch $system {
         apparent {
            set cosysname Apparent
         }
         polarMount {
            set cosysname AzEl
         }
         default {
            switch [string index $system 0] {
               j -
               J {
                  set cosysname FK5/${system}
               }
               b -
               B {
                  set cosysname FK4/${system}
               }
               default {
                  if { [string is double $system] } {
                     if { $system > 1984.0 } {
                        set cosysname FK5/${system}
                     } else {
                        set cosysname FK4/${system}
                     }
                  } else {
                     error "\"$system\" is not a valid coordinate system"
                  }
               }
            }
         }
      }
   
# See if it already exists.
      if { [lsearch -exact [itcl::find objects -class CosysComponent] \
            ::CosysNames::$cosysname] < 0 } {

# Create it.
         switch $cosysname {
            Apparent {
               CosysComponent ::CosysNames::Apparent -frame Appt
            }
            AzEl {
               CosysComponent ::CosysNames::AzEl -frame AzEl
            }
            default {
               foreach {frame equinox} [split $cosysname /] {}
               CosysComponent ::CosysNames::$cosysname ::CosysList \
                     -frame $frame -equinox $equinox
            }
         }
      }
   
# Set the cosys option.
      $this configure -cosys $cosysname
   }
}

itcl::configbody Target::type {
   if { [lsearch -exact {hmsdegTarget degdegTarget conicTarget namedTarget} \
        $type] == -1 } {
      error "\"$type\" is not a recognised target type"
   }
}

itcl::body Target::pmconvert {c1 c2 pm1 pm2 pmunits} {

# Returns the proper motions in seconds and arcsec per year (the units used 
# by the TCS).

# If both strings are blank then don't bother.
   if { [string is space $pm1] && [string is space $pm2] } {
      return [list "" ""]
   } else {

# Convert to per year.
      switch $pmunits {
         arcsec/century -
         mas/century -
         sec-arcsec/century {
            if { [string is double -strict $pm1] } {
               set pm1 [expr {$pm1 / 100.0}]
            }
            if { [string is double -strict $pm2] } {
               set pm2 [expr {$pm2 / 100.0}]
            }
         }
      }
   
   # Convert mas to arcsec.
      switch $pmunits {
         mas/year -
         mas/century {
            if { [string is double -strict $pm1] } {
               set pm1 [expr {$pm1 / 1000.0}]
            }
            if { [string is double -strict $pm2] } {
               set pm2 [expr {$pm2 / 1000.0}]
            }
         }
      }

# Convert arcsec to seconds of RA.
      switch $pmunits {
         mas/year -
         mas/century -
         arcsec/year -
         arcsec/century {
            set AS2R 0.0000048481368111
            set raz [expr {[slaDafin $c1] * 15.0}]
            set decz [slaDafin $c2]
            set radec [slaDtp2s [expr {$pm1* $AS2R}] [expr {$pm2 * $AS2R}] \
                  $raz $decz]
            set pm1 [expr { ([lindex $radec 0] - $raz) / $AS2R / 15.0 }]
            set pm2 [expr { ([lindex $radec 1] - $decz) / $AS2R }]
         }
      }
      return [list $pm1 $pm2]
   }
}
