#+
#  Target
#
#  Implements the Target class. A Target object stores all
#  the parameters needed to specify a target.
#
#  Options:
#           -objName       The object name
#
#           -type          The type of the coordinate (radec, or azel).
#
#           -wavelength_name
#
#           -wavelength_value
#
#           The following options apply when -type is radec.
#
#              -cosys         The target coordinate system.
#
#              -epoch         The epoch of the position.
#
#              -parallax      The parallax.
#
#              -radec         Right ascension and declination.
#
#              -rv            Radial velocity.
#
#           The following options apply when -type is radec.
#
#              -azel          Azimuth and elevation.
#
#  Methods:
#           apply vt      Applies the target definition to the TCS by 
#                         setting the values of the command parameters
#                         for virtual telescope "vt".
#
#           preview item  Sets the preview target for "item".
#
#           save file     Writes the values of the target options to the
#                         channel identifier "file".
#
#  Procs:
#           subcomponents Returns a list of the target classes subcomponents.
#
#  D Terrett 17 February 2000
#
#  Copyright CCLRC
#+

itcl::class Target {

   constructor args {}

   public proc subcomponents {}

   public method apply vt {}
   public method preview vt {}
   public method save file

   public variable type
   public variable objName {}

# Type "radec"
   public variable radec {} {if {$radec != ""} {set type radec}}
   public variable cosys {}
   public variable epoch {}
   public variable parallax 0
   public variable pm {}
   public variable rv 0

# Type "azel"
   public variable azel {} {if {$azel != ""} {set type azel}}

   public variable wavelength_name {}
   public variable wavelength_value {} {
      set wavelength_value [valWavelength $wavelength_value]
   }
   public variable trackrate {}

   protected common Wavelength ""
}

itcl::body Target::subcomponents {} {
   return { \
      {cosys Cosys CosysNames CosysList {Coordinate System} {}} \
      {wavelength Wavelength WavelengthNames WavelengthList {Wavelength} {}} \
      {trackrate TrackRate TrackRateNames TrackRateList {Differential Track Rate} {}} \
   }
}

itcl::body Target::constructor args {

# Create the scratch wavelength object if it doesn't already exist.
   if { [info commands $Wavelength] == "" } {
      set Wavelength [Wavelength #auto]
   }
   eval configure $args
}

itcl::body Target::apply vt {

   cs $vt set objName \"$objName\"
   switch $type {
      radec {
         if { $cosys == "" } {
            cs $vt set system FK5
            cs $vt set equinox J2000
         } else {
            CosysNames::$cosys apply $vt
         }
         cs $vt set theta1 \"[lindex $radec 0]\"
         cs $vt set theta2 \"[lindex $radec 1]\"
         cs $vt set epoch \"$epoch\"
         cs $vt set parallax \"$parallax\"
         if { $pm != "" } {
            cs $vt set dtheta1 \"[lindex $pm 0]\"
            cs $vt set dtheta2 \"[lindex $pm 1]\"
         } else {
            cs $vt set dtheta1 \"\"
            cs $vt set dtheta2 \"\"
         }
         cs $vt set rv \"$rv\"
      }
      azel {
         cs $vt set system \"AZEL_TOPO\"
         cs $vt set equinox \"\"
         cs $vt set theta1 \"[lindex $azel 0]\"
         cs $vt set theta2 \"[lindex $azel 1]\"
         cs $vt set epoch \"\"
         cs $vt set parallax \"\"
         cs $vt set dtheta1 \"\"
         cs $vt set dtheta2 \"\"
         cs $vt set rv \"\"
      }
   }
   if { $wavelength_name != "" } {
      if { [info commands ::WavelengthNames::$wavelength_name] != "" } {
         ::WavelengthNames::$wavelength_name apply $vt
      }
   } else {
      if { $wavelength_value != "" } {
         $Wavelength configure -wavel $wavelength_value
         $Wavelength apply $vt
      }
   }
   if { [info commands ::TrackRateNames::$trackrate] != "" } {
      ::TrackRateNames::$trackrate apply $vt
   }
}

itcl::body Target::preview vt {

   if { $cosys == "" } {
      set system FK5
      set equinox J2000
   } else {
      set system [CosysNames::$cosys cget -frame]
      set equinox [CosysNames::$cosys cget -equinox]
   }
   switch $type {
      radec {
         tccPreview set $vt $system [lindex $radec 0] [lindex $radec 1] \
               $equinox $epoch
      }
      azel {
         tccPreview set $vt AZEL [lindex $azel 0] [lindex $azel 1]
      }
   }
      
   if { $wavelength_name != "" } {
      if { [info commands ::WavelengthNames::$wavelength_name] != "" } {
         ::WavelengthNames::$wavelength_name preview $vt
      }
   } else {
      if { $wavelength_value != "" } {
         $Wavelength configure -wavel $wavelength_value
         $Wavelength preview $vt
      }
   }
   if { [info commands ::TrackRateNames::$trackrate] != "" } {
      ::TrackRateNames::$trackrate preview $vt
   }
}

itcl::body Target::save file {
   puts $file "   -objName \"$objName\" \\"
   puts $file "   -cosys \"$cosys\" \\"
   puts $file "   -radec \"$radec\" \\"
   puts $file "   -epoch \"$epoch\" \\"
   puts $file "   -parallax \"$parallax\" \\"
   puts $file "   -pm \"$pm\" \\"
   puts $file "   -rv \"$rv\" \\"
   puts $file "   -azel \"$azel\" \\"
   puts $file "   -wavelength_name \"$wavelength_name\" \\"
   puts $file "   -wavelength_value \"$wavelength_value\" \\"
   puts $file "   -trackrate \"$trackrate\""
}
