#+
#  TargetControl <- ComponentControl
#
#  A Target control is a ComponentControl widget with widgets for
#  the target position etc. It is intended to be inherited by widgets
#  for specific target types (science & wfs).
#
#  Options:
#           -shadow         The name of the control's edit shadow.
#
#           -vt             The virtual telescope that the coordinate system 
#                           applies to.
#
#  Methods:
#           selectobj name  Copies the contents of the Target object "name"
#                           into the edit controls.
#
#           updateobj name  Stores the contents of the edit controls in the
#                           Target object "name".
#
#  D Terrett 5 April 2000
#
#  Copyright CCLRC
#+

itcl::class TargetControl {
   inherit ComponentControl

   constructor args {}

   itk_option define -shadow shadow Shadow ""
   itk_option define -vt vt Vt ""

   public method selectobj name
   public method updateobj name
}

itk::usual TargetControl {
   keep -borderwidth -cursor -font -highlightthickness -insertborderwidth \
         -insertofftime -insertontime -insertwidth -labelfont -popupcursor \
         -selectborderwidth -textfont -title -vt
}

itcl::body TargetControl::constructor args {

   itk_component add frame {
      frame $itk_interior.frame -borderwidth 2 -relief ridge
   }
   pack $itk_component(frame) -fill x -expand y
   set w $itk_component(frame)

# Frame to highlight the position entry window.
   itk_component add highlight {
      frame $w.highlight
   } {
      usual
      ignore -background
   }
   pack $itk_component(highlight) -fill x -expand y
   set w $itk_component(highlight)

# Create tabnotebook for the target position.
   itk_component add notebook {
      iwidgets::tabnotebook $w.notebook -height 300 -width 450 
   }
   pack $itk_component(notebook)

# Page for RA/Dec
   set w [$itk_component(notebook) add -label "RA/Dec"]
   
# RA and Dec side by side.
   itk_component add radec {
      frame $w.radec
   }
   pack $itk_component(radec) -fill x -expand y
   set w $itk_component(radec)
   itk_component add ra {
      iwidgets::entryfield $w.ra -width 12 -labeltext RA:
   } {
      usual
      rename -textfont -majorfont majorFont Font
      rename -labelfont -majorfont majorFont Font
   }
   itk_component add dec {
      iwidgets::entryfield $w.dec -width 12 -labeltext Dec:
   } {
      usual
      rename -textfont -majorfont majorFont Font
      rename -labelfont -majorfont majorFont Font
   }
   pack $itk_component(ra) $itk_component(dec) -side left -expand y -pady 10
   set w [winfo parent $w]

# Frame for epoch and equinox.
   itk_component add epeq {
      frame $w.epeq
   }
   pack $itk_component(epeq) -padx 2 -pady 2 -anchor e
   set w $itk_component(epeq)

# Epoch.
   itk_component add epoch {
      iwidgets::entryfield $w.epoch -width 12 \
            -labeltext [lindex [cs sourceA info epoch] 2] \
            -labelpos nw
   }

#  Coordinate frame.
   itk_component add cosys {
      SubComponentSelector $w.cosys -labeltext "Coordinate system" \
            -labelpos nw -componentlist CosysList -component cosys
   }
   pack $itk_component(epoch) $itk_component(cosys) -side left -anchor n \
      -padx 3
   set w [winfo parent $w]

# Frame for space motions.
   itk_component add space {
      frame $w.space -bd 2 -relief sunken
   }
   pack $itk_component(space) -padx 2 -pady 2 -fill y
   set w $itk_component(space)

# Title for space motion frame.
   itk_component add smtitle {
      label $w.smtitle -text "Proper motion"
   }
   pack $itk_component(smtitle) -pady 3 -padx 3

# Frame for proper motions.
   itk_component add pm {
      frame $w.pm
   }
   pack $itk_component(pm) -pady 3
   set w $itk_component(pm)

# Proper motions.
   itk_component add dtheta1 {
      iwidgets::entryfield $w.dtheta1 -width 11 \
            -labeltext "RA (s/yr)"
   }
   itk_component add dtheta2 {
      iwidgets::entryfield $w.dtheta2 -width 11 \
            -labeltext "Dec (arcsec/yr)"
   }
   pack $itk_component(dtheta1) $itk_component(dtheta2) -side left -padx 3
   set w [winfo parent $w]

# Frame for parallax and radial velocity.
   itk_component add pv {
      frame $w.pv
   }
   pack $itk_component(pv) -pady 3
   set w $itk_component(pv)

# Parallax
   itk_component add parallax {
      iwidgets::entryfield $w.parallax -width 11 \
            -labeltext [lindex [cs sourceA info parallax] 2]
   }

# Radial velocity.
   itk_component add rv {
      iwidgets::entryfield $w.rv -width 11 \
            -labeltext [lindex [cs sourceA info rv] 2]
   }
   pack $itk_component(parallax) $itk_component(rv) -side left -padx 3

# Page for Az/El
   set w [$itk_component(notebook) add -label "Az/El"]
   
# Az and El.
   itk_component add az {
      iwidgets::entryfield $w.az -width 12 -labeltext Az:
   } {
      usual
      rename -textfont -majorfont majorFont Font
      rename -labelfont -majorfont majorFont Font
   }
   itk_component add el {
      iwidgets::entryfield $w.el -width 12 -labeltext El:
   } {
      usual
      rename -textfont -majorfont majorFont Font
      rename -labelfont -majorfont majorFont Font
   }
   pack $itk_component(az) $itk_component(el) -side left -expand y -pady 40 \
      -anchor n

# Control for selecting a differential track rate.
   set w $itk_component(frame)
   itk_component add trackrate {
      SubComponentSelector $w.trackrate -labeltext "Diff track rate" \
            -labelpos nw -componentlist TrackRateList -component trackrate
   }
   pack $itk_component(trackrate) -side left -anchor n -padx 5 -pady 5

# Control for setting the effective wavelength.
   itk_component add wavelength {
       WavelengthSelector $w.wavelength
   }
   pack $itk_component(wavelength) -side left -padx 5 -pady 1

# Select the RA/Dec page.
  $itk_component(notebook) select RA/Dec

# Add a menu button to the frame containing the selector.
   set w [winfo parent $itk_component(selector)]
   itk_component add copy {
      menubutton $w.copy -text "Copy to..." -relief raised
   }
   pack $itk_component(copy) -side right -pady 4 -padx 4
   itk_component add copymenu {
      menu $itk_component(copy).menu -tearoff 0
   } {
      usual
      ignore -tearoff
   }
   $itk_component(copy) configure -menu $itk_component(copymenu)

   eval itk_initialize $args
}

itcl::body TargetControl::selectobj name {

   $itk_component(ra) clear
   $itk_component(dec) clear
   $itk_component(epoch) clear
   $itk_component(dtheta1) clear
   $itk_component(dtheta2) clear
   $itk_component(parallax) clear
   $itk_component(rv) clear
   $itk_component(az) clear
   $itk_component(el) clear

   if { $name != "" } {
      switch [$name cget -type] {
         radec {
            $itk_component(notebook) select RA/Dec
            $itk_component(cosys) select [$name cget -cosys]
            set radec [$name cget -radec]
            $itk_component(ra) insert end [lindex $radec 0]
            $itk_component(dec) insert end [lindex $radec 1]
            $itk_component(epoch) insert end [$name cget -epoch]
            set pm [$name cget -pm]
            $itk_component(dtheta1) insert end [lindex $pm 0]
            $itk_component(dtheta2) insert end [lindex $pm 1]
            $itk_component(parallax) insert end [$name cget -parallax]
            $itk_component(rv) insert end [$name cget -rv]
         }
         azel {
            $itk_component(notebook) select Az/El
            set azel [$name cget -azel]
            $itk_component(az) insert end [lindex $azel 0]
            $itk_component(el) insert end [lindex $azel 1]
         }
      }
      set wavel [$name cget -wavelength_name]
      $itk_component(wavelength) select $wavel
      if { $wavel == "" } {
         set wavel [$name cget -wavelength_value]
         $itk_component(wavelength) value $wavel
      }
      $itk_component(trackrate) select [$name cget -trackrate]
   }
}

itcl::body TargetControl::updateobj name {
#+
# Updates a target object with the values currently entered in the
# control window.
#-
   set page [lindex [$itk_component(notebook) pageconfigure \
         [$itk_component(notebook) select select] -label] 4]
   switch $page {
      RA/Dec {
         $name configure \
               -objName [$itk_component(selector) get] \
               -cosys [$itk_component(cosys) get] \
               -radec [list [$itk_component(ra) get] \
               [$itk_component(dec) get]] \
               -epoch [$itk_component(epoch) get] \
               -pm "[$itk_component(dtheta1) get] \
               [$itk_component(dtheta2) get]" \
               -parallax [$itk_component(parallax) get] \
               -rv [$itk_component(rv) get] \
               -trackrate [$itk_component(trackrate) get]
      }
      Az/El {
         $name configure \
               -azel [list [$itk_component(az) get] \
               [$itk_component(el) get]] \
      }
   }

   set wavel [$itk_component(wavelength) get name]
   $name configure -wavelength_name $wavel
   if { $wavel == "" } {
      $name configure -wavelength_value [$itk_component(wavelength) get value]
   }
}

itcl::configbody TargetControl::shadow {
   $itk_component(cosys) configure -editcontrol \
            $itk_option(-shadow)cosys
   $itk_component(wavelength) configure -editcontrol \
            $itk_option(-shadow)wavelength
   $itk_component(trackrate) configure -editcontrol \
            $itk_option(-shadow)trackrate
   $itk_component(cosys) configure -shadow $itk_option(-shadow)
   $itk_component(wavelength) configure -shadow $itk_option(-shadow)
   $itk_component(trackrate) configure -shadow $itk_option(-shadow)
}

itcl::configbody TargetControl::vt {
   $itk_component(storeapply) configure \
         -logmessage "$itk_option(-vt) target"
}
