#+
#  TargetComponent.itcl
#
#  Implements the TargetComponent class. A TargetComponent object 
#  is a Target object that is stored in a configuration.
#
#  D Terrett 19 August 1999
#
#  Copyright CCLRC
#+

itcl::class TargetComponent {
   inherit Target Component

   constructor {list args} {
      Component::constructor $list
   } {
      eval configure $args
   }

   public method save file
}

itcl::body TargetComponent::save file {
   set objname [namespace tail $this]
   set namespace [namespace qualifiers $this]
   puts $file "catch {delete object \"${namespace}::$objname\"}"
   puts $file "TargetComponent \"${namespace}::$objname\"  $componentList \\"
   Target::save $file
}
