#+
#  TargetComponent <- Target, tcclib::Component
#
#  A TargetComponent object is a Target object that is stored in a 
#  configuration list.
#
#  Options:
#           none
#
#  Methods:
#           constructor list  Creates the Target object and puts it onto
#                           "list".
#
#  D Terrett 19 September 2001
#
#  Copyright CCLRC
#+

itcl::class TargetComponent {
   inherit tcclib::Component Target
   constructor {list args} {
      tcclib::Component::constructor $list
   } {
      eval configure $args
   }
}
