#+
#  TccToolbar <- itk::Widget
#
#  Implements the TccToolbar widget which is packed into . to make the
#  root window of the Gemini tcc.
#
#  Options:
#           none
#
#  Methods:
#           none
#
#  D Terrett 25 September 2000
#
#  Copyright CCLRC
#-

itcl::class TccToolbar {
   inherit itk::Widget

   constructor args {}

   private method export
   private method import
   private method save
}

itk::usual TccToolbar {
}

itcl::body TccToolbar::constructor args {

  itk_component add menubar {
      iwidgets::menubar $itk_interior.menubar -menubuttons {
         menubutton file -text File -menu {
            command export -label Export... -command \"[code $this export]\"
            command import -label Import... -command \"[code $this import]\"
            command layout -label "Save layout..." -command saveLayout
            command exit -label Exit -command exit
         }
      }
   } {}
   pack $itk_component(menubar) -fill x -expand y

# Create a border.
   itk_component add border {
      frame $itk_interior.border
   }
   pack $itk_component(border) -fill both -expand y -padx 6 -pady 6

# Divide the window into a frame at the top for the main buttons and
# a frame for the subsystem controls with a spacing frame in between.
   set w $itk_component(border)
   itk_component add main {
      frame $w.main
   }
   itk_component add space {
      frame $w.space -height 8
   }
   itk_component add subsys {
      frame $w.subsys -bd 2 -relief sunken
   }
   pack $itk_component(main) $itk_component(space) $itk_component(subsys)

# Pack the main control buttons into the top frame.
   set w $itk_component(main)
   itk_component add tc {
      PanelButton $w.tc -text "System Control" -panel tcsPanel
   }
   itk_component add config {
      PanelButton $w.config -text "Target Selection" -panel tcsconfig
   }
   itk_component add observe {
      PanelButton $w.observe -text "Acquisition & Guiding" -panel observePanel
   }
   itk_component add log {
      PanelButton $w.log -text "Command Log" -panel logPanel
   }
   itk_component add eng {
      button $w.eng -text "Engineering Screen" \
            -command "exec /gemini/tcs/tcs/data/tcs_dm.sh &"
   }
   global env
   if { [info exists env(TCC_TCSNAME)] } {
      switch $env(TCC_TCSNAME) {
         tc1 {
            $itk_component(eng) configure \
                  -command "exec /gemini/tcs/tcs/data/tc1_dm.sh &"
         }
         default {
            $itk_component(eng) configure -state disabled
         }
      }
   }
   pack $itk_component(tc) $itk_component(config) $itk_component(observe) \
         $itk_component(log) $itk_component(eng) -fill x -expand y

# Label the subsystems frame.
   set w $itk_component(subsys)
   itk_component add sslabel {
      label $w.sslabel -text "Subsystem Controls"
   }
   pack $itk_component(sslabel)

# Divide the rest of the window into 3 rows
   itk_component add row1 {
      frame $w.row1
   }
   itk_component add row2 {
      frame $w.row2
   }
   itk_component add row3 {
      frame $w.row3
   }
   pack $itk_component(row1) $itk_component(row2) $itk_component(row3) \
         -fill x -expand y

# Rotator, M1 and M2 buttons in the first row.
   set w $itk_component(row1)
   itk_component add cr {
      PanelButton $w.cr -text "Rotator" -panel crsPanel
   }
   itk_component add m1 {
      PanelButton $w.m1 -text "M1" -panel m1sPanel -state disabled
   }
   itk_component add m2 {
      PanelButton $w.m2 -text "M2" -panel m2sPanel -state disabled
   }
   pack $itk_component(cr) $itk_component(m1) $itk_component(m2) \
         -side left -expand y -fill x

# Enclosure and A&G in the next row.
   set w $itk_component(row2)
   itk_component add ec {
      PanelButton $w.ec -text "Enclosure" -panel ecsPanel
   }
   itk_component add ag {
      PanelButton $w.ag -text "A & G" -panel agsPanel -state disabled
   }
   pack $itk_component(ec) $itk_component(ag) -side left -expand y -fill x

# Mount and AO in the last row.
   set w $itk_component(row3)
   itk_component add mc {
      PanelButton $w.mc -text Mount -panel mcsPanel
   }
   itk_component add ao {
      PanelButton $w.ao -text "Active Optics" -panel aosPanel -state disabled
   }
   pack $itk_component(mc) $itk_component(ao) -side left -expand y -fill x

   eval itk_initialize $args
}

itcl::body TccToolbar::import {} {

# Save the current directory and cd to save file directory.
   global SAVE_FILE_DIR
   set pwd [pwd]
   catch {cd $SAVE_FILE_DIR}

# Create a dialog box for selecting the file and center it.
   set dialog [iwidgets::fileselectiondialog .fsd \
         -modality application -title "Import File Selection Dialog"]
   $dialog center

# Activate the dialog
   if { [$dialog activate] } {

# Open the file.
      set filename [$dialog get]
      if { [catch {set file [open $filename RDONLY]} msg] } {
         tk_messageBox -icon error -message $msg
      } else {
         loadDefFile $file
         close $file

# Update save file directory.
         set dir [file dirname $filename]
         if { [string compare [file pathtype $dir] relative] == 0 } {
            set SAVE_FILE_DIR [pwd]/$dir
         } else {
            set SAVE_FILE_DIR $dir
         }
      }
   }
   destroy $dialog

# Restore default directory
   cd $pwd
}

itcl::body TccToolbar::save {list namespace file} {
   set n [$list length]
   for { set i 0 } { $i < $n } { incr i } {
      set name [$list get $i]
      if { $name != "" } {
         ${namespace}::$name save $file
      }
   }
}

itcl::body TccToolbar::export {} {

# cd to save file directory.
   global SAVE_FILE_DIR
   set pwd [pwd]
   catch {cd $SAVE_FILE_DIR}

# Create dialog.
   set dialog [ExportDialog $itk_interior.exportDialog \
         -title "Export Definitions Dialog" -modality application \
         -master $itk_interior]

   $dialog center

   if { [$dialog activate] } {
      set filename [$dialog get]
      if { [file exists $filename] } {
         set ans [tk_messageBox -icon warning -parent $itk_interior \
             -type yesno -message \
             "file \"$filename\" already exist. Do you want to overwrite it?"] 
      } else {
         set ans yes
      }
      if {[string equal $ans yes]} {
         if { [catch {set file [open $filename {WRONLY CREAT TRUNC}]} msg]} {
            tk_messageBox -icon error -message $msg -parent $itk_interior
         } else {
            upvar #0 [[$dialog component trackframe] cget -variable] trackframevar
            if { $trackframevar } {
               save TrackFrameList TrackFrameNames $file
            }
            upvar #0 [[$dialog component wavelength] cget -variable] wavelvar
            if { $wavelvar } {
               save WavelengthList WavelengthNames $file
            }
            upvar #0 [[$dialog component pointorig] cget -variable] povar
            if { $povar } {
               save PointOrigList PointOrigNames $file
            }
            upvar #0 [[$dialog component trackrate] cget -variable] trvar
            if { $trvar } {
               save TrackRateList TrackRateNames $file
            }
            upvar #0 [[$dialog component sciencetarget] cget -variable] scitargvar
            if { $scitargvar } {
               save ScienceTargetList ScienceTargetNames $file
            }
            upvar #0 [[$dialog component wfstarget] cget -variable] wfstargvar
            if { $wfstargvar } {
               save WfsTargetList WfsTargetNames $file
            }
            upvar #0 [[$dialog component rotator] cget -variable] rotvar
            if { $rotvar } {
               save RotatorList RotatorNames $file
            }
            upvar #0 [[$dialog component chop] cget -variable] chopvar
            if { $chopvar } {
               save ChopList ChopNames $file
            }
            upvar #0 [[$dialog component slewoptions] cget -variable] slewvar
            if { $slewvar } {
               save SlewOptionsList SlewOptionsNames $file
            }
            upvar #0 [[$dialog component instrument] cget -variable] instrumentvar
            if { $instrumentvar } {
               save InstrumentList InstrumentNames $file
            }
            upvar #0 [[$dialog component guide] cget -variable] guidevar
            if { $guidevar } {
               save GuideList GuideNames $file
            }
            upvar #0 [[$dialog component config] cget -variable] configsvar
            if { $configsvar } {
               save TcsConfigList TcsConfigNames $file
            }
            close $file

# Update save file directory.
            set dir [file dirname $filename]
            if { [string compare [file pathtype $dir] relative] == 0 } {
               set SAVE_FILE_DIR [pwd]/$dir
            } else {
               set SAVE_FILE_DIR $dir
            }
         }
      }
   }
   destroy $dialog

# Restore default directory
   cd $pwd
}
