#+
#  TcsConfigControl <- ComponentControl
#
#  Implements the TcsConfigControl widget.
#
#  D Terrett 3 June 2003
#
#  Copyright CCLRC
#+

itcl::class TcsConfigControl {
   inherit ComponentControl
   constructor {args} {}
   destructor {}
   public {
      method load {name}
      method preview {}
      method save {name}
   }
   private {
      method apply {}
      method newfield {n1 n2 op}
      method sesidle {}
      method wrap {par}
      variable components {
         field pointOrig slewOptions chop gaos trackFrame instrument
      }
      variable options {
         -field -pointOrig -slewOptions -chop -gaos -trackFrame -instrument
      }
      variable fieldcomponents {
         field.guide field.rotator field.wavelength field.sciencetarget field.pwfs1target field.pwfs2target field.oiwfstarget field.aowfstarget
      }
      variable fieldoptions {
         -guide -rotator -wavelength -sciencetarget -pwfs1target -pwfs2target -oiwfstarget -aowfstarget
      }
      variable view ""
   }
}

itk::usual TcsConfigControl {
   keep -borderwidth -cursor -font -highlightthickness -insertborderwidth \
         -insertofftime -insertontime -insertwidth -labelfont -popupcursor \
         -selectborderwidth -textfont -title -component
}

itcl::body TcsConfigControl::constructor {args} {

   if { [catch {cs aoGimOffsets info}] } {
      epics cs aoGimOffsets
   }

# Expand the component selector.
   $itk_component(selector) configure -width 43

# Divide the window into 4 vertically.
   itk_component add row1 {
      frame $itk_interior.row1 -relief ridge -bd 2
   }
   itk_component add row2 {
      iwidgets::labeledframe $itk_interior.row2 -relief ridge \
            -labeltext "Session Control" -labelpos nw
   }
   itk_component add row3 {
      iwidgets::labeledframe $itk_interior.row3 -relief ridge \
            -labeltext "Wrap Control" -labelpos nw
   }
   itk_component add row4 {
      frame $itk_interior.row4
   }
   pack $itk_component(row1) $itk_component(row2) $itk_component(row3) \
         $itk_component(row4) -expand y -fill x

# Configuration component selectors.
   set w $itk_component(row1)
   itk_component add field {
      ComponentSelector $w.field -labeltext "Target Field" \
            -component tcs.field \
            -active 1 
   } {
      usual
      rename -textfont -majorfont majorFont Font
      rename -labelfont -majorfont majorFont Font
   }
   itk_component add pointOrig {
      ComponentSelector $w.pointOrig -labeltext "Instrument Origin" \
            -component tcs.pointorig \
            -active 1 
   } {
      usual
      rename -textfont -majorfont majorFont Font
      rename -labelfont -majorfont majorFont Font
   }
   itk_component add chop {
      ComponentSelector $w.chop -labeltext "Chop Configuration" \
            -component tcs.chop \
            -active 1 
   } {
      usual
      rename -textfont -majorfont majorFont Font
      rename -labelfont -majorfont majorFont Font
   }
   itk_component add gaos {
      ComponentSelector $w.gaos -labeltext "Adaptive Optics" \
            -component tcs.gaos \
            -active 1 
   } {
      usual
      rename -textfont -majorfont majorFont Font
      rename -labelfont -majorfont majorFont Font
   }
   itk_component add slewOptions {
      ComponentSelector $w.slewOptions -labeltext "Slew Options" \
            -component tcs.slewoptions \
            -active 1 
   } {
      usual
      rename -textfont -majorfont majorFont Font
      rename -labelfont -majorfont majorFont Font
   }
   itk_component add trackFrame {
      ComponentSelector $w.trackFrame -labeltext "Tracking Frames" \
            -component tcs.trackframe \
            -active 1 
   } {
      usual
      rename -textfont -majorfont majorFont Font
      rename -labelfont -majorfont majorFont Font
   }
   itk_component add instrument {
      ComponentSelector $w.instrument -labeltext "Instrument" \
            -component tcs.instrument \
            -active 1 
   } {
      usual
      rename -textfont -majorfont majorFont Font
      rename -labelfont -majorfont majorFont Font
   }

   pack $itk_component(field) $itk_component(pointOrig) \
         $itk_component(chop) $itk_component(gaos) \
         $itk_component(slewOptions) $itk_component(instrument) -fill x -pady 1

# Session control
   set w [$itk_component(row2) childsite]
   itk_component add idle {
      button $w.idle -text "Set Idle reason" \
            -command [itcl::code $this sesidle]
   }
   itk_component add obsidf {
      frame $w.obsidf
   }
   set w $itk_component(obsidf)
   itk_component add obsidlab {
      label $w.obsidlab -text "Observation id:"
   }
   itk_component add obsid {
      label $w.obsid -width 40 -relief sunken -anchor w
   }
   pack $itk_component(obsidlab) $itk_component(obsid) -side left
   pack $itk_component(obsidf) $itk_component(idle) -side left -pady 3 -padx 2

# Wrap control
   set w [$itk_component(row3) childsite]
   itk_component add azwrap {
      iwidgets::optionmenu $w.azwrap -labeltext Azimuth
   }
   $itk_component(azwrap) insert end + "" -
   itk_component add rotwrap {
      iwidgets::optionmenu $w.rotwrap -labeltext Rotator
   }
   $itk_component(rotwrap) insert end + "" -
   itk_component add wrapapply {
      ApplyButton $w.wrapapply -command wrap -text Apply \
            -parcommand [itcl::code $this wrap]
   }

   pack $itk_component(wrapapply) $itk_component(rotwrap) \
      $itk_component(azwrap) -side right -pady 3 -padx 20

# Trace changes in the selected field.
   trace variable ::Config(tcs.field,value) w [itcl::code $this newfield]

# Replace the apply button with Slew/Set and Preview buttons.
   destroy $itk_component(store) $itk_component(aframe)

   set w $itk_component(row4)
   itk_component add setslew {
      LiveButton $w.setslew -text "Set/Slew" \
            -command [itcl::code $this apply] -width 8
   }
   itk_component add store {
      StoreButton $itk_interior.store -text Store -width 6 \
             -command [itcl::code $this store] \
             -combobox $itk_component(selector)
   }
   itk_component add preview {
      button $w.preview -text Preview \
            -command [itcl::code $this preview] -width 8
   }
   pack $itk_component(setslew) $itk_component(store) $itk_component(preview) \
         -side left -expand y -pady 4 -in $itk_component(row4)

# Set the object description.
   set description configuration

   eval itk_initialize $args
}

itcl::body TcsConfigControl::destructor {} {
   trace vdelete ::Config(tcs.field,value) w [itcl::code $this newfield]
}

itcl::body TcsConfigControl::apply {} {
#+
# Called when the apply button is pressed.
#-
# First check to make sure that the laser isn't propogating!
    if {[string equal [sa aossad get laserProp] "SKY"]} {
	tk_messageBox -icon error \
	    -message "You cannot SLEW while the laser is propogating"
	return
    }

# Ensure that the STRAP is off
    if {[AO state gaosTTGS]} {
	tk_messageBox -icon error \
	    -message "Warning The STRAP Detector is On"
	return
    }

# Try setting Guide mode (chop states) first here to see if the P2>P2 MAx prob goes away
    #apply guide config (nod states) before point origin
    set fieldObj ${::Config(tcs.field,namespace)}::${::Config(tcs.field,value)}
    set guide "No guiding"
    #puts "guide: $guide"
    set guideObj ::GuideNames::$guide
    #puts "guideObj: $guideObj"
    $guideObj apply tcs.field.guide

# Set OIWFS mode in the TCS
   set guide $::Config(tcs.field.guide,value)
   if { ! [string equal $guide ""] } {
       set inst $::Config(tcs.instrument,value)
       if {([string equal $guide "AO-OI"]) && [string match "*NIFS*" $inst]} {
	   set oiwfstarget $::Config(tcs.field.oiwfstarget,value)
	   #puts "oiwfs target: $oiwfstarget"
	   if {! [string equal $oiwfstarget ""]} {
	       #puts "found NIFS (Aowfs/OI)"
	       cs oiwfsSelect set oiwfs NIFS
               cs oiwfsSelect set output WFS
	       logger command oiwfsSelect
	   } else {
	       #puts "no OIWFS"
	       cs oiwfsSelect set oiwfs None
               cs oiwfsSelect set output WFS
	       logger command oiwfsSelect
	   }   
       } elseif {[string match "*OI*" $guide] || [string equal $guide "No guiding"]} {
	   #puts "OIWFS only or No guiding, choosing oiwfs based on instrument: $inst"
	   if {[string match "*GMOS*" $inst]} {
	       #puts "found GMOS"
	       cs oiwfsSelect set oiwfs GMOS
               cs oiwfsSelect set output WFS
	       logger command oiwfsSelect
	   } elseif {[string match "*NIFS*" $inst]} {
	       #puts "found NIFS"
	       cs oiwfsSelect set oiwfs NIFS
               cs oiwfsSelect set output WFS
	       logger command oiwfsSelect
	   } elseif {[string match "*GNIRS*" $inst]} {
	       #puts "found GNIRS"
	       cs oiwfsSelect set oiwfs GNIRS
               cs oiwfsSelect set output WFS
	       logger command oiwfsSelect
	   } elseif {[string match "*NIRI*" $inst]} {
	       #puts "found NIRI"
	       cs oiwfsSelect set oiwfs NIRI
               cs oiwfsSelect set output WFS
	       logger command oiwfsSelect
	   } elseif {[string match "*BHROS*" $inst]} {
	       #puts "found BHROS"
	       cs oiwfsSelect set oiwfs BHROS
               cs oiwfsSelect set output WFS
	       logger command oiwfsSelect
	   } else {
	       #puts "no OIWFS"
	       cs oiwfsSelect set oiwfs None
               cs oiwfsSelect set output WFS
	       logger command oiwfsSelect
	   }
       } else {
	   #puts "no OIWFS"
	   cs oiwfsSelect set oiwfs None
           cs oiwfsSelect set output WFS
	   logger command oiwfsSelect
         }
   }

# Configure default filters, fieldstop for the WFS, and AO Flexture Model

    if {[string match "*P1*" $guide]} {
	pwfs filter pwfs1 "Red"
#	pwfs fldstop pwfs1 "open1"
    }
    
    if {[string match "*P2*" $guide]} {
	pwfs filter pwfs2 "Red"
#	pwfs fldstop pwfs2 "open1"
    }

    if {[string match "*AO*" $guide]} {
	set ::Config(tcs.field.guide.aowfswavelength,value) "GAOS"
#	pwfs filter pwfs2 "AOWFS"
	# set the NCPA and Flexure config file names for altair
	if {[AO state useLwfs]} {
	    set wfs Lgs
	} else {
	    set wfs Ngs
	}
	set instr ""
	set port 0
	if {[string match "*NIRI*" $inst]} {
	    set instr NIRI
	    set port [sa agssad get portNiri]
	} elseif {[string match "*NIFS*" $inst]} {
	    set instr NIFS
	    set port [sa agssad get portNifs]
	}
	set port "p$port"
	if {[string length $inst] > 0} {
	    set ncpafile "/aoBase/rel/input/aoNcpa${instr}${port}${wfs}.dat"
	    set flexfile "/aoBase/rel/data/aoFlex${instr}${port}.dat"
	    #puts "ncpafile: $ncpafile"
	    #puts "flexfile: $flexfile"
	    cs aoFlex set ncpa $ncpafile
	    cs aoFlex set flex $flexfile
	    cs aoFlex set dir 3
	}
    }

    if {[string match "*OI*" $guide]} {
	if {[string match "*GMOS*" $inst]} {
	    set ::Config(tcs.field.guide.oiwfswavelength,value) "GMOS OIWFS"
	} else {
	    set ::Config(tcs.field.guide.oiwfswavelength,value) "K"
	}
    }

#     set oiwlList $::Config(tcs.field.guide.oiwfswavelength,list)
#     puts "OIWFS Wavelength List: $oiwlList inst: $inst"
#     set inst [$::Config(tcs.instrument,namespace)::$inst cget -name]
#     set inst [string toupper $inst]
#     puts "OIWFS Wavelength List: $oiwlList inst: $inst"
#     set oiwlName "$inst OIWFS K"
#     puts "looking for name: $oiwlName"
#     if {[$oiwlList index $oiwlName] > 0} {
# 	puts "found OI wl $oiwlName"
# 	set ::Config(tcs.field.guide.oiwfswavelength,value) $oiwlName
#     }

# Zero the offsets for the Gimbals if we're using aowfs and not LGS
    if {[string match "*AO*" $guide] && ![AO state useLwfs]} {
	cs aoGimOffsets set xoff 0
	cs aoGimOffsets set yoff 0
	cs aoGimOffsets set zoff 0
    }

# this is a slew ... reset wrap controls
   $itk_component(azwrap) select 1
   $itk_component(rotwrap) select 1

# Process the wrap controls
   switch -- [$itk_component(azwrap) get] {
      + {cs wrap set azimuth 1}
      "" {cs wrap set azimuth 0}
      - {cs wrap set azimuth -1}
   }
   switch -- [$itk_component(rotwrap) get] {
      + {cs wrap set rotator 1}
      "" {cs wrap set rotator 0}
      - {cs wrap set rotator -1}
   }
   logger command wrap

# Call the normal apply function.
   $this ComponentControl::applycmd

# Reinvoke the sf to aout conf inst origin and wavelength
   global sfPos

   if {$sfPos != "empty"} {
       .observePanel.frame.control.botframe.mirrors.lpath select $sfPos
   }

}

itcl::body TcsConfigControl::save {name} {
#+
#  Updates the named configuration with the active components.
#-
   foreach component $components option $options {
      if { [$itk_component($component) cget -active] } {
         $name configure \
                $option [[$itk_component($component) component selector] get]
      } else {
         $name configure $option ""
      }
   }
}

itcl::body TcsConfigControl::preview {} {
#+
#  Maps the preview window by calling the preview method for the
#  config object followed by the update method of the previewControl.
#-

# Create or map the preview panel.
   previewPanel map

# Store the values in the temporary config object.
   save $::Config(tcs,anon)

# Call the preview panel's update method to generate and display the preview.
   [[previewPanel cget -name] component control] update
}

itcl::body TcsConfigControl::load {name} {
   if { ! [string equal [namespace tail $name] ""] } {
      foreach component $components option $options {
         if { [$itk_component($component) cget -active] } {
            set comp [$name cget $option]
            if { ! [string equal $comp ""] } {
               set ::Config(tcs.[string tolower $component],value) $comp
               $itk_component($component) configure \
		   -source [namespace tail $name]
		if {$component == "pointOrig"} {
		    global instPO
		    set instPO $comp
		    #puts "set instPO to $instPO"
		}
            }
         }
      }
      set name ::FieldNames::[$name cget -field]
      foreach subcomponent $fieldcomponents suboption $fieldoptions {
	  set comp [$name cget $suboption]
	  if { ! [string equal $comp ""] } {
	      set ::Config(tcs.[string tolower $subcomponent],value) $comp
	  }
      }
   }
}

itcl::body TcsConfigControl::wrap par {
   switch $par {
      azimuth {
         switch -- [$itk_component(azwrap) get] {
            + {return 1}
            "" {return 0}
            - {return -1}
         }
      }
      rotator {
         switch -- [$itk_component(rotwrap) get] {
            + {return 1}
            "" {return 0}
            - {return -1}
         }
      }
   }
}

itcl::body TcsConfigControl::newfield {n1 n2 op} {
   set name $::Config(tcs.field,value)
   if { $name == "" } {
      $itk_component(obsid) configure -text ""
   } else {
      $itk_component(obsid) configure -text \
            [$::Config(tcs.field,namespace)::$name cget -observationid]
   }
}

itcl::body TcsConfigControl::sesidle {} {
   set dialog  $itk_interior.reason
   if { ! [winfo exists $dialog] } {
      set dialog [IdleReasonDialog $dialog -modality application \
            -master $itk_interior]
      $dialog center
   }
   if { [$dialog activate] } {
      ocssession idleReason [$dialog get reason] [$dialog get comment]
   }
}
