#+
#  TcsControl <- itk::Widget
#
#  Implements the TcsControl widget.
#
#  Options:
#          none
#
#  Methods:
#          none
#
#  D Terrett 3 May 2000
#
#  Copyright CCLRC
#+

itcl::class TcsControl {
   inherit itk::Widget

   constructor args {}

   private method disable par
   private method enable par
   private method carousel par
   private method parget par
   private method weather {}
   private method shStep
   private method shutterMode
   private method closeDome
   private variable dome
   private variable shutter
}

itk::usual TcsControl {
    keep -cursor -font -highlightthickness -activeborderwidth -borderwidth \
          -labelfont -popupcursor -insertborderwidth -insertofftime \
          -insertontime -insertwidth -selectborderwidth -textfont 
}

itcl::body TcsControl::constructor args {

# Divide the window into 3 vertically
   itk_component add row1 {
      frame $itk_interior.row1
   }
   itk_component add row2 {
      frame $itk_interior.row2
   }
   itk_component add row3 {
      frame $itk_interior.row3
   }
   pack $itk_component(row1) $itk_component(row2) $itk_component(row3) \
         -fill x -expand y

# The first row contains 3 frames.
   set w $itk_component(row1)
#   itk_component add row1f1 {
#      frame $w.f1 -bd 2 -relief ridge
#   }
   itk_component add row1f2 {
      frame $w.f2 -bd 2 -relief ridge
   }
   itk_component add row1f3 {
      frame $w.f3
   }
#   pack $itk_component(row1f1) $itk_component(row1f2) $itk_component(row1f3) \
         -side left -fill both -expand y
   pack $itk_component(row1f2) $itk_component(row1f3) \
         -side left -fill both -expand y

# The second frame in the first row is divided into 8 horizontally
   set w $itk_component(row1f2)
   itk_component add f2r1 {
      frame $w.f2r1 -bd 2
   }
   itk_component add f2r2 {
      frame $w.f2r2 -bd 2
   }
   itk_component add f2r3 {
      frame $w.f2r3 -bd 2
   }
   itk_component add f2r4 {
      frame $w.f2r4 -bd 2
   }
   itk_component add f2r5 {
      frame $w.f2r5 -bd 2
   }
   itk_component add f2r6 {
      frame $w.f2r6 -bd 2
   }
   itk_component add f2r7 {
      frame $w.f2r7 -bd 2
   }
   itk_component add f2r8 {
      frame $w.f2r8 -bd 2
   }
   pack $itk_component(f2r1) $itk_component(f2r2) $itk_component(f2r3) \
        $itk_component(f2r4) $itk_component(f2r5) $itk_component(f2r6) \
        $itk_component(f2r7) $itk_component(f2r8) -fill both -expand yes 

# The third frame in the first row is divided into 2 horizontally.
   set w $itk_component(row1f3)
   itk_component add f3top {
      frame $w.top -bd 2 -relief ridge
   }
   itk_component add f3bot {
      frame $w.bot -bd 2 -relief ridge
   }
   pack $itk_component(f3top) $itk_component(f3bot) -fill both -expand yes

# The third row contains 2 frames.
   set w $itk_component(row3)
   itk_component add row3f1 {
      frame $w.f1 -bd 2 -relief ridge
   }
   itk_component add row3f2 {
      frame $w.f2 -bd 2 -relief ridge
   }
   pack $itk_component(row3f1) $itk_component(row3f2) \
         -side left -fill both -expand y

# Park to Reboot buttons.
#   set w $itk_component(row1f1)
#   itk_component add park {
#      ApplyButton $w.park -command park
#   }
#   itk_component add datum {
#      ApplyButton $w.datum -command datum
#   }
#   itk_component add init {
#      ApplyButton $w.init -command init
#   }
#   itk_component add test {
#      ApplyButton $w.test -command test
#   }
#   itk_component add reboot {
#      ApplyButton $w.reboot -command reboot -confirm \
#            "This will reboot the TCS and all it's subsystems"
#   }
#   pack $itk_component(park) $itk_component(datum) $itk_component(init) \
#         $itk_component(test) $itk_component(reboot) -padx 4 -pady 8 \
#         -expand y -fill both 

# Commands to enable/disable following in each subsystem 
   set w $itk_component(f2r1)
   itk_component add header {
      label $w.followLabel -text "Set following state"
   }
   set w $itk_component(f2r2)
   itk_component add mcsLabel {
      label $w.mcsLabel -text "Mount    " 
   }
   itk_component add mcsOn {
      ApplyButton $w.mcsOn -command mcFollow -text On -parcommand \
          [code $this enable] 
   }
   itk_component add mcsOff {
      ApplyButton $w.mcsOff -command mcFollow -text Off -parcommand \
          [code $this disable] 
   }
   set w $itk_component(f2r3)
   itk_component add crcsLabel {
      label $w.crcsLabel -text "Rotator  " 
   }
   itk_component add crcsOn {
      ApplyButton $w.crcsOn -command crFollow -text On -parcommand \
          [code $this enable] 
   }
   itk_component add crcsOff {
      ApplyButton $w.crcsOff -command crFollow -text Off -parcommand \
          [code $this disable] 
   }
   set w $itk_component(f2r4)
   itk_component add p1Label {
      label $w.p1Label -text "PWFS1    " 
   }
   itk_component add pwfs1On {
      ApplyButton $w.pwfs1On -command p1Follow -text On -parcommand \
          [code $this enable] 
   }
   itk_component add pwfs1Off {
      ApplyButton $w.pwfs1Off -command p1Follow -text Off -parcommand \
          [code $this disable] 
   }
   set w $itk_component(f2r5)
   itk_component add p2Label {
      label $w.p2Label -text "PWFS2    " 
   }
   itk_component add pwfs2On {
      ApplyButton $w.pwfs2On -command p2Follow -text On -parcommand \
          [code $this enable] 
   }
   itk_component add pwfs2Off {
      ApplyButton $w.pwfs2Off -command p2Follow -text Off -parcommand \
          [code $this disable] 
   }
   set w $itk_component(f2r6)
   itk_component add oiLabel {
      label $w.oiLabel -text "OIWFS    " 
   }
   itk_component add oiwfsOn {
      ApplyButton $w.oiwfsOn -command oiFollow -text On -parcommand \
          [code $this enable] 
   }
   itk_component add oiwfsOff {
      ApplyButton $w.oiwfsOff -command oiFollow -text Off -parcommand \
          [code $this disable] 
   }
   set w $itk_component(f2r7)
   itk_component add m2Label {
      label $w.oiLabel -text "Secondary" 
   }
   itk_component add scsOn {
      ApplyButton $w.scsOn -command m2Follow -text On -parcommand \
          [code $this enable] 
   }
   itk_component add scsOff {
      ApplyButton $w.scsOff -command m2Follow -text Off -parcommand \
          [code $this disable] 
   }
#   set w $itk_component(f2r8)
#   itk_component add aoLabel {
#      label $w.oiLabel -text "AOS      " 
#   }
#   itk_component add aoOn {
#      ApplyButton $w.aoOn -command aoFollow -text On -parcommand \
#          [code $this enable] 
#   }
#   itk_component add aoOff {
#      ApplyButton $w.aoOff -command aoFollow -text Off -parcommand \
#          [code $this disable] 
#   }
   pack $itk_component(header) 
   pack $itk_component(mcsLabel) $itk_component(mcsOn) $itk_component(mcsOff) \
        -side left 
   pack $itk_component(crcsLabel) $itk_component(crcsOn) \
        $itk_component(crcsOff) -side left 
   pack $itk_component(p1Label) $itk_component(pwfs1On)\
        $itk_component(pwfs1Off) -side left
   pack $itk_component(p2Label) $itk_component(pwfs2On) \
        $itk_component(pwfs2Off) -side left
   pack $itk_component(oiLabel) $itk_component(oiwfsOn) \
        $itk_component(oiwfsOff) -side left
   pack $itk_component(m2Label) $itk_component(scsOn) \
        $itk_component(scsOff) -side left
#   pack $itk_component(aoLabel) $itk_component(aoOn) \
        $itk_component(aoOff) -side left

# Carousel driving mode command.
   set w $itk_component(f3top)
   itk_component add carousel {
      ApplyButton $w.carousel -command carousel -parcommand \
            [code $this carousel]
   }
   itk_component add domemode {
      iwidgets::optionmenu $w.domemode -labeltext \
            [lindex [cs carousel info domemode] 2] \
   }
   $itk_component(domemode) insert end Basic MinScatter MinVibration
   itk_component add shuttermode {
      iwidgets::optionmenu $w.shuttermode -labeltext \
            [lindex [cs carousel info shuttermode] 2] \
            -command [code $this shutterMode]
   }
   $itk_component(shuttermode) insert end FullyOpen Tracking
   itk_component add slit {
       iwidgets::spinner $w.slit -labeltext "Shutter aperture (m)" -width 8 \
             -validate real -increment [code $this shStep +] \
             -decrement [code $this shStep -] -state disabled
   }
   $itk_component(slit) insert end 9.320
   itk_component add dome {
      checkbutton $w.dome -text [lindex [cs carousel info dome] 2] \
            -variable [scope dome] -onvalue On -offvalue Off
   }
   $itk_component(dome) invoke
   itk_component add shutter {
      checkbutton $w.shutter -text [lindex [cs carousel info shutter] 2] \
            -variable [scope shutter] -onvalue On -offvalue Off
   }
   pack $itk_component(carousel) -pady 4
   pack $itk_component(domemode) \
         $itk_component(shuttermode) $itk_component(slit) \
         -padx 4 -pady 5 -anchor w
   pack $itk_component(dome) $itk_component(shutter) \
         -side left -padx 4 -pady 5 -anchor w

# Close dome command.
   set w $itk_component(f3bot)
   itk_component add close {
      ApplyButton $w.close -command domeClose
   }
   pack $itk_component(close) -fill both -expand yes -padx 10 -pady 5

# Vent gates move command.
   set w $itk_component(row2)
   itk_component add vg {
      frame $w.vg -bd 2 -relief ridge
   }
   pack $itk_component(vg) -fill x -expand y
   set w $itk_component(vg)
   itk_component add ventgates {
      ApplyButton $w.ventgates -command ventgates -parcommand \
            [code $this parget]
   }
   itk_component add east {
      scale $w.east -label [lindex [cs ventgates info east] 2] \
            -showvalue 1 -to 1.0 -orient horizontal -resolution 0.05
   }
   itk_component add west {
      scale $w.west -label [lindex [cs ventgates info west] 2] \
            -showvalue 1 -to 1.0 -orient horizontal -resolution 0.05
   }
   pack $itk_component(ventgates) -padx 4 -pady 2  -side left
   pack $itk_component(east) $itk_component(west) \
         -padx 4 -pady 2 -fill x -expand y -side left
   $itk_component(east) set [expr [sa ecssad get eastVentGatePos value] / 100]
   $itk_component(west) set [expr [sa ecssad get westVentGatePos value] / 100]

# Enclosure thermal control command.
   set w $itk_component(row3f1)
   itk_component add thermal {
      ApplyButton $w.thermal -command encThermal \
            -parcommand [code $this parget]
   }
   itk_component add mode {
      iwidgets::optionmenu $w.mode \
            -labeltext [lindex [cs encThermal info mode] 2] \
   }
   $itk_component(mode) insert end Passive Active Shutdown
   pack $itk_component(thermal) $itk_component(mode) -pady 4

# Create weather command sender here because we can't use an apply button
# because the weather data CAD must not be marked if the data source is
# being set to server.
   if [catch {cs weather info}] {
      epics cs weather
   }

# Weather command.
   set w $itk_component(row3f2)
   itk_component add weather {
      LiveButton $w.weather -command [code $this weather] \
            -text [lindex [cs weather info] 1] \
            -logmessage "Weather"
   }
   itk_component add source {
      iwidgets::optionmenu $w.source \
            -labeltext [lindex [cs weather info source] 2] \
   }
   $itk_component(source) insert end server local
   itk_component add temp {
      iwidgets::entryfield $w.temp \
            -labeltext [lindex [cs weather info temp] 2] -width 8
   }
   itk_component add press {
      iwidgets::entryfield $w.press \
            -labeltext [lindex [cs weather info press] 2] -width 8
   }
   itk_component add humid {
      iwidgets::entryfield $w.humid \
            -labeltext [lindex [cs weather info humid] 2] -width 8
   }
   pack $itk_component(weather) $itk_component(source) -padx 4
   pack $itk_component(temp) $itk_component(press) $itk_component(humid) \
         -anchor e
}

itcl::body TcsControl::enable par {
#+
# Enables following in a TCS subsystem
#-
   return On
}

itcl::body TcsControl::disable par {
#+
# Disables following in a TCS subsystem
#-
   return Off
}

itcl::body TcsControl::carousel par {
#+
# Sets carousel command parameters.
#-
   switch $par {
      dome {
         return $dome
      }
      shutter {
         return $shutter
      }
      slit {
         set sh [$itk_component(slit) get]
         if { $sh != "" } {
            set sh [expr $sh * 1000.0]
         }
         return $sh
      }
      default {
         return [$itk_component($par) get]
      }
   }
}

itcl::body TcsControl::parget par {
#+
# Sets command parameters for commands whos parameter widgets all have a
# "get" method.
#-
   return [$itk_component($par) get]
}

itcl::body TcsControl::weather {} {
#+
# Sets parameters and posts the weather command. The weather data is only
# set if the source is "local".
#-
   set source [$itk_component(source) get]
   if { [string compare $source "server"] } {
     set s 1
   } else {
     set s 0
   }
   cs weather set source $s
   if { [string compare $source local] == 0 } {
      cs weather set temp [$itk_component(temp) get]
      cs weather set press [$itk_component(press) get]
      cs weather set humid [$itk_component(humid) get]
   }
   if [catch {cs weather post} msg] {
      tk_messageBox -icon error -parent $itk_interior -message \
            "Error posting weather command: TCS reports \
            \"$msg\""
   }
}

itcl::body TcsControl::shStep sign {
   set sh [$itk_component(slit) get]
   set sh [expr $sh $sign 0.5]
   if { $sh > 16.999 } {
      set sh 16.999
   } elseif { $sh < 9.320 } {
      set sh 9.320
   }
   $itk_component(slit) clear
   $itk_component(slit) insert end $sh
}

itcl::body TcsControl::shutterMode {} {
   if { [string compare [$itk_component(shuttermode) get] Tracking] == 0 } {
      $itk_component(slit) configure -state normal
   } else {
      $itk_component(slit) configure -state disabled
   }
}

itcl::body TcsControl::closeDome {} {
   cs shutterPark set dummy mark
   cs ventgatesPark set dummy mark
   if [catch {cs tcsApply post} msg] {
      tk_messageBox -icon error -parent $itk_interior -message \
            "Error parking shutters and vent gates: TCS reports \
            \"$msg\""
   }
}
