#+
#  TcsConfig
#
#  Implements the TcsConfig class. A TcsConfig contains a list of
#  the configuration components (Component objects) that make up a 
#  configuration and a set a flags to indicate which are active (i.e. 
#  should be sent to the TCS when the configuration is applied.
#
#  Options:
#           -scienceTarget  The name of the science target component.
#
#           -guide          The name of the guide component.
#
#           -rotator        The name of the rotator component.
#
#           -pointOrig      The name of the pointing origin component.
#
#           -chop           The name of the chop component.
#
#           -slewOptions    The name of the slew options component.
#
#           -trackFrame     The name of the tracking frame component.
#
#           -instrument     The name of the instrument component.
#
#  Methods:
#          apply        Applies all the active components to the TCS.
#
#          init         Sets the tcs config object to its initial state.
#
#          preview      Sets all the active components in the preview.
#
#          save file    Writes the values of all the component options to
#                       the channel identifier "file".
#
#  D Terrett 7 June 2000
#
#  Copyright CCLRC
#+

itcl::class TcsConfig {
   destructor {$this init}
   public {
      proc subcomponents {}
      method apply {args}
      method init {}
      method preview {}
      method save {file}
      variable scienceTarget ""
      variable guide ""
      variable rotator ""
      variable pointOrig ""
      variable chop ""
      variable slewOptions ""
      variable trackFrame ""
      variable instrument ""
   }
   private {
      variable current_scienceTarget ""
      variable current_guide ""
      variable current_rotator ""
      variable current_pointOrig ""
      variable current_chop ""
      variable current_slewOptions ""
      variable current_trackFrame ""
      variable current_instrument ""
   }
}

itcl::body TcsConfig::subcomponents {} {
   return { \
      {scienceTarget SciTarget ScienceTargetNames ScienceTargetList {Science Target} sourceA} \
      {guide Guide GuideNames GuideList {Guide} {}} \
      {rotator Rotator RotatorNames RotatorList {Field Orientation} {}} \
      {pointOrig PointOrig PointOrigNames PointOrigList {Instrument Origin} all} \
      {chop Chop ChopNames ChopList {Chop} all} \
      {slewOptions SlewOptions SlewOptionsNames SlewOptionsList {Slew Configuration} {}} \
      {trackFrame TrackFrame TrackFrameNames TrackFrameList {Tracking Frames} {}} \
      {instrument Instrument InstrumentNames InstrumentList {Instrument} {}} \
   }
}

itcl::body TcsConfig::apply args {

# Call the apply method of all the components that have a value.
   if { $scienceTarget != "" } {
      ::ScienceTargetNames::$scienceTarget apply sourceA
   }
   if { $guide != "" } {
      ::GuideNames::$guide apply
   }
   if { $rotator != "" } {
      ::RotatorNames::$rotator apply
   }
   if { $pointOrig != "" } {
      ::PointOrigNames::$pointOrig apply all
   }
   if { $chop != "" } {
      ::ChopNames::$chop apply
   }
   if { $slewOptions != "" } {
      ::SlewOptionsNames::$slewOptions apply
   }
   if { $trackFrame != "" } {
      ::TrackFrameNames::$trackFrame apply
   }
   if { $instrument != "" } {
      ::InstrumentNames::$instrument apply
   }
}

itcl::body TcsConfig::init {} {
   $this configure -scienceTarget ""
   $this configure -guide ""
   $this configure -rotator ""
   $this configure -pointOrig ""
   $this configure -chop ""
   $this configure -slewOptions ""
   $this configure -trackFrame ""
   $this configure -instrument ""
}

itcl::body TcsConfig::preview {} {

# Call the preview method of all the components that have a value.
   if { $scienceTarget != "" } {
      ::ScienceTargetNames::$scienceTarget preview sourceA
   }
   if { $guide != "" } {
      ::GuideNames::$guide preview
   }
   if { $rotator != "" } {
      ::RotatorNames::$rotator preview
   }
   if { $pointOrig != "" } {
      ::PointOrigNames::$pointOrig preview poriginA
   }
   if { $slewOptions != "" } {
      ::SlewOptionsNames::$slewOptions preview
   }
   if { $trackFrame != "" } {
      ::TrackFrameNames::$trackFrame preview
   }
   if { $instrument != "" } {
      ::InstrumentNames::$instrument preview
   }
}

itcl::body TcsConfig::save file {
   puts $file "   -scienceTarget \"$scienceTarget\" \\"
   puts $file "   -guide \"$guide\" \\"
   puts $file "   -rotator \"$rotator\" \\"
   puts $file "   -pointOrig \"$pointOrig\" \\"
   puts $file "   -chop \"$chop\" \\"
   puts $file "   -slewOptions \"$slewOptions\" \\"
   puts $file "   -trackFrame \"$trackFrame\" \\"
   puts $file "   -instrument \"$instrument\""
}

itcl::configbody TcsConfig::scienceTarget {
   if { $current_scienceTarget != "" } {
      ScienceTargetNames::$current_scienceTarget refdec
   }
   set current_scienceTarget ""
   if { $scienceTarget != "" } {
      if { [catch {ScienceTargetNames::$scienceTarget refinc}] } {
         error "Science target \"$scienceTarget\" does not exist"
      } else {
         set current_scienceTarget $scienceTarget
      }
   }
}

itcl::configbody TcsConfig::guide {
   if { $current_guide != "" } {
      GuideNames::$current_guide refdec
   }
   set current_guide ""
   if { $guide != "" } {
      if { [catch {GuideNames::$guide refinc}] } {
         error "Guide configuration \"$guide\" does not exist"
      } else {
         set current_guide $guide
      }
   }
}

itcl::configbody TcsConfig::rotator {
   if { $current_rotator != "" } {
      RotatorNames::$current_rotator refdec
   }
   set current_rotator ""
   if { $rotator != "" } {
      if { [catch {RotatorNames::$rotator refinc}] } {
         error "Field orientation \"$rotator\" does not exist"
      } else {
         set current_rotator $rotator
      }
   }
}

itcl::configbody TcsConfig::pointOrig {
   if { $current_pointOrig != "" } {
      PointOrigNames::$current_pointOrig refdec
   }
   set current_pointOrig ""
   if { $pointOrig != "" } {
      if { [catch {PointOrigNames::$pointOrig refinc}] } {
         error "Pointing origin \"$pointOrig\" does not exist"
      } else {
         set current_pointOrig $pointOrig
      }
   }
}

itcl::configbody TcsConfig::chop {
   if { $current_chop != "" } {
      ChopNames::$current_chop refdec
   }
   set current_chop ""
   if { $chop != "" } {
      if { [catch {ChopNames::$chop refinc}] } {
         error "Chop configuration \"$chop\" does not exist"
      } else {
         set current_chop $chop
      }
   }
}

itcl::configbody TcsConfig::slewOptions {
   if { $current_slewOptions != "" } {
      SlewOptionsNames::$current_slewOptions refdec
   }
   set current_slewOptions ""
   if { $slewOptions != "" } {
      if { [catch {SlewOptionsNames::$slewOptions refinc}] } {
         error "Slew options \"$slewOptions\" does not exist"
      } else {
         set current_slewOptions $slewOptions
      }
   }
}

itcl::configbody TcsConfig::trackFrame {
   if { $current_trackFrame != "" } {
      TrackFrameNames::$current_trackFrame refdec
   }
   set current_trackFrame ""
   if { $trackFrame != "" } {
      if { [catch {TrackFrameNames::$trackFrame refinc}] } {
         error "tracking Frames \"$trackFrame\" does not exist"
      } else {
         set current_trackFrame $trackFrame
      }
   }
}

itcl::configbody TcsConfig::instrument {
   if { $current_instrument != "" } {
      InstrumentNames::$current_instrument refdec
   }
   set current_instrument ""
   if { $instrument != "" } {
      if { [catch {InstrumentNames::$instrument refinc}] } {
         error "Instrument \"$instrument\" does not exist"
      } else {
         set current_instrument $instrument
      }
   }
}
