#+
#  TcsConfig.itcl
#
#  Implements the TcsConfig class. A TcsConfig contains a list of
#  the configuration components (Component objects) that make up a 
#  configuration and a set a flags to indicate which are active (i.e. 
#  should be sent to the TCS when the configuration is applied.
#
#  Methods:
#
#     apply
#
#        Applies all the active components the telescope.
#
#  D Terrett 26 November 1999
#
#  Copyright CCLRC
#+

itcl::class TcsConfig {

   public proc subcomponents {}

   public variable scienceTarget ""
   public variable guide ""
   public variable rotator ""
   public variable pointOrig ""
   public variable slewOptions ""
   public variable trackFrame ""
   public variable instrument ""

   public method apply args
   public method preview
   public method save file
}

itcl::body TcsConfig::subcomponents {} {
   return { \
      {scienceTarget SciTarget ScienceTargetNames ScienceTargetList {Science Target} sourceA} \
      {guide Guide GuideNames GuideList {Guide} {}} \
      {rotator Rotator RotatorNames RotatorList {Field Orientation} {}} \
      {pointOrig PointOrig PointOrigNames PointOrigList {Pointing Origin} all} \
      {slewOptions SlewOptions SlewOptionsNames SlewOptionsList {Slew Configuration} {}} \
      {trackFrame TrackFrame TrackFrameNames TrackFrameList {Tracking Frames} {}} \
      {instrument Instrument InstrumentNames InstrumentList {Instrument} {}} \
   }
}

itcl::body TcsConfig::apply args {

# Call the apply method of all the components that have a value.
   if { [info commands ::ScienceTargetNames::$scienceTarget] != "" } {
      ::ScienceTargetNames::$scienceTarget apply sourceA
   }
   if { [info commands ::GuideNames::$guide] != "" } {
      ::GuideNames::$guide apply
   }
   if { [info commands ::RotatorNames::$rotator] != "" } {
      ::RotatorNames::$rotator apply
   }
   if { [info commands ::PointOrigNames::$pointOrig] != "" } {
      ::PointOrigNames::$pointOrig apply sourceA
   }
   if { [info commands ::SlewOptionsNames::$slewOptions] != "" } {
      ::SlewOptionsNames::$slewOptions apply
   }
   if { [info commands ::TrackFrameNames::$trackFrame] != "" } {
      ::TrackFrameNames::$trackFrame apply
   }
   if { [info commands ::InstrumentNames::$instrument] != "" } {
      ::InstrumentNames::$instrument apply
   }
}

itcl::body TcsConfig::preview {} {

# Call the preview method of all the components that have a value.
   if { $scienceTarget != "" } {
      ::ScienceTargetNames::$scienceTarget preview sourceA
   }
   if { [info commands ::GuideNames::$guide] != "" } {
      ::GuideNames::$guide preview
   }
   if { [info commands ::RotatorNames::$rotator] != "" } {
      ::RotatorNames::$rotator preview
   }
   if { [info commands ::PointOrigNames::$pointOrig] != "" } {
      ::PointOrigNames::$pointOrig preview poriginA
   }
   if { [info commands ::SlewOptionsNames::$slewOptions] != "" } {
      ::SlewOptionsNames::$slewOptions preview
   }
   if { [info commands ::TrackFrameNames::$trackFrame] != "" } {
      ::TrackFrameNames::$trackFrame preview
   }
   if { [info commands ::InstrumentNames::$instrument] != "" } {
      ::InstrumentNames::$instrument preview
   }
}

itcl::body TcsConfig::save file {
   puts $file "   -scienceTarget \"$scienceTarget\" \\"
   puts $file "   -guide \"$guide\" \\"
   puts $file "   -rotator \"$rotator\" \\"
   puts $file "   -pointOrig \"$pointOrig\" \\"
   puts $file "   -slewOptions \"$slewOptions\" \\"
   puts $file "   -trackFrame \"$trackFrame\" \\"
   puts $file "   -instrument \"$instrument\""
}
