#+
#  TcsConfigControl <- ComponentControl
#
#  Implements the TcsConfigControl widget.
#
#  D Terrett 6 April 2002
#
#  Copyright CCLRC
#+

itcl::class TcsConfigControl {
   inherit ComponentControl
   constructor args {}
   public {
      method load {name}
      method preview {}
      method save {name}
   }
   private {
      method apply {}
      method wrap {par}
      variable components {
         field pointOrig slewOptions chop trackFrame instrument
      }
      variable options {
         -field -pointOrig -slewOptions -chop -trackFrame -instrument
      }
   }
}

itk::usual TcsConfigControl {
   keep -borderwidth -cursor -font -highlightthickness -insertborderwidth \
         -insertofftime -insertontime -insertwidth -labelfont -popupcursor \
         -selectborderwidth -textfont -title -component
}

itcl::body TcsConfigControl::constructor args {

# Divide the window into 3 vertically.
   itk_component add row1 {
      frame $itk_interior.row1 -relief ridge -bd 2
   }
   itk_component add row2 {
      frame $itk_interior.row2 -relief ridge -bd 2
   }
   itk_component add row3 {
      frame $itk_interior.row3
   }
   pack $itk_component(row1) $itk_component(row2) $itk_component(row3) \
         -expand y -fill x

# Configuration component selectors.
   set w $itk_component(row1)
   itk_component add field {
      ComponentSelector $w.field -labeltext "Target Field" \
            -component tcs.field \
            -active 1 
   } {
      usual
      rename -textfont -majorfont majorFont Font
      rename -labelfont -majorfont majorFont Font
   }
   itk_component add pointOrig {
      ComponentSelector $w.pointOrig -labeltext "Instrument Origin" \
            -component tcs.pointorig \
            -active 1 
   } {
      usual
      rename -textfont -majorfont majorFont Font
      rename -labelfont -majorfont majorFont Font
   }
   itk_component add chop {
      ComponentSelector $w.chop -labeltext "Chop Configuration" \
            -component tcs.chop \
            -active 1 
   } {
      usual
      rename -textfont -majorfont majorFont Font
      rename -labelfont -majorfont majorFont Font
   }
   itk_component add slewOptions {
      ComponentSelector $w.slewOptions -labeltext "Slew Options" \
            -component tcs.slewoptions \
            -active 1 
   } {
      usual
      rename -textfont -majorfont majorFont Font
      rename -labelfont -majorfont majorFont Font
   }
   itk_component add trackFrame {
      ComponentSelector $w.trackFrame -labeltext "Tracking Frames" \
            -component tcs.trackframe \
            -active 1 
   } {
      usual
      rename -textfont -majorfont majorFont Font
      rename -labelfont -majorfont majorFont Font
   }
   itk_component add instrument {
      ComponentSelector $w.instrument -labeltext "Instrument" \
            -component tcs.instrument \
            -active 1 
   } {
      usual
      rename -textfont -majorfont majorFont Font
      rename -labelfont -majorfont majorFont Font
   }

   pack $itk_component(field) $itk_component(pointOrig) \
         $itk_component(chop) $itk_component(slewOptions) \
         $itk_component(instrument) -fill x -pady 1

# Wrap control
   set w $itk_component(row2)
   itk_component add wraptitle {
      label $w.wraptitle -text "Wrap Control: "
   }
   itk_component add azwrap {
      iwidgets::optionmenu $w.azwrap -labeltext Azimuth
   }
   $itk_component(azwrap) insert end + "" -
   itk_component add rotwrap {
      iwidgets::optionmenu $w.rotwrap -labeltext Rotator
   }
   $itk_component(rotwrap) insert end + "" -
   itk_component add wrapapply {
      ApplyButton $w.wrapapply -command wrap -text Apply \
            -parcommand [itcl::code $this wrap]
   }

   pack $itk_component(wrapapply) $itk_component(rotwrap) \
      $itk_component(azwrap) $itk_component(wraptitle) -side right -pady 3

# Replace the apply button with Slew/Set and Preview buttons.
   destroy $itk_component(store) $itk_component(aframe)

   set w $itk_component(row3)
   itk_component add setslew {
      LiveButton $w.setslew -text "Set/Slew" \
            -command [itcl::code $this apply] -width 8
   }
   itk_component add store {
      StoreButton $itk_interior.store -text Store -width 6 \
             -command [itcl::code $this store] \
             -combobox $itk_component(selector)
   }
   itk_component add preview {
      button $w.preview -text Preview -text Preview \
            -command [itcl::code $this preview] -width 8
   }
   pack $itk_component(setslew) $itk_component(store) $itk_component(preview) \
         -side left -expand y -pady 4 -in $itk_component(row3)

# Set the object description.
   set description configuration

   eval itk_initialize $args
}

itcl::body TcsConfigControl::apply {} {
#+
# Called when the apply button is pressed.
#-

# Process the wrap controls
   switch -- [$itk_component(azwrap) get] {
      + {cs wrap set azimuth 1}
      "" {cs wrap set azimuth 0}
      - {cs wrap set azimuth -1}
   }
   switch -- [$itk_component(rotwrap) get] {
      + {cs wrap set rotator 1}
      "" {cs wrap set rotator 0}
      - {cs wrap set rotator -1}
   }
   logger command wrap

# Call the normal apply function.
   $this ComponentControl::applycmd
}

itcl::body TcsConfigControl::save {name} {
#+
#  Updates the named configuration with the active components.
#-
   foreach component $components option $options {
      if { [$itk_component($component) cget -active] } {
         $name configure \
                $option [[$itk_component($component) component selector] get]
      } else {
         $name configure $option ""
      }
   }
}

itcl::body TcsConfigControl::preview {} {
#+
#  Maps the preview window by calling the preview method for the
#  config object followed by the update method of the previewControl.
#-

# Create or map the preview panel.
   previewPanel map

# Store the values in the temporary config object.
   save $::Config(tcs,anon)

# Initialise the preview system.
   tccPreview begin

# Load the preview system with the configuration.
    $::Config(tcs,anon) preview

# Call the preview panel's update method to generate and display the preview.
   [[previewPanel cget -name] component control] update
}

itcl::body TcsConfigControl::load {name} {
   if { ! [string equal [namespace tail $name] ""] } {
      foreach component $components option $options {
         if { [$itk_component($component) cget -active] } {
            set comp [$name cget $option]
            if { ! [string equal $comp ""] } {
               set ::Config(tcs.[string tolower $component],value) $comp
               $itk_component($component) configure \
                     -source [namespace tail $name]
            }
         }
      }
   }
}

itcl::body TcsConfigControl::wrap par {
   switch $par {
      azimuth {
         switch -- [$itk_component(azwrap) get] {
            + {return 1}
            "" {return 0}
            - {return -1}
         }
      }
      rotator {
         switch -- [$itk_component(rotwrap) get] {
            + {return 1}
            "" {return 0}
            - {return -1}
         }
      }
   }
}
