#+
#  TcsConfig <- Paramset
#
#  Implements the TcsConfig class. A TcsConfig contains a list of
#  the configuration components (Component objects) that make up a 
#  configuration and a set a flags to indicate which are active (i.e. 
#  should be sent to the TCS when the configuration is applied.
#
#  Options:
#           -field          The name of the field component.
#
#           -pointOrig      The name of the pointing origin component.
#
#           -chop           The name of the chop component.
#
#           -altair         The name of the ALTAIR component.
#
#           -slewOptions    The name of the slew options component.
#
#           -trackFrame     The name of the tracking frame component.
#
#           -instrument     The name of the instrument component.
#
#  Methods:
#          apply comp   Applies all the active components to the TCS.
#
#          init         Sets the tcs config object to its initial state.
#
#          preview      Sets all the active components in the preview.
#
#          save node    Saves the values of all the component options to
#                       the xml node.
#
#  D Terrett 21 February 2003
#
#  Copyright CCLRC
#+

itcl::class TcsConfig {
   inherit Paramset
   destructor {$this init}
   public {
      method apply {comp}
      method init {}
      method preview {view}
      method save {node}
      variable field ""
      variable pointOrig ""
      variable chop ""
      variable altair ""
      variable slewOptions ""
      variable trackFrame ""
      variable instrument ""
   }
   private {
      variable current_field ""
      variable current_pointOrig ""
      variable current_chop ""
      variable current_altair ""
      variable current_slewOptions ""
      variable current_trackFrame ""
      variable current_instrument ""
   }
}

itcl::body TcsConfig::apply {comp} {

# Call the apply method of all the components that have a value.
   if { ! [string equal $field ""] } {
      ::FieldNames::$field apply $comp.field
   }
   if { ! [string equal $pointOrig ""] } {
      ::PointOrigNames::$pointOrig apply $comp.pointorig
   }
   if { ! [string equal $chop ""] } {
      ::ChopNames::$chop apply $comp.chop
   }
   if { ! [string equal $altair ""] } {
      ::AltairNames::$altair apply $comp.altair
   }
   if { ! [string equal $slewOptions ""] } {
      ::SlewOptionsNames::$slewOptions apply $comp.slewoptions
   }
   if { ! [string equal $trackFrame ""] } {
      ::TrackFrameNames::$trackFrame apply $comp.trackframe
   }
   if { ! [string equal $instrument ""] } {
      ::InstrumentNames::$instrument apply $comp.instrument
   }
}

itcl::body TcsConfig::init {} {
   $this configure -field ""
   $this configure -pointOrig ""
   $this configure -chop ""
   $this configure -altair ""
   $this configure -slewOptions ""
   $this configure -trackFrame ""
   $this configure -instrument ""
}

itcl::body TcsConfig::preview {view} {

# Call the preview method of all the components that have a value.
   if { ! [string equal $field ""] } {
      ::FieldNames::$field preview $view
   }
   if { ! [string equal $pointOrig ""] } {
      ::PointOrigNames::$pointOrig preview $view poriginA
   }
   if { ! [string equal $slewOptions ""] } {
      ::SlewOptionsNames::$slewOptions preview $view
   }
   if { ! [string equal $trackFrame ""] } {
      ::TrackFrameNames::$trackFrame preview $view
   }
   if { ! [string equal $instrument ""] } {
      ::InstrumentNames::$instrument preview $view
   }
}

itcl::body TcsConfig::save {node} {
   set node [paramset $node tcs_configuration]
   param $node field $field
   param $node pointOrig $pointOrig
   param $node chop $chop
   param $node altair $altair
   param $node slewOptions $slewOptions
   param $node trackFrame $trackFrame
   param $node instrument $instrument
}

itcl::configbody TcsConfig::field {
   if { ! [string equal $current_field ""] } {
      FieldNames::$current_field refdec
   }
   set current_field ""
   if { ! [string equal $field ""] } {
      if { [catch {FieldNames::$field refinc}] } {
         error "Field \"$field\" does not exist"
      } else {
         set current_field $field
      }
   }
}

itcl::configbody TcsConfig::pointOrig {
   if { ! [string equal $current_pointOrig ""] } {
      PointOrigNames::$current_pointOrig refdec
   }
   set current_pointOrig ""
   if { ! [string equal $pointOrig ""] } {
      if { [catch {PointOrigNames::$pointOrig refinc}] } {
         error "Pointing origin \"$pointOrig\" does not exist"
      } else {
         set current_pointOrig $pointOrig
      }
   }
}

itcl::configbody TcsConfig::chop {
   if { ! [string equal $current_chop ""] } {
      ChopNames::$current_chop refdec
   }
   set current_chop ""
   if { ! [string equal $chop ""] } {
      if { [catch {ChopNames::$chop refinc}] } {
         error "Chop configuration \"$chop\" does not exist"
      } else {
         set current_chop $chop
      }
   }
}

itcl::configbody TcsConfig::altair {
   if { ! [string equal $current_altair ""] } {
      AltairNames::$current_altair refdec
   }
   set current_altair ""
   if { ! [string equal $altair ""] } {
      if { [catch {AltairNames::$altair refinc}] } {
         error "Altair configuration \"$altair\" does not exist"
      } else {
         set current_altair $altair
      }
   }
}

itcl::configbody TcsConfig::slewOptions {
   if { ! [string equal $current_slewOptions ""] } {
      SlewOptionsNames::$current_slewOptions refdec
   }
   set current_slewOptions ""
   if { ! [string equal $slewOptions ""] } {
      if { [catch {SlewOptionsNames::$slewOptions refinc}] } {
         error "Slew options \"$slewOptions\" does not exist"
      } else {
         set current_slewOptions $slewOptions
      }
   }
}

itcl::configbody TcsConfig::trackFrame {
   if { ! [string equal $current_trackFrame ""] } {
      TrackFrameNames::$current_trackFrame refdec
   }
   set current_trackFrame ""
   if { ! [string equal $trackFrame ""] } {
      if { [catch {TrackFrameNames::$trackFrame refinc}] } {
         error "tracking Frames \"$trackFrame\" does not exist"
      } else {
         set current_trackFrame $trackFrame
      }
   }
}

itcl::configbody TcsConfig::instrument {
   if { ! [string equal $current_instrument ""] } {
      InstrumentNames::$current_instrument refdec
   }
   set current_instrument ""
   if { ! [string equal $instrument ""] } {
      if { [catch {InstrumentNames::$instrument refinc}] } {
         error "Instrument \"$instrument\" does not exist"
      } else {
         set current_instrument $instrument
      }
   }
}
