#+
#  TcsPanel.itk
#
#  Implements the TcsPanel widget. A Panel widget with a TcsControl
#  widget packed into its interior
#
#  D Terrett 26 April 1999
#
#  Copyright CCLRC
#+

itcl::class TcsPanel {
   inherit Panel

   constructor args {}
}

itk::usual TcsPanel {
   keep -background -cursor
}

itcl::body TcsPanel::constructor args {

# Withdraw the top level window so that we don't see geometry changes 
# while waiting for sa to connect.
   set toplevel [winfo toplevel $itk_interior]
   wm withdraw $toplevel

   itk_component add control {
      TcsControl $itk_interior.control
   } {
      usual
      ignore -troughcolor
      ignore -disabledforeground
      ignore -highlightcolor
      ignore -selectbackground
      ignore -selectforeground
      ignore -activebackground
      ignore -insertbackground
      ignore -textbackground
      ignore -activeforeground
      ignore -selectcolor
   }

   setWidgetColors "$itk_component(menubar) $itk_component(control)" \
         $itk_option(-background) $itk_option(-foreground)

   pack $itk_component(control) -fill both -expand y

   set itk_option(-windows) $itk_component(control)

   eval itk_initialize $args

   wm deiconify $toplevel
}
