#+
#  TcsPanel <- Panel
#
#  Implements the TcsPanel widget. A Panel widget with a TcsControl
#  widget packed into its interior
#
#  Options:
#          none
#
#  Methods:
#          none
#
#  D Terrett 29 March 2001
#
#  Copyright CCLRC
#+

itcl::class TcsPanel {
   inherit Panel
   constructor args {}
}

itk::usual TcsPanel {
   keep -background -cursor
}

itcl::body TcsPanel::constructor args {

# Withdraw the top level window so that we don't see geometry changes 
# while waiting for sa to connect.
   set toplevel [winfo toplevel $itk_interior]
   wm withdraw $toplevel

   itk_component add control {
      TcsControl $itk_interior.control
   }

   setWidgetColors "$itk_component(menubar) $itk_component(control)" \
         $itk_option(-background) $itk_option(-foreground)

   pack $itk_component(control) -fill both -expand y

   eval itk_initialize $args

   wm deiconify $toplevel
}
