#+
#  TrackFrame
#
#  Implements the TrackFrame class. A TrackFrame object 
#  stores all the parameters needed to specify the tracking frame for
#  all the virtual telescopes.
#
#  Options:
#           -mountCosys     The mount tracking frame
#
#           -sourceACosys   The source A tracking frame
#
#           -sourceBCosys   The source B tracking frame
#
#           -sourceCCosys   The source C tracking frame
#
#           -pwfs1Cosys     The pwfs1 tracking frame
#
#           -pwfs2Cosys     The pwfs2 tracking frame
#
#           -oiwfsCosys     The oiwfs tracking frame
#
#  Methods:
#           apply args   Applies the track frame definition to the TCS by 
#                        setting the values of the TrackFrame command 
#                        parameters. Any parameters are ignored.
#
#           init         Sets the track frame object to its initial state.
#
#           preview      The tracking frame does not effect the preview 
#                        system so this method does nothing.
#
#           save file    Writes the values of the options to the channel
#                        identifier "file".
#
#  Procs:
#           subcomponents   Returns a list of the subcomponents of the
#                           TrackFrame objects.
#
#  D Terrett 26 June 2000
#
#  Copyright CCLRC
#+

itcl::class TrackFrame {
   constructor {} {}
   destructor {$this init}
   public {
      proc subcomponents {}
      method apply {args}
      method init {}
      method preview {} {}
      method save {file}
      variable mountCosys {} {newCosys mount $mountCosys}
      variable sourceACosys {} {newCosys sourceA $sourceACosys}
      variable sourceBCosys {} {newCosys sourceB $sourceBCosys}
      variable sourceCCosys {} {newCosys sourceC $sourceCCosys}
      variable pwfs1Cosys {} {newCosys pwfs1 $pwfs1Cosys}
      variable pwfs2Cosys {} {newCosys pwfs2 $pwfs2Cosys}
      variable oiwfsCosys {} {newCosys oiwfs $oiwfsCosys}
   }
   private {
      method newCosys {vt name}
      variable current_cosys
   }
}

itcl::body TrackFrame::constructor {} {
   set current_cosys(sourceA) ""
   set current_cosys(sourceB) ""
   set current_cosys(sourceC) ""
   set current_cosys(mount) ""
   set current_cosys(pwfs1) ""
   set current_cosys(pwfs2) ""
   set current_cosys(oiwfs) ""
}

itcl::body TrackFrame::subcomponents {} {
   return { \
      {mountCosys Cosys CosysNames CosysList {Mount Tracking Frame} trackMount} \
      {sourceACosys Cosys CosysNames CosysList {Source A Tracking Frame} trackSourceA} \
      {sourceBCosys Cosys CosysNames CosysList {Source B Tracking Frame} trackSourceB} \
      {sourceCCosys Cosys CosysNames CosysList {Source C Tracking Frame} trackSourceC} \
      {pwfs1Cosys Cosys CosysNames CosysList {PWFS1 Tracking Frame} trackPwfs1} \
      {pwfs2Cosys Cosys CosysNames CosysList {PWFS2 Tracking Frame} trackPwfs2} \
      {oiwfsCosys Cosys CosysNames CosysList {OIWFS Tracking Frame} trackOiwfs} \
   }
}

itcl::body TrackFrame::apply args {

# Set all the parameters.
   foreach cs {trackMount trackSourceA trackSourceB trackSourceC \
         trackPwfs1 trackPwfs2 trackOiwfs} \
         comp {mount sourceA sourceB sourceC pwfs1 pwfs2 oiwfs} {
      set cosys [set ${comp}Cosys]
      if { [string is space $cosys] } {
         cs $cs set system FK5
         cs $cs set equinox J2000
      } else {
         CosysNames::$cosys apply $cs
      }
      logger command $cs
   }
}

itcl::body TrackFrame::save file {
   puts $file "   -mountCosys \"$mountCosys\" \\"
   puts $file "   -sourceACosys \"$sourceACosys\" \\"
   puts $file "   -sourceBCosys \"$sourceBCosys\" \\"
   puts $file "   -sourceCCosys \"$sourceCCosys\" \\"
   puts $file "   -pwfs1Cosys \"$pwfs1Cosys\" \\"
   puts $file "   -pwfs2Cosys \"$pwfs2Cosys\" \\"
   puts $file "   -oiwfsCosys \"$oiwfsCosys\""
}

itcl::body TrackFrame::init {} {
   $this configure -sourceACosys ""
   $this configure -sourceBCosys ""
   $this configure -sourceCCosys ""
   $this configure -mountCosys ""
   $this configure -pwfs1Cosys ""
   $this configure -pwfs2Cosys ""
   $this configure -oiwfsCosys ""
}

itcl::body TrackFrame::newCosys {vt name} {
   if { $current_cosys($vt) != "" } {
      CosysNames::$current_cosys($vt) refdec
   }
   set current_cosys($vt) ""
   if { $name != "" } {
      if { [catch {CosysNames::$name refinc}] } {
         error "Coordinate system \"$name\" does not exist"
      } else {
         set current_cosys($vt) $name
      }
   }
}
