#+
#  TrackRateControl <- tcclib::ComponentControl
#
#  Implements the TrackRateControl widget.
#
#  Options:
#           -shadow
#
#  D Terrett 11 October 2001
#
#  Copyright CCLRC
#+

itcl::class TrackRateControl {
   inherit tcclib::ComponentControl
   constructor args {}
   itk_option define -shadow shadow Shadow {}
   public {
      method load {name}
      method save {name}
      method reset {}
   }
   private {
      method checkcosys {}
   }
}

itk::usual TrackRateControl {
   keep -borderwidth -cursor -font -highlightthickness -insertborderwidth \
         -insertofftime -insertontime -insertwidth -labelfont -popupcursor \
         -selectborderwidth -textfont -title -applyarg -namespace -componentlist
}

itcl::body TrackRateControl::constructor args {

   itk_component add frame {
      frame $itk_interior.frame -borderwidth 2 -relief ridge
   }
   pack $itk_component(frame) -fill x -expand y
   set w $itk_component(frame)

# Epoch.
   itk_component add epoch {
      iwidgets::entryfield $w.epoch \
            -labeltext [lindex [cs difTrSourceA info epoch] 2]
   }
   pack $itk_component(epoch)

# Tabbed notebook for rate.
   itk_component add notebook {
      iwidgets::tabnotebook $w.notebook
   }
   pack $itk_component(notebook) -expand yes -fill both

# Page for RA/Dec rates
   set w [$itk_component(notebook) add -label "RA/Dec"]

# Control for selecting a coordinate frame.
   itk_component add cosys {
      tcclib::SubComponentSelector $w.cosys -labeltext "Coordinate system" \
            -labelpos nw -componentlist CosysList -component cosys \
            -selectioncommand [code $this checkcosys]
   }
   pack $itk_component(cosys) -anchor e

# Track rates.
   itk_component add ra {
      iwidgets::entryfield $w.ra -width 12 -labeltext "RA (s/s)"
   }
   itk_component add dec {
      iwidgets::entryfield $w.dec -width 12 -labeltext "Dec (arcsec/s)"
   }
   pack $itk_component(ra) $itk_component(dec) -anchor w

# Page for Az/El/Dec rates
   set w [$itk_component(notebook) add -label "Az/El"]

# Track rates.
   itk_component add az {
      iwidgets::entryfield $w.az -width 12 -labeltext "Az (arcsec/s)"
   }
   itk_component add el {
      iwidgets::entryfield $w.el -width 12 -labeltext "El (arcsec/s)"
   }
   pack $itk_component(az) $itk_component(el) -anchor w

# Select the RA/Dec page.
  $itk_component(notebook) select RA/Dec

# Set the object class
   set objclass TrackRateComponent
   set description "differential track rate"

# Create the trackrate object used by apply.
   set scratchobj [namespace which -command [TrackRate #auto]]

   eval itk_initialize $args
}

itcl::body TrackRateControl::reset {} {
   $itk_component(epoch) clear
   $itk_component(ra) clear
   $itk_component(dec) clear
   $itk_component(az) clear
   $itk_component(el) clear
}

itcl::body TrackRateControl::load {name} {
   $itk_component(epoch) insert end [$name cget -epoch]
   set cosys [$name cget -cosys]
   if { [string equal $cosys AzEl] } {
      $itk_component(notebook) select Az/El
      $itk_component(az) insert end [$name cget -dtheta1]
      $itk_component(el) insert end [$name cget -dtheta2]
   } else {
      $itk_component(notebook) select RA/Dec
      if { [string is space $cosys] } {
         $itk_component(cosys) select FK5/J2000
      } else {
         $itk_component(cosys) select $cosys
      }
      $itk_component(ra) insert end [$name cget -dtheta1]
      $itk_component(dec) insert end [$name cget -dtheta2]
   }
}

itcl::body TrackRateControl::save {name} {
   if { [string equal [lindex [$itk_component(notebook) pageconfigure \
         [$itk_component(notebook) select select] -label] 4] Az/El] } {
      $name configure \
            -cosys AzEl \
            -epoch [$itk_component(epoch) get] \
            -dtheta1 [$itk_component(az) get] \
            -dtheta2 [$itk_component(el) get] \
   } else {
      $name configure \
            -cosys [$itk_component(cosys) get] \
            -epoch [$itk_component(epoch) get] \
            -dtheta1 [$itk_component(ra) get] \
            -dtheta2 [$itk_component(dec) get] \
   }
}

itcl::configbody TrackRateControl::shadow {
   $itk_component(cosys) configure -editcontrol \
            $itk_option(-shadow)cosys
   $itk_component(cosys) configure -shadow $itk_option(-shadow)
}

itcl::body TrackRateControl::checkcosys {} {
   set cosys [$itk_component(cosys) get]
   set frame [CosysNames::$cosys cget -frame]
   if { [string equal $frame AZEL_TOPO] } {
      $itk_component(cosys) select ""
   }
}
