#+
#  TrackFrameComponent.itcl
#
#  Implements the TrackFrameComponent class. A TrackFrameComponent object 
#  is a TrackFrame object that is stored in a configuration.
#
#  D Terrett 21 August 1998
#
#  Copyright CCLRC
#+

itcl::class TrackFrameComponent {
   inherit TrackFrame Component

   constructor {list args} {
      Component::constructor $list
   } {
      eval configure $args
   }

   public method save file
}

itcl::body TrackFrameComponent::save file {
   set objname [namespace tail $this]
   set namespace [info namespace qualifiers $this]
   puts $file "catch {delete object \"$namespace::$objname\"}"
   puts $file "TrackFrameComponent \"$namespace::$objname\"  $componentList \\"
   TrackFrame::save $file
}
