#+
#  TrackRate
#
#  Implements the TrackRate class. A TrackRate object 
#  stores all the parameters needed to specify a differential track rate.
#
#  Options:
#           -cosys     The tracking rate coordinate frame.
#
#           -dtheta1   The track rate in RA or Azimuth.
#
#           -dtheta2   The track rate in Dec or Elevation.
#
#           -epoch     The epoch of the track rates.
#
#  Methods:
#           apply vt   Applies the track rate definition to the TCS by setting 
#                      the values of the command parameters for the virtual
#                      telescope "vt".
#
#           preview vt The preview system does not support differential track 
#                      rates so this method does nothing.
#
#           save file  Writes the values of the options to the channel
#                      identifier "file".
#
#  D Terrett 7 October 1998
#
#  Copyright CCLRC
#+

itcl::class TrackRate {

   public proc subcomponents {}

   public method apply vt
   public method preview vt {}
   public method save file

   public variable cosys {}
   public variable epoch {}
   public variable dtheta1 {}
   public variable dtheta2 {}
}

itcl::body TrackRate::subcomponents {} {
   return { \
      {cosys Cosys CosysNames CosysList {Coordinate system} difTr} \
   }
}

itcl::body TrackRate::apply vt {

# Convert leading character of the virtual telescope name to upper case.
   set vt [string toupper [string range $vt 0 0]][string range $vt 1 end]

# Set all the parameters.
   if { $cosys == "" || $cosys == "AZEL_TOPO"} {
      cs difTr${vt} set system AZEL_TOPO
      cs difTr${vt} set equinox ""
   } else {
      CosysNames::$cosys apply difTr${vt}
   }
   cs difTr${vt} set epoch \"$epoch\"
   cs difTr${vt} set dtheta1 \"$dtheta1\"
   cs difTr${vt} set dtheta2 \"$dtheta2\"
}

itcl::body TrackRate::save file {
   puts $file "   -cosys \"$cosys\" \\"
   puts $file "   -epoch \"$epoch\" \\"
   puts $file "   -dtheta1 \"$dtheta1\" \\"
   puts $file "   -dtheta2 \"$dtheta2\""
}
