#+
#  TrackFrameControl.itk
#
#  Implements the TrackFrameControl widget.
#
#  D Terrett 10 November 1998
#
#  Copyright CCLRC
#+

itcl::class TrackFrameControl {
   inherit ComponentControl

   constructor args {}

   itk_option define -shadow shadow Shadow {}

   public method selectobj name
   public method updateobj name

   private method setazel tel
}

itk::usual TrackFrameControl {
   keep -activebackground -activeforeground -disabledforeground
   keep -background -borderwidth -cursor -foreground -highlightcolor
   keep -highlightthickness -insertbackground -insertborderwidth
   keep -insertofftime -insertontime -insertwidth -labelfont -popupcursor
   keep -selectbackground -selectborderwidth -selectforeground
   keep -textbackground -textfont -font
   keep -vt -title
}

itcl::body TrackFrameControl::constructor args {

# Frame for the track frames.
   itk_component add trackframes {
      frame $itk_interior.trackframes -bd 2 -relief ridge
   }
   pack $itk_component(trackframes) -fill x -expand y
   set w $itk_component(trackframes)

   itk_component add mountAzEl {
      checkbutton $w.mountazel -text Az/El -variable $w._mount \
            -command [code $this setazel mount]
   }
   itk_component add mountCosys {
      SubComponentSelector $w.mount -labeltext "Mount" \
            -labelpos w -componentlist CosysList -component mountCosys
   }
   itk_component add sourceAAzEl {
      checkbutton $w.sourceAazel -text Az/El -variable $w._sourceA \
            -command [code $this setazel sourceA]
   }
   itk_component add sourceACosys {
      SubComponentSelector $w.sourcea -labeltext "Source A" \
            -labelpos w -componentlist CosysList -component sourceACosys
   }
   itk_component add sourceBAzEl {
      checkbutton $w.sourceBazel -text Az/El -variable $w._sourceB \
            -command [code $this setazel sourceB]
   }
   itk_component add sourceBCosys {
      SubComponentSelector $w.sourceb -labeltext "Source B" \
            -labelpos w -componentlist CosysList -component sourceBCosys
   }
   itk_component add sourceCAzEl {
      checkbutton $w.sourceCazel -text Az/El -variable $w._sourceC \
            -command [code $this setazel sourceC]
   }
   itk_component add sourceCCosys {
      SubComponentSelector $w.sourcec -labeltext "Source C" \
            -labelpos w -componentlist CosysList -component sourceCCosys
   }
   itk_component add pwfs1AzEl {
      checkbutton $w.pwfs1azel -text Az/El -variable $w._pwfs1 \
            -command [code $this setazel pwfs1]
   }
   itk_component add pwfs1Cosys {
      SubComponentSelector $w.pwfs1 -labeltext "PWFS1" \
            -labelpos w -componentlist CosysList -component pwfs1Cosys
   }
   itk_component add pwfs2AzEl {
      checkbutton $w.pwfs2azel -text Az/El -variable $w._pwfs2 \
            -command [code $this setazel pwfs2]
   }
   itk_component add pwfs2Cosys {
      SubComponentSelector $w.pwfs2 -labeltext "PWFS2" \
            -labelpos w -componentlist CosysList -component pwfs2Cosys
   }
   itk_component add oiwfsAzEl {
      checkbutton $w.oiwfsazel -text Az/El -variable $w._oiwfs \
            -command [code $this setazel oiwfs]
   }
   itk_component add oiwfsCosys {
      SubComponentSelector $w.oiwfs -labeltext "OIWFS" \
            -labelpos w -componentlist CosysList -component oiwfsCosys
   }
   grid $itk_component(mountCosys) $itk_component(mountAzEl) -sticky e
   grid $itk_component(sourceACosys) $itk_component(sourceAAzEl) -sticky e
   grid $itk_component(sourceBCosys) $itk_component(sourceBAzEl) -sticky e
   grid $itk_component(sourceCCosys) $itk_component(sourceCAzEl) -sticky e
   grid $itk_component(pwfs1Cosys) $itk_component(pwfs1AzEl) -sticky e
   grid $itk_component(pwfs2Cosys) $itk_component(pwfs2AzEl) -sticky e
   grid $itk_component(oiwfsCosys) $itk_component(oiwfsAzEl) -sticky e

# Set the apply log message.
   $itk_component(storeapply) configure -logmessage "Tracking frames"

# Create the trackframe object used by apply.
   set scratchobj [namespace which -command [TrackFrame #auto]]

# Set the object class.
   set objclass TrackFrameComponent
   set description "tracking frames"

   eval itk_initialize $args
}

itcl::body TrackFrameControl::selectobj name {

   if { $name != "" } {
      foreach tel {mount sourceA sourceB sourceC pwfs1 pwfs2 oiwfs} {
         set frame [$name cget -${tel}Cosys]
         $itk_component(${tel}Cosys) select $frame
         upvar #0 [$itk_component(${tel}AzEl) cget -variable] check
         if {$frame == ""} {
            set check 1
         } else {
            set check 0
         }
      }
   }
}

itcl::body TrackFrameControl::updateobj name {
#+
# Updates the named trackframe object.
#-
   foreach tel {mount sourceA sourceB sourceC pwfs1 pwfs2 oiwfs} {
      set ${tel}Cosys [$itk_component(${tel}Cosys) get]
      upvar #0 [$itk_component(${tel}AzEl) cget -variable] check
      if { $check } {
         set ${tel}Cosys ""
      }
   }
   $name configure \
         -mountCosys $mountCosys \
         -sourceACosys $sourceACosys \
         -sourceBCosys $sourceBCosys \
         -sourceCCosys $sourceCCosys \
         -pwfs1Cosys $pwfs1Cosys \
         -pwfs2Cosys $pwfs2Cosys \
         -oiwfsCosys $oiwfsCosys \
}

itcl::configbody TrackFrameControl::shadow {
   $itk_component(mountCosys) configure -editcontrol \
            $itk_option(-shadow)mountCosys
   $itk_component(sourceACosys) configure -editcontrol \
            $itk_option(-shadow)sourceACosys
   $itk_component(sourceBCosys) configure -editcontrol \
            $itk_option(-shadow)sourceBCosys
   $itk_component(sourceCCosys) configure -editcontrol \
            $itk_option(-shadow)sourceCCosys
   $itk_component(pwfs1Cosys) configure -editcontrol \
            $itk_option(-shadow)pwfs1Cosys
   $itk_component(pwfs2Cosys) configure -editcontrol \
            $itk_option(-shadow)pwfs2Cosys
   $itk_component(oiwfsCosys) configure -editcontrol \
            $itk_option(-shadow)oiwfsCosys
   $itk_component(mountCosys) configure -shadow $itk_option(-shadow)
   $itk_component(sourceACosys) configure -shadow $itk_option(-shadow)
   $itk_component(sourceBCosys) configure -shadow $itk_option(-shadow)
   $itk_component(sourceCCosys) configure -shadow $itk_option(-shadow)
   $itk_component(pwfs1Cosys) configure -shadow $itk_option(-shadow)
   $itk_component(pwfs2Cosys) configure -shadow $itk_option(-shadow)
   $itk_component(oiwfsCosys) configure -shadow $itk_option(-shadow)
}

itcl::body TrackFrameControl::setazel tel {
#+
# Clears the cosys selector when Az/El is selected.
#-
   upvar #0 [$itk_component(${tel}AzEl) cget -variable] check
   if { $check } {
      $itk_component(${tel}Cosys) select ""
   }
}
