#+
#  TrackFramePanel <- Panel
#
#  Implements the TrackratePanel widget. A Panel widget with a 
#  TrackFrameControl widget packed into its interior.
#
#  Options:
#           -component      The class of component that the widget selects.
#
#           -componentlist
#
#           -namespace      The namespace in which the components are
#                           defined.
#
#  D Terrett 24 November 1999
#
#  Copyright CCLRC
#+

itcl::class TrackFramePanel {
   inherit Panel

   constructor args {}

   itk_option define -componentlist componentList ComponentList {}
   itk_option define -namespace namespace Namespace {}
   itk_option define -component component Component {}
}

itk::usual TrackFramePanel {
   keep -background -cursor
}

itcl::body TrackFramePanel::constructor args {
   itk_component add control {
      TrackFrameControl $itk_interior.control
   }
   setWidgetColors "$itk_component(menubar) $itk_component(control)" \
         $itk_option(-background) $itk_option(-foreground)

   pack $itk_component(control) -fill both -expand y

   set itk_option(-windows) $itk_component(control)

   eval itk_initialize $args
}

itcl::configbody TrackFramePanel::componentlist {
   $itk_component(control) configure -componentlist $itk_option(-componentlist)
}

itcl::configbody TrackFramePanel::namespace {
   $itk_component(control) configure -namespace $itk_option(-namespace)
}
