#+
#  TrackRatePanel <- tcclib::Panel
#
#  Implements the TrackratePanel widget. A Panel widget with a 
#  TrackRateControl widget packed into its interior.
#
#  Methods:
#           none
#
#  D Terrett 29 March 2001
#
#  Copyright CCLRC
#+

itcl::class TrackRatePanel {
   inherit tcclib::Panel
   constructor args {}
}

itk::usual TrackRatePanel {
   keep -background -cursor
}

itcl::body TrackRatePanel::constructor args {
   itk_component add control {
      TrackRateControl $itk_interior.control
   }
   setWidgetColors "$itk_component(menubar) $itk_component(control)" \
         $itk_option(-background) $itk_option(-foreground)

   pack $itk_component(control) -fill both -expand y

   eval itk_initialize $args
}
