#+
#  TrackFramePanel <- tcclib::Panel
#
#  Implements the TrackratePanel widget. A Panel widget with a 
#  TrackFrameControl widget packed into its interior.
#
#  D Terrett 29 March 2000
#
#  Copyright CCLRC
#+

itcl::class TrackFramePanel {
   inherit tcclib::Panel
   constructor args {}
}

itk::usual TrackFramePanel {
   keep -background -cursor
}

itcl::body TrackFramePanel::constructor args {
   itk_component add control {
      TrackFrameControl $itk_interior.control
   }
   setWidgetColors "$itk_component(menubar) $itk_component(control)" \
         $itk_option(-background) $itk_option(-foreground)

   pack $itk_component(control) -fill both -expand y

   eval itk_initialize $args
}
