#+
#  TrackFrameControl <- tcclib::ComponentControl
#
#  Implements the TrackFrameControl widget.
#
#  Options:
#           -shadow
#
#  Methods:
#           selectobj name
#
#           updateobj name
#
#  D Terrett 28 March 2001
#
#  Copyright CCLRC
#+

itcl::class TrackFrameControl {
   inherit tcclib::ComponentControl
   constructor args {}
   itk_option define -shadow shadow Shadow {}
   public {
      method selectobj {name}
      method updateobj {name}
   }
}

itk::usual TrackFrameControl {
   keep -borderwidth -cursor -font -highlightthickness -insertborderwidth \
         -insertofftime -insertontime -insertwidth -labelfont -popupcursor \
         -selectborderwidth -textfont -title -applyarg -namespace -componentlist
}

itcl::body TrackFrameControl::constructor args {

# Frame for the track frames.
   itk_component add trackframes {
      frame $itk_interior.trackframes -bd 2 -relief ridge
   }
   pack $itk_component(trackframes) -fill x -expand y
   set w $itk_component(trackframes)

   itk_component add mountCosys {
      tcclib::SubComponentSelector $w.mount -labeltext "Mount" \
            -labelpos w -componentlist CosysList -component mountCosys
   }
   itk_component add sourceACosys {
      tcclib::SubComponentSelector $w.sourcea -labeltext "Source A" \
            -labelpos w -componentlist CosysList -component sourceACosys
   }
   itk_component add sourceBCosys {
      tcclib::SubComponentSelector $w.sourceb -labeltext "Source B" \
            -labelpos w -componentlist CosysList -component sourceBCosys
   }
   itk_component add sourceCCosys {
      tcclib::SubComponentSelector $w.sourcec -labeltext "Source C" \
            -labelpos w -componentlist CosysList -component sourceCCosys
   }
   itk_component add pwfs1Cosys {
      tcclib::SubComponentSelector $w.pwfs1 -labeltext "PWFS1" \
            -labelpos w -componentlist CosysList -component pwfs1Cosys
   }
   itk_component add pwfs2Cosys {
      tcclib::SubComponentSelector $w.pwfs2 -labeltext "PWFS2" \
            -labelpos w -componentlist CosysList -component pwfs2Cosys
   }
   itk_component add oiwfsCosys {
      tcclib::SubComponentSelector $w.oiwfs -labeltext "OIWFS" \
            -labelpos w -componentlist CosysList -component oiwfsCosys
   }
   grid $itk_component(mountCosys) -sticky e
   grid $itk_component(sourceACosys) -sticky e
   grid $itk_component(sourceBCosys) -sticky e
   grid $itk_component(sourceCCosys) -sticky e
   grid $itk_component(pwfs1Cosys) -sticky e
   grid $itk_component(pwfs2Cosys) -sticky e
   grid $itk_component(oiwfsCosys) -sticky e

# Set the object class.
   set objclass TrackFrameComponent
   set description "tracking frames"

   eval itk_initialize $args

# Create the trackframe object used by apply.
   set scratchobj [namespace which -command [TrackFrame #auto]]
}

itcl::body TrackFrameControl::selectobj name {

   if { ! [string equal [namespace tail $name] ""] } {
      foreach tel {mount sourceA sourceB sourceC pwfs1 pwfs2 oiwfs} {
         $itk_component(${tel}Cosys) select [$name cget -${tel}Cosys]
      }
   }
}

itcl::body TrackFrameControl::updateobj name {
#+
# Updates the named trackframe object.
#-
   $name configure \
         -mountCosys [$itk_component(mountCosys) get] \
         -sourceACosys [$itk_component(sourceACosys) get] \
         -sourceBCosys [$itk_component(sourceBCosys) get] \
         -sourceCCosys [$itk_component(sourceCCosys) get] \
         -pwfs1Cosys [$itk_component(pwfs1Cosys) get] \
         -pwfs2Cosys [$itk_component(pwfs2Cosys) get] \
         -oiwfsCosys [$itk_component(oiwfsCosys) get]
}

itcl::configbody TrackFrameControl::shadow {
   $itk_component(mountCosys) configure -editcontrol \
            $itk_option(-shadow)mountCosys
   $itk_component(sourceACosys) configure -editcontrol \
            $itk_option(-shadow)sourceACosys
   $itk_component(sourceBCosys) configure -editcontrol \
            $itk_option(-shadow)sourceBCosys
   $itk_component(sourceCCosys) configure -editcontrol \
            $itk_option(-shadow)sourceCCosys
   $itk_component(pwfs1Cosys) configure -editcontrol \
            $itk_option(-shadow)pwfs1Cosys
   $itk_component(pwfs2Cosys) configure -editcontrol \
            $itk_option(-shadow)pwfs2Cosys
   $itk_component(oiwfsCosys) configure -editcontrol \
            $itk_option(-shadow)oiwfsCosys
   $itk_component(mountCosys) configure -shadow $itk_option(-shadow)
   $itk_component(sourceACosys) configure -shadow $itk_option(-shadow)
   $itk_component(sourceBCosys) configure -shadow $itk_option(-shadow)
   $itk_component(sourceCCosys) configure -shadow $itk_option(-shadow)
   $itk_component(pwfs1Cosys) configure -shadow $itk_option(-shadow)
   $itk_component(pwfs2Cosys) configure -shadow $itk_option(-shadow)
   $itk_component(oiwfsCosys) configure -shadow $itk_option(-shadow)
}
