#+
#  TrackRatePanel <- Panel
#
#  Implements the TrackratePanel widget. A Panel widget with a 
#  TrackRateControl widget packed into its interior.
#
#  Options:
#           -componentlist - The -componentlist option of the TrackRate control
#
#           -namespace -     The -namespace option of the TrackRate control
#
#           -component -
#
#  Methods:
#           none
#
#  D Terrett 24 November 1999
#
#  Copyright CCLRC
#+

itcl::class TrackRatePanel {
   inherit Panel

   constructor args {}

   itk_option define -componentlist componentList ComponentList {}
   itk_option define -namespace namespace Namespace {}
   itk_option define -component component Component {}
}

itk::usual TrackRatePanel {
   keep -background -cursor
}

itcl::body TrackRatePanel::constructor args {
   itk_component add control {
      TrackRateControl $itk_interior.control
   }
   setWidgetColors "$itk_component(menubar) $itk_component(control)" \
         $itk_option(-background) $itk_option(-foreground)

   pack $itk_component(control) -fill both -expand y

   set itk_option(-windows) $itk_component(control)

   eval itk_initialize $args
}

itcl::configbody TrackRatePanel::componentlist {
   $itk_component(control) configure -componentlist $itk_option(-componentlist)
}

itcl::configbody TrackRatePanel::namespace {
   $itk_component(control) configure -namespace $itk_option(-namespace)
}
