#+
#  TrackRateComponent <- TrackRate, Component
#
#  A TrackRateComponent object is a TrackRate object that is stored in a 
#  configuration list.
#
#
#  Options:
#           none
#
#  Methods:
#           constructor list  Creates the TrackRate object and puts it onto
#                           "list".
#
#           save file       Writes commands to re-create the object to the
#                           channel identifier "file" and then calls the
#                           TrackRate save method to add the objects data.
#
#  D Terrett 19 August 1999
#
#  Copyright CCLRC
#+

itcl::class TrackRateComponent {
   inherit TrackRate Component

   constructor {list args} {
      Component::constructor $list
   } {
      eval configure $args
   }

   public method save file
}

itcl::body TrackRateComponent::save file {
   set objname [namespace tail $this]
   set namespace [namespace qualifiers $this]
   puts $file "catch {delete object \"${namespace}::$objname\"}"
   puts $file "TrackRateComponent \"${namespace}::$objname\"  $componentList \\"
   TrackRate::save $file
}
