#+
#  WaveFrontSensor
#
#  Implements the interface to a wave-front sensor
#
#  Methods:
#           start
#
#           stop
#
#  Options:
#
#           -quicklook
#
#           -exposetime
#
#           -mode
#
#  D Terrett  17 January 2004
#
#  Copyright CLRC
#-

itcl::class WaveFrontSensor {
   constructor {wfs $args} {}
   public {
      method start {{frames -1}}
      method stop {}
      variable quicklook 0
      variable exposetime 0.01
      variable mode seq
   }
   private {
      variable prefix
      variable name
      variable dirname
      variable sky
      variable current_mode ""
      variable current_exposetime 0
      variable current_quicklook -1
   }
}

itcl::body WaveFrontSensor::constructor {wfs args} {
 
# Store the full name
   set name $wfs

# Set the prefix and directory name.
   switch $name {
      pwfs1 {
         set prefix p1
         set dirname p1wfs
      }
      pwfs2 {
         set prefix p2
         set dirname p2wfs
      }
      oiwfs {
         set prefix oi
         set dirname oiwfs
      }
   }

# Create command senders
   if { [catch {cs ${name}Observe info}] } {
      epics cs ${name}Observe
   }
   if { [catch {cs ${name}StopObserve info}] } {
      epics cs ${name}StopObserve
   }
   if { [catch {cs ${prefix}SeqDark info}] } {
      epics cs ${prefix}SeqDark
   }
   if { [catch {cs ${prefix}DetSigInit info}] } {
      epics cs ${prefix}DetSigInit
   }
   if { [catch {cs ${prefix}Seq info}] } {
      epics cs ${prefix}Seq
   }

   eval configure $args 
}

itcl::body WaveFrontSensor::start {{frames -1}} {

# Current state
   set stopped [expr {[sa guideConfig get ${prefix}state value] ne "Yes"}]

# Set the sky name
   set filename [expr { int(1.0/$exposetime)}]Hz.fits
   set sky [file join /gemini/files/wfs $dirname $filename]

# If the mode or exposure time or output destination has been changed then
# stop the sensor mode.
   if { $mode ne $current_mode || $exposetime != $current_exposetime || \
         $current_quicklook != $quicklook } {
      stop
      set stopped 1
      after 10
   }

# If the mode has changed, set the new processing mode
   if { $mode ne $current_mode } {
      switch $mode {
         sky {
            cs ${prefix}SeqDark set filename $sky
            logger command ${prefix}SeqDark
         }
         seq {
            cs ${prefix}Seq set z2m2 1
            logger command ${prefix}Seq
         }
         seqnz {
            cs ${prefix}Seq set z2m2 0
            logger command ${prefix}Seq
         }
      }
      if { [catch {cs tcsApply post} msg] } {
         tk_messageBox -icon error -message \
               "Error posting guide commands: TCS reports \
               \"$msg\""
      }
   }

# If the exposure time has changed then re-init the processing with
# the new file name.
   if { $exposetime != $current_exposetime } {
      cs ${prefix}DetSigInit set filename $sky
      logger command ${prefix}DetSigInit
      if { [catch {cs tcsApply post} msg] } {
         tk_messageBox -icon error -message \
               "Error posting guide commands: TCS reports \
               \"$msg\""
      }
   }

# Save the new mode and exposure time and quicklook.
   set current_mode $mode
   set current_exposetime $exposetime
   set current_quicklook $quicklook

# If the sensor is stopped, then start it with the appropriate settings.
   if { $stopped } {
      cs ${name}Observe set noexp $frames
      cs ${name}Observe set int $exposetime
      if { $quicklook } {
         cs ${name}Observe set outopt DHS
         cs ${name}Observe set output QL
      } else {
         cs ${name}Observe set outopt NONE
         cs ${name}Observe set output [list ""]
      }
      logger command ${name}Observe
      if { [catch {cs tcsApply post} msg] } {
         tk_messageBox -icon error -message \
               "Error posting guide commands: TCS reports \
               \"$msg\""
      }
   }
}

itcl::body WaveFrontSensor::stop {} {
   cs ${name}StopObserve set dummy 1
   logger command ${name}StopObserve
   if { [catch {cs tcsApply post} msg] } {
      tk_messageBox -icon error -message \
            "Error posting guide commands: TCS reports \
               \"$msg\""
   }
}
