#+
#  WavelengthComponent <- Wavelength, Component
#
#  A WavelengthComponent object is a Wavelength object that is stored in a 
#  configuration list.
#
#
#  Options:
#           none
#
#  Methods:
#           constructor list  Creates the Wavelength object and puts it onto
#                           "list".
#
#           save file       Writes commands to re-create the object to the
#                           channel identifier "file" and then calls the
#                           Wavelength save method to add the objects data.
#
#  D Terrett 25 September 2000
#
#  Copyright CCLRC
#+

itcl::class WavelengthComponent {
   inherit Wavelength Component
   constructor {list args} {
      Component::constructor $list
   } {
      eval configure $args
   }
   public {
      method save {file}
   }
}

itcl::body WavelengthComponent::save file {
   set obj [namespace tail $this]
   set namespace [namespace qualifiers $this]
   puts $file \
         "catch {WavelengthComponent \"${namespace}::$obj\"  $componentList}"
   puts $file "\"${namespace}::$obj\" init"
   puts $file "\"${namespace}::$obj\" configure \\"
   Wavelength::save $file
}
