#+
#  Wavelength
#
#  Implements the Wavelength class. A Wavelength object stores an effective 
#  wavelength.
#
#  Options:
#          -wavel      The wavelength.
#
#  Methods:
#          apply vt    Applies the wavelength to the TCS by setting the 
#                      values of the command parameters for virtual
#                      telescope "vt".
#
#          init          Returns the wavelength object to its initial state.
#
#          preview vt  Sets the preview wavelength for the virtual
#                      telescope "vt".
#
#          save        Writes the values of the options to the channel
#                      identifier "file".
#
#  Procs:
#           subcomponents   Returns a list of the subcomponents of the
#                           Wavelength objects (an empty list).
#
#  D Terrett 5 June 2000
#
#  Copyright CCLRC
#+

itcl::class Wavelength {
   public proc subcomponents {} {return {}}
   public {
      method apply {vt}
      method init {}
      method preview {vt}
      method save {file}
      variable wavel {} {set wavel [valWavelength $wavel]}
   }
}

itcl::body Wavelength::apply vt {
   set vt [string toupper [string range $vt 0 0]][string range $vt 1 end]
   cs wavel${vt} set wavel $wavel
   logger command wavel${vt}
}

itcl::body Wavelength::init {} {
   set wavel {}
}

itcl::body Wavelength::preview vt {
   if { ! [string equal $wavel ""] } {
      tccPreview set wavel${vt} $wavel
   }
}

itcl::body Wavelength::save file {
   puts $file "   -wavel \"$wavel\""
}
