#+
#  WavelengthControl <- ComponentControl
#
#  Implements the WavelengthControl widget. A ComponentControl widget with
#  an entryfield widget for the wavelength.
#
#  D Terrett 7 January 2002
#
#  Copyright CCLRC
#+

itcl::class WavelengthControl {
   inherit ComponentControl
   constructor args {}
   private {
      variable prevwl 0
      variable prevcentral
      variable prevdeploy
   }
   public {
      method load {name}
      method reset {}
      method save {name}
   }
}

itk::usual WavelengthControl {
   keep -borderwidth -cursor -font -highlightthickness -insertborderwidth\
         -insertofftime -insertontime -insertwidth -labelfont -popupcursor \
         -selectborderwidth -textfont -title
}

itcl::body WavelengthControl::constructor args {

   itk_component add wframe {
      frame $itk_interior.wframe -bd 2 -relief ridge
    }
    pack $itk_component(wframe)
    set w $itk_component(wframe)

# Entryfield for the wavelength.
   itk_component add wavel {
      iwidgets::entryfield $w.wavel \
           -labeltext [lindex [cs wavelSourceA info wavel] 2]  -width 8
   }
   pack $itk_component(wavel) -padx 4 -pady 4

# Central baffle
   itk_component add central {
      iwidgets::optionmenu $w.central -labeltext "M2 Central hole cover"
   }
   $itk_component(central) insert end "" open closed
   $itk_component(central) select open
   pack $itk_component(central) -anchor e -padx 3 -pady 3

# Deployable baffle
   itk_component add deploy {
      iwidgets::optionmenu $w.deploy -labeltext "M2 Deployable baffle"
   }
   $itk_component(deploy) insert end "" "thermal IR" "near IR" visible \
      extended
   pack $itk_component(deploy) -anchor e -padx 3 -pady 3

# Set the object description.
   set description wavelength

   eval itk_initialize $args
}

itcl::body WavelengthControl::save {name} {
#puts "WavelengthControl::save name: $name prevwl: $prevwl"
   if {[$itk_component(wavel) get] != $prevwl } {set prevwl "-1"}
   $name configure -wavel [$itk_component(wavel) get] \
          -centralBaffle [$itk_component(central) get] \
          -deployableBaffle [$itk_component(deploy) get]

}

itcl::body WavelengthControl::reset {} {
#puts "WavelengthControl::reset"
   if {$prevwl >= 0 } { set prevwl [$itk_component(wavel) get]}
   #set prevwl [$itk_component(wavel) get]
   set prevcentral [$itk_component(central) get]
   set prevdeploy [$itk_component(deploy) get]
   $itk_component(wavel) clear
   $itk_component(central) select ""
   $itk_component(deploy) select ""
}

itcl::body WavelengthControl::load {name} {
   set wavelen [$name cget -wavel]
   set set_baffles [$name cget -set_baffles]
#puts "WavelengthControl Load, name: $name, wavelen: $wavelen, prevwl: $prevwl set_baffles: $set_baffles"
   if {($wavelen != $prevwl) && $set_baffles } {
      if {$wavelen < 1.4} {
	$itk_component(central) select closed
	$itk_component(deploy) select visible
      } elseif {$wavelen > 3} {
	$itk_component(central) select open
	$itk_component(deploy) select "thermal IR"
      } else {
	$itk_component(central) select open
	$itk_component(deploy) select "near IR"
      }
      set prevwl $wavelen
   } else {
      $itk_component(central) select $prevcentral
      $itk_component(deploy) select $prevdeploy
   }
#	[$name cget -centralBaffle][$name cget -deployableBaffle]
   $itk_component(wavel) insert end $wavelen
}
