#+
#  WavelengthPanel <- Panel
#
#  Implements the WavelengthPanel widget. A Panel widget with a 
#  WavelengthControl widget packed into its interior.
#
#  Methods:
#           none
#
#  D Terrett 29 March 2001
#
#  Copyright CCLRC
#+

itcl::class WavelengthPanel {
   inherit Panel
   constructor args {}
}

itk::usual WavelengthPanel {
   keep -background -cursor
}

itcl::body WavelengthPanel::constructor args {
   itk_component add control {
      WavelengthControl $itk_interior.control
   }
   setWidgetColors "$itk_component(menubar) $itk_component(control)" \
         $itk_option(-background) $itk_option(-foreground)

   pack $itk_component(control) -fill both -expand y

   eval itk_initialize $args
}
