#+
#  WavelengthComponent.itcl
#
#  Implements the WavelengthComponent class. A WavelengthComponent object 
#  is a Wavelength object that is stored in a configuration list.
#
#  D Terrett 19 August 1999
#
#  Copyright CCLRC
#+

itcl::class WavelengthComponent {
   inherit Wavelength Component

   constructor {list args} {
      Component::constructor $list
   } {
      eval configure $args
   }

   public method save file
}

itcl::body WavelengthComponent::save file {
   set objname [namespace tail $this]
   set namespace [namespace qualifiers $this]
   puts $file "catch {delete object \"${namespace}::$objname\"}"
   puts $file "WavelengthComponent \"${namespace}::$objname\"  $componentList \\"
   Wavelength::save $file
}
