#+
#  WfsTarget <- Target
#
#  Implements the WfsTarget class. A WfsTarget object stores all
#  the parameters needed to specify a wave front sensor target.
#
#  Procs:
#           subcomponents Returns a list of the target classes subcomponents.
#
#  D Terrett 22 February 2000
#
#  Copyright CCLRC
#+

itcl::class WfsTarget {
   inherit Target
   public proc subcomponents {} {return [Target::subcomponents]}
}
