#+
#  WfsTargetPanel <- Panel
#
#  Implements the WfsTargetPanel widget. A Panel widget with a 
#  WfsTargetControl widget packed into its interior.
#
#  Methods:
#           none
#
#  D Terrett 29 March 2001
#
#  Copyright CCLRC
#+

itcl::class WfsTargetPanel {
   inherit Panel
   constructor args {}
   itk_option define -componentlist componentList ComponentList {}
   itk_option define -namespace namespace Namespace {}
}

itk::usual WfsTargetPanel {
   keep -background -cursor
}

itcl::body WfsTargetPanel::constructor args {
   itk_component add control {
      WfsTargetControl $itk_interior.control
   }
   setWidgetColors "$itk_component(menubar) $itk_component(control)" \
         $itk_option(-background) $itk_option(-foreground)

   pack $itk_component(control) -fill both -expand y

   eval itk_initialize $args
}
