#+
#  WfsTargetControl <- TargetControl
#
#  A WfsTarget control is a TargetControl widget for entering a wave front
#  sensor target.
#
#  D Terrett 28 March 2001
#
#  Copyright CCLRC
#+

itcl::class WfsTargetControl {
   inherit TargetControl
   constructor args {}
}

itk::usual WfsTargetControl {
   keep -borderwidth -cursor -font -highlightthickness -insertborderwidth \
         -insertofftime -insertontime -insertwidth -labelfont -popupcursor \
         -selectborderwidth -textfont -title -applyarg -componentlist -namespace
}

itcl::body WfsTargetControl::constructor args {

# Add destinations to the copy menu.
   $itk_component(copymenu) add command -label "Science targets" \
         -command [code $this copy createScienceTarget "Science target name" \
         tcsconfigscienceTarget]

# Define the object class
   set objclass WfsTargetComponent
   set description target

   eval itk_initialize $args

# Create the scatch target object used by apply.
   set scratchobj [namespace which -command [WfsTarget #auto]]
}
