#+
#  WfsTargetComponent <- WfsTarget, Component
#
#  A WfsTargetComponent object is a WfsTarget object that is stored in a 
#  configuration list.
#
#
#  Options:
#           none
#
#  Methods:
#           constructor list  Creates the WfsTarget object and puts it onto
#                           "list".
#
#           save file       Writes commands to re-create the object to the
#                           channel identifier "file" and then calls the
#                           Target save method to add the objects data.
#
#  D Terrett 22 February 2000
#
#  Copyright CCLRC
#+

itcl::class WfsTargetComponent {
   inherit WfsTarget Component

   constructor {list args} {
      Component::constructor $list
   } {
      eval configure $args
   }

   public method save file
}

itcl::body WfsTargetComponent::save file {
   set objname [namespace tail $this]
   set namespace [namespace qualifiers $this]
   puts $file "catch {delete object \"${namespace}::$objname\"}"
   puts $file "WfsTargetComponent \"${namespace}::$objname\"  $componentList \\"
   Target::save $file
}
