#+
#  AgsPanel <- Panel
#
#  Implements the AgsPanel widget. A Panel widget with a AgsControl
#  widget packed into its interior
#
#  Options:
#          none
#
#  Methods:
#          none
#
#  A Ebbers April, 2005
#
#+

itcl::class AgsPanel {
   inherit Panel
   constructor args {}
}

itk::usual AgsPanel {
   keep -background -cursor
}

itcl::body AgsPanel::constructor args {

# Withdraw the top level window so that we don't see geometry changes as
# we wait for sa to connect.
   set toplevel [winfo toplevel $itk_interior]
   wm withdraw $toplevel

   setWidgetColors $itk_interior \
         $itk_option(-background) $itk_option(-foreground)

   itk_component add control {
      AgsControl $itk_interior.control
   }

   pack $itk_component(control) -fill both -expand y

   eval itk_initialize $args

   wm deiconify $toplevel
}
