#+
#  GaosComponent <- Gaos, Component
#
#  A GaosComponent object is a Gaos object that is stored in a 
#  configuration list.
#
#
#  Options:
#           none
#
#  Methods:
#           constructor list  Creates the Gaos object and puts it onto
#                           "list".
#
#  D Terrett 1 November 2002
#
#  Copyright CCLRC
#+

itcl::class GaosComponent {
   inherit Component Gaos
   constructor {list args} {
      Component::constructor $list
   } {
      eval configure $args
   }
}
