itcl::class AzElTarget {
   inherit itk::Widget
   constructor {args} {}
   destructor {}
	method load target {}
	method save {target {propagate 1}} {}
	method cleanFields {} {}
	protected {
		method buildDiffTrackRate {parent}
	}
}

itk::usual AzElTarget {
    keep -background  -cursor
}

itcl::body AzElTarget::constructor {args} {
   #itk_option add hull.borderwidth hull.relief    
   eval itk_initialize $args

   set w $itk_interior
	
	itk_component add coordframe { frame $w.coordframe }

   itk_component add az {
      iwidgets::entryfield $w.coordframe.az -width 12 -labeltext Az
   } {
      usual
      rename -textfont -majorfont majorFont Font
      rename -labelfont -majorfont majorFont Font
   }
   itk_component add el {
      iwidgets::entryfield $w.coordframe.el -width 12 -labeltext El
   } {
      usual
      rename -textfont -majorfont majorFont Font
      rename -labelfont -majorfont majorFont Font
   }

# Controls for differential track rate.
	itk_component add trframe { iwidgets::labeledframe $w.trframe \
		-labelpos nw -labeltext "Differential Track Rates" -ipadx 1 -ipady 1 }
	
	buildDiffTrackRate [$itk_component(trframe) childsite]
   pack $itk_component(az) $itk_component(el) -side left -expand n -padx 3 -pady 15 \
      -anchor n	
   pack $itk_component(coordframe) -side top -anchor w -expand yes -fill x
   pack $itk_component(trframe) -side top -anchor w

}


itcl::body AzElTarget::cleanFields {} {
	$itk_component(az) clear
	$itk_component(el) clear
	set ::Config(tcs.field.cosys,value) ""
	set ::Config(tcs.field.trackrate2,value) ""
}

itcl::body AzElTarget::load {target} {
	if { ![string equal $target ""] && [string equal [$target cget -type] "degdegTarget"]} {
		cleanFields
		$itk_component(az) insert end [$target cget -c1]
		$itk_component(el) insert end [$target cget -c2]
		set ::Config(tcs.field.trackrate2,value) [$target cget -trackrate]
		set ::Config(tcs.field.trackrate2.cosys,value) AzEl		
	}
}

itcl::body AzElTarget::save {target {propagate 1}} {
	if { $propagate } {
		$itk_component(trcontrol) store
	}
	if { ![string equal $target ""] } {
		#$target init
		$target configure -type degdegTarget
		$target configure -c1 [$itk_component(az) get]
		$target configure -c2 [$itk_component(el) get]
		$target configure -trackrate $::Config(tcs.field.trackrate2,value)
	}	
}

itcl::body AzElTarget::buildDiffTrackRate {parent} {
	itk_component add trcontrol { TrackRateControl $parent.trcontrol \
		-component tcs.field.trackrate2 -cosys AzEl }
	pack $itk_component(trcontrol) -side top -anchor w  -padx 1 -pady 1
}
