#+
#  FieldControl <- ComponentControl
#
#  A FieldControl is a ComponentControl widget with widgets for the science
#  and wave-front sensor targets
#
#  Options:
#
#           -component      The name of the component that the control
#                           edits.
#
#  Methods:
#           load name       Copies the contents of the Field object "name"
#                           into the edit controls.
#
#           save name       Stores the contents of the edit controls in the
#                           Field object "name".
#
#           newtarget name type args  Creates a new target in the currently 
#                                     selected field.
#
#  D Terrett 16 Janaury 2004
#
#  Copyright CCLRC
#+

itcl::class FieldControl {
   inherit ComponentControl
   constructor args {}
   destructor {}
   itk_option define -component component Component {}
   public {
      method load {name}
      method reset {}
      method save {name}
      method sync {component name}
      method newtarget {name type args}
      method swapguide {}
   }
   private {
      method newfieldval {n1 n2 op}
      method pageSelectCB {color}
      variable comp ""
      variable currentname ""
      variable fieldObj ""
      variable curr_guide ""
      variable curr_sciencetarget ""
      variable curr_ns ""
      variable curr_objname ""
      variable curr_guidetarget ""
      variable curr_wl_name ""
      variable curr_wavelength ""
      variable new_wavelength ""
   }
}

itk::usual FieldControl {
   keep -borderwidth -cursor -font -highlightthickness -insertborderwidth \
         -insertofftime -insertontime -insertwidth -labelfont -popupcursor \
         -selectborderwidth -textfont -title
}

itcl::body FieldControl::constructor args {

# Expand the selector.
   $itk_component(selector) configure -width 55

   itk_component add display {
      frame $itk_interior.display
   }
   pack $itk_component(display) -side top -anchor c
   set w $itk_component(display)

# Display of current targets.
   itk_component add sciencelabel {
      label $w.sciencelabel -text "SCIENCE Target"
   }
   itk_component add sciencename {
      label $w.sciencename -width 30 -borderwidth 2 -relief sunken
   }
   itk_component add pwfs1label {
      label $w.pwfs1label -text "PWFS1 Target"
   }
   itk_component add pwfs1name {
      label $w.pwfs1name -width 30 -borderwidth 2 -relief sunken
   }
   itk_component add pwfs2label {
      label $w.pwfs2label -text "PWFS2 Target"
   }
   itk_component add pwfs2name {
      label $w.pwfs2name -width 30 -borderwidth 2 -relief sunken
   }
   itk_component add oiwfslabel {
      label $w.oiwfslabel -text "OIWFS target"
   }
   itk_component add oiwfsname {
      label $w.oiwfsname -width 30 -borderwidth 2 -relief sunken
   }
   itk_component add aowfslabel {
      label $w.aowfslabel -text "AOWFS target"
   }
   itk_component add aowfsname {
      label $w.aowfsname -width 30 -borderwidth 2 -relief sunken
   }
#   grid $itk_component(sciencelabel) $itk_component(sciencename)
#   grid $itk_component(pwfs1label)  $itk_component(pwfs1name)
#   grid $itk_component(pwfs2label) $itk_component(pwfs2name)
#   grid $itk_component(oiwfslabel) $itk_component(oiwfsname)
#   grid $itk_component(aowfslabel) $itk_component(aowfsname)

# Guide, rotator and wavelength selection.
   itk_component add subsel {
      frame $itk_interior.subsel
   }
   set w $itk_component(subsel)
   itk_component add guide {
      SubComponentSelector $w.guide -labeltext "Guide Configuration" \
            -labelpos w -width 30
   }
   itk_component add rotator {
      SubComponentSelector $w.rotator -labeltext "Rotator Configuration" \
            -labelpos w -width 30
   }
   itk_component add wavelength {
      SubComponentSelector $w.wavelength -labeltext "Observing wavelength" \
            -labelpos w -width 30
   }
   pack $itk_component(subsel)
   pack $itk_component(guide) $itk_component(rotator) \
         $itk_component(wavelength) -side top -pady 3 -anchor e

# Data entry widgets.
   itk_component add data {
      frame $itk_interior.data
   }
   set w $itk_component(data)

# Swapguide button
   itk_component add swapguide {
	button $w.swapguide -text "Swap Science/Guide Targets" -command "$this swapguide"
   }
   pack $itk_component(swapguide) -side top -pady 3




# Notebook for target entry controls.
   itk_component add tarframe {
      frame $w.tarframe -borderwidth 2 -relief raised
   }
   pack $itk_component(tarframe)
   set w $itk_component(tarframe)

   itk_component add targets {
      iwidgets::tabnotebook $w.targets -height 440 -width 450 \
            -tabpos n
   } {
      ignore -background -tabbackground
   }

# Science target page.
   set w [$itk_component(targets) add -label Science]

# Set colours from the options database
   set bg [option get $w background Background] 
   set fg [option get $w foreground Foreground] 
   setWidgetColors $w [option get $w background Background] \
         [option get $w foreground Foreground]

# Configure page to set background when selected.
   $itk_component(targets) pageconfigure Science -background $bg \
         -foreground $fg -command [itcl::code $this pageSelectCB $bg]

   itk_component add sciencecontrol {
      SciTargetControl $w.sciencecontrol
   } {
      usual
      ignore -title
   }
   pack $itk_component(sciencecontrol)

# Repeat for PWFS1
   set w [$itk_component(targets) add -label PWFS1]
   set bg [option get $w background Background] 
   set fg [option get $w foreground Foreground] 
   setWidgetColors $w [option get $w background Background] \
         [option get $w foreground Foreground]
   $itk_component(targets) pageconfigure PWFS1 -background $bg \
         -foreground $fg -command [itcl::code $this pageSelectCB $bg]

   itk_component add pwfs1control {
      SciTargetControl $w.pwfs1control -keepApply 1
   } {
      usual
      ignore -title
   }
   pack $itk_component(pwfs1control)

# and PWFS2
   set w [$itk_component(targets) add -label PWFS2]
   set bg [option get $w background Background] 
   set fg [option get $w foreground Foreground] 
   setWidgetColors $w [option get $w background Background] \
         [option get $w foreground Foreground]
   $itk_component(targets) pageconfigure PWFS2 -background $bg \
         -foreground $fg -command [itcl::code $this pageSelectCB $bg]

   itk_component add pwfs2control {
      SciTargetControl $w.pwfs2control -keepApply 1
   } {
      usual
      ignore -title
   }
   pack $itk_component(pwfs2control)

# and OIWFS
   set w [$itk_component(targets) add -label OIWFS]
   set bg [option get $w background Background] 
   set fg [option get $w foreground Foreground] 
   setWidgetColors $w [option get $w background Background] \
         [option get $w foreground Foreground]
   $itk_component(targets) pageconfigure OIWFS -background $bg \
         -foreground $fg -command [itcl::code $this pageSelectCB $bg]

   itk_component add oiwfscontrol {
      SciTargetControl $w.oiwfscontrol -keepApply 1
   } {
      usual
      ignore -title
   }
   pack $itk_component(oiwfscontrol)

# and AOWFS
   set w [$itk_component(targets) add -label AOWFS]
   set bg [option get $w background Background] 
   set fg [option get $w foreground Foreground] 
   setWidgetColors $w [option get $w background Background] \
         [option get $w foreground Foreground]
   $itk_component(targets) pageconfigure AOWFS -background $bg \
         -foreground $fg -command [itcl::code $this pageSelectCB $bg]

   itk_component add aowfscontrol {
      SciTargetControl $w.aowfscontrol -keepApply 1
   } {
      usual
      ignore -title
   }
   pack $itk_component(aowfscontrol)
   pack $itk_component(targets)

# Airmass limit and program ID.
   set w $itk_component(data)
   frame $w.sf
   itk_component add progid {
      iwidgets::entryfield $w.sf.progid -labeltext "Program ID" -width 15
   }
   itk_component add airmass {
      iwidgets::entryfield $w.sf.airmass -labeltext "Airmass limit" -width 8
   }
   pack $itk_component(airmass) $itk_component(progid) -side left \
         -padx 5 -pady 10 -expand yes

   $itk_component(targets) select Science

   pack $w.sf -side top -pady 3

   pack $itk_component(data) -side left -padx 3 -pady 3 -expand yes -fill y

# Set the current field name to the scratch field.
   set currentname $::Config(tcs.field,anon)

# Define the object description.
   set description "field"

# Turn off geometry propogation once the widget is constructed so that
# re-configuring the notebook widgets doesn't cause the top level window
# to be re-sized.
   after idle pack propagate $itk_component(tarframe) 0

   eval itk_initialize $args
   $itk_component(swapguide) configure -text "Swap Science/Guide Targets" -bg "white"
}

itcl::body FieldControl::destructor {} {

# Remove variable trace.
   trace vdelete ::Config($comp,value) w [itcl::code $this newfieldval]
}

itcl::body FieldControl::save {name} {

#+
# Updates the named field object.
#-

# If this is a new field then add each target and track rate from the old 
# field to the new provided that the old field still exists.
   if { ![string equal $currentname $name] && \
         ( [string equal $currentname $::Config(tcs.field,anon)] ||
         [lsearch -exact [itcl::find objects -class FieldComponent] \
         $currentname] >= 0 ) } {

# Copy each track rate first so that they all exist when we configure the
# targets.
      set n [${currentname}TrackRateList length]
      for { set i 0 } { $i < $n } { incr i } {
         set trackrate [${currentname}TrackRateList get $i]
         if { ![string is space $trackrate] } {
            $name add trackrate $trackrate

# Copy all parameters.
            foreach par [$currentname subconfigure trackrate $trackrate] {
               $name subconfigure trackrate $trackrate [lindex $par 0] \
                     [lindex $par 2]
            }

# Set refcount to zero since the new target isn't referenced anywhere yet.
            ${name}TrackRateNames::$trackrate configure -refcount 0
         }
      }

# Copy each target.
      set n [${currentname}TargetList length]
      for { set i 0 } { $i < $n } { incr i } {
         set target [${currentname}TargetList get $i]
         if { ![string is space $target] } {
            $name add target $target

# Copy all parameters.
            foreach par [$currentname subconfigure target $target] {
               $name subconfigure target $target [lindex $par 0] [lindex $par 2]
            }

# Set refcount to zero since the new target isn't referenced anywhere yet.
            ${name}TargetNames::$target configure -refcount 0
         }
      }

# If we have just copied the anonymous field then delete all its targets and
# track rates.
      if { [string equal $currentname $::Config(tcs.field,anon)] } {
         while { [${currentname}TargetList length] > 1 } {
            ${currentname}TargetList remove [${currentname}TargetList get 1]
         }
         while { [${currentname}TrackRateList length] > 1 } {
            ${currentname}TrackRateList remove \
                  [${currentname}TrackRateList get 1]
         }
      }
   }

# Configure the targets.
   foreach target {science pwfs1 pwfs2 oiwfs aowfs} {
      $name configure -${target}target \
            [$itk_component(${target}name) cget -text]
   }

# Set the remaining components.
   $name configure -guide [$itk_component(guide) get] \
         -rotator [$itk_component(rotator) get] \
         -wavelength [$itk_component(wavelength) get] \
         -programid [$itk_component(progid) get] \
         -airmassLimit [$itk_component(airmass) get]

# Record the new current object.
   set currentname $name
}

itcl::body FieldControl::reset {} {
   $itk_component(progid) clear
   $itk_component(airmass) clear
   set ::Config(tcs.field.sciencetarget,value) ""
   set ::Config(tcs.field.pwfs1target,value) ""
   set ::Config(tcs.field.pwfs2target,value) ""
   set ::Config(tcs.field.oiwfstarget,value) ""
   set ::Config(tcs.field.aowfstarget,value) ""
}


itcl::body FieldControl::swapguide {} {
   global env
   if {$curr_guide == ""} {
	set new_wavelength ""
	set fieldObj ${::Config(tcs.field,namespace)}::${::Config(tcs.field,value)}
	#puts "fieldObj: $fieldObj"

	set curr_guide ${::Config(tcs.field.guide,value)}
   	set curr_sciencetarget ${::Config(tcs.field.sciencetarget,value)}
	set curr_wl_name ${::Config(tcs.field.wavelength,value)}

	if {![string equal $curr_wl_name ""]} {
	   set curr_wavelength [::WavelengthNames::$curr_wl_name cget -wavel]
	}
	#puts "got current wavelength name: $curr_wl_name , wl: $curr_wavelength"
	# getting current guide wavelength (from Acquisition Camera)
	# Create the status acceptor if it doesn't alread exist.
	if { [catch {sa hrwfs::currStatus info}] } {
	   epics sa hrwfs::currStatus
	}
        if {$env(TCC_TCSNAME) == "tcs"} {
	    set guide_wl [.observePanel.frame.control.botframe.wfsconfig getValue HrwfsColFilt]
	} else {
	    set guide_wl [.observePanel.frame.control.botframe.wfsconfig.tabs.canvas.notebook.cs.page1.cs.hrwfs.col get]
	}
#	puts "swapguide got guide wl: $guide_wl"
	switch $guide_wl {
	   "U-red1"  { set new_wavelength "Acq Cam U" }
	   "B-blue"  { set new_wavelength "Acq Cam B" }
	   "V-green" { set new_wavelength "Acq Cam V" }
	   "R-red2"  { set new_wavelength "Acq Cam R" }
	   "I-red3"  { set new_wavelength "Acq Cam I" }
	   "neutral" { set new_wavelength "Acq Cam neutral" }
	   default   { set new_wavelength "" }
	}
       switch $curr_guide {
	   "P1-P2" -
	   "P1-OI" -
	   "AO-P1" -
	   "P1" {
	       set curr_guidetarget ${::Config(tcs.field.pwfs1target,value)}
	       #set ::Config(tcs.field.pwfs1target,value) ""
	       set lpath "Sky>AC/HR"
	   }
	   "P2-OI" -
	   "P2" {
	       set curr_guidetarget ${::Config(tcs.field.pwfs2target,value)}
	       #set ::Config(tcs.field.pwfs2target,value) ""
	       set lpath "Sky>AC/HR"
	   }
	   "OI" {
	       set curr_guidetarget ${::Config(tcs.field.oiwfstarget,value)}
	       #set ::Config(tcs.field.oiwfstarget,value) ""
	       set lpath "Sky>AC/HR"
	   }
	   "AO-OI" -
	   "AO" {
	       set curr_guidetarget ${::Config(tcs.field.aowfstarget,value)}
	       #set ::Config(tcs.field.aowfstarget,value) ""
	       set lpath "Sky>AO>AC/HR"
	   }
	   default {
	       tk_messageBox -icon warning -parent $itk_interior \
		   -message "Invalid guide configuration ... doing nothing"
	       # puts "No guidestar set ... do nothing"
	       set curr_guide ""
	       set curr_sciencetarget ""
	       return
	   }
	}
	if {$curr_guidetarget == ""} {
	   tk_messageBox -icon warning -parent $itk_interior \
		-message "No guidestar set ... doing nothing"
	   # puts "No guidestar set ... do nothing"
	   set curr_guide ""
	   set curr_sciencetarget ""
	   set curr_wl_name ""
	   set curr_wavelength ""
	   set new_wavelength ""
	   return
	}
   	 #puts "guide conficuration is: $curr_guide"
   	 #puts "Science target is $curr_sciencetarget, curr_wl_name: $curr_wl_name"
   	 #puts "Guide target is $curr_guidetarget"
	
	if {[string equal $new_wavelength ""]} {
	   tk_messageBox -icon warning -parent $itk_interior \
		-message "No guide wavelength found ... using 0.5 (Acq Cam neutral)"
	   set new_wavelength "Acq Cam neutral"
	}
	#puts "guide wl: $guide_wl using wl: $new_wavelength"
       logactions logmess "guide wl: $guide_wl using wl: $new_wavelength"

   	::WavelengthNames::$new_wavelength configure -set_baffles 0
	$fieldObj configure -guide "No guiding"
	$fieldObj configure -sciencetarget $curr_guidetarget
	$fieldObj configure -wavelength $new_wavelength

	$itk_component(swapguide) configure -text "Revert Science/Guide Targets" -bg red

	# set Light Path Mode (for the A&G)
	if [winfo exists .observePanel] {
	    ::.observePanel.frame.control.botframe.mirrors.lpath select $lpath
	}

	# Append _GUIDE to the object name.
	# puts "current guide target: $curr_guidetarget"
	set curr_ns ${::Config(tcs.field.sciencetarget,namespace)}
	set curr_objname [${curr_ns}::$curr_guidetarget cget -objname]
	#puts "objname: $curr_objname ns: $curr_ns"
	#puts "changing name to [list ${curr_objname}_GUIDE]"
	${curr_ns}::$curr_guidetarget configure -objname [list ${curr_objname}_GUIDE]
	$this load $fieldObj
	$this applycmd
   	::WavelengthNames::$new_wavelength configure -set_baffles 1
   } else {
	#puts "swapping back ..."
	
	switch $curr_guide {
	   "P1-P2" -
	   "P1-OI" -
	   "AO-P1" -
	   "P1" {
		   $fieldObj configure -pwfs1target $curr_guidetarget
		   set lpath "Sky>Instr"
	        }
	   "P2-OI" -
	   "P2" {
		   $fieldObj configure -pwfs2target $curr_guidetarget
		   set lpath "Sky>Instr"
	        }
	   "OI" {
		   $fieldObj configure -oiwfstarget $curr_guidetarget
		   set lpath "Sky>Instr"
	        }
	   "AO-OI" -
	   "AO" {
		   $fieldObj configure -aowfstarget $curr_guidetarget
		   set lpath "Sky>AO>Inst"
	        }
	}
	$fieldObj configure -guide $curr_guide
	$fieldObj configure -sciencetarget $curr_sciencetarget
	${curr_ns}::$curr_guidetarget configure -objname ${curr_objname}
	$fieldObj configure -wavelength $curr_wl_name

	# set Light Path Mode (for the A&G)
	if [winfo exists .observePanel] {
	    ::.observePanel.frame.control.botframe.mirrors.lpath select $lpath
	}
	
	#clear temp storage
	set curr_guide ""
	set curr_sciencetarget ""
	set curr_guidetarget ""
	set curr_wl_name ""
	set curr_wavelength ""
	#set fieldObj ""
	$itk_component(swapguide) configure -text "Swap Science/Guide Targets" -bg "white"
	$this load $fieldObj
	$this applycmd
   }
}


itcl::body FieldControl::load {name} {

# If the targets are currently swapped, swap back
   if {($curr_guide != "") && ( ${name} != ${currentname} )} {

	#puts "swapping back because loading new target ..."
	
	switch $curr_guide {
	   "P1-P2" -
	   "P1-OI" -
	   "AO-P1" -
	   "P1" {
		   $fieldObj configure -pwfs1target $curr_guidetarget
		   set lpath "Sky>Instr"
	        }
	   "P2-OI" -
	   "P2" {
		   $fieldObj configure -pwfs2target $curr_guidetarget
		   set lpath "Sky>Instr"
	        }
	   "OI" {
		   $fieldObj configure -oiwfstarget $curr_guidetarget
		   set lpath "Sky>Instr"
	        }
	   "AO-OI" -
	   "AO" {
		   $fieldObj configure -aowfstarget $curr_guidetarget
		   set lpath "Sky>AO>Inst"
	        }
	}
	$fieldObj configure -guide $curr_guide
	$fieldObj configure -sciencetarget $curr_sciencetarget
	${curr_ns}::$curr_guidetarget configure -objname ${curr_objname}
	$fieldObj configure -wavelength $curr_wl_name

	# set Light Path Mode (for the A&G)
	if [winfo exists .observePanel] {
	    ::.observePanel.frame.control.botframe.mirrors.lpath select $lpath
	}
	
	#clear temp storage
	set curr_guide ""
	set curr_sciencetarget ""
	set curr_guidetarget ""
	set curr_wl_name ""
	set curr_wavelength ""
	$itk_component(swapguide) configure -text "Swap Science/Guide Targets" -bg "white"
    }


# Copy the contents of the field object selected in the combobox into the 
# edit controls.

# Save the existing name so that we can copy all the targets it
# contains.
   set currentname ${name}

# Set the namespace and list to save targets and track rates in.
   foreach target {science pwfs1 pwfs2 oiwfs aowfs} {
      set ::Config($comp.${target}target,list) ${name}TargetList
      set ::Config($comp.${target}target,namespace) ${name}TargetNames
      set ::Config($comp.${target}target,value) [$name cget -${target}target]
      set ::Config($comp.${target}target.trackrate,list) ${name}TrackRateList
      set ::Config($comp.${target}target.trackrate,namespace) \
            ${name}TrackRateNames
   }

   set ::Config($comp.guide,value) [$name cget -guide]
   set ::Config($comp.rotator,value) [$name cget -rotator]
   set ::Config($comp.wavelength,value) [$name cget -wavelength]
   $itk_component(progid) clear
   $itk_component(airmass) clear
   $itk_component(progid) insert end [$name cget -programid]
   $itk_component(airmass) insert end [$name cget -airmassLimit]

}

itcl::configbody FieldControl::component {
# Remove any existing trace
   trace vdelete ::Config($comp,value) w [itcl::code $this newname]
   set comp ""

   if { $itk_option(-component) != "" } {
       set comp $itk_option(-component)

# Configure the component options of the target controls.
      foreach target {science pwfs1 pwfs2 oiwfs aowfs} {
         $itk_component(${target}control) configure \
               -component $comp.${target}target

# Configure the textvariable option on the target display widgets to the
# config array.
         $itk_component(${target}name) configure -textvariable \
               ::Config($comp.${target}target,value)
      }

# Configure the guide, rotator and wavelength components.
      $itk_component(guide) configure -component $comp.guide
      $itk_component(rotator) configure -component $comp.rotator
      $itk_component(wavelength) configure -component $comp.wavelength

# Set a trace on the component value so that we can detect the selection
# of the scratch object.
      trace variable ::Config($comp,value) w [itcl::code $this newfieldval]

# Set the name of the current component and the list and namespace for
# targets.
      set currentname $::Config($comp,anon)
      foreach target {science pwfs1 pwfs2 oiwfs aowfs} {
         set ::Config($comp.${target}target,list) ${currentname}TargetList
         set ::Config($comp.${target}target,namespace) ${currentname}TargetNames
      }
      set name $::Config($comp.wavelength,value)
   }
}

itcl::body FieldControl::sync {component name} {
   switch $component {
      tcs.field.sciencetarget {
         $itk_component(sciencecontrol) sync $name
      }
      tcs.field.pwfs1target {
         $itk_component(pwfs1control) sync $name
      }
      tcs.field.pwfs2target {
         $itk_component(pwfs2control) sync $name
      }
      tcs.field.oiwfstarget {
         $itk_component(oiwfscontrol) sync $name
      }
      tcs.field.aowfstarget {
         $itk_component(aowfscontrol) sync $name
      }
   }
}

itcl::body FieldControl::newfieldval {n1 n2 op} {
# Update the current name if the scratch object is selected. This is required
# because load will not get called.
   if { $::Config($comp,value) == "" } {
      set currentname $::Config($comp,anon)
   }
}

itcl::body FieldControl::newtarget {name type args} {
   if { $::Config(tcs.field,value) == "" } {
      set field $::Config(tcs.field,anon)
   } else {
      set field $::Config(tcs.field,namespace)::$::Config(tcs.field,value)
   }

# See if a name was specified.
   if { $name != "" } {
      set target $name
   } else {
      set target "Unnamed target"
   }

# Remove any existing target with the specified name.
   if { $target == $::Config(tcs.field.sciencetarget,value) } {
      $field configure -sciencetarget ""
   }
   if { $target == $::Config(tcs.field.pwfs1target,value) } {
      $field configure -pwfs1target ""
   }
   if { $target == $::Config(tcs.field.pwfs2target,value) } {
      $field configure -pwfs2target ""
   }
   if { $target == $::Config(tcs.field.oiwfstarget,value) } {
      $field configure -oiwfstarget ""
   }
   if { $target == $::Config(tcs.field.aowfstarget,value) } {
      $field configure -aowfstarget ""
   }
   catch {$field remove target $target}

# Create the new target.
   $field add target $target

# Configure the new target.
   eval [list $field] subconfigure target [list $target] $args

# Make it the specified target and select it.
   if { $type != "" } {
      $field configure -$type $target
      set ::Config(tcs.field.$type,value) $target
   }
}

itcl::body FieldControl::pageSelectCB {color} {

# Re-configure the notebook background to match the selected page.
   $itk_component(targets) config -background $color -tabbackground $color \
         -backdrop $color

# Restore the colours of the tabs.
   $itk_component(targets) pageconfigure Science -background \
         [option get $itk_component(sciencecontrol) background Background] 
   $itk_component(targets) pageconfigure PWFS1 -background \
         [option get $itk_component(pwfs1control) background Background] 
   $itk_component(targets) pageconfigure PWFS2 -background \
         [option get $itk_component(pwfs2control) background Background] 
   $itk_component(targets) pageconfigure OIWFS -background \
         [option get $itk_component(oiwfscontrol) background Background] 
   $itk_component(targets) pageconfigure AOWFS -background \
         [option get $itk_component(aowfscontrol) background Background] 
}
