#+
#  Field <- Paramset
#
#  Implements the Field class. A Field contains a list of targets, guide
#  and rotator configurations and an airmass limit and a gemini program
#  id.
#
#  Options:
#           -sciencetarget  The name of the science target
#
#           -pwfs1target    The name of the pwfs1 target
#
#           -pwfs2target    The name of the pwfs2 target
#
#           -oiwfstarget    The name of the oiwfs target
#
#           -aowfstarget    The name of the aowfs target
#
#           -ttgs1target    The name of the tip-tilt (Canopus) target 1
#
#           -ttgs2target    The name of the tip-tilt (Canopus) target 2
#
#           -ttgs3target    The name of the tip-tilt (Canopus) target 3
#
#           -odgw1target    The name of the on-detector guide window 1 target
#
#           -odgw2target    The name of the on-detector guide window 2 target
#
#           -odgw3target    The name of the on-detector guide window 3 target
#
#           -odgw4target    The name of the on-detector guide window 4 target
#
#           -rotator        The name of the rotator confguration
#
#           -guide          The name of the guide configuration
#
#           -airmassLimit   The airmass limit to
#
#           -programid      Gemini Program ID
#
#           -observationid  Gemini Observation ID
#
#           -wavelength     The observing wavelength
#
#  Methods:
#          apply comp   Applies all the active components to the TCS.
#
#          init         Sets the tcs config object to its initial state.
#
#          preview      Sets all the active components in the preview.
#
#          save node    Saves the values of all the component options to
#                       the xml node.
#
#          add type name  Adds a new target or track rate.
#
#          remove type name  Removes a target or track rate
#
#          subconfigure type name  Configures a target or track rate.
#
#          subinit type name       Inits a target or track rate.
#
#          subcget type name option Gets a target or track rate option.
#
#          plot azelplot Plots the field position on an azelplot.
#
#  D Terrett 14 March 2003
#
#  Copyright CCLRC
#+

itcl::class Field {
   inherit Paramset
   constructor {args} {}
   destructor {}
   public {
      method apply {comp}
      method init {}
      method preview {view}
      method save {node}
      method add {type name args}
      method remove {type name}
      method subconfigure {type name args}
      method subinit {type name}
      method subcget {type name option}
      method plot {azelplot} {puts "plotting $this on $azelplot"}
      variable sciencetarget ""
      variable pwfs1target ""
      variable pwfs2target ""
      variable oiwfstarget ""
      variable aowfstarget ""
		variable ttgs1target ""
		variable ttgs2target ""
		variable ttgs3target ""
		variable odgw1target ""
		variable odgw2target ""
		variable odgw3target ""
		variable odgw4target ""
		variable swaptarget ""
		variable swapguide ""
		variable swaprotator ""
		variable swapwavelength ""
		variable gcount 0
      variable rotator ""
      variable guide ""
      variable wavelength ""
      variable programid ""
      variable observationid ""
      variable airmassLimit ""
      variable targetns
      variable targetlist
      variable trackratens
      variable trackratelist
      variable posAngle
		
		variable taggedTargets
		method addTaggedTarget {{tagPrefix User} {target ""}}
		method removeTaggedTarget {taggedTarget}
		method setDefaultTarget { tagtarget }
		method clearDefaultTarget { tag }
		method getDefaultTarget { tag }
		method setSwapTarget { tagtarget }
		method clearSwapTarget {}
		method getSwapTarget {}
		method subscribe {observer}
      method unsubscribe {observer}
	}
   private {
      variable current_sciencetarget ""
      variable current_pwfs1target ""
      variable current_pwfs2target ""
      variable current_oiwfstarget ""
      variable current_aowfstarget ""
      variable current_guide ""
      variable current_rotator ""
      variable current_wavelength ""
		
		method cleanTaggedTargets {}
		
		variable observerList {}
		method notify {elementList}
   }
}

itcl::body Field::constructor {args} {

# Create the list and namespace for targets.
   set targetlist [ComponentList ${this}TargetList]
   set targetns ${this}TargetNames
   namespace eval $targetns {}

# Create the list and namespace for track rates.
   set trackratelist [ComponentList ${this}TrackRateList]
   set trackratens ${this}TrackRateNames
   namespace eval $trackratens {}
	
	set taggedTargets [namespace current]::[ObservedList #auto]

   eval configure $args
}

itcl::body Field::destructor {} {

# Set the object back to its default so that all the targets can be deleted.
   $this init

# Delete all the targets.
   set n [$targetlist length]
   set targets ""
   for {set i 0} {$i < $n} {incr i} {
      lappend targets [$targetlist get $i]
   }
   foreach name $targets {
      if { ![string equal $name ""] } {
         itcl::delete object ${targetns}::$name
      }
   }

# Delete the list and the namespace.
   itcl::delete object $targetlist
   namespace delete ${targetns}

# Repeat for the track rates.
   set n [$trackratelist length]
   set trackrates ""
   for {set i 0} {$i < $n} {incr i} {
      lappend trackrates [$trackratelist get $i]
   }
   foreach name $trackrates {
      if { ![string equal $name ""] } {
         itcl::delete object ${trackratens}::$name
      }
   }

# Delete the list and the namespace.
   itcl::delete object $trackratelist
   namespace delete $trackratens
	
	set n [$taggedTargets length]
   for {set i 0} {$i < $n} {incr i} {
      set name [$taggedTargets get $i]
      if { ![string equal $name ""] } {
         itcl::delete object $name
      }
   }
	itcl::delete object $taggedTargets
}

itcl::body Field::apply {comp} {
	global env

	if { $swaptarget ne "" } {
#		set tag [$swaptarget cget -tagPrefix]
#		switch $tag {
#		   "AOWFS" {
#		       set lpath "Sky>AO>AC/HR"
#		   }
#		   default {
#		       set lpath "Sky>AC/HR"
#		   }
#		}
#		if [winfo exists .observePanel] {
#		    ::.observePanel.frame.control.botframe.mirrors.lpath select $lpath
#		}

		[$swaptarget cget -target] apply science
		"::GuideNames::$swapguide" apply $comp.guide
	   if { ! [string equal $rotator ""] } {
	      ::RotatorNames::$rotator apply $comp.rotator
	   }
		
		"::WavelengthNames::$swapwavelength" configure -set_baffles 0
		"::WavelengthNames::$swapwavelength" apply $comp.wavelength
		"::WavelengthNames::$swapwavelength" configure -set_baffles 1

		if { ![string is space $airmassLimit] } {
	      cs airmassLimit set limit $airmassLimit
	      logger command airmassLimit
	   }
	   if { ![string is space $programid] } {
	      ss $::env(TCC_TCSNAME):sad:programID set value [list $programid]
	      ss $::env(TCC_TCSNAME):sad:programID post
	   }
	   if { ![string is space $observationid] } {
	      ocssession obsStart $observationid
	   }
	} else {
		#set light path (probably changed by a swap)
#		if {$guide ne "" } {
#			switch $guide {
#				"No guiding" -
#			   "P1-P2" -
#			   "P1-OI" -
#			   "AO-P1" -
#			   "P1" -
#			   "P2-OI" -
#			   "P2" -
#			   "OI" {
#				   set lpath "Sky>Instr"
#				}
#			   "AO-OI" -
#			   "AO" -
#				"GeMS" -
#				"GeMS-OI" {
#				   set lpath "Sky>AO>Inst"
#				}
#			}
#			if [winfo exists .observePanel] {
#			    ::.observePanel.frame.control.botframe.mirrors.lpath select $lpath
#			}
#		}
# Call the apply method of all the components that have a value.
	   if { ! [string equal $sciencetarget ""] } {
	      	[$sciencetarget cget -target] apply science
	   }
		foreach {tagtarget code} [list $pwfs1target pwfs1 $pwfs2target pwfs2 $oiwfstarget oiwfs $aowfstarget aowfs] {
			if { $tagtarget ne "" } {
				[$tagtarget cget -target] apply $code
			}
		}
		if {[calparam cget -site] eq "CP"} {
			set gId 1
			foreach tagtarget "$ttgs1target $ttgs2target $ttgs3target $odgw1target $odgw2target $odgw3target $odgw4target" {
				if { $tagtarget ne "" } {
					if { $gId > 4 } {
						error "Trying to use more that 4 GEMS stars."
					} else {
						[$tagtarget cget -target] apply g$gId
						set tag [$tagtarget cget -tagPrefix]
						switch $tag {
							CWFS1 {
								cs guidersMapping set G${gId}guider TTGS1
								"::GuideNames::$guide" applyGems g${gId} cwfs
							}
							CWFS2 {
								cs guidersMapping set G${gId}guider TTGS2
								"::GuideNames::$guide" applyGems g${gId} cwfs
							}
							CWFS3 {
								cs guidersMapping set G${gId}guider TTGS3
								"::GuideNames::$guide" applyGems g${gId} cwfs
							}
							ODGW1 -
							ODGW2 -
							ODGW3 -
							ODGW4 {
								cs guidersMapping set G${gId}guider [$tagtarget cget -tagPrefix]
								"::GuideNames::$guide" applyGems g${gId} odgw
							}
						}
						incr gId
					}
				}
			}
			for {} {$gId <= 4} {incr gId} {
				cs guidersMapping set G${gId}guider None
				"::GuideNames::$guide" applyGems g${gId} none
			}
		}
	   if { ! [string equal $guide ""] } {
	      ::GuideNames::$guide apply $comp.guide
	   }
	   if { ! [string equal $rotator ""] } {
	      ::RotatorNames::$rotator apply $comp.rotator
	   }
	   if { ! [string equal $wavelength ""] } {
	      ::WavelengthNames::$wavelength apply $comp.wavelength
	   }
	   if { ![string is space $airmassLimit] } {
	      cs airmassLimit set limit $airmassLimit
	      logger command airmassLimit
	   }
	   if { ![string is space $programid] } {
	      ss $::env(TCC_TCSNAME):sad:programID set value [list $programid]
	      ss $::env(TCC_TCSNAME):sad:programID post
	   }
	   if { ![string is space $observationid] } {
	      ocssession obsStart $observationid
	   }
	}
}

itcl::body Field::init {} {
   $this configure -sciencetarget ""
   $this configure -pwfs1target ""
   $this configure -pwfs2target ""
   $this configure -oiwfstarget ""
   $this configure -aowfstarget ""
	set ttgs1target ""
	set ttgs2target ""
	set ttgs3target ""
	set odgw1target ""
	set odgw2target ""
	set odgw3target ""
	set odgw4target ""
	set swaptarget ""
	set gcount 0
	$this configure -guide ""
   $this configure -rotator ""
   $this configure -wavelength ""
   set programid ""
   set airmassLimit ""
	cleanTaggedTargets
}

itcl::body Field::preview {view} {

# Call the preview method of all the components that have a value.
   if { ! [string equal $sciencetarget ""] } {
      [$sciencetarget cget -target] preview $view sourceA
   }
   if { ! [string equal $pwfs1target ""] } {
      [$pwfs1target cget -target] preview $view pwfs1
   }
   if { ! [string equal $pwfs2target ""] } {
      [$pwfs2target cget -target] preview $view pwfs2
   }
   if { ! [string equal $oiwfstarget ""] } {
      [$oiwfstarget cget -target] preview $view oiwfs
   }
   if { ! [string equal $aowfstarget ""] } {
      [$aowfstarget cget -target] preview $view aowfs
   }
   if { ! [string equal $guide ""] } {
      ::GuideNames::$guide preview $view
   }
   if { ! [string equal $rotator ""] } {
      ::RotatorNames::$rotator preview $view
   }
   if { ! [string equal $wavelength ""] } {
      ::WavelengthNames::$wavelength preview $view science
   }
}

itcl::body Field::save {node} {
   set node [paramset $node field]
	if {$sciencetarget ne "" } {
   	param $node sciencetarget [namespace tail [$sciencetarget cget -target]]
	} else {
		param $node sciencetarget ""
	}
	if { $pwfs1target ne "" } {
   	param $node pwfs1target [namespace tail [$pwfs1target cget -target]]
	} else {
		param $node pwfs1target ""
	}
	if { $pwfs2target ne "" } {
		param $node pwfs2target [namespace tail [$pwfs2target cget -target]]
	} else {
		param $node pwfs2target ""
	}
	if { $oiwfstarget ne "" } {
		param $node oiwfstarget [namespace tail [$oiwfstarget cget -target]]
	} else {
		param $node oiwfstarget ""
	}
	if { $aowfstarget ne "" } {
		param $node aowfstarget [namespace tail [$aowfstarget cget -target]]
	} else {
		param $node aowfstarget ""
	}
   param $node guide $guide
   param $node rotator $rotator
   param $node wavelength $wavelength
   param $node programid $programid
   param $node airmassLimit $airmassLimit

   for {set i 0} {$i < [$targetlist length]} {incr i} {
      set target [$targetlist get $i]
      if { ! [string equal $target ""] } {
         ${targetns}::$target save $node
      }
   }
   for {set i 0} {$i < [$trackratelist length]} {incr i} {
      set trackrate [$trackratelist get $i]
      if { ! [string equal $trackrate ""] } {
         ${trackratens}::$trackrate save $node
      }
   }
}

itcl::configbody Field::sciencetarget {
	if { [llength [itcl::find objects $sciencetarget -isa TaggedTarget]] == 0 } {
		set sciencetarget ""
	}
}

itcl::configbody Field::pwfs1target {
	if { [llength [itcl::find objects $pwfs1target -isa TaggedTarget]] == 0 } {
		set pwfs1target ""
	}
}

itcl::configbody Field::pwfs2target {
	if { [llength [itcl::find objects $pwfs2target -isa TaggedTarget]] == 0 } {
		set pwfs2target ""
	}
}

itcl::configbody Field::oiwfstarget {
	if { [llength [itcl::find objects $oiwfstarget -isa TaggedTarget]] == 0 } {
		set oiwfstarget ""
	}
}

itcl::configbody Field::aowfstarget {
	if { [llength [itcl::find objects $aowfstarget -isa TaggedTarget]] == 0 } {
		set aowfstarget ""
	}
}

itcl::configbody Field::guide {
   if { ! [string equal $current_guide ""] } {
      GuideNames::$current_guide refdec
   }
   set current_guide ""
   if { ! [string equal $guide ""] } {
#		if { [calparam cget -site] eq "CP" } {
		# Some name translations are needed for CP
#			if { [string match "*AO*" $guide] } {
#				if { [string match "*GSAOI*" $::Config(tcs.instrument,value)] } {
#					set guide GeMS
#				} elseif { $guide eq "AO-OI" } {
#					set guide "GeMS-OI"
#				}
#			}
#		}
      if { [catch {GuideNames::$guide refinc}] } {
         error "Guide configuration \"$guide\" does not exist"
      } else {
         set current_guide $guide
      }
   }
}

itcl::configbody Field::rotator {
   if { ! [string equal $current_rotator ""] } {
      RotatorNames::$current_rotator refdec
   }
   set current_rotator ""
   if { ! [string equal $rotator ""] } {
      if { [catch {RotatorNames::$rotator refinc}] } {
         error "Field orientation \"$rotator\" does not exist"
      } else {
         set current_rotator $rotator
      }
   }
}

itcl::configbody Field::wavelength {
   if { ! [string equal $current_wavelength ""] } {
      WavelengthNames::$current_wavelength refdec
   }
   set current_wavelength ""
   if { ! [string equal $wavelength ""] } {
      if { [catch {WavelengthNames::$wavelength refinc}] } {
         error "Wavelength definition \"$wavelength\" does not exist"
      } else {
         set current_wavelength $wavelength
      }
   }
}

itcl::body Field::add {type name args} {
   switch $type {
      target {
         set targetname [TargetComponent ${targetns}::$name $targetlist]
         $targetname configure -trackratens $trackratens
			$targetname configure -objname $name
         eval [list $targetname] configure $args
         return $targetname
      }
      trackrate {
         return [eval TrackRateComponent [list ${trackratens}::$name] \
               [list $trackratelist] $args]
      }
      default {
         error "\"$type\" is not a valid field component"
      }
   }
}

itcl::body Field::subconfigure {type name args} {
   switch $type {
      target {
         eval [list ${targetns}::$name] configure $args
      }
      trackrate {
         eval [list ${trackratens}::$name] configure $args
      }
      default {
         error "\"$type\" is not a valid field component"
      }
   }
}

itcl::body Field::subinit {type name} {
   switch $type {
      target {
         ${targetns}::$name init
      }
      trackrate {
         ${trackratens}::$name init
      }
      default {
         error "\"$type\" is not a valid field component"
      }
   }
}

itcl::body Field::subcget {type name option} {
   switch $type {
      target {
         return [${targetns}::$name cget $option]
      }
      trackrate {
         return [${trackratens}::$name cget $option]
      }
      default {
         error "\"$type\" is not a valid field component"
      }
   }
}

itcl::body Field::remove {type name} {
   switch $type {
      target {
         itcl::delete object ${targetns}::$name
      }
      trackrate {
         itcl::delete object ${trackratens}::$name
      }
      default {
         error "\"$type\" is not a valid field component"
      }
   }
}

# The posAngle config body sets the rotator option, creating the rotator 
# component if there isn't one that matches the posAngle definition. The
# frame is assumed to be FK5/J2000.

itcl::configbody Field::posAngle {

# Do nothing if posAngle is empty.
   if { ! [string is space $posAngle] } {

# Construct the rotator component name.
      set rotator "$posAngle ([namespace tail $this])"
   
# See if it already exists.
      if { [lsearch -exact [itcl::find objects -class RotatorComponent] \
            ::RotatorNames::$rotator] < 0 } {

# Create it.
         RotatorComponent ::RotatorNames::$rotator ::RotatorList \
               -cosys FK5/J2000 -ipa $posAngle
      }
   }
}

itcl::body Field::addTaggedTarget {{tagPrefix User} {target ""}} {
	if { [string equal $target ""] } {
		set freeId 1
		for {set i 0} {$i < [$targetlist length]} {incr i} {
			if {[string match target* [namespace tail [$targetlist get $i]] ] } {
				set idx [string range [namespace tail [$targetlist get $i]] 6 end]
				if { [string is integer -strict $idx] } {
					if { $idx >= $freeId } {
						set freeId [expr "$idx+1"]
					}
				}
			}
		}
		set target [TargetComponent ${targetns}::target$freeId $targetlist]
		$target init
      $target configure -trackratens $trackratens
		$target configure -objname [namespace tail $target]		
	}
	if { [string equal $tagPrefix Base] } {
		#We force to have only one Base target. If already exists one, it is overwritten
		for {set i 0} {$i < [$taggedTargets length]} {incr i} {
			set tagTarget [$taggedTargets get $i]
			if { [string equal Base [$tagTarget cget -tagPrefix] ] } {
				$tagTarget configure -target $target
				return $tagTarget
			}
		}
		set newTaggedTarget [namespace current]::[TaggedTarget #auto $tagPrefix $target]
	} else {
		if { [string equal $tagPrefix User] } {
			#Check we are not creating a User target for the Science target
			for {set i 0} {$i < [$taggedTargets length]} {incr i} {
				set tagTarget [$taggedTargets get $i]
				if { [string equal Base [$tagTarget cget -tagPrefix] ] && [string equal [$tagTarget cget -target] $target]} {
					return ""
				}
			}
		}
		#Check we are not duplicating an existing tag-target
		for {set i 0} {$i < [$taggedTargets length]} {incr i} {
			set tagTarget [$taggedTargets get $i]
			if { [string equal $tagPrefix [$tagTarget cget -tagPrefix] ] && [string equal [$tagTarget cget -target] $target]} {
				return ""
			}
		}
		set lowestUnusedId 1
		for {set i 0} {$i < [$taggedTargets length]} {incr i} {
			set tag [$taggedTargets get $i]
			if { [string equal [$tag cget -tagPrefix] $tagPrefix ] } {
				set tagSuffix [$tag cget -tagSuffix]
				if { [string is integer -strict  $tagSuffix]} {
					if { $lowestUnusedId <= $tagSuffix } {
						set lowestUnusedId [expr "$tagSuffix + 1"]
					}
				}
			}
		}
		set newTaggedTarget [namespace current]::[TaggedTarget #auto $tagPrefix-$lowestUnusedId $target]
	}
	$taggedTargets insert $newTaggedTarget
	#if it is the first of its kind, set it as default
	if { [getDefaultTarget [$newTaggedTarget cget -tagPrefix]] eq "" } {
		setDefaultTarget $newTaggedTarget
	}
	return $newTaggedTarget
}

itcl::body Field::removeTaggedTarget {taggedTarget} {
	#Base target can not be removed
	if {![string equal [$taggedTarget cget -tagPrefix] Base] && [$taggedTargets index $taggedTarget] != -1 } {
		$taggedTargets remove $taggedTarget
		if { [string equal $taggedTarget [getDefaultTarget [$taggedTarget cget -tagPrefix]]] } {
			clearDefaultTarget [$taggedTarget cget -tagPrefix]
		}
		itcl::delete object $taggedTarget
	}
}

itcl::body Field::cleanTaggedTargets {} {
	set sciencetarget ""
	set pwfs1target ""
	set pwfs2target ""
	set oiwfstarget ""
	set aowfstarget ""
	set ttgs1target ""
	set ttgs2target ""
	set ttgs3target ""
	set odgw1target ""
	set odgw2target ""
	set odgw3target ""
	set odgw4target ""
	set swaptarget ""
	while { [$taggedTargets length] > 0 } {
		set temp [$taggedTargets get 0]
		$taggedTargets remove $temp
		itcl::delete object $temp
	}
}

itcl::body Field::clearDefaultTarget {tag} {
	#undo swap if needed
	if { [getDefaultTarget $tag] eq [getSwapTarget]} {
		clearSwapTarget
	}
	switch $tag {
		CWFS1 -
		CWFS2 -
		CWFS3 -
		ODGW1 -
		ODGW2 -
		ODGW3 -
		ODGW4 {
			incr gcount -1
		}
	}
	switch $tag {
		User {
			#If default User target is unset, science revert to original science target
			#We asume science target was set previoulsy to a User target
			set target ""
			for {set i 0} {$i < [$taggedTargets length]} {incr i} {
				set tagTarget [$taggedTargets get $i]
				if { [string equal Base [$tagTarget cget -tagPrefix] ] } {
					set target [$tagTarget cget -target]
					break
				}
			}
			if {[string equal $target ""]} {
				error "Deselecting User target: Could not revert to Science target, Science target undefined"
			} else {
				set sciencetarget $target
				notify sciencetarget
			}
		}
		PWFS1 {
			set pwfs1target ""
			notify pwfs1target
		}
		PWFS2 {
			set pwfs2target ""
			notify pwfs2target
		}
		OIWFS {
			set oiwfstarget ""
			notify oiwfstarget
		}
		AOWFS {
			set aowfstarget ""
			notify aowfstarget
		}
		CWFS1 {
			set ttgs1target ""
			notify ttgs1target
		}
		CWFS2 {
			set ttgs2target ""
			notify ttgs2target
		}
		CWFS3 {
			set ttgs3target ""
			notify ttgs3target
		}
		ODGW1 {
			set odgw1target ""
			notify odgw1target
		}
		ODGW2 {
			set odgw2target ""
			notify odgw2target
		}
		ODGW3 {
			set odgw3target ""
			notify odgw3target
		}
		ODGW4 {
			set odgw4target ""
			notify odgw4target
		}
	}
}

itcl::body Field::setDefaultTarget {tagtarget} {
	
	if {[string equal $tagtarget ""] || [string equal [$tagtarget cget -tagPrefix] ""]} {
		return
	}
	set tag [$tagtarget cget -tagPrefix]
	
	if {[string equal [$tagtarget cget -target] ""]} {
		clearDefaultTarget $tag
	} else {
		#Don't do anything if it's the same
		if { [getDefaultTarget $tag] eq $tagtarget } {
			return
		}
		#undo swap if needed
		if { [getDefaultTarget $tag] eq [getSwapTarget]} {
			clearSwapTarget
		}
		#Limit GEMS stars to 4
		switch $tag {
			CWFS1 -
			CWFS2 -
			CWFS3 -
			ODGW1 -
			ODGW2 -
			ODGW3 -
			ODGW4 {
				if { [getDefaultTarget $tag] eq "" } {
					if { $gcount < 4 } {
						incr gcount
					} else {
						return
					}
				}
			}
		}
		switch $tag {
			Base -
			User {
				set sciencetarget $tagtarget
				if { [string is space [$tagtarget cget -target]] } {
					set $::Config(tcs.field.sciencetarget,value) $::Config(tcs.field.sciencetarget,anon) 
				} else {					
					set $::Config(tcs.field.sciencetarget,value) [namespace tail [$tagtarget cget -target]]
				}
				notify sciencetarget
			}
			PWFS1 {
				set pwfs1target $tagtarget
				if { [string is space [$tagtarget cget -target]] } {
					set $::Config(tcs.field.pwfs1target,value) $::Config(tcs.field.pwfs1target,anon) 
				} else {					
					set $::Config(tcs.field.pwfs1target,value) [namespace tail [$tagtarget cget -target]]
				}
				notify pwfs1target
			}
			PWFS2 {
				set pwfs2target $tagtarget
				if { [string is space [$tagtarget cget -target]] } {
					set $::Config(tcs.field.pwfs2target,value) $::Config(tcs.field.pwfs2target,anon) 
				} else {					
					set $::Config(tcs.field.pwfs2target,value) [namespace tail [$tagtarget cget -target]]
				}
				notify pwfs2target
			}
			OIWFS {
				set oiwfstarget $tagtarget
				if { [string is space [$tagtarget cget -target]] } {
					set $::Config(tcs.field.oiwfstarget,value) $::Config(tcs.field.oiwfstarget,anon) 
				} else {					
					set $::Config(tcs.field.oiwfstarget,value) [namespace tail [$tagtarget cget -target]]
				}
				notify oiwfstarget
			}
			AOWFS {
				set aowfstarget $tagtarget
				if { [string is space [$tagtarget cget -target]] } {
					set $::Config(tcs.field.aowfstarget,value) $::Config(tcs.field.aowfstarget,anon) 
				} else {					
					set $::Config(tcs.field.aowfstarget,value) [namespace tail [$tagtarget cget -target]]
				}
				notify aowfstarget
			}
			CWFS1 {
				set ttgs1target $tagtarget
				notify ttgs1target
			}
			CWFS2 {
				set ttgs2target $tagtarget
				notify ttgs2target
			}
			CWFS3 {
				set ttgs3target $tagtarget
				notify ttgs3target
			}
			ODGW1 {
				set odgw1target $tagtarget
				notify odgw1target
			}
			ODGW2 {
				set odgw2target $tagtarget
				notify odgw2target
			}
			ODGW3 {
				set odgw3target $tagtarget
				notify odgw3target
			}
			ODGW4 {
				set odgw4target $tagtarget
				notify odgw4target
			}
		}
	}
}

itcl::body Field::getDefaultTarget {tag} {
	set ret ""
	switch $tag {
		Base -
		User {
			set ret $sciencetarget
		}
		PWFS1 {
			set ret $pwfs1target
		}
		PWFS2 {
			set ret $pwfs2target
		}
		OIWFS {
			set ret $oiwfstarget
		}
		AOWFS {
			set ret $aowfstarget
		}
		CWFS1 {
			set ret $ttgs1target
		}
		CWFS2 {
			set ret $ttgs2target
		}
		CWFS3 {
			set ret $ttgs3target
		}
		ODGW1 {
			set ret $odgw1target
		}
		ODGW2 {
			set ret $odgw2target
		}
		ODGW3 {
			set ret $odgw3target
		}
		ODGW4 {
			set ret $odgw4target
		}
	}
	return $ret
}

itcl::body Field::subscribe observer {

# Check that the observer isn't already on the list.
   if { [lsearch -exact $observerList $observer] == -1 } {
# Append the observer to the list.
      lappend observerList $observer
   }
}

itcl::body Field::unsubscribe observer {
# Check that the observer is registered.
   set index [lsearch -exact $observerList $observer]
   if { $index != -1 } {
   	set observerList [lreplace $observerList $index $index]
   }
}

itcl::body Field::notify elementList {
   foreach observer $observerList {
      $observer $elementList
   }	
}

itcl::body Field::setSwapTarget tagtarget {
	global env
	
	set tag [$tagtarget cget -tagPrefix]
	#Check we are swapping with a WFS star
	if { ![string equal $tag Base] && ![string equal $tag User] && \
		[string equal $tagtarget [getDefaultTarget $tag]] && ![string equal $swaptarget $tagtarget]} {
			set swaptarget $tagtarget
			set swapguide "No guiding"
			if {$env(TCC_TCSNAME) == "tcs"} {
				 set guide_wl [.observePanel.frame.control.botframe.wfsconfig getValue HrwfsColFilt]
			} else {
				 set guide_wl [.observePanel.frame.control.botframe.wfsconfig.tabs.canvas.notebook.cs.page1.cs.hrwfs.col get]
			}
			switch $guide_wl {
				"U-red1"  { set swapwavelength "Acq Cam U" }
				"B-blue"  { set swapwavelength "Acq Cam B" }
				"V-green" { set swapwavelength "Acq Cam V" }
				"R-red2"  { set swapwavelength "Acq Cam R" }
				"I-red3"  { set swapwavelength "Acq Cam I" }
				"neutral" { set swapwavelength "Acq Cam neutral" }
				default   { 
					tk_messageBox -icon warning -parent $itk_interior \
						-message "No guide wavelength found ... using 0.5 (Acq Cam neutral)"
					set swapwavelength "Acq Cam neutral"
				}
			}
			notify swaptarget
		}
}

itcl::body Field::clearSwapTarget {} {
	if {![string equal $swaptarget ""]} {
		set swaptarget ""
		notify swaptarget
	}
}

itcl::body Field::getSwapTarget {} {
	return $swaptarget
}
