#+
#  FieldControl <- ComponentControl
#
#  A FieldControl is a ComponentControl widget with widgets for the science
#  and wave-front sensor targets
#
#  Options:
#
#           -component      The name of the component that the control
#                           edits.
#
#  Methods:
#           load name       Copies the contents of the Field object "name"
#                           into the edit controls.
#
#           save name       Stores the contents of the edit controls in the
#                           Field object "name".
#
#           newtarget name type args  Creates a new target in the currently 
#                                     selected field.
#
#  D Terrett 16 Janaury 2004
#
#  Copyright CCLRC
#+

itcl::class FieldControl {
   inherit ComponentControl
   constructor args {}
   destructor {}
   itk_option define -component component Component {}
   public {
      method load {name}
      method reset {}
      method save {name}
      method sync {component name}
      method newtarget {name type args}
#      method swapguide {}
   }
   private {
      method newfieldval {n1 n2 op}
      method pageSelectCB {color}
      variable comp ""
      variable currentname ""
      variable fieldObj ""
      variable curr_guide ""
      variable curr_sciencetarget ""
      variable curr_ns ""
      variable curr_objname ""
      variable curr_guidetarget ""
      variable curr_wl_name ""
      variable curr_wavelength ""
      variable new_wavelength ""
		method onSelectTarget {target} {}
		method deleteTarget {taggedTarget} {}
		method onDeleteTarget {} {}
		method addNewTarget {} {}
		method onAddNewTarget {} {}
		method onSaveTarget {} {}
		method onFieldChange {elementList} {}
		method onAnyAssignedTargetChange {attr} {}
		method onSetDefault {} {}
		method onSwapTarget {} {}
		method store {name} 
   }
}

itk::usual FieldControl {
   keep -borderwidth -cursor -font -highlightthickness -insertborderwidth \
         -insertofftime -insertontime -insertwidth -labelfont -popupcursor \
         -selectborderwidth -textfont -title
}

itcl::body FieldControl::constructor args {

# Expand the selector.
   $itk_component(selector) configure -width 55

   itk_component add display {
      frame $itk_interior.display
   }
   pack $itk_component(display) -side top -anchor c
   set w $itk_component(display)
	
	setTooltip $itk_component(store) "Save changes to the field parameters."
	setTooltip $itk_component(apply) "Configure TCS with the current field values."

# Display of current targets.
#   itk_component add sciencelabel {
#      label $w.sciencelabel -text "SCIENCE Target"
#   }
#   itk_component add sciencename {
#      label $w.sciencename -width 30 -borderwidth 2 -relief sunken
#   }
#   itk_component add pwfs1label {
#      label $w.pwfs1label -text "PWFS1 Target"
#   }
#   itk_component add pwfs1name {
#      label $w.pwfs1name -width 30 -borderwidth 2 -relief sunken
#   }
#   itk_component add pwfs2label {
#      label $w.pwfs2label -text "PWFS2 Target"
#   }
#   itk_component add pwfs2name {
#      label $w.pwfs2name -width 30 -borderwidth 2 -relief sunken
#   }
#   itk_component add oiwfslabel {
#      label $w.oiwfslabel -text "OIWFS target"
#   }
#   itk_component add oiwfsname {
#      label $w.oiwfsname -width 30 -borderwidth 2 -relief sunken
#   }
#   itk_component add aowfslabel {
#      label $w.aowfslabel -text "AOWFS target"
#   }
#   itk_component add aowfsname {
#      label $w.aowfsname -width 30 -borderwidth 2 -relief sunken
#   }
#   grid $itk_component(sciencelabel) $itk_component(sciencename)
#   grid $itk_component(pwfs1label)  $itk_component(pwfs1name)
#   grid $itk_component(pwfs2label) $itk_component(pwfs2name)
#   grid $itk_component(oiwfslabel) $itk_component(oiwfsname)
#   grid $itk_component(aowfslabel) $itk_component(aowfsname)

# Guide, rotator and wavelength selection.
   itk_component add subsel {
      frame $itk_interior.subsel
   }
   set w $itk_component(subsel)
   itk_component add guide {
      SubComponentSelector $w.guide -labeltext "Guide Configuration" \
            -labelpos w -width 30
   }
   itk_component add rotator {
      SubComponentSelector $w.rotator -labeltext "Rotator Configuration" \
            -labelpos w -width 30
   }
   itk_component add wavelength {
      SubComponentSelector $w.wavelength -labeltext "Observing wavelength" \
            -labelpos w -width 30
   }
   pack $itk_component(subsel) -anchor w
   pack $itk_component(guide) $itk_component(rotator) \
         $itk_component(wavelength) -side top -pady 3 -anchor e

# Data entry widgets.
   itk_component add data {
      frame $itk_interior.data
   }
   set w $itk_component(data)

# Swapguide button
	itk_component add swapguide {
		button $w.swapguide -text "Swap Science/Guide Targets" -command [itcl::code $this onSwapTarget]
	}
	setTooltip $itk_component(swapguide) "Temporarily slew telescope to selected target."
	pack $itk_component(swapguide) -side top -pady 3


# Frame for target entry controls.
   itk_component add tarframe {
      frame $w.tarframe -borderwidth 0 -relief flat
   }
   pack $itk_component(tarframe) -expand true -fill x
   set w $itk_component(tarframe)

   itk_component add targets {
      TargetList $w.targets -selectcommand [itcl::code $this onSelectTarget]
   }

   itk_component add trgOpFrm { frame $w.trgOpFrm }


   image create photo ::images::addIcon -file [file join tcclib add.gif]
	image create photo ::images::delIcon -file [file join tcclib remove.gif]
   itk_component add addTrg { button $w.trgOpFrm.add -image ::images::addIcon -command [itcl::code $this onAddNewTarget]}
   itk_component add delTrg { button $w.trgOpFrm.del -image ::images::delIcon -command [itcl::code $this onDeleteTarget]}

	setTooltip $itk_component(addTrg) "Add new target."
	setTooltip $itk_component(delTrg) "Delete selected target."

#   frame $w.trgOpFrm.edBtnFrm
#   image create photo ::images::copyIcon -file [file join tcclib copy.gif]
#   image create photo ::images::pasteIcon -file [file join tcclib paste.gif]
#   image create photo ::images::duplicateIcon -file [file join tcclib duplicate.gif]
#   itk_component add copyTrg { button $w.trgOpFrm.edBtnFrm.copy -image ::images::copyIcon }
#   itk_component add pasteTrg { button $w.trgOpFrm.edBtnFrm.paste -image ::images::pasteIcon }
#   itk_component add duplicateTrg { button $w.trgOpFrm.edBtnFrm.duplicate -image ::images::duplicateIcon }
#
#	pack $w.trgOpFrm.edBtnFrm.copy $w.trgOpFrm.edBtnFrm.paste $w.trgOpFrm.edBtnFrm.duplicate \
#		-side left

	frame $w.trgOpFrm.opBtnFrm
	image create photo ::images::makedefaultIcon -file [file join tcclib star.gif]
	itk_component add makeDefault { button $w.trgOpFrm.opBtnFrm.makedefault -image ::images::makedefaultIcon \
		-command [itcl::code $this onSetDefault]}
	setTooltip $itk_component(makeDefault) "Select/unselect target as the default for science/WFS." 
	image create photo ::images::swapTargetsIcon -file [file join tcclib dep_loop.gif]
#	itk_component add swapTargets { button $w.trgOpFrm.opBtnFrm.swaptargets -image ::images::swapTargetsIcon \
#		-command [itcl::code $this onSwapTarget]}
#	pack $w.trgOpFrm.opBtnFrm.makedefault $w.trgOpFrm.opBtnFrm.swaptargets -side left 
	pack $w.trgOpFrm.opBtnFrm.makedefault -side left 
		

   pack $w.trgOpFrm.add $w.trgOpFrm.del  -side left
#	pack $w.trgOpFrm.add $w.trgOpFrm.del  $w.trgOpFrm.edBtnFrm -side left
#	pack configure $w.trgOpFrm.edBtnFrm -padx 5

	pack $w.trgOpFrm.opBtnFrm -side right 


#   itk_component add hideNonDefaultBtn { button $w.trgOpFrm.hideNonDefaultBtn -text "Show non-defaults" }
#   pack $w.trgOpFrm.hideNonDefaultBtn -side right
   itk_component add trgFrm { iwidgets::labeledframe $w.trgFrm -labeltext "Selected Target" \
	   -labelpos nw -relief groove}

   itk_component add trgDetails { TargetDetail  $w.trgFrm.trgDetails -relief flat \
		-savecommand [itcl::code $this onSaveTarget]}
   grid $w.trgFrm.trgDetails

   pack $itk_component(targets) $itk_component(trgOpFrm) $itk_component(trgFrm) -side top
   pack configure $itk_component(targets) -expand true -fill x
   pack configure $itk_component(trgFrm) -fill x -padx 4
   pack configure $itk_component(trgOpFrm) -anchor w -fill x

# Airmass limit and program ID.
   set w $itk_component(data)
   frame $w.sf
   itk_component add progid {
      iwidgets::entryfield $w.sf.progid -labeltext "Program ID" -width 15
   }
   itk_component add airmass {
      iwidgets::entryfield $w.sf.airmass -labeltext "Airmass limit" -width 8
   }
   pack $itk_component(airmass) $itk_component(progid) -side left \
         -padx 5 -pady 10 -expand yes

   #$itk_component(targets) select Science

   pack $w.sf -side top -pady 3

   pack $itk_component(data) -side left -padx 3 -pady 3 -expand yes -fill y

# Set the current field name to the scratch field.
   set currentname $::Config(tcs.field,anon)

# Define the object description.
   set description "field"

# Turn off geometry propogation once the widget is constructed so that
# re-configuring the notebook widgets doesn't cause the top level window
# to be re-sized.
   #after idle pack propagate $itk_component(tarframe) 0

   eval itk_initialize $args
#   $itk_component(swapguide) configure -text "Swap Science/Guide Targets" -bg "white"
}

itcl::body FieldControl::destructor {} {

# Remove variable trace.
   trace vdelete ::Config($comp,value) w [itcl::code $this newfieldval]
}

itcl::body FieldControl::save {name} {
#+
# Updates the named field object.
#-

# If this is a new field then add each target and track rate from the old 
# field to the new provided that the old field still exists.
   if { ![string equal $currentname $name] && \
         ( [string equal $currentname $::Config(tcs.field,anon)] ||
         [lsearch -exact [itcl::find objects -class FieldComponent] \
         $currentname] >= 0 ) } {

# Copy each track rate first so that they all exist when we configure the
# targets.
      set n [${currentname}TrackRateList length]
      for { set i 0 } { $i < $n } { incr i } {
         set trackrate [${currentname}TrackRateList get $i]
         if { ![string is space $trackrate] } {
            $name add trackrate $trackrate

# Copy all parameters.
            foreach par [$currentname subconfigure trackrate $trackrate] {
               $name subconfigure trackrate $trackrate [lindex $par 0] \
                     [lindex $par 2]
            }

# Set refcount to zero since the new target isn't referenced anywhere yet.
            ${name}TrackRateNames::$trackrate configure -refcount 0
         }
      }

# Copy each target.
      set n [${currentname}TargetList length]
      for { set i 0 } { $i < $n } { incr i } {
         set target [${currentname}TargetList get $i]
         if { ![string is space $target] } {
            $name add target $target

# Copy all parameters.
            foreach par [$currentname subconfigure target $target] {
               $name subconfigure target $target [lindex $par 0] [lindex $par 2]
            }

# Set refcount to zero since the new target isn't referenced anywhere yet.
            ${name}TargetNames::$target configure -refcount 0
         }
      }

# If we have just copied the anonymous field then delete all its targets and
# track rates.
      if { [string equal $currentname $::Config(tcs.field,anon)] } {
         while { [${currentname}TargetList length] > 1 } {
            ${currentname}TargetList remove [${currentname}TargetList get 1]
         }
         while { [${currentname}TrackRateList length] > 1 } {
            ${currentname}TrackRateList remove \
                  [${currentname}TrackRateList get 1]
         }
      }
   }

# Set the remaining components.
	if {[string is space [$name getSwapTarget]]} {
		$name configure -guide [$itk_component(guide) get] \
			-wavelength [$itk_component(wavelength) get]
	} else {
		$name configure -swapguide [$itk_component(guide) get] \
			-swapwavelength [$itk_component(wavelength) get]
	}
   $name configure -rotator [$itk_component(rotator) get] \
		-programid [$itk_component(progid) get] \
		-airmassLimit [$itk_component(airmass) get]

# Record the new current object.
   set currentname $name
}

itcl::body FieldControl::reset {} {
   $itk_component(progid) clear
   $itk_component(airmass) clear
	
	set ::Config(tcs.field.target,value) ""
	
   set ::Config(tcs.field.sciencetarget,value) ""
   set ::Config(tcs.field.pwfs1target,value) ""
   set ::Config(tcs.field.pwfs2target,value) ""
   set ::Config(tcs.field.oiwfstarget,value) ""
   set ::Config(tcs.field.aowfstarget,value) ""
}


#itcl::body FieldControl::swapguide {} {
#   global env
#   if {$curr_guide == ""} {
#	set new_wavelength ""
#	set fieldObj ${::Config(tcs.field,namespace)}::${::Config(tcs.field,value)}
#	#puts "fieldObj: $fieldObj"
#
#	set curr_guide ${::Config(tcs.field.guide,value)}
#   	set curr_sciencetarget ${::Config(tcs.field.sciencetarget,value)}
#	set curr_wl_name ${::Config(tcs.field.wavelength,value)}
#
#	if {![string equal $curr_wl_name ""]} {
#	   set curr_wavelength [::WavelengthNames::$curr_wl_name cget -wavel]
#	}
#	#puts "got current wavelength name: $curr_wl_name , wl: $curr_wavelength"
#	# getting current guide wavelength (from Acquisition Camera)
#	# Create the status acceptor if it doesn't alread exist.
#	if { [catch {sa hrwfs::currStatus info}] } {
#	   epics sa hrwfs::currStatus
#	}
#        if {$env(TCC_TCSNAME) == "tcs"} {
#	    set guide_wl [.observePanel.frame.control.botframe.wfsconfig getValue HrwfsColFilt]
#	} else {
#	    set guide_wl [.observePanel.frame.control.botframe.wfsconfig.tabs.canvas.notebook.cs.page1.cs.hrwfs.col get]
#	}
##	puts "swapguide got guide wl: $guide_wl"
#	switch $guide_wl {
#	   "U-red1"  { set new_wavelength "Acq Cam U" }
#	   "B-blue"  { set new_wavelength "Acq Cam B" }
#	   "V-green" { set new_wavelength "Acq Cam V" }
#	   "R-red2"  { set new_wavelength "Acq Cam R" }
#	   "I-red3"  { set new_wavelength "Acq Cam I" }
#	   "neutral" { set new_wavelength "Acq Cam neutral" }
#	   default   { set new_wavelength "" }
#	}
#       switch $curr_guide {
#	   "P1-P2" -
#	   "P1-OI" -
#	   "AO-P1" -
#	   "P1" {
#	       set curr_guidetarget ${::Config(tcs.field.pwfs1target,value)}
#	       #set ::Config(tcs.field.pwfs1target,value) ""
#	       set lpath "Sky>AC/HR"
#	   }
#	   "P2-OI" -
#	   "P2" {
#	       set curr_guidetarget ${::Config(tcs.field.pwfs2target,value)}
#	       #set ::Config(tcs.field.pwfs2target,value) ""
#	       set lpath "Sky>AC/HR"
#	   }
#	   "OI" {
#	       set curr_guidetarget ${::Config(tcs.field.oiwfstarget,value)}
#	       #set ::Config(tcs.field.oiwfstarget,value) ""
#	       set lpath "Sky>AC/HR"
#	   }
#	   "AO-OI" -
#	   "AO" {
#	       set curr_guidetarget ${::Config(tcs.field.aowfstarget,value)}
#	       #set ::Config(tcs.field.aowfstarget,value) ""
#	       set lpath "Sky>AO>AC/HR"
#	   }
#	   default {
#	       tk_messageBox -icon warning -parent $itk_interior \
#		   -message "Invalid guide configuration ... doing nothing"
#	       # puts "No guidestar set ... do nothing"
#	       set curr_guide ""
#	       set curr_sciencetarget ""
#	       return
#	   }
#	}
#	if {$curr_guidetarget == ""} {
#	   tk_messageBox -icon warning -parent $itk_interior \
#		-message "No guidestar set ... doing nothing"
#	   # puts "No guidestar set ... do nothing"
#	   set curr_guide ""
#	   set curr_sciencetarget ""
#	   set curr_wl_name ""
#	   set curr_wavelength ""
#	   set new_wavelength ""
#	   return
#	}
#   	 #puts "guide conficuration is: $curr_guide"
#   	 #puts "Science target is $curr_sciencetarget, curr_wl_name: $curr_wl_name"
#   	 #puts "Guide target is $curr_guidetarget"
#	
#	if {[string equal $new_wavelength ""]} {
#	   tk_messageBox -icon warning -parent $itk_interior \
#		-message "No guide wavelength found ... using 0.5 (Acq Cam neutral)"
#	   set new_wavelength "Acq Cam neutral"
#	}
#	#puts "guide wl: $guide_wl using wl: $new_wavelength"
#       logactions logmess "guide wl: $guide_wl using wl: $new_wavelength"
#
#   	::WavelengthNames::$new_wavelength configure -set_baffles 0
#	$fieldObj configure -guide "No guiding"
#	$fieldObj configure -sciencetarget $curr_guidetarget
#	$fieldObj configure -wavelength $new_wavelength
#
#	$itk_component(swapguide) configure -text "Revert Science/Guide Targets" -bg red
#
#	# set Light Path Mode (for the A&G)
#	if [winfo exists .observePanel] {
#	    ::.observePanel.frame.control.botframe.mirrors.lpath select $lpath
#	}
#
#	# Append _GUIDE to the object name.
#	# puts "current guide target: $curr_guidetarget"
#	set curr_ns ${::Config(tcs.field.sciencetarget,namespace)}
#	set curr_objname [${curr_ns}::$curr_guidetarget cget -objname]
#	#puts "objname: $curr_objname ns: $curr_ns"
#	#puts "changing name to [list ${curr_objname}_GUIDE]"
#	${curr_ns}::$curr_guidetarget configure -objname [list ${curr_objname}_GUIDE]
#	$this load $fieldObj
#	$this applycmd
#   	::WavelengthNames::$new_wavelength configure -set_baffles 1
#   } else {
#	#puts "swapping back ..."
#	
#	switch $curr_guide {
#	   "P1-P2" -
#	   "P1-OI" -
#	   "AO-P1" -
#	   "P1" {
#		   $fieldObj configure -pwfs1target $curr_guidetarget
#		   set lpath "Sky>Instr"
#	        }
#	   "P2-OI" -
#	   "P2" {
#		   $fieldObj configure -pwfs2target $curr_guidetarget
#		   set lpath "Sky>Instr"
#	        }
#	   "OI" {
#		   $fieldObj configure -oiwfstarget $curr_guidetarget
#		   set lpath "Sky>Instr"
#	        }
#	   "AO-OI" -
#	   "AO" {
#		   $fieldObj configure -aowfstarget $curr_guidetarget
#		   set lpath "Sky>AO>Inst"
#	        }
#	}
#	$fieldObj configure -guide $curr_guide
#	$fieldObj configure -sciencetarget $curr_sciencetarget
#	${curr_ns}::$curr_guidetarget configure -objname ${curr_objname}
#	$fieldObj configure -wavelength $curr_wl_name
#
#	# set Light Path Mode (for the A&G)
#	if [winfo exists .observePanel] {
#	    ::.observePanel.frame.control.botframe.mirrors.lpath select $lpath
#	}
#	
#	#clear temp storage
#	set curr_guide ""
#	set curr_sciencetarget ""
#	set curr_guidetarget ""
#	set curr_wl_name ""
#	set curr_wavelength ""
#	#set fieldObj ""
#	$itk_component(swapguide) configure -text "Swap Science/Guide Targets" -bg "white"
#	$this load $fieldObj
#	$this applycmd
#   }
#}


itcl::body FieldControl::load {name} {
# If the targets are currently swapped, swap back
#   if {($curr_guide != "") && ( ${name} != ${currentname} )} {
#
#	#puts "swapping back because loading new target ..."
#	
#	switch $curr_guide {
#	   "P1-P2" -
#	   "P1-OI" -
#	   "AO-P1" -
#	   "P1" {
#		   $fieldObj configure -pwfs1target $curr_guidetarget
#		   set lpath "Sky>Instr"
#	        }
#	   "P2-OI" -
#	   "P2" {
#		   $fieldObj configure -pwfs2target $curr_guidetarget
#		   set lpath "Sky>Instr"
#	        }
#	   "OI" {
#		   $fieldObj configure -oiwfstarget $curr_guidetarget
#		   set lpath "Sky>Instr"
#	        }
#	   "AO-OI" -
#	   "AO" {
#		   $fieldObj configure -aowfstarget $curr_guidetarget
#		   set lpath "Sky>AO>Inst"
#	        }
#	}
#	$fieldObj configure -guide $curr_guide
#	$fieldObj configure -sciencetarget $curr_sciencetarget
#	${curr_ns}::$curr_guidetarget configure -objname ${curr_objname}
#	$fieldObj configure -wavelength $curr_wl_name
#
#	# set Light Path Mode (for the A&G)
#	if [winfo exists .observePanel] {
#	    ::.observePanel.frame.control.botframe.mirrors.lpath select $lpath
#	}
#	
#	#clear temp storage
#	set curr_guide ""
#	set curr_sciencetarget ""
#	set curr_guidetarget ""
#	set curr_wl_name ""
#	set curr_wavelength ""
#	$itk_component(swapguide) configure -text "Swap Science/Guide Targets" -bg "white"
#    }
	if {( ${name} != ${currentname} ) && ![string is space $currentname ]} {
		$currentname clearSwapTarget
	}

# Copy the contents of the field object selected in the combobox into the 
# edit controls.

# Save the existing name so that we can copy all the targets it
# contains.
	if {![string equal $currentname ""]} {
		$currentname unsubscribe [itcl::code $this onFieldChange]
	}
   set currentname ${name}

# Set the namespace and list to save targets and track rates in.
   foreach target {science pwfs1 pwfs2 oiwfs aowfs} {
      set ::Config($comp.${target}target,namespace) ${name}TargetNames
      set ::Config($comp.${target}target.trackrate,namespace) \
            ${name}TrackRateNames
      set ::Config($comp.${target}target,list) ${name}TargetList
		if {[$name cget -${target}target] ne "" && [[$name cget -${target}target] cget -target] ne "" } {
      	set ::Config($comp.${target}target,value) [namespace tail [[$name cget -${target}target] cget -target]]
		} else {
			set ::Config($comp.${target}target,value) ""
		}
		set ::Config($comp.${target}target.trackrate,list) ${name}TrackRateList
   }
  set ::Config($comp.target,namespace) ${name}TargetNames
  set ::Config($comp.trackrate,namespace) ${name}TrackRateNames
  set ::Config($comp.trackrate2,namespace) ${name}TrackRateNames
  set ::Config($comp.target,list) ${name}TargetList 
  set ::Config($comp.target,value) ""
  set ::Config($comp.taggedtarget,list) [${name} cget -taggedTargets] 
  set ::Config($comp.taggedtarget,value) ""
  set ::Config($comp.trackrate,list) ${name}TrackRateList
  set ::Config($comp.trackrate2,list) ${name}TrackRateList
 
	if { [string is space [$name getSwapTarget]] } {
   	set ::Config($comp.guide,value) [$name cget -guide]
		set ::Config($comp.wavelength,value) [$name cget -wavelength]
	} else {
		set ::Config($comp.guide,value) [$name cget -swapguide]
		set ::Config($comp.wavelength,value) [$name cget -swapwavelength]
	}

	set ::Config($comp.rotator,value) [$name cget -rotator]
   $itk_component(progid) clear
   $itk_component(airmass) clear
   $itk_component(progid) insert end [$name cget -programid]
   $itk_component(airmass) insert end [$name cget -airmassLimit]

	$currentname subscribe [itcl::code $this onFieldChange]
}

itcl::configbody FieldControl::component {
# Remove any existing trace
	if { $comp ne "" } {
   	trace vdelete ::Config($comp,value) w [itcl::code $this newname]
   	set comp ""
	}

   if { $itk_option(-component) != "" } {
       set comp $itk_option(-component)

# Configure the component options of the target controls.
#      foreach target {science pwfs1 pwfs2 oiwfs aowfs} {
#         $itk_component(${target}control) configure \
#               -component $comp.${target}target

# Configure the textvariable option on the target display widgets to the
# config array.
#         $itk_component(${target}name) configure -textvariable \
#               ::Config($comp.${target}target,value)
#      }
      $itk_component(targets) configure -component $comp.taggedtarget
		

# Configure the guide, rotator and wavelength components.
      $itk_component(guide) configure -component $comp.guide
      $itk_component(rotator) configure -component $comp.rotator
      $itk_component(wavelength) configure -component $comp.wavelength

# Set a trace on the component value so that we can detect the selection
# of the scratch object.
      trace variable ::Config($comp,value) w [itcl::code $this newfieldval]

# Set the name of the current component and the list and namespace for
# targets.
      set currentname $::Config($comp,anon)
      foreach target {science pwfs1 pwfs2 oiwfs aowfs} {
         set ::Config($comp.${target}target,list) ${currentname}TargetList
         set ::Config($comp.${target}target,namespace) ${currentname}TargetNames
      }
      set ::Config($comp.target,namespace) ${currentname}TargetNames
		set ::Config($comp.trackrate,namespace) ${currentname}TrackRateNames
		set ::Config($comp.trackrate2,namespace) ${currentname}TrackRateNames
      set ::Config($comp.target,list) ${currentname}TargetList
      set ::Config($comp.taggedtarget,list) [${currentname} cget -taggedTargets]
      set ::Config($comp.trackrate,list) ${currentname}TrackRateList
      set ::Config($comp.trackrate2,list) ${currentname}TrackRateList
     
		set name $::Config($comp.wavelength,value)
   }
}

itcl::body FieldControl::sync {component name} {
return
   switch $component {
      tcs.field.sciencetarget {
         $itk_component(sciencecontrol) sync $name
      }
      tcs.field.pwfs1target {
         $itk_component(pwfs1control) sync $name
      }
      tcs.field.pwfs2target {
         $itk_component(pwfs2control) sync $name
      }
      tcs.field.oiwfstarget {
         $itk_component(oiwfscontrol) sync $name
      }
      tcs.field.aowfstarget {
         $itk_component(aowfscontrol) sync $name
      }
   }
}

itcl::body FieldControl::newfieldval {n1 n2 op} {

# Update the current name if the scratch object is selected. This is required
# because load will not get called.
   if { $::Config($comp,value) == "" } {
      #set currentname $::Config($comp,anon)
		load $::Config($comp,anon)
   }
}

itcl::body FieldControl::newtarget {name type args} {
   if { $::Config(tcs.field,value) == "" } {
      set field $::Config(tcs.field,anon)
   } else {
      set field $::Config(tcs.field,namespace)::$::Config(tcs.field,value)
   }

# See if a name was specified.
   if { $name != "" } {
      set target $name
   } else {
      set target "Unnamed target"
   }

# Remove any existing target with the specified name.
   if { $target == $::Config(tcs.field.sciencetarget,value) } {
      $field configure -sciencetarget ""
   }
   if { $target == $::Config(tcs.field.pwfs1target,value) } {
      $field configure -pwfs1target ""
   }
   if { $target == $::Config(tcs.field.pwfs2target,value) } {
      $field configure -pwfs2target ""
   }
   if { $target == $::Config(tcs.field.oiwfstarget,value) } {
      $field configure -oiwfstarget ""
   }
   if { $target == $::Config(tcs.field.aowfstarget,value) } {
      $field configure -aowfstarget ""
   }
   catch {$field remove target $target}

# Create the new target.
   $field add target $target

# Configure the new target.
   eval [list $field] subconfigure target [list $target] $args

# Make it the specified target and select it.
   if { $type != "" } {
		switch $type {
			sciencetarget {
				$field setDefaultTarget [$field addTaggedTarget Base [$field cget -targetns]::$target]
			}
			pwfs1target {
				$field setDefaultTarget [$field addTaggedTarget PWFS1 [$field cget -targetns]::$target]
			}
			pwfs2target {
				$field setDefaultTarget [$field addTaggedTarget PWFS2 [$field cget -targetns]::$target]
			}
			oiwfstarget {
				$field setDefaultTarget [$field addTaggedTarget OIWFS [$field cget -targetns]::$target]
			}
			aowfstarget {
				$field setDefaultTarget [$field addTaggedTarget AOWFS [$field cget -targetns]::$target]
			}
			ttgs1target {
				$field setDefaultTarget [$field addTaggedTarget CWFS1 [$field cget -targetns]::$target]
			}
			ttgs2target {
				$field setDefaultTarget [$field addTaggedTarget CWFS2 [$field cget -targetns]::$target]
			}
			ttgs3target {
				$field setDefaultTarget [$field addTaggedTarget CWFS3 [$field cget -targetns]::$target]
			}
			odgw1target {
				$field setDefaultTarget [$field addTaggedTarget ODGW1 [$field cget -targetns]::$target]
			}
			odgw2target {
				$field setDefaultTarget [$field addTaggedTarget ODGW2 [$field cget -targetns]::$target]
			}
			odgw3target {
				$field setDefaultTarget [$field addTaggedTarget ODGW3 [$field cget -targetns]::$target]
			}
			odgw4target {
				$field setDefaultTarget [$field addTaggedTarget ODGW4 [$field cget -targetns]::$target]
			}
		}
   }
}

itcl::body FieldControl::pageSelectCB {color} {
return
# Re-configure the notebook background to match the selected page.
   $itk_component(targets) config -background $color -tabbackground $color \
         -backdrop $color

# Restore the colours of the tabs.
#   $itk_component(targets) pageconfigure Science -background \
#         [option get $itk_component(sciencecontrol) background Background] 
#   $itk_component(targets) pageconfigure PWFS1 -background \
#         [option get $itk_component(pwfs1control) background Background] 
#   $itk_component(targets) pageconfigure PWFS2 -background \
#         [option get $itk_component(pwfs2control) background Background] 
#   $itk_component(targets) pageconfigure OIWFS -background \
#         [option get $itk_component(oiwfscontrol) background Background] 
#   $itk_component(targets) pageconfigure AOWFS -background \
#         [option get $itk_component(aowfscontrol) background Background] 
}

itcl::body FieldControl::onSelectTarget {target} {
	$itk_component(trgDetails) load $target
}

itcl::body FieldControl::deleteTarget {target} {
	$::Config(tcs.field,namespace)::$::Config(tcs.field,value) removeTaggedTarget $target
}

itcl::body FieldControl::onDeleteTarget {} {
	set target [$itk_component(targets) getSelected]
	if { ![string equal $target ""] } {
		deleteTarget $target
	}
}

itcl::body FieldControl::addNewTarget {} {
	set currTarget [$itk_component(targets) getSelected]
	if { [string equal $currTarget ""] } {
		set tag Base
	} elseif {[string equal [$currTarget cget -tagPrefix] "Base"]} {
		set tag User
	} else {
		set tag [$currTarget cget -tagPrefix]
	}
	
	return [$::Config(tcs.field,namespace)::$::Config(tcs.field,value) addTaggedTarget $tag]
}

itcl::body FieldControl::onAddNewTarget {} {
	set newTarget [addNewTarget]
	$itk_component(targets) select $newTarget 
}

itcl::body FieldControl::onSaveTarget {} {
	set tagtarget [$itk_component(targets) getSelected]
	if { $tagtarget ne "" } {
		set tagtarget [$itk_component(trgDetails) save $tagtarget]
		$itk_component(targets) refresh
		$itk_component(targets) select $tagtarget
	}
}

itcl::body FieldControl::onFieldChange {elementList} {
	foreach attr $elementList {
		switch -glob $attr {
			*target 	{
				onAnyAssignedTargetChange $attr
				if { $attr eq "swaptarget" } {
					if { [string is space [$::Config(tcs.field,namespace)::$::Config(tcs.field,value) getSwapTarget]] } {
						$itk_component(swapguide) configure -text "Swap Science/Guide Targets" -bg $itk_option(-background)
						setTooltip $itk_component(swapguide) "Temporarily slew telescope to selected target."
						set ::Config($comp.wavelength,value) [$currentname cget -wavelength]
						set ::Config($comp.guide,value) [$currentname cget -guide]
					} else {
						$itk_component(swapguide) configure -text "Revert Science/Guide Targets" -bg red
						setTooltip $itk_component(swapguide) "Revert telescope to Science target."
						set ::Config($comp.wavelength,value) [$currentname cget -swapwavelength]
						set ::Config($comp.guide,value) [$currentname cget -swapguide]
					}
				}
			}
		}
	}
}

itcl::body FieldControl::onAnyAssignedTargetChange {attr} {
	$itk_component(targets) onAnyAssignedTargetChange
}

itcl::body FieldControl::onSetDefault {} {
	set tagtarget [$itk_component(targets) getSelected]
	set tag [$tagtarget cget -tagPrefix]
	set default [$::Config(tcs.field,namespace)::$::Config(tcs.field,value) getDefaultTarget $tag]
	if { $default eq $tagtarget } {
		$::Config(tcs.field,namespace)::$::Config(tcs.field,value) clearDefaultTarget $tag
	} else {
		$::Config(tcs.field,namespace)::$::Config(tcs.field,value) setDefaultTarget $tagtarget
	}
}

itcl::body FieldControl::onSwapTarget {} {
	#Currently, store has the effect of reloading the field, so I must save the
	#current selection beforehand
	set tagtarget [$itk_component(targets) getSelected]
	#Always store windows contents before doing a swap
	#FIXME: It would be better to warn the user of unsaved changes, and give 
	#her/him the option to save or ignore.
	store [$itk_component(selector) get]
	
	set swaptarget [$::Config(tcs.field,namespace)::$::Config(tcs.field,value) getSwapTarget]
	#If the science and guide are swapped, just unswap
	if { ![string is space $swaptarget]} {
		$::Config(tcs.field,namespace)::$::Config(tcs.field,value) clearSwapTarget
	} else {
		set tag [$tagtarget cget -tagPrefix]
		if { $tagtarget eq [$::Config(tcs.field,namespace)::$::Config(tcs.field,value) getDefaultTarget $tag] && \
				$tag ne "Base" && $tag ne "User" } {
			$::Config(tcs.field,namespace)::$::Config(tcs.field,value) setSwapTarget $tagtarget
		}
	}
	#Keep the target selected
	$itk_component(targets) select $tagtarget
	
	#Force an apply of the swapped configuration
	if { $swaptarget ne [$::Config(tcs.field,namespace)::$::Config(tcs.field,value) getSwapTarget] } {
		#set light path
		set swaptarget [$::Config(tcs.field,namespace)::$::Config(tcs.field,value) getSwapTarget]
		if { [string is space $swaptarget]} {
			set guide [$::Config(tcs.field,namespace)::$::Config(tcs.field,value) cget -guide]
			if {$guide ne "" } {
				switch $guide {
					"No guiding" -
				   "P1-P2" -
				   "P1-OI" -
				   "AO-P1" -
				   "P1" -
				   "P2-OI" -
				   "P2" -
				   "OI" {
					   set lpath "Sky>Instr"
					}
				   "AO-OI" -
				   "AO" -
					"GeMS" -
					"GeMS-OI" {
					   set lpath "Sky>AO>Inst"
					}
				}
				if [winfo exists .observePanel] {
				    ::.observePanel.frame.control.botframe.mirrors.lpath select $lpath
				}
			}		
		} else {
			set tag [$swaptarget cget -tagPrefix]
			switch $tag {
			   "AOWFS" {
			       set lpath "Sky>AO>AC/HR"
			   }
			   default {
			       set lpath "Sky>AC/HR"
			   }
			}
			if [winfo exists .observePanel] {
			    ::.observePanel.frame.control.botframe.mirrors.lpath select $lpath
			}	
		}
		#Apply the swapped configuration
		$::Config($comp,namespace)::$::Config($comp,value) apply \
			$itk_option(-component)
		if [catch {cs $itk_option(-apply) post} msg] {
			  tk_messageBox -icon error -parent $itk_interior -message \
					"Error posting command: $itk_option(-system) reports \"$msg\""
		}
	}
}

itcl::body FieldControl::store {name} {
	#Force store of target
	onSaveTarget
	ComponentControl::store $name
}