#+
#  GaosPanel <- Panel
#
#  Implements the GaosPanel widget. A Panel widget with a 
#  GaosControl widget packed into its interior.
#
#  Methods:
#           none
#
#  D Terrett 1 November 2002
#
#  Copyright CCLRC
#+

itcl::class GaosPanel {
   inherit Panel
   constructor args {}
   public {
      method sync {component name} {$itk_component(control) sync $name}
   }
}

itk::usual GaosPanel {
   keep -background -cursor
}

itcl::body GaosPanel::constructor args {

   setWidgetColors $itk_interior \
         $itk_option(-background) $itk_option(-foreground)

	if {[calparam cget -site] eq "CP"} {
		itk_component add control {
			GemsControl $itk_interior.control
		} {
			usual
			rename -component -components components Components
		}
	} else {
	   itk_component add control {
			AltairControl $itk_interior.control
	   } {
	      usual
	      rename -component -components components Components
	   }
	}
   setWidgetColors "$itk_component(menubar) $itk_component(control)" \
         $itk_option(-background) $itk_option(-foreground)

   pack $itk_component(control) -fill both -expand y

   eval itk_initialize $args
}
