#+
#  GemsComponent <- Gems, Component
#
#  A GemsComponent object is a Gems object that is stored in a 
#  configuration list.
#
#
#  Options:
#           none
#
#  Methods:
#           constructor list  Creates the Gems object and puts it onto
#                           "list".
#
#  J Luhrs July 2009
#
#  Copyright CCLRC
#+

itcl::class GemsComponent {
	inherit Component Gems
	constructor {list args} {
		Component::constructor $list
	} {
		eval configure $args
	}
}
