#+
#  Gems <- Paramset
#
#  Implements the Gems class. A Gems object stores various parameters
#  that are needed for the initial setup of GeMS when the telescope is
#  slewed.
#
#  Options:
#
#          -adc                  Use ADC
#
#          -dichroicBeamsplitter Dichroic beamsplitter
#
#          -astrometricMode      Astrometric mode
#
#  Methods:
#          apply comp    Applies the GeMS configuration to the TCS by 
#                        setting the values of the command parameters.
#                        The argument is ignored.
#
#          init          Returns the GeMS object to its initial state.
#
#          save node     Saves the values of the Gaos configuration
#                        to the xml node
#
#  J Luhrs   July 2009
#+

itcl::class Gems {
	inherit Paramset
	constructor {} {}
	destructor {}
public {
	method apply {comp}
	method init {}
	method save {node}
	
	variable adc ""
	variable dichroicBeamsplitter ""
	variable astrometricMode ""
}
private {
	variable gemsSys
}
}

itcl::body Gems::constructor {} {
	set gemsSys [GemsSys::getSingleton]
}

itcl::body Gems::destructor {} {
	init
}

itcl::body Gems::apply {comp} {
	#FIXME: Check configuration commands when the ICD is released.
	logactions logmess "Applying GeMS ADC: (\"$adc\")"
	set aomChange 0
	set mystChange 0
	if { ![string is space $adc] } {
		switch $adc {
			ON {
				cs gems::adcMech set pos In
				cs gems::adcLoop set loop On
				set aomChange 1
			}
			OFF {
				cs gems::adcMech set pos Out
				cs gems::adcLoop set loop Off
				set aomChange 1
			}
			default {
				error "Gems::apply: $adc is not a valid option for ADC"
			}
		}
	}

	logactions logmess "Applying GeMS dichroic beamsplitter: (\"$dichroicBeamsplitter\")"
	if { ![string is space $dichroicBeamsplitter] } {
		switch $dichroicBeamsplitter {
			WAVELENGTH_850NM {
				cs gems::beamSplitter set pos 1
				set aomChange 1
			}
			WAVELENGTH_1UM {
				cs gems::beamSplitter set pos 2
				set aomChange 1
			}
			default {
				error "Gems::apply: $dichroicBeamsplitter is not a valid option for the Dichroic Beamsplitter"
			}
		}
	}
	
	logactions logmess "Applying GeMS astrometric mode: (\"$astrometricMode\")"
	if { ![string is space $astrometricMode] } {
		switch $astrometricMode {
			OFF {
				cs gems::astroMode set mode Off
				set mystChange 1
			}
			REGULAR {
				cs gems::astroMode set mode Regular
				set mystChange 1
			}
			GOOD {
				cs gems::astroMode set mode Good
				set mystChange 1
			}
			BEST {
				cs gems::astroMode set mode Best
				set mystChange 1
			}
			default {
				error "Gems::apply: $astrometricMode is not a valid option for Astrometric Mode"
			}
		}
	}
	if { $aomChange && [catch {cs gems::aomApply post} msg] } {
		error "Error posting commands for GeMS: \"$msg\""
	}
	if { $mystChange && [catch {cs gems::mystApply post} msg]} {
		error "Error posting commands for GeMS (Myst): \"$msg\""
	}
}

itcl::body Gems::save {node} {
	set node [paramset $node gaos]
	param $node adc $adc
	param $node dichroicBeamsplitter $dichroicBeamsplitter
	param $node astrometricMode $astrometricMode
}
	
itcl::body Gems::init {} {
	set adc ""
	set dichroicBeamsplitter ""
	set astrometricMode ""
}
