#+
#  GemsWidget <- itk::Widget
#
#  Widget to specify parameters for a GeMS.
##  Options:
#           none
#
#  Methods:
#           none
#
#  J. Luhrs 04 March 2010
#
#+

itcl::class GemsWidget {
	inherit itk::Widget
	
public {
	constructor {args} {}
	destructor {}
	
	itk_option define -aocontroller aoController AoController {} { init }
	
	method reset {} {}
	method enable {} {}
	method recolor {} {}
	method init {}
}
private {
	variable sys
	variable odgwExpLUT ""
	variable sfsExpLUT ""
	variable ttExpCount 8
	method onGemsChange {reasons}
	method onLGSExpSel {}
}
}

itk::usual GemsWidget {
#	keep -background -cursor -foreground -highlightcolor \
#		-highlightthickness
	keep -background -cursor
}

itcl::body GemsWidget::constructor {args} {
	set sfsExpLUT [calparam cget -sfsExpLUT]
	set odgwExpLUT [calparam cget -odgwExpLUT]
	if { [llength $sfsExpLUT] == 0 } {
		set sfsExpLUT { {15 1} {14 5} {13 10} {12 20} {11 50} }
	}
	if { [llength $odgwExpLUT] == 0 } {
		set odgwExpLUT { {15 50} {14 100} {13 200} {12 400} {11 800} }
	}
	
	itk_component add mainframe {
		frame $itk_interior.mainframe -relief solid -borderwidth 1 -background white 
	} { usual
		ignore -background }
	pack $itk_component(mainframe)
	set w $itk_component(mainframe)
	
	itk_component add gaoson {
		ToggleButton $w.gaoson -text AO -pushedbackground Green -pady 0 -width 9
	} { ignore -width }
	pack $itk_component(gaoson) -side top -anchor n -padx 2 -pady 2
	
	itk_component add buttonframe {
		frame $w.buttonframe -background white 
	} { usual
			ignore -background }
	itk_component add buttonframeright {
		frame $w.buttonframe.right -background white 
	}
	itk_component add buttonframeleft {
		frame $w.buttonframe.left -background white 
	}
	itk_component add ttgsloop {
		ToggleButton $w.buttonframe.left.ttgsloop -text TTGS \
			-pushedbackground Green -pady 0  -width 6
	} { ignore -width }
	itk_component add odgwloop {
		ToggleButton $w.buttonframe.right.odgwloop -text ODGW \
			-pushedbackground Green -pady 0 -width 6
	} { ignore -width }
	itk_component add oiloop {
		ToggleButton $w.buttonframe.left.oiloop -text OI -pushedbackground Green \
			-pady 0 -width 6
	} { ignore -width }
	itk_component add sfsloop {
		ToggleButton $w.buttonframe.right.sfsloop -text SFS -pushedbackground Green \
			-pady 0 -width 6
	} { ignore -width }
	itk_component add lgswfs {
		WfsWidget $w.buttonframe.lgswfs -label LGSWFS -explabel Hz \
			-expvalues [list 50 100 200 500 800] \
			-onexpselect [itcl::code $this onLGSExpSel]
	}
	[$itk_component(lgswfs) component exp] configure -width 4
	$itk_component(lgswfs) switchPush
	$itk_component(lgswfs) configure -onswitchpress "if \{ \[$itk_component(lgswfs) switchGet\] eq \"popped\" \} \{ [$itk_component(lgswfs) component onoff] mark \}"
	pack $itk_component(ttgsloop) $itk_component(oiloop) -side top -anchor w
	pack $itk_component(sfsloop) $itk_component(odgwloop) -side top -anchor e
	pack $itk_component(buttonframeright) -side right
	pack $itk_component(buttonframeleft) -side left
	pack $itk_component(lgswfs) -padx 2 -pady 2
	pack $itk_component(buttonframe) -fill x 
	
	itk_component add canframe {
		frame $w.canframe -background white
	} { usual
			ignore -background }
	itk_component add can1 {
		WfsWidget $w.canframe.can1 -label C1 -explabel Hz -expvalues [list 50 100 200 500 800]
	}
	itk_component add can2 {
		WfsWidget $w.canframe.can2 -label C2 -explabel Hz -expvalues [list 50 100 200 500 800]
	}
	itk_component add can3 {
		WfsWidget $w.canframe.can3 -label C3 -explabel Hz -expvalues [list 50 100 200 500 800]
	}
	set sfsExpList ""
	foreach { pair } $sfsExpLUT {
		lappend sfsExpList "[format %.1f [lindex $pair 0]]([lindex $pair 1])"
	}
	itk_component add sfs {
		WfsWidget $w.canframe.sfs -label SFS -explabel Hz -expvalues $sfsExpList
	}
	[$itk_component(can1) component exp] configure -width 5
	[$itk_component(can2) component exp] configure -width 5 -state disabled
	[$itk_component(can3) component exp] configure -width 5 -state disabled
	[$itk_component(sfs) component exp] configure -width 8 -labelpos nw -labeltext "Mag(f\[Hz\])"
				
	grid $itk_component(can1) $itk_component(can2) -padx 1 -pady 1
	grid $itk_component(can3) $itk_component(sfs) -padx 1 -pady 1
	#grid configure $itk_component(sfs) -padx 0 -pady 0 -sticky se
	pack $itk_component(canframe) -padx 2 -pady 2

	set odgwExpList ""
	foreach { pair } $odgwExpLUT {
		lappend odgwExpList "[format %.1f [lindex $pair 0]]([lindex $pair 1])"
	}
	itk_component add odgwframe {
		frame $w.odgwframe -background white 
	} { usual
			ignore -background }
	itk_component add odgw1 {
		WfsWidget $w.odgwframe.odgw1 -label ODGW1 -explabel Hz -expvalues $odgwExpList
	}
	itk_component add odgw2 {
		WfsWidget $w.odgwframe.odgw2 -label ODGW2 -explabel Hz -expvalues $odgwExpList
	}
	itk_component add odgw3 {
		WfsWidget $w.odgwframe.odgw3 -label ODGW3 -explabel Hz -expvalues $odgwExpList
	}
	itk_component add odgw4 {
		WfsWidget $w.odgwframe.odgw4 -label ODGW4 -explabel Hz -expvalues $odgwExpList
	}
	[$itk_component(odgw1) component exp] configure -width 8 -labelpos nw -labeltext "Mag(f\[Hz\])"
	[$itk_component(odgw2) component exp] configure -width 8 -labelpos nw -labeltext "Mag(f\[Hz\])"
	[$itk_component(odgw3) component exp] configure -width 8 -labelpos nw -labeltext "Mag(f\[Hz\])"
	[$itk_component(odgw4) component exp] configure -width 8 -labelpos nw -labeltext "Mag(f\[Hz\])"
	
	grid $itk_component(odgw1) $itk_component(odgw2) -padx 1 -pady 1
	grid $itk_component(odgw3) $itk_component(odgw4) -padx 1 -pady 1
	pack $itk_component(odgwframe) -padx 2 -pady 2
	
	set sys [GemsSys::getSingleton]
	$sys subscribe [itcl::code $this onGemsChange]

	eval itk_initialize $args
}

itcl::body GemsWidget::destructor {} {
	$sys unsubscribe [itcl::code $this onGemsChange]	
}

itcl::body GemsWidget::init {} {
	if { $itk_option(-aocontroller) ne "" } {
      set lgsExp [$sys getLGSWFSExposure]
      if {[string is double -strict $lgsExp] && $lgsExp > 0 } {
			$itk_component(lgswfs) expSet [expr "1.0 / $lgsExp"]
      } else {
         [$itk_component(lgswfs) component exp] selection set 0
      }
      onLGSExpSel
      
      set ttExp [$sys getTTWFSExposure 1]

      if {[string is integer -strict $ttExp] && $ttExp > 0 && $ttExp <= $ttExpCount } {
         [$itk_component(can1) component exp] selection set [expr "$ttExpCount - $ttExp" ]
	   } else {
	      [$itk_component(can1) component exp] selection set 0
      }
      set ttExp [$sys getTTWFSExposure 2]
      if {[string is integer -strict $ttExp] && $ttExp > 0 && $ttExp <= $ttExpCount } {
         [$itk_component(can2) component exp] selection set [expr "$ttExpCount - $ttExp" ]
      } else {
         [$itk_component(can2) component exp] selection set 0
      }
      set ttExp [$sys getTTWFSExposure 3]  
      if {[string is integer -strict $ttExp] && $ttExp > 0 && $ttExp <= $ttExpCount } {
         [$itk_component(can3) component exp] selection set [expr "$ttExpCount - $ttExp" ]
      } else {
         [$itk_component(can3) component exp] selection set 0
      }
		
		
		#$itk_component(sfs) expSet [$sys getSFSExposure]
		#$itk_component(odgw1) expSet [$sys getODGWExposure 1]
		#$itk_component(odgw2) expSet [$sys getODGWExposure 2]
		#$itk_component(odgw3) expSet [$sys getODGWExposure 3]
		#$itk_component(odgw4) expSet [$sys getODGWExposure 4]
		[$itk_component(sfs) component exp] selection set 0
		[$itk_component(odgw1) component exp] selection set 0
		[$itk_component(odgw2) component exp] selection set 0
		[$itk_component(odgw3) component exp] selection set 0
		[$itk_component(odgw4) component exp] selection set 0
	}
}

itcl::body GemsWidget::reset {} {
	$itk_component(gaoson) pop
   $itk_component(ttgsloop) pop
   $itk_component(oiloop) pop
	$itk_component(sfsloop) pop
	$itk_component(odgwloop) pop
	$itk_component(can1) switchPop
	$itk_component(can2) switchPop
	$itk_component(can3) switchPop
	$itk_component(sfs) switchPop
	$itk_component(odgw1) switchPop
	$itk_component(odgw2) switchPop
	$itk_component(odgw3) switchPop
	$itk_component(odgw4) switchPop
	$itk_component(lgswfs) switchPop
}

itcl::body GemsWidget::recolor {} {
	if { [$itk_option(-aocontroller) state gaos] } {
		#$itk_component(gaoson) configure -status on
		$itk_component(mainframe) configure -background Green
		$itk_component(buttonframe) configure -background Green
   } else {
		#$itk_component(gaoson) configure -status off
		$itk_component(mainframe) configure -background white
		$itk_component(buttonframe) configure -background white
	}
	if { [$itk_option(-aocontroller) state lgswfs] } {
		$itk_component(lgswfs) configure -status on
	} else {
		$itk_component(lgswfs) configure -status off
	}
	set ttFlag 0
	if { [$itk_option(-aocontroller) state ttgs1] } {
		$itk_component(can1) configure -status on
		set ttFlag 1
	} else {
		$itk_component(can1) configure -status off
	}
	if { [$itk_option(-aocontroller) state ttgs2] } {
		$itk_component(can2) configure -status on
		set ttFlag 1
	} else {
		$itk_component(can2) configure -status off
	}
	if { [$itk_option(-aocontroller) state ttgs3] } {
		$itk_component(can3) configure -status on
		set ttFlag 1
	} else {
		$itk_component(can3) configure -status off
	}
	if { [$itk_option(-aocontroller) state sfs] } {
		$itk_component(sfs) configure -status on
	} else {
		$itk_component(sfs) configure -status off
	}
	if { $ttFlag } {
		$itk_component(canframe) configure -background Green
	} else {
		$itk_component(canframe) configure -background white
	}
	set odgwFlag 0
	if { [$itk_option(-aocontroller) state odgw1] } {
		$itk_component(odgw1) configure -status on
		set odgwFlag 1
	} else {
		$itk_component(odgw1) configure -status off
	}
	if { [$itk_option(-aocontroller) state odgw2] } {
		$itk_component(odgw2) configure -status on
		set odgwFlag 1
	} else {
		$itk_component(odgw2) configure -status off
	}
	if { [$itk_option(-aocontroller) state odgw3] } {
		$itk_component(odgw3) configure -status on
		set odgwFlag 1
	} else {
		$itk_component(odgw3) configure -status off
	}
	if { [$itk_option(-aocontroller) state odgw4] } {
		$itk_component(odgw4) configure -status on
		set odgwFlag 1
	} else {
		$itk_component(odgw4) configure -status off
	}
	if { $odgwFlag } {
		$itk_component(odgwframe) configure -background Green
	} else {
		$itk_component(odgwframe) configure -background white
	}
}

itcl::body GemsWidget::enable {} {
	$itk_option(-aocontroller) configure -gaos [expr \"[$itk_component(gaoson) get]\" eq \"pushed\"] 
	$itk_option(-aocontroller) configure -ttgs1Active [expr \"[$itk_component(can1) switchGet]\" eq \"pushed\"] 
	$itk_option(-aocontroller) configure -ttgs1Exp [expr "$ttExpCount - [lindex [[[$itk_component(can1) component exp] component list] curselection ] 0 ]"]
	$itk_option(-aocontroller) configure -ttgs2Active [expr \"[$itk_component(can2) switchGet]\" eq \"pushed\"]
	#$itk_option(-aocontroller) configure -ttgs2Exp	[$itk_component(can2) expGet]
	$itk_option(-aocontroller) configure -ttgs3Active [expr \"[$itk_component(can3) switchGet]\" eq \"pushed\"]
	#$itk_option(-aocontroller) configure -ttgs3Exp	[$itk_component(can3) expGet]

	$itk_option(-aocontroller) configure -sfsActive [expr \"[$itk_component(sfs) switchGet]\" eq \"pushed\"]
	set magexp [$itk_component(sfs) expGet]
	set ind [string first "(" $magexp]
	set sfsFreq [string trim [string range $magexp $ind end] "()"]
	if { ![string is double -strict $sfsFreq] } {
		set sfsFreq 1
	}
	$itk_option(-aocontroller) configure -sfsExp [expr "1.0 / $sfsFreq"]

	$itk_option(-aocontroller) configure -odgw1Active [expr \"[$itk_component(odgw1) switchGet]\" eq \"pushed\"]
	set magexp [$itk_component(odgw1) expGet]
	set ind [string first "(" $magexp]
	$itk_option(-aocontroller) configure -odgw1Mag [string range $magexp 0 [expr $ind-1]]
	set odgw1Freq [string trim [string range $magexp $ind end] "()"]
	if { ![string is double -strict $odgw1Freq] } {
		set odgw1Freq 800
	}
	$itk_option(-aocontroller) configure -odgw1Exp [expr "1.0 / $odgw1Freq"]

	$itk_option(-aocontroller) configure -odgw2Active [expr \"[$itk_component(odgw2) switchGet]\" eq \"pushed\"]
	set magexp [$itk_component(odgw2) expGet]
	set ind [string first "(" $magexp]
	$itk_option(-aocontroller) configure -odgw2Mag [string range $magexp 0 [expr $ind-1]]
	set odgw2Freq [string trim [string range $magexp $ind end] "()"]
	if { ![string is double -strict $odgw2Freq] } {
		set odgw2Freq 800
	}
	$itk_option(-aocontroller) configure -odgw2Exp [expr "1.0 / $odgw2Freq"]

	$itk_option(-aocontroller) configure -odgw3Active [expr \"[$itk_component(odgw3) switchGet]\" eq \"pushed\"]
	set magexp [$itk_component(odgw3) expGet]
	set ind [string first "(" $magexp]
	$itk_option(-aocontroller) configure -odgw3Mag [string range $magexp 0 [expr $ind-1]]
	set odgw3Freq [string trim [string range $magexp $ind end] "()"]
	if { ![string is double -strict $odgw3Freq] } {
		set odgw3Freq 800
	}
	$itk_option(-aocontroller) configure -odgw3Exp [expr "1.0 / $odgw3Freq"]

	$itk_option(-aocontroller) configure -odgw4Active [expr \"[$itk_component(odgw4) switchGet]\" eq \"pushed\"]
	set magexp [$itk_component(odgw4) expGet]
	set ind [string first "(" $magexp]
	$itk_option(-aocontroller) configure -odgw4Mag [string range $magexp 0 [expr $ind-1]]
	set odgw4Freq [string trim [string range $magexp $ind end] "()"]
	if { ![string is double -strict $odgw4Freq] } {
		set odgw4Freq 800
	}
	$itk_option(-aocontroller) configure -odgw4Exp [expr "1.0 / $odgw4Freq"]

	$itk_option(-aocontroller) configure -lwfsActive [expr \"[$itk_component(lgswfs) switchGet]\" eq \"pushed\"]
	$itk_option(-aocontroller) configure -lwfsFreq [expr "1.0 / [$itk_component(lgswfs) expGet]" ]
	$itk_option(-aocontroller) configure -lwfsLoop [expr \"[$itk_component(lgswfs) switchGet]\" eq \"pushed\"]
	$itk_option(-aocontroller) configure -oigsLoop [expr \"[$itk_component(oiloop) get]\" eq \"pushed\"]
	$itk_option(-aocontroller) configure -odgwLoop [expr \"[$itk_component(odgwloop) get]\" eq \"pushed\"]
	$itk_option(-aocontroller) configure -ttgsLoop [expr \"[$itk_component(ttgsloop) get]\" eq \"pushed\"]
	$itk_option(-aocontroller) configure -sfsLoop [expr \"[$itk_component(sfsloop) get]\" eq \"pushed\"]

	#$itk_option(-aocontroller) configure -oigsActive [expr \"[$itk_component(can1) switchGet]\" eq \"pushed\"]
	#$itk_option(-aocontroller) configure -oigsMag [$itk_component(can1) expGet]
}

itcl::body GemsWidget::onGemsChange {reasons} {
	set shouldRecolor 0
	foreach reason $reasons {
		switch -glob $reason {
		gemsActive -
		ttwfsActive* -
		odgwActive* -
		sfsActive -
		lgswfsActive {
			set shouldRecolor 1
			break
		}
		}
	}
	if { $shouldRecolor } {
		recolor
	}
}

itcl::body GemsWidget::onLGSExpSel {} {
	set lgsExp [$itk_component(lgswfs) expGet]
	set canExpList ""
	for { set i $ttExpCount } { $i > 0 } { incr i -1 } {
		lappend canExpList [format "%.1f" [expr "double($lgsExp) / $i"]]
	}
	set oldSel [lindex [[[$itk_component(can1) component exp] component list] curselection ] 0 ]
	for { set i 1 } { $i <= 3 } { incr i } {
		$itk_component(can$i) configure -expvalues $canExpList
		if { [string is integer -strict $oldSel] } {
			if { $i > 1 } { [$itk_component(can$i) component exp] configure -state normal }
			[$itk_component(can$i) component exp] selection set $oldSel
			if { $i > 1 } { [$itk_component(can$i) component exp] configure -state disabled }
		}
	}
}