#+
#  Gems <- Paramset
#
#  Implements the Gems class. A Gems object stores various parameters
#  that are needed for the initial setup of GeMS when the telescope is
#  slewed.
#
#  Options:
#
#          -adc                  Use ADC
#
#          -dichroicBeamsplitter Dichroic beamsplitter
#
#          -astrometricMode      Astrometric mode
#
#  Methods:
#          apply comp    Applies the GeMS configuration to the TCS by 
#                        setting the values of the command parameters.
#                        The argument is ignored.
#
#          init          Returns the GeMS object to its initial state.
#
#          save node     Saves the values of the Gaos configuration
#                        to the xml node
#
#  J Luhrs   July 2009
#+

itcl::class Gems {
	inherit Paramset
	constructor {} {}
	destructor {}
public {
	method apply {comp}
	method init {}
	method save {node}
	
	variable adc ""
	variable dichroicBeamsplitter ""
	variable astrometricMode ""
}
private {
	variable gemsSys
	variable lastError ""
	
	method waitFor {timeout outCondition}
	method waitForCmdIdle {{timeout 1000}}
	method waitForCmdComplete {idleTimeout settledTimeout settledCond timeoutMsg}
}
}

itcl::body Gems::constructor {} {
	init
	set gemsSys [GemsSys::getSingleton]
}

itcl::body Gems::destructor {} {
	init
}

itcl::body Gems::apply {comp} {
   if { $::Flags(ignoreao) } {
      logactions logmess "GeMS AO configuration skipped."
   } else {
      logactions logmess "Applying GeMS ADC: (\"$adc\")"
   	if { ![string is space $adc] } {
   		switch $adc {
   			ON {
   				$gemsSys moveADC In
   				if { [waitForCmdComplete 40000 40000 {expr {[$gemsSys getADCPos] eq "In"}} "ADC to reach In position"] } {
   					logactions logmess "Error applying GeMS ADC: $lastError"
   				}
   				$gemsSys startADC
   				if { [waitForCmdComplete 1000 10000 {expr {[$gemsSys getADCLoopState] eq "CLOSED"}} "ADC loop to close"] } {
   					logactions logmess "Error applying GeMS ADC: $lastError"
   				}
   			}
   			OFF {
   				$gemsSys stopADC
   				if { [waitForCmdComplete 1000 10000 {expr {[$gemsSys getADCLoopState] eq "OPEN"}} "ADC loop to open"] } {
   					logactions logmess "Error applying GeMS ADC: $lastError"
   				}
   				$gemsSys moveADC Out
   				if { [waitForCmdComplete 40000 40000 {expr {[$gemsSys getADCPos] eq "Out"}} "ADC to reach Out position"] } {
   					logactions logmess "Error applying GeMS ADC: $lastError"
   				}
   			}
   			default {
   				error "Gems::apply: $adc is not a valid option for ADC"
   			}
   		}
   	}
   
   	logactions logmess "Applying GeMS dichroic beamsplitter: (\"$dichroicBeamsplitter\")"
   	if { ![string is space $dichroicBeamsplitter] } {
   		set pos ""
   		switch $dichroicBeamsplitter {
   			WAVELENGTH_850NM {
   				set pos 1
   			}
   			WAVELENGTH_1UM {
   				set pos 2
   			}
   			default {
   				error "Gems::apply: $dichroicBeamsplitter is not a valid option for the Dichroic Beamsplitter"
   			}
   		}
   		if { $pos ne "" } {
   			$gemsSys moveBeamSplitter $pos
   			if { [waitForCmdComplete 40000 40000 "expr \{\[$gemsSys getBeamSplitterPos\] eq \"$pos\" \}" "beamsplitter to reach position $pos"] } {
   				logactions logmess "Error applying GeMS beamsplitter: $lastError"
   			}
   		}
   	}
   	
   	logactions logmess "Applying GeMS astrometric mode: (\"$astrometricMode\")"
   	if { ![string is space $astrometricMode] } {
   		set mode ""
   		switch $astrometricMode {
   			OFF {
   				set mode None
   			}
   			REGULAR {
   				set mode Regular
   			}
   			GOOD {
   				set mode Good
   			}
   			BEST {
   				set mode Best
   			}
   			default {
   				error "Gems::apply: $astrometricMode is not a valid option for Astrometric Mode"
   			}
   		}
   		if { $mode ne "" } {
   			$gemsSys setAstroMode $mode
   			if { [waitForCmdComplete 1000 1000 {expr 1} "Astrometry mode to change to $mode"] } {
   				logactions logmess "Error applying Astrometry mode: $lastError"
   			}
   		}
   	}
   }
}

itcl::body Gems::save {node} {
	set node [paramset $node gaos]
	param $node adc $adc
	param $node dichroicBeamsplitter $dichroicBeamsplitter
	param $node astrometricMode $astrometricMode
}
	
itcl::body Gems::init {} {
	set adc "OFF"
	set dichroicBeamsplitter "WAVELENGTH_850NM"
	set astrometricMode "OFF"
}

itcl::body Gems::waitFor {timeout outCondition} {
	set elapsedTime 0
	while {$timeout==0 || $elapsedTime<$timeout} {
		if {[eval $outCondition]} {
			return ok
		}
		after 100
		set elapsedTime [expr $elapsedTime + 100]
		update
	}
	return timeout
}

itcl::body Gems::waitForCmdIdle {{timeout 1000}} {
	set elapsedTime 0
	while {$timeout==0 || $elapsedTime<$timeout} {
		if {[$gemsSys getCommandState] eq "IDLE"} {
			return ok
		} elseif {[$gemsSys getCommandState] eq "ERROR"} {
			set lastError [$gemsSys getLastError]
			return error
		}
		after 100
		set elapsedTime [expr $elapsedTime + 100]
		update
	}
	return timeout
}

itcl::body Gems::waitForCmdComplete {idleTimeout settledTimeout settledCond timeoutMsg} {
	set result [waitForCmdIdle $idleTimeout]
	if {$result eq "error"} {
		return 1
	} elseif {$result eq "timeout" || [waitFor $settledTimeout $settledCond] eq "timeout" } {
		set lastError "Timed out waiting for $timeoutMsg"
		return 1
	}
	return 0
}
