#+
#
# This class keeps the GeMS AO settings and sequences its commands.
#
# J Luhrs 01 April 2009
#
#  $Id: Exp $
#+

itcl::class GemsAO {
public {
#	variable gaos 0
	variable ttgs1Active 0
	variable ttgs1Exp	10
	variable ttgs2Active 0
	variable ttgs2Exp	10
	variable ttgs3Active 0
	variable ttgs3Exp	10
	variable sfsActive 0
	variable sfsExp 10
	variable odgw1Active 0
	variable odgw1Exp	10
	variable odgw2Active 0
	variable odgw2Exp	10
	variable odgw3Active 0
	variable odgw3Exp	10
	variable odgw4Active 0
	variable odgw4Exp	10
	variable ttgs1Mag	10
	variable ttgs2Mag	10
	variable ttgs3Mag	10
	variable odgw1Mag 10
	variable odgw2Mag 10
	variable odgw3Mag 10
	variable odgw4Mag 10
	variable oigsMag 10
	variable lwfsActive 0
	variable lwfsFreq 100
	variable lwfsLoop 0
	variable flexLoop 0
	variable aniLoop 0
	variable ttLoop 0
	variable sfsLoop 0
	
	variable lastError ""
	
	method enable {}
	method disable {}
	method state {var}

	constructor {} {}

	method configure {args} { if {[llength $args] > 0 } {logactions logmess "$this configure $args"} ; eval _itcl_config $args }
}
private {
	variable sys
	method waitFor {timeout outCondition}
	method waitForCmdIdle {{timeout 1000}}
	method waitForCmdComplete {idleTimeout settledTimeout settledCond timeoutMsg}
	method startWFS {}
	method startTTGS {}
	method startODGW {}
	method stopWFS {}
	method stopTTGS {}
	method stopODGW {}
   method setupLoops {}
	method disableWFS
	method disableTTGS {}
	method disableODGW {}
	method disableLoops {}
	method defineTTSources {}
	method _itcl_config {option args} \
		@itcl-builtin-configure
}
}

itcl::body GemsAO::constructor {} {
	set sys [GemsSys::getSingleton]
}

itcl::body GemsAO::enable {} {
	set lastError ""
	#WFS are enabled first
	if { [startWFS] } {
		return 1
	}
   
   #Close/open loops
   if { [setupLoops] } {
     return 1
   }
   
	#And finally disable WFS
	if { [stopWFS] } {
		return 1
	}	

	return 0
}

itcl::body GemsAO::disable {} {
	set errMsg ""
	set ret 0
	
	if  { [disableLoops] } {
		set ret 1
		set errMsg $lastError
	}
	if  { [disableWFS] } {
		set ret 1
		set errMsg "$errMsg\n$lastError"
	}
	
	set lastError $errMsg
	return $ret
}

itcl::body GemsAO::waitFor {timeout outCondition} {
	set elapsedTime 0
	while {$timeout==0 || $elapsedTime<$timeout} {
		if {[eval $outCondition]} {
			return ok
		}
		after 100
		set elapsedTime [expr $elapsedTime + 100]
		update
	}
	return timeout
}

itcl::body GemsAO::waitForCmdIdle {{timeout 1000}} {
	set elapsedTime 0
	while {$timeout==0 || $elapsedTime<$timeout} {
		if {[$sys getCommandState] eq "IDLE"} {
			return ok
		} elseif {[$sys getCommandState] eq "ERROR"} {
			set lastError [$sys getLastError]
			return error
		}
		after 100
		set elapsedTime [expr $elapsedTime + 100]
		update
	}
	return timeout
}

itcl::body GemsAO::waitForCmdComplete {idleTimeout settledTimeout settledCond timeoutMsg} {
	set result [waitForCmdIdle $idleTimeout]
	if {$result eq "error"} {
		return 1
	} elseif {$result eq "timeout" || [waitFor $settledTimeout $settledCond] eq "timeout" } {
		set lastError "Timed out waiting for $timeoutMsg"
		return 1
	}
	return 0
}

itcl::body GemsAO::startWFS {} {
	if { [startTTGS] } {
		return 1
	}
	if { $sfsActive } {
		if { $sfsExp ne "" && $sfsExp != [$sys getSFSExposure] } {
			$sys setSFSExposure $sfsExp
			if { [waitForCmdComplete 1000 1000 "expr 1" "SFS exposure setup"] } {
				return 1
			}
		}
		if { ![state sfs] } {
			$sys startSFS
			if { [waitForCmdComplete 1000 2000 "state sfs" "SFS to go ON"] } {
				return 1
			}
		}
	}
	if { $lwfsActive} {
		if {$lwfsFreq ne "" && $lwfsFreq != [$sys getLGSWFSExposure]} {
			$sys setLGSWFSExposure $lwfsFreq 
			if { [waitForCmdComplete 1000 1000 "expr 1" "LGSWFS exposure setup"] } {
				return 1
			}			
		}
		if { ![state lgswfs] } {
			$sys startLGSWFS
			if { [waitForCmdComplete 1000 2000 "state lgswfs" "LGSWFS to go ON"] } {
				return 1
			}
		}
	}
	if { [startODGW] } {
		return 1
	}
	return 0
}

itcl::body GemsAO::startTTGS {} {
	if { $ttgs1Active || $ttgs2Active || $ttgs3Active } {
		if {[set ttgs1Exp] ne "" && [set ttgs1Exp] != [$sys getTTWFSExposure 1]} {
			#TODO: The three canopus use the same value, so I'll use only ttgs1Exp
			$sys setTTWFSExposure 1 [set ttgs1Exp]
			if { [waitForCmdComplete 1000 1000 "expr 1" "TTWFS exposure setup"] } {
				return 1
			}
		}
      set idList ""
      set testExp "expr \{ 1"
      for {set i 1} {$i <= 3} { incr i} {
         if { [set ttgs${i}Active] && ![state ttgs${i}] } {
            lappend idList $i
            set testExp "$testExp && \[ state ttgs${i} \]"
         }
      }
      set testExp "$testExp \}"
      
		if { [llength $idList] > 0 } {
			$sys startTTWFS $idList
			if { [waitForCmdComplete 1000 2000 $testExp "TTWFS $idList to go ON"] } {
				return 1
			}
		}
	}
	return 0	
}

itcl::body GemsAO::startODGW {} {
   set idList ""
   set testExp "expr \{ 1"
   for {set i 1} {$i <= 4} { incr i} {
		if { [set odgw${i}Active] } {
			if {[set odgw${i}Exp] ne "" && [set odgw${i}Exp] != [$sys getODGWExposure $i]} {
				$sys setODGWExposure $i [set odgw${i}Exp] 
				if { [waitForCmdComplete 10000 10000 "expr 1" "ODGW${i} exposure setup"] } {
					return 1
				}
			}
			if { ![state odgw${i}] } {
            lappend idList $i
            set testExp "$testExp && \[ state odgw${i} \]"
			}
		}
   }
   set testExp "$testExp \}"
   if { [llength $idList] > 0 } {
		$sys startODGW $idList
      if { [waitForCmdComplete 10000 10000 $testExp "ODGW $idList to go ON"] } {
         return 1
      }
   }
	return 0	
}

itcl::body GemsAO::stopWFS {} {
	set errMsg ""
	set ret 0
	
	if { [stopODGW] } {
		set ret 1
		set errMsg "$errMsg\n$lastError"
	}
	
	if { !$lwfsActive && [state lgswfs] } {
		$sys stopLGSWFS
		if {[waitForCmdComplete 1000 2000 {expr ![state lgswfs]} "LGSWFS to go OFF"]} {
			set ret 1
			set errMsg "$errMsg\n$lastError"
		}
	}
	if { !$sfsActive && [state sfs] } {
		$sys stopSFS
		if {[waitForCmdComplete 1000 15000 {expr ![state sfs]} "SFS to go OFF"]} {
			set ret 1
			set errMsg "$errMsg\n$lastError"
		}
	}
	if { [stopTTGS] } {
		set ret 1
		set errMsg "$errMsg\n$lastError"
	}
	set lastError $errMsg
	return $ret
}

itcl::body GemsAO::stopTTGS {} {
   set idList ""
   set testExp "expr \{ 1"
   for {set i 1} {$i <= 3} { incr i} {
      if { ![set ttgs${i}Active] && [state ttgs${i}] } {
         lappend idList $i
         set testExp "$testExp && !\[ state ttgs${i} \]"
      }
   }
   set testExp "$testExp \}"
   
   if { [llength $idList] > 0 } {
      $sys stopTTWFS $idList
      if { [waitForCmdComplete 1000 2000 $testExp "TTWFS $idList to go OFF"] } {
         return 1
      }
   }
   
	return 0
}

itcl::body GemsAO::stopODGW {} {
   set idList ""
   set testExp "expr \{ 1"
   for {set i 1} {$i <= 4} { incr i} {
      if { ![set odgw${i}Active] && [state odgw${i}] } {
         lappend idList $i
         set testExp "$testExp && !\[ state odgw${i} \]"
      }
   }
   set testExp "$testExp \}"
   if { [llength $idList] > 0 } {
      $sys stopODGW $idList
      if { [waitForCmdComplete 10000 10000 $testExp "ODGW $idList to go OFF"] } {
         return 1
      }
   }
   return 0 
}

itcl::body GemsAO::disableWFS {} {
	set errMsg ""
	set ret 0
	
	if { [disableODGW] } {
		set ret 1
		set errMsg "$errMsg\n$lastError"
	}
#	if { [state lgswfs] } {
#		$sys stopLGSWFS
#		if {[waitForCmdComplete 1000 2000 {expr ![state lgswfs]} "LGSWFS to go OFF"]} {
#			set ret 1
#			set errMsg "$errMsg\n$lastError"
#		}
#	}
	if { [state sfs] } {
		$sys stopSFS
		if {[waitForCmdComplete 1000 15000 {expr ![state sfs]} "SFS to go OFF"]} {
			set ret 1
			set errMsg "$errMsg\n$lastError"
		}
	}
	if { [disableTTGS] } {
		set ret 1
		set errMsg "$errMsg\n$lastError"
	}
	set lastError $errMsg
	return $ret
}

itcl::body GemsAO::disableTTGS {} {
   set idList ""
   set testExp "expr \{ 1"
   for {set i 1} {$i <= 3} { incr i} {
      if { [state ttgs${i}] } {
         lappend idList $i
         set testExp "$testExp && !\[ state ttgs${i} \]"
      }
   }
   set testExp "$testExp \}"
   
   if { [llength $idList] > 0 } {
      $sys stopTTWFS $idList
      if { [waitForCmdComplete 1000 2000 $testExp "TTWFS $idList to go OFF"] } {
         return 1
      }
   }
   
   return 0
}

itcl::body GemsAO::disableODGW {} {
   set idList ""
   set testExp "expr \{ 1"
   for {set i 1} {$i <= 4} { incr i} {
      if { [state odgw${i}] } {
         lappend idList $i
         set testExp "$testExp && !\[ state odgw${i} \]"
      }
   }
   set testExp "$testExp \}"
   if { [llength $idList] > 0 } {
      $sys stopODGW $idList
      if { [waitForCmdComplete 10000 10000 $testExp "ODGW $idList to go OFF"] } {
         return 1
      }
   }
   return 0 
}

itcl::body GemsAO::setupLoops {} {
   set loopList {}
   set sources {}
   set testExp "expr \{ 1"

   #Set TT loop sources
   set sources [defineTTSources]

   if { [AO cget -m1source] eq "GAOS" } {
      lappend loopList m1
      set testExp "$testExp && \[ state m1Offload \]"
   } else {
      set testExp "$testExp && !\[ state m1Offload \]"
   }
   if { [AO cget -aoguide] eq "On" } {
      lappend loopList m2
      set testExp "$testExp && \[ state m2Offload \]"
   } else {
      set testExp "$testExp && !\[ state m2Offload \]"
   }
   if { $lwfsLoop } {
      lappend loopList lwfs
      set testExp "$testExp && \[ state lwfsLoop \]"
   } else {
      set testExp "$testExp && !\[ state lwfsLoop \]"
   }
   if { $ttLoop } {
      lappend loopList tt
      set testExp "$testExp && \[ state ttLoop \]"
   } else {
      set testExp "$testExp && !\[ state ttLoop \]"
   }
   if { $sfsLoop } {
      lappend loopList sfs
      set testExp "$testExp && \[ state sfsLoop \]"
   } else {
      set testExp "$testExp && !\[ state sfsLoop \]"
   }
   if { $flexLoop } {
      lappend loopList flex
      set testExp "$testExp && \[ state flexLoop \]"
   } else {
      set testExp "$testExp && !\[ state flexLoop \]"
   }
   if { $aniLoop } {
      lappend loopList ani
      set testExp "$testExp && \[ state aniLoop \]"
   } else {
      set testExp "$testExp && !\[ state aniLoop \]"
   }
   if { [AO cget -crsource] eq "GAOS" } {
      lappend loopList rot
      set testExp "$testExp && \[ state rotOffload \]"
   } else {
      set testExp "$testExp && !\[ state rotOffload \]"
   }

   set testExp "$testExp \}"
   $sys setupLoops $loopList $sources
   if { [waitForCmdComplete 10000 150000 $testExp "GeMS loops setup"] } {
      return 1
   } else {
      return 0
   }
}

itcl::body GemsAO::disableLoops {} {
   set testExp "expr \{ 1"
   set testExp "$testExp && !\[ state m1Offload \]"
   set testExp "$testExp && !\[ state m2Offload \]"
   set testExp "$testExp && !\[ state lwfsLoop \]"
   set testExp "$testExp && !\[ state ttLoop \]"
   set testExp "$testExp && !\[ state sfsLoop \]"
   set testExp "$testExp && !\[ state flexLoop \]"
   set testExp "$testExp && !\[ state aniLoop \]"
   set testExp "$testExp && !\[ state rotOffload \]"
   set testExp "$testExp \}"
   
   $sys setupLoops {} {}
   if { [waitForCmdComplete 5000 60000 $testExp ""] } {
      return 1
   } else {
      return 0
   }
}

itcl::body GemsAO::state {var} {
	switch $var {
	astrometry { return [expr {[$sys getAstrometryState] eq "READY"}] }
	astromode  { return [$sys getAstroMode] }
	m1Offload  { return [expr {[$sys getM1OffloadState] eq "START"}] }
	m2Offload  { return [expr {[$sys getM2OffloadState] eq "START"}] }
	lwfsLoop   { return [expr {[$sys getLGSLoopState] eq "CLOSED"}] }
	ttLoop     { return [expr {[$sys getTTLoopState] eq "CLOSED"}] }
	sfsLoop    { return [expr {[$sys getFocLoopState] eq "CLOSED"}] }
	aniLoop    { return [expr {[$sys getAniLoopState] eq "CLOSED"}] }
	rotOffload { return [expr {[$sys getRotOffloadState] eq "START"}] }
	flexLoop   { return [expr {[$sys getFlexLoopState] eq "CLOSED"}] }
	lgswfs     { return [expr {[$sys getLGSWFSActive] eq "ON"}] }
	sfs        { return [expr {[$sys getSFSActive] eq "ON"}] }
	ttgs1      { return [expr {[$sys getTTWFSActive 1] eq "ON"}] }
	ttgs2      { return [expr {[$sys getTTWFSActive 2] eq "ON"}] }
	ttgs3      { return [expr {[$sys getTTWFSActive 3] eq "ON"}] }
	odgw1      { return [expr {[$sys getODGWActive 1] eq "ON"}] }
	odgw2      { return [expr {[$sys getODGWActive 2] eq "ON"}] }
	odgw3      { return [expr {[$sys getODGWActive 3] eq "ON"}] }
	odgw4      { return [expr {[$sys getODGWActive 4] eq "ON"}] }
	aoSettled  { return [expr {[$sys getLoopsState] eq "READY"}] }
	}
	return 0
}

itcl::body GemsAO::defineTTSources {} {
	set sources ""
	
	if { $ttLoop || $aniLoop } {
   	if { $ttgs1Active } {
   		lappend sources ttgs1 $ttgs1Mag
   	}
   	if { $ttgs2Active } {
   		lappend sources ttgs2 $ttgs2Mag
   	}
   	if { $ttgs3Active } {
   		lappend sources ttgs3 $ttgs3Mag
   	}
   	if { $odgw1Active } {
   		lappend sources odgw1 $odgw1Mag
   	}
   	if { $odgw2Active } {
   		lappend sources odgw2 $odgw2Mag
   	}
   	if { $odgw3Active } {
   		lappend sources odgw3 $odgw3Mag
   	}
   	if { $odgw4Active } {
   		lappend sources odgw4 $odgw4Mag
   	}
	}
	if { $flexLoop && [AO state oiwfs] } {
		lappend sources oigs $oigsMag
	}
	
	return $sources
}