#+
#  GemsWidget <- itk::Widget
#
#  Widget to specify parameters for a GeMS.
##  Options:
#           none
#
#  Methods:
#           none
#
#  J. Luhrs 04 March 2010
#
#+

itcl::class GemsWidget {
   inherit itk::Widget

   public {
      constructor {args} {}
      destructor {}

      itk_option define -aocontroller aoController AoController {} { init }
      itk_option define -state state State {}
      itk_option define -layoutchangecmd layoutChangeCmd LayoutChangeCmd {}

      method reset {} {}
      method enable {} {}
      method recolor {} {}
      method init {}

      method getMagnetPoint { type }
   }
   private {
      variable sys
      variable odgwExpLUT ""
      method onGemsChange {reasons}

      variable linkedField ""
      method onFieldChange {name1 name2 op}
      method onTargetChange {changes}
      method clearFieldSubscription {}
      method setFieldSubscription {fieldname }
      method onTTGSChange {id}
      method onODGWChange {id}
      method onTTODGWxPress { op }
      method onTTCxPress { op }
      method calcMagForWavelength {wavel mags brightness}
      method calcMagForTarget {wavel target }
      method lookup { val lut {index 0} }
      method nearest { val lut {index 0} }

      method onLayoutChange {}
   }
}

itk::usual GemsWidget {
#	keep -background -cursor -foreground -highlightcolor \
#		-highlightthickness
	keep -background -cursor -state
}

itcl::body GemsWidget::constructor {args} {
   set odgwExpLUT [calparam cget -odgwExpLUT]
   if {[llength $odgwExpLUT] == 0 } {
      set odgwExpLUT { {15 0.02} {14 0.01} {13 0.005} {12 0.0025} {11 0.00125} }
   }

   itk_component add mainframe {
		frame $itk_interior.mainframe -relief solid -borderwidth 0 -background white
	} {usual
		ignore -background }
   pack $itk_component(mainframe)
   set w $itk_component(mainframe)

   itk_component add gaoson {
		ToggleButton $w.gaoson -text AO -pushedbackground Green -pady 0 -width 9
	} {ignore -width }

   itk_component add buttonframe {
		frame $w.buttonframe -background white
	} {usual
			ignore -background }
   itk_component add aniloop {
		ToggleButton $w.buttonframe.aniloop -text ANI \
			-pushedbackground Green -pady 0  -width 6
	} {ignore -width }
   itk_component add flexloop {
		ToggleButton $w.buttonframe.flexloop -text FLEX -pushedbackground Green \
			-pady 0 -width 6
	} {ignore -width }
   itk_component add crloop {
      ToggleButton $w.buttonframe.crloop -text CRCS -pushedbackground Green \
         -pady 0 -width 6
   } {ignore -width }
   itk_component add sfsloop {
		ToggleButton $w.buttonframe.sfsloop -text SFS -pushedbackground Green \
			-pady 0 -width 6
	} {ignore -width }
   itk_component add rightframe {
       frame $w.rightframe -background white -borderwidth 0
   } {
      usual
      ignore -highlightthickness -borderwidth
   }
   itk_component add lgswfsframe {
      frame $w.rightframe.lgswfsframe -background white -relief solid -borderwidth 1
   } {usual
         ignore -background }
   itk_component add lgswfslabel {
      label $w.rightframe.lgswfsframe.lgswfslabel -text LGSWFS -background white -highlightthickness 0 -borderwidth 0
   } {  usual
         ignore -highlightthickness -borderwidth -background
   }
   pack $itk_component(lgswfslabel) -padx 1 -pady 1

   pack $itk_component(crloop) $itk_component(sfsloop) $itk_component(flexloop) $itk_component(aniloop) -side top -anchor w

   itk_component add ttframe {
       frame $w.rightframe.ttframe -background white -relief solid -borderwidth 1
   } { usual
         ignore -background }
   itk_component add ttlabel {
         label $w.rightframe.ttframe.ttlabel -text TT -background white -highlightthickness 0 -borderwidth 0
   } { usual
          ignore -background -highlightthickness -borderwidth }
   itk_component add ttcan1 {
      ToggleButton $w.rightframe.ttframe.ttcan1 -text C1 \
         -pushedbackground Green -pady 0 -width 5 -command [itcl::code $this onTTCxPress]
   } {ignore -width }
   itk_component add ttcan2 {
      ToggleButton $w.rightframe.ttframe.ttcan2 -text C2 \
         -pushedbackground Green -pady 0 -width 5 -command [itcl::code $this onTTCxPress]
   } {ignore -width }
   itk_component add ttcan3 {
      ToggleButton $w.rightframe.ttframe.ttcan3 -text C3 \
         -pushedbackground Green -pady 0 -width 5 -command [itcl::code $this onTTCxPress]
   } {ignore -width }
   itk_component add ttodgw1 {
      ToggleButton $w.rightframe.ttframe.ttodgw1 -text OD1 \
         -pushedbackground Green -pady 0 -width 5 -command [itcl::code $this onTTODGWxPress]
   } {ignore -width }
   itk_component add ttodgw2 {
      ToggleButton $w.rightframe.ttframe.ttodgw2 -text OD2 \
         -pushedbackground Green -pady 0 -width 5 -command [itcl::code $this onTTODGWxPress]
   } {ignore -width }
   itk_component add ttodgw3 {
      ToggleButton $w.rightframe.ttframe.ttodgw3 -text OD3 \
         -pushedbackground Green -pady 0 -width 5 -command [itcl::code $this onTTODGWxPress]
   } {ignore -width }
   itk_component add ttodgw4 {
      ToggleButton $w.rightframe.ttframe.ttodgw4 -text OD4 \
         -pushedbackground Green -pady 0 -width 5 -command [itcl::code $this onTTODGWxPress]
   } {ignore -width }
   grid $itk_component(ttlabel) -
   grid $itk_component(ttcan1) $itk_component(ttcan2)
   grid $itk_component(ttcan3) - -sticky we
   grid $itk_component(ttodgw1) $itk_component(ttodgw2)
   grid $itk_component(ttodgw3) $itk_component(ttodgw4)

   itk_component add canframe {
		frame $w.canframe -relief solid -borderwidth 1 -background white
	} { usual
			ignore -background }
   itk_component add can1frame {
      frame $w.canframe.can1frame -relief flat -borderwidth 1 -background white
   } { usual
         ignore -background }
   itk_component add can1 {
      ToggleButton $w.canframe.can1frame.can1 -text C1 -pushedbackground Green -width 6 -pady 0
   } { ignore -width -pady -padx}
   pack $itk_component(can1) -pady 2 -padx 5
   itk_component add can2frame {
      frame $w.canframe.can2frame -relief flat -borderwidth 1 -background white
   } { usual
         ignore -background }
   itk_component add can2 {
      ToggleButton $w.canframe.can2frame.can2 -text C2 -pushedbackground Green -width 6 -pady 0
   } { ignore -width -pady -padx}
   pack $itk_component(can2) -pady 2 -padx 5
   itk_component add can3frame {
      frame $w.canframe.can3frame -relief flat -borderwidth 1 -background white
   } { usual
         ignore -background }
   itk_component add can3 {
      ToggleButton $w.canframe.can3frame.can3 -text C3 -pushedbackground Green -width 6 -pady 0
   } { ignore -width -pady -padx}
   pack $itk_component(can3) -pady 2 -padx 5
   grid $itk_component(can1frame) $itk_component(can2frame) $itk_component(can3frame) -padx 0 -pady 0 -sticky we
   grid columnconfigure $itk_component(canframe) { 0 1 2 } -weight 1

   set odgwExpList ""
   foreach {pair } $odgwExpLUT {
      lappend odgwExpList "[format %.0f [expr 1.0 / [lindex $pair 1]]]"
   }
   itk_component add odgwframe {
		frame $w.odgwframe -background white
	} {usual
			ignore -background }
   itk_component add odgw1 {
		WfsWidget $w.odgwframe.odgw1 -label ODGW1 -explabel Hz -expvalues $odgwExpList -orientation horiz
	}
   itk_component add odgw2 {
		WfsWidget $w.odgwframe.odgw2 -label ODGW2 -explabel Hz -expvalues $odgwExpList -orientation horiz
	}
   itk_component add odgw3 {
		WfsWidget $w.odgwframe.odgw3 -label ODGW3 -explabel Hz -expvalues $odgwExpList -orientation horiz
	}
   itk_component add odgw4 {
		WfsWidget $w.odgwframe.odgw4 -label ODGW4 -explabel Hz -expvalues $odgwExpList -orientation horiz
	}
   [$itk_component(odgw1) component onoff] configure -width 6
   [$itk_component(odgw1) component exp] configure -width 3 -labeltext "f\[Hz\]"
   [$itk_component(odgw2) component onoff] configure -width 6
   [$itk_component(odgw2) component exp] configure -width 3 -labeltext "f\[Hz\]"
   [$itk_component(odgw3) component onoff] configure -width 6
   [$itk_component(odgw3) component exp] configure -width 3 -labeltext "f\[Hz\]"
   [$itk_component(odgw4) component onoff] configure -width 6
   [$itk_component(odgw4) component exp] configure -width 3 -labeltext "f\[Hz\]"

   pack $itk_component(odgw1) $itk_component(odgw2) $itk_component(odgw3) $itk_component(odgw4) \
      -fill x -expand yes -anchor n -padx 1 -pady {0 1}
   pack configure $itk_component(odgw1) -pady 1

   [$itk_component(odgw1) component exp] selection set 0
   [$itk_component(odgw2) component exp] selection set 0
   [$itk_component(odgw3) component exp] selection set 0
   [$itk_component(odgw4) component exp] selection set 0

   pack $itk_component(ttframe) -side top -anchor e
   pack $itk_component(lgswfsframe) -side top -anchor e -fill x -expand yes -pady {2 1}

   itk_component add arrowspace {
      canvas $w.arrowspace -width [expr $GraphParam::interLineSpace + $GraphParam::arrowHeadSpace] -height 1 -borderwidth 0 -highlightthickness 0  -background white
   } {
      usual
      ignore -highlightthickness -borderwidth -background
   }
   $itk_component(arrowspace) create line 0 0 48 1 -tags tt_cr_br -fill black \
      -width [expr $GraphParam::lineWidth + 2 * $GraphParam::arrowBorder] \
      -arrow last -arrowshape $GraphParam::arrowBorderShape
   $itk_component(arrowspace) create line 0 0 1 1 -tags tt_cr -fill white \
      -width [expr $GraphParam::lineWidth] \
      -arrow last -arrowshape $GraphParam::arrowShape

   pack $itk_component(gaoson) -side top -anchor n -padx 0 -pady {0 2}
   pack $itk_component(odgwframe) -padx 0 -pady 0 -side bottom -expand yes -fill x
   pack $itk_component(canframe) -padx 0 -pady 1 -side bottom -fill x -expand yes
   pack $itk_component(rightframe) -side right
   pack $itk_component(buttonframe) -side left -pady 2
   pack $itk_component(arrowspace) -fill both -expand yes

   set sys [GemsSys::getSingleton]
   $sys subscribe [itcl::code $this onGemsChange]

   trace variable ::Config(tcs.field,value) w [itcl::code $this onFieldChange]

   foreach wd { mainframe rightframe ttframe ttcan3 ttodgw4 odgwframe odgw1 odgw4 buttonframe canframe sfsloop aniloop flexloop} {
      bind $itk_component($wd) <Configure> [itcl::code $this onLayoutChange]
   }

   eval itk_initialize $args

   onFieldChange ::Config "tcs.field,value" w
}

itcl::body GemsWidget::destructor {} {
   clearFieldSubscription
   trace vdelete ::Config(tcs.field,value) w [itcl::code $this onFieldChange]
   $sys unsubscribe [itcl::code $this onGemsChange]
}

itcl::body GemsWidget::init {} {
   if {$itk_option(-aocontroller) ne "" } {
      if { $linkedField eq "" } {
         [$itk_component(odgw1) component exp] selection set 0
         [$itk_component(odgw2) component exp] selection set 0
         [$itk_component(odgw3) component exp] selection set 0
         [$itk_component(odgw4) component exp] selection set 0
      }
   }
}

itcl::body GemsWidget::reset {} {
   $itk_component(gaoson) pop
   $itk_component(ttcan1) pop
   $itk_component(ttcan2) pop
   $itk_component(ttcan3) pop
   $itk_component(ttodgw1) pop
   $itk_component(ttodgw2) pop
   $itk_component(ttodgw3) pop
   $itk_component(ttodgw4) pop
   $itk_component(flexloop) pop
   $itk_component(crloop) pop
   $itk_component(sfsloop) pop
   $itk_component(aniloop) pop
   $itk_component(can1) pop
   $itk_component(can2) pop
   $itk_component(can3) pop
   $itk_component(odgw1) switchPop
   $itk_component(odgw2) switchPop
   $itk_component(odgw3) switchPop
   $itk_component(odgw4) switchPop
}

itcl::body GemsWidget::recolor {} {
   if {[$itk_option(-aocontroller) state lwfsLoop] } {
      $itk_component(mainframe) configure -background green
      $itk_component(buttonframe) configure -background green
      $itk_component(rightframe) configure -background green
      $itk_component(arrowspace) configure -background green
   } else {
      $itk_component(mainframe) configure -background white
      $itk_component(buttonframe) configure -background white
      $itk_component(rightframe) configure -background white
      $itk_component(arrowspace) configure -background white
   }
   if {[$itk_option(-aocontroller) state lgswfs] } {
      $itk_component(lgswfsframe) configure -background green
      $itk_component(lgswfslabel) configure -background green
   } else {
      $itk_component(lgswfsframe) configure -background white
      $itk_component(lgswfslabel) configure -background white
   }
   if {[$itk_option(-aocontroller) state ttLoop] } {
      $itk_component(ttframe) configure -background green
      $itk_component(ttlabel) configure -background green
   } else {
      $itk_component(ttframe) configure -background white
      $itk_component(ttlabel) configure -background white
   }
   set ttFlag 0
   if {[$itk_option(-aocontroller) state ttgs1] } {
      $itk_component(can1frame) configure -background green
      set ttFlag 1
   } else {
      $itk_component(can1frame) configure -background white
   }
   if {[$itk_option(-aocontroller) state ttgs2] } {
      $itk_component(can2frame) configure -background green
      set ttFlag 1
   } else {
      $itk_component(can2frame) configure -background white
   }
   if {[$itk_option(-aocontroller) state ttgs3] } {
      $itk_component(can3frame) configure -background green
      set ttFlag 1
   } else {
      $itk_component(can3frame) configure -background white
   }
   if {$ttFlag } {
      $itk_component(canframe) configure -background Green
   } else {
      $itk_component(canframe) configure -background white
   }
   set odgwFlag 0
   if {[$itk_option(-aocontroller) state odgw1] } {
      $itk_component(odgw1) configure -status on
      set odgwFlag 1
   } else {
      $itk_component(odgw1) configure -status off
   }
   if {[$itk_option(-aocontroller) state odgw2] } {
      $itk_component(odgw2) configure -status on
      set odgwFlag 1
   } else {
      $itk_component(odgw2) configure -status off
   }
   if {[$itk_option(-aocontroller) state odgw3] } {
      $itk_component(odgw3) configure -status on
      set odgwFlag 1
   } else {
      $itk_component(odgw3) configure -status off
   }
   if {[$itk_option(-aocontroller) state odgw4] } {
      $itk_component(odgw4) configure -status on
      set odgwFlag 1
   } else {
      $itk_component(odgw4) configure -status off
   }
   if {$odgwFlag } {
      $itk_component(odgwframe) configure -background Green
   } else {
      $itk_component(odgwframe) configure -background white
   }
   if { [$itk_option(-aocontroller) state ttLoop] } {
      if { [AO state rotator] && [$itk_option(-aocontroller) state rotOffload] } {
         $itk_component(arrowspace) itemconfigure tt_cr -fill green
      } else {
         $itk_component(arrowspace) itemconfigure tt_cr -fill yellow
      }
   } else {
      $itk_component(arrowspace) itemconfigure tt_cr -fill white
   }
}

itcl::body GemsWidget::enable {} {
   $itk_option(-aocontroller) configure -ttgs1Active [expr \"[$itk_component(can1) get]\" eq \"pushed\"]
   $itk_option(-aocontroller) configure -ttgs2Active [expr \"[$itk_component(can2) get]\" eq \"pushed\"]
   $itk_option(-aocontroller) configure -ttgs3Active [expr \"[$itk_component(can3) get]\" eq \"pushed\"]

   $itk_option(-aocontroller) configure -odgw1Active [expr \"[$itk_component(odgw1) switchGet]\" eq \"pushed\"]
   set odgw1Freq [$itk_component(odgw1) getExp]
   if {![string is double -strict $odgw1Freq] } {
      set odgw1Freq 800
   }
   $itk_option(-aocontroller) configure -odgw1Exp [expr "1.0 / $odgw1Freq"]

   $itk_option(-aocontroller) configure -odgw2Active [expr \"[$itk_component(odgw2) switchGet]\" eq \"pushed\"]
   set odgw2Freq [$itk_component(odgw2) getExp]
   if {![string is double -strict $odgw2Freq] } {
      set odgw2Freq 800
   }
   $itk_option(-aocontroller) configure -odgw2Exp [expr "1.0 / $odgw2Freq"]

   $itk_option(-aocontroller) configure -odgw3Active [expr \"[$itk_component(odgw3) switchGet]\" eq \"pushed\"]
   set odgw3Freq [$itk_component(odgw3) getExp]
   if {![string is double -strict $odgw3Freq] } {
      set odgw3Freq 800
   }
   $itk_option(-aocontroller) configure -odgw3Exp [expr "1.0 / $odgw3Freq"]

   $itk_option(-aocontroller) configure -odgw4Active [expr \"[$itk_component(odgw4) switchGet]\" eq \"pushed\"]
   set odgw4Freq [$itk_component(odgw4) getExp]
   if {![string is double -strict $odgw4Freq] } {
      set odgw4Freq 800
   }
   $itk_option(-aocontroller) configure -odgw4Exp [expr "1.0 / $odgw4Freq"]

   $itk_option(-aocontroller) configure -lwfsActive 1
   $itk_option(-aocontroller) configure -lwfsLoop [expr \"[$itk_component(gaoson) get]\" eq \"pushed\"]
   $itk_option(-aocontroller) configure -flexLoop [expr \"[$itk_component(flexloop) get]\" eq \"pushed\"]
   if { "[$itk_component(crloop) get]" eq "pushed" } {
      AO configure -crsource GAOS
   } else {
      AO configure -crsource ""
   }
   set useTTGS1 [expr \"[$itk_component(ttcan1) get]\" eq \"pushed\"]
   set useTTGS2 [expr \"[$itk_component(ttcan2) get]\" eq \"pushed\"]
   set useTTGS3 [expr \"[$itk_component(ttcan3) get]\" eq \"pushed\"]
   set useODGW1 [expr \"[$itk_component(ttodgw1) get]\" eq \"pushed\"]
   set useODGW2 [expr \"[$itk_component(ttodgw2) get]\" eq \"pushed\"]
   set useODGW3 [expr \"[$itk_component(ttodgw3) get]\" eq \"pushed\"]
   set useODGW4 [expr \"[$itk_component(ttodgw4) get]\" eq \"pushed\"]
   if { $useTTGS1 || $useTTGS2 || $useTTGS3 || $useODGW1 || $useODGW2 || $useODGW3 || $useODGW4 } {
      $itk_option(-aocontroller) configure -ttLoop 1
   } else {
      $itk_option(-aocontroller) configure -ttLoop 0
   }
   $itk_option(-aocontroller) configure -ttgs1UseForTT $useTTGS1
   $itk_option(-aocontroller) configure -ttgs2UseForTT $useTTGS2
   $itk_option(-aocontroller) configure -ttgs3UseForTT $useTTGS3
   $itk_option(-aocontroller) configure -odgw1UseForTT $useODGW1
   $itk_option(-aocontroller) configure -odgw2UseForTT $useODGW2
   $itk_option(-aocontroller) configure -odgw3UseForTT $useODGW3
   $itk_option(-aocontroller) configure -odgw4UseForTT $useODGW4
   $itk_option(-aocontroller) configure -aniLoop [expr \"[$itk_component(aniloop) get]\" eq \"pushed\"]
   $itk_option(-aocontroller) configure -sfsLoop [expr \"[$itk_component(sfsloop) get]\" eq \"pushed\"]
}

itcl::body GemsWidget::onGemsChange {reasons} {
   set shouldRecolor 0
   foreach reason $reasons {
      switch -glob $reason {
         gemsActive -
         ttLoopState -
         ttwfsActive* -
         odgwActive* -
         lgsLoopState -
         lgswfsActive {
            set shouldRecolor 1
            break
         }
      }
   }
   if {$shouldRecolor } {
      recolor
   }
}

itcl::body GemsWidget::onFieldChange {name1 name2 op} {
   clearFieldSubscription
   set fieldname $::Config(tcs.field,namespace)::$::Config(tcs.field,value)
   if { [llength [itcl::find objects $fieldname] ] > 0 } {
      setFieldSubscription $fieldname
      onTargetChange { ttgs3target odgw1target odgw2target odgw3target \
         odgw4target }
   }
}

itcl::body GemsWidget::onTargetChange {changes} {
   foreach change $changes {
      switch $change {
         ttgs1target { onTTGSChange 1 }
         ttgs2target { onTTGSChange 2 }
         ttgs3target { onTTGSChange 3 }
         odgw1target { onODGWChange 1 }
         odgw2target { onODGWChange 2 }
         odgw3target { onODGWChange 3 }
         odgw4target { onODGWChange 4 }
      }
   }
}

itcl::body GemsWidget::clearFieldSubscription {} {
   if {$linkedField ne "" } {
      if {[llength [itcl::find objects $linkedField] ] > 0 } {
         $linkedField unsubscribe [itcl::code $this onTargetChange]
      }
      set linkedField ""
   }
}

itcl::body GemsWidget::setFieldSubscription {fieldname } {
   if {$linkedField ne "" && [llength [itcl::find objects $linkedField] ] > 0 } {
      $linkedField unsubscribe [itcl::code $this onTargetChange]
   }
   set linkedField $fieldname
   $fieldname subscribe [itcl::code $this onTargetChange]
}

itcl::body GemsWidget::onTTGSChange {id} {
   set tagtarget [$linkedField getDefaultTarget CWFS${id}]
   if { $tagtarget ne "" } {
      set target [$tagtarget cget -target]
   } else {
      set target ""
   }
   if { [llength [itcl::find objects $target] ] > 0 } {
      set mag [calcMagForTarget 0.65 $target]
      if { [string is double -strict $mag] } {
         $itk_option(-aocontroller) configure -ttgs${id}Mag $mag
      }
   }
}

itcl::body GemsWidget::onODGWChange {id} {
   set tagtarget [$linkedField getDefaultTarget ODGW${id}]
   if { $tagtarget ne "" } {
      set target [$tagtarget cget -target]
   } else {
      set target ""
   }
   if { [llength [itcl::find objects $target] ] > 0 } {
      set wavel ::WavelengthNames::[$linkedField cget -wavelength]
      if { [llength [itcl::find objects $target] ] > 0 } {
         set mag [calcMagForTarget [$wavel cget -wavel] $target]
         if { [string is double -strict $mag] } {
            set index [nearest $mag $odgwExpLUT ]
            [$itk_component(odgw${id}) component exp] selection set $index
            $itk_option(-aocontroller) configure -odgw${id}Mag $mag
         }
      }
   }
}

itcl::body GemsWidget::calcMagForWavelength {wavel mags brightness} {
   if { [llength $mags] > 0 } {
      set index [nearest $wavel $mags]
      set ret [lindex $mags $index 1]
   } else {
      set ret $brightness
   }
   return $ret
}

itcl::body GemsWidget::calcMagForTarget {wavel target} {
   set bands { {U 0.36} {B 0.44} {V 0.55} {UC 0.6} {R 0.67} {I 0.87} {Y 1.0} \
               {J 1.25} {H 1.65} {K 2.2}  {L 3.8}  {M 4.8}  {N 10.5} {Q 20.5} }
   set brightness [$target cget -brightness]
   set targetBands  [$target getMagnitudeBands]
   set dummy {}
   set magAB ""
   set magJy ""

   foreach targetBand $targetBands {
      if { $targetBand eq "AB" } {\
         set magAB [$target getMagnitude AB ]
      } elseif { $targetBand eq "Jy" } {\
         set magAB [$target getMagnitude Jy ]
      } else {
         foreach band $bands {
            if { [lindex $band 0] eq $targetBand } {
               lappend dummy [list [lindex $band 1] [$target getMagnitude $targetBand]]
               break
            }
         }
      }
   }
   if { [llength $dummy] > 0 } {
      return [calcMagForWavelength $wavel $dummy $brightness]
   } elseif { $magAB ne "" } {
      return $magAB
   }
   return $magJy
}

itcl::body GemsWidget::lookup { val lut {index 0} } {
   for { set ret [expr "[llength $lut] - 1"] } { $ret >= 0 } { incr ret -1 } {
      if { [lindex $lut $ret $index] <= $val } {
         break
      }
   }
   return $ret
}

itcl::body GemsWidget::nearest { val lut {index 0} } {
   set ret 0
   set len [llength $lut]
   if { $len > 0 } {
      set dist [expr abs([lindex $lut 0 $index] - $val)]
   }
   for { set i 1 } { $i < $len } { incr i } {
      set d [expr abs([lindex $lut $i $index] - $val)]
      if { $d < $dist } {
         set ret $i
         set dist $d
      }
   }
   return $ret
}

itcl::configbody GemsWidget::state {
   switch $itk_option(-state) {
      normal -
      active -
      disabled {
         $itk_component(gaoson) configure -state $itk_option(-state)
         $itk_component(aniloop) configure -state $itk_option(-state)
         $itk_component(ttlabel) configure -state $itk_option(-state)
         $itk_component(ttcan1) configure -state $itk_option(-state)
         $itk_component(ttcan2) configure -state $itk_option(-state)
         $itk_component(ttcan3) configure -state $itk_option(-state)
         $itk_component(ttodgw1) configure -state $itk_option(-state)
         $itk_component(ttodgw2) configure -state $itk_option(-state)
         $itk_component(ttodgw3) configure -state $itk_option(-state)
         $itk_component(ttodgw4) configure -state $itk_option(-state)
         $itk_component(flexloop) configure -state $itk_option(-state)
         $itk_component(crloop) configure -state $itk_option(-state)
         $itk_component(sfsloop) configure -state $itk_option(-state)
         $itk_component(can1) configure -state $itk_option(-state)
         $itk_component(can2) configure -state $itk_option(-state)
         $itk_component(can3) configure -state $itk_option(-state)
         $itk_component(odgw1) configure -state $itk_option(-state)
         $itk_component(odgw2) configure -state $itk_option(-state)
         $itk_component(odgw3) configure -state $itk_option(-state)
         $itk_component(odgw4) configure -state $itk_option(-state)
         $itk_component(lgswfslabel) configure -state $itk_option(-state)
      }
   }
}

itcl::body GemsWidget::onTTODGWxPress {op} {
   if { $op eq "push" } {
      $itk_component(ttcan1) clear
      $itk_component(ttcan2) clear
      $itk_component(ttcan3) clear
   }
}

itcl::body GemsWidget::onTTCxPress {op} {
   if { $op eq "push" } {
      $itk_component(ttodgw1) clear
      $itk_component(ttodgw2) clear
      $itk_component(ttodgw3) clear
      $itk_component(ttodgw4) clear
   }
}

itcl::body GemsWidget::getMagnetPoint { type } {
   switch $type {
      TT_CAN_IN {
         set x [ expr [winfo x $itk_component(rightframe)] + [winfo x $itk_component(ttframe)] + [winfo width $itk_component(ttframe)] ]
         set y [ expr [winfo y $itk_component(rightframe)] + [winfo y $itk_component(ttframe)] + [winfo y $itk_component(ttcan3)] ]
      }
      TT_ODGW_IN {
         set x [ expr [winfo x $itk_component(rightframe)] + [winfo x $itk_component(ttframe)] + [winfo width $itk_component(ttframe)] ]
         set y [ expr [winfo y $itk_component(rightframe)] + [winfo y $itk_component(ttframe)] + [winfo y $itk_component(ttodgw4)] ]
      }
      ODGW_OUTR {
         set x [ expr [winfo x $itk_component(odgwframe)] + \
            [winfo x $itk_component(odgw1)] + [winfo width $itk_component(odgw1)] +1 ]
         set y [ expr [winfo y $itk_component(odgwframe)] + ( [winfo y $itk_component(odgw1)] \
            + [winfo y $itk_component(odgw4)] + [winfo height $itk_component(odgw4)] ) / 2 ]
      }
      ODGW_OUTL {
         set x [expr [winfo x $itk_component(odgwframe)] ]
         set y [ expr [winfo y $itk_component(odgwframe)] + ( [winfo y $itk_component(odgw1)] \
            + [winfo y $itk_component(odgw4)] + [winfo height $itk_component(odgw4)] ) / 2 ]
      }
      CAN_OUTR  {
         set x [ expr [winfo x $itk_component(canframe)] + [winfo width $itk_component(canframe)] ]
         set y [ expr [winfo y $itk_component(canframe)] + [winfo height $itk_component(canframe)] / 2 ]
      }
      CAN_OUTL  {
         set x [winfo x $itk_component(canframe)]
         set y [ expr [winfo y $itk_component(canframe)] + [winfo height $itk_component(canframe)] / 2 ]
      }
      SF_IN {
         set x [ expr [winfo x $itk_component(buttonframe)] + [winfo x $itk_component(sfsloop)] ]
         set y [ expr [winfo y $itk_component(buttonframe)] + [winfo y $itk_component(sfsloop)] + [winfo height $itk_component(sfsloop)] / 2 ]
      }
      ANI_IN {
         set x [ expr [winfo x $itk_component(buttonframe)] + [winfo x $itk_component(aniloop)] ]
         set y [ expr [winfo y $itk_component(buttonframe)] + [winfo y $itk_component(aniloop)] + [winfo height $itk_component(aniloop)] / 2 ]
      }
      FLEX_IN {
         set x [ expr [winfo x $itk_component(buttonframe)] + [winfo x $itk_component(flexloop)] ]
         set y [ expr [winfo y $itk_component(buttonframe)] + [winfo y $itk_component(flexloop)] + [winfo height $itk_component(flexloop)] / 2 ]
      }
      default {
         return {-1 -1}
      }
   }
   return [ list [expr [winfo x $itk_interior] + [winfo x $itk_component(mainframe)] + $x ] [expr [winfo y $itk_interior] + [winfo y $itk_component(mainframe)] + $y ] ]
}

itcl::body GemsWidget::onLayoutChange {} {
   set startx [ expr [winfo width $itk_component(arrowspace)] ]
   set starty [ expr [winfo y $itk_component(rightframe)] + [winfo y $itk_component(ttframe)] \
      + [winfo y $itk_component(ttlabel)] + [winfo height $itk_component(ttlabel)] / 2 \
      - [winfo y $itk_component(arrowspace)] ]
   set endx 0
   set endy [ expr [winfo y $itk_component(buttonframe)] + [winfo y $itk_component(crloop)] \
      + [winfo height $itk_component(crloop)] / 2 \
      - [winfo y $itk_component(arrowspace)] ]
   set midx [expr $startx - $GraphParam::interLineSpace ]

   $itk_component(arrowspace) coords tt_cr_br \
      $startx $starty \
      $midx $starty \
      $midx $endy \
      [expr $endx + $GraphParam::arrowBorderOffset] $endy
   $itk_component(arrowspace) coords tt_cr \
      $startx $starty \
      $midx $starty \
      $midx $endy \
      [expr $endx + $GraphParam::arrowOffset] $endy

   if { ! [string is space $itk_option(-layoutchangecmd)] } {
      eval $itk_option(-layoutchangecmd)
   }
}