#+
#  GuideLoop <- itk::Widget
#
#  A GuideLoop is a diagram of the various guiding loops with control
#  for setting them up and enabling them
##  Options:
#           none
#
#  Methods:
#           none
#
#  D Terrett  29 April 2004
#
#  Copyright CCLRC
#+

itcl::class GuideLoop {
   inherit itk::Widget
   constructor args {}
   destructor {}
   public {
      method reset {}
      method recolour {args}
   }
   private {
      method comacorr {op}
      method m2mode {probe val}
      method mtmode {val}
		method crmode {val}
		method probefrom {val}
      method probeto {val}
      method wfsmode {wfs val}
      method enable {}
      method m1mode {state}
      method configSfoEx {}
      variable monids
		variable gemsSys ""
		
		variable gaosWidget ""
		method buildGaos {}
		method buildAltairArrows {}
		method buildGemsArrows {}
		method recolourAltairArrows {}
		method recolourGemsArrows {}
		method recolourGaos {}
		method enableGaos {}
		method resetGaos {}
		method onGemsChange {reasons}
   }
   itk_option define -wfsConfigObj wfsConfigObj WfsConfigObj "" {
   }
	itk_option define -wfsAlarmObj wfsAlarmObj WfsAlarmObj ""
}

itk::usual GuideLoop {
   keep -cursor -foreground -background
}

itcl::body GuideLoop::constructor args {
# Create canvas.
   itk_component add canv {
#AWE      canvas $itk_interior.canv -width 630 -height 497 -borderwidth 2 
      canvas $itk_interior.canv -width 650 -height 475 -borderwidth 2 \
            -relief sunken
   }
   pack $itk_component(canv)
   set w $itk_component(canv)
   AO setCanvas $itk_component(canv)
   bind $w <Button-2> {
       puts "on canvas x: %x y: %y"
   }

# WFS boxes AWE ... seperating out the OIWFS
   # rectangle to group pwfs1 and pwfs2
   $w create rectangle 0 0 131 106 -fill white -tags "active pwfs1_bg pwfs2_bg pwfs_comb"

	itk_component add pwfs1 {
		WfsWidget $w.pwfs1 -label P1 -onswitchpress [itcl::code $this wfsmode pwfs1] -background grey
	} {
		usual
	}
	$itk_component(pwfs1) expSet [AO cget -pwfs1Expose]
	$w create window 0 0 -window $w.pwfs1 -tags pwfs1 -anchor nw
	itk_component add pwfs2 {
		WfsWidget $w.pwfs2 -label P2 -onswitchpress [itcl::code $this wfsmode pwfs2]
	} {
		usual
	}
	$itk_component(pwfs2) expSet [AO cget -pwfs2Expose]
	$w create window 0 0 -window $w.pwfs2 -tags pwfs2 -anchor nw

# OIWFS including an AO mode for NICI
   itk_component add oiwfs {
	  ToggleButton $w.oiwfs -text OI -pushedbackground Green -pady 0 \
        -command [itcl::code $this wfsmode oiwfs]
   } {
      usual
   }
   $w create window 62 3 -width 60 -window $w.oiwfs -tags oiwfs -anchor n
   itk_component add oiwfs_label {
      label $w.oiwfs_label -text [string toupper oiwfs]
   }
   $w create rectangle 0 0 123 70 -fill white -tags "active oiwfs oiwfs_bg"
   $w create rectangle 2 26 60 47 -fill white -tags "active oiwfs oiwfs_ao"
   $w create rectangle 63 26 121 47 -fill white -tags "active oiwfs oiwfs_wfs"

# WFS controls.
   itk_component add oiwfs_ex {
      iwidgets::combobox $w.oiwfs_ex -arrowrelief flat -width 5 \
            -validate real -labeltext "exp(s)"
   }

   $w create window 2 48 -window $w.oiwfs_ex -tag oiwfs -anchor nw
   $w.oiwfs_ex insert list end 1.0 0.5 0.1 0.05 0.02 0.01 0.005
   $w.oiwfs_ex insert entry end [AO cget -oiwfsExpose]
   [$w.oiwfs_ex component list] configure -hscrollmode none \
         -vscrollmode none

	set font [$itk_component(oiwfs) cget -font]
   $w create text 31 37 -text AO -tags "oiwfs oiwfs_aotxt" -font $font
   $w create text 92 37 -text WFS -tags "oiwfs oiwfs_wfstxt" -font $font

# GAOS
#   $w create rectangle 0 0 140 137 -fill white -tags "active gaos gaos_bg"
# display aoSettled state
   $w create rectangle 0 0 100 20 -fill white -tags "settled aoSettled active"
   $w create text 50 10 -text aoSettled -tags settled -font $font

	
	buildGaos
	
	

# M1, M2 and Mount boxes.
   $w create rectangle 0 0 128 87 -fill white -tags "active m2 m2_bg"
   $w create text 95 22 -text M2 -tags m2 -font $font
   $w create text 95 42 -text TIP/TILT -tags m2 -font $font
   $w create text 95 62 -text FOCUS -tags m2 -font $font
   $w create rectangle 0 0 73 87 -fill white -tags "active m2xy m2xy_bg"
   $w create text 37 24 -text "M2" -tags m2xy -font $font
   $w create rectangle 0 0 123 87 -fill white -tags "active m1 m1_bg"
   $w create text 92 33 -text M1 -tags m1 -font $font
   $w create text 92 54 -text FIGURE -tags m1 -font $font
   $w create rectangle 0 21 123 49 -fill white -tags "active mount mount_bg"
   $w create text 92 35 -text MOUNT -tags mount -font $font
	$w create rectangle 0 21 123 49 -fill white -tags "active rotator rotator_bg"
	$w create text 92 35 -text ROTAT -tags rotator -font $font

# Controls for M1.
   itk_component add m1src {
      SelectButton $w.m1src -orient vertical \
            -command [itcl::code $this m1mode]
   } {
      usual
      rename -offbackground -background background Background
   }
   $w create window 2 2 -width 60 -window $w.m1src -tags m1 -anchor nw
   $itk_component(m1src) add P1 -pady 0
   $itk_component(m1src) add P2 -pady 0
   $itk_component(m1src) add OI -pady 0
   $itk_component(m1src) add AO -pady 0

# Controls for M2
   itk_component add m2p1 {
		ToggleButton $w.m2p1 -text P1 -pushedbackground Green -pady 0 -padx 0 \
            -command [itcl::code $this m2mode p1]
   } {
      usual
   }
   $w create window 2 2 -width 60 -window $itk_component(m2p1) -tags m2 -anchor nw

   itk_component add m2p2 {
		ToggleButton $w.m2p2 -text P2 -pushedbackground Green -pady 0 -padx 0 \
            -command [itcl::code $this m2mode p2]
   } {
      usual
   }
   $w create window 2 23 -width 60 -window $itk_component(m2p2) -tags m2 -anchor nw

   itk_component add m2oi {
		ToggleButton $w.m2oi -text OI -pushedbackground Green -pady 0 -padx 0 \
            -command [itcl::code $this m2mode oi]
   } {
      usual
   }
   $w create window 2 44 -width 60 -window $itk_component(m2oi) -tags m2 -anchor nw

   itk_component add m2ao {
		ToggleButton $w.m2ao -text AO -pushedbackground Green -pady 0 -padx 0 \
            -command [itcl::code $this m2mode ao]
   } {
      usual
   }
   $w create window 2 65 -width 60 -window $itk_component(m2ao) -tags m2 -anchor nw

   itk_component add m2coma {
		ToggleButton $w.m2coma -text COMA -pushedbackground Green -pady 0 \
            -command [itcl::code $this comacorr]
   } {
      usual
   }
   $w create window 37 54 -width 60 -window $itk_component(m2coma) -tags m2xy

# Controls for Mount.
   itk_component add mt {
		SelectButton $w.mt -orient horizontal \
            -command [itcl::code $this mtmode]
   } {
      usual
		rename -offbackground -background background Background
   }
   $w create window 2 25 -width 60 -window $itk_component(mt) -tags mount -anchor nw
   $itk_component(mt) add M2 -pady 0

	# Controls for Cass-rotator.
	itk_component add rotator {
		SelectButton $w.rotator -orient horizontal \
				-command [itcl::code $this crmode]
	} {
		usual
		rename -offbackground -background background Background
	}
	$w create window 2 25 -width 60 -window $itk_component(rotator) -tags rotator -anchor nw
	$itk_component(rotator) add AO -pady 0

# Box for WFS probes.
   $w create rectangle 0 0 123 66 -fill white -tags "active probes probes_bg"
   $w create text 92 33 -text PROBES -tags probes -font $font

# Controls for probes.
   itk_component add prfrom {
      SelectButton $w.prfrom -orient vertical \
            -command [itcl::code $this probefrom]
   } {
      usual
      rename -offbackground -background background Background
   }
   $w create window 2 2 -width 30 -window $w.prfrom -tags probes -anchor nw
   $itk_component(prfrom) add P1 -pady 0
   $itk_component(prfrom) add P2 -pady 0
   $itk_component(prfrom) add OI -pady 0

   itk_component add prto {
      SelectButton $w.prto -orient vertical -command [itcl::code $this probeto]
   } {
      usual
      rename -offbackground -background background Background
   }
   $w create window 32 2 -width 30 -window $w.prto -tags probes -anchor nw
   $itk_component(prto) add P1 -pady 0
   $itk_component(prto) add P2 -pady 0
   $itk_component(prto) add OI -pady 0

   $itk_component(prto) setState "0 1 2" disabled

# Move boxes into position.
   $w move m2 149 10
   $w move m2xy 277 10
   $w move m1 227 107
   $w move settled 480 40
   $w move oiwfs 227 280
   $w move pwfs_comb 31 175
   $w move pwfs1 35 179
   $w move pwfs2 35 230
   $w move probes 227 204
   $w move mount 227 339
	$w move rotator 227 377

# PWFS to M1
   $w create line 118 174 118 131 226 131 -width 3 -fill white \
         -tags {active pwfs1_m1 pwfs2_m1} -arrow last -arrowshape {20 20 7}

   $w create line 226 315 191 315 191 161 226 161 -width 3 -fill white \
         -tags {active oiwfs_m1} -arrow last -arrowshape {20 20 7}

# WFS to M2
   $w create line 74 174 74 33 148 33 -width 3 -fill white \
         -tags {active pwfs1_m2 pwfs2_m2} -arrow last -arrowshape {20 20 7}

   $w create line 226 338 181 338 181 97 -width 3 -fill white \
         -tags {active oiwfs_m2} -arrow last -arrowshape {20 20 7}

# WFS to Probes
   $w create line 163 228 226 228 -width 3 -fill white \
         -tags {active pwfs1_pr pwfs2_pr} -arrow last -arrowshape {20 20 7}


   $w create line 226 292 201 292 201 257 226 257 -width 3 -fill white \
         -tags {active oiwfs_pr} -arrow last -arrowshape {20 20 7}


# M2 to mount
   $w create line 148 53 20 53 20 374 226 374 -width 3 -fill white \
         -tags {active m2_mt} -arrow last -arrowshape {20 20 7}


# ENABLE/DISABLE/RESET buttons.
# display loopProcessing state
   $w create rectangle 0 0 100 20 -fill white -tags "processing processing_bg"
   $w create text 50 10 -text IDLE -tags "processingText processing" -font $font
   $w move processing 420 420

   itk_component add on {
      LiveButton $w.on -text Enable -command [itcl::code $this enable]
   }
   itk_component add off {
       LiveButton $w.off -text Disable -command { AO disable }
   }
   itk_component add reset {
      button $w.reset -text Reset -command [itcl::code $this reset]
   }
   $w create window 430 459 -window $itk_component(on)
   $w create window 510 459 -window $itk_component(off)
   $w create window 590 459 -window $itk_component(reset)

# Monitor the guide states
   foreach rec {p1state p2state oistate aostate m2state absorbtilt m1state \
         m1source p1guide p2guide oiguide p1mweight p2mweight m2p1guide m2p2guide \
         m2oiguide m2aoguide coma oiblend aoTTGS aoSFO ttgsloop sfoloop useLwfs} {
      if { [llength [itcl::find objects ::guideConfig.$rec]] == 0 } {
         RecordMonitor ::guideConfig.$rec guideConfig $rec
      }
      lappend monids [::guideConfig.$rec add [itcl::code $this recolour]]
   }
	if { [calparam cget -site] eq "CP" } {
		foreach rec {niciAOloop niciAPD crGuide} {
			if { [llength [itcl::find objects ::guideConfig.$rec]] == 0 } {
				RecordMonitor ::guideConfig.$rec guideConfig $rec
			}
			lappend monids [::guideConfig.$rec add [itcl::code $this recolour]]
		}
		
		set gemsSys [::GemsSys::getSingleton]
		$gemsSys subscribe [itcl::code $this onGemsChange]
	}

# Schedule an update once the channels have connected.
   after 1000 [itcl::code $this recolour]

   eval itk_initialize $args
}

itcl::body GuideLoop::destructor {} {
   foreach rec {p1state p2state oistate aostate m2state absorbtilt m1state \
      	m1source p1guide p2guide oiguide p1mweight p2mweight m2p1guide m2p2guide \
	 		m2oiguide m2aoguide coma oiblend aoTTGS aoSFO ttgsloop sfoloop useLwfs niciAOloop niciAPD} mon $monids {
		if { ( $rec ne "niciAOloop" && $rec ne "niciAPD" && $rec ne "crGuide" ) || [calparam cget -site] eq "CP" } {
			::guideConfig.$rec remove $mon
		}
	}
}

itcl::body GuideLoop::recolour args {
	global AOtryingToReuseGain AOreuseGains

	set w $itk_component(canv)
	
# Assume no signal to mount
   set mount 0

# Set everything to white.
   $w itemconfigure active -fill white

# P1 signals.
   if { [AO state pwfs1] } {
		$itk_component(pwfs1) configure -status on
		$w itemconfigure pwfs1_bg -fill green
      if { [AO state m1] && [AO source m1 PWFS1] } {
         $w itemconfigure pwfs1_m1 -fill green
      } else {
         $w itemconfigure pwfs1_m1 -fill yellow
      }
      if { [AO state m2] && ([AO source m2 PWFS1 A] || \
            [AO source m2 PWFS1 B]) } {
         $w itemconfigure pwfs1_m2 -fill green
      } else {
         $w itemconfigure pwfs1_m2 -fill yellow
      }
      if { [AO state coma] } {
         $w itemconfigure pwfs1_m2 -fill green
      } else {
         $w itemconfigure pwfs1_m2 -fill yellow
      }
      if { [AO state p1guide] } {
         $w itemconfigure pwfs1_pr -fill green
      } else {
         $w itemconfigure pwfs1_pr -fill yellow
      }
      if { [AO state mount] && [AO source mount PWFS1] } {
         $w itemconfigure pwfs1_mt -fill green
         set mount 1
      } else {
         $w itemconfigure pwfs1_mt -fill yellow
      }
   } else {
		$itk_component(pwfs1) configure -status off
   }

# P2 signals
   if { [AO state pwfs2] } {
		$itk_component(pwfs2) configure -status on
      $w itemconfigure pwfs2_bg -fill green
      if { [AO state m1] && [AO source m1 PWFS2] } {
         $w itemconfigure pwfs2_m1 -fill green
      } else {
         $w itemconfigure pwfs2_m1 -fill yellow
      }
      if { [AO state m2] && ([AO source m2 PWFS2 A] || \
            [AO source m2 PWFS2 B]) } {
         $w itemconfigure pwfs2_m2 -fill green
      } else {
         $w itemconfigure pwfs2_m2 -fill yellow
      }
      if { [AO state p2guide] } {
         $w itemconfigure pwfs2_pr -fill green
      } else {
         $w itemconfigure pwfs2_pr -fill yellow
      }
      if { [AO state mount] && [AO source mount PWFS2] } {
         $w itemconfigure pwfs2_mt -fill green
         set mount 1
      } else {
         $w itemconfigure pwfs2_mt -fill yellow
      }
   } else {
		$itk_component(pwfs2) configure -status off
	}

# OIWFS signals
   if { [AO state oiao] } {
      # disable the regular oiwfs guide alarm and enable the nici guide alarm
		$itk_option(-wfsAlarmObj) disableWfs oiwfs
		$itk_option(-wfsAlarmObj) enableWfs nici

      $w itemconfigure oiwfs_ao -outline black 
      $w itemconfigure oiwfs_wfs -outline grey
      $w itemconfigure oiwfs_aotxt -fill black 
      $w itemconfigure oiwfs_wfstxt -fill grey
      $itk_component(oiwfs_ex) configure -state disabled
      $itk_option(-wfsConfigObj) niciState normal
      if { [AO state oiaoAPD] } {
         $w itemconfigure oiwfs_ao -fill green
      }
      if { [AO state oiaoLoop] } {
         $w itemconfigure oiwfs_bg -fill green
         if { [$itk_component(prfrom) get] == "OI" && [$itk_component(prto) get] == "P2" } {
            $w itemconfigure oiwfs_pr -fill green
         } else {
            $w itemconfigure oiwfs_pr -fill yellow
         }
      }
   } elseif { [AO state oiwfs] } {
      # enable the regular oiwfs guide alarm and disable the nici guide alarm
		$itk_option(-wfsAlarmObj) disableWfs nici
		$itk_option(-wfsAlarmObj) enableWfs oiwfs

      $w itemconfigure oiwfs_bg -fill green
      $w itemconfigure oiwfs_ao -outline grey
      $w itemconfigure oiwfs_wfs -outline black
      $w itemconfigure oiwfs_aotxt -fill grey 
      $w itemconfigure oiwfs_wfstxt -fill black
      $itk_component(oiwfs_ex) configure -state disabled
      $itk_option(-wfsConfigObj) niciState normal
      if { [AO state m1] && [AO source m1 OIWFS] } {
         $w itemconfigure oiwfs_m1 -fill green
      } else {
         $w itemconfigure oiwfs_m1 -fill yellow
      }
      if { [AO state m2] && ([AO source m2 OIWFS A] || \
            [AO source m2 OIWFS B]) } {
         $w itemconfigure oiwfs_m2 -fill green
      } else {
         $w itemconfigure oiwfs_m2 -fill yellow
      }
      if { [AO state oiguide] } {
         $w itemconfigure oiwfs_pr -fill green
      } else {
         $w itemconfigure oiwfs_pr -fill yellow
      }
      if { [AO state oiblend] } {
         $w itemconfigure oiwfs_gaos -fill green
      } else {
         $w itemconfigure oiwfs_gaos -fill yellow
      }	  
   } else {
      # enable the regular oiwfs guide alarm and disable the nici guide alarm
		$itk_option(-wfsAlarmObj) disableWfs nici
		$itk_option(-wfsAlarmObj) enableWfs oiwfs
      
      $w itemconfigure oiwfs_ao -outline grey
      $w itemconfigure oiwfs_wfs -outline black
      $w itemconfigure oiwfs_aotxt -fill grey 
      $w itemconfigure oiwfs_wfstxt -fill black
      $itk_component(oiwfs_ex) configure -state normal
      $itk_option(-wfsConfigObj) niciState disabled
   }

	recolourGaos

# M1
   if { [AO state m1] } {
      if { ( [AO source m1 PWFS1] && [AO state pwfs1] ) ||
            ( [AO source m1 PWFS2] && [AO state pwfs2] ) ||
            ( [AO source m1 OIWFS] && [AO state oiwfs] ) ||
            ( [AO source m1 Altair] && [AO state gaos] ) } {
         $w itemconfigure m1_bg -fill green
      } else {
         $w itemconfigure m1_bg -fill yellow
      }
   }

# M2
   if { [AO state m2] } {
      if { (( [AO source m2 PWFS1 A] || [AO source m2 PWFS1 B] ) && \
            [AO state pwfs1] ) || \
            (( [AO source m2 PWFS2 A] || [AO source m2 PWFS2 B] ) && \
            [AO state pwfs2] ) || \
            (( [AO source m2 OIWFS A] || [AO source m2 OIWFS B] ) && \
            [AO state oiwfs] ) || \
            (( [AO source m2 GAOS A] || [AO source m2 GAOS B] ) && \
            [AO state gaos] ) } {
         $w itemconfigure m2_bg -fill green
         if { [AO source mount M2] && [AO state mount] } {
            $w itemconfigure m2_mt -fill green
            set mount 1
         } else {
            $w itemconfigure m2_mt -fill yellow
         }
      } else {
         $w itemconfigure m2_bg -fill yellow
         $w itemconfigure m2_mt -fill yellow
      }
   }

# M2 Coma
   if { [AO state coma] } {
      if { [AO state pwfs1] || [AO state gaos] } {
         $w itemconfigure m2xy_bg -fill green
      } else {
         $w itemconfigure m2xy_bg -fill yellow
      }
   }

# M2 guide source buttons.
#   if { [AO source m2 PWFS1] } {
#      $itk_component(m2p1) mark
#   }
#   if { [AO source m2 PWFS2] } {
#      $itk_component(m2p2) mark
#   }
#   if { [AO source m2 OIWFS] } {
#      $itk_component(m2oi) mark
#   }
#   if { [AO source m2 GAOS] } {
#      $itk_component(m2ao) mark
#   }

# Mount
   if { [AO state mount] } {
      if { $mount } {
         $w itemconfigure mount_bg -fill green
      } else {
         $w itemconfigure mount_bg -fill yellow
      }
   }
#Rotator
	if { [AO state rotator] } {
		if { [AO state gaos] } {
			$w itemconfigure rotator_bg -fill green
		} else {
			$w itemconfigure rotator_bg -fill yellow
		}
	}
# WFS probes
	switch [$itk_component(prfrom) get] {
	P1 {
		switch [$itk_component(prto) get] {
		P1 {
		   if {[AO state p1guide] && [AO state pwfs1]} {
				$w itemconfigure probes_bg -fill green
		   } elseif {[AO state p1guide]} {
				$w itemconfigure probes_bg -fill yellow
		   }
		}
		}
	}
	P2 {
		switch [$itk_component(prto) get] {
		P2 {
		   if {[AO state p2guide] && [AO state pwfs2]} {
				$w itemconfigure probes_bg -fill green
		   } elseif {[AO state p2guide]} {
				$w itemconfigure probes_bg -fill yellow
		   }
		}
	   }
	}
	OI {
	   switch [$itk_component(prto) get] {
		P1 {
		   if {[AO state p1guide] && [AO state pwfs1] && [AO state oiwfs]} {
				$w itemconfigure probes_bg -fill green
		   } elseif {[AO state p1guide]} {
				$w itemconfigure probes_bg -fill yellow
		   }
		}
		P2 {
		   if {[AO state p2guide] && [AO state pwfs2] && [AO state oiwfs]} {
				$w itemconfigure probes_bg -fill green
		   } elseif {[AO state p2guide] && [AO state pwfs2] && [AO state oiao] && [AO state oiaoLoop]} {
				$w itemconfigure probes_bg -fill green
		   } elseif {[AO state p2guide]} {
				$w itemconfigure probes_bg -fill yellow
			}
		}
		OI {
			set oiguideprint [AO state oiguide]
		   set oiwfsprint [AO state oiwfs]

		   puts "oiguideprint = $oiguideprint"
		   puts "oiwfsprint = $oiwfsprint"

			if {[AO state oiguide] && [AO state oiwfs]} {
				$w itemconfigure probes_bg -fill green
		   } elseif {[AO state oiguide]} {
				$w itemconfigure probes_bg -fill yellow
		   }
		}
		}
	}
	}
}

itcl::body GuideLoop::comacorr {op} {
   switch $op {
	push {
		AO configure -comacorr 1
	}
	pop {
		AO configure -comacorr 0
	}
   }
}


itcl::body GuideLoop::m2mode {probe val} {
	switch $val {
	push {
      AO configure -${probe}guide On
   } 
	pop {
      AO configure -${probe}guide ""
   }
	}
}

itcl::body GuideLoop::mtmode {val} {
   switch $val {
      P1 {
         AO configure -mountguide PWFS1
      }
      P2 {
         AO configure -mountguide PWFS2
      }
      M2 {
         AO configure -mountguide SCS
      }
		"" {
         AO configure -mountguide none
      }
   }
}

itcl::body GuideLoop::crmode {val} {
	switch $val {
		AO {
			AO configure -crsource GAOS
		}
		"" {
			AO configure -crsource ""
		}
	}
}

itcl::body GuideLoop::probefrom {val} {
   $itk_component(prto) clear
   $itk_component(prto) setState "0 1 2" disabled
   switch $val {
	P1 {
		AO configure -probefrom PWFS1
		$itk_component(prto) setState 0 normal
	}
	P2 {
		AO configure -probefrom PWFS2
		$itk_component(prto) setState 1 normal
	}
	OI {
		AO configure -probefrom OIWFS
		$itk_component(prto) setState "0 1 2" normal
	}
   }
	AO configure -probeguide OFF
}

itcl::body GuideLoop::probeto {val} {
	if { [string is space $val] } {
		AO configure -probeguide OFF
	} else {
	   switch $val {
	      P1 {
	         AO configure -probeto PWFS1
	      }
	      P2 {
	         AO configure -probeto PWFS2
	      }
	      OI {
	         AO configure -probeto OIWFS
	      }
	   }
   	AO configure -probeguide ON
	}
}

itcl::body GuideLoop::wfsmode {wfs val} {
   if { [AO state oiao] && $wfs == "oiwfs" } {
		switch $val {
		push {
			AO configure -oiaoLoop 1
		}
		pop {
			AO configure -oiaoLoop 0
		}
      }
   } else {
      switch $val {
		push {
			AO configure -${wfs}Active 1
		}
		pop {
			AO configure -${wfs}Active 0
		}
      }
   }
}

itcl::body GuideLoop::enable {} {
   AO configure -pwfs1Expose [$itk_component(pwfs1) expGet ]
   AO configure -pwfs2Expose [$itk_component(pwfs2) expGet]
   AO configure -oiwfsExpose [$itk_component(oiwfs_ex) get]

	enableGaos
   AO enable
}

itcl::body GuideLoop::configSfoEx {} {
    set exp [$itk_component(ttgs_ex) get]
    set exp [string trim [string range $exp [string first "(" $exp] end] "()"]
    if {[string length $exp] > 0} {
	set ttgsLimit [expr 1.65*$exp*1000]
	.observePanel.frame.control.alarm configure -ttgsLimit $ttgsLimit
    }
    $itk_component(sfo_ex) clear entry
    switch $exp {
	0.001 {$itk_component(sfo_ex) insert entry end 1.0}
	0.002 {$itk_component(sfo_ex) insert entry end 2.0}
	0.005 {$itk_component(sfo_ex) insert entry end 5.0}
	0.01  {$itk_component(sfo_ex) insert entry end 10.0}
	0.02  {$itk_component(sfo_ex) insert entry end 20.0}
	0.05  {$itk_component(sfo_ex) insert entry end 50.0}
    }
}

itcl::body GuideLoop::m1mode {state} {
	switch $state {
	P1 {
		AO configure -m1source PWFS1
	}
	P2 {
		AO configure -m1source PWFS2
	}
	OI {
		AO configure -m1source OIWFS
	}
	AO {
		AO configure -m1source GAOS
	}
	default {
		AO configure -m1source ""
	}
	}
}

itcl::body GuideLoop::reset {} {

# Disable
   AO process IDLE
   AO disable

# Simulate pushing all the "off" buttons.
   $itk_component(pwfs1) switchPop
   $itk_component(pwfs2) switchPop
   $itk_component(oiwfs) pop
   $itk_component(m1src) select ""
   $itk_component(m2p1) pop
   $itk_component(m2p2) pop
   $itk_component(m2ao) pop
   $itk_component(m2oi) pop
   $itk_component(m2coma) pop
   $itk_component(mt) select ""
	$itk_component(rotator) select ""
	$itk_component(prto) select ""
	$itk_component(prfrom) select ""
	resetGaos
	$itk_component(prto) setState "0 1 2" disabled
	AO configure -probeto ""
}

itcl::body GuideLoop::buildGaos {} {
	set w $itk_component(canv)
	if { [calparam cget -site] eq "CP" } {
		itk_component add gaos { GemsWidget $w.gaos -aocontroller [AO getGaosObj] }
		$w create window 433 72 -window $w.gaos -tags gaos -anchor nw
		set gaosWidget $itk_component(gaos)
		buildGemsArrows
	} else {
		itk_component add gaos { AltairWidget $w.gaos -aocontroller AO }
		$w create window 471 72 -window $w.gaos -tags gaos -anchor nw
		set gaosWidget $itk_component(gaos)
		buildAltairArrows
	}
}

itcl::body GuideLoop::buildAltairArrows {} {
	set w $itk_component(canv)
	$w create line 470 85 351 85  -width 3 -fill white -tags {active gaos_m2} \
		-arrow last -arrowshape {20 20 7}
	$w create line 470 119 351 119 -width 3 -fill white \
		-tags {active gaos_m1} -arrow last -arrowshape {20 20 7}
	$w create line 351 315 425 315 425 173 470 173 -width 3 -fill white \
		-tags {active oiwfs_gaos} -arrow last -arrowshape {20 20 7}

	# GAOS internal
	$w create line 470 221 435 221 435 131 470 131 -width 3 -fill white \
		-tags {active ttgs_gaos} -arrow last -arrowshape {20 20 7}
	$w create line 470 281 445 281 445 152 470 152 -width 3 -fill white \
		-tags {active sfo_gaos} -arrow last -arrowshape {20 20 7}

}

itcl::body GuideLoop::recolourAltairArrows {} {
	set w $itk_component(canv)
	
	if { [AO state gaosTTGS] } {
		if { [AO state ttgsloop] } {
			$w itemconfigure ttgs_gaos -fill green
		} else {
			$w itemconfigure ttgs_gaos -fill yellow
		}
	} else {
		$w itemconfigure ttgs_gaos -fill white
	}
	if { [AO state gaosSFO] } {
		if { [AO state sfoloop] } {
			$w itemconfigure sfo_gaos -fill green
		} else {
			$w itemconfigure sfo_gaos -fill yellow
		}
	} else {
		$w itemconfigure sfo_gaos -fill white
	}
	if { [AO state gaos] } {
		if { [AO state m1] && [AO source m1 Altair] } {
			$w itemconfigure gaos_m1 -fill green
		} else {
			$w itemconfigure gaos_m1 -fill yellow
		}
		if { [AO state m2] && ([AO source m2 GAOS A] || \
				[AO source m2 GAOS B]) } {
			$w itemconfigure gaos_m2 -fill green
		} else {
			$w itemconfigure gaos_m2 -fill yellow
		}
		if { [AO state coma] } {
			$w itemconfigure gaos_m2 -fill green
		} else {
			$w itemconfigure gaos_m2 -fill yellow
		}
	}
}

itcl::body GuideLoop::buildGemsArrows {} {
	set w $itk_component(canv)
	$w create line 433 85 351 85  -width 3 -fill white -tags {active gaos_m2} \
		-arrow last -arrowshape {20 20 7}
	$w create line 433 125 351 125 -width 3 -fill white \
		-tags {active gaos_m1} -arrow last -arrowshape {20 20 7}
	$w create line 351 315 407 315 407 176 433 176 -width 3 -fill white \
		-tags {active oiwfs_gaos} -arrow last -arrowshape {20 20 7}
	$w create line 433 105 388 105 388 411 351 411 -width 3 -fill white \
		-tags {active gaos_cr} -arrow last -arrowshape {20 20 7}

	# GAOS internal
	$w create line 433 238 398 238 398 156 433 156 -width 3 -fill white \
		-tags {active ttgs_gaos} -arrow last -arrowshape {20 20 7}
	$w create line 608 266 633 266 633 156 608 156 -width 3 -fill white \
		-tags {active sfs_gaos} -arrow last -arrowshape {20 20 7}
	$w create line 608 341 643 341 643 176 608 176 -width 3 -fill white \
	-tags {active odgw_gaos} -arrow last -arrowshape {20 20 7}

}

itcl::body GuideLoop::recolourGemsArrows {} {
	set w $itk_component(canv)

	if { [$gemsSys getSFSActive] eq "ON" } {
		if { [$gemsSys getFocLoopState] eq "CLOSED" } {
			$w itemconfigure sfs_gaos -fill green
		} else {
			$w itemconfigure sfs_gaos -fill yellow
		}
	} else {
		$w itemconfigure sfs_gaos -fill white
	}
	set sources [$gemsSys getTTLoopSources]
	set odgwCount 0
	for {set i 1} {$i <= 4} {incr i} {
		if {[$gemsSys getODGWActive $i] eq "ON"} {
			incr odgwCount
		}
	}
	set ttwfsCount 0
	for {set i 1} {$i <= 3} {incr i} {
		if {[$gemsSys getTTWFSActive $i] eq "ON"} {
			incr ttwfsCount
		}
	}
	if { $odgwCount > 0 } {
		if { ( [$gemsSys getFlexLoopState] eq "CLOSED" && [string first oigs $sources] == -1 ) || \
			( [$gemsSys getTTLoopState] eq "CLOSED" && [string first odgw $sources] > -1 ) } {
			$w itemconfigure odgw_gaos -fill green
		} else {
			$w itemconfigure odgw_gaos -fill yellow
		}
	} else {
		$w itemconfigure odgw_gaos -fill white
	}
	if { $ttwfsCount > 0 } {
		if { [$gemsSys getTTLoopState] eq "CLOSED" && [string first ttgs $sources] > -1} {
			$w itemconfigure ttgs_gaos -fill green
		} else {
			$w itemconfigure ttgs_gaos -fill yellow
		}
	} else {
		$w itemconfigure ttgs_gaos -fill white
	}
	if { [AO state oiwfs] } {
		if {[$gemsSys getFlexLoopState] eq "CLOSED" && [string first oigs $sources] > -1 } {
			$w itemconfigure oiwfs_gaos -fill green
		} else {
			$w itemconfigure oiwfs_gaos -fill yellow
		}
	} else {
		$w itemconfigure oiwfs_gaos -fill white
	}
	if {[AO state gaos]} {
		if {[AO state m1] && [AO source m1 Altair]} {
			$w itemconfigure gaos_m1 -fill green
		} else {
			$w itemconfigure gaos_m1 -fill yellow
		}
	} else {
		$w itemconfigure gaos_m1 -fill white
	}
	if {[AO state gaos]} {
		if {[AO state m2] && [AO source m2 GAOS A]} {
			$w itemconfigure gaos_m2 -fill green
		} else {
			$w itemconfigure gaos_m2 -fill yellow
		}
	} else {
		$w itemconfigure gaos_m2 -fill white
	}
	if {[AO state gaos]} {
		if {[AO state rotator]} {
			$w itemconfigure gaos_cr -fill green
		} else {
			$w itemconfigure gaos_cr -fill yellow
		}
	} else {
		$w itemconfigure gaos_cr -fill white
	}
}

itcl::body GuideLoop::recolourGaos {} {
	set w $itk_component(canv)

	if { [AO state gaos] } {
		if { [AO state aoSettled] } {
			$w itemconfigure aoSettled -fill green
			if {[calparam cget -site] eq "MK" && $AOtryingToReuseGain} {
				set AOreuseGains 1
				set AOtryingToReuseGain 0
			}
		} else {
			  $w itemconfigure aoSettled -fill yellow
		}
	}
	if { $gaosWidget ne "" } {
			$gaosWidget recolor
	}
	if { [calparam cget -site] eq "CP" } {
		recolourGemsArrows
	} else {
		recolourAltairArrows
	}
}

itcl::body GuideLoop::enableGaos {} {
	if { $gaosWidget ne "" } {
		$gaosWidget enable
	}
}

itcl::body GuideLoop::resetGaos {} {
	if { $gaosWidget ne "" } {
		$gaosWidget reset
	}
}

itcl::body GuideLoop::onGemsChange {reasons} {
	set shouldRecolor 0
	foreach reason $reasons {
		switch -glob $reason {
		ttLoopState -
		flexLoopState -
		focLoopState -
		m1OffloadState -
		m2OffloadState -
		rotOffloadState -
		ttLoopSources -
		gemsActive -
		ttwfsActive* -
		odgwActive* -
		sfsActive -
		gemsActive -
		loopsSettled {
			set shouldRecolor 1
			break
		}
		}
	}
	if { $shouldRecolor } {
		recolour
	}
}
