#+
#  GuideLoop <- itk::Widget
#
#  A GuideLoop is a diagram of the various guiding loops with control
#  for setting them up and enabling them
##  Options:
#           none
#
#  Methods:
#           none
#
#  D Terrett  29 April 2004
#
#  Copyright CCLRC
#+

itcl::class GuideLoop {
   inherit itk::Widget
   constructor args {}
   destructor {}
   public {
      method reset {}
      method recolour {args}
   }
   private {
      method comacorr {op}
      method m2mode {probe val}
      method mtmode {val}
		method crmode {val}
      method configProbeTracking {}
      method wfsmode {wfs val}
      method configP1Ex {}
      method configP2Ex {}
      method configOiEx {}
      method configHREx {}
      method enable {}
      method m1mode {state}
      variable monids
		variable gemsSys ""
		
		variable gaosWidget ""
		method buildGaos {}
		method buildAltairArrows {}
		method buildGemsArrows {}
		method recolourAltairArrows {}
		method recolourGemsArrows {}
		method recolourGaos {}
		method enableGaos {}
		method resetGaos {}
		method onGemsChange {reasons}
      method onIgnoreAOChange {name1 name2 op}
   }
   itk_option define -wfsConfigObj wfsConfigObj WfsConfigObj "" {
   	if { $itk_option(-wfsConfigObj) ne "" } { recolour }
   }
	itk_option define -wfsAlarmObj wfsAlarmObj WfsAlarmObj "" { 
		if { $itk_option(-wfsAlarmObj) ne "" } { recolour }
	}
}

itk::usual GuideLoop {
   keep -cursor -foreground -background
}

itcl::body GuideLoop::constructor args {
# Create canvas.
   itk_component add canv {
#AWE      canvas $itk_interior.canv -width 630 -height 497 -borderwidth 2 
      canvas $itk_interior.canv -width 695 -height 475 -borderwidth 2 \
            -relief sunken
   }
   pack $itk_component(canv)
   set w $itk_component(canv)
   AO setCanvas $itk_component(canv)
   bind $w <Button-2> {
       puts "on canvas x: %x y: %y"
   }

   # rectangle to group WFS
   $w create rectangle 0 0 337 156 -tags "wfs_comb"
   # PWFS1 box
	itk_component add pwfs1 {
		WfsWidget $w.pwfs1 -label P1 -onswitchpress [itcl::code $this wfsmode pwfs1] -background grey \
		    -onexpselect [itcl::code $this configP1Ex]
	} {
		usual
	}
   [$itk_component(pwfs1) component exp] configure -labelpos nw
   if { [calparam cget -site] eq "CP" } {
      $itk_component(pwfs1) configure -expvalues [list 1.0 0.5 0.1 0.05 0.02 0.01]
   }
	$itk_component(pwfs1) setExp [AO cget -pwfs1Expose]
	$w create window 0 0 -window $w.pwfs1 -tags "wfs_comb pwfs1" -anchor nw
   # PWFS2 box
   itk_component add pwfs2 {
		WfsWidget $w.pwfs2 -label P2 -onswitchpress [itcl::code $this wfsmode pwfs2] \
		    -onexpselect [itcl::code $this configP2Ex]
	} {
		usual
	}
   [$itk_component(pwfs2) component exp] configure -labelpos nw
	$itk_component(pwfs2) setExp [AO cget -pwfs2Expose]
	$w create window 0 0 -window $w.pwfs2 -tags "wfs_comb pwfs2" -anchor nw
   # HRWFS box
   itk_component add hrwfs {
      WfsWidget $w.hrwfs -label HR -explabel Sec -onswitchpress [itcl::code $this wfsmode hrwfs] \
          -expvalues [list 0.01 0.1 1.0 10.0] -onexpselect [itcl::code $this configHREx]
   } {
      usual
   }
   [$itk_component(hrwfs) component exp] configure -labelpos nw
   $itk_component(hrwfs) setExp [AO cget -hrwfsExpose]
   $w create window 0 0 -window $w.hrwfs -tags "wfs_comb hrwfs" -anchor nw
   # OIWFS including an AO mode for NICI
#   itk_component add oiwfs {
#      WfsWidget $w.oiwfs -label OI -onswitchpress [itcl::code $this wfsmode oiwfs] \
#          -onexpselect [itcl::code $this configOiEx]
#   } {
#      usual
#   }
#   [$itk_component(oiwfs) component exp] configure -labelpos nw
#   $itk_component(oiwfs) setExp [AO cget -oiwfsExpose]
#   $w create window 0 0 -width 100 -window $w.oiwfs -tags "wfs_comb oiwfs" -anchor nw
   
   itk_component add oiwfs {
	  ToggleButton $w.oiwfs -text OI -pushedbackground Green -pady 0 \
        -command [itcl::code $this wfsmode oiwfs]
   } {
      usual
   }
   $w create window 32 2 -width 48 -window $w.oiwfs -tags "wfs_comb oiwfs" -anchor nw
   $w create rectangle 0 0 110 68 -fill white -tags "active wfs_comb oiwfs oiwfs_bg"
#   $w create rectangle 2 26 60 47 -fill white -tags "active wfs_comb oiwfs oiwfs_ao"
#   $w create rectangle 63 26 121 47 -fill white -tags "active wfs_comb oiwfs oiwfs_wfs"
   $w create rectangle 2 2 30 20 -fill white -tags "active wfs_comb oiwfs oiwfs_ao"
   $w create rectangle 80 2 108 20 -fill white -tags "active wfs_comb oiwfs oiwfs_wfs"

# OIWFS controls.
   itk_component add oiwfs_ex {
      iwidgets::combobox $w.oiwfs_ex -arrowrelief flat -width 5 \
            -validate real -labeltext "Sec/Hz" -labelpos nw -selectioncommand [itcl::code $this configOiEx]
   }

   $w create window 55 24 -window $w.oiwfs_ex -tag "oiwfs wfs_comb" -anchor n
   $w.oiwfs_ex insert list end 1.0 0.5 0.1 0.05 0.02 0.01 0.005
   $w.oiwfs_ex insert entry end [AO cget -oiwfsExpose]
   [$w.oiwfs_ex component list] configure -hscrollmode none \
         -vscrollmode none

	set font [$itk_component(oiwfs) cget -font]
   $w create text 16 11 -text AO -tags "wfs_comb oiwfs oiwfs_aotxt" -font $font
   $w create text 94 11 -text WFS -tags "wfs_comb oiwfs oiwfs_wfstxt" -font $font

# display aoSettled state
   $w create rectangle 0 0 100 20 -fill white -tags "settled aoSettled active"
   $w create text 50 10 -text "AO Settled" -tags settled -font $font
	
	buildGaos
	
	$w create text 168 12 -text WFS -tags wfs_comb -font $font

# M1, M2 and Mount boxes.
   $w create rectangle 0 0 227 111 -fill white -tags "active m2 m2_bg"
   $w create text 113 10 -text M2 -tags m2 -font $font
   $w create rectangle 4 20 123 107 -fill white -tags "active m2 m2_bg"
   $w create text 89 52 -text TIP/TILT -tags m2 -font $font
   $w create text 89 72 -text FOCUS -tags m2 -font $font
   $w create rectangle 123 20 223 107 -fill white -tags "active m2 m2xy m2xy_bg"
   $w create text 147 63 -text "COMA" -tags "m2 m2xy" -font $font
   $w create rectangle 0 0 244 44 -fill white -tags "active m1 m1_bg"
   $w create text 122 12 -text "M1 Figure" -tags m1 -font $font
   $w create rectangle 0 0 85 44 -fill white -tags "active mount mount_bg"
   $w create text 42 12 -text Mount -tags mount -font $font
	$w create rectangle 0 0 75 44 -fill white -tags "active rotator rotator_bg"
	$w create text 37 12 -text "Cass Rot" -tags rotator -font $font

# Controls for M1.
   itk_component add m1src {
      SelectButton $w.m1src -orient horizontal \
            -command [itcl::code $this m1mode]
   } {
      usual
      rename -offbackground -background background Background
   }
   $w create window 2 22 -width 240 -window $w.m1src -tags m1 -anchor nw
   $itk_component(m1src) add P1 -pady 0
   $itk_component(m1src) add P2 -pady 0
   $itk_component(m1src) add HR -pady 0
   $itk_component(m1src) add OI -pady 0
   $itk_component(m1src) add AO -pady 0

# Controls for M2
   itk_component add m2p1 {
		ToggleButton $w.m2p1 -text P1 -pushedbackground Green -pady 0 -padx 0 \
            -command [itcl::code $this m2mode p1]
   } {
      usual
   }
   $w create window 6 22 -width 50 -window $itk_component(m2p1) -tags m2 -anchor nw

   itk_component add m2p2 {
		ToggleButton $w.m2p2 -text P2 -pushedbackground Green -pady 0 -padx 0 \
            -command [itcl::code $this m2mode p2]
   } {
      usual
   }
   $w create window 6 43 -width 50 -window $itk_component(m2p2) -tags m2 -anchor nw

   itk_component add m2oi {
		ToggleButton $w.m2oi -text OI -pushedbackground Green -pady 0 -padx 0 \
            -command [itcl::code $this m2mode oi]
   } {
      usual
   }
   $w create window 6 64 -width 50 -window $itk_component(m2oi) -tags m2 -anchor nw

   itk_component add m2ao {
		ToggleButton $w.m2ao -text AO -pushedbackground Green -pady 0 -padx 0 \
            -command [itcl::code $this m2mode ao]
   } {
      usual
   }
   $w create window 6 85 -width 50 -window $itk_component(m2ao) -tags m2 -anchor nw

   itk_component add m2coma {
      SelectButton $w.m2coma -orient vertical \
            -command [itcl::code $this comacorr]
   } {
      usual
      rename -offbackground -background background Background
   }
   $w create window 173 22 -width 50 -window $w.m2coma -tags m2 -anchor nw
   $itk_component(m2coma) add P1 -pady 0
   $itk_component(m2coma) add HR -pady 0
   $itk_component(m2coma) add AO -pady 0

# Controls for Mount.
   itk_component add mt {
		SelectButton $w.mt -orient horizontal \
            -command [itcl::code $this mtmode]
   } {
      usual
		rename -offbackground -background background Background
   }
   $w create window 43 22 -width 60 -window $itk_component(mt) -tags mount -anchor n
   $itk_component(mt) add M2 -pady 0

	# Controls for Cass-rotator.
	itk_component add rotator {
		SelectButton $w.rotator -orient horizontal \
				-command [itcl::code $this crmode]
	} {
		usual
		rename -offbackground -background background Background
	}
	$w create window 38 22 -width 50 -window $itk_component(rotator) -tags rotator -anchor n
	$itk_component(rotator) add AO -pady 0

# Box for WFS probes.
   $w create rectangle 0 0 82 44 -fill white -tags "active probes probes_bg wfs_comb"
   $w create text 41 12 -text PROBES -tags "probes wfs_comb" -font $font

# Controls for probes.
   itk_component add prsel {
      iwidgets::combobox $w.prsel -arrowrelief flat -width 6 \
            -selectioncommand [itcl::code $this configProbeTracking]
   }

   $w.prsel insert list end None "P1->P1" "P2->P2" "OI->P1" "OI->P2" "OI->OI"
   $w.prsel insert entry end None
   [$w.prsel component list] configure -hscrollmode none \
         -vscrollmode none
   $w create window 2 22 -window $w.prsel -tag "probes wfs_comb" -anchor nw

# Move boxes into position.
   $w move m2 88 10
   #$w move m2xy 269 10
   $w move m1 79 296
   $w move settled 482 30
   $w move pwfs1 4 20
   $w move pwfs2 77 20
   $w move hrwfs 150 20
   $w move oiwfs 223 20
   $w move probes 127 108
   $w move wfs_comb 33 130
   $w move mount 159 404
	$w move rotator 164 350

# PWFS to M1 and M2
   $w create line 33 184 23 184 -width 3 -fill white \
      -tags {active wfs_head}
   $w create line 23 184 23 318 79 318 -width 3 -fill white \
      -tags {active wfs_m1} -arrow last -arrowshape {20 20 7}
   $w create line 23 184 23 52 88 52 -width 3 -fill white \
      -tags {active wfs_m2} -arrow last -arrowshape {20 20 7}

# WFS to Probes
   $w create line 201 228 201 238 -width 3 -fill white \
      -tags {active wfs_pr_tail}
   $w create line 73 219 73 228 146 228 -width 3 -fill white \
      -tags {active pwfs1_pr}
   $w create line 146 219 146 228 -width 3 -fill white \
      -tags {active pwfs2_pr}
   $w create line 146 228 201 228 -width 3 -fill white \
      -tags {active pwfs12_pr}
   $w create line 311 219 311 228 201 228 -width 3 -fill white \
      -tags {active oiwfs_pr}

# M2 to mount
   $w create line 88 20 12 20 12 426 159 426 -width 3 -fill white \
         -tags {active m2_mt} -arrow last -arrowshape {20 20 7}


# ENABLE/DISABLE/RESET buttons.
# display loopProcessing state
   $w create rectangle 0 0 100 20 -fill white -tags "processing processing_bg"
   $w create text 50 10 -text IDLE -tags "processingText processing" -font $font
   $w move processing 420 420

   itk_component add on {
      LiveButton $w.on -text Enable -command [itcl::code $this enable]
   }
   itk_component add off {
       LiveButton $w.off -text Disable -command { AO disable }
   }
   itk_component add reset {
      button $w.reset -text Reset -command [itcl::code $this reset]
   }
   $w create window 430 459 -window $itk_component(on)
   $w create window 510 459 -window $itk_component(off)
   $w create window 590 459 -window $itk_component(reset)

# Monitor the guide states
   foreach rec {p1state p2state oistate aostate m2state absorbtilt m1state \
         m1source p1guide p2guide oiguide p1mweight p2mweight m2p1guide m2p2guide \
         m2oiguide m2aoguide coma oiblend aoTTGS aoSFO ttgsloop sfoloop useLwfs} {
      if { [llength [itcl::find objects ::guideConfig.$rec]] == 0 } {
         RecordMonitor ::guideConfig.$rec guideConfig $rec
      }
      lappend monids [::guideConfig.$rec add [itcl::code $this recolour]]
   }
	if { [calparam cget -site] eq "CP" } {
		foreach rec {niciAOloop niciAPD crGuide} {
			if { [llength [itcl::find objects ::guideConfig.$rec]] == 0 } {
				RecordMonitor ::guideConfig.$rec guideConfig $rec
			}
			lappend monids [::guideConfig.$rec add [itcl::code $this recolour]]
		}
		
		set gemsSys [::GemsSys::getSingleton]
		$gemsSys subscribe [itcl::code $this onGemsChange]
	}
   #Add monitor for HRWFS
   if { [llength [itcl::find objects ::hrwfs.observeC]] == 0 } {
      RecordMonitor ::hrwfs.observeC hrwfs::observeC observe
   }
   lappend monids [::hrwfs.observeC add [itcl::code $this recolour]]
   
   trace add variable ::Flags(ignoreao) write [itcl::code $this onIgnoreAOChange]
   onIgnoreAOChange ::Flags ignoreao w

# Schedule an update once the channels have connected.
   after 1000 [itcl::code $this recolour]

   eval itk_initialize $args
}

itcl::body GuideLoop::destructor {} {
   trace remove variable ::Flags(ignoreao) write [itcl::code $this onIgnoreAOChange]
   ::hrwfs.observeC remove [lindex $monids end]
   set monids [lreplace $monids end end]
   foreach rec {p1state p2state oistate aostate m2state absorbtilt m1state \
      	m1source p1guide p2guide oiguide p1mweight p2mweight m2p1guide m2p2guide \
	 		m2oiguide m2aoguide coma oiblend aoTTGS aoSFO ttgsloop sfoloop useLwfs niciAOloop niciAPD crGuide} mon $monids {
		if { ( $rec ne "niciAOloop" && $rec ne "niciAPD" && $rec ne "crGuide") || [calparam cget -site] eq "CP" } {
			::guideConfig.$rec remove $mon
		}
	}
}

itcl::body GuideLoop::recolour args {

	set w $itk_component(canv)
	
# Assume no signal to mount
   set mount 0

# Set everything to white.
   $w itemconfigure active -fill white

# P1 signals.
   set wfs12_pr ""
   set pr_tail ""
   set wfs_head ""
   set wfs_m1 ""
   set wfs_m2 ""

   if { [AO state pwfs1] } {
		$itk_component(pwfs1) configure -status on
		$w itemconfigure pwfs1_bg -fill green

      set wfs12_pr yellow
      set pr_tail yellow
      set wfs_head yellow
      set wfs_m1 yellow
      set wfs_m2 yellow      
      
      if { [AO state m1] && [AO source m1 PWFS1] } {
         set wfs_head green
         set wfs_m1 green
      }
      if { ( [AO state m2] && ([AO source m2 PWFS1 A] || [AO source m2 PWFS1 B]) ) \
         || ( [AO state coma] && [AO source m1 PWFS1] ) } {
         set wfs_head green
         set wfs_m2 green
      }
      
      if { [AO state p1guide] } {
         $w itemconfigure pwfs1_pr -fill green
         set wfs12_pr green
         set pr_tail green
      } else {
         $w itemconfigure pwfs1_pr -fill yellow
      }
      if { [AO state mount] && [AO source mount PWFS1] } {
         $w itemconfigure pwfs1_mt -fill green
         set mount 1
      } else {
         $w itemconfigure pwfs1_mt -fill yellow
      }
   } else {
		$itk_component(pwfs1) configure -status off
   }

# P2 signals
   if { [AO state pwfs2] } {
		$itk_component(pwfs2) configure -status on
      $w itemconfigure pwfs2_bg -fill green
      
      if { $wfs12_pr eq "" } { set wfs12_pr yellow }
      if { $pr_tail eq "" } { set pr_tail yellow }
      if { $wfs_head eq "" } { set wfs_head yellow }
      if { $wfs_m1 eq "" } { set wfs_m1 yellow }
      if { $wfs_m2 eq "" } { set wfs_m2 yellow }
      
      if { [AO state m1] && [AO source m1 PWFS2] } {
         set wfs_head green
         set wfs_m1 green
      }
      if { [AO state m2] && ([AO source m2 PWFS2 A] || [AO source m2 PWFS2 B]) } {
         set wfs_head green
         set wfs_m2 green
      }
      if { [AO state p2guide] } {
         $w itemconfigure pwfs2_pr -fill green
         set wfs12_pr green
         set pr_tail green
      } else {
         $w itemconfigure pwfs2_pr -fill yellow
      }
      if { [AO state mount] && [AO source mount PWFS2] } {
         $w itemconfigure pwfs2_mt -fill green
         set mount 1
      } else {
         $w itemconfigure pwfs2_mt -fill yellow
      }
   } else {
		$itk_component(pwfs2) configure -status off
	}
# HR signals
   if { [AO state hrwfs] } {
      $itk_component(hrwfs) configure -status on
      $w itemconfigure hrwfs_bg -fill green
      
      if { $wfs_head eq "" } { set wfs_head yellow }
      if { $wfs_m1 eq "" } { set wfs_m1 yellow }
      if { $wfs_m2 eq "" } { set wfs_m2 yellow }
      
      if { [AO state m1] && [AO source m1 HRWFS] } {
         set wfs_head green
         set wfs_m1 green
      }
      if { [AO state coma] && [AO source m1 HRWFS] } {
         set wfs_head green
         set wfs_m2 green
      }
   } else {
      $itk_component(hrwfs) configure -status off
   }
# OIWFS signals
   if { [AO state oiao] } {
      # disable the regular oiwfs guide alarm and enable the nici guide alarm
      if { $itk_option(-wfsAlarmObj) ne "" } {
			$itk_option(-wfsAlarmObj) disableWfs oiwfs
			$itk_option(-wfsAlarmObj) enableWfs nici
		}

      $w itemconfigure oiwfs_ao -outline black 
      $w itemconfigure oiwfs_wfs -outline grey
      $w itemconfigure oiwfs_aotxt -fill black 
      $w itemconfigure oiwfs_wfstxt -fill grey
      $itk_component(oiwfs_ex) configure -state disabled
      if { $itk_option(-wfsConfigObj) ne "" } {
      	$itk_option(-wfsConfigObj) niciState normal
		}
      if { [AO state oiaoAPD] } {
         $w itemconfigure oiwfs_ao -fill green
      }
      if { [AO state oiaoLoop] } {
         $w itemconfigure oiwfs_bg -fill green
#         if { [$itk_component(prfrom) get] == "OI" && [$itk_component(prto) get] == "P2" } {
#            $w itemconfigure oiwfs_pr -fill green
#         } else {
#            $w itemconfigure oiwfs_pr -fill yellow
#         }
      }
   } elseif { [AO state oiwfs] } {
      # enable the regular oiwfs guide alarm and disable the nici guide alarm
      if { $itk_option(-wfsAlarmObj) ne "" } {
			$itk_option(-wfsAlarmObj) disableWfs nici
			$itk_option(-wfsAlarmObj) enableWfs oiwfs
		}

      $w itemconfigure oiwfs_bg -fill green
      $w itemconfigure oiwfs_ao -outline grey
      $w itemconfigure oiwfs_wfs -outline black
      $w itemconfigure oiwfs_aotxt -fill grey 
      $w itemconfigure oiwfs_wfstxt -fill black
      $itk_component(oiwfs_ex) configure -state disabled
      if { $itk_option(-wfsConfigObj) ne "" } {
			$itk_option(-wfsConfigObj) niciState normal
		}
      
      if { $pr_tail eq "" } { set pr_tail yellow }
      if { $wfs_head eq "" } { set wfs_head yellow }
      if { $wfs_m1 eq "" } { set wfs_m1 yellow }
      if { $wfs_m2 eq "" } { set wfs_m2 yellow }

      if { [AO state m1] && [AO source m1 OIWFS] } {
         set wfs_head green
         set wfs_m1 green
      }
      if { ( [AO state m2] && ([AO source m2 OIWFS A] || [AO source m2 OIWFS B]) ) \
            || ([AO state coma] && [AO source m1 OIWFS] ) } {
         set wfs_head green
         set wfs_m2 green
      }
      if { [AO state oiguide] } {
         $w itemconfigure oiwfs_pr -fill green
         set pr_tail green
      } else {
         $w itemconfigure oiwfs_pr -fill yellow
      }
   } else {
      # enable the regular oiwfs guide alarm and disable the nici guide alarm
      if { $itk_option(-wfsAlarmObj) ne "" } {
			$itk_option(-wfsAlarmObj) disableWfs nici
			$itk_option(-wfsAlarmObj) enableWfs oiwfs
		}
      
      $w itemconfigure oiwfs_ao -outline grey
      $w itemconfigure oiwfs_wfs -outline black
      $w itemconfigure oiwfs_aotxt -fill grey 
      $w itemconfigure oiwfs_wfstxt -fill black
      $itk_component(oiwfs_ex) configure -state normal
      if { $itk_option(-wfsConfigObj) ne "" } {
			$itk_option(-wfsConfigObj) niciState disabled
		}
   }
   
   if { $wfs12_pr ne "" } { $w itemconfigure pwfs12_pr -fill $wfs12_pr }
   if { $pr_tail ne "" } { $w itemconfigure wfs_pr_tail -fill $pr_tail }
   if { $wfs_head ne "" } { $w itemconfigure wfs_head -fill $wfs_head }
   if { $wfs_m1 ne "" } { $w itemconfigure wfs_m1 -fill $wfs_m1 }
   if { $wfs_m2 ne "" } { $w itemconfigure wfs_m2 -fill $wfs_m2 }
   
	recolourGaos

# M1
   if { [AO state m1] } {
      if { ( [AO source m1 PWFS1] && [AO state pwfs1] ) ||	\
            ( [AO source m1 PWFS2] && [AO state pwfs2] ) ||	\
            ( [AO source m1 OIWFS] && [AO state oiwfs] ) ||	\
            ( [AO source m1 GAOS] && [AO state gaos] && ([calparam cget -site] ne "CP" || [[AO getGaosObj] state m1Offload]) )  } {
         $w itemconfigure m1_bg -fill green
      } else {
         $w itemconfigure m1_bg -fill yellow
      }
   }

# M2
   if { [AO state m2] } {
      if { ( ( [AO source m2 PWFS1 A] || [AO source m2 PWFS1 B] ) && \
            [AO state pwfs1] ) || \
            ( ( [AO source m2 PWFS2 A] || [AO source m2 PWFS2 B] ) && \
            [AO state pwfs2] ) || \
            ( ( [AO source m2 OIWFS A] || [AO source m2 OIWFS B] ) && \
            [AO state oiwfs] ) || \
            ( ( [AO source m2 GAOS A] || [AO source m2 GAOS B] ) && \
            ( ( [calparam cget -site] eq "MK" && [AO state gaos] ) || \
				  ( [calparam cget -site] eq "CP" && [AO state ttgsloop] && [[AO getGaosObj] state m2Offload]) ) )  } {
         $w itemconfigure m2_bg -fill green
         if { [AO source mount M2] && [AO state mount] } {
            $w itemconfigure m2_mt -fill green
            set mount 1
         } else {
            $w itemconfigure m2_mt -fill yellow
         }
      } else {
         $w itemconfigure m2_bg -fill yellow
         $w itemconfigure m2_mt -fill yellow
      }
   }

# M2 Coma
   if { [AO state coma] } {
      if { ( [AO state pwfs1] && [AO source m1 PWFS1] ) \
            || ( [AO state hrwfs] && [AO source m1 HRWFS] ) \
            || ( ( [AO state gaos] && ([calparam cget -site] ne "CP" || [[AO getGaosObj] state m2Offload])) && [AO source m1 GAOS] ) } {
         $w itemconfigure m2xy_bg -fill green
      } else {
         $w itemconfigure m2xy_bg -fill yellow
      }
   }

# M2 guide source buttons.
#   if { [AO source m2 PWFS1] } {
#      $itk_component(m2p1) mark
#   }
#   if { [AO source m2 PWFS2] } {
#      $itk_component(m2p2) mark
#   }
#   if { [AO source m2 OIWFS] } {
#      $itk_component(m2oi) mark
#   }
#   if { [AO source m2 GAOS] } {
#      $itk_component(m2ao) mark
#   }

# Mount
   if { [AO state mount] } {
      if { $mount } {
         $w itemconfigure mount_bg -fill green
      } else {
         $w itemconfigure mount_bg -fill yellow
      }
   }
#Rotator
	if { [calparam cget -site] eq "CP" && [AO state rotator] } {
		if { [AO state ttgsloop] && [[AO getGaosObj] state rotOffload]} {
			$w itemconfigure rotator_bg -fill green
		} else {
			$w itemconfigure rotator_bg -fill yellow
		}
	}
# WFS probes
   if { ( [AO state p1guide] && [AO state pwfs1] ) \
      || ( [AO state p2guide] && [AO state pwfs2] ) \
      || ( [AO state oiguide] && ([AO state oiwfs] || ( [AO state oiao] && [AO state oiaoLoop] ) ) )
   } {
		$w itemconfigure probes_bg -fill green
   } elseif { [AO state p1guide] || [AO state p2guide] || [AO state oiguide] } {
		$w itemconfigure probes_bg -fill yellow
   }
}

itcl::body GuideLoop::comacorr {state} {
   switch $state {
   P1 {
		AO configure -comacorr 1
      AO configure -m1source PWFS1
      #Synchronize M1 selection control
      if { [$itk_component(m1src) get] ne "" && [$itk_component(m1src) get] ne "P1" } {
         $itk_component(m1src) select P1
      }
	}
   HR {
		AO configure -comacorr 1
      AO configure -m1source HRWFS
      #Synchronize M1 selection control
      if { [$itk_component(m1src) get] ne "" && [$itk_component(m1src) get] ne "HR" } {
         $itk_component(m1src) select HR
      }
   }
   AO {
      AO configure -comacorr 1
      AO configure -m1source GAOS
      #Synchronize M1 selection control
      if { [$itk_component(m1src) get] ne "" && [$itk_component(m1src) get] ne "AO" } {
         $itk_component(m1src) select AO
      }
	}
   default {
      AO configure -comacorr 0
   }
   }
}

itcl::body GuideLoop::m2mode {probe val} {
	switch $val {
	push {
      AO configure -${probe}guide On
   } 
	pop {
      AO configure -${probe}guide ""
   }
	}
}

itcl::body GuideLoop::mtmode {val} {
   switch $val {
      P1 {
         AO configure -mountguide PWFS1
      }
      P2 {
         AO configure -mountguide PWFS2
      }
      M2 {
         AO configure -mountguide SCS
      }
		"" {
         AO configure -mountguide none
      }
   }
}

itcl::body GuideLoop::crmode {val} {
	switch $val {
		AO {
			AO configure -crsource GAOS
		}
		"" {
			AO configure -crsource ""
		}
	}
}

itcl::body GuideLoop::configProbeTracking {} {
   switch "[$itk_component(prsel) get]" {
   "P1->P1" {
      AO configure -probefrom PWFS1
      AO configure -probeto PWFS1
      AO configure -probeguide ON
   }
   "P2->P2" {
      AO configure -probefrom PWFS2
      AO configure -probeto PWFS2
      AO configure -probeguide ON
   }
   "OI->P1" {
      AO configure -probefrom OIWFS
      AO configure -probeto PWFS1
      AO configure -probeguide ON
   }
   "OI->P2" {
      AO configure -probefrom OIWFS
      AO configure -probeto PWFS2
      AO configure -probeguide ON
   }
   "OI->OI" {
      AO configure -probefrom OIWFS
      AO configure -probeto OIWFS
      AO configure -probeguide ON
   }
   default {
      AO configure -probeguide OFF
   }
   }
}

itcl::body GuideLoop::wfsmode {wfs val} {
   if { [AO state oiao] && $wfs == "oiwfs" } {
		switch $val {
		push {
			AO configure -oiaoLoop 1
		}
		pop {
			AO configure -oiaoLoop 0
		}
      }
   } else {
      switch $val {
		push {
			AO configure -${wfs}Active 1
		}
		pop {
			AO configure -${wfs}Active 0
		}
      }
   }
}

itcl::body GuideLoop::configP1Ex {} {
   AO configure -pwfs1Expose [$itk_component(pwfs1) getExp]
   Pwfs1 configure -exposetime [$itk_component(pwfs1) getExp]
}
itcl::body GuideLoop::configP2Ex {} {
   AO configure -pwfs2Expose [$itk_component(pwfs2) getExp]
   Pwfs2 configure -exposetime [$itk_component(pwfs2) getExp]
}
itcl::body GuideLoop::configOiEx {} {
   AO configure -oiwfsExpose [$itk_component(oiwfs_ex) get]
   Oiwfs configure -exposetime [$itk_component(oiwfs_ex) get]
}
itcl::body GuideLoop::configHREx {} {
   AO configure -hrwfsExpose [$itk_component(hrwfs) getExp]
}

itcl::body GuideLoop::enable {} {
   enableGaos
   AO enable
}

itcl::body GuideLoop::m1mode {state} {
	switch $state {
	P1 {
		AO configure -m1source PWFS1
      AO configure -m1corr 1
      #Synchronize coma selection control
      if { [$itk_component(m2coma) get] ne "" && [$itk_component(m2coma) get] ne "P1" } {
         $itk_component(m2coma) select P1
      }
	}
	P2 {
		AO configure -m1source PWFS2
		AO configure -m1corr 1
      #Synchronize coma selection control
      if { [$itk_component(m2coma) get] ne "" } {
         $itk_component(m2coma) select ""
      }
   }
   HR {
      AO configure -m1source HRWFS
      AO configure -m1corr 1
      #Synchronize coma selection control
      if { [$itk_component(m2coma) get] ne "" && [$itk_component(m2coma) get] ne "HR" } {
         $itk_component(m2coma) select HR
      }
   }
	OI {
		AO configure -m1source OIWFS
      AO configure -m1corr 1
      #Synchronize coma selection control
      if { [$itk_component(m2coma) get] ne "" } {
         $itk_component(m2coma) select ""
      }
	}
	AO {
		AO configure -m1source GAOS
      AO configure -m1corr 1
      #Synchronize coma selection control
      if { [$itk_component(m2coma) get] ne "" && [$itk_component(m2coma) get] ne "AO" } {
         $itk_component(m2coma) select AO
      }
	}
	default {
      AO configure -m1corr 0
	}
	}
}

itcl::body GuideLoop::reset {} {

# Disable
   AO process IDLE
   AO disable

# Simulate pushing all the "off" buttons.
   $itk_component(pwfs1) switchPop
   $itk_component(pwfs2) switchPop
   $itk_component(hrwfs) switchPop
   $itk_component(oiwfs) pop
   $itk_component(m1src) select ""
   $itk_component(m2p1) pop
   $itk_component(m2p2) pop
   $itk_component(m2ao) pop
   $itk_component(m2oi) pop
   $itk_component(m2coma) select ""
   $itk_component(mt) select ""
	$itk_component(rotator) select ""
	$itk_component(prsel) clear entry
   $itk_component(prsel) insert entry end None
	resetGaos
	AO configure -probeto ""
}

itcl::body GuideLoop::buildGaos {} {
	set w $itk_component(canv)
	if { [calparam cget -site] eq "CP" } {
		itk_component add gaos { GemsWidget $w.gaos -aocontroller [AO getGaosObj] }
		$w create window 443 62 -window $w.gaos -tags gaos -anchor nw
		set gaosWidget $itk_component(gaos)
		buildGemsArrows
	} else {
		itk_component add gaos { AltairWidget $w.gaos -aocontroller AO }
		$w create window 481 72 -window $w.gaos -tags gaos -anchor nw
		set gaosWidget $itk_component(gaos)
		buildAltairArrows
	}
}

itcl::body GuideLoop::buildAltairArrows {} {
	set w $itk_component(canv)
	$w create line 480 83 315 83  -width 3 -fill white -tags {active gaos_m2} \
		-arrow last -arrowshape {20 20 7}
	$w create line 501 288 501 318 323 318 -width 3 -fill white \
		-tags {active gaos_m1} -arrow last -arrowshape {20 20 7}
	$w create line 371 184 425 184 425 140 480 140 -width 3 -fill white \
		-tags {active wfs_gaos} -arrow last -arrowshape {20 20 7}

	# GAOS internal
	$w create line 617 200 642 200 642 152 617 152 -width 3 -fill white \
		-tags {active ttgs_gaos} -arrow last -arrowshape {20 20 7}
	$w create line 617 260 652 260 652 131 617 131 -width 3 -fill white \
		-tags {active sfo_gaos} -arrow last -arrowshape {20 20 7}

}

itcl::body GuideLoop::recolourAltairArrows {} {
	set w $itk_component(canv)
	
	if { [AO state gaosTTGS] } {
		if { [AO state ttgsloop] } {
			$w itemconfigure ttgs_gaos -fill green
		} else {
			$w itemconfigure ttgs_gaos -fill yellow
		}
	} else {
		$w itemconfigure ttgs_gaos -fill white
	}
	if { [AO state gaosSFO] } {
		if { [AO state sfoloop] } {
			$w itemconfigure sfo_gaos -fill green
		} else {
			$w itemconfigure sfo_gaos -fill yellow
		}
	} else {
		$w itemconfigure sfo_gaos -fill white
	}
	if { [AO state gaos] } {
		if { [AO state m1] && [AO source m1 GAOS] } {
			$w itemconfigure gaos_m1 -fill green
		} else {
			$w itemconfigure gaos_m1 -fill yellow
		}
		if { [AO state m2] && ([AO source m2 GAOS A] || \
				[AO source m2 GAOS B]) } {
			$w itemconfigure gaos_m2 -fill green
		} else {
			$w itemconfigure gaos_m2 -fill yellow
		}
		if { [AO state coma] } {
			$w itemconfigure gaos_m2 -fill green
		} else {
			$w itemconfigure gaos_m2 -fill yellow
		}
	}
   set wfs_gaos ""
   if { [AO state pwfs1] } {
      set wfs_gaos yellow
      if { [AO state lgsp1source] } {
         set wfs_gaos green
      }
   }
   if { [AO state oiwfs] } {
      if { $wfs_gaos eq "" } {
         set wfs_gaos yellow
      }
      if { [AO state oiblend] } {
         set wfs_gaos green
      }
   }
   if { $wfs_gaos ne "" } {
      $w itemconfigure wfs_gaos -fill $wfs_gaos
   }
}

itcl::body GuideLoop::buildGemsArrows {} {
	set w $itk_component(canv)
	$w create line 443 83 315 83  -width 3 -fill white -tags {active gaos_m2} \
		-arrow last -arrowshape {20 20 7}
	$w create line 443 362 383 362 383 318 323 318 -width 3 -fill white \
		-tags {active gaos_m1} -arrow last -arrowshape {20 20 7}
	$w create line 371 184 398 184 -width 3 -fill white \
		-tags {active wfs_gaos}
	$w create line 443 372 239 372 -width 3 -fill white \
		-tags {active gaos_cr} -arrow last -arrowshape {20 20 7}

	# GAOS internal
   $w create line 398 184 398 97 443 97 -width 3 -fill white \
   -tags {active flexend_gaos} -arrow last -arrowshape {20 20 7}
	$w create line 443 248 408 248 408 116 443 116 -width 3 -fill white \
		-tags {active cwfsani_gaos} -arrow last -arrowshape {20 20 7}
	$w create line 443 192 418 192 418 135 443 135 -width 3 -fill white \
		-tags {active sfs_gaos} -arrow last -arrowshape {20 20 7}
	$w create line 645 343 680 343 680 160 645 160 -width 3 -fill white \
	-tags {active odgwtt_gaos} -arrow last -arrowshape {20 20 7}
   $w create line 443 343 398 343 398 184 -width 3 -fill white \
   -tags {active odgwflex_gaos}
   $w create line 645 248 670 248 670 123 645 123 -width 3 -fill white \
   -tags {active cwfstt_gaos} -arrow last -arrowshape {20 20 7}

}

itcl::body GuideLoop::recolourGemsArrows {} {
   if { ! $::Flags(ignoreao) } {
   	set w $itk_component(canv)
   
   	if { [$gemsSys getSFSActive] eq "ON" } {
   		if { [$gemsSys getFocLoopState] eq "CLOSED" } {
   			$w itemconfigure sfs_gaos -fill green
   		} else {
   			$w itemconfigure sfs_gaos -fill yellow
   		}
   	} else {
   		$w itemconfigure sfs_gaos -fill white
   	}
   	set ttSources [$gemsSys getTTLoopSources]
      set flexSources [$gemsSys getFlexLoopSources]
   	set odgwCount 0
   	for {set i 1} {$i <= 4} {incr i} {
   		if {[$gemsSys getODGWActive $i] eq "ON"} {
   			incr odgwCount
   		}
   	}
   	set ttwfsCount 0
   	for {set i 1} {$i <= 3} {incr i} {
   		if {[$gemsSys getTTWFSActive $i] eq "ON"} {
   			incr ttwfsCount
   		}
   	}
      set flextail white
   	if { $odgwCount > 0 } {
   		if { ( [$gemsSys getFlexLoopState] eq "CLOSED" && [string first odgw $flexSources] > -1 ) } {
   			$w itemconfigure odgwflex_gaos -fill green
            set flextail green
   		} else {
   			$w itemconfigure odgwflex_gaos -fill yellow
            set flextail yellow
   		}
         if { [$gemsSys getTTLoopState] eq "CLOSED" && [string first odgw $ttSources] > -1 } {
            $w itemconfigure odgwtt_gaos -fill green
         } else {
            $w itemconfigure odgwtt_gaos -fill yellow
         }
   	} else {
   		$w itemconfigure odgwflex_gaos -fill white
         $w itemconfigure odgwtt_gaos -fill white
   	}
   	if { $ttwfsCount > 0 } {
   		if { [$gemsSys getTTLoopState] eq "CLOSED" && [string first ttgs $ttSources] > -1 } {
   			$w itemconfigure cwfstt_gaos -fill green
   		} else {
   			$w itemconfigure cwfstt_gaos -fill yellow
   		}
         if { [$gemsSys getAniLoopState] eq "CLOSED" } {
            $w itemconfigure cwfsani_gaos -fill green
         } else {
            $w itemconfigure cwfsani_gaos -fill yellow
         }
   	} else {
   		$w itemconfigure cwfsani_gaos -fill white
         $w itemconfigure cwfstt_gaos -fill white
   	}
   	if { [AO state oiwfs] } {
   		if {[$gemsSys getFlexLoopState] eq "CLOSED" && [string first oigs $flexSources] > -1 } {
   			$w itemconfigure wfs_gaos -fill green
            set flextail green
   		} else {
   			$w itemconfigure wfs_gaos -fill yellow
            if { $flextail ne "green" } {
               set flextail yellow
            }
   		}
   	} else {
   		$w itemconfigure wfs_gaos -fill white
   	}
      
      $w itemconfigure flexend_gaos -fill $flextail
      
   	if {[AO state gaos]} {
   		if {[AO state m1] && [AO source m1 GAOS] && [$gemsSys getM1OffloadState] eq "CLOSED"} {
   			$w itemconfigure gaos_m1 -fill green
   		} else {
   			$w itemconfigure gaos_m1 -fill yellow
   		}
   	} else {
   		$w itemconfigure gaos_m1 -fill white
   	}
   	if {[AO state gaos] || [AO state ttgsloop]} {
   		if {[AO state m2] && [AO source m2 GAOS A] && [$gemsSys getM2OffloadState] eq "CLOSED" } {
   			$w itemconfigure gaos_m2 -fill green
   		} else {
   			$w itemconfigure gaos_m2 -fill yellow
   		}
   	} else {
   		$w itemconfigure gaos_m2 -fill white
   	}
   	if {[AO state ttgsloop]} {
   		if {[AO state rotator] && [$gemsSys getRotOffloadState] eq "CLOSED" } {
   			$w itemconfigure gaos_cr -fill green
   		} else {
   			$w itemconfigure gaos_cr -fill yellow
   		}
   	} else {
   		$w itemconfigure gaos_cr -fill white
   	}
   }
}

itcl::body GuideLoop::recolourGaos {} {
   global AOtryingToReuseGain AOreuseGains

	set w $itk_component(canv)
   
   if { [calparam cget -site] eq "MK" } {
      if { [AO state gaos] } {
         if { [AO state aoSettled] } {
            $w itemconfigure aoSettled -fill green
            if {$AOtryingToReuseGain} {
               set AOreuseGains 1
               set AOtryingToReuseGain 0
            }
         } else {
            $w itemconfigure aoSettled -fill yellow
         }
      }
      if { $gaosWidget ne "" } {
         $gaosWidget recolor
      }
      recolourAltairArrows
   } elseif { ! $::Flags(ignoreao) } {
      if { [AO state gaos] } {
   		if { [AO state aoSettled] } {
   			$w itemconfigure aoSettled -fill green
   		} else {
   			  $w itemconfigure aoSettled -fill yellow
   		}
   	}
   	if { $gaosWidget ne "" } {
         $gaosWidget recolor
   	}
   	recolourGemsArrows
   }
}

itcl::body GuideLoop::enableGaos {} {
	if { $gaosWidget ne "" } {
		$gaosWidget enable
	}
}

itcl::body GuideLoop::resetGaos {} {
	if { $gaosWidget ne "" } {
		$gaosWidget reset
	}
}

itcl::body GuideLoop::onGemsChange {reasons} {
	set shouldRecolor 0
	foreach reason $reasons {
		switch -glob $reason {
		ttLoopState -
		flexLoopState -
		focLoopState -
      aniLoopState -
      lwfsLoopState -
		m1OffloadState -
		m2OffloadState -
		rotOffloadState -
		ttLoopSources -
		ttwfsActive* -
		odgwActive* -
		sfsActive -
		gemsActive -
		loopsSettled {
			set shouldRecolor 1
			break
		}
		}
	}
	if { $shouldRecolor } {
		recolour
	}
}

itcl::body GuideLoop::onIgnoreAOChange {name1 name2 op} {
   if { [calparam cget -site ] eq "CP" } {
      if { $::Flags(ignoreao) } {
         $itk_component(rotator) configure -state disabled
         $gaosWidget configure -state disabled
      } else {
         $itk_component(rotator) configure -state normal
         $gaosWidget configure -state normal         
      }
   } else {
      $itk_component(rotator) configure -state disabled
   }
}