#+
# IGemsSys
#
# Interface to the GeMS system. It is implementated by RealGems and SimGems.
#
# J Luhrs 01 April 2009
#
#  $Id: Exp $
#+

itcl::class IGemsSys {
public {
	method slewReset {}
	#Loop control commands
	method openLGSLoop {}
	method closeLGSLoop {}
	method openTTLoop {}
	method closeTTLoop {}
	method openFocLoop {}
	method closeFocLoop {}
	method openFlexLoop {}
	method closeFlexLoop {}
	method openAniLoop {}
	method closeAniLoop {}
	method disableM1Offload {}
	method enableM1Offload {}
	method disableM2Offload {}
	method enableM2Offload {}
	method disableRotOffload {}
	method enableRotOffload {}
	method pauseLoops {why}
	method resumeLoops {}
	method stopLoops {}
   method setupLoops {loopList sources}
	
	#Loop configuration
	method configureNGS {sources}
	
	#Astrometry
	method setAstroMode {mode}
	method startAstrometry {}
	method stopAstrometry {}
	
	method moveADC {pos}
	method startADC {}
	method stopADC {}
	method moveBeamSplitter {pos}

	#WFS control commands
   method setupODGW {idList}
   method startODGW {idList}
   method stopODGW {idList}
	#method startTTWFS {idList}
	#method stopTTWFS {idList}
	method startLGSWFS {}
	method stopLGSWFS {}
	method setODGWExposure {id val}
	#method setTTWFSExposure {id val}
	method setLGSWFSExposure {val}
   
   #ODGW special commands
   method setODGWSize { size {apply 1} }
   method getODGWSize {}
   method setODGWSciRows { num {apply 1} }
   method getODGWSciRows {}
   method setODGWIdleRows { num {apply 1} }
   method getODGWIdleRows {}
   method setODGWDisplay { opt {apply 1} }

   #LIS commands
   method pauseLis {}

	#States
	method getGemsActive {}
	method getLoopsState {}
	method getLGSLoopState {}
	method getTTLoopState {}
	method getFocLoopState {}
	method getFlexLoopState {}
	method getAniLoopState {}
	method getM1OffloadState {}
	method getM2OffloadState {}
	method getRotOffloadState {}
	method getTTLoopSources {}
   method getFlexLoopSources {}
	method getODGWActive {id}
   method getODGWEnabled {id}
	method getTTWFSActive {id}
	method getLGSWFSActive {}
	method getODGWExposure {id}
	method getTTWFSExposure {id}
	method getLGSWFSExposure {}
	method getODGWCounts {id}
	method getTTWFSCounts {id}
	method getLGSWFSCounts {id}
   method getLGSWFSAverage {}
	method getAstroMode {}
	method getAstrometryState {}
	method getADCPos {}
	method getADCLoopState {}
	method getBeamSplitterPos {}
	method getLaserProp {}
   
   #Loops commands state
   method getLGSCmdState {}
   method getLGSCmdMess {}
   method getTTCmdState {}
   method getTTCmdMess {}
   method getFocCmdState {}
   method getFocCmdMess {}
   method getFlexCmdState {}
   method getFlexCmdMess {}
   method getAniCmdState {}
   method getAniCmdMess {}
	
	#Command state
	method getCommandState {}
	method getLastError {}

	#Observable interface
	method subscribe {observer}
	method unsubscribe {observer}
}
}
