#+
#  InstrumentPanel <- Panel
#
#  Implements the InstrumentPanel widget. A Panel widget with a 
#  InstrumentControl widget packed into its interior.
#
#  Methods:
#          none
#
#  D Terrett 6 March 2002
#
#  Copyright CCLRC
#+

itcl::class InstrumentPanel {
   inherit Panel
   constructor args {}
   public {
      method sync {component name} {$itk_component(control) sync $name}
   }
}

itk::usual InstrumentPanel {
   keep -background -cursor
}

itcl::body InstrumentPanel::constructor args {

   setWidgetColors $itk_interior \
         $itk_option(-background) $itk_option(-foreground)

   itk_component add control {
      InstrumentControl $itk_interior.control
   } {
      usual
      rename -component -components components Components
   }

   pack $itk_component(control) -fill both -expand y

   eval itk_initialize $args
}
