#+
#  InstrumentComponent <- Instrument, Component
#
#  An InstrumentComponent object is a Instrument object that is stored in a 
#  configuration list.
#
#  Options:
#           none
#
#  Methods:
#           constructor list  Creates the Instrument object and puts it onto
#                           "list".
#
#  D Terrett 19 September 2001
#
#  Copyright CCLRC
#+

itcl::class InstrumentComponent {
   inherit Component Instrument
   constructor {list args} {
      Component::constructor $list
   } {
      eval configure $args
   }
}
