#+
#  McsControl <- itk::Widget
#
#  An McsControl widget contains various widget for controlling the 
#  mount control system.
#
#  Options:
#           none
#
#  Methods:
#           none
#
#  D Terrett  11 February 2000
#
#  Copyright CCLRC
#+

itcl::class McsControl {
   inherit itk::Widget
   constructor args {}
   private {
      method getParVal {par}
      variable brakes
   }
}

itk::usual McsControl {
   keep -cursor -font -highlightthickness -borderwidth \
         -labelfont -insertborderwidth -insertofftime \
         -insertontime -insertwidth -textfont -selectborderwidth
}

itcl::body McsControl::constructor args {

# Divide the window into 2 vertically.
   itk_component add row1 {
      frame $itk_interior.row1 -bd 2 -relief ridge
   }
   itk_component add row2 {
      frame $itk_interior.row2
   }
   pack $itk_component(row1) $itk_component(row2) -fill x -expand y


# Mount Move command.
   set w $itk_component(row1)
   itk_component add azel {
      ApplyButton $w.azel -command azel \
            -parcommand [itcl::code $this getParVal]
   }
   itk_component add az {
      iwidgets::entryfield $w.az -labeltext [lindex [cs azel info az] 2] \
           -width 10
   }
   itk_component add el {
      iwidgets::entryfield $w.el -labeltext [lindex [cs azel info el] 2] \
            -width 10
   }

   pack $itk_component(az) $itk_component(el) $itk_component(azel) -side left -fill x -expand y -padx 4 -pady 4

# Cass Rotator commands

# Move command.
   set w $itk_component(row2)
   itk_component add move {
      ApplyButton $w.move -command rotMove \
            -parcommand [itcl::code $this getParVal]
   }

   itk_component add rma {
      iwidgets::entryfield $w.rma -labeltext Angle -width 6
   }

   itk_component add rotstop {
      ApplyButton $w.rotstop -command rotStop \
            -parcommand [itcl::code $this getParVal]
   }
   itk_component add brakes {
      checkbutton $w.brakes -onvalue Yes -offvalue No \
            -variable [itcl::scope brakes] -text brake
   }
   pack $itk_component(rma) $itk_component(move) $itk_component(rotstop) $itk_component(brakes) -side left -expand y -fill x -padx 4 -pady 4




   eval itk_initialize $args
}

itcl::body McsControl::getParVal par {
   switch $par {
      brakes {
         return $brakes
      }
      dummy {
         return ""
      }
      default {
         return [$itk_component($par) get]
      }
   }
}
