#+
# Preview
#
# Computes a preview of the telescope and guide probe positions at some
# specified time.
#
# Methods:
#
#    target hmsdegTarget a b system equinox epoch pm1 pm2 parallax rv
#
#    target degdegTarget a b
#
#    target conicTarget type epoch orbinc anode perih aorq e ?aorl dm?
#
#    slew time
#
# Options
#
#    -iaa           Instrument alignment angle
#
#    -poriginA      Source A pointing origin
#
#    -poriginB      Source B pointing origin
#    
# D Terrett  28 February 2003
#
# Copyright CLRC
#+

itcl::class Preview {
   constructor {} {}
   destructor {}
   public {

# Inputs.
      method target {type args}
      method slew {time}
      variable pox 0.0 {$telsim configure -pox $pox}
      variable poy 0.0 {$telsim configure -poy $poy}
      variable iaa 0.0 {$telsim configure -iaa $iaa}
      variable ipa 0.0 {$telsim configure -ipa $ipa}
      variable rotSystem FK5 {$telsim configure -rotSystem $rotSystem}
      variable rotEquinox J2000 {$telsim configure -rotEquinox $rotEquinox}
      variable p1Target [list]
      variable p2Target [list]
      variable oiTarget [list]
		variable ttgs1Target [list]
		variable ttgs2Target [list]
		variable ttgs3Target [list]
		variable odgw1Target [list]
		variable odgw2Target [list]
		variable odgw3Target [list]
		variable odgw4Target [list]
      variable wavel 0.5 {$telsim configure -wavelength $wavel}
      variable p1Wavel 0.5
      variable p2Wavel 0.5
      variable oiWavel 0.5
		variable ttgs1Wavel 0.5
		variable ttgs2Wavel 0.5
		variable ttgs3Wavel 0.5
		variable odgw1Wavel 0.5
		variable odgw2Wavel 0.5
		variable odgw3Wavel 0.5
		variable odgw4Wavel 0.5
# Outputs.
      variable utc
      variable visible
      variable target
      variable az1
      variable az2
      variable el
      variable rma1
      variable rma2
      variable ha
      variable zd
      variable am
      variable moonSep
      variable azttl1
      variable azttl2
      variable elttl
      variable rotttl1
      variable rotttl2
      variable zttl
      variable p1xy [list]
      variable p2xy [list]
      variable oixy [list]
		variable ttgs1xy [list]
		variable ttgs2xy [list]
		variable ttgs3xy [list]
		variable odgw1xy [list]
		variable odgw2xy [list]
		variable odgw3xy [list]
		variable odgw4xy [list]
   }
   private {
      variable telsim
		method getXY {wavelength target}
   }
}

itcl::body Preview::constructor {} {

# Create telescope simulation object.
   set telsim [TelescopeSim #auto]

}

itcl::body Preview::destructor {} {
   itcl::delete object $telsim
}

itcl::body Preview::target {type args} {
   switch $type {
      hmsdegTarget {
         $telsim configure \
               -targetType $type \
               -theta1 [lindex $args 0] \
               -theta2 [lindex $args 1] \
               -system [lindex $args 2] \
               -equinox [lindex $args 3] \
               -epoch [lindex $args 4] \
               -pm1 [lindex $args 5] \
               -pm2 [lindex $args 6] \
               -parallax [lindex $args 7] \
               -rv [lindex $args 8]
      }
      degdegTarget {
         $telsim configure \
               -targetType $type \
               -theta1 [lindex $args 1] \
               -theta2 [lindex $args 2]
      }
      conicTarget {
         $telsim configure \
               -targetType $type \
               -orbType [lindex $args 0] \
               -orbElements [lrange $args 1 end]
      }
   }
}

itcl::body Preview::slew {time} {

# Check that a science target has been defined.
   if { [string equal [$telsim cget -targetType] <undefined>] } {
      error "Preview must have a science target defined"
   }

# Update telescope context in the TelescopeSim object.
   $telsim configure -delut [sa tcssad get delut value] \
         -elongm [sa tcssad get tlongm value] \
         -latm [sa tcssad get tlatm value] \
         -hm [sa tcssad get height value] \
         -xpm [sa tcssad get xpm value] \
         -ypm [sa tcssad get ypm value] \
         -tlr [sa tcssad get tlr value] \
         -focalLength [sa tcssad get focalLength value] \
         -an 0.0 \
         -aw 0.0 \
         -pnpae 0.0 \
         -ca [sa tcssad get collErrAz value] \
         -ce [sa tcssad get collErrEl value] \
         -temperature [sa tcssad get currentExternalTemp value] \
         -pressure [sa tcssad get currentAirPressure value] \
         -humidity [sa tcssad get currentRH value]

# Set mechanism limits.
   $telsim configure -ellim [sa tcssad get ellimit] \
         -azlolim [sa tcssad get azlolimit] \
         -azhilim [sa tcssad get azhilimit] \
         -rotlolim [sa tcssad get rotlolimit] \
         -rothilim [sa tcssad get rothilimit] \
         -zlim [sa tcssad get zlimit]

# Slew the simulator.
   $telsim slew 0.0 $time

# Compute the WFS x/y positions.
   if {[string length $p1Target]} {
		set p1xy [getXY $p1Wavel $p1Target]
   }

   if {[string length $p2Target]} {
		set p2xy [getXY $p2Wavel $p2Target]
   }

   if {[string length $oiTarget]} {
		set oixy [getXY $oiWavel $oiTarget]
   }

	if {[string length $ttgs1Target]} {
		set ttgs1xy [getXY $ttgs1Wavel $ttgs1Target]
	}

	if {[string length $ttgs2Target]} {
		set ttgs2xy [getXY $ttgs2Wavel $ttgs2Target]
	}
	
	if {[string length $ttgs3Target]} {
		set ttgs3xy [getXY $ttgs3Wavel $ttgs3Target]
	}

	if {[string length $odgw1Target]} {
		set odgw1xy [getXY $odgw1Wavel $odgw1Target]
	}

	if {[string length $odgw2Target]} {
		set odgw2xy [getXY $odgw2Wavel $odgw2Target]
	}
	
	if {[string length $odgw3Target]} {
		set odgw3xy [getXY $odgw3Wavel $odgw3Target]
	}

	if {[string length $odgw4Target]} {
		set odgw4xy [getXY $odgw4Wavel $odgw4Target]
	}


# Fetch the results.
   set utc [$telsim cget -utc]
   set visible [$telsim cget -visible]
   set target [$telsim cget -target]
   set az1 [$telsim cget -az1]
   set az2 [$telsim cget -az2]
   set el [$telsim cget -el]
   set rma1 [$telsim cget -rma1]
   set rma2 [$telsim cget -rma2]
   set ha [$telsim cget -ha]
   set zd [$telsim cget -zd]
   set am [$telsim cget -am]
   set moonSep [$telsim cget -moonSep]
   set azttl1 [$telsim cget -azttl1]
   set azttl2 [$telsim cget -azttl2]
   set elttl [$telsim cget -elttl]
   set azttl1 [$telsim cget -rotttl1]
   set azttl2 [$telsim cget -rotttl2]
   set zttl [$telsim cget -zttl]
}


itcl::body Preview::getXY {wavelength target} {
	eval target [lindex $target 0] [lrange $target 1 end]
	if { [lindex $target 0] eq "hmsdegTarget" } {
		$telsim configure -wavelength $wavelength
	}
	return [$telsim getxy]
}