itcl::class RADecTarget {
    inherit itk::Widget
    constructor {args} {}
    destructor {}
 	method load {target}
 	method save {target {propagate 1}}
	method cleanFields {}
	
	private {
		method buildProperMotion {parent}
		method buildDiffTrackRate {parent}
		method onCosys {}
	}
}

itk::usual RADecTarget {
    keep -background  -cursor
}

itcl::body RADecTarget::constructor {args} {
    eval itk_initialize $args

    set w $itk_interior
# Frame for position.
	itk_component add pos {
		frame $w.pos
   }

# RA and Dec.
    set w $itk_component(pos)
    itk_component add ra {
	iwidgets::entryfield $w.ra -width 12 -labeltext RA
    } {
	usual
	rename -textfont -majorfont majorFont Font
	rename -labelfont -majorfont majorFont Font
    }
    itk_component add dec {
	iwidgets::entryfield $w.dec -width 12 -labeltext Dec
    } {
	usual
	rename -textfont -majorfont majorFont Font
	rename -labelfont -majorfont majorFont Font
    }
#   pack $itk_component(ra) $itk_component(dec) -side left -expand y -pady 10
#   set w [winfo parent $w]

#  Coordinate frame.
	itk_component add cosys {
		SubComponentSelector $w.cosys  \
			-labelpos w -width 10 \
			-component tcs.field.cosys -selectioncommand [itcl::code $this onCosys]
    }
#    pack $itk_component(cosys) -side bottom  \
#	    -expand y -pady 4 -anchor w
	pack $itk_component(ra) $itk_component(dec) -side left -expand n -padx 3 -pady 15
	pack $itk_component(cosys) -side right -padx 3 -pady 15
   set w [winfo parent $w]

# Frame for space motions.
	itk_component add space {
	iwidgets::labeledframe $w.space -labeltext "Proper motions" \
		-labelpos nw -ipadx 0 -ipady 2
	}
	buildProperMotion [$itk_component(space) childsite]

	itk_component add lftframe { frame $w.lftframe }
# Controls for differential track rate.
	itk_component add trframe { iwidgets::labeledframe $w.lftframe.trframe \
		-labelpos nw -labeltext "Differential Track Rates" -ipadx 1 -ipady 2 }
	
	buildDiffTrackRate [$itk_component(trframe) childsite]
   
   itk_component add ephemeris {
      iwidgets::entryfield $w.lftframe.ephemeris -width 15 -labeltext Ephemeris
   } {
      usual
      rename -textfont -majorfont majorFont Font
      rename -labelfont -majorfont majorFont Font
   }

	pack $itk_component(pos) -side top -expand yes -fill x
	pack $itk_component(ephemeris) -side bottom -fill x -padx 3 -pady 1
   pack $itk_component(trframe) -side top -fill x
   pack $itk_component(lftframe) $itk_component(space) -side left -expand y -fill both -padx 0
}


itcl::body RADecTarget::cleanFields {} {
	$itk_component(ra) clear
	$itk_component(dec) clear
	$itk_component(epoch) clear
	$itk_component(pm1) clear
	$itk_component(pm2) clear
	$itk_component(parallax) clear
	$itk_component(rv) clear
   $itk_component(ephemeris) clear
	set ::Config(tcs.field.cosys,value) ""
	set ::Config(tcs.field.trackrate,value) ""
}

itcl::body RADecTarget::load {target} {
	if { ![string equal $target ""] && [string equal [$target cget -type] "hmsdegTarget"]} {
		cleanFields
      $itk_component(ra) insert end [$target cget -c1]
      $itk_component(dec) insert end [$target cget -c2]
      $itk_component(epoch) insert end [$target cget -epoch]
      $itk_component(pmunits) select [$target cget -pmunits]
      $itk_component(pm1) insert end [$target cget -pm1]
      $itk_component(pm2) insert end [$target cget -pm2]
      $itk_component(parallax) insert end [$target cget -parallax]
      $itk_component(rv) insert end [$target cget -rv]
      $itk_component(ephemeris) insert end [$target cget -ephemeris]
		set ::Config(tcs.field.cosys,value) [$target cget -cosys]

		set ::Config(tcs.field.trackrate,value) [$target cget -trackrate]
		if { ![string equal [$target cget -trackrate] ""]} {
			set ::Config(tcs.field.trackrate.cosys,value) \
				[$::Config(tcs.field.trackrate,namespace)::$::Config(tcs.field.trackrate,value) cget -cosys]
		}
	}
}

itcl::body RADecTarget::save {target {propagate 1}} {
	if { $propagate } {
		$itk_component(trcontrol) store
	}
	if { ![string equal $target ""] } {
		#$target init
      $target configure -type hmsdegTarget
      $target configure -c1 [$itk_component(ra) get]
      $target configure -c2 [$itk_component(dec) get]
      $target configure -epoch [$itk_component(epoch) get]
      $target configure -pmunits [$itk_component(pmunits) get]
      $target configure -pm1 [$itk_component(pm1) get]
      $target configure -pm2 [$itk_component(pm2) get]
      $target configure -parallax [$itk_component(parallax) get]
      $target configure -rv [$itk_component(rv) get]
      $target configure -cosys [$itk_component(cosys) get]
      $target configure -ephemeris [$itk_component(ephemeris) get]
      $target configure -trackrate $::Config(tcs.field.trackrate,value)
	}
}

itcl::body RADecTarget::buildProperMotion {parent} {
	# Epoch.
    itk_component add epoch {
	iwidgets::entryfield $parent.epoch -width 8 \
		-labeltext [lindex [cs sourceA info epoch] 2]
    }

# Proper motions.
   itk_component add pmunits {
      iwidgets::optionmenu $parent.pmunits -labeltext Units
   }
   [$itk_component(pmunits) component menuBtn] configure -anchor w
   $itk_component(pmunits) insert 0 mas/year mas/century arcsecs/year \
         arcsecs/century sec-arcsecs/year sec-arcsecs/century
   itk_component add pm {
      frame $parent.pm
   }
   itk_component add pm1 {
      iwidgets::entryfield $parent.pm.pm1 -labeltext RA -width 8
   }
   itk_component add pm2 {
      iwidgets::entryfield $parent.pm.pm2 -labeltext Dec -width 8
   }
   pack $itk_component(pm1) $itk_component(pm2) -side left

# Parallax
   itk_component add parallax {
      iwidgets::entryfield $parent.parallax -width 8 \
            -labeltext "Parallax (mas)"
   }

# Radial velocity.
   itk_component add rv {
      iwidgets::entryfield $parent.rv -width 8 \
            -labeltext "Radial vel. (km/s)"
   }
   pack $itk_component(epoch) $itk_component(pmunits) $itk_component(pm) \
         $itk_component(parallax) $itk_component(rv) -padx 3 -pady 1 \
         -anchor e -side top -expand yes
}

itcl::body RADecTarget::buildDiffTrackRate {parent} {
	itk_component add trcontrol { TrackRateControl $parent.trcontrol -component tcs.field.trackrate}
	pack $itk_component(trcontrol) -side top -anchor n -expand yes -padx 1 -pady 1
}

itcl::body RADecTarget::onCosys {} {
	$itk_component(trcontrol) configure -cosys [$itk_component(cosys) get]
}
