#+
# RealGems
#
# This class encapsulates the configuration interactions with the real GEMS
# through EPICS. It is a singleton.
#
# J Luhrs 01 April 2009
#
#  $Id: Exp $
#-

package require Ocspkg

itcl::class RealGems {
	inherit IGemsSys  
public {
	constructor {} {}
	destructor {}

	method slewReset {}
	#Loop control commands
	method openLGSLoop {}
	method closeLGSLoop {}
	method openTTLoop {}
	method closeTTLoop {}
	method openFocLoop {}
	method closeFocLoop {}
	method openFlexLoop {}
	method closeFlexLoop {}
	method openAniLoop {}
	method closeAniLoop {}
	method disableM1Offload {}
	method enableM1Offload {}
	method disableM2Offload {}
	method enableM2Offload {}
	method disableRotOffload {}
	method enableRotOffload {}
	method pauseLoops {why}
	method resumeLoops {}
	method stopLoops {}
   method setupLoops {loopList sources}
	
	#Loop configuration
	method configureNGS {sources}
	
	#Astrometry
	method setAstroMode {mode}
	method startAstrometry {}
	method stopAstrometry {}
	
	method moveADC {pos}
	method startADC {}
	method stopADC {}
	method moveBeamSplitter {pos}

	#WFS control commands
   method setupODGW {idList}
	method startODGW {idList}
	method stopODGW {idList}
	method startTTWFS {idList}
	method stopTTWFS {idList}
	method startLGSWFS {}
	method stopLGSWFS {}
	method setODGWExposure {id val}
	method setTTWFSExposure {id val}
	method setLGSWFSExposure {val}

   #ODGW special commands
   method setODGWSize { size {apply 1} }
   method getODGWSize {}
   method setODGWSciRows { num {apply 1} }
   method getODGWSciRows {}
   method setODGWIdleRows { num {apply 1} }
   method getODGWIdleRows {}
   method setODGWDisplay { opt {apply 1} }
   method getODGWDisplayRate {}
   method setODGWDisplayRate { val {apply 1} }
   
   #LIS commands
   method pauseLis {}

	#States
	method getGemsActive {}
	method getLoopsState {}
	method getLGSLoopState {}
	method getTTLoopState {}
	method getFocLoopState {}
	method getFlexLoopState {}
	method getAniLoopState {}
	method getM1OffloadState {}
	method getM2OffloadState {}
	method getRotOffloadState {}
	method getTTLoopSources {}
   method getFlexLoopSources {}
	method getODGWActive {id}
   method getODGWEnabled {id}
	method getTTWFSActive {id}
	method getLGSWFSActive {}
	method getODGWExposure {id}
	method getTTWFSExposure {id}
	method getLGSWFSExposure {}
	method getODGWCounts {id}
	method getTTWFSCounts {id}
	method getLGSWFSCounts {id}
   method getLGSWFSAverage {}
	method getAstroMode {}
	method getAstrometryState {}
	method getADCPos {}
	method getADCLoopState {}
	method getBeamSplitterPos {}
	method getLaserProp {}
   
   #Loops commands state
   method getLGSCmdState {}
   method getLGSCmdMess {}
   method getTTCmdState {}
   method getTTCmdMess {}
   method getFocCmdState {}
   method getFocCmdMess {}
   method getFlexCmdState {}
   method getFlexCmdMess {}
   method getAniCmdState {}
   method getAniCmdMess {}

	
	#Command state
	method getCommandState {}
	method getLastError {}

	#Observable interface
	method subscribe {observer}
	method unsubscribe {observer}
	
	variable logger logactions
}
private {
	variable lastCmdSys ""
	variable lastTTFLux
	variable lastLGSFlux
	variable gemsActive OFF
	variable astroMode None
	variable odgwBaseExpTime 0.00125
	variable odgwExpTime
   variable validLGSWFSCounts 1
   
   common minExpTime 0.00125
   common expTimeTolerance 0.1
		
	variable observerList {}
	method notify {reasons}
	
	method onStatusChange {name alarm time value}
	method checkGemsActive {}
   method waitForCmdIdle {{timeout 1000}}
   method setTTLoopInputs {sources}
   method calculateBaseExpTime { idList tolerance }
}
}

itcl::body RealGems::constructor {} {
	if { [llength [info commands epics]] == 0 } {
		error "unable to load package: EPICS ocs service does not exist"
	}
   epics cs gems::slewReset
	epics cs gems::lgsLoopCtrl
	epics cs gems::ttLoopCtrl
	epics cs gems::focLoopCtrl
	epics cs gems::flexLoopCtrl
	epics cs gems::taLoopCtrl
	epics cs gems::m1OffloadCtrl
	epics cs gems::m2OffloadCtrl
	epics cs gems::crLoopCtrl
	epics cs gems::seqLoopCtrl
	epics cs gems::ngsConfig
	#epics cs gems::astroMode
	epics cs gems::astrometricCtrl
	epics cs gems::adcMech
	epics cs gems::adcLoop
	epics cs gems::beamSplitter
	epics cs gems::ttApdCtrl
	epics cs gems::ttExpCtrl
	epics cs gems::lgsExpCtrl
	epics cs gems::odgwSetup
   epics cs gems::odgwGuide
   epics cs gems::odgwEndGuide
   epics cs gems::lisPause
	epics sa gemssad
	epics sa aomsad
   epics sa aomauxsad
   epics sa aomadcsad
   epics sa rtcsad
	epics sa odgwsad
	
	cs gems::aomAuxApply setTimeout 3
   cs gems::aomAdcApply setTimeout 3
	cs gems::mystApply setTimeout 3
	
	set lastTTFLux {-1 -1 -1 -1 -1 -1 -1 -1}
	set lastLGSFlux {-1 -1 -1 -1 -1 -1}
   set odgwExpTime(1) 0.1
   set odgwExpTime(2) 0.1
   set odgwExpTime(3) 0.1
   set odgwExpTime(4) 0.1
	
	#sa gemssad proc applyC [itcl::code $this onStatusChange]
	sa gemssad proc sciReady [itcl::code $this onStatusChange]
	sa gemssad proc lgsLoop [itcl::code $this onStatusChange]
	sa gemssad proc ttLoop [itcl::code $this onStatusChange]
	sa gemssad proc focLoop [itcl::code $this onStatusChange]
	sa gemssad proc flexLoop [itcl::code $this onStatusChange]
	sa gemssad proc astromReady [itcl::code $this onStatusChange]
	sa gemssad proc aniLoop [itcl::code $this onStatusChange]
   sa gemssad proc aniLoop [itcl::code $this onStatusChange]
   sa gemssad proc rtcHealth [itcl::code $this onStatusChange]
	#sa gemssad proc lgsFlux [itcl::code $this onStatusChange]
	#sa gemssad proc ngsFlux [itcl::code $this onStatusChange]
   sa gemssad proc m1Offload [itcl::code $this onStatusChange]
   sa gemssad proc m2Offload [itcl::code $this onStatusChange]
   sa gemssad proc crOffload [itcl::code $this onStatusChange]

	sa gemssad proc ngs1 [itcl::code $this onStatusChange]
	sa gemssad proc ngs2 [itcl::code $this onStatusChange]
	sa gemssad proc ngs3 [itcl::code $this onStatusChange]
	sa gemssad proc odgs1 [itcl::code $this onStatusChange]
	sa gemssad proc odgs2 [itcl::code $this onStatusChange]
	sa gemssad proc odgs3 [itcl::code $this onStatusChange]
	sa gemssad proc odgs4 [itcl::code $this onStatusChange]
	sa gemssad proc oigs [itcl::code $this onStatusChange]
	sa gemssad proc ngs1Mag [itcl::code $this onStatusChange]
	sa gemssad proc ngs2Mag [itcl::code $this onStatusChange]
	sa gemssad proc ngs3Mag [itcl::code $this onStatusChange]
	sa gemssad proc odgs1Mag [itcl::code $this onStatusChange]
	sa gemssad proc odgs2Mag [itcl::code $this onStatusChange]
	sa gemssad proc odgs3Mag [itcl::code $this onStatusChange]
	sa gemssad proc odgs4Mag [itcl::code $this onStatusChange]
	sa gemssad proc apd1Status [itcl::code $this onStatusChange]
	sa gemssad proc apd2Status [itcl::code $this onStatusChange]
	sa gemssad proc apd3Status [itcl::code $this onStatusChange]

	#sa aomsad proc applyC [itcl::code $this onStatusChange]
	sa aomsad proc adcScState [itcl::code $this onStatusChange]
	sa aomsad proc beamSplitterState [itcl::code $this onStatusChange]
	sa aomsad proc adcScLoop [itcl::code $this onStatusChange]
	
	sa rtcsad proc tt1Active [itcl::code $this onStatusChange]
	sa rtcsad proc tt2Active [itcl::code $this onStatusChange]
	sa rtcsad proc tt3Active [itcl::code $this onStatusChange]
	
#	sa odgwsad proc counts1 [itcl::code $this onStatusChange]
#	sa odgwsad proc counts2 [itcl::code $this onStatusChange]
#	sa odgwsad proc counts3 [itcl::code $this onStatusChange]
#	sa odgwsad proc counts4 [itcl::code $this onStatusChange]
	sa odgwsad proc expMult1 [itcl::code $this onStatusChange]
	sa odgwsad proc expMult2 [itcl::code $this onStatusChange]
	sa odgwsad proc expMult3 [itcl::code $this onStatusChange]
	sa odgwsad proc expMult4 [itcl::code $this onStatusChange]
   sa odgwsad proc odgwSize [itcl::code $this onStatusChange]
   sa odgwsad proc notGuiding [itcl::code $this onStatusChange]
}

itcl::body RealGems::destructor {} {
	#sa gemssad unproc applyC [itcl::code $this onStatusChange]
   sa gemssad unproc sciReady [itcl::code $this onStatusChange]
	sa gemssad unproc lgsLoop [itcl::code $this onStatusChange]
	sa gemssad unproc ttLoop [itcl::code $this onStatusChange]
	sa gemssad unproc focLoop [itcl::code $this onStatusChange]
	sa gemssad unproc flexLoop [itcl::code $this onStatusChange]
	sa gemssad unproc astromReady [itcl::code $this onStatusChange]
	sa gemssad unproc aniLoop [itcl::code $this onStatusChange]
   sa gemssad unproc aniLoop [itcl::code $this onStatusChange]
   sa gemssad unproc rtcHealth [itcl::code $this onStatusChange]
#	sa gemssad unproc lgsFlux [itcl::code $this onStatusChange]
#	sa gemssad unproc ngsFlux [itcl::code $this onStatusChange]
	sa gemssad unproc ngs1 [itcl::code $this onStatusChange]
	sa gemssad unproc ngs2 [itcl::code $this onStatusChange]
	sa gemssad unproc ngs3 [itcl::code $this onStatusChange]
	sa gemssad unproc odgs1 [itcl::code $this onStatusChange]
	sa gemssad unproc odgs2 [itcl::code $this onStatusChange]
	sa gemssad unproc odgs3 [itcl::code $this onStatusChange]
	sa gemssad unproc odgs4 [itcl::code $this onStatusChange]
	sa gemssad unproc oigs [itcl::code $this onStatusChange]
	sa gemssad unproc ngs1Mag [itcl::code $this onStatusChange]
	sa gemssad unproc ngs2Mag [itcl::code $this onStatusChange]
	sa gemssad unproc ngs3Mag [itcl::code $this onStatusChange]
	sa gemssad unproc odgs1Mag [itcl::code $this onStatusChange]
	sa gemssad unproc odgs2Mag [itcl::code $this onStatusChange]
	sa gemssad unproc odgs3Mag [itcl::code $this onStatusChange]
	sa gemssad unproc odgs4Mag [itcl::code $this onStatusChange]
	sa gemssad unproc apd1Status [itcl::code $this onStatusChange]
	sa gemssad unproc apd2Status [itcl::code $this onStatusChange]
	sa gemssad unproc apd3Status [itcl::code $this onStatusChange]

	#sa aomsad unproc applyC [itcl::code $this onStatusChange]
	sa aomsad unproc adcScState [itcl::code $this onStatusChange]
	sa aomsad unproc beamSplitterState [itcl::code $this onStatusChange]
	sa aomsad unproc adcScLoop [itcl::code $this onStatusChange]
	sa rtcsad unproc tt1Active [itcl::code $this onStatusChange]
	sa rtcsad unproc tt2Active [itcl::code $this onStatusChange]
	sa rtcsad unproc tt3Active [itcl::code $this onStatusChange]

#	sa odgwsad unproc counts1 [itcl::code $this onStatusChange]
#	sa odgwsad unproc counts2 [itcl::code $this onStatusChange]
#	sa odgwsad unproc counts3 [itcl::code $this onStatusChange]
#	sa odgwsad unproc counts4 [itcl::code $this onStatusChange]
	sa odgwsad unproc expMult1 [itcl::code $this onStatusChange]
	sa odgwsad unproc expMult2 [itcl::code $this onStatusChange]
	sa odgwsad unproc expMult3 [itcl::code $this onStatusChange]
	sa odgwsad unproc expMult4 [itcl::code $this onStatusChange]
   sa odgwsad unproc odgwSize [itcl::code $this onStatusChange]
}

itcl::body RealGems::slewReset {} {
	cs gems::slewReset set astroMode $astroMode
	$logger logmess gems::slewReset
	set lastCmdSys gemssad
   catch {cs gems::slewReset post}
}

itcl::body RealGems::openLGSLoop {} {
	cs gems::lgsLoopCtrl set cmd STOP
	$logger logmess "gems::lgsLoopCtrl STOP"
	set lastCmdSys gemssad
	catch {cs gems::lgsLoopCtrl post}
}

itcl::body RealGems::closeLGSLoop {} {
	cs gems::lgsLoopCtrl set cmd START
	$logger logmess "gems::lgsLoopCtrl START"
	set lastCmdSys gemssad
	catch {cs gems::lgsLoopCtrl post}
}

itcl::body RealGems::openTTLoop {} {
	cs gems::ttLoopCtrl set cmd STOP
	$logger logmess "gems::ttLoopCtrl STOP"
	set lastCmdSys gemssad
	catch {cs gems::ttLoopCtrl post}
}

itcl::body RealGems::closeTTLoop {} {
	cs gems::ttLoopCtrl set cmd START
	$logger logmess "gems::ttLoopCtrl START"
	set lastCmdSys gemssad
	catch {cs gems::ttLoopCtrl post}
}

itcl::body RealGems::openFocLoop {} {
	cs gems::focLoopCtrl set cmd STOP
	$logger logmess "gems::focLoopCtrl STOP"
	set lastCmdSys gemssad
	catch {cs gems::focLoopCtrl post}
}

itcl::body RealGems::closeFocLoop {} {
	cs gems::focLoopCtrl set cmd START
	$logger logmess "gems::focLoopCtrl START"
	set lastCmdSys gemssad
	catch {cs gems::focLoopCtrl post}
}

itcl::body RealGems::openFlexLoop {} {
	cs gems::flexLoopCtrl set cmd STOP
	$logger logmess "gems::flexLoopCtrl STOP"
	set lastCmdSys gemssad
	catch {cs gems::flexLoopCtrl post}
}

itcl::body RealGems::closeFlexLoop {} {
	cs gems::flexLoopCtrl set cmd START
	$logger logmess "gems::flexLoopCtrl START"
	set lastCmdSys gemssad
	catch {cs gems::flexLoopCtrl post}
}

itcl::body RealGems::openAniLoop {} {
	cs gems::taLoopCtrl set cmd STOP
	$logger logmess "gems::taLoopCtrl STOP"
	set lastCmdSys gemssad
	catch {cs gems::taLoopCtrl post}
}

itcl::body RealGems::closeAniLoop {} {
	cs gems::taLoopCtrl set cmd START
	$logger logmess "gems::taLoopCtrl START"
	set lastCmdSys gemssad
	catch {cs gems::taLoopCtrl post}
}

itcl::body RealGems::disableM1Offload {} {
	cs gems::m1OffloadCtrl  set cmd STOP
	$logger logmess "gems::m1OffloadCtrl STOP"
	set lastCmdSys gemssad
	catch {cs gems::m1OffloadCtrl  post}
}

itcl::body RealGems::enableM1Offload {} {
	cs gems::m1OffloadCtrl  set cmd START
	$logger logmess "gems::m1OffloadCtrl START"
	set lastCmdSys gemssad
	catch {cs gems::m1OffloadCtrl  post}
}

itcl::body RealGems::disableM2Offload {} {
	cs gems::m2OffloadCtrl  set cmd STOP
	$logger logmess "gems::m2OffloadCtrl STOP"
	set lastCmdSys gemssad
	catch {cs gems::m2OffloadCtrl  post}
}

itcl::body RealGems::enableM2Offload {} {
	cs gems::m2OffloadCtrl  set cmd START
	$logger logmess "gems::m2OffloadCtrl START"
	set lastCmdSys gemssad
	catch {cs gems::m2OffloadCtrl  post}
}

itcl::body RealGems::disableRotOffload {} {
	cs gems::crLoopCtrl  set cmd STOP
	$logger logmess "gems::crLoopCtrl STOP"
	set lastCmdSys gemssad
	catch {cs gems::crLoopCtrl  post}
}

itcl::body RealGems::enableRotOffload {} {
	cs gems::crLoopCtrl  set cmd START
	$logger logmess "gems::crLoopCtrl START"
	set lastCmdSys gemssad
	catch {cs gems::crLoopCtrl post}
}

itcl::body RealGems::pauseLoops {why} {
	cs gems::seqLoopCtrl set cmd PAUSE
	cs gems::seqLoopCtrl set reason $why
	$logger logmess "gems::seqLoopCtrl PAUSE $why"
	set lastCmdSys gemssad
	catch {cs gems::seqLoopCtrl post}	
}

itcl::body RealGems::resumeLoops {} {
	cs gems::seqLoopCtrl set cmd RESUME
	$logger logmess "gems::seqLoopCtrl RESUME"
	set lastCmdSys gemssad
	catch {cs gems::seqLoopCtrl post}	
}

itcl::body RealGems::stopLoops {} {
	cs gems::seqLoopCtrl set cmd STOP
	$logger logmess "gems::seqLoopCtrl STOP"
	set lastCmdSys gemssad
	catch {cs gems::seqLoopCtrl post}
}


#Loop configuration
itcl::body RealGems::configureNGS {sources} {
   set lastCmdSys gemssad
   if { [setTTLoopInputs $sources] } {
      catch {cs gems::ngsConfig post}
   } 
}

itcl::body RealGems::setTTLoopInputs {sources} {
   set notUsed ""
	foreach wfs {ttgs1 ttgs2 ttgs3 odgw1 odgw2 odgw3 odgw4 oigs} {
      if {[string first $wfs $sources] == -1} {
         lappend notUsed $wfs
      }
	}
   foreach wfs $notUsed {
      lappend sources $wfs NotUsed 15.0
   }
   set change 0
	foreach {wfs loop mag} $sources {
		switch $wfs {
		ttgs1 {
         if {[sa gemssad get ngs1 value] ne $loop} {
   			cs gems::ngsConfig set ngs1 $loop
            set change 1
         }
         if { $loop ne "NotUsed" && [sa gemssad get ngs1Mag value] != $mag} {
   			cs gems::ngsConfig set ngs1Mag $mag
            set change 1
         }
		}
		ttgs2 {
         if {[sa gemssad get ngs2 value] ne $loop} {
            cs gems::ngsConfig set ngs2 $loop
            set change 1
         }
         if { $loop ne "NotUsed" && [sa gemssad get ngs2Mag value] != $mag} {
            cs gems::ngsConfig set ngs2Mag $mag
            set change 1
         }
		}
		ttgs3 {
         if {[sa gemssad get ngs3 value] ne $loop} {
            cs gems::ngsConfig set ngs3 $loop
            set change 1
         }
         if { $loop ne "NotUsed" && [sa gemssad get ngs3Mag value] != $mag} {
            cs gems::ngsConfig set ngs3Mag $mag
            set change 1
         }
		}
		odgw1 {
         if {[sa gemssad get odgs1 value] ne $loop} {
            cs gems::ngsConfig set odgs1 $loop
            set change 1
         }
         if { $loop ne "NotUsed" && [sa gemssad get odgs1Mag value] != $mag} {
            cs gems::ngsConfig set odgs1Mag $mag
            set change 1
         }
		}
		odgw2 {
         if {[sa gemssad get odgs2 value] ne $loop} {
            cs gems::ngsConfig set odgs2 $loop
            set change 1
         }
         if { $loop ne "NotUsed" && [sa gemssad get odgs2Mag value] != $mag} {
            cs gems::ngsConfig set odgs2Mag $mag
            set change 1
         }
		}
		odgw3 {
         if {[sa gemssad get odgs3 value] ne $loop} {
            cs gems::ngsConfig set odgs3 $loop
            set change 1
         }
         if { $loop ne "NotUsed" && [sa gemssad get odgs3Mag value] != $mag} {
            cs gems::ngsConfig set odgs3Mag $mag
            set change 1
         }
		}
		odgw4 {
         if {[sa gemssad get odgs4 value] ne $loop} {
            cs gems::ngsConfig set odgs4 $loop
            set change 1
         }
         if { $loop ne "NotUsed" && [sa gemssad get odgs4Mag value] != $mag} {
            cs gems::ngsConfig set odgs4Mag $mag
            set change 1
         }
		}
		oigs {
         if {[sa gemssad get oigs value] ne $loop} {
            cs gems::ngsConfig set oigs $loop
            set change 1
         }
         if { $loop ne "NotUsed" && [sa gemssad get oigs value] != $mag} {
            cs gems::ngsConfig set oigsMag $mag
            set change 1
         }
		}
		}
	}
	$logger logmess "gems::ngsConfig $sources"
   
   return $change
}

#Astrometry
itcl::body RealGems::setAstroMode {mode} {
	switch $mode {
	None -
	Regular -
	Good -
	Best { 
      set astroMode $mode
      $logger logmess "RealGems::setAstroMode $mode"
      cs gems::slewReset set astroMode $mode
	} 
	default {
		$logger logmess "RealGems::setAstroMode unknow mode $mode"
	}
	}
	set lastCmdSys gemssad
   catch {cs gems::slewReset post}
}

itcl::body RealGems::startAstrometry {} {
	cs gems::astrometricCtrl set cmd START
	cs gems::astrometricCtrl set mode $astroMode
	$logger logmess "gems::astrometricCtrl START $astroMode"
	set lastCmdSys gemssad
	catch {cs gems::astrometricCtrl  post}
}

itcl::body RealGems::stopAstrometry {} {
	cs gems::astrometricCtrl set cmd STOP
	$logger logmess "gems::astrometricCtrl STOP"
	set lastCmdSys gemssad
	catch {cs gems::astrometricCtrl  post}
}

itcl::body RealGems::moveADC {pos} {
	cs gems::adcMech set pos $pos
	$logger logmess "gems::adcMech $pos"
	set lastCmdSys aomadcsad
	catch {cs gems::adcMech post}
}

itcl::body RealGems::startADC {} {
	cs gems::adcLoop set loop On
	$logger logmess "gems::adcLoop loop On"
	set lastCmdSys aomadcsad
	catch {cs gems::adcLoop post}
}

itcl::body RealGems::stopADC {} {
	cs gems::adcLoop set loop Off
	$logger logmess "gems::adcLoop loop Off"
	set lastCmdSys aomadcsad
	catch {cs gems::adcLoop post}
}

itcl::body RealGems::moveBeamSplitter {pos} {
	cs gems::beamSplitter set pos $pos
	$logger logmess "gems::beamSplitter pos $pos"
	set lastCmdSys aomauxsad
	catch {cs gems::beamSplitter post}
}

#WFS control commands
itcl::body RealGems::setupODGW {idList} {
   set change 0
   set logmult ""
   if { [llength $idList] > 0 } { 
      set odgwBaseExpTime [calculateBaseExpTime $idList $expTimeTolerance]
   }
   foreach id {1 2 3 4} {
      if {[lsearch $idList $id] == -1} {
         set mult 0
      } else {
   		set mult [expr "round(double($odgwExpTime($id)) / $odgwBaseExpTime )"]
   		if { $mult < 1 } {
   			set mult 1
   		}
      }
      set currentMult [sa odgwsad get expMult${id} value]
      if { ![string is integer -strict $currentMult] || $currentMult != $mult } {
   		cs gems::odgwSetup set expMult${id} $mult
         set change 1
      }
      set logmult "$logmult $id:$mult"
   }
   set currentBaseExpTime [sa odgwsad get baseExpTime]
   if { ![string is double -strict $currentBaseExpTime] || $currentBaseExpTime != $odgwBaseExpTime } {
      cs gems::odgwSetup set baseExpTime $odgwBaseExpTime
      set change 1
   }
   
   if { $change } {
      set lastCmdSys odgwsad
      $logger logmess "gems::odgwSetup multipliers $logmult"
      catch {cs gems::odgwSetup post}
      after 1000
   } else {
      set lastCmdSys ""
   }
}

itcl::body RealGems::startODGW {idList} {
   catch {cs gems::odgwGuide set command MARK}
   after 100
   catch {cs gems::odgwGuide set command START}
   set lastCmdSys ""
   $logger logmess "gems::odgwGuide"
   after 1000
}

itcl::body RealGems::stopODGW {idList} {
   catch {cs gems::odgwEndGuide set command MARK}
   after 100
   catch {cs gems::odgwEndGuide set command START}
   set lastCmdSys ""
   $logger logmess "gems::odgwEndGuide"
   after 1000
}

itcl::body RealGems::startTTWFS {idList} {
   if { [getTTWFSActive 1] } {
      set apd1Op START
   } else {
      set apd1Op STOP
   }
   if { [getTTWFSActive 2] } {
      set apd2Op START
   } else {
      set apd2Op STOP
   }
   if { [getTTWFSActive 3] } {
      set apd3Op START
   } else {
      set apd3Op STOP
   }
   
   foreach id $idList {
		switch $id {
		1 { set apd1Op START }
		2 { set apd2Op START }
		3 { set apd3Op START }
		default {
			$logger logmess "RealGems::startTTWFS invalid index $id"
		}
		}
   }
   cs gems::ttApdCtrl set apd1 $apd1Op
   cs gems::ttApdCtrl set apd2 $apd2Op
   cs gems::ttApdCtrl set apd3 $apd3Op
   
	$logger logmess "gems::ttApdCtrl $apd1Op $apd2Op $apd3Op"
	set lastCmdSys gemssad
	catch {cs gems::ttApdCtrl post}
}

itcl::body RealGems::stopTTWFS {idList} {
   if { [getTTWFSActive 1] } {
      set apd1Op START
   } else {
      set apd1Op STOP
   }
   if { [getTTWFSActive 2] } {
      set apd2Op START
   } else {
      set apd2Op STOP
   }
   if { [getTTWFSActive 3] } {
      set apd3Op START
   } else {
      set apd3Op STOP
   }
  
   foreach id $idList {
      switch $id {
      1 { set apd1Op STOP }
      2 { set apd2Op STOP }
      3 { set apd3Op STOP }
      default {
         $logger logmess "RealGems::stopTTWFS invalid index $id"
      }
      }
   }
   cs gems::ttApdCtrl set apd1 $apd1Op
   cs gems::ttApdCtrl set apd2 $apd2Op
   cs gems::ttApdCtrl set apd3 $apd3Op
   
   $logger logmess "gems::ttApdCtrl $apd1Op $apd2Op $apd3Op"
   set lastCmdSys gemssad
   catch {cs gems::ttApdCtrl post}
}

itcl::body RealGems::startLGSWFS {} {
	$logger logmess "RealGems::startLGSWFS Gems command undefined."
	set lastCmdSys gemssad
}

itcl::body RealGems::stopLGSWFS {} {
	$logger logmess "RealGems::stopLGSWFS Gems command undefined."
	set lastCmdSys gemssad
}

itcl::body RealGems::pauseLis {} {
   cs gems::lisPause set command MARK
   $logger logmess "gems::lisPause"
   set lastCmdSys lissad
   after 100
   catch {cs gems::lisPause post}
}

itcl::body RealGems::setODGWExposure {id val} {
   if { $val < $minExpTime } {
      set val $minExpTime
   }
	set odgwExpTime($id) $val
	set lastCmdSys ""
}

itcl::body RealGems::setTTWFSExposure {id val} {
	cs gems::ttExpCtrl set freqDiv $val
	$logger logmess "gems::ttExpCtrl $val"
	set lastCmdSys rtcsad
	catch {cs gems::ttExpCtrl post}
}

itcl::body RealGems::setLGSWFSExposure {val} {
	cs gems::lgsExpCtrl set expTime $val
	$logger logmess "gems::lgsExpCtrl $val"
	set lastCmdSys rtcsad
	catch {cs gems::lgsExpCtrl post}
}


#States
itcl::body RealGems::getGemsActive {} {
	return $gemsActive
}

itcl::body RealGems::getLoopsState {} {
	return [string toupper [sa gemssad get sciReady value]]
}

itcl::body RealGems::getLGSLoopState {} {
	return [string toupper [sa gemssad get lgsLoop value]]
}

itcl::body RealGems::getTTLoopState {} {
	return [string toupper [sa gemssad get ttLoop value]]
}

itcl::body RealGems::getFocLoopState {} {
	return [string toupper [sa gemssad get focLoop value]]
}

itcl::body RealGems::getFlexLoopState {} {
	return [string toupper [sa gemssad get flexLoop value]]
}

itcl::body RealGems::getAniLoopState {} {
	return [string toupper [sa gemssad get aniLoop value]]
}

itcl::body RealGems::getM1OffloadState {} {
	return [string toupper [sa gemssad get m1Offload value]]
}

itcl::body RealGems::getM2OffloadState {} {
	return [string toupper [sa gemssad get m2Offload value]]
}

itcl::body RealGems::getRotOffloadState {} {
	return [string toupper [sa gemssad get crOffload value]]
}

itcl::body RealGems::getTTLoopSources {} {
	set sources ""
	for {set i 1} { $i <= 3} { incr i } {
		if { [sa gemssad get ngs${i} value] eq "Fast" } {
			lappend sources ttgs${i} [sa gemssad get ngs${i}Mag value]
		}
	}
	for {set i 1} { $i <= 4} { incr i } {
		if { [sa gemssad get odgs${i} value] eq "Fast" } {
			lappend sources odgw${i} [sa gemssad get odgs${i}Mag value]
		}
	}
	if { [sa gemssad get oigs value] eq "Fast" } {
		lappend sources oigs [sa gemssad get oigsMag value]
	}
	
	return $sources
}

itcl::body RealGems::getFlexLoopSources {} {
   set sources ""
   for {set i 1} { $i <= 4} { incr i } {
      if { [sa gemssad get odgs${i} value] eq "Flex" } {
         lappend sources odgw${i} [sa gemssad get odgs${i}Mag value]
      }
   }
   if { [sa gemssad get oigs value] eq "Flex" } {
      lappend sources oigs [sa gemssad get oigsMag value]
   }
   
   return $sources
}

itcl::body RealGems::getODGWActive {id} {
   set val [sa odgwsad get notGuiding value]
	if { ![string is boolean -strict $val] || $val } {
		return OFF
	}
	return ON
}

itcl::body RealGems::getODGWEnabled {id} {
   if { [ sa odgwsad get expMult${id} value] > 0 } {
      return ON
   }
   return OFF
}

itcl::body RealGems::getTTWFSActive {id} {
	if { [string compare -nocase [sa rtcsad get tt${id}Active value] "ENABLED"] == 0} {
		return ON
	}
	return OFF
}

itcl::body RealGems::getLGSWFSActive {} {
#	$logger logmess "RealGems::getLGSWFSActive Gems status undefined."
   
   set lgsActive [sa gemssad get rtcHealth value]
   if { $lgsActive eq "GOOD" } {
      return ON
   }
   return OFF
}

itcl::body RealGems::getODGWExposure {id} {
   set base [sa odgwsad get baseExpTime value]
   set mult [sa odgwsad get expMult${id} value]
   
   if {[string is double -strict $base] && [string is double -strict $mult] } {
      return [expr "$base * $mult"]
   } else {
     return "0"
   }
}

itcl::body RealGems::getTTWFSExposure {id} {
   return [sa rtcsad get ngsExpMult value]
}

itcl::body RealGems::getLGSWFSExposure {} {
	return [sa rtcsad get lgsExp value]
}

itcl::body RealGems::getODGWCounts {id} {
   if { $id >= 1 && $id <= 4 } {
      return [sa odgwsad get counts${id} value]
   } else {
		$logger logmess "RealGems::getODGWCounts invalid index $id"
		return 0
   }
}

itcl::body RealGems::getTTWFSCounts {id} {
   if { $id >= 1 && $id <= 3 } {
      incr id -1
      set vals [sa gemssad get ngsFlux value]
      if { [llength $vals] < 3 } {
         return ""
      } else {
         return [expr "[lindex $vals $id ] / 100"]
      }
   } else {
		$logger logmess "RealGems::getTTWFSCounts invalid index $id"
		return ""
	}
}

itcl::body RealGems::getLGSWFSCounts {id} {
	switch $id {
	1 { set index 0 }
	2 { set index 1 }
	3 { set index 2 }
	4 { set index 3 }
	5 { set index 4 }
	default {
	   if { $validLGSWFSCounts } {
	      $logger logmess "RealGems::getLGSWFSCounts invalid index $id"
         set validLGSWFSCounts 0
	   }
		return 0
	}
	}
	set vals [sa gemssad get lgsFlux value]
	if { [llength $vals] < 6 } {
      if { $validLGSWFSCounts } {
         $logger logmess "RealGems::getLGSWFSCounts invalid values read from Myst $vals"
         set validLGSWFSCounts 0
      }
		return 0
	}
   set validLGSWFSCounts 1
	return [lindex $vals $index]
}

itcl::body RealGems::getLGSWFSAverage {} {
   return [sa gemssad get lgsAvrg value]
}

itcl::body RealGems::getAstroMode {} {
#	$logger logmess "RealGems::getAstroMode Gems status undefined."
	#return [sa gemssad get astroMode value]
	return $astroMode
}

itcl::body RealGems::getAstrometryState {} {
	return [string toupper [sa gemssad get astromReady value]]
}

itcl::body RealGems::getADCPos {} {
	return [sa aomsad get adcScState value]
}

itcl::body RealGems::getADCLoopState {} {
	return [string toupper [sa aomsad get adcScLoop value]]
}


itcl::body RealGems::getBeamSplitterPos {} {
	return [sa aomsad get beamSplitterState value]
}

itcl::body RealGems::getLaserProp {} {
	return [sa gemssad get laserProp value]
}

#Loops commands state
itcl::body RealGems::getLGSCmdState {} {
   return [sa gemssad get lgsLoopState value]
}

itcl::body RealGems::getLGSCmdMess {} {
   return [sa gemssad get lgsLoopStateMess value]
}

itcl::body RealGems::getTTCmdState {} {
   return [sa gemssad get ttLoopState value]
}

itcl::body RealGems::getTTCmdMess {} {
   return [sa gemssad get ttLoopStateMess value]
}

itcl::body RealGems::getFocCmdState {} {
   return [sa gemssad get focusLoopState value]
}

itcl::body RealGems::getFocCmdMess {} {
   return [sa gemssad get focusLoopStateMess value]
}

itcl::body RealGems::getFlexCmdState {} {
   return [sa gemssad get flexLoopState value]
}

itcl::body RealGems::getFlexCmdMess {} {
   return [sa gemssad get flexLoopStateMess value]
}

itcl::body RealGems::getAniCmdState {} {
   return [sa gemssad get taLoopState value]
}

itcl::body RealGems::getAniCmdMess {} {
   return [sa gemssad get taLoopStateMess value]
}


#Command state
itcl::body RealGems::getCommandState {} {
	if { $lastCmdSys ne "" } {
		return [sa $lastCmdSys get applyC value]
	} else {
		return IDLE
	}
}

itcl::body RealGems::getLastError {} {
	if { $lastCmdSys ne "" } {
		return [sa $lastCmdSys get message value]
	} else {
		return ""
	}
}

#Observable interface
itcl::body RealGems::subscribe {observer} {
# Check that the observer isn't already on the list.
	if { [lsearch -exact $observerList $observer] == -1 } {
# Append the observer to the list.
		lappend observerList $observer
	}
}

itcl::body RealGems::unsubscribe {observer} {
# Check that the observer is registered.
	set index [lsearch -exact $observerList $observer]
	if { $index != -1 } {
		set observerList [lreplace $observerList $index $index]
	}
}

itcl::body RealGems::notify {reasons} {
	foreach observer $observerList {
      if {$observer ne ""} {
   		$observer $reasons
      } else {
         $logger logmess "RealGems::notify: found invalid subscriptor"
      }
	}
}

itcl::body RealGems::onStatusChange {name alarm time value} {
	set reasons ""
	switch $name {
	gemssad.applyC -
	aomsad.applyC { lappend reason cmdState }
	gemssad.lgsFlux {
		for { set i 1 } { $i <= 5 } { incr i } {
			if { [lindex $value $i] != [lindex lastLGSFlux $i] } {
				lappend reasons lgswfsCounts($i)
			}
		}
	}
	gemssad.ngsFlux {
		foreach {i reason} {0 ttwfsCounts(1) 1 ttwfsCounts(2) 2 ttwfsCounts(3) 3 odgwCounts(1) 4 odgwCounts(2) 5 odgwCounts(3) 6 odgwCounts(4)} {
			if { [lindex $value $i] != [lindex lastTTFlux $i] } {
				lappend reasons $reason
			}
		}
	}
	gemssad.apd1Status { lappend reasons ttwfsActive1 }
	gemssad.apd2Status { lappend reasons ttwfsActive2 }
	gemssad.apd3Status { lappend reasons ttwfsActive3 }
	gemssad.ngs1 -
	gemssad.ngs2 -
	gemssad.ngs3 -
	gemssad.odgw1 -
	gemssad.odgw2 -
	gemssad.odgw3 -
	gemssad.odgw4 -
	gemssad.oigs { lappend reasons ttLoopSources }
	gemssad.lgsLoop { lappend reasons lgsLoopState }
	gemssad.ttLoop { lappend reasons ttLoopState }
	gemssad.focLoop { lappend reasons focLoopState }
	gemssad.flexLoop { lappend reasons flexLoopState }
	gemssad.astromReady { lappend reasons astroState }
	gemssad.aniLoop { lappend reasons aniLoopState }
   gemssad.rtcHealth { lappend reasons lgswfsActive }
	gemssad.sciReady { lappend reasons loopsSettled }
   gemssad.m1Offload { lappend reasons m1OffloadState }
   gemssad.m2Offload { lappend reasons m2OffloadState }
   gemssad.crOffload { lappend reasons rotOffloadState }
	aomsad.adcScState { lappend reasons adcPos }
	aomsad.adcScLoop { lappend reasons adcState }
	aomsad.beamSplitterState { lappend reasons beamSplitterPos }
	rtcsad.tt1Active { lappend reasons ttwfsActive(1) }
	rtcsad.tt2Active { lappend reasons ttwfsActive(2) }
	rtcsad.tt3Active { lappend reasons ttwfsActive(3) }
	odgwsad.counts1 { lappend reasons odgwCounts(1) }
	odgwsad.counts2 { lappend reasons odgwCounts(2) }
	odgwsad.counts3 { lappend reasons odgwCounts(3) }
	odgwsad.counts4 { lappend reasons odgwCounts(4) }
	odgwsad.expMult1 { lappend reasons odgwActive(1) }
	odgwsad.expMult2 { lappend reasons odgwActive(2) }
	odgwsad.expMult3 { lappend reasons odgwActive(3) }
	odgwsad.expMult4 { lappend reasons odgwActive(4) }
   odgwsad.odgwSize { lappend reasons odgwSize }
   odgwsad.notGuiding { lappend reasons odgwActive(1) odgwActive(2) odgwActive(3) odgwActive(4) }
	}
	switch $name {
	gemssad.lgsLoop -
	gemssad.ttLoop -
	gemssad.focLoop -
	gemssad.flexLoop -
	gemssad.astromReady -
	gemssad.aniLoop {
		if { [checkGemsActive] } {
			lappend reasons gemsActive
		}
	}	
	}
	if { [llength $reasons] > 0 } {
		notify $reasons
	}
}

itcl::body RealGems::checkGemsActive {} {
	set oldVal $gemsActive
	set gemsActive OFF
	foreach loop { ttLoop aniLoop flexLoop focLoop lgsLoop } {
		if { [string equal -nocase "[sa gemssad get $loop value]" "CLOSED" ] } {
			set gemsActive ON
		}
	}
	if { [string equal -nocase "[sa gemssad get astromReady value]" "READY" ] } {
		set gemsActive ON
	}
	if { $gemsActive ne $oldVal } {
		return 1
	}
	return 0
}

#ODGW special commands
itcl::body RealGems::setODGWSize { size {apply 1}} {
   cs gems::odgwSetup set odgwSize $size
   $logger logmess "gems::setODGWSize $size"
   
   #Autoset idleRows and sciRows
   setODGWSciRows [calparam odgwGetSciRows $size] 0
   setODGWIdleRows [calparam odgwGetIdleRows $size] 0
   setODGWDisplayRate [calparam odgwGetDisplayRate $size] 0

   set lastCmdSys applyC
   if { $apply } {
      catch {cs gems::odgwSetup post}
   }
}

itcl::body RealGems::getODGWSize {} {
   return [sa odgwsad get odgwSize value]
}

itcl::body RealGems::setODGWSciRows { num {apply 1}} {
   cs gems::odgwSetup set numSciRows $num
   $logger logmess "gems::setODGWSciRows $num"
   set lastCmdSys applyC
   if { $apply } {
      catch {cs gems::odgwSetup post}
   }
}

itcl::body RealGems::getODGWSciRows {} {
   return [sa odgwsad get odgwSciRows value]
}

itcl::body RealGems::setODGWIdleRows { num {apply 1}} {
   cs gems::odgwSetup set numIdleRows $num
   $logger logmess "gems::setODGWIdleRows $num"
   set lastCmdSys applyC
   if { $apply } {
      catch {cs gems::odgwSetup post}
   }
}

itcl::body RealGems::getODGWIdleRows {} {
   return [sa odgwsad get odgwIdleRows value]
}

itcl::body RealGems::setODGWDisplay { opt {apply 1} } {
   cs gems::odgwSetup set odgwDisplay $opt
   $logger logmess "gems::odgwDisplay $opt"
   set lastCmdSys applyC
   if { $apply } {
      catch {cs gems::odgwSetup post}
   }
}
itcl::body RealGems::getODGWDisplayRate {} {
   return [sa odgwsad get odgwDisplayRate value]
}

itcl::body RealGems::setODGWDisplayRate { val {apply 1}} {
   cs gems::odgwSetup set odgwDisplayRate $val
   $logger logmess "gems::setODGWDisplayRate $val"
   set lastCmdSys applyC
   if { $apply } {
      catch {cs gems::odgwSetup post}
   }
}

itcl::body RealGems::waitForCmdIdle {{timeout 1000}} {
   set elapsedTime 0
   while {$timeout==0 || $elapsedTime<$timeout} {
      if {[getCommandState] eq "IDLE"} {
         return ok
      } elseif {[getCommandState] eq "ERROR"} {
         return error
      }
      after 100
      set elapsedTime [expr $elapsedTime + 100]
      update
   }
   return timeout
}

itcl::body RealGems::setupLoops {loopList sources} {
   if { [llength $sources] > 0 } {
      set change [setTTLoopInputs $sources]
   } else {
      set change 0
   }
   
   if { [lsearch $loopList lwfs] >= 0 } {
      if { [getLGSLoopState] ne "CLOSED" } {
         cs gems::lgsLoopCtrl set cmd START
         set change 1
      }
   } else {
      if { [getLGSLoopState] ne "OPEN" } {
         cs gems::lgsLoopCtrl set cmd STOP
         set change 1
      }
   }
   if { [lsearch $loopList ani] >= 0 } {
      if { [getAniLoopState] ne "CLOSED" } {
         cs gems::taLoopCtrl set cmd START
         set change 1
      }
   } else {
      if { [getAniLoopState] ne "OPEN" } {
         cs gems::taLoopCtrl set cmd STOP
         set change 1
      }
   }
   if { [lsearch $loopList tt] >= 0 } {
      if { [getTTLoopState] ne "CLOSED" } {
         cs gems::ttLoopCtrl set cmd START
         set change 1
      }
   } else {
      if { [getTTLoopState] ne "OPEN" } {
         cs gems::ttLoopCtrl set cmd STOP
         set change 1
      }
   }
   if { [lsearch $loopList flex] >= 0 } {
      if { [getFlexLoopState] ne "CLOSED" } {
         cs gems::flexLoopCtrl set cmd START
         set change 1
      }
   } else {
      if { [getFlexLoopState] ne "OPEN" } {
         cs gems::flexLoopCtrl set cmd STOP
         set change 1
      }
   }
   if { [lsearch $loopList sfs] >= 0 } {
      if { [getFocLoopState] ne "CLOSED" } {
         cs gems::focLoopCtrl set cmd START
         set change 1
      }
   } else {
      if { [getFocLoopState] ne "OPEN" } {
         cs gems::focLoopCtrl set cmd STOP
         set change 1
      }
   }
   if { [lsearch $loopList m1] >= 0 } {
      if { [getM1OffloadState] ne "CLOSED" } {
         cs gems::m1OffloadCtrl set cmd START
         set change 1
      }
   } else {
      if { [getM1OffloadState] ne "OPEN" } {
         cs gems::m1OffloadCtrl set cmd STOP
         set change 1
      }
   }
   if { [lsearch $loopList m2] >= 0 } {
      if { [getM2OffloadState] ne "CLOSED" } {
         cs gems::m2OffloadCtrl set cmd START
         set change 1
      }
   } else {
      if { [getM2OffloadState] ne "OPEN" } {
         cs gems::m2OffloadCtrl set cmd STOP
         set change 1
      }
   }
   if { [lsearch $loopList rot] >= 0 } {
      if { [getRotOffloadState] ne "CLOSED" } {
         cs gems::crLoopCtrl set cmd START
         set change 1
      }
   } else {
      if { [getRotOffloadState] ne "OPEN" } {
         cs gems::crLoopCtrl set cmd STOP
         set change 1
      }
   }
   set lastCmdSys gemssad
   if { $change } {
      catch {cs gems::lgsLoopCtrl post}
   }
}

itcl::body RealGems::calculateBaseExpTime { idList tolerance } {
   set len [llength $idList]
   # return a default value if no ODGW is active
   if { $len == 0 } {
      return 0.1
   }
   set expTimes ""
   for { set i 0 } { $i < $len } { incr i } {
      lappend expTimes $odgwExpTime([lindex $idList $i])
   }
   set expTimes [lsort -real -increasing -unique $expTimes]
   set len [llength $expTimes]
   #if only one ODGW, or all have the same exposure time, return that value
   if { $len == 1 } {
      return $expTimes
   }
   #Find a big exposure time that keeps al exposure times within tolerance.
   #The method uses brute force to find a suitable value.
   set minT [lindex $expTimes 0]
   set bestExpTime $minExpTime
   for { set i 0 } { $i < $len } { incr i } {
      set expTime [lindex $expTimes $i]
      set minN [expr round ( $expTime / ( $minT*(1.0+$tolerance) ) ) ]
      set minN [expr $minN>0 ? $minN : 1]
      set maxN [expr floor ( $expTime / $minExpTime ) ]
      for { set j $minN } { $j <= $maxN } { incr j } {
         set baseExpTime [expr $expTime / $j]
         set k 0
         for { } { $k < $len } { incr k } {
            if { $k != $i } {
               set testExpTime [lindex $expTimes $k]
               set mult [expr round( $testExpTime/$baseExpTime ) ]
               set mult [expr $mult>0 ? $mult : 1]
               if { [expr abs( $mult * $baseExpTime / $testExpTime - 1.0 ) ] > $tolerance } {
                  break
               }
            }
         }
         if { $k == $len } {
            if { $baseExpTime > $bestExpTime } { 
               set  bestExpTime $baseExpTime
            }
            break
         }
      }
   }
   return $bestExpTime
}

