#+
# RemoteGuideControl.itcl
# 
# Functions to send guide configuration to Seqexec Server
#
# J. Luhrs January 28th, 2019
#+

package require Itcl
package require http
package require json::write 

itcl::class RemoteGuideControl {
    constructor {uri s} {}
    
    variable baseURI
    variable site
    variable allDisabled
    variable allDisabledWithoutGaos
    variable gaosName
    private common path "api/seqexec/guide"
    private common timeout 2000
    
    method sendConfiguration {ao includeGaos}
    method disable {includeGaos}
    private method send {body}
    private method altairConfig {mode aoOn strapOn sfoOn useOI useP1 oiBlend}
    private method gemsConfig {aoOn ttgs1On ttgs2On ttgs3On odgw1On odgw2On odgw3On odgw4On}
    private method buildConfig {m1GuideOn m1Source m2GuideOn m2Sources m2ComaOn mountGuideOn gaos}
    private method toJsonBoolean {v} { return [expr $v ? "{true}" : "{false}" ] }
    private method toJsonString {v} { if { $v eq "" } { return null } else { return [json::write string $v]} }
}

itcl::body RemoteGuideControl::constructor {uri s} {
    set baseURI $uri
    set site $s
    
    if {$site eq "MK"} {
        set gaosName altair
        set disabledGaos [altairConfig LGS false false false false false false]  
    } else {
        set gaosName gems
        set disabledGaos [gemsConfig false false false false false false false false]
    }
    set allDisabled [buildConfig false {} false {} false false $disabledGaos]
    set allDisabledWithoutGaos [buildConfig false {} false {} false false {}]
}

itcl::body RemoteGuideControl::disable {includeGaos} {
    if {$includeGaos} {
        send $allDisabled
    } else {
        send $allDisabledWithoutGaos
    }
}

itcl::body RemoteGuideControl::sendConfiguration {ao includeGaos} {
    if {$includeGaos} {
        if {$site eq "MK"} {
            set gaos [altairConfig [expr [$ao state useLwfs] ? "{LGS}" : "{NGS}" ] \
                                   [$ao cget -gaos] \
                                   [$ao cget -ttgsloop] \
                                   [$ao cget -sfoloop] \
                                   [$ao cget -lgsoisource] \
                                   [$ao cget -lgsp1source] \
                                   [$ao cget -oiblend] \
                     ]
        } else {
            set gems [$ao getGaosObj]
            set gaos [gemsConfig [$gems cget -lwfsLoop] \
                                 [$gems cget -ttgs1Active] \
                                 [$gems cget -ttgs2Active] \
                                 [$gems cget -ttgs3Active] \
                                 [$gems cget -odgw1Active] \
                                 [$gems cget -odgw2Active] \
                                 [$gems cget -odgw3Active] \
                                 [$gems cget -odgw4Active] \
                     ]
        }
    } else {
        set gaos {}
    }
    
    set m2Sources {}
    foreach {var src} {p1guide PWFS1 p2guide PWFS2 oiguide OIWFS aoguide GAOS} {
        if { [$ao cget -$var] eq "On" } { lappend m2Sources $src }
    }
    
    set body [buildConfig [$ao cget -m1corr] \
                          [$ao cget -m1source] \
                          [expr [llength m2Sources ] > 0 ] \
                          $m2Sources \
                          [$ao cget -comacorr] \
                          [string compare [$ao cget -mountguide] "none" ] \
                          $gaos \
             ]
    
    return [send $body]
}

itcl::body RemoteGuideControl::send {body} {
    set header [list Content-type application/json] 
    set uri [format "%s/%s" $baseURI $path]
    
    set t [http::geturl $uri -query $body -headers $header -timeout $timeout]
    set status [http::status $t]
    if { $status ne "ok" } {
        set ret [list $status [http::error $t] ]
    } else {
        set httpStatus [http::ncode $t]
        if { $httpStatus != 200 } {
            set ret [list "httpError($httpStatus)" [http::data $t] ] 
        } else {
            set ret [list "ok" ""]
        }
    }
    http::cleanup $t
    
    return $ret

}

itcl::body RemoteGuideControl::buildConfig {m1GuideOn m1Source m2GuideOn m2Sources m2ComaOn \
    mountGuideOn gaos} {
    
    set m2srcs {}
    foreach s $m2Sources {
        if { $s ne "" } { lappend m2srcs [json::write string $s ] }
    }
        
    if { $gaos ne "" } {
        set gaosGuide [json::write object \
                        $gaosName $gaos \
                      ]
    } else {
        set gaosGuide null
    }
        
    return [json::write object \
        tcsGuide [json::write object \
            m1Guide [json::write object \
                on [toJsonBoolean $m1GuideOn] \
                source [toJsonString $m1Source] \
            ] \
            m2Guide [json::write object \
                on [toJsonBoolean $m2GuideOn] \
                sources [eval json::write array $m2srcs] \
                comaOn [toJsonBoolean $m2ComaOn] \
            ] \
            mountGuideOn [toJsonBoolean $mountGuideOn] \
        ] \
        gaosGuide $gaosGuide \
    ]
}

itcl::body RemoteGuideControl::altairConfig {mode aoOn strapOn sfoOn useOI useP1 oiBlend} {
    if { [catch { expr [sa tcssad get aoDemandx] - [sa tcssad get xoffsetPoA1] } x ] } { set x null }
    if { [catch { expr [sa tcssad get aoDemandy] - [sa tcssad get yoffsetPoA1] } y ] } { set y null }
	
    return [json::write object \
        mode [toJsonString $mode] \
        aoOn [toJsonBoolean $aoOn] \
        strapOn [toJsonBoolean $strapOn] \
        sfoOn [toJsonBoolean $sfoOn] \
        useOI [toJsonBoolean $useOI] \
        useP1 [toJsonBoolean $useP1] \
        oiBlend [toJsonBoolean $oiBlend] \
        aogsx $x \
        aogsy $y \
    ]
}

itcl::body RemoteGuideControl::gemsConfig {aoOn ttgs1On ttgs2On ttgs3On odgw1On odgw2On odgw3On odgw4On} {
    return [json::write object \
        aoOn [toJsonBoolean $aoOn] \
        ttgs1On [toJsonBoolean $ttgs1On] \
        ttgs2On [toJsonBoolean $ttgs2On] \
        ttgs3On [toJsonBoolean $ttgs3On] \
        odgw1On [toJsonBoolean $odgw1On] \
        odgw2On [toJsonBoolean $odgw2On] \
        odgw3On [toJsonBoolean $odgw3On] \
        odgw4On [toJsonBoolean $odgw4On] \
    ]
}
