#+
# SimGems
#
# Simulated implementation of IGemsSys
#
# J Luhrs 25 March 2010
#
#  $Id: Exp $
#-

itcl::class SimGems {
	inherit IGemsSys  
public {
	method slewReset {}
	#Loop control commands
	method openLGSLoop {}
	method closeLGSLoop {}
	method openTTLoop {}
	method closeTTLoop {}
	method openFocLoop {}
	method closeFocLoop {}
	method openFlexLoop {}
	method closeFlexLoop {}
	method openAniLoop {}
	method closeAniLoop {}
	method disableM1Offload {}
	method enableM1Offload {}
	method disableM2Offload {}
	method enableM2Offload {}
	method disableRotOffload {}
	method enableRotOffload {}
	method pauseLoops {why}
	method resumeLoops {}
	method stopLoops {}
   method setupLoops {loopList sources}
	
	#Loop configuration
	method configureNGS {sources}
	
	#Astrometry
	method setAstroMode {mode}
	method startAstrometry {}
	method stopAstrometry {}
	
	method moveADC {pos}
	method startADC {}
	method stopADC {}
	method moveBeamSplitter {pos}

	#WFS control commands
   method setupODGW {idList}
   method startODGW {idList}
   method stopODGW {idList}
	method startTTWFS {idList}
	method stopTTWFS {idList}
	method startLGSWFS {}
	method stopLGSWFS {}
	method startSFS {}
	method stopSFS {}
	method setODGWExposure {id val}
	method setTTWFSExposure {id val}
	method setLGSWFSExposure {val}
	method setSFSExposure {val}

   #ODGW special commands
   method setODGWSize { size {apply 1} }
   method getODGWSize {}
   method setODGWSciRows { num {apply 1} }
   method getODGWSciRows {}
   method setODGWIdleRows { num {apply 1} }
   method getODGWIdleRows {}
   method setODGWDisplay { opt {apply 1} }

	#States
	method getGemsActive {}
	method getLoopsState {}
	method getLGSLoopState {}
	method getTTLoopState {}
	method getFocLoopState {}
	method getFlexLoopState {}
	method getAniLoopState {}
	method getM1OffloadState {}
	method getM2OffloadState {}
	method getRotOffloadState {}
	method getTTLoopSources {}
   method getFlexLoopSources {}
	method getODGWActive {id}
   method getODGWEnabled {id}
   method getTTWFSActive {id}
	method getLGSWFSActive {}
	method getSFSActive {}
	method getODGWExposure {id}
	method getTTWFSExposure {id}
	method getLGSWFSExposure {}
	method getSFSExposure {}
	method getODGWCounts {id}
	method getTTWFSCounts {id}
	method getLGSWFSCounts {id}
	method getSFSCounts {}
	method getAstroMode {}
	method getAstrometryState {}
	method getADCPos {}
	method getADCLoopState {}
	method getBeamSplitterPos {}
	method getLaserProp {}
	
	#Command state
	method getCommandState {}
	method getLastError {}

#Observable interface
	method subscribe {observer}
	method unsubscribe {observer}
		
	variable logger logactions

	constructor {} {}
	destructor {}
}
private {
	variable lgsLoopState OPEN 
	variable ttLoopState OPEN
	variable focLoopState OPEN
	variable flexLoopState OPEN
	variable aniLoopState OPEN
	variable m1OffloadState OFF
	variable m2OffloadState OFF
	variable rotOffloadState OFF
	variable ttLoopSources ""
	variable astroMode Off
	variable astroState OFF
	variable adcPos Out
	variable adcState OFF
	variable beamSplitterPos Out
	variable ttwfsExposure
	variable odgwExposure
	variable sfsExposure 100
	variable lgswgsExposure 0.01
	variable ttwfsActive
	variable odgwActive 0
   variable odgwEnabled
	variable sfsActive OFF
	variable lgswfsActive OFF
	variable ttwfsCounts
	variable odgwCounts
	variable sfsCounts 0
	variable lgswfsCounts
	variable loopsSettled FALSE
	variable laserProp OFF
	
	variable gemsActive OFF
   
   variable odgwSize 8
   variable odgwSciRows 8
   variable odgwIdleRows 8
      	
	variable loopsSettling 0
	variable loopsClosed 0 
	
	variable cmdState IDLE
	variable errMsg ""

	variable observerList {}
	
	method notify {reasons}
	
	method simDelayedChange { var value {reason ""} }
	method simLoopStabilize { var delay {reason ""} }
	method simLoopOpen {var {reason ""} }
	method simLoopClose {var {reason ""} }
	method simAstroStabilize {}
	method simAstroStart {}
	method simAstroStop {}
	method simStartMove { var value delay {reason ""} }
	method simEndMove { var value {reason ""} }
   method simSetupODGW {states}
	method openLoop {name var {reason ""}}
	method closeLoop {name var {delay 2000} {reason ""}}
	method configCmd { name var value {delay 200} {reasons ""}}
	method beginCmd {}
	method endCmd {}
	
	method checkGemsActive {}
	
	#Simulation
	variable timerId {}
	method simCycle {}
}
}

itcl::body SimGems::constructor {} {
	for { set i 1 } { $i <= 3 } { incr i } {
		set ttwfsExposure($i) 100
		set ttwfsActive($i) OFF
		set ttwfsCounts($i) 0
	}
	for { set i 1 } { $i <= 4 } { incr i } {
		set odgwExposure($i) 100
		set odgwEnabled($i) OFF
		set odgwCounts($i) 0
	}
	for { set i 1 } { $i <= 5 } { incr i } {
		set lgswfsCounts($i) 0
	}
	set timerId [after idle [itcl::code $this simCycle] ]
}

itcl::body SimGems::destructor {} {
	after cancel $timerId
}

itcl::body SimGems::slewReset {} {
	$logger logmess "SimGems: slewReset"
}

#Loop control commands
itcl::body SimGems::openLoop {name var {reason ""}} {
	$logger logmess "SimGems: open $name loop command"
	if { [beginCmd] } {
		after 200 [itcl::code $this simLoopOpen $var $reason]
	}
}

itcl::body SimGems::closeLoop {name var {delay 2000} {reason ""}} {
	$logger logmess "SimGems: close $name loop command"
	if { [beginCmd] } {
		after 200 [itcl::code $this simLoopStabilize $var $delay $reason]
	}
}

itcl::body SimGems::openLGSLoop {} {
	openLoop LGS lgsLoopState
}

itcl::body SimGems::closeLGSLoop {} {
	closeLoop LGS lgsLoopState
}

itcl::body SimGems::openTTLoop {} {
	openLoop TT ttLoopState
}

itcl::body SimGems::closeTTLoop {} {
	closeLoop TT ttLoopState
}

itcl::body SimGems::openFocLoop {} {
	openLoop Focus focLoopState
}

itcl::body SimGems::closeFocLoop {} {
	closeLoop Focus focLoopState
}

itcl::body SimGems::openFlexLoop {} {
	openLoop Flexure flexLoopState
}

itcl::body SimGems::closeFlexLoop {} {
	closeLoop Flexure flexLoopState
}

itcl::body SimGems::openAniLoop {} {
	openLoop Anisoplanetism aniLoopState
}

itcl::body SimGems::closeAniLoop {} {
	closeLoop Anisoplanetism aniLoopState
}

itcl::body SimGems::disableM1Offload {} {
	configCmd "M1 Loop" m1OffloadState OFF
}

itcl::body SimGems::enableM1Offload {} {
	configCmd "M1 Loop" m1OffloadState ON
}

itcl::body SimGems::disableM2Offload {} {
	configCmd "M2 Loop" m2OffloadState OFF
}

itcl::body SimGems::enableM2Offload {} {
	configCmd "M2 Loop" m2OffloadState ON
}

itcl::body SimGems::disableRotOffload {} {
	configCmd "Rotator Loop" rotOffloadState OFF
}

itcl::body SimGems::enableRotOffload {} {
	configCmd "Rotator Loop" rotOffloadState ON
}

itcl::body SimGems::pauseLoops {why} {
	#TODO: pendig implementation
}

itcl::body SimGems::resumeLoops {} {
	#TODO: pendig implementation
}

itcl::body SimGems::stopLoops {} {
	#TODO: pendig implementation
}

itcl::body SimGems::setupLoops {loopList sources} {
   if { [beginCmd] } {
      if { [llength $sources] > 0 } {
         $logger logmess "SimGems: configure NGS config to $sources"
         after 200 "[itcl::code $this simDelayedChange ttLoopSources $sources]"
      }
      if { [lsearch $loopList lwfs] >= 0 } {
         if { [getLGSLoopState] ne "CLOSED" } {
            $logger logmess "SimGems: close LGS loop command"
            after 200 [itcl::code $this simLoopStabilize lgsLoopState 2000]
         }
      } else {
         if { [getLGSLoopState] eq "CLOSED" } {
            $logger logmess "SimGems: open LGS loop command"
            after 200 [itcl::code $this simLoopOpen lgsLoopState]
         }
      }
      if { [lsearch $loopList ani] >= 0 } {
         if { [getAniLoopState] ne "CLOSED" } {
            $logger logmess "SimGems: close Ani loop command"
            after 200 [itcl::code $this simLoopStabilize aniLoopState 2000]
         }
      } else {
         if { [getAniLoopState] eq "CLOSED" } {
            $logger logmess "SimGems: open Ani loop command"
            after 200 [itcl::code $this simLoopOpen aniLoopState]
         }
      }
      if { [lsearch $loopList tt] >= 0 } {
         if { [getTTLoopState] ne "CLOSED" } {
            $logger logmess "SimGems: close TT loop command"
            after 200 [itcl::code $this simLoopStabilize ttLoopState 2000]
         }
      } else {
         if { [getTTLoopState] eq "CLOSED" } {
            $logger logmess "SimGems: open TT loop command"
            after 200 [itcl::code $this simLoopOpen ttLoopState]
         }
      }
      if { [lsearch $loopList flex] >= 0 } {
         if { [getFlexLoopState] ne "CLOSED" } {
            $logger logmess "SimGems: close Flex loop command"
            after 200 [itcl::code $this simLoopStabilize flexLoopState 2000]
         }
      } else {
         if { [getFlexLoopState] eq "CLOSED" } {
            $logger logmess "SimGems: open Flex loop command"
            after 200 [itcl::code $this simLoopOpen flexLoopState]
         }
      }
      if { [lsearch $loopList sfs] >= 0 } {
         if { [getFocLoopState] ne "CLOSED" } {
            $logger logmess "SimGems: close SFS loop command"
            after 200 [itcl::code $this simLoopStabilize focLoopState 2000]
         }
      } else {
         if { [getFocLoopState] eq "CLOSED" } {
            $logger logmess "SimGems: open SFS loop command"
            after 200 [itcl::code $this simLoopOpen focLoopState]
         }
      }
      if { [lsearch $loopList m1] >= 0 } {
         if { [getM1OffloadState] ne "START" } {
            $logger logmess "SimGems: configure M1 Offload to ON"
            after 200 "[itcl::code $this simDelayedChange m1OffloadState ON]"
         }
      } else {
         if { [getM1OffloadState] eq "START" } {
            $logger logmess "SimGems: configure M1 Offload to OFF"
            after 200 "[itcl::code $this simDelayedChange m1OffloadState OFF]"
         }
      }
      if { [lsearch $loopList m2] >= 0 } {
         if { [getM2OffloadState] ne "START" } {
            $logger logmess "SimGems: configure M2 Offload to ON"
            after 200 "[itcl::code $this simDelayedChange m2OffloadState ON]"
         }
      } else {
         if { [getM2OffloadState] eq "START" } {
            $logger logmess "SimGems: configure M2 Offload to OFF"
            after 200 "[itcl::code $this simDelayedChange m2OffloadState OFF]"
         }
      }
      if { [lsearch $loopList rot] >= 0 } {
         if { [getRotOffloadState] ne "START" } {
            $logger logmess "SimGems: configure Rotator Offload to ON"
            after 200 "[itcl::code $this simDelayedChange rotOffloadState ON]"
         }
      } else {
         if { [getRotOffloadState] eq "START" } {
            $logger logmess "SimGems: configure Rotator Offload to OFF"
            after 200 "[itcl::code $this simDelayedChange rotOffloadState OFF]"
         }
      }
   }
}

#Loop configuration
itcl::body SimGems::configureNGS {sources} {
	configCmd "NGS config" ttLoopSources $sources
}


#Astrometry
itcl::body SimGems::setAstroMode {mode} {
	configCmd "Astrometry Mode" astroMode $mode
}

itcl::body SimGems::startAstrometry {} {
	$logger logmess "SimGems: start Astrometry"
	if { [beginCmd] } {
		after 200 [itcl::code $this simAstroStabilize]
	}
}

itcl::body SimGems::stopAstrometry {} {
	$logger logmess  "SimGems: stop Astrometry"
	if { [beginCmd] } {
		after 200 [itcl::code $this simAstroStop]
	}
}

itcl::body SimGems::moveADC {pos} {
	$logger logmess "SimGems: move ADC to $pos"
	if { [beginCmd] } {
		after 200 [itcl::code $this simStartMove adcPos $pos 20000]
	}
}

itcl::body SimGems::startADC {} {
	configCmd "ADC" adcState ON 500
}

itcl::body SimGems::stopADC {} {
	configCmd "ADC" adcState OFF
}

itcl::body SimGems::moveBeamSplitter {pos} {
	$logger logmess "SimGems: move Beam Splitter to $pos"
	if { [beginCmd] } {
		after 200 [itcl::code $this simStartMove beamSplitterPos $pos 20000]
	}
}

#WFS control commands
itcl::body SimGems::setupODGW {idList} {
   if {[beginCmd]} {
      set val {}
      foreach id {1 2 3 4} {
         if {[lsearch $idList $id] == -1} {
            lappend val $id OFF
         } else {
            lappend val $id ON
         }
      }
      $logger logmess "SimGems: configure odgwEnabled to $val"
      after 200 [itcl::code $this simSetupODGW $val]
      #configCmd "ODGW enabling" odgwEnabled $val 200 "odgwActive(1) odgwActive(2) odgwActive(3) odgwActive(4)"      
   }
}

itcl::body SimGems::simSetupODGW {states} {
   array set odgwEnabled $states
   endCmd
   
   if { !$odgwEnabled(1) && !$odgwEnabled(2) && !$odgwEnabled(3) && !$odgwEnabled(4) } {
      set odgwActive 0
   }
   notify "odgwActive(1) odgwActive(2) odgwActive(3) odgwActive(4)"
}

itcl::body SimGems::startODGW {idList} {
   if { $odgwEnabled(1) || $odgwEnabled(2) || $odgwEnabled(3) || $odgwEnabled(4) } {
   	configCmd "ODGW guide" odgwActive 1 200 "odgwActive(1) odgwActive(2) odgwActive(3) odgwActive(4)"
   } else {
      configCmd "ODGW guide" odgwActive 0 200 "odgwActive(1) odgwActive(2) odgwActive(3) odgwActive(4)"
   }
}

itcl::body SimGems::stopODGW {idList} {
	configCmd "ODGW guide" odgwActive 0 200 "odgwActive(1) odgwActive(2) odgwActive(3) odgwActive(4)"
}

itcl::body SimGems::startTTWFS {idList} {
   if {[beginCmd]} {
      foreach id $idList {
         after 200 "[itcl::code $this simDelayedChange ttwfsActive($id) ON]"
      }
   }
}

itcl::body SimGems::stopTTWFS {idList} {
   if {[beginCmd]} {
      foreach id $idList {
         after 200 "[itcl::code $this simDelayedChange ttwfsActive($id) OFF]"
      }
   }
}

itcl::body SimGems::startLGSWFS {} {
	configCmd LGSWFS lgswfsActive ON
}

itcl::body SimGems::stopLGSWFS {} {
	configCmd LGSWFS lgswfsActive OFF
}

itcl::body SimGems::startSFS {} {
	configCmd SFS sfsActive ON
}

itcl::body SimGems::stopSFS {} {
	configCmd SFS sfsActive OFF
}

itcl::body SimGems::setODGWExposure {id val} {
	configCmd "ODGW $id Exposure" odgwExposure($id) $val
}

itcl::body SimGems::setTTWFSExposure {id val} {
	configCmd "TTWFS $id Exposure" ttwfsExposure($id) $val
}

itcl::body SimGems::setLGSWFSExposure {val} {
	configCmd "LGSWFS Exposure" lgswgsExposure $val
}

itcl::body SimGems::setSFSExposure {val} {
	configCmd "SFS Exposure" sfsExposure $val
}

itcl::body SimGems::checkGemsActive {} {
	set oldVal $gemsActive
	set gemsActive OFF
	foreach loop { ttLoopState aniLoopState flexLoopState focLoopState lgsLoopState } {
		if { [set $loop] eq "CLOSED" } {
			set gemsActive ON
		}
	}
	if { $astroState eq "ON" } {
		set gemsActive ON
	}
	if { $gemsActive ne $oldVal } {
		notify gemsActive
	}
}

#States
itcl::body SimGems::getGemsActive {} {
	return $gemsActive
}

itcl::body SimGems::getLoopsState {} {
	return [expr { ( $loopsSettled eq "TRUE" ) ? "READY" : "NOT READY" } ]
}

itcl::body SimGems::getLGSLoopState {} {
	return $lgsLoopState
}

itcl::body SimGems::getTTLoopState {} {
	return $ttLoopState
}

itcl::body SimGems::getFocLoopState {} {
	return $focLoopState
}

itcl::body SimGems::getFlexLoopState {} {
	return $flexLoopState
}

itcl::body SimGems::getAniLoopState {} {
	return $aniLoopState
}

itcl::body SimGems::getM1OffloadState {} {
	return [expr { ( $m1OffloadState eq "ON" ) ? "START" : "STOP" } ]
}

itcl::body SimGems::getM2OffloadState {} {
   return [expr { ( $m2OffloadState eq "ON" ) ? "START" : "STOP" } ]
}

itcl::body SimGems::getRotOffloadState {} {
   return [expr { ( $rotOffloadState eq "ON" ) ? "START" : "STOP" } ]
}

itcl::body SimGems::getTTLoopSources {} {
   set sources ""
   
   foreach {source loop mag} $ttLoopSources {
      if { $loop eq "Fast" } {
         lappend sources $source $mag
      }
   }
	return $sources
}

itcl::body SimGems::getFlexLoopSources {} {
   set sources ""
   
   foreach {source loop mag} $ttLoopSources {
      if { $loop eq "Flex" } {
         lappend sources $source $mag
      }
   }
   return $sources
}

itcl::body SimGems::getODGWActive {id} {
   if { $odgwActive } {
      return ON
   }
   return OFF
}

itcl::body SimGems::getODGWEnabled {id} {
   return $odgwEnabled($id)
}

itcl::body SimGems::getTTWFSActive {id} {
	return $ttwfsActive($id)
}

itcl::body SimGems::getLGSWFSActive {} {
	return $lgswfsActive
}

itcl::body SimGems::getSFSActive {} {
	return $sfsActive
}

itcl::body SimGems::getODGWExposure {id} {
	return $odgwExposure($id)
}

itcl::body SimGems::getTTWFSExposure {id} {
	return $ttwfsExposure($id)
}

itcl::body SimGems::getLGSWFSExposure {} {
	return $lgswgsExposure
}

itcl::body SimGems::getSFSExposure {} {
	return $sfsExposure
}

itcl::body SimGems::getODGWCounts {id} {
	return $odgwCounts($id)
}

itcl::body SimGems::getTTWFSCounts {id} {
	return $ttwfsCounts($id)
}

itcl::body SimGems::getLGSWFSCounts {id} {
	return $lgswfsCounts($id)
}

itcl::body SimGems::getSFSCounts {} {
	return $sfsCounts
}

itcl::body SimGems::getAstroMode {} {
	return $astroMode
}

itcl::body SimGems::getAstrometryState {} {
	return [expr { ( $astroState eq "ON" ) ? "READY" : "NOT READY" } ]
}

itcl::body SimGems::getADCPos {} {
	return $adcPos
}

itcl::body SimGems::getADCLoopState {} {
	return [expr { ( $adcState eq "ON" ) ? "CLOSED" : "OPEN" } ]
}

itcl::body SimGems::getBeamSplitterPos {} {
	return $beamSplitterPos
}

itcl::body SimGems::getLaserProp {} {
	return $laserProp
}

#Command state
itcl::body SimGems::getCommandState {} {
	return $cmdState
}

itcl::body SimGems::getLastError {} {
	return $errMsg
}


#Observable interface
itcl::body SimGems::subscribe {observer} {
# Check that the observer isn't already on the list.
	if { [lsearch -exact $observerList $observer] == -1 } {
# Append the observer to the list.
		lappend observerList $observer
	}
}

itcl::body SimGems::unsubscribe {observer} {
# Check that the observer is registered.
	set index [lsearch -exact $observerList $observer]
	if { $index != -1 } {
		set observerList [lreplace $observerList $index $index]
	}
}

itcl::body SimGems::notify {reasons} {
	foreach observer $observerList {
		$observer $reasons
	}
}

itcl::body SimGems::simDelayedChange { var value {reason ""} } {
   if { [array exists $var] } {
      array set $var $value
   } else {
   	set $var $value
   }
	if { $reason eq "" } {
		notify $var 
	} else {
		notify $reason
	}
	endCmd
}

itcl::body SimGems::simLoopStabilize { var delay {reason ""} } {
	incr loopsSettling
	if { $loopsSettled eq "TRUE"} {
		set loopsSettled FALSE
		notify loopsSettled
	}
	endCmd
	after $delay [itcl::code $this simLoopClose $var]
}

itcl::body SimGems::simLoopOpen {var {reason ""} } {
	set $var OPEN
	if { $reason eq "" } {
		notify $var 
	} else {
		notify $reason
	}
	checkGemsActive
	endCmd
	incr loopsClosed -1
	if { $loopsSettled eq "TRUE"  && $loopsClosed == 0 } {
		set loopsSettled FALSE
		notify loopsSettled
	}
}

itcl::body SimGems::simLoopClose {var {reason ""} } {
	set $var CLOSED
	if { $reason eq "" } {
		notify $var 
	} else {
		notify $reason
	}
	checkGemsActive
	incr loopsClosed
	incr loopsSettling -1
	if { $loopsSettled eq "FALSE" && $loopsSettling == 0 } {
		set loopsSettled TRUE
		notify loopsSettled
	}
}

itcl::body SimGems::simAstroStabilize {} {
	incr loopsSettling
	if { $loopsSettled eq "TRUE"} {
		set loopsSettled FALSE
		notify loopsSettled
	}
	endCmd
	switch [string toupper $astroMode] {
	REGULAR { set delay 15000 } 
	GOOD { set delay 30000 }
	BEST { set delay 120000 }
	default { set delay 1000 }
	}
	after $delay [itcl::code $this simAstroStart]
}

itcl::body SimGems::simAstroStop {} {
	set astroState OFF
	notify astroState 
	checkGemsActive
	endCmd
	incr loopsClosed -1
	if { $loopsSettled eq "TRUE"  && $loopsClosed == 0 } {
		set loopsSettled FALSE
		notify loopsSettled
	}
}

itcl::body SimGems::simAstroStart {} {
	set astroState ON
	notify astroState
	checkGemsActive
	incr loopsClosed
	incr loopsSettling -1
	if { $loopsSettled eq "FALSE" && $loopsSettling == 0 } {
		set loopsSettled TRUE
		notify loopsSettled
	}
}

itcl::body SimGems::beginCmd {} {
	if { $cmdState eq "BUSY" } {
		set cmdState ERROR
		set errMsg "ERROR: GeMS command in progress."
		set ret 0
	} else {
		set cmdState BUSY
		set errMsg ""
		set ret 1
	}
	notify cmdState
	return $ret
}

itcl::body SimGems::endCmd {} {
	if { $cmdState eq "BUSY" } {
		set cmdState IDLE
		notify cmdState
	}
}

itcl::body SimGems::configCmd { name var value {delay 200} {reasons ""}} {
	$logger logmess "SimGems: configure $name to $value"
	if { [beginCmd] } {
		after $delay "[itcl::code $this simDelayedChange $var $value $reasons]"
	}
}

itcl::body SimGems::simCycle {} {
	foreach {stateVar countVar} { ttwfsActive(1) ttwfsCounts(1)  \
											ttwfsActive(2) ttwfsCounts(2)  \
											ttwfsActive(3) ttwfsCounts(3)  \
											odgwEnabled(1) odgwCounts(1)   \
                                 odgwEnabled(2) odgwCounts(2)   \
                                 odgwEnabled(3) odgwCounts(3)   \
                                 odgwEnabled(4) odgwCounts(4)   \
											sfsActive      sfsCounts       \
											lgswfsActive   lgswfsCounts(1) \
											lgswfsActive   lgswfsCounts(2) \
											lgswfsActive   lgswfsCounts(3) \
											lgswfsActive   lgswfsCounts(4) \
											lgswfsActive   lgswfsCounts(5) } {
		set oldVal [set $countVar]
		if { [set $stateVar] eq "ON" } {
			set $countVar [expr "1000 + round( rand() * 1000 )"]
		} else {
			set $countVar 0
		}
		if { $oldVal != [set $countVar] } {
			notify $countVar
		}
	}
	set timerId [after 1000 [itcl::code $this simCycle] ]
}

itcl::body SimGems::simStartMove { var value delay {reason ""} } {
	if { [set $var] ne $value } {
		set $var Moving
		if { $reason eq "" } {
			notify $var 
		} else {
			notify $reason
		}
		endCmd
		after $delay [itcl::code $this simEndMove $var $value $reason]
	} else {
		endCmd
	}
}

itcl::body SimGems::simEndMove { var value {reason ""} } {
	set $var $value
	if { $reason eq "" } {
		notify $var 
	} else {
		notify $reason
	}
}

itcl::body SimGems::setODGWSize { size {apply 1} } {
   configCmd "ODGW Size" odgwSize $size
}

itcl::body SimGems::getODGWSize {} {
   return $odgwSize
}

itcl::body SimGems::setODGWSciRows { num {apply 1} } {
   configCmd "ODGW Science Rows" odgwSciRows $num
}

itcl::body SimGems::getODGWSciRows {} {
   return $odgwSciRows
}

itcl::body SimGems::setODGWIdleRows { num {apply 1} } {
   configCmd "ODGW Idle ROws" odgwIdleRows $num
}

itcl::body SimGems::getODGWIdleRows {} {
   return $odgwIdleRows
}

itcl::body SimGems::setODGWDisplay { opt {apply 1} } {}