#+
#  SlewOptionsControl <- ComponentControl
#
#  A SlewOptionsControl is a ComponentControl widget with checkbutton widgets 
#  for each of the Slew CAD parameters plus options for disableing and
#  reseting all active optics.
#
#  D Terrett 16 January 2004
#
#  Copyright CCLRC
#+

itcl::class SlewOptionsControl {
   inherit ComponentControl
   constructor args {}
   public {
      method load {name}
      method reset {}
      method save {name}
   }
   private {
      variable chopThrow
      variable sourceOffset
      variable sourceDifTr
      variable mountOffset
      variable mountDifTr
      variable filter1
      variable filter2
      variable pointing
      variable guiding
      variable guideOffset
      variable instrOffset
      variable resetao
      variable disableao
      variable ignoreao
      variable ltcscheck
      variable restoreM1
   }
}

itk::usual SlewOptionsControl {
   keep -borderwidth -cursor -font -highlightthickness -insertborderwidth \
         -insertofftime -insertontime -insertwidth -labelfont -popupcursor \
         -selectborderwidth -textfont -title
}

itcl::body SlewOptionsControl::constructor args {

# Frame for all the options.
   itk_component add options {
      frame $itk_interior.options -bd 2 -relief ridge
   }
   pack $itk_interior.options -fill x -expand y

# Checkbuttons for the options.
   set w $itk_component(options)
   itk_component add chopThrow {
      checkbutton $w.chopThrow -variable [itcl::scope chopThrow] \
            -onvalue On -offvalue Off \
            -text [lindex [cs slew info chopThrow] 2]
   }
   itk_component add sourceOffset {
      checkbutton $w.sourceOffset -variable [itcl::scope sourceOffset] \
            -onvalue On -offvalue Off \
            -text [lindex [cs slew info sourceOffset] 2]
   }
   itk_component add sourceDifTr {
      checkbutton $w.sourceDifTr -variable [itcl::scope sourceDifTr] \
            -onvalue On -offvalue Off \
            -text [lindex [cs slew info sourceDifTr] 2]
   }
   itk_component add mountOffset {
      checkbutton $w.mountOffset -variable [itcl::scope mountOffset] \
            -onvalue On -offvalue Off \
            -text [lindex [cs slew info mountOffset] 2]
   }
   itk_component add mountDifTr {
      checkbutton $w.mountDifTr -variable [itcl::scope mountDifTr] \
            -onvalue On -offvalue Off \
            -text [lindex [cs slew info mountDifTr] 2]
   }
   itk_component add filter1 {
      checkbutton $w.filter1 -variable [itcl::scope filter1] \
            -onvalue On -offvalue Off \
            -text [lindex [cs slew info filter1] 2]
   }
   itk_component add filter2 {
      checkbutton $w.filter2 -variable [itcl::scope filter2] \
            -onvalue On -offvalue Off \
            -text [lindex [cs slew info filter2] 2]
   }
   itk_component add pointing {
      checkbutton $w.pointing -variable [itcl::scope pointing] \
            -onvalue On -offvalue Off \
            -text [lindex [cs slew info pointing] 2]
   }
   itk_component add guiding {
      checkbutton $w.guiding -variable [itcl::scope guiding] \
            -onvalue On -offvalue Off \
            -text [lindex [cs slew info guiding] 2]
   }
   itk_component add guideOffset {
      checkbutton $w.guideOffset -variable [itcl::scope guideOffset] \
            -onvalue On -offvalue Off \
            -text [lindex [cs slew info guideOffset] 2]
   }
   itk_component add instrOffset {
      checkbutton $w.instrOffset -variable [itcl::scope instrOffset] \
            -onvalue On -offvalue Off \
            -text [lindex [cs slew info instrOffset] 2]
   }
   itk_component add resetao {
      checkbutton $w.resetao -variable [itcl::scope resetao] \
            -text "Reset active optics configuration"
   }
   itk_component add disableao {
      checkbutton $w.disableao -variable [itcl::scope disableao] \
            -text "Disable active optics configuration"
   }
   itk_component add ltcscheck {
      checkbutton $w.ltcscheck -variable [itcl::scope ltcscheck] \
            -text "Check for collisions when using LGS"
   }
   itk_component add restorefig {
      checkbutton $w.restorefig -variable [itcl::scope restoreM1] \
            -text "Automatically restore M1 and M2 after using GAOS"
   }
   pack $itk_component(chopThrow) $itk_component(sourceOffset) \
         $itk_component(sourceDifTr) $itk_component(mountOffset) \
         $itk_component(mountDifTr) $itk_component(filter1) \
         $itk_component(filter2) $itk_component(pointing) \
         $itk_component(guiding) $itk_component(guideOffset) \
         $itk_component(instrOffset) $itk_component(resetao) \
         $itk_component(disableao) $itk_component(ltcscheck) \
         $itk_component(restorefig) -pady 2 -anchor w
   if { [calparam cget -site] eq "CP" } {
      itk_component add ignoreao {
         checkbutton $w.ignoreao -variable [itcl::scope ignoreao] \
               -text "Don't apply adaptive optics configuration"
      }
      pack $itk_component(ignoreao) -pady 2 -anchor w
   }

# Set the object description.
   set description "slew options"

   eval itk_initialize $args
}

itcl::body SlewOptionsControl::reset {} {
}

itcl::body SlewOptionsControl::load {name} {
   set chopThrow [$name cget -chopThrow]
   set sourceOffset [$name cget -sourceOffset]
   set sourceDifTr [$name cget -sourceDifTr]
   set mountOffset [$name cget -mountOffset]
   set mountDifTr [$name cget -mountDifTr]
   set filter1 [$name cget -filter1]
   set filter2 [$name cget -filter2]
   set pointing [$name cget -pointing]
   set guiding [$name cget -guiding]
   set guideOffset [$name cget -guideOffset]
   set instrOffset [$name cget -instrOffset]
   set resetao [$name cget -resetao]
   set disableao [$name cget -disableao]
   set ltcscheck [$name cget -ltcscheck]
   if { [calparam cget -site] eq "CP" } {
      set ignoreao [$name cget -ignoreao]
   }
   set restoreM1 [$name cget -restoreFigure]
}

itcl::body SlewOptionsControl::save {name} {
   $name configure \
         -chopThrow $chopThrow -sourceOffset $sourceOffset \
         -sourceDifTr $sourceDifTr -mountOffset $mountOffset \
         -mountDifTr $mountDifTr -filter1 $filter1 \
         -filter2 $filter2 -pointing $pointing \
         -guiding $guiding -guideOffset $guideOffset \
         -instrOffset $instrOffset -resetao $resetao \
         -disableao $disableao -ltcscheck $ltcscheck \
         -restoreFigure $restoreM1
   if { [calparam cget -site] eq "CP" } {
       $name configure -ignoreao $ignoreao
   }
}
