#+
#  SlewOptions <- Paramset
#
#  Implements the SlewOptions class. A SlewOptions object stores all the 
#  flags of the Slew CAD command plus options for reseting and disabling
#  the active-optics configuration.
#
#  Options:
#          All the following options specify whether the corresponding
#          element in the TCS configuration should be reset.
#
#          -chopThrow        Chop throw.
#
#          -sourceOffset     Source offsets.
#
#          -sourceDifTr      Source differential tracking.
#
#          -mountOffset      Mount offsets
#
#          -mountDifTr       Mount differential tracking.
#
#          -filter1          Filter 1.
#
#          -filter2          Filter 2.
#
#          -pointing         Local pointing offsets.
#
#          -guiding          Guiding.
#
#          -guideOffset      Guide star offsets.
#
#          -instrOffset      Instrument (aka pointin origin) offsets.
#
#          -resetao          Reset the ao configuration
#
#          -disableao        Disable the ao configuration
#
#          -ltcscheck        Check for a Collision when using LGS
#
#  Methods:
#           apply comp Applies the slew options to the TCS by setting 
#                      the values of the command parameters.
#
#           init       Returns the slew options object to its initial state.
#
#           preview    Does nothing. The method exist so that all components
#                      have a preview method.
#
#           save node  Saves all the slew option values to the xml node.
#
#  D Terrett 21 January 2004
#
#  Copyright CCLRC
#+

itcl::class SlewOptions {
   inherit Paramset
   public {
      method apply {comp}
      method init {}
      method preview {view}
      method save {node}
      variable chopThrow {}
      variable sourceOffset {}
      variable sourceDifTr {}
      variable mountOffset {}
      variable mountDifTr {}
      variable filter1 {}
      variable filter2 {}
      variable pointing {}
      variable guiding {}
      variable guideOffset {}
      variable instrOffset {}
      variable parkPwfs1 {}
      variable parkPwfs2 {}
      variable parkOiwfs {}
      variable parkGeMS {}
      variable followPwfs1 {}
      variable followPwfs2 {}
      variable followOiwfs {}
      variable followGeMS {}
      variable resetao 0
      variable disableao 0
      variable ltcscheck 0
      variable ignoreao 0 { set ::Flags(ignoreao) $ignoreao }
      variable restoreFigure 0
   }
}

itcl::body SlewOptions::apply {comp} {

   cs slew set chopThrow [list $chopThrow]
   cs slew set sourceOffset [list $sourceOffset]
   cs slew set sourceDifTr [list $sourceDifTr]
   cs slew set mountOffset [list $mountOffset]
   cs slew set mountDifTr [list $mountDifTr]
   cs slew set filter1 [list $filter1]
   cs slew set filter2 [list $filter2]
   cs slew set pointing [list $pointing]
   cs slew set guiding [list $guiding]
   cs slew set guideOffset [list $guideOffset]
   cs slew set instrOffset [list $instrOffset]
   cs slew set parkPwfs1 [list $parkPwfs1]
   cs slew set parkPwfs2 [list $parkPwfs2]
   cs slew set parkOiwfs [list $parkOiwfs]
   cs slew set parkGeMS [list $parkGeMS]
   cs slew set followPwfs1 [list $followPwfs1]
   cs slew set followPwfs2 [list $followPwfs2]
   cs slew set followOiwfs [list $followOiwfs]
   cs slew set followGeMS [list $followGeMS]
   logger command slew

# Clearing the instrument offsets through the slew command confuses the 
# seqexec because it looks at the outputs of the offsetPoA1 CAD so we
# set this offset explicitly as well.
   if { $instrOffset } {
      cs offsetPoA1 set x 0.0
      cs offsetPoA1 set y 0.0
      logger command offsetPoA1
   }

# Similarly for the target filter.
   if { $filter1 } {
      cs filter1 set shortCircuit Closed
   }
}

itcl::body SlewOptions::init {} {
   set chopThrow {}
   set sourceOffset {}
   set sourceDifTr {}
   set mountOffset {}
   set mountDifTr {}
   set filter1 {}
   set filter2 {}
   set pointing {}
   set guiding {}
   set guideOffset {}
   set instrOffset {}
   set parkPwfs1 {}
   set parkPwfs2 {}
   set parkOiwfs {}
   set parkGeMS {}
   set followPwfs1 {}
   set followPwfs2 {}
   set followOiwfs {}
   set followGeMS {}
   set resetao 0
   set disableao 0
   set ltcscheck 0
   set ignoreao 0
   set restoreFigure 0
}

itcl::body SlewOptions::preview {view} {}

itcl::body SlewOptions::save {node} {
   set node [paramset $node slew_options]
   param $node chopThrow $chopThrow
   param $node sourceOffset $sourceOffset
   param $node sourceDifTr $sourceDifTr
   param $node mountOffset $mountOffset
   param $node mountDifTr $mountDifTr
   param $node filter1 $filter1
   param $node filter2 $filter2
   param $node pointing $pointing
   param $node guiding $guiding
   param $node guideOffset $guideOffset
   param $node instrOffset $instrOffset
   param $node parkPwfs1 $parkPwfs1
   param $node parkPwfs2 $parkPwfs2
   param $node parkOiwfs $parkOiwfs
   param $node parkGeMS $parkGeMS
   param $node followPwfs1 $followPwfs1
   param $node followPwfs2 $followPwfs2
   param $node followOiwfs $followOiwfs
   param $node followGeMS $followGeMS
   param $node resetao $resetao
   param $node disableao $disableao
   param $node ltcscheck $ltcscheck
   param $node ignoreao $ignoreao
   param $node restoreFigure $restoreFigure
}
