#+
#  TccToolbar <- itk::Widget
#
#  Implements the TccToolbar widget which is packed into . to make the
#  root window of the Gemini tcc.
#
#  Options:
#           none
#
#  Methods:
#           none
#
#  D Terrett 17 Janaury 2004
#
#  Copyright CCLRC
#-

itcl::class TccToolbar {
   inherit itk::Widget
   constructor args {}
}

itk::usual TccToolbar {
}

itcl::body TccToolbar::constructor args {

  itk_component add menubar {
      iwidgets::menubar $itk_interior.menubar -menubuttons {
         menubutton file -text File -menu {
            command layout -label "Save layout..." -command saveLayout
	     command exit -label Exit -command {
		 logactions destructor
		 exit
	     }
         }
      }
   } {}
   pack $itk_component(menubar) -fill x -expand y

# Create a border.
   itk_component add border {
      frame $itk_interior.border
   }
   pack $itk_component(border) -fill both -expand y -padx 6 -pady 6

# Divide the window into a frame at the top for the main buttons and
# a frame for the subsystem controls with a spacing frame in between.
   set w $itk_component(border)
   itk_component add main {
      frame $w.main
   }
   itk_component add space {
      frame $w.space -height 8
   }
   itk_component add subsys {
      frame $w.subsys -bd 2 -relief sunken
   }
   pack $itk_component(main) $itk_component(space) $itk_component(subsys)

# Pack the main control buttons into the top frame.
   set w $itk_component(main)
   itk_component add tc {
      PanelButton $w.tc -text "System Control" -panel tcsPanel
   }
   itk_component add config {
      PanelButton $w.config -text "Target Selection" \
            -panel tcsConfigPanel
   }
   itk_component add handsets {
      PanelButton $w.handsets -text Handsets -panel handsetPanel
   }
   itk_component add observe {
      PanelButton $w.observe -text "Acquisition & Guiding" \
            -panel observePanel
   }
   itk_component add log {
      PanelButton $w.log -text "Command Log" -panel logPanel
   }
   itk_component add catalogs {
      PanelButton $w.catalogs -text Catalogs -panel skyPanel
   }
	global ::env
	if { [string compare [exec uname] "Solaris"] == 0 } {
	   itk_component add eng {
	      button $w.eng -text "Engineering Screen" -command \
				"exec [file join [calparam cget -tcs_root_dir] data $::env(TCC_TCSNAME)_dm.sh] &"
	   }
	} else {
		itk_component add eng {
			button $w.eng -text "Engineering Screen" -command \
				"exec $::env(TCC_TCSNAME)_dm.sh &"
		}
	}
   if { [info exists ::env(TCC_TCSNAME)] } {
      switch $::env(TCC_TCSNAME) {
         tc1 -
			tcs {}
         default {
            $itk_component(eng) configure -state disabled
         }
      }
   }
   pack $itk_component(tc) $itk_component(config) $itk_component(handsets) \
         $itk_component(observe) $itk_component(log) $itk_component(catalogs) \
         $itk_component(eng) -fill x -expand y

# Label the subsystems frame.
   set w $itk_component(subsys)
   itk_component add sslabel {
      label $w.sslabel -text "Subsystem Controls"
   }
   pack $itk_component(sslabel)

# Divide the rest of the window into 2 rows
   itk_component add row1 {
      frame $w.row1
   }
   itk_component add row2 {
      frame $w.row2
   }

   pack $itk_component(row1) $itk_component(row2) \
         -fill x -expand y

# M1 and Adaptive Optics  buttons in the first row.
   set w $itk_component(row1)
   itk_component add m1 {
      PanelButton $w.m1 -text "M1" -panel m1sPanel
   }
   itk_component add ao {
      PanelButton $w.ao -text "Adaptive Optics" -panel aosPanel
   }

   pack $itk_component(m1) $itk_component(ao)\
         -side left -expand y -fill x

# Mount & Rotator in the last row.
   set w $itk_component(row2)
   itk_component add mc {
      PanelButton $w.mc -text "Mount and Rotator" -panel mcsPanel
   }

   pack $itk_component(mc) -side left -expand y -fill x

   eval itk_initialize $args
}
