#+
#  TcsConfigComponent <- TcsConfig, Component
#
#  A TcsConfigComponent object is a TcsConfig object that is stored in a 
#  configuration list.
#
#
#  Options:
#           none
#
#  Methods:
#           constructor list  Creates the TcsConfig object and puts it onto
#                           "list".
#
#           save file       Writes commands to re-create the object to the
#                           channel identifier "file" and then calls the
#                           TcsConfig save method to add the objects data.
#
#  D Terrett 19 September 2001
#
#  Copyright CCLRC
#+

itcl::class TcsConfigComponent {
   inherit Component TcsConfig
   constructor {list args} {
      Component::constructor $list
   } {
      eval configure $args
   }
}
