#+
#  TrackFrameComponent <- TrackFrame, Component
#
#  A TrackFrameComponent object is a TrackFrame object that is stored in a 
#  configuration list.
#
#
#  Options:
#           none
#
#  Methods:
#           constructor list  Creates the TrackFrame object and puts it onto
#                           "list".
#
#  D Terrett 19 September 2001
#
#  Copyright CCLRC
#+

itcl::class TrackFrameComponent {
   inherit Component TrackFrame
   constructor {list args} {
      Component::constructor $list
   } {
      eval configure $args
   }
}
