#+
#  TrackFramePanel <- Panel
#
#  Implements the TrackratePanel widget. A Panel widget with a 
#  TrackFrameControl widget packed into its interior.
#
#  D Terrett 6 March 2002
#
#  Copyright CCLRC
#+

itcl::class TrackFramePanel {
   inherit Panel
   constructor args {}
   public {
      method sync {component name} {$itk_component(control) sync $name}
   }
}

itk::usual TrackFramePanel {
   keep -background -cursor
}

itcl::body TrackFramePanel::constructor args {

   setWidgetColors $itk_interior \
         $itk_option(-background) $itk_option(-foreground)

   itk_component add control {
      TrackFrameControl $itk_interior.control
   } {
      usual
      rename -component -components components Components
   }

   pack $itk_component(control) -fill both -expand y

   eval itk_initialize $args
}
