#+
#  TrackRatePanel <- Panel
#
#  Implements the TrackratePanel widget. A Panel widget with a 
#  TrackRateControl widget packed into its interior.
#
#  Methods:
#           none
#
#  D Terrett 6 February 2002
#
#  Copyright CCLRC
#+

itcl::class TrackRatePanel {
   inherit Panel
   constructor args {}
   public {
      method sync {component name} {$itk_component(control) sync $name}
   }
}

itk::usual TrackRatePanel {
   keep -background -cursor
}

itcl::body TrackRatePanel::constructor args {

   setWidgetColors $itk_interior \
         $itk_option(-background) $itk_option(-foreground)

   itk_component add control {
      TrackRateControl $itk_interior.control
   } {
      usual
      rename -component -components components Components
   }

   pack $itk_component(control) -fill both -expand y

   eval itk_initialize $args
}
