#+
#  WavelengthControl <- ComponentControl
#
#  Implements the WavelengthControl widget. A ComponentControl widget with
#  an entryfield widget for the wavelength.
#
#  D Terrett 7 January 2002
#
#  Copyright CCLRC
#+

itcl::class WavelengthControl {
   inherit ComponentControl
   constructor args {}
   itk_option define -obsWavel obsWavel ObsWavel 0
   private {
      variable prevwl 0
      variable prevcentral
      variable prevdeploy
   }
   public {
      variable locked 0
      variable locked_name ""
      method set_lock {}
      method load {name}
      method reset {}
      method save {name}
   }
}

itk::usual WavelengthControl {
   keep -borderwidth -cursor -font -highlightthickness -insertborderwidth\
         -insertofftime -insertontime -insertwidth -labelfont -popupcursor \
         -selectborderwidth -textfont -title
}

itcl::body WavelengthControl::constructor args {
   itk_component add wframe {
      frame $itk_interior.wframe -bd 2 -relief ridge
   }
   pack $itk_component(wframe)
   set w $itk_component(wframe)

   # Lock the wavelength
   itk_component add wllock {
	   checkbutton $w.lock -variable [itcl::scope locked] -onvalue 1 -offvalue 0 -text "Lock Current WL: " -command "$this set_lock"
   }
    
   # Entryfield for the wavelength.
   itk_component add wavel {
      iwidgets::entryfield $w.wavel \
           -labeltext [lindex [cs wavelSourceA info wavel] 2]  -width 8
   }
   pack $itk_component(wavel) -padx 4 -pady 4

   itk_component add central {
      iwidgets::optionmenu $w.central -labeltext "Periscope"
   }
   $itk_component(central) insert end "" open closed
       
   # Deployable baffle
   itk_component add deploy {
      iwidgets::optionmenu $w.deploy -labeltext "M2 Deployable baffle"
   }
   $itk_component(deploy) insert end "" "thermal IR" "near IR" visible \
      extended
   
   # Set the object description.
   set description wavelength

   eval itk_initialize $args
}

itcl::body WavelengthControl::save {name} {

   if {[$itk_component(wavel) get] != $prevwl } {set prevwl "-1"}
   if {$itk_option(-obsWavel)} {
       $name configure -wavel [$itk_component(wavel) get] \
	   -centralBaffle [$itk_component(central) get] \
	   -deployableBaffle [$itk_component(deploy) get]
   } else {
       $name configure -wavel [$itk_component(wavel) get]
   }
}

itcl::body WavelengthControl::reset {} {

   if {$prevwl >= 0 } { set prevwl [$itk_component(wavel) get]}
   #set prevwl [$itk_component(wavel) get]
   if {$itk_option(-obsWavel)} {
       set prevcentral [$itk_component(central) get]
       set prevdeploy [$itk_component(deploy) get]
       $itk_component(central) select ""
       $itk_component(deploy) select ""
   }
   $itk_component(wavel) clear
}

itcl::body WavelengthControl::set_lock {} {
    if {$locked} {
	set locked_name  ${::Config(tcs.field.wavelength,value)}
    } else {
	set locked_name ""
    }
}

itcl::body WavelengthControl::load {name} {
   if {$itk_option(-obsWavel)} {
      if {$locked} {
         set ::Config(tcs.field.wavelength,value) $locked_name
         set name ::WavelengthNames::$locked_name
         $itk_component(selector) select $locked_name
      }
   }
   set wavelen [$name cget -wavel]
   if {$itk_option(-obsWavel)} {
      $itk_component(central) select [$name getCentralBaffle]
      $itk_component(deploy) select [$name getDeployableBaffle]
	   set prevwl $wavelen
   } else {
	   $itk_component(central) select $prevcentral
	   $itk_component(deploy) select $prevdeploy
   }

   $itk_component(wavel) insert end $wavelen
}

itcl::configbody WavelengthControl::obsWavel {
   if { $itk_option(-obsWavel) } {
      pack $itk_component(wllock) -padx 4 -pady 4
      pack $itk_component(central) -anchor e -padx 3 -pady 3
      pack $itk_component(deploy) -anchor e -padx 3 -pady 3
   } else {
      pack forget $itk_component(wllock)
      pack forget $itk_component(central)
      pack forget $itk_component(deploy)
   }
}
