#+
#  Wavelength <- Paramset
#
#  Implements the Wavelength class. A Wavelength object stores an effective
#  wavelength.
#
#  Options:
#          -wavel      The wavelength.
#
#          -centralBaffle     The position of the M2 central baffle ("open"
#                             "closed" or "").
#
#          -deployableBaffle  The position of the M2 deployable baffle
#                             ("thermal IR", "near IR", "visible",
#                             "extended" or "").
#
#  Methods:
#          apply comp  Applies the wavelength to the TCS by setting the
#                      values of the command parameters for the virtual
#                      telescope.
#
#          init          Returns the wavelength object to its initial state.
#
#          preview comp  Sets the preview wavelength for the virtual
#                        telescope".
#
#          save node   Writes the values of the options to the xml node.
#
#  D Terrett 21 February 2003
#
#  Copyright CCLRC
#+

itcl::class Wavelength {
   inherit Paramset
   public {
      method apply {comp}
      method init {}
      method preview {view comp}
      method save {node}
      variable wavel {} {set wavel [valWavelength $wavel]}
      variable set_baffles 1
      variable centralBaffle ""
      variable deployableBaffle ""
      
      method getCentralBaffle {}
      method getDeployableBaffle {}
   }
   private method getBaffles {}
}

itcl::body Wavelength::apply {comp} {
   switch $comp {
      tcs.field.wavelength {
         set fieldObj ${::Config(tcs.field,namespace)}::${::Config(tcs.field,value)}
         set name [namespace tail $this]
         if {[string match "*Acq Cam*" $name]} {
            set loc_set_baffles 0
         } else {
            set loc_set_baffles $set_baffles
         }
         set loc_centralBaffle [getCentralBaffle]
         set loc_deployableBaffle [getDeployableBaffle]

	      cs wavelSourceA set wavel $wavel
         logger command wavelSourceA
         if { ! [string is space $loc_centralBaffle] && $loc_set_baffles} {
            switch $loc_centralBaffle {
               closed {cs m2Baffle set centralBaffle Closed}
               open {cs m2Baffle set centralBaffle Open}
            }
         }
         if { ! [string is space $loc_deployableBaffle] && $loc_set_baffles} {
            switch $loc_deployableBaffle {
               "thermal IR" {cs m2Baffle set deployBaffle Retracted}
               "near IR" {cs m2Baffle set deployBaffle [list "Near IR"]}
               visible {cs m2Baffle set deployBaffle Visible}
               extended {cs m2Baffle set deployBaffle Extended}
            }
         }
         if { !( [string is space $loc_centralBaffle] && \
               [string is space $loc_deployableBaffle] ) && $loc_set_baffles} {
            logger command m2Baffle
         }
      }
      tcs.field.guide.oiwfswavelength {
         cs wavelOiwfs set wavel $wavel
         logger command wavelOiwfs
      }
      tcs.field.guide.aowfswavelength {
         cs wavelPwfs2 set wavel $wavel
      	logger command wavelPwfs2
      }
   }
}

itcl::body Wavelength::init {} {
   set wavel {}
   set centralBaffle ""
   set deployableBaffle ""
}

itcl::body Wavelength::preview {view comp} {
   if { ! [string equal $wavel ""] } {
      switch $comp {
         science {
            $view configure -wavel $wavel
         }
			p1wfs {
				$view configure -p1Wavel $wavel
			}
			p2wfs -
			aowfs {
				$view configure -p2Wavel $wavel
			}
         oiwfs {
            $view configure -oiWavel $wavel
         }
			ttgs {
				$view configure -ttgs1Wavel $wavel
				$view configure -ttgs2Wavel $wavel
				$view configure -ttgs3Wavel $wavel
			}
			odgw {
				$view configure -odgw1Wavel $wavel
				$view configure -odgw2Wavel $wavel
				$view configure -odgw3Wavel $wavel
				$view configure -odgw4Wavel $wavel
			}
      }
   }
}

itcl::body Wavelength::save {node} {
   set node [paramset $node wavelength]
   param $node wavel $wavel
   param $node centralBaffle $centralBaffle
   param $node deployableBaffle $deployableBaffle
}

itcl::body Wavelength::getBaffles {} {
   set name [namespace tail $this]
   if {[string match "*Acq Cam*" $name]} {
      set loc_set_baffles 0
   } else {
      set loc_set_baffles $set_baffles
   }
   
   set loc_centralBaffle $centralBaffle
   set loc_deployableBaffle $deployableBaffle

   set inst $::Config(tcs.instrument,value)
   foreach instname { GMOS NICI NIRI GPI GNIRS GSAOI NIFS F2 } {
      if { [ string match "*$instname*" $inst] } {
         set inst $instname
         break
      }
   }
   if { $loc_centralBaffle == "" && [calparam centralBaffleOverride $inst] ne "<undefined>" && $loc_set_baffles } {
      set loc_centralBaffle [calparam centralBaffleOverride $inst]
   }
   if { $loc_deployableBaffle == "" && [calparam deployableBaffleOverride $inst] ne "<undefined>" && $loc_set_baffles } {
      set loc_deployableBaffle [calparam deployableBaffleOverride $inst]
   }

   if {($loc_centralBaffle == ""  || $loc_deployableBaffle == "") && $loc_set_baffles } {
      if {$wavel <= [calparam cget -baffle_visible]} {
         set loc_centralBaffle closed
         set loc_deployableBaffle visible
      } elseif {$wavel < [calparam cget -baffle_nearir]} {
         set loc_centralBaffle open
         set loc_deployableBaffle "near IR"
      } else {
         set loc_centralBaffle open
         set loc_deployableBaffle "thermal IR"
      }
   }
   # for GS Engineering: Override baffles to retracted and closed when inst is HR
   if { $inst == "HRWFS"} {
      set loc_set_baffles 1
      set loc_centralBaffle closed
      set loc_deployableBaffle "thermal IR"
   }
   
   return [list $loc_centralBaffle $loc_deployableBaffle]
}

itcl::body Wavelength::getCentralBaffle {} {
   return [ lindex [ getBaffles ] 0 ]
}

itcl::body Wavelength::getDeployableBaffle {} {
   return [ lindex [ getBaffles ] 1 ]
}