#+
#  WavelengthComponent <- Wavelength, Component
#
#  A WavelengthComponent object is a Wavelength object that is stored in a 
#  configuration list.
#
#
#  Options:
#           none
#
#  Methods:
#           constructor list  Creates the Wavelength object and puts it onto
#                           "list".
#
#  D Terrett 19 September 2001
#
#  Copyright CCLRC
#+

itcl::class WavelengthComponent {
   inherit Component Wavelength
   constructor {list args} {
      Component::constructor $list
   } {
      eval configure $args
   }
}
