#+
#  WfsConfig <- itk::Widget
#
# allows configuration of WFS filter and fieldstop
#
# A.W.Ebbers Nov 2006
#-

itcl::class WfsConfig {
   inherit itk::Widget
   constructor {args} {}
   destructor {}
   public {
      method load {name}
      method reset {}
      method save {name}
      method getValue {comp}
      method niciState {state}
   }
   private {
       method pageSelectCB {color}
       method filter {wfs}
       method fldstop {wfs}
       method ndsel {}
       method aoflenssel {}
       method aondsel {}
       method aottgsiris {}
       method startNICInd {}
       method setmanNICInd {}
       method checkNICIAOLoop {}
       method checkNICI_SFPos {}
       method colsel {}
       method window {}
		method buildPageFrame {tabbook wfs label}
		method buildOiwfsPage {parent}
		method buildAowfsPage {parent}
		method buildGemsPage {parent}
		method buildHrwfsPage {parent}
		method buildPwfsPage {wfs parent}
		method configureODGWFilter {}
		method onODGWChange {changeList}
      method configureODGW {}
      method onODGWSizeChange {changeList}
      
      variable odgwDisplay YES
	}
}

itk::usual WfsConfig {
   keep -borderwidth -cursor -font -highlightthickness -insertborderwidth \
         -insertofftime -insertontime -insertwidth -labelfont -popupcursor \
         -selectborderwidth -textfont
}

itcl::body WfsConfig::constructor {args} {

   set w $itk_interior

   itk_component add tabbook {
      iwidgets::tabnotebook $w.tabs -tabpos n -width 430 -height 190 -equaltabs true
   } {
      ignore -background -tabbackground
   }

   pack $itk_component(tabbook)

	buildHrwfsPage [buildPageFrame $itk_component(tabbook) hrwfs HRWFS/AC]
	buildPwfsPage pwfs1 [buildPageFrame $itk_component(tabbook) pwfs1 PWFS1]
	buildPwfsPage pwfs2 [buildPageFrame $itk_component(tabbook) pwfs2 PWFS2]
	buildOiwfsPage [buildPageFrame $itk_component(tabbook) oiwfs OIWFS]
	if {[calparam cget -site] eq "CP"} {
		buildGemsPage [buildPageFrame $itk_component(tabbook) gems GSAOI]
	} else {
		buildAowfsPage [buildPageFrame $itk_component(tabbook) aowfs AOWFS]
	}

   $itk_component(tabbook) select HRWFS/AC

   eval itk_initialize $args
}

itcl::body WfsConfig::destructor {} {
}

itcl::body WfsConfig::filter {wfs} {
	if {[$itk_component(${wfs}filter) get] != ""} {
		if {$wfs == "aowfs"} {
		    pwfs filter pwfs2 [$itk_component(${wfs}filter) get]
		} else {
		    pwfs filter $wfs [$itk_component(${wfs}filter) get]
		}
		$itk_component(${wfs}wavel) clear
		$itk_component(${wfs}wavel) insert end [pwfs getWl [$itk_component(${wfs}filter) get]]
	}
}

itcl::body WfsConfig::fldstop {wfs} {
	pwfs fldstop $wfs [$itk_component(${wfs}fldstop) get]
}

itcl::body WfsConfig::aottgsiris {} {
#puts "WfsConfig::aottgsiris sending [$itk_component(aoiris) get]"
# Select GAOS ND TTGS iris open close
   if { ![catch {cs aoTTGSiris info}] } {
       cs aoTTGSiris set pos [$itk_component(aoiris) get]
       cs aoTTGSiris set mode 1
       cs aoTTGSiris set dir 3
   }
}

itcl::body WfsConfig::aondsel {} {
    #puts "WfsConfig::aondsel sending [$itk_component(aond) get]"
# Select GAOS ND filter IN/OUT
	if {[$itk_component(aond) get] == ""} {return}
	if {[AO state useLwfs]} {
		#puts "WfsConfig::aondsel setting ndfilter to $ndFilter"
		if { ![catch {cs aolgsNDFilter info}] } {
				logactions logmess "WfsConfig::aondsel moving ND Filter to [$itk_component(aond) get]"
				cs aolgsNDFilter set pos [$itk_component(aond) get]
				cs aolgsNDFilter set mode 1
				cs aolgsNDFilter set dir 3
				logactions logmess "WfsConfig::aondsel moving LGS ND Filter to [$itk_component(aond) get]"
		}
	} else {
		#puts "WfsConfig::aondsel setting ndfilter to $ndFilter"
		if { ![catch {cs aongsNDFilter info}] } {
	   	logactions logmess "WfsConfig::aondsel moving ND Filter to [$itk_component(aond) get]"
			cs aongsNDFilter set pos [$itk_component(aond) get]
			cs aongsNDFilter set mode 1
			cs aongsNDFilter set dir 3
			logactions logmess "WfsConfig::aondsel moving NGS ND Filter to [$itk_component(aond) get]"
		}
	}
	if { [calparam cget -site] eq "MK" && $::Config(tcs.gaos,value) != "" } {
		$::Config(tcs.gaos,namespace)::$::Config(tcs.gaos,value) configure -ndFilter [$itk_component(aond) get]
	}
}

itcl::body WfsConfig::aoflenssel {} {
#puts "WfsConfig::aoflenssel sending [$itk_component(aoflens) get]"
# Select GAOS Field Lens IN/OUT
   if { ![catch {cs aoFLens info}] } {
   	set demand [$itk_component(aoflens) get]
   	logactions logmess "WfsConfig::aoflenssel moving Field Lens to $demand"
   	switch $demand {
      IN {
         cs aoFLens set pos FLENS
         cs aoFLens set flens 1
      }
      OUT {
         cs aoFLens set pos PARK
         cs aoFLens set flens 0
      }
   	}
      if { [calparam cget -site] eq "MK" && $::Config(tcs.gaos,value) != "" } {
   	   $::Config(tcs.gaos,namespace)::$::Config(tcs.gaos,value) configure -fldLens [$itk_component(aoflens) get]
   	}
   }
# Apply preparing the CM
   if { [catch {cs tcsApply post} msg] } {
      tk_messageBox -icon error -message \
                                    "Error posting GAOS commands: TCS reports \
                                    \"$msg\""
      return
   }
}

itcl::body WfsConfig::checkNICIAOLoop {} {
    if { [AO state oiaoLoop] } {
	tk_messageBox -icon warning -type ok -title "Warning" -message \
	"Can not move ND filter wheel while AO loop is closed.\nPlease open the AO loop and try again."
	return 0
    } else {
	return 1
    }
}

itcl::body WfsConfig::checkNICI_SFPos {} {
    set port [sa agssad get portNici]
    set sfParked [sa agssad get sfParked]
# Check if SF is in a NICI valid position, or if NICI is installed in bottom port that SF is parked
    if { ([string match -nocase "*nici*" [sa agssad get sfName] ]) || (( $port == 1) && ($sfParked)) } {
	return 1
    } else {
	tk_messageBox -icon warning -type ok -title "Warning" -message \
	"Can not move ND filter wheel while Science Fold is not in a NICI position.\nPlease move the Science Fold and try again."
	return 0
    }
}

itcl::body WfsConfig::startNICInd {} {
    if { [checkNICIAOLoop] == 0 } { return }
    if { [checkNICI_SFPos] == 0 } { return }

# Trigger AUTO NICI ND Configuration ... after making sure ...
   if { ![catch {cs niciMag info}] } {
       set choice [tk_messageBox -icon question -type yesno -default no -title "NICI ND Filter Config" -message \
		       "About to begin NICI Automatic ND Filter configuration.  This will begin with the Requested Filter.\nAre you sure?"]
       
       if {$choice == "yes"} {
	   logactions logmess "WfsConfig::startNICInd Starting NICI Automatic ND Filter Configuration"
	   cs niciMag set mode Auto
	   cs niciMag set conf config
	   cs niciMag set dir 0
	   after 100
	   cs niciMag set dir 3	
	   cs niciMag set conf moving
	   cs niciMag set dir 0
	   cs niciMag set dir 3
       }
   }
}

itcl::body WfsConfig::setmanNICInd {} {
    if { [checkNICIAOLoop] == 0 } { return }

    set reqPos [$itk_component(niciNDManualFlt) get]
    if { ![string match -nocase block $reqPos] } {
	if { [checkNICI_SFPos] == 0 } { return }
    }

# Sets NICI ND Filter ... after making sure ...
    if { ![catch {cs niciMag info}] } {
	set choice [tk_messageBox -icon question -type yesno -default no -title "NICI ND Filter Config" -message \
			"About to set NICI ND Filter.\nAre you sure?"]
	
	if {$choice == "yes"} {
	    set reqPos [$itk_component(niciNDManualFlt) get]
	    logactions logmess "WfsConfig::setmanNICInd Setting NICI ND Filter position manually to $reqPos"
	    cs niciMag set mode Manual
	    cs niciMag set manPos $reqPos
	    cs niciMag set conf config
	    cs niciMag set dir 0
	    after 100
	    cs niciMag set dir 3	
	    #	cs niciMag set conf moving
	    #	cs niciMag set dir 0
	    #	cs niciMag set dir 3
	}
    }
}

itcl::body WfsConfig::ndsel {} {
# Select hrwfs neutral desity filter.
   hrwfs ndsel [$itk_component(nd) get]
}

itcl::body WfsConfig::colsel {} {
# Select hrwfs colout filter.
   hrwfs colsel [$itk_component(col) get]
}

itcl::body WfsConfig::window {} {
# Set window size.
   hrwfs window [$itk_component(window) get]
}

itcl::body WfsConfig::getValue {comp} {
    #puts "WfsConfig::getValue, comp: $comp"
    switch $comp {
	HrwfsColFilt {
	    set value [$itk_component(currColFilt) getValue]
	    #if {$value == "No Value"} {
	    #   set value [$itk_component(col) get]
	    #}
	}
    }
    #puts "got value $value"
    return $value
}

itcl::body WfsConfig::pageSelectCB {color} {

# Re-configure the notebook background to match the selected page.
   $itk_component(tabbook) config -background $color -tabbackground $color \
         -backdrop $color

# Restore the colours of the tabs.
   $itk_component(tabbook) pageconfigure HRWFS/AC -background \
         [option get $itk_component(hrwfs) background Background] 
   $itk_component(tabbook) pageconfigure PWFS1 -background \
         [option get $itk_component(pwfs1) background Background] 
   $itk_component(tabbook) pageconfigure PWFS2 -background \
         [option get $itk_component(pwfs2) background Background] 
   $itk_component(tabbook) pageconfigure OIWFS -background \
         [option get $itk_component(oiwfs) background Background]
	if {[calparam cget -site] eq "CP"} {
		$itk_component(tabbook) pageconfigure GSAOI -background \
			[option get $itk_component(gems) background Background]
	} else {
   	$itk_component(tabbook) pageconfigure AOWFS -background \
			[option get $itk_component(aowfs) background Background]
	}
}

itcl::body WfsConfig::niciState {state} {
	if {[calparam cget -site] eq "CP"} {
	    $itk_component(niciLabel) configure -state $state
	    $itk_component(nicindcurrMag) configure -state $state
	    $itk_component(nicindreqFlt) configure -state $state
	    $itk_component(nicindcurrFlt) configure -state $state
	    $itk_component(niciAutoBut) configure -state $state
	    $itk_component(nicindcar) configure -state $state
	    $itk_component(niciNDManualFlt) configure -state $state
	    $itk_component(niciManFltApply) configure -state $state
	}
}

itcl::body WfsConfig::buildOiwfsPage {parent} {
	# A subcomponent selector for the OIWFS.
	itk_component add oiwfsfilter {
		 WavelengthSelector $parent.oiwfsfilter -labeltext "filter" \
		-labelpos w -component tcs.field.guide.oiwfswavelength
	} {
		 usual
		 ignore -background
	}
	pack $itk_component(oiwfsfilter) -anchor w -padx 3 -pady 3

 # ND Filter for the NICI OI/AO system
	if {[calparam cget -site] eq "CP" } {
		itk_component add niciFrame {
			frame $parent.nicifr
		} {
			ignore -background
		}
		itk_component add niciLabel {
			label $parent.nicifr.lab -text "NICI" 
		} {
			 ignore -background
		}
		itk_component add nicindcurrMag {
			 MonitorLabel $parent.nicifr.niciNdMag nici ndMag -width 6 -anchor w -text "Req Mag:"
		}  {
			 ignore -background
		}
		itk_component add nicindreqFlt {
			 MonitorLabel $parent.nicifr.niciNdReq nici ndReq -width 8 -anchor w  -text "Req ND Flt:"
		}  {
			 ignore -background
		}
		itk_component add nicindcurrFlt {
			 MonitorLabel $parent.nicifr.niciNdFlt nici ndfilt2 -width 8 -anchor w  -text "Cur ND Flt:"
		}  {
			 ignore -background
		}
		itk_component add niciManFltFrame {
			 frame $parent.nicimanfr
		} {
			 ignore -background
		}
		itk_component add niciNDManualFlt {
			 iwidgets::optionmenu $parent.nicimanfr.niciNdFltSel -labeltext "ND filter" -labelpos w -width 90
		} {
			 ignore -background
		}
		$itk_component(niciNDManualFlt) insert end Block ND5 ND3 ND2 ND1 Open
		itk_component add niciManFltApply {
			button $parent.nicimanfr.nicimanflapply -text "Apply ND Filter" -command [itcl::code $this setmanNICInd]
		} {
			ignore -background
		}
		itk_component add niciFrame2 {
			frame $parent.nicifr2
		} {
			ignore -background
		}
		itk_component add niciAutoBut {
			button $parent.nicifr2.nicibut -text "Start AUTO ND Config" -command [itcl::code $this startNICInd]
		} {
			 ignore -background
		}
		itk_component add nicindcar {
			 MonitorLabel $parent.nicifr2.nicicar nici ndCAR -width 10 -anchor w -text "CAR:"
		}  {
			 ignore -background
		}
		pack $itk_component(niciLabel) -side top
			  pack $itk_component(nicindcurrMag) $itk_component(nicindreqFlt) $itk_component(nicindcurrFlt) -side left -padx 2
			  pack $itk_component(niciNDManualFlt) $itk_component(niciManFltApply) -side left
		pack $itk_component(niciAutoBut) $itk_component(nicindcar) -side left -padx 2
		pack $itk_component(niciFrame) $itk_component(niciManFltFrame) $itk_component(niciFrame2) -side top -padx 3 -pady 3
	}
}

itcl::body WfsConfig::buildAowfsPage {parent} {
	# A subcomponent selector for the AOWFS.
	itk_component add aowfsfilter {
		 WavelengthSelector $parent.aowfsfilter -labeltext "filter" \
		-labelpos w -component tcs.field.guide.aowfswavelength
	} {
		 usual
		 ignore -background
	}
#	   pack $itk_component(aowfsfilter) -anchor w -padx 3 -pady 3

	itk_component add aond {
		 iwidgets::optionmenu $parent.nd -labeltext "ND filt" -labelpos w -width 100 \
		-command [itcl::code $this aondsel]
	} {
		 ignore -background
	}
	$itk_component(aond) insert end IN OUT ""
	#puts "aond optionmenu: $itk_component(aond)"

	itk_component add currAONDFilt {
		 MonitorLabel $parent.currNDFilt aossad ndFiltPos -width 12 -anchor e -font "Arial 12 bold"
	} {
		 ignore -background
	}

	itk_component add aoflens {
		 iwidgets::optionmenu $parent.flens -labeltext "Field Lens" -labelpos w -width 100 \
		-command [itcl::code $this aoflenssel]
	} {
		 ignore -background
	}
	$itk_component(aoflens) insert end IN OUT ""
	#puts "aoflens optionmenu: $itk_component(aoflens)"
	
	itk_component add currflens {
		 MonitorLabel $parent.currflens aossad flensPos -width 12 -anchor e -font "Arial 12 bold" -trans "* OUT {} unknown FLENS IN"
	} {
		 ignore -background
	}

	itk_component add aoiris {
		 iwidgets::optionmenu $parent.iris -labeltext "TTGS iris" -labelpos w -width 100 \
		-command [itcl::code $this aottgsiris]
	} {
		 ignore -background
	}
	$itk_component(aoiris) insert end open close ""

	itk_component add currTTGSiris {
		 MonitorLabel $parent.currTTGSiris aossad ttgsIrisPos -width 12 -anchor e -font "Arial 12 bold"
	} {
		 ignore -background
	}

	grid $itk_component(aowfsfilter) - -sticky nes -pady 1
	grid $itk_component(aond) $itk_component(currAONDFilt) -sticky nes
	grid $itk_component(aoflens) $itk_component(currflens) -sticky nes
	grid $itk_component(aoiris) $itk_component(currTTGSiris) -sticky nes
	grid configure $itk_component(currAONDFilt) $itk_component(currflens) $itk_component(currTTGSiris) -sticky nws	
}

itcl::body WfsConfig::buildHrwfsPage {parent} {
	itk_component add nd {
		 iwidgets::optionmenu $parent.nd -labeltext "ND filt" -labelpos w -width 100 \
		-command [itcl::code $this ndsel]
	} {
		 ignore -background
	}

	if {[calparam cget -site] eq "CP"} {
	    $itk_component(nd) insert end open ND3 ND2 ND1
        } else {
	    $itk_component(nd) insert end open nd100 nd1000 filt04 filt06 filt08
        }

	
	itk_component add col {
		 iwidgets::optionmenu $parent.col -labeltext "Col filt" -labelpos w \
		-width 100 -command [itcl::code $this colsel]
	} {
		 ignore -background
	}
	
	$itk_component(col) insert end neutral  U-red1 B-blue V-green R-red2 \
		 I-red3
	itk_component add currNDFilt {
		 MonitorLabel $parent.currNDFilt hrwfs::currStatus ndfilt -width 12 -anchor e -font "Arial 12 bold"
	} {
		 ignore -background
	}
	
	itk_component add currColFilt {
		 MonitorLabel $parent.currColFilt hrwfs::currStatus colfilt -width 12 -anchor e -font "Arial 12 bold"
	} {
		 ignore -background
	}
	itk_component add window {
		 iwidgets::optionmenu $parent.window -labeltext Window -labelpos w -width 100 \
		-command [itcl::code $this window]
	} {
		 ignore -background
	}
	$itk_component(window) insert end full 200x200 100x100 
	
	grid $itk_component(nd) $itk_component(currNDFilt) -sticky nes -pady 2
	grid $itk_component(col) $itk_component(currColFilt) -sticky nes -pady 2
	grid $itk_component(window) x -sticky nes -pady 3
}

itcl::body WfsConfig::buildPwfsPage {wfs parent} {
	# An option menus and an entry field for the PWFSs.
	itk_component add ${wfs}filter {
		iwidgets::optionmenu $parent.${wfs}filter -labeltext "filter" -labelpos w -width 100 \
			-command [itcl::code $this filter $wfs]
	} {
		 ignore -background
	}
	itk_component add ${wfs}currFlt {
		 MonitorLabel $parent.currFlt agssad ${wfs}Filter -width 10 -anchor w -font "Arial 12 bold"
	}  {
		 ignore -background
	}
	
	$itk_component(${wfs}filter) insert end neutral Blue Green Red Red04 \
				Red1 ""

	itk_component add ${wfs}wavel {
		 iwidgets::entryfield $parent.${wfs}wavel -labeltext "wavelength" -width 6
	}  {
		 ignore -background
	}
	
	itk_component add ${wfs}fldstop {
		 iwidgets::optionmenu $parent.${wfs}fldstop -labeltext "fieldstop" -labelpos w -width 100 \
		-command [itcl::code $this fldstop $wfs]
	}  {
		 ignore -background
	}
	
	itk_component add ${wfs}currFld {
		 MonitorLabel $parent.currFld agssad ${wfs}Fldstop -width 10 -anchor w -font "Arial 12 bold"
	}  {
		 ignore -background
	}
	
	$itk_component(${wfs}fldstop) insert end prism 10.0 6.4 3.2 1.6 open1 open2 open3 open4 ""
	
	grid $itk_component(${wfs}filter) $itk_component(${wfs}currFlt) $itk_component(${wfs}wavel) -sticky e -pady 2
	grid $itk_component(${wfs}fldstop) $itk_component(${wfs}currFld) -sticky nes -pady 2
}

itcl::body WfsConfig::buildGemsPage {parent} {
	itk_component add odgwframe { iwidgets::labeledframe $parent.odgwframe \
		-labeltext "GSAOI Filter" -labelpos nw } {ignore -background}
	set w [$itk_component(odgwframe) childsite]
	# An option menus for the ODGW filter.
	itk_component add odgwsetframe {
		frame $w.odgwsetframe
	}  {ignore -background}
	itk_component add odgwfilter {
		iwidgets::optionmenu $w.odgwsetframe.odgwfilter
	} {
		 ignore -background
	}
	itk_component add odgwFilterApply {
		button $w.odgwsetframe.odgwfilterapply -text "Apply Filter" -command [itcl::code $this configureODGWFilter]
	} {
		ignore -background
	}
	itk_component add odgwlab1 {label $w.labb1 -text "current:"} { 
		ignore -background }
	itk_component add odgwCurrFlt { label $w.currFlt -width 15 -relief sunken } { 
		ignore -background }
	itk_component add odgwlab2 {label $w.labb2 -text "wavelength (um):" } {
		ignore -background}
	itk_component add odgwCurrWavel { label $w.currWavel -width 10 -relief sunken 
		} { ignore -background }
			
	set odgw [Odgw::getSingleton]
   $itk_component(odgwfilter) insert end Blocked
	foreach name [$odgw getFilterList] {
		$itk_component(odgwfilter) insert end $name
	}
   
   itk_component add odgwsizeframe { iwidgets::labeledframe $parent.odgwsizeframe \
         -labeltext "ODGW" -labelpos nw } {ignore -background}
    set w [$itk_component(odgwsizeframe) childsite]
   itk_component add odgwsizesel {
      iwidgets::optionmenu $w.odgwsizesel
   } {
      ignore -background
   }
   $itk_component(odgwsizesel) insert end 2 4 6 8 10 12 16 24 32 64 128
   itk_component add odgwSizeApply {
      button $w.odgwsizeapply -text "Apply Size" -command [itcl::code $this configureODGW]
   } {
      ignore -background
   }
   itk_component add odgwCurrSize { label $w.currsize -width 5 -relief sunken } { 
      ignore -background }
#   itk_component add odgwDisplay { checkbutton $w.odgwdisplay -text Display -onvalue YES -offvalue NO -variable [itcl::scope odgwDisplay]} { 
#         ignore -background }
	pack $itk_component(odgwfilter) $itk_component(odgwFilterApply) -side left -anchor w -pady 2 
	pack $itk_component(odgwsetframe) -side top -anchor w -pady 0
	pack $itk_component(odgwlab1) $itk_component(odgwCurrFlt) \
		$itk_component(odgwlab2) $itk_component(odgwCurrWavel) -side left \
		-pady 1 -padx 2
   
   pack $itk_component(odgwsizesel) $itk_component(odgwCurrSize) $itk_component(odgwSizeApply) -side left -anchor w -pady 2
   pack configure $itk_component(odgwSizeApply) -padx 5
#   pack $itk_component(odgwsizesel) $itk_component(odgwCurrSize) $itk_component(odgwDisplay) $itk_component(odgwSizeApply) -side left -anchor w -pady 2
#   pack configure $itk_component(odgwDisplay) -padx 5
   
	pack $itk_component(odgwframe) $itk_component(odgwsizeframe) -side top -pady 0 -expand yes -fill x

	[Odgw::getSingleton] subscribe [itcl::code $this onODGWChange]
   [GemsSys::getSingleton] subscribe [itcl::code $this onODGWSizeChange]
   onODGWSizeChange odgwSize
}

itcl::body WfsConfig::buildPageFrame {tabbook wfs label} {
	set w  [$tabbook add -label $label]

# Set colours from the options database
	set bg [option get $w background Background] 
	set fg [option get $w foreground Foreground] 
	setWidgetColors $w $bg $fg

# Configure page to set background when selected.
	$tabbook pageconfigure $label -background $bg \
		-foreground $fg -command [itcl::code $this pageSelectCB $bg]

	itk_component add $wfs {
		frame $w.$wfs -bd 2
	} {
		ignore -background
	}
	pack $itk_component($wfs)
	
	return $itk_component($wfs)
}

itcl::body WfsConfig::configureODGWFilter {} {
	set filter [$itk_component(odgwfilter) get]
   
   #HACK to change the Wavelength for the current field
   set gsaoi [Gsaoi::getSingleton]
   if { [string toupper $filter] ne "BLOCKED" } {
      set wavel [$gsaoi getFilterWavelength $filter]
      set sciWavel ""
      for {set i 1} { $i < [$::Config(tcs.field.wavelength,list) length] } {incr i} {
         set fullname $::Config(tcs.field.wavelength,namespace)::[$::Config(tcs.field.wavelength,list) get $i]
         set w [$fullname cget -wavel]
         if { $wavel == $w } {
            set sciWavel [$::Config(tcs.field.wavelength,list) get $i]
            break
         }
      }
      if { $sciWavel eq "" } {
         set sciWavel [format "%.3f" $wavel]
         WavelengthComponent $::Config(tcs.field.wavelength,namespace)::$sciWavel $::Config(tcs.field.wavelength,list)
         $::Config(tcs.field.wavelength,namespace)::$sciWavel configure -wavel $wavel
      }
      set fieldName $::Config(tcs.field,namespace)::$::Config(tcs.field,value)
      if { [llength [itcl::find objects $fieldName]] > 0 } {
         $fieldName configure -wavelength $sciWavel
      }
      set ::Config(tcs.field.wavelength,value) $sciWavel   
   }

	if {![string is space $filter]} {
		[Odgw::getSingleton] configureFilter $filter
	}
}

itcl::body WfsConfig::onODGWChange {changeList} {
	foreach el $changeList {
		switch $el {
			filter {
				set filter [[Odgw::getSingleton] getCurrentFilter]
				$itk_component(odgwCurrFlt) configure -text $filter
				$itk_component(odgwCurrWavel) configure -text [[Odgw::getSingleton] getFilterWavelength $filter]
			}
		}
	}
}

itcl::body WfsConfig::configureODGW {} {
   set gems [GemsSys::getSingleton]
   set size [$itk_component(odgwsizesel) get]
   if {![string is space $size]} {
      $gems setODGWSize $size
   }
   
#   $gems setODGWDisplay $odgwDisplay
}

itcl::body WfsConfig::onODGWSizeChange {changeList} {
   foreach el $changeList {
      switch $el {
         odgwSize {
            set size [[GemsSys::getSingleton] getODGWSize]
            $itk_component(odgwCurrSize) configure -text $size         }
      }
   }
}
