#+
#  WfsTargetControl <- TargetControl
#
#  A WfsTarget control is a TargetControl widget for entering a wave front
#  sensor target.
#
#  D Terrett 27 February 2002
#
#  Copyright CCLRC
#+

itcl::class WfsTargetControl {
   inherit TargetControl
   constructor args {}
}

itk::usual WfsTargetControl {
   keep -borderwidth -cursor -font -highlightthickness -insertborderwidth \
         -insertofftime -insertontime -insertwidth -labelfont -popupcursor \
         -selectborderwidth -textfont -title
}

itcl::body WfsTargetControl::constructor args {

# Define the object description
   set description "WFS target"

   eval itk_initialize $args
}
