#+
#  WfsWidget <- itk::Widget
#
#  Widget to specify parameters for a generic WFS.
##  Options:
#           none
#
#  Methods:
#           none
#
#  J. Luhrs 15 February 2010
#
#+

itcl::class WfsWidget {
	inherit itk::Widget
	
public {
	itk_option define -label label Label "" { 
		$itk_component(onoff) configure -text $itk_option(-label)
	}
	itk_option define -explabel expLabel ExpLabel "Sec/Hz" {
		$itk_component(exp) configure -labeltext $itk_option(-explabel) }
	itk_option define -expvalues expValues ExpValues \
		[list 1.0 0.5 0.1 0.05 0.02 0.01 0.005] {
			$itk_component(exp) clear list
			eval $itk_component(exp) insert list end $itk_option(-expvalues) }
	itk_option define -status status Status off {
		if {$itk_option(-status) eq "off"} {
			$itk_component(mainframe) configure -background $itk_option(-offbackground)
		} else {
			$itk_component(mainframe) configure -background $itk_option(-onbackground)
		}
	}
	itk_option define -onswitchpress onSwitchPress OnSwitchPress {} {
		$itk_component(onoff) configure -command $itk_option(-onswitchpress) }
	itk_option define -onexpselect onExpSelect OnExpSelect {} {
			$itk_component(exp) configure -selectioncommand $itk_option(-onexpselect) }
	itk_option define -state state State normal {
		$itk_component(onoff) configure -state $itk_option(-state)
		$itk_component(exp) configure -state $itk_option(-state)
	}
	itk_option define -onbackground onBackground OnBackground green
	itk_option define -offbackground offBackground OffBackground white
	itk_option define -relief relief Relief solid {
		$itk_component(mainframe) configure -relief $itk_option(-relief)
	}
   itk_option define -orientation orientation Orientation vert {
      changeOrientation $itk_option(-orientation)
   }  
	
	method clear {} { 
		$itk_component(onoff) clear 
		#$itk_component(exp) clear entry 
	}
	method switchPush {} { $itk_component(onoff) push }  
	method switchPop {} { $itk_component(onoff) pop }  
	method switchGet {} { return [$itk_component(onoff) get] }
	method setExp { val }
	method getExp {} { return [$itk_component(exp) get ] }
	method getButton {} { return $itk_component(onoff) }
	method getExpCombo {} { return $itk_component(exp) }
								
	constructor {args} {}
   
   private {
      variable old_orientation vert
      method changeOrientation { new_orientation }
   }
}
}

itk::usual WfsWidget {
	keep -background -cursor -foreground -highlightcolor \
		-highlightthickness
}

itcl::body WfsWidget::constructor {args} {
	itk_component add mainframe {
		frame $itk_interior.mainframe -relief solid -borderwidth 1 -background white 
	} { usual
		ignore -background }
	itk_component add frame {
		frame $itk_interior.mainframe.frame
	}
	
	set w $itk_component(frame) 
	itk_component add onoff {
		ToggleButton $w.onoff -pushedbackground Green -width 5 -pady 0
	} { ignore -width -pady -padx}
	itk_component add exp {
		iwidgets::combobox $itk_interior.mainframe.exp -arrowrelief flat -width 5
	}
	[$itk_component(exp) component list] configure -hscrollmode none -vscrollmode none
	
	pack $itk_component(mainframe) -expand yes -fill both
	pack $itk_component(onoff) -pady 1 -padx 1
	pack $itk_component(frame) -side top -anchor n -pady 1 -padx 1 
	pack $itk_component(exp) -side top -anchor s -pady 1 -padx 1

	eval itk_initialize $args
}

itcl::body WfsWidget::setExp { val } {
   $itk_component(exp) clear entry
   $itk_component(exp) insert entry end $val
}

itcl::body WfsWidget::changeOrientation { new_orientation } {
   if { $new_orientation == $old_orientation } {
      return
   }
   pack forget $itk_component(onoff) $itk_component(frame) $itk_component(exp)
   if { $new_orientation eq "vert" } {
      $itk_component(exp) configure -labelpos nw
      pack $itk_component(onoff) -side top -pady 1 -padx 1
      pack $itk_component(exp) -side top -anchor s -pady 1 -padx 1
      pack $itk_component(frame) -side top -anchor n -pady 1 -padx 1 
   } else {
      $itk_component(exp) configure -labelpos w
      pack $itk_component(onoff) -side top -pady 1 -padx 1
      pack $itk_component(frame) -side left -anchor n -pady 1 -padx 1 -expand yes 
      pack $itk_component(exp) -side left -anchor s -pady 1 -padx 1
   }
}