#+
#  Haku.itcl
#
#  Implements the Haku class. A Haku object mimics a seq::PrincipleSystem
#  object but connects to QUIRC/Hokupaa with sockets instead of using
#  EPICS.
#
#  Parameters:
#
#     address     The network address of Haku.
#
#     socket      The socket number of the QUIRC/Hokupaa server.`
#
#  Methods:
#
#     post action
#
#        posts an action
#
#     cancel action
#
#        cancels an action
#
#  D Terrett 8 September 2000
#
#  Copyright CCLRC
#+

itcl::class Haku {
   constructor {address port} {}
   destructor {}
   public {
      method post {action}
      method cancel {action}
   }
   private {
      method monitor {}
      method timeout {}
      variable CurrentAction ""
      variable Channel
   }
}

itcl::body Haku::constructor {address port} {

# Open a socket to talk to Haku.
   set Channel [socket $address $port]

# Monitor the socket.
   fileevent $Channel readable [itcl::code $this monitor]
}

itcl::body Haku::destructor {} {

# Remove the monitor.
   filevent $Channel readable ""

# Close the socket.
   close $Channel
}


itcl::body Haku::post {action} {

# Sent the actions command string to the server.
   puts $Channel [$action cget -command]
   flush $Channel

# If the action expects a reply.
   if { ![string is space [$action cget -reply]] } {

# Record the current action.
      set CurrentAction $action

# Start the timeout handler
      if { ![string is space [$action cget -ontimeout]] } {
         after [expr { [$action cget -timeout] * 1000 }] \
               [itcl::code $this timeout]
      }
   }
}

itcl::body Haku::monitor {} {

# Cancel the timeout.
  after cancel [itcl::code $this timeout]

# Read the incoming message.
  set message [gets $Channel]
  if { [eof $Channel] } {
     fileevent $Channel readable ""
     tk_messageBox -type ok -parent . -icon error -message \
          "Socket was closed by server"
     return
  }

# Assume no script to invoke.
  set command ""

# If there is an action in progress then compare the message with the reply
# that the current action expects.
  if { ![string is space $CurrentAction] } {
     set reply [$CurrentAction cget -reply]

# If the message is the expected reply then invoke the -onok script of the
# action.
     if { [string equal $reply $message] } {
        set command [$CurrentAction cget -onok]
     } else {

# Otherwise report that the message wasn't what was expected.
        tk_messageBox -type ok -parent . -icon error -message \
              "Haku replied with \"$message\" when expecting \"$reply\""
     }
  } else {

# Report that the message was unexpected.
     tk_messageBox -type ok -parent . -icon error -message \
           "Unexpected message \"$message\" received from Haku"
  }


# Invoke the script.
  if { ![string is space $command] } {
     uplevel #0 $command
  }
}

itcl::body Haku::timeout {} {

   if { ![string is space $CurrentAction] } {
      set command [$CurrentAction cget -ontimeout]
      if { ![string is space $command] } {
         uplevel #0 $command
      }
   }
}

itcl::body Haku::cancel {action} {
  if { [string is space $action] || [string equal $action $CurrentAction] } {
     after cancel [itcl::code $this timeout]
  }
}
