#+
#  NiriStep.itcl
#
#  Implements the NiriStep class. A NiriStep behaves in the same way as a
#  Step object but also communicates NIRI to start an exposure.
#
#  D Terrett 9 May 2001
#
#  History
#		D Terrett  9 May 2001: original version
#		M Bec     14 May 2001: timeout is estimated from numCoAdds and intTime
#
#  Copyright CCLRC
#+

itcl::class NiriStep {
   inherit Step
   constructor {args} {}
   destructor {}
   protected {
      method nextaction {after}
      method error {msg} {Step::error $msg}
   }
   private {
      method exposedone
      common Exposing
	  common numCoAdds
	  common intTime
	  common minInt
      variable ExposeAction
   }
}

itcl::body NiriStep::constructor {args} {

# Create the actions for controlling Niri.
   set ExposeAction [namespace current]::[seq::Action #auto niri]
   $ExposeAction configure -onok [itcl::code $this nextaction expose] \
         -onerror [itcl::code $this error] \
         -ontimeout [itcl::code $this error "timed out"] \
         -oktest [itcl::code $this exposedone] \
         -waitvar [scope Exposing(value)]
   $ExposeAction set niriObserve dummy start

# Replace the onok option of the GuideOnAction to call this 
# class's implementation of nextaction.
   $GuideOnAction configure -onok [itcl::code $this nextaction offset]

   eval configure $args
}

itcl::body NiriStep::destructor {} {
   itcl::delete object $ExposeAction
}

itcl::body NiriStep::nextaction {after} {

   switch $after {
      offset {
         set ProgressMessage "Waiting for NIRI exposure to finish"
         update
         sa niri link observe [scope Exposing]
         sa niriTiming link numCoAdds [scope numCoAdds]
         sa niriTiming link intTime [scope intTime]
         sa niriTiming link minInt [scope minInt]
         
		 cs niriObserve set datalab value [format "%03d" $ListIndex]
         # configure the timeout to :
		 # 30+2.5*intTime*numCoAdds
		 # this seems 'too much' but is based on the timeout
		 #  used by the gmos controller itself ...
		 if [ catch {
		 	# probably could use the common var...
			set _intTime [sa niriTiming get intTime]
			set _numCoAdds [sa niriTiming get numCoAdds]
		 	set _minInt [sa niriTiming get minInt]
			
			set to [expr 30 + 2.5 * ( $_intTime + $_minInt) * $_numCoAdds]
		 	# integer value (ceil ?)
			set to [lindex [split $to .] 0]
			$ExposeAction configure -timeout $to
			# puts stdout "set timeout $to"
			} msg ] {
				puts stdout "Failed to estimate timeout value .. using default (60s)"
				bell;bell;bell;
				}
		 $ExposeAction start
      }
      default {
         Step::nextaction $after
      }
   }
}

itcl::body NiriStep::exposedone {} {
   set val [sa niri get observe]
   return [string equal IDLE $val]
}
