#+
#  PattEdit <- itk::Widget
#
#  A widget for editing patterns
#
#  D Terrett 4 October 2000
#
#  Copyright CCLRC
#+

itcl::class PattEdit {
   inherit itk::Widget
   constructor {args} {}
   public {
      method get {pattern} {return $Patterns($pattern)}
      method clear {}
      method pset {pattern def}
      method select {pattern}
   }
   private {
      method new {}
      method remall {}
      method remove {}
      method selpatt {}
      method move {dir}
      method generate {}
      variable Patterns
   }
}

itk::usual PattEdit {
   keep -background -cursor -foreground -font
   keep -activebackground -activeforeground -disabledforeground
   keep -highlightcolor -highlightthickness
}

itcl::body PattEdit::constructor {args} {

# Initialize the patterns array.
   foreach l {A B C D E F G H I J K L M N O P Q R S T U V W X Y Z} {
      set Patterns($l) ""
   }

   itk_component add frame {
      frame $itk_interior.frame -borderwidth 2 -relief ridge
   }
   set w $itk_component(frame)

   itk_component add pattern {
      iwidgets::optionmenu $w.pattern -labeltext Pattern \
            -command [code $this selpatt]
   }
   $itk_component(pattern) insert end \
      A B C D E F G H I J K L M N O P Q R S T U V W X Y Z

   itk_component add -private p {
      iwidgets::entryfield $w.p -labeltext p -width 8 -validate real
   }
   itk_component add -private q {
      iwidgets::entryfield $w.q -labeltext q -width 8 -validate real
   }
   itk_component add -private new {
      button $w.new -text New -command [code $this new]
   }
   itk_component add -private remall {
      button $w.remall -text "Rm. All" -command [code $this remall]
   }
   itk_component add -private rem {
      button $w.rem -text Remove -command [code $this remove]
   }

   itk_component add -private list {
      iwidgets::scrolledlistbox $w.list -hscrollmode none
   }

   global ROOT
   itk_component add -private top {
      button $w.top -bitmap @$ROOT/seqlib/top.xbm \
            -command [code $this move top]
   }
   itk_component add -private up {
      button $w.up -bitmap @$ROOT/seqlib/up.xbm \
            -command [code $this move up]
   }
   itk_component add -private down {
      button $w.down -bitmap @$ROOT/seqlib/down.xbm \
            -command [code $this move down]
   }
   itk_component add -private bottom {
      button $w.bottom -bitmap @$ROOT/seqlib/bottom.xbm \
            -command [code $this move bottom]
   }

   itk_component add gen {
      PattGen $w.gen
   }
   [$itk_component(gen) component create] configure \
         -command [code $this generate]

   grid  $itk_component(pattern) - -sticky w
   grid $itk_component(p) $itk_component(list) $itk_component(top)
   grid $itk_component(q) x $itk_component(up)
   grid $itk_component(new)
   grid $itk_component(remall) x $itk_component(down)
   grid $itk_component(rem) x $itk_component(bottom)
   grid $itk_component(gen) - - -padx 10 -pady 10
   grid configure $itk_component(list) -rowspan 5
   grid configure $itk_component(new) $itk_component(remall) \
         $itk_component(rem) -sticky ew -padx 5
   grid configure $itk_component(top) $itk_component(up) $itk_component(down) \
         $itk_component(bottom) -pady 5
   pack $itk_component(frame)

   eval itk_initialize $args
}

itcl::body PattEdit::new {} {
   set p [$itk_component(p) get]
   if { [string is space $p] } {set p 0.0}
   set q [$itk_component(q) get]
   if { [string is space $q] } {set q 0.0}
   set point [format "%6.2f %6.2f" $p $q]

   $itk_component(list) insert end $point
   lappend Patterns([$itk_component(pattern) get]) $point
}

itcl::body PattEdit::remall {} {
   $itk_component(list) clear
   set Patterns([$itk_component(pattern) get]) ""
}

itcl::body PattEdit::remove {} {
   set index [$itk_component(list) curselection]
   if { [string length $index] } {
      $itk_component(list) delete $index
      set p [$itk_component(pattern) get]
      set Patterns($p) [lreplace $Patterns($p) $index $index]
   }
}

itcl::body PattEdit::selpatt {} {
   $itk_component(list) clear
   foreach p $Patterns([$itk_component(pattern) get]) {
      $itk_component(list) insert end $p
   }
}

itcl::body PattEdit::move {dir} {

   set cur [$itk_component(list) curselection]
   if { [string length $cur] } {
      set listbox [$itk_component(list) component listbox]
      set point [$itk_component(list) get $cur]
      $listbox delete $cur
      set p [$itk_component(pattern) get]
      set Patterns($p) [lreplace $Patterns($p) $cur $cur]

      switch $dir {
         top {
            set cur 0
         }
         up {
            if { $cur > 0 } {incr cur -1}
         }
         down {
            if { $cur < [$listbox size] } {incr cur 1}
         }
         bottom {
            set cur end
         }
      }
      $listbox insert $cur $point
      $listbox selection set $cur
      $listbox see $cur
      set Patterns($p) [linsert $Patterns($p) $cur $point]
   }
}

itcl::body PattEdit::generate {} {
   foreach point [$itk_component(gen) generate] {
      foreach {p q} $point {}
      set point [format "%6.2f %6.2f" $p $q]
      $itk_component(list) insert end $point
      lappend Patterns([$itk_component(pattern) get]) $point
   }
}

itcl::body PattEdit::clear {} {
   foreach el [array names Patterns] {
      set Patterns($el) ""
   }
}

itcl::body PattEdit::pset {pattern def} {
   set Patterns($pattern) $def
}

itcl::body PattEdit::select {pattern} {
   $itk_component(list) clear
   foreach p $Patterns([$itk_component(pattern) get]) {
      $itk_component(list) insert end $p
   }
   $itk_component(pattern) select $pattern
}

