#+
#  Sequence.itcl
#
#  A Sequence object is a linked chain of Steps. When it is created the 
#  offsets for the steps are read from a file.
#
#  D Terrett 7 October 2000
#
#  Copyright CCLRC
#+

itcl::class Sequence {

   constructor {{steptype Step} chanid {canvas ""} {list ""}} {}
   destructor {}
   public {
      variable First {}
      variable Title {}
   }
   private {
      method pattern {p args}
      method patdef {p args} {set PattDefs($p) $args}
      variable Patterns
      variable PattDefs
      variable List ""
   }
}

itcl::body Sequence::constructor {{steptype Step} chanid {canvas ""} {list ""}} {

   set prev ""
   set pmax 0.0
   set pmin 0.0
   set qmax 0.0
   set qmin 0.0

   while { ![eof $chanid] } {
      if { [gets $chanid line] > 0 } {

# Lines starting with a # are comments. The first comment line is stored
# for use as a window title.
         if { [string equal [string index $line 0] "#"] } {
            if { ![string is space $Title] } {
               set Title [string range $line 1 end]
            }
         } else {

# Decode the line.
            eval $line
         }
      }
   }

# Expand the sequence into steps.
   if { [info exists Patterns] } {
      foreach pat $Patterns {
         if { ![info exists PattDefs($pat)] } {
            error "Pattern $pat not defined"
         }
         foreach s $PattDefs($pat) {
   
# Create a new step.
            foreach {p q} $s {}
            set cur [$steptype #auto -To "$p $q" -Canvas $canvas -List $list]

# Configure the previous step to link to the current one.
            if { [string length $prev] } {
               $prev configure -Next [namespace current]::$cur
            } else {
               set First [namespace current]::$cur
            }
            set prev $cur

# Update the range variable.
            if { $p < $pmin } {set pmin $p}
            if { $p > $pmax } {set pmax $p}
            if { $q < $qmin } {set qmin $q}
            if { $q > $qmax } {set qmax $q}
         }
      }

# Add the marker size to the limits.
      if { ![string is space $canvas] } {
         set pmin [expr { $pmin - 3.0 }]
         set pmax [expr { $pmax + 3.0 }]
         set pmax [expr { $pmax > - $pmin ? $pmax : - $pmin }]
         set qmin [expr { $qmin - 3.0 }]
         set qmax [expr { $qmax + 3.0 }]
         set qmax [expr { $qmax > - $qmin ? $qmax : - $qmin }]

# Scale and shift the step markers on the canvas.
         set w [$canvas cget -width]
         set h [$canvas cget -height]
         set pf [expr { ( $w - 50) / ( 2.0 * $pmax ) }]
         set qf [expr { ( $h - 50) / ( 2.0 * $qmax ) }]
         set f [expr { $pf < $qf ? $pf : $qf }]
         $canvas scale steps 0.0 0.0 $f $f
         $canvas move steps [expr { $w / 2.0 }] [expr { $h / 2.0 }]
      }

# Save the name of the list box.
      set List $list

   } else {
      error "No sequence defined in file"
   }
}

itcl::body Sequence::destructor {} {
   set next $First
   while { [string length $next] } {
      set tmp [$next cget -Next]
      itcl::delete object $next
      set next $tmp
   }
   if { ![string is space $List] } {
      $List delete 0 end
   }
}

itcl::body Sequence::pattern {p args} {
   if { [llength $args] } {
      switch [lindex $args 0] {
         repeated {
            for { set i 0 } { $i < [lindex $args 1] } { incr i } {
               lappend Patterns $p
            }
         }
      }
   } else {
      lappend Patterns $p
   }
}
