#+
# Step.itcl
#
# D Terrett 24 May 2001
#
# Copyright CLRC
#+

itcl::class Step {
   constructor {args} {}
   destructor {}
   public proc platescale {value} {set PlateScale $value}
   public proc maxguidestep {value} {set MaxGuideStep $value}
   public proc maxguideoffset {value} {set MaxGuideOffset $value}
   public proc wfs {value} {set WFS [string tolower $value]}
   public proc start {{step ""}}
   public proc stop
   public proc pause {} {set Paused 1}
   public proc step
   public {
      common Paused 0
      common ProgressMessage "Idle"
      common CurrentStep ""
      common NextStep ""
      common CurrentP
      common CurrentQ
      common PlateScale 1.0
      common MaxGuideStep 1.5
      common MaxGuideOffset 40.0
      common WFS p2
      variable Next {}
      variable MoveAction
      variable Canvas {}
      variable List {}
      variable To 
      variable X 0.0
      variable Y 0.0
      variable GuideOnAction
      variable GuideOffAction
      variable Expose 1
   }
   protected {
      method nextaction {after}
      method error {message}
      variable ListIndex
   }
   private {
      method begin
      method next
      method finish
      method isinposition
      common InPosition
      variable EnableGuide
      variable DisableGuide
   }
}

itcl::body Step::constructor {args} {

# Create an action object to handle offsetting the telescope.
   set MoveAction [namespace current]::[seq::Action #auto tcs]
   $MoveAction configure -onok [itcl::code $this nextaction move] \
         -onerror [itcl::code $this error] \
         -ontimeout [itcl::code $this error "timed out"] \
         -oktest [code $this isinposition] \
         -waitvar [scope InPosition(value)]

# Create actions for enabling and disabling guiding.
   set GuideOnAction [namespace current]::[seq::Action #auto tcs]
   $GuideOnAction configure -onok [itcl::code $this nextaction offset] \
         -onerror [itcl::code $this error] \
         -ontimeout [itcl::code $this error "timed out"]
   $GuideOnAction set mountGuide mode on
   $GuideOnAction set m2Guide state on
   $GuideOnAction set ${WFS}Follow followState on

   set GuideOffAction [namespace current]::[seq::Action #auto tcs]
   $GuideOffAction configure -onok "$MoveAction start" \
         -onerror [itcl::code $this error] \
         -ontimeout [itcl::code $this error "timed out"]
   $GuideOffAction set mountGuide mode off
   $GuideOffAction set m2Guide state off

   eval configure $args
}

itcl::body Step::destructor {} {
   itcl::delete object $MoveAction
   if { ![string is space $Canvas] } {
      $Canvas delete $this
   }
}

itcl::body Step::begin {} {

   sa tcssad link inPosition [scope InPosition]

# Check the net offset against the maximum distance from the base to guide
# on.
   if { ($X * $X + $Y * $Y) > ($MaxGuideOffset * $MaxGuideOffset) } {
      set DisableGuide 1
      set EnableGuide 0
   } else {

# Check the distance of the move against the maximum step without disabling
# guiding.
      set dx [expr {[sa tcssad get xoffsetPoA1 value] - $X}]
      set dy [expr {[sa tcssad get yoffsetPoA1 value] - $Y}]

      if { ($dx * $dx + $dy * $dy) > ($MaxGuideStep * $MaxGuideStep) } {
         set DisableGuide 1
         set EnableGuide 1
      } else {
         set DisableGuide 0
         set EnableGuide 1
      }
   }

# Configure the Guide Off action to disable or enable follow as appropriate.
   if { $EnableGuide } {
      $GuideOffAction set ${WFS}Follow followState on
   } else {
      $GuideOffAction set ${WFS}Follow followState off
   }

# Set the current step, next step and position.
   set CurrentStep $this
   set NextStep [$this cget -Next]
   foreach {CurrentP CurrentQ} $To {}

   set ProgressMessage "Moving telescope..."
   if { ![string is space $Canvas] } {
      $Canvas itemconfigure $this -fill yellow
      $Canvas raise $this
   }
   if { ![string is space $List] } {
      $List highlight $ListIndex
   }
   nextaction start
}

itcl::body Step::nextaction {after} {

   switch $after {
      start {
         set ProgressMessage "Moving telescope"
         update
         if { $DisableGuide } {
            $GuideOffAction start
         } else {
            $MoveAction start
         } 
      }
      move {
         if { $EnableGuide } {
            $GuideOnAction start
         } else {
            nextaction offset
         }
      }
      offset {
         if { $Expose } {
            set ProgressMessage "Waiting for operator intervention"
            update
            if { ![string is space $Canvas] } {
               $Canvas itemconfigure $this -fill green
            }
            tk_messageBox -type ok -icon info -parent . \
               -message "Press ok when ready to continue"
         }
         $this finish
      }
      expose {
         $this finish
      }
   }
}

itcl::body Step::error {message} {
   set CurrentStep ""
   set ProgressMessage $message
   update
}

itcl::body Step::finish {} {

   if { ![string is space $Canvas] } {
      $Canvas itemconfigure $this -fill grey
      $Canvas lower $this
   }

# Unset the current action.
   set CurrentStep ""

# If the pause flag is set, set an appropriate message.
   if { $Paused } {
      set ProgressMessage "paused"
      update
   } else {

# If there is next step defined then start it.
      if { [string length $NextStep] } {
         uplevel #0 [itcl::code $NextStep begin]
      } else {

# Otherwise just set the message to show we are idle.
         set ProgressMessage idle
         update
      }
   }
}

itcl::body Step::start {{step ""}} {

# Clear the pause flag.
   set Paused 0

# If no start step has been specified then start the next step (if there)
# is one.
   if { [string equal $step ""] } {
      set step $NextStep
   }

# If there is a step in progress then replace the next step otherwise
# start the new step.
   if { [string equal $CurrentStep ""] } {
      if { ! [string equal $step ""] } {
         $step begin
      }
   } else {
      set NextStep $step
   }
}

itcl::body Step::stop {} {

# Clear the next step.
   set NextStep ""
}

itcl::body Step::step {} {
   if { [string length $NextStep] } {
      sa tcssad link inPosition [[$NextStep cget -MoveAction] cget -waitvar]
      start $NextStep
      set Paused 1
   }
}

itcl::body Step::isinposition {} {
   set val [sa tcssad get inPosition]
   return [string equal $val TRUE]
}

itcl::configbody Step::To {

# Compute the equivalent x and y offsets.
   foreach {p q} $To {}

   set iaa [expr [sa tcssad get instrAA] / 57.2957795131]
   set X [expr { ( $p * cos($iaa) + $q * sin($iaa) ) / $PlateScale }]
   set Y [expr { ( - $p * sin($iaa) + $q * cos($iaa) ) / $PlateScale }]

# Set the action parameters.
   $MoveAction set offsetPoA1 x $X
   $MoveAction set offsetPoB1 x $X
   $MoveAction set offsetPoC1 x $X
   $MoveAction set offsetPoA1 y $Y
   $MoveAction set offsetPoB1 y $Y
   $MoveAction set offsetPoC1 y $Y
}

itcl::configbody Step::Canvas {

# Create the marker on the canvas.
   if { ![string is space $Canvas] } {
      foreach {p q} $To {}
      $Canvas create rectangle [expr {$p - 1}] [expr {-1 - $q}] \
            [expr {$p + 1}] [expr {1 - $q}] -tags "steps $this" -fill black \
            -outline white
      $Canvas lower $this
   }
}

itcl::configbody Step::List {

# Add coordinates to the list box.
   if { ![string is space $List] } {
      foreach {p q} $To {}
      set entry [format {%8.2f %8.2f} $p $q]
      set ListIndex [$List size]
      $List insert end $entry
   }
}
