#+
# Step.itcl
#
# D Terrett 4 October 2000
#
# Copyright CLRC
#+

itcl::class Step {
   constructor {args} {}
   destructor {}

   public variable Next {}
   public variable MoveAction
   public variable Canvas {}
   public variable List {}
   public variable To 
   public variable X 0.0
   public variable Y 0.0
   public variable GuideOnAction
   public variable GuideOffAction
   public variable Expose 1
   public variable MaxGuideStep 2.5

   private variable ListIndex
   private variable ToggleGuide

   protected method nextaction after
   protected method error
   private method begin
   private method next
   private method finish
   private method isinposition

   private common InPosition

   public proc platescale {platescale} {set PlateScale $platescale}
   public proc start {{step ""}}
   public proc stop
   public proc pause {} {set Paused 1}
   public proc step

   public common PlateScale 1.0
   public common Paused 0
   public common ProgressMessage "Idle"
   public common CurrentStep ""
   public common NextStep ""
   public common CurrentP
   public common CurrentQ
}

itcl::body Step::constructor {args} {

# Create an action object to handle offsetting the telescope.
   set MoveAction [namespace current]::[seq::Action #auto tcs]
   $MoveAction configure -onok [itcl::code $this nextaction move] \
         -onerror [itcl::code $this error] \
         -ontimeout [itcl::code $this error "timed out"] \
         -oktest [code $this isinposition] \
         -waitvar [scope InPosition(value)]

# Create actions for enabling and disabling guiding.
   set GuideOnAction [namespace current]::[seq::Action #auto tcs]
   $GuideOnAction configure -onok [itcl::code $this nextaction offset] \
         -onerror [itcl::code $this error] \
         -ontimeout [itcl::code $this error "timed out"]
   $GuideOnAction set mountGuide mode on
   $GuideOnAction set m2Guide state on

   set GuideOffAction [namespace current]::[seq::Action #auto tcs]
   $GuideOffAction configure -onok "$MoveAction start" \
         -onerror [itcl::code $this error] \
         -ontimeout [itcl::code $this error "timed out"]
   $GuideOffAction set mountGuide mode off
   $GuideOffAction set m2Guide state off

   eval configure $args
}

itcl::body Step::destructor {} {
   itcl::delete object $MoveAction
   if { ![string is space $Canvas] } {
      $Canvas delete $this
   }
}

itcl::body Step::begin {} {

   sa tcssad link inPosition [scope InPosition]

# Check the distance of the move against the maximum step without disabling
# guiding.
   set dx [expr {[sa tcssad get xoffsetPoA1 value] - $X}]
   set dy [expr {[sa tcssad get yoffsetPoA1 value] - $Y}]

   set ToggleGuide \
         [expr { ($dx * $dx + $dy * $dy) > ($MaxGuideStep * $MaxGuideStep) }]

# Set the current step, next step and position.
   set CurrentStep $this
   set NextStep [$this cget -Next]
   foreach {CurrentP CurrentQ} $To {}

   set ProgressMessage "Moving telescope..."
   if { ![string is space $Canvas] } {
      $Canvas itemconfigure $this -fill yellow
      $Canvas raise $this
   }
   if { ![string is space $List] } {
      $List highlight $ListIndex
   }
   nextaction start
}

itcl::body Step::nextaction {after} {

   switch $after {
      start {
         set ProgressMessage "Moving telescope"
         update
         if { $ToggleGuide } {
            $GuideOffAction start
         } else {
            $MoveAction start
         } 
      }
      move {
         if { $ToggleGuide } {
            $GuideOnAction start
         } else {
            nextaction offset
         }
      }
      offset {
         if { $Expose } {
            set ProgressMessage "Waiting for operator intervention"
            update
            if { ![string is space $Canvas] } {
               $Canvas itemconfigure $this -fill green
            }
            tk_messageBox -type ok -icon info -parent . \
               -message "Press ok when ready to continue"
         }
         $this finish
      }
      expose {
         $this finish
      }
   }
}

itcl::body Step::error {message} {
   set CurrentStep ""
   set ProgressMessage $message
   update
}

itcl::body Step::finish {} {

   if { ![string is space $Canvas] } {
      $Canvas itemconfigure $this -fill grey
      $Canvas lower $this
   }

# Unset the current action.
   set CurrentStep ""

# If the pause flag is set, set an appropriate message.
   if { $Paused } {
      set ProgressMessage "paused"
      update
   } else {

# If there is next step defined then start it.
      if { [string length $NextStep] } {
         uplevel #0 [itcl::code $NextStep begin]
      } else {

# Otherwise just set the message to show we are idle.
         set ProgressMessage idle
         update
      }
   }
}

itcl::body Step::start {{step ""}} {

# Clear the pause flag.
   set Paused 0

# If no start step has been specified then start the next step (if there)
# is one.
   if { ![string length $step] } {
      set step $NextStep
   }

# If there is a step in progress then replace the next step otherwise
# start the new step.
   if { [string length $CurrentStep] } {
      set NextStep $step
   } else {
      if { [string length $step] } {
         $step begin
      }
   }
}

itcl::body Step::stop {} {

# Clear the next step.
   set NextStep ""
}

itcl::body Step::step {} {
   if { [string length $NextStep] } {
      sa tcssad link inPosition [[$NextStep cget -MoveAction] cget -waitvar]
      start $NextStep
      set Paused 1
   }
}

itcl::body Step::isinposition {} {
   set val [sa tcssad get inPosition]
   return [string equal $val TRUE]
}

itcl::configbody Step::To {

# Compute the equivalent x and y offsets.
   foreach {p q} $To {}

   set iaa [expr [sa tcssad get instrAA] / 57.2957795131]
   set X [expr { ( $p * cos($iaa) + $q * sin($iaa) ) / $PlateScale }]
   set Y [expr { ( - $p * sin($iaa) + $q * cos($iaa) ) / $PlateScale }]

# Set the action parameters.
   $MoveAction set offsetPoA1 x $X
   $MoveAction set offsetPoB1 x $X
   $MoveAction set offsetPoC1 x $X
   $MoveAction set offsetPoA1 y $Y
   $MoveAction set offsetPoB1 y $Y
   $MoveAction set offsetPoC1 y $Y
}

itcl::configbody Step::Canvas {

# Create the marker on the canvas.
   if { ![string is space $Canvas] } {
      foreach {p q} $To {}
      $Canvas create rectangle [expr {$p - 2}] [expr {-2 - $q}] \
            [expr {$p + 2}] [expr {2 - $q}] -tags "steps $this" -fill black \
            -outline white
      $Canvas lower $this
   }
}

itcl::configbody Step::List {

# Add coordinates to the list box.
   if { ![string is space $List] } {
      foreach {p q} $To {}
      set entry [format {%8.2f %8.2f} $p $q]
      set ListIndex [$List size]
      $List insert end $entry
   }
}
