#+
#  ApplyButton <- itk::Widget
#
#  An ApplyButton is a push button that sends a simple epics ocs command and
#  sends a message to the logger.
#
#  Options:
#           -command        The ocs command that the button posts.
#
#           -confirm        A message to display in a confirmation dialog box
#                           before posting the command. If blank, no 
#                           confirmation dialog is displayed
#
#           -logger         The logger object to log commands to.
#
#           -parcommand     A command executed to obtain the value of each 
#                           parameter.
#
#           -text           The label for the button. Defaults to the 
#                           description string of the command sender specified
#                           by the -command option.
#
#           -system         The name of the system that is being commanded.
#
#  Methods:
#           none
#
#  Notes:
#        o  If -parcommand option is not set, each parameter of the ocs
#           command is set the value "mark" in order to mark the CAD record.
#
#        o  If the epics command sender doesn't exist it is created.
#
#  D Terrett 19 July 2001
#
#  Copyright CCLRC
#+

itcl::class ApplyButton {
   inherit itk::Widget
   constructor args {}
   itk_option define -command command Command ""
   itk_option define -confirm confirm Confirm ""
   itk_option define -parcommand parCommand Command ""
   itk_option define -text text Text ""
   itk_option define -logger logger Logger logger
   itk_option define -system system System TCS
   private {
      method apply {}
   }
}

itk::usual ApplyButton {
   keep -activeforeground -background -cursor -disabledforeground -font \
         -foreground -highlightcolor -highlightthickness -logger -system
}

itcl::body ApplyButton::constructor args {

   itk_component add lbutton {
      LiveButton $itk_interior.lbutton -command [itcl::code $this apply]
   } {
      usual
      keep -relief -state
   }

   pack $itk_component(lbutton) -fill both -expand y

   eval itk_initialize $args
}

itcl::configbody ApplyButton::command {

# Create the sender for this command if it doesn't already exist.
   if { [catch {cs $itk_option(-command) info}] } {
      epics cs $itk_option(-command)
   }

# Configure the -text option of the LiveButton.
   if { [string equal $itk_option(-text) ""] } {
      $itk_component(lbutton) configure \
            -text [lindex [cs $itk_option(-command) info] 1]
   }
}

itcl::configbody ApplyButton::text {
   if { ! [string equal $itk_option(-text) ""] } {
      $itk_component(lbutton) configure -text $itk_option(-text)
   }
}

itcl::body ApplyButton::apply {} {

   set ok 1
   if { ! [string equal $itk_option(-confirm) ""] } {

# Display the confirmation dialog.
      if { ! [winfo exists $itk_interior.confirm] } {
         iwidgets::messagedialog $itk_interior.confirm \
               -text $itk_option(-confirm) -bitmap warning \
               -modality application -master $itk_interior
         $itk_interior.confirm hide Help
      }
      $itk_interior.confirm center
      set ok [$itk_interior.confirm activate]
   }

# Set the command parameters.
   if { $ok } {
      foreach par [lindex [cs $itk_option(-command) info] 3] {
         if { [string equal $itk_option(-parcommand) ""] } {
            cs $itk_option(-command) set $par mark
         } else {
            cs $itk_option(-command) set $par \
                  [list [$itk_option(-parcommand) $par]]
         }
      }

# Log the command and its parameters.
      if { ![string is space $itk_option(-logger)] } {
         $itk_option(-logger) command $itk_option(-command)
      }

# Post the command.
      if { [catch {cs $itk_option(-command) post} msg] } {
         tk_messageBox -icon error -parent $itk_interior -message \
   "Error posting $itk_option(-command) command: $itk_option(-system) reports \
               \"$msg\""
      }
   }
}
