#+
# CalParam
#
# A calibration parameter object supplies an application with calibration
# parameters and other values that may be revised over time or are potentially
# different between north and south. The values are read from a file
# when the object is created.
#
# D Terrett 20 January 2005
#
# Copyright CCLRC
#+

itcl::class CalParam {
   constructor {args} {}
   public {
      variable calFile {calparams.dat}
      variable pwfs1_center_x <undefined>
      variable pwfs1_center_y <undefined>
      variable pwfs1_center_z <undefined>
      variable pwfs2_center_x <undefined>
      variable pwfs2_center_y <undefined>
      variable pwfs2_center_z <undefined>
      variable acqcam_x <undefined>
      variable acqcam_y <undefined>
      variable ocs_proxy <undefined>
      variable tcs_root_dir <undefined>
      variable m1_tune_dir <undefined>
      variable default_wfs_dir <undefined>
      variable hrwfs_sky_dir <undefined>
      variable skycalc_dir <undefined>
      variable hrwfs_ao_prog <undefined>
      variable baffle_visible <undefined>
      variable baffle_nearir <undefined>
      variable niri_sfo_defocus <undefined>
      variable nifs_sfo_defocus <undefined>
      variable top_shutter_current_limit <undefined>
      variable bottom_shutter_current_limit <undefined>
   }
}

itcl::body CalParam::constructor {args} {
   global ROOT
   puts "CalParam using file $calFile"
   eval configure $args
   source $ROOT/$calFile
}
