#+
# CalParam
#
# A calibration parameter object supplies an application with calibration
# parameters that may be revised over time. The values are read from a file
# when the object is created.
#
# D Terrett 2 July  2001
#
# Copyright CCLRC
#+

itcl::class CalParam {
   constructor {args} {}
   public {
      variable pwfs1_center_x
      variable pwfs1_center_y
      variable pwfs1_center_z
      variable pwfs2_center_x
      variable pwfs2_center_y
      variable pwfs2_center_z
      variable acqcam_x
      variable acqcam_y
   }
}

itcl::body CalParam::constructor {args} {
   global ROOT
   source $ROOT/calparams.dat

   eval configure $args
}
