#+
#  ComponentControl <- itk::Widget
#
#  A ComponentControl widget is a widget with controls for selecting a 
#  configuration component. This class is intended to be inherited by the 
#  panels for specific components.
#
#  Options:
#           -apply          The name of the apply record to post.
#
#           -component      The class of component that the widget selects.
#
#           -namespace      The namespace in which the components are
#                           defined.
#
#           -system         The name of the system being controlled (for
#                           error messages).
#
#  Methods:
#           select name     Selects the component "name".
#
#           store name      Stores the widget contents in a new or existing 
#                           component object.
#
#           scratchobj      Returns the name of the scratch object used by 
#                           the control.
#
#           subselect component subcomponent
#
#  D Terrett  21 March 2001
#
#  Copyright CCLRC
#+

itcl::class ComponentControl {
   inherit itk::Widget
   constructor args {}
   destructor {}
   itk_option define -apply apply Apply tcsApply
   itk_option define -component component Component {}
   itk_option define -namespace namespace Namespace {}
   itk_option define -system system System TCS
   public {
      method select {name}
      method store {name}
      method scratchobj {} {return $scratchobj}
      method subselect {component name}
   }
   protected {
      method apply {args}
      method delselected {}
      variable description
      variable objclass
      variable scratchobj
   }
   private {
      method selectioncommand {}
      method returncom {}
      variable cursel {}
   }
}

itk::usual ComponentControl {
   keep -activebackground -activeforeground -background -borderwidth \
         -cursor -disabledforeground -font -foreground -highlightcolor \
         -highlightthickness -insertbackground -insertborderwidth \
         -insertofftime -insertontime -insertwidth -labelfont -popupcursor \
         -selectbackground -selectborderwidth -selectforeground \
         -textbackground -textfont -title -vt
}

itcl::body ComponentControl::constructor args {

   itk_component add top {
      frame $itk_interior.top
   }
   pack $itk_component(top) -fill x -expand y
   set w $itk_component(top)

   itk_component add label {
      label $w.label -width 1
   } {
      usual
      rename -text -title title Title
   }
   bind $itk_component(label) <Configure> {%W configure -wraplength %w}
   pack $itk_component(label) -fill x -expand yes

   itk_component add delete {
      button $w.delete -bitmap delete
   }
   itk_component add selector {
      ListManager $w.selector -returncommand [itcl::code $this returncom]
   } {
      usual
      keep -componentlist
   }
   pack $itk_component(delete) $itk_component(selector) -side left
   set w [winfo parent $w]
   itk_component add interior {
      frame $w.interior
   }
   pack $itk_component(interior) -fill both -expand y

# Store and apply buttons.
   itk_component add storeapply {
      StoreApply $w.storeapply -combobox $itk_component(selector) \
            -control [code $this]
   } {
      usual
      keep -shadow
   }
   pack $itk_component(storeapply) -fill x -pady 4

# Configure the selector and delete button.
   $itk_component(selector) configure \
         -selectioncommand [code $this selectioncommand]
   $itk_component(delete) configure -command [code $this delselected]

   set itk_interior $itk_component(interior)

   eval itk_initialize $args
}

itcl::body ComponentControl::destructor {} {

# Inform our edit shadow that we are being destroyed.
   $itk_option(-shadow) unmap

# Delete the scratch object.
   delete object $scratchobj
}

itcl::body ComponentControl::select name {

# Set the selector to "name" and load its contents into the edit controls.
   set cursel $name
   $itk_component(selector) select $name
   if { ! [string equal $name ""] } {
      $this selectobj $itk_option(-namespace)::$name
   }
}

itcl::body ComponentControl::store name {

# Determine the full name of the object to be updated.
   if { [string equal $name ""] } {
      set fullname $scratchobj
   } else {
      set fullname ::$itk_option(-namespace)::$name
   }

# If the object doesn't exist.
   if { [string equal [info commands $fullname] ""] } {

# Create it.
      $objclass $fullname $itk_option(-componentlist)

# Update the object with the contents of the widget, catching any errors
# due to invalid data.
      if { [catch {$this updateobj $fullname} msg] } {

# Delete the bad object and report the error.
         delete object $fullname
         $itk_component(selector) insert $name
         tk_messageBox -icon error -parent $itk_interior -message \
               "Error creating $description \"$name\": $msg"
         return 0
      }
   } else {

# Update the existing object with data from the widget.
      if { [catch {$this updateobj $fullname} msg] } {
         if { [string equal $name ""] } {
            tk_messageBox -icon error -parent $itk_interior -message \
                  "Error updating $description: $msg"
            return 0
         } else {
            tk_messageBox -icon error -parent $itk_interior -message \
                  "Error updating $description \"$name\": $msg"
            return 0
         }
      }
   } 

# Select the new or updated object.
   $itk_option(-shadow) selectfromcontrol $name

   return 1
}

itcl::body ComponentControl::subselect {component name} {
   $itk_component($component) select $name
}

itcl::body ComponentControl::apply args {

# Get the name of the component begin applied
   set name [$itk_component(selector) get]

# Update the object from the edit controls.
   if { [$itk_option(-shadow) store $name] } {

# Apply the object
      if { [string equal $name ""] } {
         eval $scratchobj apply $args

# Return the scratch object to its initial state so that it doesn't prevent
# the deletion of any of its subcomponents.
          $scratchobj init
      } else {
         eval $itk_option(-namespace)::$name apply $args
      }

# Post the command.
      if [catch {cs $itk_option(-apply) post} msg] {
            tk_messageBox -icon error -parent $itk_interior -message \
               "Error posting command: $itk_option(-system) reports \"$msg\""
      }
   }
}

itcl::body ComponentControl::delselected {} {
#+
# Deletes the currently selected component object.
#-
   set name [$itk_component(selector) get]
   if { ! [string equal $name ""] } {
      if { [catch {delete object $itk_option(-namespace)::$name} msg] } {
         tk_messageBox -icon error -message $msg \
               -parent $itk_interior -title "Component delete error"
      }
   }
}

itcl::body ComponentControl::selectioncommand {} {
#+
#  Updates the EditShadow with the new object name.
#-
   set name [$itk_component(selector) get]
   $itk_option(-shadow) selectfromcontrol $name
}

itcl::body ComponentControl::returncom {} {

# If the contents of the ListManager matches the current selection or doesn't
# exist then store it otherwise select it.
   set name [$itk_component(selector) get]
   if { [string equal $cursel $name] || [string equal \
         [info commands ::$itk_option(-namespace)::${name}] ""] } {
      store $name
  } else {
      selectioncommand
  }
}
