#+
#  EditShadow
#
#  An EditShadow object encapsulates the information needed to create an
#  edit control window and map it onto the screen. The EditShadow object 
#  exists even when the edit control doesn't so that other parts of the 
#  system can configure the window (via the EditShadow's select and subselect
#  methods without having to bother about whether the window exists. When the
#  window is created it is set to the correct state.
#
#  Options:
#           -children       A list of the child EditShadow of this one.
#
#           -component      The component class that this EditShadow edits.
#
#           -panel
#
#           -parent         The parent of this EditShadow.
#
#           -selection      The name of the component currently selected.
#
#           -window         The name of the eidt window controlled by this
#                           EditShadow.
#
#  Methods:
#           map             Calls the map method of the Panel that contains 
#                           this control.
#
#           select name     Sets the name of the object selected in the edit
#                           control
#
#           subselect component name  Sets the name of the object in the 
#                           specified sub-component selector
#
#           store name      Calls the store method of the control window (if 
#                           it exists) and the shadow objects of all the 
#                           subcomponents that have values.
#
#  D Terrett 24 November 1998
#
#  Copyright CCLRC
#+

itcl::class EditShadow {
   constructor {arg args} {}
   public {
      method map {}
      method select {name}
      method store {name}
      method subselect {component name}
      variable children ""
      variable component ""
      variable panel
      variable parent ""
      variable selection ""
      variable window ""
   }
   private {
      variable subselections
   }
}

itcl::body EditShadow::constructor {arg args} {

# Store the panel name.
   set panel $arg

   eval configure $args
}

itcl::configbody EditShadow::children {
   if { [array exists subselections] } {
      unset subselections
   }
   foreach child $children {
      set subselections($child) ""
   }
}

itcl::body EditShadow::map {} {

# Call the map method of the panel containing the edit control.
   if { [$panel map] } {

# Store the name of the edit control window.
      set window [lindex [$panel cget -windows] 0]

# Set the name of the shadow in the window.
      $window configure -shadow $this

# Configure the window by calling its select and subselect methods with
# the current state of the shadow.
      $window select $selection
      foreach el [array names subselections] {
         $window subselect $el $subselections($el)
      }
   }
}

itcl::body EditShadow::select name {

# If the edit control exists, call its select method.
   if { [winfo exists $window] } {
      $window select $name
   }

# If this shadow has a parent, then call its subselect method.
   if { [string length $parent] } {
      $parent subselect $component $name
   }

# Store the current selection.
   set selection $name
}

itcl::body EditShadow::store name {

# If the edit control exists, call its store method.
   if { [winfo exists $window] } {
      $window store $name 

# And select it.
      $window select $name
   }

# Call the store method of the edit shadow of the components that have values.
   foreach el [array names subselections] {
      if { [string length $subselections($el)] } {
         $this$el store $subselections($el)
      }
   }
}

itcl::body EditShadow::subselect {comp name} {

# If the edit control exists, call its subselect method.
   if { [winfo exists $window] } {
      $window subselect $comp $name 
   }

# If the subselection has changed, call the selection method of the edit 
# shadow of the component edit control.
   if { [info exists subselections($comp)] } {
      if { [string compare $subselections($comp) $name] } {
         set subselections($comp) $name
         $this$comp select $name
      }
   } else {
      set subselections($comp) $name
      $this$comp select $name
   }
}
