#+
#  EditPanelMgr <- PanelMgr
#
#  An EditPanelMgr is a PanelMgr with the addition of an options for 
#  configuring the componentList that the panel edits.
#
#  Options:
#           -componentlist  Configures the -componentlist option of the 
#                           EditPanel
#
#           -controls       A list of controls that the EditPanel contains
#
#           -namespace      Configures the -namespace option of the EditPanel
#
#           -vt             Configures the -vt option of the EditPanel
#
#  Methods:
#           map             Overrides the map method of PanelMgr
#
#  D Terrett 28 March 2001
#
#  Copyright CCLRC
#+

itcl::class EditPanelMgr {
   inherit PanelMgr
   constructor args {eval configure $args}
   public {
      method map {}
      variable componentlist {}
      variable controls {}
      variable namespace {}
      variable vt {}
   }
}

itcl::body EditPanelMgr::map {} {
   if { [$this PanelMgr::map] } {
      $name configure -componentlist $componentlist -namespace $namespace \
            -vt $vt
      return 1
   }
   return 0
}
