#+
#  EditPanelMgr <- PanelMgr
#
#  An EditPanelMgr is a PanelMgr with the addition of an options for 
#  configuring the componentList that the panel edits.
#
#  Options:
#           -componentlist  Configures the -componentlist option of the 
#                           EditPanel
#
#           -controls       A list of controls that the EditPanel contains
#
#           -namespace      Configures the -namespace option of the EditPanel
#
#           -vt             Configures the -vt option of the EditPanel
#
#  Methods:
#           map             Overrides the map method of PanelMgr
#
#  D Terrett 27 March 2001
#
#  Copyright CCLRC
#+

itcl::class EditPanelMgr {
   inherit PanelMgr
   constructor args {eval configure $args}
   public {
      method map {}
      variable componentlist {}
      variable controls {}
      variable namespace {}
      variable vt {}
   }
}

itcl::configbody EditPanelMgr::componentlist {
   if { [winfo exists $name] } {
      foreach c $componentlist {
         $name configure -componentlist $c
      }
   }
}

itcl::configbody EditPanelMgr::namespace {
   if { [winfo exists $name] } {
      foreach n $namespace {
         $name configure -namespace $n
      }
   }
}

itcl::configbody EditPanelMgr::vt {
   if { [winfo exists $name] } {
      foreach n $vt {
         $name configure -vt $n
      }
   }
}

itcl::body EditPanelMgr::map {} {
   if { [$this PanelMgr::map] } {

# Configure each of the control objects that the panel contains.
      foreach control $controls l $componentlist n $namespace v $vt {
         $name configure -componentlist $l -namespace $n -vt $v
      }
      return 1
   }
   return 0
}
