#+
#  EditShadow
#
#  An EditShadow object encapsulates the information needed to create an
#  edit control window and map it onto the screen. The EditShadow object 
#  exists even when the edit control doesn't so that other parts of the 
#  system can configure the window (via the EditShadow's selectfromparent and 
#  subselectfromchild  methods without having to bother about whether the 
#  window exists. When the window is created it is set to the correct state.
#
#  Options:
#           -alsomaps       A list of the other edit shadows who's windows
#                           get mapped at the same time as this one.
#
#           -children       A list of the child EditShadow of this one.
#
#           -component      The component class that this EditShadow edits.
#
#           -control        The component name of the edit window in the panel
#
#           -panel          The name of the panel that contains the edit
#                           window.
#
#           -parent         The parent of this EditShadow.
#
#           -selection      The name of the component currently selected.
#
#           -window         The name of the edit window controlled by this
#                           EditShadow.
#
#  Methods:
#           childstored comp       Informs the edit window that a child
#                                  component stored a new value.
#
#           map                    Calls the map method of the Panel that 
#                                  contains this control.
#
#           prepare                Prepares the window for use.
#
#           selectfromcontrol name Sets the name of the object selected and
#                                  updates the parent and child edit shadow
#                                  and updates the edit window.
#
#           selectfromparent name  Sets the name of the object selected and
#                                  updates the child edit shadows and
#                                  the edit window.
#
#           subselectfromcontrol comp name  Sets the name of the object in 
#                                           the specified sub-component 
#                                           selector and updates the child
#                                           edit shadow.
#
#           subselectfromchild comp name  Sets the name of the object in 
#                                         the specified sub-component selector 
#                                         and updates the parent edit shadow
#                                         and the edit window.
#
#           store name             Calls the store method of the control 
#                                  window (if it exists) and the shadow 
#                                  objects of all the subcomponents that have 
#                                  values.
#
#           storefromcontrol name  Calls store and then calls the childstored
#                                  method of the parent
#
#  D Terrett 29 March 2001
#
#  Copyright CCLRC
#+

itcl::class EditShadow {
   constructor {arg args} {}
   public {
      method map {}
      method prepare {}
      method childstored {comp}
      method selectfromcontrol {name}
      method selectfromparent {name}
      method store {name}
      method storefromcontrol {name}
      method subselectfromcontrol {comp name}
      method subselectfromchild {comp name}
      method unmap {} {set scratchobj ""}
      variable children ""
      variable component ""
      variable control control
      variable namespace ""
      variable panel
      variable parent ""
      variable alsomaps ""
      variable selection ""
      variable window ""
   }
   private {
      variable scratchobj ""
      variable subselections
   }
}

itcl::body EditShadow::constructor {arg args} {

# Store the panel name.
   set panel $arg

   eval configure $args
}

itcl::configbody EditShadow::children {
   if { [array exists subselections] } {
      unset subselections
   }
   foreach child $children {
      set subselections($child) ""
   }
}

itcl::body EditShadow::map {} {

# Call the map method of the panel containing the edit control.
   if { [$panel map] } {

# Prepare it for use.
      prepare

# Prepare the other windows that got mapped at the same time.
      foreach w $alsomaps {
         $w prepare
      }
   }
}

itcl::body EditShadow::prepare {} {

# Store the name of the edit control window.
   set window [[$panel cget -name] component $control]

# Set the name of the shadow in the window.
   $window configure -shadow $this

# Store the name of the window's scratch object.
   set scratchobj [$window scratchobj]

# Configure the window by calling its select and subselect methods with
# the current state of the shadow.
   $window select [namespace tail $selection]
   foreach el [array names subselections] {
      $window subselect $el $subselections($el)
   }
}

itcl::body EditShadow::selectfromparent {name} {

# Store the new object name.
   if { [string equal $name ""] } {
      set selection $scratchobj
   } else {
      set selection ${namespace}::$name
   }

# If the edit control exists, call its select method.
   if { [winfo exists $window] } {
      $window select $name
   }

# Update the subselections array from the object just selected.
   if { ! [string equal $selection ""] } {
      foreach el [array names subselections] {
         set subselections($el) [$selection cget -$el]
      }
   }

# Call the selectfromparent method of all this objects subcomponents that
# have values.
   foreach el [array names subselections] {
      if { ! [string equal $subselections($el) ""] } {
         $this$el selectfromparent $subselections($el)
      }
   }
}

itcl::body EditShadow::store name {

# If the edit control exists, call its store method.
   if { [winfo exists $window] } {
      if { ![$window store $name] } {
         return 0
      }

# And select it if it has a name.
      if { [string equal $name ""] } {
         $window select $name
      }
   }

# Store the new object name.
   if { [string equal $name ""] } {
      set selection $scratchobj
   } else {
      set selection ${namespace}::$name
   }

# Update the subselections array from the object just selected.
   if { ![string equal $name ""] } {
      foreach el [array names subselections] {
         set subselections($el) [$selection cget -$el]
      }
   }

# Call the store method of the edit shadow of the components that have values.
   foreach el [array names subselections] {
      if { ! [string equal $subselections($el) ""] } {
         if { ![$this$el store $subselections($el)] } {
            return 0
         }
      }
   }
   return 1
}

itcl::body EditShadow::selectfromcontrol {name} {

# Store the new object name.
   if { [string equal $name ""] } {
      set selection $scratchobj
   } else {
      set selection ${namespace}::$name
   }

# If the edit control exists, call its select method.
   if { [winfo exists $window] } {
      $window select $name
   }

# Update the subselections array from the object just selected.
   if { ! [string equal $selection ""] } {
      foreach el [array names subselections] {
         set subselections($el) [$selection cget -$el]
      }
   }

# If this shadow has a parent, then call its subselectfromchild method.
   if { ! [string equal $parent ""] } {
      $parent subselectfromchild $component $name
   }

# Call the selectfromparent method of all this objects subcomponents that
# have values.
   foreach el [array names subselections] {
      if { ! [string equal $subselections($el) ""] } {
         $this$el selectfromparent $subselections($el)
      }
   }
}

itcl::body EditShadow::subselectfromchild {comp name} {

# Store the new subcomponent value.
   set subselections($comp) $name

# If the edit control exists, call its subselect method.
   if { [winfo exists $window] } {
      $window subselect $comp $name
   }
}

itcl::body EditShadow::subselectfromcontrol {comp name} {

# Store the new subcomponent value.
   set subselections($comp) $name

# Call the selectfromparent of the subcomponent's edit shadow.
   $this$comp selectfromparent $name
}

itcl::body EditShadow::childstored {comp} {
   if { [winfo exists $window] } {
      $window childstored $comp
   }
   if { ! [string equal $parent ""] } {
      $parent childstored $comp
   }
}

itcl::body EditShadow::storefromcontrol {name} {
   if { [store $name] } {
      if { ! [string equal $parent ""] } {
         $parent childstored $component
         $parent subselectfromchild $component $name
      }
      return 1
   }
   return 0
}
