#+
#  EditPanelMgr <- PanelMgr
#
#  An EditPanelMgr is a PanelMgr with the addition of an options for 
#  configuring the componentList that the panel edits.
#
#  Options:
#           -componentlist  Configures the -componentlist option of the 
#                           EditPanel
#
#           -namespace      Configures the -namespace option of the EditPanel
#
#           -vt             Configures the -vt option of the EditPanel
#
#           -titlelist      Configures the -titlelist option of the EditPanel
#
#  Methods:
#           map             Overrides the map method of PanelMgr
#
#  D Terrett 30 March 2001
#
#  Copyright CCLRC
#+

itcl::class EditPanelMgr {
   inherit PanelMgr
   constructor args {eval configure $args}
   public {
      method map {component}
      variable componentlist {}
      variable namespace {}
      variable titlelist {}
      variable vt {}
   }
}

itcl::body EditPanelMgr::map {component} {
   if { [$this PanelMgr::map $component] } {
      $name configure -componentlist $componentlist -namespace $namespace \
            -vt $vt -titlelist $titlelist
      return 1
   }
   return 0
}
