#+
#  ListManager <- itk::Widget
#
#  Implements the ListManager class. A ListManager widget is a combobox with
#  a drop-down list that is associated with a ComponentList object and has
#  a method for selecting one of the elements in the list and returning the
#  name of the currently selected item. 
#
#  Options:
#          -componentlist  The name of the associated ComponentList object.
#
#          -returncommand  The action to perform when <Return> is detected 
#                          in the combo box
#
#  Methods:
#          select item     Selects the list entry "item".
#
#          get             Returns the name of the currently selected item.
#
#          insert string   Inserts a "string" into the entry widget
#
#  D Terrett  20 April 2000
#
#  Copyright CCLRC
#-

itcl::class ListManager {
   inherit itk::Widget
   constructor args {}
   destructor {}
   itk_option define -componentlist componentList ComponentList {}
   itk_option define -returncommand returnCommand Command break
   public {
      method select {item}
      method get {}
      method insert {string}
   }
}

itk::usual ListManager {
   keep -background -borderwidth -cursor -foreground -highlightcolor \
         -highlightthickness -insertbackground -insertborderwidth \
         -insertofftime -insertontime -insertwidth -labelfont -popupcursor \
         -selectbackground -selectborderwidth -selectforeground \
         -textbackground -textfont
}

itcl::body ListManager::constructor args {

   itk_component add selector {
      iwidgets::combobox $itk_interior.selector -width 14
   } {
      usual
      keep -editable -labelpos -labeltext -selectioncommand -state
   }

   pack $itk_component(selector) -fill both -expand y

   eval itk_initialize $args
}

itcl::body ListManager::destructor {} {
#-
# Removes the widget from the list of widgets managed by the list object.
#-
   set list $itk_option(-componentlist)
   if { $list != "" } {
      $list removewidget $itk_component(selector)
   }
}

itcl::configbody ListManager::componentlist {
#-
#  Adds the combobox widget to the list of widgets managed by the list.
#-
   if { $itk_option(-componentlist) != "" } {
      $itk_option(-componentlist) addwidget $itk_component(selector)
   }
}

itcl::body ListManager::select item {
#-
# Selects one of the items in the associated list.
#-

# Make the combobox editable.
   set editable [$itk_component(selector) cget -editable]
   if { $editable == 0 } {
      $itk_component(selector) configure -editable 1
   }

# Clear the current selection.
   $itk_component(selector) selection clear 0 end

# Select the item according to its position in the list.
   if { $itk_option(-componentlist) != "" } {
      set i [$itk_option(-componentlist) index $item]
      if { $i >= 0 } {
         $itk_component(selector) selection set $i
      }
   } else {
      error "componentlist not defined"
   }

# Restore the editability.
   if { $editable == 0 } {
      $itk_component(selector) configure -editable 0
   }
}

itcl::body ListManager::get {} {
#-
# Returns the currently selected item.
#-
   return [$itk_component(selector) get]
}

itcl::body ListManager::insert string {
#-
# Sets the combobox to the specified string as if it had been typed into
# the box.
#-

# Make the combobox editable.
   set editable [$itk_component(selector) cget -editable]
   if { $editable == 0 } {
      $itk_component(selector) configure -editable 1
   }

# Clear the current selection.
   $itk_component(selector) selection clear 0 end

# Insert the string.
   $itk_component(selector) insert entry end $string

# Restore the editability.
   if { $editable == 0 } {
      $itk_component(selector) configure -editable 0
   }
}

itcl::configbody ListManager::returncommand {
   bind [$itk_component(selector) component entry] <Return> \
         $itk_option(-returncommand)
}
