#+
#  Logger
#
#  Implements the Logger class. A logger object monitors the TCS applyC.CLID
#  and errorMess.VAL and displays a log of TCS activity in as scrollable text 
#  window. The log method allows additional messages to be written to the log.
#
#  Options:
#          none
#
#  Methods:
#          log message   Writes "message" into the log window.
#
#          command cs    Writes the values of the command sender cs's
#                        parameters to the log window.
#
#  D Terrett 27 September 2000
#
#  Copyright CCLRC
#+

itcl::class Logger {

   constructor {apply applyC errMessage} {}

   public method log message
   public method command cs

   private method monitor {record status time value}
   private method send text

   private variable clid 0
   private variable applyMess {}
   private variable Apply
   private variable ApplyC
   private variable ErrMessage
}

itcl::body Logger::constructor {apply applyC errMessage} {

# Set up monitors on the TCS epics records of interest.
   sa $applyC proc clid [code $this monitor]
   sa $apply proc mess [code $this monitor]
   sa $errMessage proc val [code $this monitor]

# Save the record names.
   set Apply $apply
   set ApplyC $applyC
   set ErrMessage $errMessage
}

itcl::body Logger::monitor {record status time value} {

# Get UTC timestamp for the message.
   set utc [sa tcssad get UTC value]

# Initialise message.
   set text ""

# Switch on the record name.
   switch $record \
         $ApplyC.clid {

# If the client ID was incremented then a command was accepted by the TCS.
            if { $value > $clid } {
                 set text "$utc: command accepted"
                 set clid $value
            }
         } \
         $ErrMessage.val {
            set text "$utc: $value"
         } \
         $Apply.mess {
            if { ![string is space $value] } {
               set text "$utc: rejected: $value"
            }
         }

# Send the text to the logger.
   if { ![string is space $text] } {
      send $text
   }
}

itcl::body Logger::log message {
   set text "[sa tcssad get UTC value]: $message"

# Send the text to the logger.
   send $text
}

itcl::body Logger::command cs {

# Get UTC timestamp for the message.
   set text [sa tcssad get UTC value]:

# Get the command info
   set info [cs $cs info]

# Write the name of the command.
   set text "$text [lindex $info 1]"

# Get the names of the commands parameters.
   set params [lindex $info 3]

   foreach par $params {

#  Ingnore parameters called dummy.
      if { [string equal dummy $par] } continue

#  Get the value
      set val [cs $cs get $par]

#  Ignore empty values or "No Value".
      if { [string is space $val] || [string equal $val "No Value"] } continue

#  add the name and value to the log window.
      set text "$text, [lindex [cs $cs info $par] 2] = $val"
   }

# Send the text to the logger.
   send $text
}

itcl::body Logger::send text {
   set logwindow [logPanel cget -windows]
   if { [winfo exists $logwindow] } {
       $logwindow add $text
   }
}
