#+
#  PanelButton <- itk::widget
#
#  A panel button is a button that creates and maps a tcc panel window. If
#  the panel already exists but is iconised or hidden it is mapped to the
#  screen
#
#  Options:
#           -panel          The name of the panel to be created or mapped.
#
#  Methods:
#           none
#
#  D Terrett  5 August 1998
#
#  Copyright CCLRC
#-

itcl::class PanelButton {
   inherit itk::Widget
   constructor args {}
   itk_option define -panel panel Panel ""
   protected {
      method map {} {$itk_option(-panel) map}
   }
}

itk::usual PanelButton {
   keep -activebackground -activeforeground -background -cursor \
         -disabledforeground -foreground -font -highlightcolor \
         -highlightthickness
}

itcl::body PanelButton::constructor args {
   itk_component add button {
      button $itk_interior.button
   } {
      usual
      keep -bitmap -state -text
   }

   pack $itk_component(button) -fill x -expand y

   eval itk_initialize $args
}

itcl::configbody PanelButton::panel {
   $itk_component(button) configure -command [code $this map]
}
