#+
#  XML.itcl
#
#  An XML object writes a file in XML
#
#  D Terrett 12 March 2002
#
#  Copyright CCLRC
#-

itcl::class XML {
   constructor {fd type} {}
   destructor {}
   public {
      method beginParamset {name type}
      method endParamset {}
      method param {name value}
   }
   private {
      method quote {string}
      variable file
      variable ftype
      variable indent ""
   }
}

itcl::body XML::constructor {fd type} {
   set file $fd
   set ftype $type
   puts $file "<$ftype>"
}

itcl::body XML::destructor {} {
   puts $file "</$ftype>"
}

itcl::body XML::quote {string} {
   regsub -all & $string {\&amp;} string
   regsub -all < $string {\&lt;} string
   regsub -all \" $string {\&quot;} string
   return \"$string\"
}

itcl::body XML::beginParamset {name type} {
   puts $file "$indent <paramset name=[quote $name] type=[quote $type]>"
   set indent "${indent}   "
}

itcl::body XML::param {name value} {
   if { ![string is space $value] } {
      puts $file "$indent <param name=[quote $name] value=[quote $value]/>"
   }
}

itcl::body XML::endParamset {} {
   set indent [string range $indent 0 end-3]
   puts $file "$indent </paramset>"
}
