#+
# CalParam
#
# A calibration parameter object supplies an application with calibration
# parameters and other values that may be revised over time or are potentially
# different between north and south. The values are read from a file
# when the object is created.
#
# D Terrett 20 January 2005
#
# Copyright CCLRC
#+

itcl::class CalParam {
   constructor {args} {}
   public {
		variable defaultFile <undefined>
      variable calFile <undefined>
      variable site <undefined>
      variable pwfs1_center_x <undefined>
      variable pwfs1_center_y <undefined>
      variable pwfs1_center_z <undefined>
      variable pwfs2_center_x <undefined>
      variable pwfs2_center_y <undefined>
      variable pwfs2_center_z <undefined>
      variable acqcam_x <undefined>
      variable acqcam_y <undefined>
      variable ocs_proxy <undefined>
      variable tcs_root_dir <undefined>
      variable m1_tune_dir <undefined>
      variable default_wfs_dir <undefined>
      variable hrwfs_sky_dir <undefined>
      variable skycalc_dir <undefined>
      variable hrwfs_ao_prog <undefined>
      variable baffle_visible <undefined>
      variable baffle_nearir <undefined>
      
      variable centralBaffleOverride
      variable deployableBaffleOverride
      
      variable niri_sfo_defocus <undefined>
      variable nifs_sfo_defocus <undefined>
      variable gnirs_sfo_defocus <undefined>
      variable gmos_sfo_defocus <undefined>
      variable niri_p1_defocus <undefined>
      variable nifs_p1_defocus <undefined>
      variable gnirs_p1_defocus <undefined>
      variable gmos_p1_defocus <undefined>
      variable gmos_oi_defocus <undefined>
      variable top_shutter_current_limit <undefined>
      variable bottom_shutter_current_limit <undefined>
      variable p1m2TipGain
      variable p1m2TiltGain
      variable p1m2FocusGain
      variable p2m2TipGain
      variable p2m2TiltGain
      variable p2m2FocusGain
      variable oim2TipGain
      variable oim2TiltGain
      variable oim2FocusGain
		
		variable odgw1XLimLow
		variable odgw1XLimHigh
		variable odgw1YLimLow
		variable odgw1YLimHigh
		variable odgw2XLimLow
		variable odgw2XLimHigh
		variable odgw2YLimLow
		variable odgw2YLimHigh
		variable odgw3XLimLow
		variable odgw3XLimHigh
		variable odgw3YLimLow
		variable odgw3YLimHigh
		variable odgw4XLimLow
		variable odgw4XLimHigh
		variable odgw4YLimLow
		variable odgw4YLimHigh
		
		variable sfsExpLUT ""
		variable odgwExpLUT ""
      variable odgwParamLUT
		
		variable lgsExpDefault 200
		variable ngsExpDefault 200
		variable sfsExpDefault 10
		variable odgwExpDefault 100
		variable lgsAlarmDefault 50
		variable ngsAlarmDefault 100
		variable sfsAlarmDefault 100
		variable odgwAlarmDefault 100
      variable gpiAlarmDefault 100

      method p1m2TipGain {instrument wfs}
      method p1m2TiltGain {instrument wfs}
      method p1m2FocusGain {instrument wfs}
      method p2m2TipGain {instrument wfs}
      method p2m2TiltGain {instrument wfs}
      method p2m2FocusGain {instrument wfs}
      method oim2TipGain {instrument wfs}
      method oim2TiltGain {instrument wfs}
      method oim2FocusGain {instrument wfs}
      
      method odgwGetSciRows { size }
      method odgwGetIdleRows { size }
      method odgwGetDisplayRate { size }
      
      method centralBaffleOverride {instrument}
      method deployableBaffleOverride {instrument}
   }
}

itcl::body CalParam::constructor {args} {
   global ROOT
   
   set m2TipGain(Default) 0.1
   set m2TiltGain(Default) 0.1
   set m2FocusGain(Default) 0.0002
   eval configure $args
	if { $defaultFile eq "<undefined>" } {
	   if { [string compare [exec uname] "Linux"] == 0 } {
	   	set defaultFile defaultparams.$::env(GEMINI_SITE).[exec uname]
	   } else {
	   	set defaultFile "defaultparams.dat"
	   }
	}
	if { $calFile eq "<undefined>" } {
	   if { [string compare [exec uname] "Linux"] == 0 } {
	   	set calFile [file join $::env(GEMINI_TOP) etc tcc calparams calparams.dat]
	   } else {
	   	set calFile "/gemini/files/calparams/calparams.dat"
	   }
	}
   puts "CalParam using file $calFile (defaults is $ROOT/$defaultFile)"
   source $ROOT/$defaultFile
   source $calFile
}

itcl::body CalParam::p1m2TipGain {instrument wfs} {
   set key "$instrument,$wfs"
   if { [array names p1m2TipGain -exact $key] == "" } {
      return <undefined>
   } else {
      return $p1m2TipGain($key)
   }
}

itcl::body CalParam::p1m2TiltGain {instrument wfs} {
   set key "$instrument,$wfs"
   if { [array names p1m2TiltGain -exact $key] == "" } {
      return <undefined>
   } else {
      return $p1m2TiltGain($key)
   }
}
itcl::body CalParam::p1m2FocusGain {instrument wfs} {
   set key "$instrument,$wfs"
   if { [array names p1m2FocusGain -exact $key] == "" } {
      return <undefined>
   } else {
      return $p1m2FocusGain($key)
   }
}

itcl::body CalParam::p2m2TipGain {instrument wfs} {
   set key "$instrument,$wfs"
   if { [array names p2m2TipGain -exact $key] == "" } {
      return <undefined>
   } else {
      return $p2m2TipGain($key)
   }
}

itcl::body CalParam::p2m2TiltGain {instrument wfs} {
   set key "$instrument,$wfs"
   if { [array names p2m2TiltGain -exact $key] == "" } {
      return <undefined>
   } else {
      return $p2m2TiltGain($key)
   }
}
itcl::body CalParam::p2m2FocusGain {instrument wfs} {
   set key "$instrument,$wfs"
   if { [array names p2m2FocusGain -exact $key] == "" } {
      return <undefined>
   } else {
      return $p2m2FocusGain($key)
   }
}

itcl::body CalParam::oim2TipGain {instrument wfs} {
   set key "$instrument,$wfs"
   if { [array names oim2TipGain -exact $key] == "" } {
      return <undefined>
   } else {
      return $oim2TipGain($key)
   }
}

itcl::body CalParam::oim2TiltGain {instrument wfs} {
   set key "$instrument,$wfs"
   if { [array names oim2TiltGain -exact $key] == "" } {
      return <undefined>
   } else {
      return $oim2TiltGain($key)
   }
}
itcl::body CalParam::oim2FocusGain {instrument wfs} {
   set key "$instrument,$wfs"
   if { [array names oim2FocusGain -exact $key] == "" } {
      return <undefined>
   } else {
      return $oim2FocusGain($key)
   }
}

itcl::body CalParam::odgwGetSciRows { size } {
   if { [array names odgwParamLUT -exact $size] == "" } {
      return 16
   } else {
      return [lindex $odgwParamLUT($size) 0]
   }
}

itcl::body CalParam::odgwGetIdleRows { size } {
   if { [array names odgwParamLUT -exact $size] == "" } {
      return 16
   } else {
      return [lindex $odgwParamLUT($size) 1]
   }
}

itcl::body CalParam::odgwGetDisplayRate { size } {
   if { [array names odgwParamLUT -exact $size] == "" } {
      return 2
   } else {
      return [lindex $odgwParamLUT($size) 2]
   }
}

itcl::body CalParam::centralBaffleOverride {instrument} {
   if { [array names centralBaffleOverride -exact $instrument] == "" } {
      return <undefined>
   } else {
      return $centralBaffleOverride($instrument)
   }
}

itcl::body CalParam::deployableBaffleOverride {instrument} {
   if { [array names deployableBaffleOverride -exact $instrument] == "" } {
      return <undefined>
   } else {
      return $deployableBaffleOverride($instrument)
   }
}
