#+
#  Component
#
#  The Component class is a virtual base class for all the specific 
#  configuration component classes. 
# 
#  A component object adds itself to a componentList object when it is 
#  created and removing itself when it is deleted. It has a reference
#  count which prevents it from being deleted if the count is not zero.
#
#  Options:
#          none
#
#  Methods:
#          Component list   Creates the Component object adds it to the
#                           list object "list".
#
#          refinc           Increments the reference count.
#
#          refdec           Decrements the reference count.
#
#  D Terrett 20 February 2000
#
#  Copyright CCLRC
#+

itcl::class Component {
   constructor list {}
   destructor {}
   public {
      method refinc {} {incr refcount}
      method refdec {} {incr refcount -1}
      variable refcount 0
   }
   protected {
      variable componentList
   }
}

itcl::body Component::constructor list {
   $list add [namespace tail $this] end
   set componentList $list
}

itcl::body Component::destructor {} {
   if { $refcount } {
      error \
      "\"[namespace tail $this]\" cannot be deleted (reference count not zero)"
   }
   $componentList remove [namespace tail $this]
}
