#+
#  Component
#
#  The Component class is a virtual base class for all the specific 
#  configuration component classes. 
# 
#  A component object adds itself to a componentList object when it is 
#  created and removing itself when it is deleted. It has a reference
#  count which prevents it from being deleted if the count is not zero.
#
#  Options:
#          none
#
#  Methods:
#          Component list   Creates the Component object adds it to the
#                           list object "list".
#
#          refinc           Increments the reference count.
#
#          refdec           Decrements the reference count.
#
#  D Terrett 20 February 2000
#
#  Copyright CCLRC
#
# NOTE: There is a potencial problem for derived classes with the object adding
# itself to the list. The object is added before the derived class constructor
# is executed. That means some object variable will not be initialized when
# widgets are notified of the inclusion of the new object.
#+

itcl::class Component {
   constructor {list {_useFullName 0} } {}
   destructor {}
   public {
      method refinc {} {incr refcount}
      method refdec {} {incr refcount -1}
      variable refcount 0
   }
   protected {
      variable componentList
		variable useFullName 0
   }
}

itcl::body Component::constructor {list {_useFullName 0} } {
	set useFullName $_useFullName
	if { ![string equal $list ""] } {
		if { $useFullName } {
		   $list add $this end
		} else {
	   	$list add [namespace tail $this] end
		}
	}
   set componentList $list
}

itcl::body Component::destructor {} {
   if { $refcount } {
      error \
      "\"[namespace tail $this]\" cannot be deleted (reference count not zero)"
   }
	if { ![string equal $componentList ""] } {
		if { $useFullName } {
	   	$componentList remove $this
		} else {
	   	$componentList remove [namespace tail $this]
		}
	}
}
