#+
#  ComponentList
#
#  A ComponentList object manages a list of component objects, keeping any 
#  associated combo boxes up-to-date.
#
#  Options:
#           none
#
#  Methods:
#           add component position  Adds a component to the list at the
#                            specified position.
#
#           addwidget widget  Adds a widget to the list of combo boxes updated
#                           when the component list changes.
#
#           get position    Returns the name of the component at the specified 
#                           position.
#
#           index component Returns the index position of the specified
#                           component.
#
#           length          Returns the number of items in the list.
#
#           remove component  Removes a component from the list.
#
#           removewidget widget  Removes a widget from the list of widgets.
#
#  Notes:
#        o A position can be either an integer or the string "end".
#
#  D Terrett 19 September 2001
#
#  Copyright CCLRC
#+

itcl::class ComponentList {
   public {
      destructor {}
      method add {component position}
      method addwidget {widget}
      method get position {return [lindex $list $position]}
      method index component {return [lsearch -exact $list $component]}
      method length {} {return [llength $list]}
      method remove {component}
      method removewidget {widget}
   }
   protected {
      variable list {{}}
   }
   private {
      variable widgetList {}
   }
}

itcl::body ComponentList::destructor {} {
   foreach widget $widgetList {
      removewidget $widget
   }
}

itcl::body ComponentList::add {component position} {
# Add the new component to the list.
   if { [string equal $position "end"] || $position > [llength $list] } {
      lappend list $component
   } else {
      set list [lreplace $list $position -1 $component]
   }

# Add the component to all the associated widgets.
   foreach widget $widgetList {
      $widget insert list $position $component
   }
}

itcl::body ComponentList::addwidget widget {

# Check that the widget isn't already on the list.
   if { [lsearch -exact $widgetList $widget] == -1 } {

# Append the widget to the list.
      lappend widgetList $widget

# Add all the components to the new widget.
      foreach el $list {
         $widget insert list end $el
      }
   }
}

itcl::body ComponentList::remove component {

# remove the component from the list.
   set index [lsearch -exact $list $component]
	if {$index == -1 } {
		error "ComponentList::remove ($this), trying to remove unknown componet ($component). Valid options are $list"
	}
   set list [lreplace $list $index $index]

# Remove the component from all the widgets.
   foreach widget $widgetList {
      set editstate [$widget cget -editable]
      $widget configure -editable 1
      $widget delete list $index
      $widget configure -editable $editstate
   }
}

itcl::body ComponentList::removewidget widget {
   if { [winfo exists $widget] } {

# Clear the widget.
      set editstate [$widget cget -editable]
      $widget configure -editable 1
      $widget delete list 0 end
      $widget delete entry 0 end
      $widget configure -editable $editstate

   }
   set index [lsearch -exact $widgetList $widget]
   set widgetList [lreplace $widgetList $index $index]
}
