#+
#  MonitorLabel <- itk::Widget
#
#  Implements a label which monitors an EPICS and displays its value.
#
#  Methods:
#         
#
# AWEbbers  January, 2005
#

itcl::class MonitorLabel {
   inherit itk::Widget
   constructor {sys var args} {}
   destructor {}
   public {
       method getValue {}
       method traceProc { name index op }
   }
   private {
      variable varName ""
		variable attrName ""
		variable sysName ""
      variable buttonList {}
   }
   itk_option define -width width Width 0 {
	#puts "new width: $itk_option(-width)"
   }
   itk_option define -text text Text "" {
	#puts "label text: $itk_option(-text)"
   }
   itk_option define -font font Font "Arial 12" {
	#puts "new font: $itk_option(-font)"
   }
   itk_option define -anchor anchor Anchor "c" {
	#puts "new anchor: $itk_option(-anchor)"
   }
   itk_option define -trans trans Trans "" {
	#puts "new trans: $itk_option(-trans)"
   }
   itk_option define -state state State "" {
        #puts "new state: $itk_option(-state)"
       foreach {button} $buttonList {
           $button configure -state $itk_option(-state)
       }
   }
}

itk::usual MonitorLabel {
   keep -background -cursor
}

itcl::body MonitorLabel::constructor {sys var args} {

# Create the status acceptor if it doesn't alread exist.
   if { [catch {sa $sys info}] } {
      epics sa $sys
      #puts just created sa $sys
   }

   itk_option add MonitorLabel::width
   #puts "MonitorLabel const: this: $this sys: $sys var: $var path: $itk_interior"
   eval itk_initialize $args
   set varName "$var\(value\)"
	set sysName $sys
	set attrName $var

   global $var

   itk_component add frame {
	frame $itk_interior.fr
   }
   set w $itk_interior.fr
   pack $w

   itk_component add desc { 
	label $w.desc -text $itk_option(-text) -font $itk_option(-font)
   }
   lappend buttonList $itk_component(desc)

   itk_component add label { 
	label $w.lab -text "" -width $itk_option(-width) -font $itk_option(-font)
   }
   lappend buttonList $itk_component(label)

   trace add variable $varName write [itcl::code $this traceProc]

   set $varName [sa $sys get $var]
   sa $sys link $var $var

#   set unlink "sa $sys unlink $var $var"
#   set untrace "trace remove variable $varName write [list [itcl::code $this traceProc]]"

   pack $itk_component(desc) $itk_component(label) -side left -anchor $itk_option(-anchor)
}

itcl::body MonitorLabel::destructor {} {
   global [string trimright $varName "(value)"]
	
	sa $sysName unlink $attrName
	
	trace remove variable $varName write [itcl::code $this traceProc]
}

itcl::body MonitorLabel::getValue {} {
   global [string trimright $varName "(value)"]
   #puts "MonitorLabel getValue $varName"

   #puts "MonitorLabel getValue $varName = [set $varName]"
   return [set $varName]
}

itcl::body MonitorLabel::traceProc {name index op} {

   set gVar "$name\($index\)"
   #puts "gVar: $gVar"
   global $name
   #puts "traceProc called with name: $name index: $index op: $op gVar: $gVar [set $gVar] colRules: $itk_option(-trans)"

   $itk_component(label) configure -text [set $gVar]

   foreach {val text} $itk_option(-trans) {
      if {[string match $val [set $gVar]]} {
         $itk_component(label) configure -text $text
      }
   }
}
