#+
# PointObs
#
# A PointObs object sequences the actions needed to execute a pointing
# sequence of pointing observations.
#
#    Methods:
#
#       slew   Slews to the next star
#
#       log    Logs the pointing data
#
#    Options:
#
#       guidedelay     The number of seconds to wait before enabling guiding.
#
#       logdelay       The number of seconds to wait after enabling guiding
#                      before loging the pointing.
#
#       logafterslew   If true, the pointing is logged at the end of a slew.
#
#       nextstyle      The method for selecting the next star.
#
#       selectafterlog If true, slew to the next star after logging.
#
#       guide          If true, guiding is enabled before logging and
#                      disbaled afterwards.
#
#       wfs            Which WFS to use for guiding.
#
#       zlpm           If true, zero the local pointing model when slewing.
#
#  D Terrett 23 July 2000
#
#  Copyright CCLRC
#+

itcl::class PointObs {

   constructor {sourceentry args} {}

   public method slew {}
   public method log {}

   public variable logdelay 0
   public variable guidedelay 10
   public variable logafterslew 0
   public variable nextstyle minslew
   public variable selectafterlog 0
   public variable guideafterslew 0
   public variable zlpm 0
   public variable wfs PWFS2

   private method nextstar {args}
   private method nextaction {args}
   private method reporterror {message}
   private method start {action}
   private method onerror {message}
   private method isinposition {} 
   private method novignette
   private method isguiding

   private variable SlewAction
   private variable Guide1Action
   private variable Guide2Action
   private variable MountGuideAction
   private variable GuideOffAction
   private variable DomeWaitAction
   private variable LogAction
   private variable SourceEntry
   private variable AzElPlot
   private variable Catalogue
   private variable Guiding 0
   private variable InPosition
   private variable DomeVignette
   private variable IsGuiding
   private variable LogCount 0
}

itcl::body PointObs::constructor {sourceentry azelplot catalogue args} {

# Store the source entry etc object.
   set SourceEntry $sourceentry
   set AzElPlot $azelplot
   set Catalogue $catalogue

# Create the action that slews the telescope.
   set SlewAction [seq::Action #auto tcs -timeout 300 \
         -onok [code $this nextaction slew] \
         -onerror [code $this onerror] \
         -ontimeout [code $this onerror "Slew timed out"] \
         -oktest [code $this isinposition] \
         -waitvar [scope InPosition(value)]]
   sa tcssad link inPosition [scope InPosition]
   $SlewAction set slew pointing Off

# Create action that waits for the dome vignetting to go to zero.
   set DomeWaitAction [seq::Action #auto tcs -timeout 300 \
         -onok [code $this nextaction domewait] \
         -ontimeout [code $this onerror "timed out waiting for dome"] \
         -oktest [code $this novignette] \
         -waitvar [scope DomeVignette(value)]]
   sa tcssad link domeVignette [scope DomeVignette]

# Create actions for enabling and disabling guiding.
   set MountGuideAction [seq::Action #auto tcs \
         -onok "after 10000 [code $this nextaction guideon]" \
         -onerror [code $this onerror] \
         -oktest [itcl::code $this isguiding] \
         -ontimeout [code $this onerror "Attempt to guide timed out"] \
         -waitvar [scope IsGuiding(value)]]
   $MountGuideAction set mountGuide mode On 
   set Guide1Action [seq::Action #auto tcs \
         -onok "after 5000 [namespace code "$MountGuideAction start"]" \
         -onerror [code $this onerror]]
   $Guide1Action set m2Guide state On
   $Guide1Action set pwfs1Observe noexp -1

   set Guide2Action [seq::Action #auto tcs \
         -onok "after 5000 [namespace code "$MountGuideAction start"]" \
         -onerror [code $this onerror]]
   $Guide2Action set m2Guide state On
   $Guide2Action set pwfs2Observe noexp -1

   set GuideOffAction [seq::Action #auto tcs \
         -onok [code $this nextaction guideoff] \
         -onerror [code $this onerror] \
         -ontimeout [code $this onerror "Attempt to disable guiding timed out"]]
   $GuideOffAction set m2Guide state Off
   $GuideOffAction set mountGuide mode Off 
   $GuideOffAction set pwfs1StopObserve dummy 1
   $GuideOffAction set pwfs2StopObserve dummy 1

# Create the action that logs the pointing.
   set LogAction [seq::Action #auto tcs -timeout 300 \
         -onok [code $this nextaction log] \
         -onerror [code $this onerror] \
         -ontimeout [code $this onerror "Logging pointing timed out"] \
         -oktest [code $this isinposition] \
         -waitvar [scope InPosition(value)]]

# Set the pointLog parameter to mark the CAD.
   $LogAction set pointLog log Off

   eval configure $args
}

itcl::body PointObs::slew {} {

   $SlewAction set sourceA objName [[$SourceEntry component objname] get]
   $SlewAction set sourceA system [[$SourceEntry component frame] get]
   $SlewAction set sourceA theta1 [[$SourceEntry component ra] get]
   $SlewAction set sourceA theta2 [[$SourceEntry component dec] get]
   $SlewAction set sourceA equinox [[$SourceEntry component equinox] get]
   $SlewAction set sourceA epoch [[$SourceEntry component epoch] get]
   $SlewAction set sourceA parallax [[$SourceEntry component parallax] get]
   $SlewAction set sourceA dtheta1 [[$SourceEntry component pmra] get]
   $SlewAction set sourceA dtheta2 [[$SourceEntry component pmdec] get]
   $SlewAction set sourceA rv [[$SourceEntry component rv] get]

   start $SlewAction
}

itcl::body PointObs::log {} {

# Look at the guide ca/ce to check that some guiding has taken place and that
# it isn't an excessive amount.
   set ca [sa tcssad get caguide]
   set ce [sa tcssad get ceguide]
   if { $ca == 0.0 && $ce == 0.0 } {
      set ans [tk_messageBox -icon question -parent . -type yesno \
         -message "No guiding has taken place. Log this star ?"]
   } elseif { $ca * $ca + $ce * $ce > 100.0 } {
      set ans [tk_messageBox -icon question -parent . -type yesno \
         -message "guiding correction is accessive. Log this star ?"]
   } else {
      set ans yes
   }
 
   if { [string equal $ans yes] } {
      start $LogAction
   } else {
      nextaction log
   }
}

itcl::body PointObs::nextaction {after} {
   switch $after {
      slew {
         set LogCount 0
         start $DomeWaitAction
      }
      domewait {
         set LogCount 0
         if { $guideafterslew } {
            set Guiding 1
            switch $wfs {
               PWFS1 {
                  start $Guide1Action
               }
               PWFS2 {
                  start $Guide2Action
               }
            }
         } elseif { $logafterslew } {
            log
         }
      }
      guideon {
         set LogCount 0
         if { $logafterslew } {
            log
         }
      }
      guideoff {
         set LogCount 0
         if { $selectafterlog } {
            set Guiding 0
            nextstar
         }
      }
      log {
         if { $LogCount < 4 } {
            incr LogCount
            after 100 [namespace code "$LogAction start"]
         } else {
            set LogCount 0
            if { $Guiding } {
               start $GuideOffAction
            } elseif { $selectafterlog } {
               nextstar
            }
         }
      }
   }
}

itcl::configbody PointObs::zlpm {
   if { $zlpm } {
      $SlewAction set slew pointing On
   } else {
      $SlewAction set slew pointing Off
   }
}

itcl::body PointObs::nextstar {args} {
   set tag [$AzElPlot next $nextstyle]
   $Catalogue select $tag
   $AzElPlot select $tag
}

itcl::body PointObs::reporterror {message} {
   tk_messageBox -icon error -message $message -type ok \
         -title "Point Test Error"
}


itcl::body PointObs::start {action} {
   if { [catch {$action start} message] } {
      reporterror $message
   }
}

itcl::body PointObs::onerror {message} {
   reporterror $message
}

itcl::configbody PointObs::logdelay {
   $MountGuideAction configure -onok "after [expr {$logdelay * 1000}] \
         [code $this nextaction guideon]" 
}

itcl::body PointObs::isinposition {} {
   set val [sa tcssad get inPosition]
   return [string equal $val TRUE]
}

itcl::body PointObs::novignette {} {
   set val [sa tcssad get domeVignette]
   return [expr { $val <= 0.0 }]
}

itcl::body PointObs::isguiding {} {
   switch $wfs {
      PWFS1 {
         set val [sa agssad get p1guiding]
      }
      PWFS2 {
         set val [sa agssad get p2guiding]
      }
   }
   return [expr { $val == 0 }]
}

itcl::configbody PointObs::guidedelay {
   $SlewAction configure -onok "after [expr {$guidedelay * 1000}] \
         [code $this nextaction slew]"
}
