#+
# ProbeCal <- itk::Widget
#
# The interface of the probe calibration procedure.
#
# D Terrett 23 June 2001
#
# Copyright CCLRC
#+

itcl::class ProbeCal {
   inherit itk::Widget
   constructor {args} {}
   destructor {}
   public {
      variable guidetelwait 10000
      variable guidewfswait 20000
   }
   private {
      method start {}
      method isinposition {p}
      method report {act msg}
      method log {p}
      method probesetup {p}
      method finish {}
      method manual {p}
      variable probe
      variable logfd
      variable poindex
      variable polist
      variable action
      variable inposition1
      variable inposition2
      variable xguide 150
      variable yguide 150
   }
}

itk::usual ProbeCal {
   keep -labelfont -selectcolor
   keep -background -cursor -foreground -font
   keep -activebackground -activeforeground -disabledforeground
   keep -highlightcolor -highlightthickness
}

itcl::body ProbeCal::constructor {args} {

   itk_component add options {
      frame $itk_interior.options
   }
   set w $itk_component(options)

   itk_component add probe {
      iwidgets::radiobox $w.probe -labeltext Probe
   }
   $itk_component(probe) add 1 -text "P1      "
   $itk_component(probe) add 2 -text P2
   $itk_component(probe) select 0

   itk_component add mode {
      iwidgets::radiobox $w.mode -labeltext Mode
   }
   $itk_component(mode) add auto -text Auto
   $itk_component(mode) add manual -text Manual
   $itk_component(mode) select 0

   itk_component add pattern {
      iwidgets::radiobox $w.pattern -labeltext "Pattern size"
   }
   $itk_component(pattern) add normal -text Normal
   $itk_component(pattern) add full -text Full
   $itk_component(pattern) select 1

   pack $itk_component(probe) $itk_component(mode) $itk_component(pattern) \
      -side left -anchor n -padx 5
   
   set w $itk_interior
   itk_component add buttons {
      frame $w.buttons -borderwidth 2 -relief sunken
   }
   set w $itk_component(buttons)
   itk_component add start {
      button $w.start -text Start -command [itcl::code $this start]
   }
   itk_component add stop {
      button $w.stop -text Stop -state disabled \
            -command "[itcl::code $this finish]"
   }
   pack $itk_component(start) $itk_component(stop) -padx 50 -pady 10 \
         -fill x -side left -expand y
   pack $itk_component(options) $itk_component(buttons) -fill x \
      -expand yes

# Create all the actions needed to drive the calibration process.
   foreach p {1 2} {
      if { $p == 1 } {
         set pg 2
      } else {
         set pg 1
      }

# Setting up M2 and guiding.
      set action($p,setup) [seq::Action #auto tcs]
      $action($p,setup) set m2GuideConfig source PWFS${pg}
      $action($p,setup) set pwfs1Guide nodachopa on
      $action($p,setup) set pwfs1Guide nodbchopa off
      $action($p,setup) set pwfs1Guide nodachopb off
      $action($p,setup) set pwfs1Guide nodbchopb off
      $action($p,setup) set pwfs2Guide nodachopa on
      $action($p,setup) set pwfs2Guide nodbchopa off
      $action($p,setup) set pwfs2Guide nodachopb off
      $action($p,setup) set pwfs2Guide nodbchopb off

# Setting up for guiding the telescope.
      set action($p,guidesetup) [seq::Action #auto tcs \
            -waitvar [scope inposition${pg}(value)] \
            -oktest [itcl::code $this isinposition $pg]]
      $action($p,guidesetup) set pwfs${p}StopObserve
      $action($p,guidesetup) set pwfs${p}Park
      $action($p,guidesetup) set wfsGuideMode state off
      $action($p,guidesetup) set pwfs${p}StopObserve
      $action($p,guidesetup) set p${pg}Follow followState on
      $action($p,guidesetup) set poriginA x $xguide
      $action($p,guidesetup) set poriginA y $yguide
      $action($p,guidesetup) set poriginB x $xguide
      $action($p,guidesetup) set poriginB y $yguide
      $action($p,guidesetup) set poriginC x $xguide
      $action($p,guidesetup) set poriginC y $yguide

# Guiding the telescope.
      set action($p,guidetel) [seq::Action #auto tcs \
            -waitvar [scope inposition${pg}(value)] \
            -oktest [itcl::code $this isinposition $pg]]
      $action($p,guidetel) set m2Guide state on
      $action($p,guidetel) set pwfs${pg}Observe noexp -1
      $action($p,guidetel) set mountGuide mode on
      $action($p,guidetel) set mountGuide source SCS

# Set the arm following
      set action($p,probesetup) [seq::Action #auto tcs \
            -waitvar [scope inposition${p}(value)] \
            -oktest [itcl::code $this isinposition $p]]
      $action($p,probesetup) set mountGuide mode off
      $action($p,probesetup) set m2Guide state off
      $action($p,probesetup) set pwfs${pg}StopObserve
      $action($p,probesetup) set pwfs${pg}Park
      $action($p,probesetup) set p${p}Follow followState on
      $action($p,probesetup) set clearOffset vt PWFS${p}
      $action($p,probesetup) set clearOffset index all

# Guide the probe onto the star.
      set action($p,guideprobe) [seq::Action #auto tcs \
            -waitvar [scope inposition${p}(value)] \
            -oktest [itcl::code $this isinposition $p]]
      $action($p,guideprobe) set pwfs${p}Observe noexp -1
      $action($p,guideprobe) set wfsGuideMode state on
      $action($p,guideprobe) set wfsGuideMode probe PWFS${p}


# Chain the actions together.
      $action($p,setup) configure \
            -onok [namespace code "$action($p,guidesetup) start"]
      $action($p,guidesetup) configure \
            -onok [namespace code "$action($p,guidetel) start"]
      $action($p,guidetel) configure \
            -onok "after $guidetelwait [itcl::code $this probesetup $p]"
      $action($p,probesetup) configure -onok [itcl::code $this manual $p]
      $action($p,guideprobe) configure \
            -onok "after $guidewfswait [itcl::code $this log $p]"

# Monitor the probe arm inPosition status.
      sa agssad link p${p}InPosition [scope inposition${p}]
   }

# Cleanup action.
   set action(cleanup) [seq::Action #auto tcs]
   $action(cleanup) set pwfs1StopObserve
   $action(cleanup) set pwfs2StopObserve
   $action(cleanup) set pwfs1Park
   $action(cleanup) set pwfs2Park
   $action(cleanup) set wfsGuideMode state off

# Configure all the -onerror options.
   foreach act [array names action] {
      $action($act) configure \
            -onerror [itcl::code $this report $act]
   }

   eval itk_initialize $args
}

itcl::body ProbeCal::destructor {} {

# Delete all the action objects.
   foreach act [array names action] {
      itcl::delete object $action($act)
   }
}

itcl::body ProbeCal::start {} {

# Open a log file.
   set filename [tk_getSaveFile -parent $itk_interior \
         -title "Probe Calibration Log File"]

   if { ![string is space $filename] } {
      set logfd [open $filename {WRONLY CREAT TRUNC}]

# Disable the start button.
      $itk_component(start) configure -state disabled
      $itk_component(stop) configure -state normal

# Write the file header.
      set probe [$itk_component(probe) get]
      puts $logfd $probe
      set dt [clock format [clock seconds] -format "%Y %B %d %H:%M" -gmt 1]
      puts $logfd "# Probe geometry calibration started at $dt UTC"
      puts $logfd "#"
      puts $logfd "# Current settings of probe geometry model are:"
      puts $logfd "#"
      puts $logfd "#  Rotary table radius: [sa agssad get p${probe}RadiusRT]"
      puts $logfd "#  Probe arm radius:    [sa agssad get p${probe}RadiusPA]"
      puts $logfd "#  X translation:       [sa agssad get p${probe}XTranslation]"
      puts $logfd "#  Y translation:       [sa agssad get p${probe}YTranslation]"
      puts $logfd "#  Rotary table offset: [sa agssad get p${probe}TableOffset]"
      puts $logfd "#  Probe arm offset:    [sa agssad get p${probe}ArmOffset]"
      puts $logfd "#"
      puts $logfd "#      X          Y         RT        PA"
      flush $logfd

# Start at the begining of the pointing origin list.
      set poindex -1

# Initialise the pointing origin list.
      switch [$itk_component(pattern) get] {
         normal {
            switch $probe {
               1 {
                  set xlist {  0   0 100 100 200}
                  set ylist {100 200 100 200 100}
               }
               2 {
                  set xlist {  0   0 100 100 200}
                  set ylist {100 200 100 200 100}
               }
            }
         }
         full {
            switch $probe {
              1 {
                  set xlist {  0   0   0   0   0 \
                              50  50  50  50 \
                             100 100 100 100 \
                             150 150 150 150 \
                             200 200 200}
                  set ylist { 50 100 150 200 250 \
                              50 100 150 200 \
                              50 100 150 200 \
                              50 100 150 200 \
                              50 100 150}
              }
              2 {
                  set xlist {  0   0   0   0   0 \
                              50  50  50  50 \
                             100 100 100 100 \
                             150 150 150 150 \
                             200 200 200}
                  set ylist { 50 100 150 200 250 \
                              50 100 150 200 \
                              50 100 150 200 \
                              50 100 150 200 \
                              50 100 150}
              }
            }
         }
      }
      set polist {}
      foreach x $xlist y $ylist {lappend polist "$x $y"}
      foreach x $xlist y $ylist {lappend polist "$y -$x"}
      foreach x $xlist y $ylist {lappend polist "-$x -$y"}
      foreach x $xlist y $ylist {lappend polist "-$y $x"}

# Start the calibration process.
      $action($probe,setup) start
   }
}

itcl::body ProbeCal::isinposition {p} {
   set val [sa agssad get p${p}InPosition]
   return $val
}

itcl::body ProbeCal::report {act msg} {
   set reply [tk_messageBox -parent $itk_interior -icon error -type okcancel \
         -message $msg]
   if { [string equal $reply ok] } {
      uplevel #0 [$action($act) cget -onok]
   } else {
      finish
   }
}

itcl::body ProbeCal::probesetup {p} {

# Get the next pointing origin in the list.
   set po [lindex $polist [incr poindex]]

# Configure the follow action to go to the next position and start it.
   foreach {x y} $po {}
   $action($p,probesetup) set poriginA x $x
   $action($p,probesetup) set poriginA y $y
   $action($p,probesetup) set poriginB x $x
   $action($p,probesetup) set poriginB y $y
   $action($p,probesetup) set poriginC x $x
   $action($p,probesetup) set poriginC y $y
   $action($p,probesetup) start

# Update the window title to show how far we have got.
   wm title . "Point [expr {$poindex + 1}] of [llength $polist]"
}

itcl::body ProbeCal::log {p} {

# Log the probe data.
   set po [lindex $polist $poindex]
   set table [sa agssad get p${p}TableAngle]
   set arm [sa agssad get p${p}ArmAngle]
   puts $logfd [format "%10.2f %10.2f %10.2f %10.2f" \
         [lindex $po 0] [lindex $po 1] $table $arm]
   flush $logfd

# Start the next step.
   if { $poindex >= [llength $polist] - 1 } {
      $action(cleanup) start
      finish
   } else {
      $action($p,guidesetup) start
   }
}

itcl::body ProbeCal::finish {} {

# Cancel any outstanding actions.
   tcs cancel ""

# Kill any pending "after" events.
  foreach id [after info] {
     after cancel $id
  }

# Close the log file.
   puts $logfd ""
   set dt [clock format [clock seconds] -format "%Y %B %d %H:%M" -gmt 1]
   puts $logfd "# finished at $dt UTC"
   close $logfd

# Re-enable the start button.
   $itk_component(start) configure -state normal
   $itk_component(stop) configure -state disabled
}

itcl::body ProbeCal::manual {p} {
   cs pwfs${p}Observe set noexp -1
   cs pwfs${p}Observe post
   if { [string equal [$itk_component(mode) get] manual] } {
      tk_messageBox -parent $itk_interior -type ok -icon question \
            -message "Press Ok when the star is visible on the WFS"
   }
   $action($p,guideprobe) start
}
