#+
# Ptweak.itcl
#
# Implements the Ptweak class. A Ptweak object represents a single observation
# of a pointing update run. The "fit" class method calculates a new estimate
# of CE and CA and optionally IA from all the Ptweak objects that are enabled.
#
# D Terrett 29 May 1999
#
# Copyright CCLRC
#+

itcl::class Ptweak {

   constructor {} {}

   public method display
   public variable enable 1
   public variable ca
   public variable ce
   public variable el

   private variable pointobs
   private common fitca 0
   private common fitce 0
   private common fitia 0
   private common nfitted

   proc fit inclia
   proc commit {w inclia}
   private proc postparam
}

itcl::body Ptweak::constructor {} {

# Grab the net and guide values of CA and CE from the TCS.
   set ca [expr [sa net get ca] + [sa guide get ca]]
   set ce [expr [sa net get ce] + [sa guide get ce]]

# Grab the pointing observation data.
   set pointobs [sa tcssad get pointObs]

# Extract the elevation.
   set el [lindex $pointobs 6]
}

itcl::body Ptweak::display {} {
#+
# Formats the contents of the Ptweak object in a form suitable for display
# in the list box.
#-

# Format the RA/Dec as HH:MM and DD:MM.
   set h [expr [lindex $pointobs 2] * 3.8197186342]
   set m [expr round( ($h - int($h)) * 60)]
   set h [expr int($h)]
   set ra [format "%02d:%02d" $h $m]
   set d [expr [lindex $pointobs 3] * 57.2957795131]
   set m [expr round( abs( ($d - int($d)) * 60) )]
   set d [expr int($d)]
   set dec [format "%+03d:%02d" $d $m]

# Compute deviation from current fit in azimuth and elevation.
   set dce [expr $ce - $fitce]
   set dca [expr $ca - ($fitca + $fitia * cos($el))]
   return [format "%s %s %+6.1f %4.1f %+5.1f %+5.1f %5.1f" \
         $ra $dec [expr [lindex $pointobs 5] * 57.2957795131] \
         [expr [lindex $pointobs 6] * 57.2957795131] \
         $dca $dce [expr sqrt( $dca * $dca + $dce * $dce )]]

}

itcl::body Ptweak::fit inclia {
#+
# Computes a new fit for all the enabled observations and returns a list
# containg the mean values of ca, ce and ia and the rms of ca, ce and
# radius.
#-

# Initialise count of enabled stars.
   set nfitted 0

# Initialise sums.
   set sa 0.0
   set se 0.0
   set sa2 0.0
   set se2 0.0
   set scos2el 0.0
   set scosel 0.0
   set sacosel 0.0

# For each enabled Ptweak object...
   foreach obs [itcl::find objects -class Ptweak] {
      if { [$obs cget -enable] } {

# Keep a count of how many there are.
         incr nfitted

# Sum CA and CE.
         set sa [expr $sa + [$obs cget -ca]]
         set se [expr $se + [$obs cget -ce]]

# If we are fiting IA as well...
         if { $inclia } {

# Sum cosine squared of elevation, cosine of elevation and CA times cosine
# of elevation.
            set cosel [expr cos([$obs cget -el])]
            set scos2el [expr $scos2el + $cosel * $cosel]
            set scosel [expr $scosel + $cosel]
            set sacosel [expr $sacosel + [$obs cget -ca] * $cosel]
         }
      }
   }
   if { $inclia } {

# Compute determinant.
      set det [expr $nfitted * $scos2el - $scosel * $scosel]

# If the determinant is too small to yield a reasonably accurate result
# give up trying to compute IA.
      if { [expr abs($det)] < 1.0e-10 } {
         set inclia 0
      }
   }

# If there is at least one star...
   if { $nfitted > 0 } {

# Compute mean CE.
      set fitce [expr $se / $nfitted]
      if { $inclia } {

# Compute CA and IA...
         set fitca [expr ( $scos2el * $sa - $scosel * $sacosel ) / $det]
         set fitia [expr ( $nfitted * $sacosel - $sa * $scosel ) / $det]
      } else {

# or mean CA and set fitted IA to zero.
         set fitca [expr $sa / $nfitted]
         set fitia 0.0
      }

# Initialise sum of squared deviation from fitted CA and CE.
      set sca2 0.0
      set sce2 0.0
      foreach obs [itcl::find objects -class Ptweak] {
         if { [$obs cget -enable] } {

# Deviation in elevation.
            set dce [expr [$obs cget -ce] - $fitce]
            set sce2 [expr $sce2 + $dce * $dce]

# Deviation in azimuth.
            set dca [expr [$obs cget -ca] - \
                  ($fitca + $fitia * cos([$obs cget -el]))]
            set sca2 [expr $sca2 + $dca * $dca]
         }
      }

# Compute root mean squared deviation.
      set rmsca [expr sqrt($sca2 / $nfitted)]
      set rmsce [expr sqrt($sce2 / $nfitted)]
      set rmsr [expr sqrt($rmsce * $rmsce + $rmsca * $rmsca)]

# Return result of fit.
      if { $inclia } {
         return [format "%5.2f %5.2f %5.2f %5.2f %5.2f %5.2f" \
               $fitca $fitce $fitia $rmsca $rmsce $rmsr]
      } else {
         return [format "%5.2f %5.2f {} %5.2f %5.2f %5.2f" \
               $fitca $fitce $rmsca $rmsce $rmsr] 
      }
   } else {
      return [list "" "" "" "" "" ""]
   }
}

itcl::body Ptweak::commit {w inclia} {
#+
# Commits (i.e. modifies the TCS session pointing model) the fitted values
# of CA and CE and, optionally, IA.
#-

# Get the current Session values of CA, CE and IA.
   set curce [sa session get ce]
   set curca [sa session get ca]
   set curia [sa session get ia]

# Create confirmation dialog box.
   iwidgets::messagedialog $w.md -title "Commit Error" -bitmap error \
         -modality application -text "No stars to fit" 
   $w.md hide Help
   $w.md component message configure -wraplength 500 -justify left

   if { $nfitted < 1 } {
      $w.md center
      $w.md hide Cancel
      $w.md activate
      destroy $w.md
      return
   }

# Build a text string that displays the new model.
   set text [format "The current model is: CA = %.2f, CE = %.2f, IA = %.2f." \
         $curca $curce $curia]
   set text [format "%s The new model will be CA = %.2f, CE = %.2f" \
         $text $fitca $fitce]
   if { $inclia } {
      set text [format "%s, IA = %.2f." $text [expr $curia + $fitia]]
   }
   set text "$text Do you want to update the session pointing model\
         with these values?"

   $w.md configure -title "Commit Confirmation" -bitmap questhead -text $text
   $w.md buttonconfigure OK -text Yes 
   $w.md buttonconfigure Cancel -text No 
   $w.md center
   if { ![$w.md activate] } {
      destroy $w.md
      return
   }
   if { $inclia && ( $nfitted < 5 ) || $nfitted < 4 } {
      $w.md configure -text "Only $nfitted stars fitted\
         Do you want to continue?" -bitmap warning
      $w.md center
      if { ![$w.md activate] } {
         destroy $w.md
         return
      }
   }
   if { abs($fitca - $curca) > 30.0 || abs($fitce - $curce) > 30.0 ||
         ( $inclia && abs($fitia) > 30.0 ) } {
      $w.md configure -text "The fit contains alarmingly large adjustments\
         Do you want to continue?" -bitmap warning
      $w.md center
      if { ![$w.md activate] } {
         destroy $w.md
         return
      }
   }
   destroy $w.md

# Set the parameter set to "Session".
   cs pointParam set level Session

# Set CE.
   cs pointParam set name CE
   cs pointParam set value $fitce
   postparam

# Set CA
   cs pointParam set name CA
   cs pointParam set value $fitca
   postparam

# Set IA if requested.
   if { $inclia } {
      cs pointParam set name IA
      cs pointParam set value [expr $curia + $fitia]
      postparam
   }

# Set the local CA & CE to zero.
   cs pointParam set level Local
   cs pointParam set name CE
   cs pointParam set value 0.0
   postparam
   cs pointParam set name CA
   postparam

# Zero the guiding offsets.
   cs zeroGuide set mark mark
      if [catch {cs zeroGuide post}] {
      set info [sa apply get mess value]
      error "zeroGuide command failed: \"$info\""
   }
}

itcl::body Ptweak::postparam {} {
   if [catch {cs pointParam post}] {
      set info [sa apply get mess value]
      error "pointParam command failed: \"$info\""
   }
}
