#+
# StarSelect <- itk::Widget
#
# A StarSelect widget is the main interface of the starselect application.
#
# D Terrett 26 September 2000
#
# Copyright CCLRC
#+

itcl::class StarSelect {
   inherit itk::Widget

   constructor {args} {}

   private method selectstar {index}
   private method loadposition {ra dec}
   private method slew
   private method onerror {msg}

   private variable SlewAction
   private variable StarCat
}

itcl::body StarSelect::constructor {args} {

# Source entry widget
   itk_component add sourceentry {
      SourceEntry $itk_interior.sourceentry
   }

# Skyplot window.
   itk_component add azelplot {
      AzElPlot $itk_interior.azelplot \
            -selectioncommand [itcl::code $this selectstar] \
            -hitcommand [itcl::code $this loadposition]
   }
 
# Create an empty star catalogue.
   set StarCat [Catalogue #auto $itk_component(azelplot)]

# Create the Action object that slews the telescope.
   set SlewAction [seq::Action #auto tcs -onerror [itcl::code $this onerror]]

# Create menus.
   itk_component add menus {
      iwidgets::menubar $itk_interior.menus -menubuttons {
         menubutton file -text File -underline 0 -menu {
            options -tearoff false
            command load -label "Load catalogue" -underline 0 \
                  -command "[namespace code "$StarCat load"]"
            command exit -label Exit -underline 1 \
                  -command exit
         }
         menubutton view -text View -underline 0 -menu {
            options -tearoff false
            command catalog -label "Catalog" -underline 0 \
                  -command "[namespace code "$StarCat view"]"
         }
      }
   }

   pack $itk_component(menus) -anchor w -fill x -expand y
   pack $itk_component(sourceentry) -pady 5 -padx 5
   pack $itk_component(azelplot)

   itk_component add -private buttonframe {
      frame $itk_interior.buttonframe
   }
   pack $itk_component(buttonframe) -fill x -expand yes -pady 5
   set w $itk_component(buttonframe)

   itk_component add slew {
      button $w.slew -text "Slew to target" -underline 0 \
            -command "[itcl::code $this slew]"
   }
   bind all <s> "$itk_component(slew) invoke"

   pack $itk_component(slew) -side left -expand yes

# - Stop keypresses from triggering button bindings
   bind Entry <Key> "[bind Entry <Key>]; break"

   eval itk_initialize $args
}

itcl::body StarSelect::selectstar {index} {

   $itk_component(sourceentry) clear
   foreach {objname ra dec frame equinox epoch pmra pmdec parallax rv comment} \
         [$StarCat extract $index] {}
   [$itk_component(sourceentry) component objname] insert end $objname
   [$itk_component(sourceentry) component ra] insert end $ra
   [$itk_component(sourceentry) component dec] insert end $dec
   [$itk_component(sourceentry) component frame] insert end $frame
   [$itk_component(sourceentry) component equinox] insert end $equinox
   [$itk_component(sourceentry) component epoch] insert end $epoch
   [$itk_component(sourceentry) component pmra] insert end $pmra
   [$itk_component(sourceentry) component pmdec] insert end $pmdec
   [$itk_component(sourceentry) component parallax] insert end $parallax
   [$itk_component(sourceentry) component rv] insert end $rv
   [$itk_component(sourceentry) component comment] configure -text $comment

   $StarCat select $index
   return
}

itcl::body StarSelect::loadposition {ra dec} {

# Format the RA/Dec as HH:MM and DD
   set ram [expr round($ra*229.18)]
   if { $ram < 0 } {set ram [expr $ram + 1440]}
   set rah [expr round(floor($ram / 60.0))]
   set ram [expr round($ram - $rah * 60.0)]
   set decm [expr round($dec*3437.746)]
   set dech [expr round(floor($decm / 60.0))]
   set decm [expr round($decm - $dech * 60.0)]

# Load the RA, Dec and frame source entry widgets and clear the rest.
   $itk_component(sourceentry) clear
   [$itk_component(sourceentry) component ra] insert end \
         [format %02d:%02d $rah $ram]
   [$itk_component(sourceentry) component dec] insert end \
         [format %0+3d:%02d $dech $decm]
   [$itk_component(sourceentry) component frame] insert end APPT
}

itcl::body StarSelect::slew {} {

   $SlewAction set sourceA objName \
         [[$itk_component(sourceentry) component objname] get]
   $SlewAction set sourceA system \
         [[$itk_component(sourceentry) component frame] get]
   $SlewAction set sourceA theta1 \
         [[$itk_component(sourceentry) component ra] get]
   $SlewAction set sourceA theta2 \
         [[$itk_component(sourceentry) component dec] get]
   $SlewAction set sourceA equinox \
         [[$itk_component(sourceentry) component equinox] get]
   $SlewAction set sourceA epoch \
         [[$itk_component(sourceentry) component epoch] get]
   $SlewAction set sourceA parallax \
         [[$itk_component(sourceentry) component parallax] get]
   $SlewAction set sourceA dtheta1 \
         [[$itk_component(sourceentry) component pmra] get]
   $SlewAction set sourceA dtheta2 \
         [[$itk_component(sourceentry) component pmdec] get]
   $SlewAction set sourceA rv \
         [[$itk_component(sourceentry) component rv] get]
   $SlewAction set slew pointing off

   $SlewAction start
}

itcl::body StarSelect::onerror {msg} {
   tk_messageBox -parent $itk_interior -icon error -type ok \
      -message "Slew failed. TCS reports \"$msg\""
}
