#+
#  DomeView <- itk:Widget 
#
#  Plots a view of the dome on a canvas.
#
#  Options:
#           none
#
#  Methods:
#           update          Updates the view with the current state of the
#                           telescope.
#
#  D Terrett 13 August 1998
#
#  Copyright CCLRC
#-

itcl::class DomeView {
   inherit itk::Widget

   constructor args {}

   public method update
}

itk::usual DomeView {
   keep -background -cursor -highlightcolor -highlightthickness \
         -insertbackground -insertborderwidth -insertwidth -insertontime \
         -insertofftime -selectbackground -selectborderwidth -selectforeground
}

itcl::body DomeView::constructor args {

   itk_component add domeview {
      canvas $itk_interior.domeview -width 340 -height 340
   }

   $itk_component(domeview) create domeview 170 170 -tags domeview

   pack $itk_component(domeview)

   eval itk_initialize $args
}

itcl::body DomeView::update {} {
   $itk_component(domeview) itemconfigure domeview -display 1
}
