#+
#  GraphicPanel <- Panel
#
#  Implements the GraphicPanel widget. A Panel widget with a GraphicsDisplay
#  widget packed into its interior
#
#  Options:
#           none
#
#  Methods:
#           update      Calls the update method of the GraphicsDisplay widget.
#
#
#  D Terrett 27 April 1999
#
#  Copyright CCLRC
#+

itcl::class GraphicPanel {
   inherit Panel

   constructor args {}

   public method update 
}

itk::usual GraphicPanel {
   keep -background -cursor
}

itcl::body GraphicPanel::constructor args {

# Withdraw the top level window so that we don't see geometry changes 
# while waiting for sa to connect.
   set toplevel [winfo toplevel $itk_interior]
   wm withdraw $toplevel

   itk_component add control {
      GraphicDisplay $itk_interior.control
   } {
      usual
      ignore -highlightcolor
      ignore -selectbackground
      ignore -selectforeground
      ignore -insertbackground
      rename -font -grahicsfont graphicsFont Font
   }
   setWidgetColors "$itk_component(menubar) $itk_component(control)" \
         $itk_option(-background) $itk_option(-foreground)

   pack $itk_component(control) -fill both -expand y

   set itk_option(-windows) $itk_component(control)

   eval itk_initialize $args

   wm deiconify $toplevel
}

itcl::body GraphicPanel::update {} {

# Update the control component.
   $itk_component(control) update
}
