#+
#  GraphicDisplay <- itk:Widget
#
#  Plots a view state of the telescope.
#
#  Options:
#           none
#
#  Methods:
#           update          Updates the view with the current state of the
#                           telescope.
#
#  D Terrett 18 February 2000
#
#  Copyright CCLRC
#-

itcl::class GraphicDisplay {
   inherit itk::Widget

   constructor args {}

   public method update

   private variable Vignette 0
}

itk::usual GraphicDisplay {
   keep -background -cursor -foreground -font -highlightcolor \
        -highlightthickness -highlightcolor -highlightthickness \
        -insertbackground -insertborderwidth -insertwidth -insertontime \
        -insertofftime -selectbackground -selectborderwidth -selectforeground
   keep -aofold -aopresent -centralbaffle -deployablebaffle -holecover -hrwfs \
        -m1cover -m2sstate -port1label -port2label -port3label -port5label \
        -scfold 
}

itcl::body GraphicDisplay::constructor args {

# Divide the window into 3 vertically
   itk_component add col1 {
      frame $itk_interior.col1
   }
   itk_component add col2 {
      frame $itk_interior.col2
   }
   itk_component add col3 {
      frame $itk_interior.col3
   }
   itk_component add col4 {
      frame $itk_interior.col4
   }
   pack $itk_component(col1) $itk_component(col2) $itk_component(col3) \
         $itk_component(col4) -side left -fill both -expand y

# Put the dome view and the elevation view in the left column.
   set w $itk_component(col1)
   itk_component add domeview {
      DomeView $w.domeview
   }
   itk_component add elview {
      ElevationView $w.elview
   }
   pack $itk_component(domeview) $itk_component(elview) -expand y

# Put the wrap view in the middle.
   set w $itk_component(col2)
   itk_component add wrapview {
      WrapView $w.wrapview
   }
   pack $itk_component(wrapview) -expand y

# Put the optics view to the right.
   set w $itk_component(col3)
   itk_component add opticsview {
      OpticsView $w.opticsview
   }
   pack $itk_component(opticsview) -expand y

# Probe views in the last column.
   set w $itk_component(col4)
   itk_component add probe1 {
      ProbeView $w.probe1 -probe p1
   }
   itk_component add p1label {
      label $w.p1label -text "PWFS1"
   }
   itk_component add probe2 {
      ProbeView $w.probe2 -probe p2
   }
   itk_component add p2label {
      label $w.p2label -text "PWFS2"
   }
   pack $itk_component(p2label) $itk_component(probe2) \
         $itk_component(p1label) $itk_component(probe1) -side bottom

   eval itk_initialize $args
}

itcl::body GraphicDisplay::update {} {
#+
#  Updates the display items.
#-

# Update the widgets.
   $itk_component(domeview) update
   $itk_component(elview) update
   $itk_component(wrapview) update
   $itk_component(probe1) update
   $itk_component(probe2) update

   set v [sadVal tcssad domeVignette -1]
   if { $v > 0.0 && $Vignette == 0 } {
      $itk_component(opticsview) configure -vignette 1
      set Vignette 1
   } elseif { $v == 0 && $Vignette == 1 } {
      $itk_component(opticsview) configure -vignette 0
      set Vignette 0
   }
   set m2sfollow [isFollowing m2ssad followS]
   set m2sinpos [isInPosition m2ssad inPosition]

   if { $m2sfollow } {
      if { $m2sinpos } {
         $itk_component(opticsview) configure -m2sstate INPOSITION
      } else {
         $itk_component(opticsview) configure -m2sstate FOLLOWING
      }
   } else {
      $itk_component(opticsview) configure -m2sstate OFF
   }
   $itk_component(opticsview) configure \
         -deployablebaffle [sa m2ssad get deployBafflePos value] \
         -centralbaffle [sa m2ssad get centralBafflePos value] \
         -scfold [sa agssad get sfName value] \
         -aofold [sa agssad get aoName value] \
         -hrwfs [sa agssad get hwName value] \
         -m1cover [sa gissad get m1cover value] \
         -holecover [sa gissad get m1inst value]
   $itk_component(opticsview) update
}
