#+
#  GraphicDisplay <- itk:Widget
#
#  Plots a view state of the telescope.
#
#  Options:
#           none
#
#  Methods:
#           update          Updates the view with the current state of the
#                           telescope.
#
#  D Terrett 24 June 2003
#
#  Copyright CCLRC
#-

itcl::class GraphicDisplay {
   inherit itk::Widget
   constructor args {}
   public {
      method update {}
   }
   private {
      variable Vignette 0
      variable flash 0
   }
}

itk::usual GraphicDisplay {
   keep -background -cursor -foreground -font -highlightcolor \
        -highlightthickness -highlightcolor -highlightthickness \
        -insertbackground -insertborderwidth -insertwidth -insertontime \
        -insertofftime -selectbackground -selectborderwidth -selectforeground
}

itcl::body GraphicDisplay::constructor args {

# Divide the window into 3 vertically
   itk_component add col1 {
      frame $itk_interior.col1
   }
   itk_component add col2 {
      frame $itk_interior.col2
   }
   itk_component add col3 {
      frame $itk_interior.col3
   }
   itk_component add col4 {
      frame $itk_interior.col4
   }
   pack $itk_component(col1) $itk_component(col2) $itk_component(col3) \
         $itk_component(col4) -side left -fill both -expand y -anchor n

# Put the dome view and the elevation view in the left column.
   set w $itk_component(col1)
   itk_component add domeview {
      DomeView $w.domeview
   }
   itk_component add elview {
      ElevationView $w.elview
   }
   pack $itk_component(domeview) $itk_component(elview) -expand y

# Put the wrap view in the middle.
   set w $itk_component(col2)
   itk_component add wrapview {
      WrapView $w.wrapview
   }
   pack $itk_component(wrapview) -expand y

# Put the optics view to the right.
   set w $itk_component(col3)
   itk_component add opticsview {
      OpticsView $w.opticsview
   }
   pack $itk_component(opticsview) -expand y

# M2 setup and probe views in the last column.
   set w $itk_component(col4)
   itk_component add m2setup {
      frame $w.m2setup -borderwidth 2 -relief ridge
   }
   set w $itk_component(m2setup)
   itk_component add m2lab {
      label $w.m2lab -text "M2 configuration"
   }
   itk_component add m2p1lab {
      label $w.m2p1lab -text PWFS1: -anchor e
   }
   itk_component add m2p1 {
      label $w.m2p1 -relief sunken
   } {
      usual
      ignore -font
   }
   itk_component add m2p2lab {
      label $w.m2p2lab -text PWFS2: -anchor e
   }
   itk_component add m2p2 {
      label $w.m2p2 -relief sunken
   } {
      usual
      ignore -font
   }
   itk_component add m2oilab {
      label $w.m2oilab -text OIWFS: -anchor e
   }
   itk_component add m2oi {
      label $w.m2oi -relief sunken
   } {
      usual
      ignore -font
   }
   itk_component add m2aolab {
      label $w.m2aolab -text GAOS: -anchor e
   }
   itk_component add m2ao {
      label $w.m2ao -relief sunken
   } {
      usual
      ignore -font
   }
   grid $itk_component(m2lab) -
   grid $itk_component(m2p1lab) $itk_component(m2p1) -pady 1 -sticky e
   grid $itk_component(m2p2lab) $itk_component(m2p2) -pady 1 -sticky e
   grid $itk_component(m2oilab) $itk_component(m2oi) -pady 1 -sticky e
   grid $itk_component(m2aolab) $itk_component(m2ao) -pady 1 -sticky e
   grid configure $itk_component(m2p1) $itk_component(m2p2) \
         $itk_component(m2oi) $itk_component(m2ao) -stick ew -padx 2
   grid columnconfigure $itk_component(m2setup) 1 -weight 1

# OIWFS
   set w $itk_component(col4)
   itk_component add oiwfs {
      frame $w.oiwfs -borderwidth 2 -relief ridge
   }
   set w $itk_component(oiwfs)
   itk_component add oiname {
      label $w.oiname
   }
   itk_component add oilabel {
      label $w.oilabel -text "OIWFS"
   }
   itk_component add oix {
      StatusField $w.oix -labeltext x -entryborder 2 -entryrelief ridge \
            -width 6 -anchor e
   }
   itk_component add oiy {
      StatusField $w.oiy -labeltext y -entryborder 2 -entryrelief ridge \
            -width 6 -anchor e
   }
   itk_component add oiwavel {
      label $w.oiwavel
   }
   pack $itk_component(oiname) $itk_component(oilabel) -padx 5
   pack $itk_component(oix) $itk_component(oiy) $itk_component(oiwavel) \
         -padx 5 -pady 3

# ALTAIR WFS.
   set w $itk_component(col4)
   itk_component add aowfs {
      frame $w.aowfs -borderwidth 2 -relief ridge
   }
   set w $itk_component(aowfs)
   itk_component add aolabel {
      label $w.aolabel -text "ALTAIR"
   }
   itk_component add aox {
      StatusField $w.aox -labeltext x -entryborder 2 -entryrelief ridge \
            -width 6 -anchor e
   }
   itk_component add aoy {
      StatusField $w.aoy -labeltext y -entryborder 2 -entryrelief ridge \
            -width 6 -anchor e
   }
   itk_component add aowavel {
      label $w.aowavel
   }
   pack $itk_component(aolabel) -padx 5
   pack $itk_component(aowavel) $itk_component(aoy) $itk_component(aox) \
         -padx 5 -pady 3 -side bottom

# PWFS1.
   set w $itk_component(col4)
   itk_component add pwfs1 {
      frame $w.pwfs1 -borderwidth 2 -relief ridge
   }
   set w $itk_component(pwfs1)
   itk_component add probe1 {
      ProbeView $w.probe1 -probe p1
   }
   itk_component add p1label {
      label $w.p1label -text "PWFS1"
   }
   itk_component add p1wavel {
      label $w.p1wavel
   }
   pack $itk_component(p1label) $itk_component(probe1) $itk_component(p1wavel)

# PWFS2.
   set w $itk_component(col4)
   itk_component add pwfs2 {
      frame $w.pwfs2 -borderwidth 2 -relief ridge
   }
   set w $itk_component(pwfs2)
   itk_component add probe2 {
      ProbeView $w.probe2 -probe p2
   }
   itk_component add p2label {
      label $w.p2label -text "PWFS2"
   }
   itk_component add p2wavel {
      label $w.p2wavel
   }
   pack $itk_component(p2label) $itk_component(probe2) $itk_component(p2wavel)

   grid $itk_component(m2setup) - -sticky ew -padx 5 -pady 5
   grid $itk_component(oiwfs) $itk_component(aowfs) -padx 5 -pady 5 -sticky ns
   grid $itk_component(pwfs1) $itk_component(pwfs2) -padx 5 -pady 5

# Configure the ISS port numbers and AO.
   $itk_component(opticsview) configure -portAnumber 1 
   switch [sa tcssad get name] {
      Gemini-North {
         $itk_component(opticsview) configure -portBnumber 4
         $itk_component(opticsview) configure -portCnumber 3
         $itk_component(opticsview) configure -portDnumber 2
         $itk_component(opticsview) configure -portEnumber 5
         $itk_component(opticsview) configure -aopresent 1
      }
      Gemini-South {
         $itk_component(opticsview) configure -portBnumber 4
         $itk_component(opticsview) configure -portCnumber 3
         $itk_component(opticsview) configure -portDnumber 2
         $itk_component(opticsview) configure -portEnumber 5
      }
   }

   eval itk_initialize $args
}

itcl::body GraphicDisplay::update {} {
#+
#  Updates the display items.
#-
   set flash [expr { $flash ? 0 : 1 }]

# Update the widgets.
   $itk_component(domeview) update
   $itk_component(elview) update
   $itk_component(wrapview) update
   $itk_component(probe1) update
   $itk_component(probe2) update

# Determine whether there is any vignetting from the enclosure.
   set v [sadVal tcssad domeVignette -1]
   if { $v > 0.0 && $Vignette == 0 } {
      $itk_component(opticsview) configure -vignette 1
      set Vignette 1
   } elseif { $v == 0 && $Vignette == 1 } {
      $itk_component(opticsview) configure -vignette 0
      set Vignette 0
   }

# Determine the status of M2.
   set m2sfollow [isFollowing m2ssad followS]
   set m2sinpos [isInPosition m2ssad inPosition]

   if { $m2sfollow } {
      if { $m2sinpos } {
         $itk_component(opticsview) configure -m2sstate INPOSITION
      } else {
         $itk_component(opticsview) configure -m2sstate FOLLOWING
      }
   } else {
      $itk_component(opticsview) configure -m2sstate OFF
   }

# Determine the state of M1.
   if { [string equal [sa pcssad get apssMsg] "APSS inflated"] && \
         [string equal [sa pcssad get aosMsg] "aO sub-system is ON"] && \
         [string equal [sa pcssad get pssInPosn] TRUE] && \
         [string equal [sa pcssad get pssOn] ON]  && \
         [string equal [sa tcssad get m1FigUpdatesFlag] On] } {
      if { [sa pcssad get aoMoving] < 10.0 } {
         $itk_component(opticsview) configure -pcsstate OK
      } else {
         $itk_component(opticsview) configure -pcsstate MOVING
      }
   } else {
      $itk_component(opticsview) configure -pcsstate OFF
   }

# Configure the science fold position.
   set sfmoving 0
   set lin [sadVal agssad sfLin 1000.0]
   if { $lin == 1000.0 } {
      $itk_component(opticsview) configure -scfold UNKNOWN
   } elseif { $lin < -300.0 } {
      $itk_component(opticsview) configure -scfold PARK
   } else {
      if { $lin < -10.0 } {
         set sfmoving 1
      }
      set tilt [sadVal agssad sfTilt 0.0]
      set rot [sadVal agssad sfRot 0.0]
      if { $tilt < 20.0 && $tilt > -20.0 } {
         if { $rot > 90.0 } {
            set sfpos DE
            if { $rot < 130.0 || $rot > 140.0 } {
               set sfmoving 1
            }
         } elseif { $rot > 0.0 } {
            set sfpos CD
            if { $rot < 40.0 || $rot > 50.0 } {
               set sfmoving 1
            }
         } elseif { $rot > -90.0 } {
            set sfpos CB
            if { $rot < -50.0 || $rot > -40.0 } {
               set sfmoving 1
            }
         } else {
            set sfpos BE
            if { $rot < -140.0 || $rot > -130.0 } {
               set sfmoving 1
            }
         }
      } else {
         if { $tilt > 20.0 } {
            set sfpos U
            if { $tilt > 47.5 || $tilt < 42.5 } {
               set sfmoving 1
            }
         } else {
            set sfpos A
            if { $tilt < -47.5 || $tilt > -42.5 } {
               set sfmoving 1
            }
         }
         if { $rot > 135.0 } {
            append sfpos E
            if { $rot < 175.0 || $rot > 185.0 } {
               set sfmoving 1
            }
         } elseif { $rot > 45.0 } {
            append sfpos D
            if { $rot < 85.0 || $rot > 95.0 } {
               set sfmoving 1
            }
         } elseif { $rot > -45.0 } {
            append sfpos C
            if { $rot < -5.0 || $rot > 5.0 } {
               set sfmoving 1
            }
         } elseif { $rot > -135.0 } {
            append sfpos B
            if { $rot < -95.0 || $rot > -85.0 } {
               set sfmoving 1
            }
         } else {
            append sfpos E
            if { $rot < -185.0 || $rot > -175.0 } {
               set sfmoving 1
            }
         }
      }
      if { $sfmoving } {
         if { $flash } {
            $itk_component(opticsview) configure -scfold MOVING
         } else {
            $itk_component(opticsview) configure -scfold $sfpos
         }
      } else {
         $itk_component(opticsview) configure -scfold $sfpos
      }
   }

# Determine if there is light from GCAL.
   set calunit [expr { [sa gcalsad get shutter value] == "OPEN" ||
         [sa gcalsad get ArLampState value] == "ON" ||
         [sa gcalsad get KrLampState value] == "ON" ||
         [sa gcalsad get CuArLampState value] == "ON" ||
         [sa gcalsad get ThArLampState value] == "ON" ||
         [sa gcalsad get QHLampState value] == "ON" }]

# Configure GPOL
   if { [sa gpolsad get upperParkSwitch] == "OPEN" } {
      if { [sa gpolsad get upperBeamSwitch] == "CLOSED" } {
         $itk_component(opticsview) configure -gpolustate IN
      } else {
         if { $flash } {
            $itk_component(opticsview) configure -gpolustate IN
         } else {
            $itk_component(opticsview) configure -gpolustate OUT
         }
      }
   } else {
      $itk_component(opticsview) configure -gpolustate OUT
   }
   if { [sa gpolsad get middleParkSwitch] == "OPEN" } {
      if { [sa gpolsad get middleBeamSwitch] == "CLOSED" } {
         $itk_component(opticsview) configure -gpolmstate IN
      } else {
         if { $flash } {
            $itk_component(opticsview) configure -gpolmstate IN
         } else {
            $itk_component(opticsview) configure -gpolmstate OUT
         }
      }
   } else {
      $itk_component(opticsview) configure -gpolmstate OUT
   }
   if { [sa gpolsad get lowerParkSwitch] == "OPEN" } {
      if { [sa gpolsad get lowerBeamSwitch] == "CLOSED" } {
         $itk_component(opticsview) configure -gpollstate IN
      } else {
         if { $flash } {
            $itk_component(opticsview) configure -gpollstate IN
         } else {
            $itk_component(opticsview) configure -gpollstate OUT
         }
      }
   } else {
      $itk_component(opticsview) configure -gpollstate OUT
   }

# Configure the light path.
   $itk_component(opticsview) configure \
         -deployablebaffle [sa m2ssad get deployBafflePos value] \
         -centralbaffle [sa m2ssad get centralBafflePos value] \
         -aofold [sa agssad get aoName value] \
         -aoentrance [sa aossad get entShutterOpen value] \
         -aoexit [sa aossad get exitShutterOpen value] \
         -hrwfs [sa agssad get hwName value] \
         -m1cover [sa gissad get m1cover value] \
         -holecover [sa gissad get m1inst value] \
         -calunit $calunit
   $itk_component(opticsview) update

# Update the M2 setup.
   $itk_component(m2p1) configure -text [sa m2ssad get p1GuideConfig]
   $itk_component(m2p2) configure -text [sa m2ssad get p2GuideConfig]
   $itk_component(m2oi) configure -text [sa m2ssad get oiGuideConfig]
   $itk_component(m2ao) configure -text [sa m2ssad get aoGuideConfig]

# Set the colour of the OIWFS according to the follow and in position state.
   if { [isFollowing agssad oiFollowS] } {
      if { [isInPosition agssad oiInPosition] } {
         $itk_component(oix) configure -status ok
         $itk_component(oiy) configure -status ok
      } else {
         $itk_component(oix) configure -status warning
         $itk_component(oiy) configure -status warning
      }
   } else {
      $itk_component(oix) configure -status error
      $itk_component(oiy) configure -status error
   }

# Set the colour of the ALTAIR WFS according to the follow and in position 
# state.
   if { [isFollowing aossad followS] } {
      if { [isInPosition aossad inPosition] } {
         $itk_component(aox) configure -status ok
         $itk_component(aoy) configure -status ok
      } else {
         $itk_component(aox) configure -status warning
         $itk_component(aoy) configure -status warning
      }
   } else {
      $itk_component(aox) configure -status error
      $itk_component(aoy) configure -status error
   }

# Update the OIWFS name and position.
   $itk_component(oiname) configure -text [sa agssad get oiwfsName]
   $itk_component(oix) configure -text [format %.2f [sadVal agssad oiX 0.0]]
   $itk_component(oiy) configure -text [format %.2f [sadVal agssad oiY 0.0]]

# Update the ALTAIR position.
   $itk_component(aox) configure \
         -text [format %.2f [sadVal aossad wfsXPosition 0.0]]
   $itk_component(aoy) configure \
         -text [format %.2f [sadVal aossad wfsYPosition 0.0]]

# Update the guiding wavelengths.
   set wavel [sadVal tcssad pwfs1Wavelength ""]
   if { $wavel != "" } {
      $itk_component(p1wavel) configure -text "[expr {$wavel / 10000.0}] mu"
   }
   set wavel [sadVal tcssad pwfs2Wavelength ""]
   if { $wavel != "" } {
      $itk_component(p2wavel) configure -text "[expr {$wavel / 10000.0}] mu"
   }
   if { $wavel != "" } {
      $itk_component(aowavel) configure -text "[expr {$wavel / 10000.0}] mu"
   }
   set wavel [sadVal tcssad oiwfsWavelength ""]
   if { $wavel != "" } {
      $itk_component(oiwavel) configure -text "[expr {$wavel / 10000.0}] mu"
   }


# Set the ISS port labels.
   $itk_component(opticsview) configure \
         -portAlabel [sa agssad get port1Label]

   switch [sa tcssad get name] {
      Gemini-North {
         $itk_component(opticsview) configure \
               -portBlabel [sa agssad get port4Label] \
               -portClabel [sa agssad get port3Label] \
               -portDlabel [sa agssad get port2Label] \
               -portElabel [sa agssad get port5Label] 
      }
      Gemini-South {
         $itk_component(opticsview) configure \
               -portBlabel [sa agssad get port4Label] \
               -portClabel [sa agssad get port3Label] \
               -portDlabel [sa agssad get port2Label] \
               -portElabel [sa agssad get port5Label] 
      }
   }
}
