#+
#  GraphicDisplay <- itk:Widget
#
#  Plots a view state of the telescope.
#
#  Options:
#           none
#
#  Methods:
#           update          Updates the view with the current state of the
#                           telescope.
#
#  D Terrett 1 November 2001
#
#  Copyright CCLRC
#-

itcl::class GraphicDisplay {
   inherit itk::Widget
   constructor args {}
   public {
      method update {}
   }
   private {
      variable Vignette 0
      variable flash 0
   }
}

itk::usual GraphicDisplay {
   keep -background -cursor -foreground -font -highlightcolor \
        -highlightthickness -highlightcolor -highlightthickness \
        -insertbackground -insertborderwidth -insertwidth -insertontime \
        -insertofftime -selectbackground -selectborderwidth -selectforeground
}

itcl::body GraphicDisplay::constructor args {

# Divide the window into 3 vertically
   itk_component add col1 {
      frame $itk_interior.col1
   }
   itk_component add col2 {
      frame $itk_interior.col2
   }
   itk_component add col3 {
      frame $itk_interior.col3
   }
   itk_component add col4 {
      frame $itk_interior.col4
   }
   pack $itk_component(col1) $itk_component(col2) $itk_component(col3) \
         $itk_component(col4) -side left -fill both -expand y

# Put the dome view and the elevation view in the left column.
   set w $itk_component(col1)
   itk_component add domeview {
      DomeView $w.domeview
   }
   itk_component add elview {
      ElevationView $w.elview
   }
   pack $itk_component(domeview) $itk_component(elview) -expand y

# Put the wrap view in the middle.
   set w $itk_component(col2)
   itk_component add wrapview {
      WrapView $w.wrapview
   }
   pack $itk_component(wrapview) -expand y

# Put the optics view to the right.
   set w $itk_component(col3)
   itk_component add opticsview {
      OpticsView $w.opticsview
   }
   pack $itk_component(opticsview) -expand y

# Probe views in the last column.
   set w $itk_component(col4)
   itk_component add oilabel {
      label $w.oilabel -text "OIWFS"
   }
   itk_component add oix {
      StatusField $w.oix -labeltext x -entryborder 2 -entryrelief ridge \
            -width 6 -anchor e
   }
   itk_component add oiy {
      StatusField $w.oiy -labeltext y -entryborder 2 -entryrelief ridge \
            -width 6 -anchor e
   }
   itk_component add probe1 {
      ProbeView $w.probe1 -probe p1
   }
   itk_component add p1label {
      label $w.p1label -text "PWFS1"
   }
   itk_component add probe2 {
      ProbeView $w.probe2 -probe p2
   }
   itk_component add p2label {
      label $w.p2label -text "PWFS2"
   }
   pack $itk_component(p2label) $itk_component(probe2) \
        $itk_component(p1label) $itk_component(probe1) \
        $itk_component(oilabel) $itk_component(oiy) \
        $itk_component(oix) -side bottom 

# Configure the ISS port numbers.
   $itk_component(opticsview) configure -portAnumber 1 
   switch [sa tcssad get name] {
      Gemini-North {
         $itk_component(opticsview) configure -portBnumber 4
         $itk_component(opticsview) configure -portCnumber 3
         $itk_component(opticsview) configure -portDnumber 2
         $itk_component(opticsview) configure -portEnumber 5
      }
      Gemini-South {
         $itk_component(opticsview) configure -portBnumber 4
         $itk_component(opticsview) configure -portCnumber 3
         $itk_component(opticsview) configure -portDnumber 2
         $itk_component(opticsview) configure -portEnumber 5
      }
   }

   eval itk_initialize $args
}

itcl::body GraphicDisplay::update {} {
#+
#  Updates the display items.
#-

# Update the widgets.
   $itk_component(domeview) update
   $itk_component(elview) update
   $itk_component(wrapview) update
   $itk_component(probe1) update
   $itk_component(probe2) update

# Determine whether there is any vignetting from the enclosure.
   set v [sadVal tcssad domeVignette -1]
   if { $v > 0.0 && $Vignette == 0 } {
      $itk_component(opticsview) configure -vignette 1
      set Vignette 1
   } elseif { $v == 0 && $Vignette == 1 } {
      $itk_component(opticsview) configure -vignette 0
      set Vignette 0
   }

# Determine the status of M2.
   set m2sfollow [isFollowing m2ssad followS]
   set m2sinpos [isInPosition m2ssad inPosition]

   if { $m2sfollow } {
      if { $m2sinpos } {
         $itk_component(opticsview) configure -m2sstate INPOSITION
      } else {
         $itk_component(opticsview) configure -m2sstate FOLLOWING
      }
   } else {
      $itk_component(opticsview) configure -m2sstate OFF
   }

# Determine the state of M1.
   if { [string equal [sa pcssad get apssMsg] "APSS inflated"] && \
         [string equal [sa pcssad get aosMsg] "aO sub-system is ON"] && \
         [string equal [sa pcssad get pssInPosn] TRUE] && \
         [string equal [sa pcssad get pssOn] ON]  && \
         [string equal [sa tcssad get m1FigUpdatesFlag] On] } {
      if { [sa pcssad get aoMoving] < 10.0 } {
         $itk_component(opticsview) configure -pcsstate OK
      } else {
         $itk_component(opticsview) configure -pcsstate MOVING
      }
   } else {
      $itk_component(opticsview) configure -pcsstate OFF
   }

# Configure the science fold position.
   set sfmoving 0
   set lin [sadVal agssad sfLin 1000.0]
   if { $lin == 1000.0 } {
      $itk_component(opticsview) configure -scfold UNKNOWN
   } elseif { $lin < -300.0 } {
      $itk_component(opticsview) configure -scfold PARK
   } else {
      if { $lin < -5.0 } {
         set sfmoving 1
      }
      set tilt [sadVal agssad sfTilt 0.0]
      set rot [sadVal agssad sfRot 0.0]
      if { $tilt < 20.0 && $tilt > -20.0 } {
         if { $rot > 90.0 } {
            set sfpos DE
            if { $rot < 140.0 || $rot > 130.0 } {
               set sfmoving 1
            }
         } elseif { $rot > 0.0 } {
            set sfpos CD
            if { $rot < 40.0 || $rot > 50.0 } {
               set sfmoving 1
            }
         } elseif { $rot > -90.0 } {
            set sfpos CB
            if { $rot < -50.0 || $rot > -40.0 } {
               set sfmoving 1
            }
         } else {
            set sfpos BE
            if { $rot < -140.0 || $rot > -130.0 } {
               set sfmoving 1
            }
         }
      } else {
         if { $tilt > 20.0 } {
            set sfpos U
            if { $tilt > 47.5 || $tilt < 42.5 } {
               set sfmoving 1
            }
         } else {
            set sfpos A
            if { $tilt < -47.5 || $tilt > -42.5 } {
               set sfmoving 1
            }
         }
         if { $rot > 135.0 } {
            append sfpos E
            if { $rot < 175.0 || $rot > 185.0 } {
               set sfmoving 1
            }
         } elseif { $rot > 45.0 } {
            append sfpos D
            if { $rot < 85.0 || $rot > 95.0 } {
               set sfmoving 1
            }
         } elseif { $rot > -45.0 } {
            append sfpos C
            if { $rot < -5.0 || $rot > 5.0 } {
               set sfmoving 1
            }
         } elseif { $rot > -135.0 } {
            append sfpos B
            if { $rot < -95.0 || $rot > -85.0 } {
               set sfmoving 1
            }
         } else {
            append sfpos E
            if { $rot < -185.0 || $rot > -175.0 } {
               set sfmoving 1
            }
         }
      }
      if { $sfmoving } {
         if { $flash } {
            $itk_component(opticsview) configure -scfold MOVING
            set flash 0
         } else {
            $itk_component(opticsview) configure -scfold $sfpos
            set flash 1
         }
      } else {
         $itk_component(opticsview) configure -scfold $sfpos
      }
   }

# Determine if there is light from GCAL.
   set calunit [expr { [sa gcalsad get shutter value] == "OPEN" ||
         [sa gcalsad get ArLampState value] == "ON" ||
         [sa gcalsad get KrLampState value] == "ON" ||
         [sa gcalsad get CuArLampState value] == "ON" ||
         [sa gcalsad get ThArLampState value] == "ON" ||
         [sa gcalsad get QHLampState value] == "ON" }]

# Configure the light path.
   $itk_component(opticsview) configure \
         -deployablebaffle [sa m2ssad get deployBafflePos value] \
         -centralbaffle [sa m2ssad get centralBafflePos value] \
         -aofold [sa agssad get aoName value] \
         -hrwfs [sa agssad get hwName value] \
         -m1cover [sa gissad get m1cover value] \
         -holecover [sa gissad get m1inst value] \
         -calunit $calunit
   $itk_component(opticsview) update

# Set the colour of the OIWFS according to the follow and in position state.
   if { [isFollowing agssad oiFollowS] } {
      if { [isInPosition agssad oiInPosition] } {
         $itk_component(oix) configure -status ok
         $itk_component(oiy) configure -status ok
      } else {
         $itk_component(oix) configure -status warning
         $itk_component(oiy) configure -status warning
      }
   } else {
      $itk_component(oix) configure -status error
      $itk_component(oiy) configure -status error
   }

# Update the OIWFS position.
   $itk_component(oix) configure -text [sa agssad get oiX]
   $itk_component(oiy) configure -text [sa agssad get oiY]

# Set the ISS port labels.
   $itk_component(opticsview) configure \
         -portAlabel [sa agssad get port1Label]

   switch [sa tcssad get name] {
      Gemini-North {
         $itk_component(opticsview) configure \
               -portBlabel [sa agssad get port4Label] \
               -portClabel [sa agssad get port3Label] \
               -portDlabel [sa agssad get port2Label] \
               -portElabel [sa agssad get port5Label] 
      }
      Gemini-South {
         $itk_component(opticsview) configure \
               -portBlabel [sa agssad get port4Label] \
               -portClabel [sa agssad get port3Label] \
               -portDlabel [sa agssad get port2Label] \
               -portElabel [sa agssad get port5Label] 
      }
   }
}
