#+
#  NumericDisplay <- itk::widget
#
#  Implements the NumericDisplay widget.
#
#  Options:
#          none
#
#  Methods
#          update      Updates the display from the SAD
#
#  options
#
#  D Terrett 30 November 2001
#
#  Copyright CCLRC
#-

itcl::class NumericDisplay {
   inherit itk::Widget
   constructor args {}
   destructor {}
   public {
      method update {}
   }
   private {
      method newtarget {record value}
      method newobject {record value}
      method inPosition {rec value}
      method noheartbeat {}
      method heartbeat {rec value}
      variable nohbid
      variable hbid
   }
}

itk::usual NumericDisplay {
   keep -background -cursor -foreground -font -labelfont
   keep -highlightcolor -highlightthickness
   keep -background -cursor
   keep -highlightcolor -highlightthickness
}

itcl::body NumericDisplay::constructor args {

# Frame for telescope RA/Dec, frame and tracking wavelength on one row
# followed by the target position, airmass and hour angle on the next
   itk_component add top {
      frame $itk_interior.top
   }
   grid $itk_component(top)

   set w $itk_component(top)

# Current object.
   itk_component add objlabel {
      label $w.objlabel
   }
   itk_component add objname {
      label $w.objname
   }

# Status and health.
   itk_component add status {
      StatusField $w.status -labelmargin 2 -width 15 -entryborder 3 \
            -labelpos n -entryrelief groove -labeltext "TCS STATUS"
   }

# Nod and chop state.
   itk_component add nod {
      label $w.nod -width 8 -anchor w
   }
   itk_component add chopping {
      label $w.chopping -width 14 -anchor w
   }

# M2 tip/tilt & focus
   itk_component add ttt {
      label $w.ttf -text "M2 tip/tilt (arcsec on sky)" -anchor center
   }
   itk_component add tt {
       frame $w.tt
   }
   set w $itk_component(tt)
   itk_component add tip {
       StatusField $w.tip -labelmargin 2 -width 5 -entryborder 3 \
            -entryrelief groove -labeltext X:
   }
   itk_component add tilt {
       StatusField $w.tilt -labelmargin 2 -width 5 -entryborder 3 \
            -entryrelief groove -labeltext Y:
   }
   pack $itk_component(tip) $itk_component(tilt) -side left
   set w [winfo parent $w]

   itk_component add focus {
       StatusField $w.focus -labelmargin 2 -width 5 -entryborder 3 \
            -entryrelief groove -labeltext "Focus (mu):"
   }

   itk_component add telposlabel {
      label $w.telposlabel -text "TELESCOPE POSITION:"
   }
   itk_component add telpos1 {
      StatusField $w.tepos1 -labelmargin 5 -width 11 -entryborder 3 \
            -entryrelief groove
   }
   itk_component add telpos2 {
      StatusField $w.tepos2 -labelmargin 5 -width 11 -entryborder 3 \
            -entryrelief groove
   }
   itk_component add telpossys {
      label $w.telpossys -width 10
   }
   itk_component add telposwavel {
      label $w.telposwavel -width 8
   }

   itk_component add tarlabel {
      label $w.tarlabel -text "TARGET:"
   }
   itk_component add tar1 {
      StatusField $w.tar1 -labelmargin 5 -width 11 -entryborder 3 \
            -entryrelief groove

   }
   itk_component add tar2 {
      StatusField $w.tar2 -labelmargin 5 -width 11 -entryborder 3 \
            -entryrelief groove
   }
   itk_component add tarsys {
      label $w.tarsys -width 10
   }
   itk_component add tarwavel {
      label $w.tarwavel -width 8
   }
   itk_component add hazdam {
      frame $w.hazdam
   }
   set w $itk_component(hazdam)
   itk_component add ha {
      StatusField $w.ha -labeltext HA: -labelmargin 5 -width 8 -entryborder 3 \
            -entryrelief groove
   }
   itk_component add zd {
      StatusField $w.zd -labeltext ZD: -labelmargin 5 -entryborder 3 \
            -entryrelief groove
   }
   itk_component add am {
      StatusField $w.am -labeltext AM: -labelmargin 5 -entryborder 3 \
            -entryrelief groove
   }
   pack $itk_component(ha) $itk_component(zd) $itk_component(am) -side left
   set w [winfo parent $w]
   itk_component add offlab {
      label $w.offlab -text "OFFSET (arcsec):"
   }
   itk_component add off1 {
      StatusField $w.off1 -labelmargin 5 -width 8 -entryborder 3 \
            -entryrelief groove -anchor e
   }
   itk_component add off2 {
      StatusField $w.off2 -labelmargin 5 -width 8 -entryborder 3 \
            -entryrelief groove -anchor e
   }

   itk_component add baselab {
      label $w.baselab -text "BASE:"
   }
   itk_component add base1 {
      StatusField $w.base1 -labelmargin 5 -width 11 -entryborder 3 \
            -entryrelief groove
   }
   itk_component add base2 {
      StatusField $w.base2 -labelmargin 5 -width 11 -entryborder 3 \
            -entryrelief groove
   }

   itk_component add ratelab {
      label $w.ratelab -text "TRACK RATE:"
   }
   itk_component add rate1 {
      StatusField $w.rate1 -labelmargin 5 -width 8 -entryborder 3 \
            -entryrelief groove -anchor e
   }
   itk_component add rate2 {
      StatusField $w.rate2 -labelmargin 5 -width 8 -entryborder 3 \
            -entryrelief groove -anchor e
   }
   itk_component add choplab {
      label $w.choplab -text "CHOP THROW (arcsec):"
   }
   itk_component add chop1 {
      StatusField $w.chop1 -labelmargin 5 -width 8 -entryborder 3 \
            -entryrelief groove -anchor e
   }
   itk_component add chop2 {
      StatusField $w.chop2 -labelmargin 5 -width 8 -entryborder 3 \
            -entryrelief groove -anchor e
   }

   itk_component add instrlab {
      label $w.instrlab -text "INSTRUMENT (arcsec):"
   }
   itk_component add instrx {
      StatusField $w.instrx -labelmargin 5 -width 6 -entryborder 3 \
            -entryrelief groove -anchor e -labeltext X
   }
   itk_component add instry {
      StatusField $w.instry -labelmargin 5 -width 6 -entryborder 3 \
            -entryrelief groove -anchor e -labeltext Y
   }

# Time.
   itk_component add time {
      frame $w.time -bd 2 -relief ridge
   }
   set w $itk_component(time)
   itk_component add utc {
      StatusField $w.utc -labeltext UTC: -labelmargin 5 -entryborder 3 \
            -entryrelief groove
   }
   [$itk_component(utc) component label] configure -width 4
   itk_component add lst {
      StatusField $w.lst -labeltext LST: -labelmargin 5 -entryborder 3 \
            -entryrelief groove
   }
   [$itk_component(lst) component label] configure -width 4
   itk_component add hflag {
      label $w.hflag -image hawaii_flag
   }
   itk_component add hst {
      StatusField $w.hst -labeltext HST: -labelmargin 5 -entryborder 3 \
            -entryrelief groove
   }
   [$itk_component(hst) component label] configure -width 4
   itk_component add cflag {
      label $w.cflag -image chile_flag
   }
   itk_component add cst {
      StatusField $w.cst -labeltext CST: -labelmargin 5 -entryborder 3 \
            -entryrelief groove
   }
   [$itk_component(cst) component label] configure -width 4
   grid x $itk_component(utc) -pady 2 -sticky w
   grid x $itk_component(lst) -pady 2 -sticky w
   grid $itk_component(hflag) $itk_component(hst) -pady 2 -sticky w
   grid $itk_component(cflag) $itk_component(cst) -pady 2 -sticky w

# Telescope and Dome positions.
   set w $itk_component(top)
   itk_component add mech {
      frame $w.mech -bd 2 -relief ridge
   }
   set w $itk_component(mech)
   itk_component add mechlab {
      label $w.mechlab -text "Mechanical Positions"
   }
   itk_component add tellab {
      label $w.tellab -text Telescope:
   }
   itk_component add telaz {
      StatusField $w.telaz -labeltext Az -labelmargin 5 -width 13 \
            -entryborder 3 -entryrelief groove 
   }
   itk_component add telel {
      StatusField $w.telel -labeltext El -labelmargin 5 -width 13 \
            -entryborder 3 -entryrelief groove 
   }
   itk_component add rot {
      StatusField $w.rot -labeltext Rotator -labelmargin 5 -width 10 \
            -entryborder 3 -entryrelief groove
   }
   itk_component add errlab {
      label $w.errlab -text Errors:
   }
   itk_component add azerr {
      StatusField $w.azerr -width 13 -entryborder 3 -entryrelief groove 
   }
   itk_component add elerr {
      StatusField $w.elerr -width 13 -entryborder 3 -entryrelief groove 
   }
   itk_component add roterr {
      StatusField $w.roterr -width 10 -entryborder 3 -entryrelief groove
   }
   itk_component add domelab {
      label $w.domelab -text Dome:
   }
   itk_component add domeaz {
      StatusField $w.domeaz -labeltext Az -labelmargin 5 -width 7 \
            -entryborder 3 -entryrelief groove
   }
   itk_component add topshut {
      StatusField $w.topshut -labeltext Top -labelmargin 5 -width 5 \
            -entryborder 3 -entryrelief groove
   }
   itk_component add botshut {
      StatusField $w.botshut -labeltext Bottom -labelmargin 5 -width 5 \
            -entryborder 3 -entryrelief groove 
   }
   grid $itk_component(mechlab) - - - -pady 2
   grid $itk_component(tellab) $itk_component(telaz) $itk_component(telel) \
         $itk_component(rot) -sticky e -pady 2
   grid  $itk_component(errlab) $itk_component(azerr) $itk_component(elerr) \
         $itk_component(roterr) -sticky e -pady 2
   grid $itk_component(domelab) $itk_component(domeaz) \
         $itk_component(topshut) $itk_component(botshut) -sticky w -pady 2
   grid configure $itk_component(domelab) -sticky e

# Layout elements.
   grid $itk_component(objlabel) $itk_component(objname) - - - \
         $itk_component(status) - - -sticky e -padx 3 -pady 2
   grid configure $itk_component(objname) -sticky w
   grid $itk_component(telposlabel) $itk_component(telpos1) \
         $itk_component(telpos2) $itk_component(telpossys) \
         $itk_component(telposwavel) -sticky e -padx 3 -pady 2
   grid configure $itk_component(status) -rowspan 2
   grid $itk_component(tarlabel) $itk_component(tar1) \
         $itk_component(tar2) $itk_component(tarsys) $itk_component(tarwavel) \
         $itk_component(nod) -sticky e -padx 3 -pady 2
   grid configure $itk_component(nod) -sticky w
   grid $itk_component(offlab) $itk_component(off1) $itk_component(off2) \
         x x $itk_component(chopping) -sticky e -padx 3 -pady 2
   grid configure $itk_component(chopping) -sticky w
   grid $itk_component(baselab) $itk_component(base1) $itk_component(base2) \
         x $itk_component(ttt) - - -sticky e -padx 3 -pady 2
   grid configure $itk_component(ttt) -sticky ew
   grid $itk_component(ratelab) $itk_component(rate1) $itk_component(rate2) \
        x $itk_component(tt) - - -sticky e -padx 3 -pady 2
   grid configure $itk_component(tt) -sticky {}
   grid $itk_component(choplab) $itk_component(chop1) $itk_component(chop2) \
         x $itk_component(focus) - - -sticky e -padx 3 -pady 2
   grid configure $itk_component(focus) -sticky {}
   grid $itk_component(instrlab) $itk_component(instrx) $itk_component(instry) \
          x $itk_component(hazdam) - - -sticky e -padx 3 -pady 2
   grid configure $itk_component(instrx) $itk_component(instry) -sticky e
   grid $itk_component(mech) - - - $itk_component(time) - -
   grid configure $itk_component(mech) -sticky w
   grid configure $itk_component(time) -sticky e

# Call newtarget whenever any of the tracking frame or wavelengths change.
   foreach vt {sourceA sourceB sourceC pwfs1 pwfs2 oiwfs mount} {
      if { [llength [find object tcssad.${vt}TrackFrame]] == 0 } {
         RecordMonitor tcssad.${vt}TrackFrame tcssad ${vt}TrackFrame
      }
      set hbid(${vt}TrackFrame) [tcssad.${vt}TrackFrame add \
            [code $this newtarget]]
      if { [llength [find object tcssad.${vt}TrackEq]] == 0 } {
         RecordMonitor tcssad.${vt}TrackEq tcssad ${vt}TrackEq
      }
      set hbid(${vt}TrackEq) [tcssad.${vt}TrackEq add \
            [code $this newtarget]]
      if { [llength [find object tcssad.${vt}TrackWavelength]] == 0 } {
         RecordMonitor tcssad.${vt}TrackWavelength tcssad ${vt}TrackWavelength
      }
      set hbid(${vt}TrackWavelength) [tcssad.${vt}TrackWavelength add \
            [code $this newtarget]]
      if { [llength [find object tcssad.${vt}Wavelength]] == 0 } {
         RecordMonitor tcssad.${vt}Wavelength tcssad ${vt}Wavelength
      }
      set hbid(${vt}Wavelength) [tcssad.${vt}Wavelength add \
            [code $this newtarget]]
   }

# Call newobject whenever any of the input objects change.
   foreach vt {sourceA sourceB sourceC pwfs1 pwfs2 oiwfs mount} {
      if { [llength [find object tcssad.${vt}ObjectName]] == 0 } {
         RecordMonitor tcssad.${vt}ObjectName tcssad ${vt}ObjectName
      }
      set hbid(${vt}ObjectName) [tcssad.${vt}ObjectName add \
            [code $this newobject]]
   }

# Call inPosition whenever any of the inPosition or followS records change.
   foreach sa {mcssad mcssad mcssad crssad ecssad ecssad ecssad \
         tcssad mcssad crssad tcssad tcssad} \
         par {inPosition inPositionAz inPositionEl inPosition \
         domeInPos topShtrInPos botShtrInPos inPosition followS followS \
         autoMoveDome autoMoveShtrs} {
         if { [llength [find object $sa.$par]] == 0 } {
            RecordMonitor $sa.$par $sa $par
         }
         set hbid($par) [$sa.$par add [code $this inPosition]]
   }

# Execute the noheartbeat method in 5 seconds time (the heartbeat monitor
# routine will cancel it if the heartbeat is running.
   set nohbid [after 5000 [code $this noheartbeat]]

# Monitor the heartbeat sad record.
   if { [llength [find object tcssad.heartbeat]] == 0 } {
      RecordMonitor tcssad.heartbeat tcssad heartbeat
   }
   set hbid(heartbeat) [tcssad.heartbeat add [code $this heartbeat]]
   
# Trigger checks on the subsystem states
   inPosition mcssad.xxxx ""
   inPosition crssad.xxxx ""
   inPosition ecssad.xxxx ""

# Update the display.
   newobject "" ""
   newtarget "" ""

   eval itk_initialize $args
}

itcl::body NumericDisplay::destructor {} {
   foreach vt {sourceA sourceB sourceC pwfs1 pwfs2 oiwfs mount} {
      tcssad.${vt}TrackFrame remove $hbid(${vt}TrackFrame)
      tcssad.${vt}TrackEq remove $hbid(${vt}TrackEq)
      tcssad.${vt}TrackWavelength remove $hbid(${vt}TrackWavelength)
      tcssad.${vt}ObjectName remove $hbid(${vt}ObjectName)
   }
   foreach sa {mcssad mcssad mcssad crssad ecssad ecssad ecssad \
         tcssad mcssad crssad} \
         par {inPosition inPositionAz inPositionEl inPosition \
         domeInPos topShtrInPos botShtrInPos inPosition \
         followS followS} {
      $sa.$par remove $hbid($par)
   }
   tcssad.heartbeat remove $hbid(heartbeat)
   after cancel $nohbid
}

itcl::body NumericDisplay::newtarget {record value} {
# Updates the display when the tracking frame or wavelength changes.
   
# Telescope position (in tracking frame of the mount).
   set system [sa tcssad get mountTrackFrame]
   set type ""
   set year ""
   scan [sa tcssad get mountTrackEq] "%c%d" type year
   set type [format "%c" $type]
   set wavel [sadVal tcssad mountWavelength ""]
   if { $wavel != "" } {
      set wavel "[expr {$wavel / 10000.0}] mu"
   }
   if { $system == "AZEL_TOPO" } {
      $itk_component(telpos1) configure -labeltext Az
      $itk_component(telpos2) configure -labeltext El
   } else {
      $itk_component(telpos1) configure -labeltext RA
      $itk_component(telpos2) configure -labeltext Dec
   }
   switch $system {
      FK4 -
      FK5 {
         $itk_component(telpossys) configure -text "$system/$type$year"
      }
      APPT {
         $itk_component(telpossys) configure -text "Apparent"
      }
      default {
         $itk_component(telpossys) configure -text ""
      }
   }
   $itk_component(telposwavel) configure -text $wavel

# Target position.
   set system [sa tcssad get sourceATrackFrame]
   set type ""
   set year ""
   scan [sa tcssad get sourceATrackEq] "%c%d" type year
   set type [format "%c" $type]
   set wavel [sadVal tcssad sourceAWavelength ""]
   if { $wavel != "" } {
      set wavel "[expr {$wavel / 10000.0}] mu"
   }
   if { $system == "AZEL_TOPO" } {
      $itk_component(tar1) configure -labeltext Az
      $itk_component(tar2) configure -labeltext El
   } else {
      $itk_component(tar1) configure -labeltext RA
      $itk_component(tar2) configure -labeltext Dec
   }
   switch $system {
      FK4 -
      FK5 {
         $itk_component(tarsys) configure -text "$system/$type$year"
      }
      APPT {
         $itk_component(tarsys) configure -text "Apparent"
      }
      default {
         $itk_component(tarsys) configure -text ""
      }
   }
   $itk_component(tarwavel) configure -text "$wavel"
}

itcl::body NumericDisplay::newobject {record value} {

# Updates the display when the source changes.
   
# Set object label.
   $itk_component(objlabel) configure -text "OBJECT:"

# Object name
   $itk_component(objname) configure \
         -text [sa tcssad get sourceAObjectName]
}

itcl::body NumericDisplay::update {} {

# Telescope and dome position.
#   $itk_component(telpos1) configure -text [sa tcssad get currentRA]
#   $itk_component(telpos2) configure -text [sa tcssad get currentDec]
   $itk_component(telaz) configure -text [sa tcssad get currentAz]
   $itk_component(azerr) configure -text [sa tcssad get azError]
   $itk_component(telel) configure -text [sa tcssad get currentEl]
   $itk_component(elerr) configure -text [sa tcssad get elError]
   $itk_component(rot) configure -text [sa crssad get currentRma]
   $itk_component(roterr) configure -text [sa tcssad get rmaError]
   $itk_component(domeaz) configure -text [sa ecssad get domePos]
   $itk_component(topshut) configure -text [sa ecssad get topShtrPos]
   $itk_component(botshut) configure -text [sa ecssad get botShtrPos]

# Target
   set wavel [sadVal tcssad sourceAWavelength ""]
   if { ![catch {set demand [ast target A A [expr { $wavel / 10000.0 }] \
         [sa tcssad get sourceATrackFrame] \
         [sa tcssad get sourceATrackEq]]}] } {
      $itk_component(tar1) configure -text [lindex $demand 0]
      $itk_component(tar2) configure -text [lindex $demand 1]
      $itk_component(ha) configure -text [lindex $demand 2]
      $itk_component(zd) configure -text [lindex $demand 3]
      $itk_component(am) configure -text [lindex $demand 4]
   }

# Nod state
   set nod [sa tcssad get nodState]
   $itk_component(nod) configure -text "Nod $nod"

# Chopping
   set chopping [sa m2ssad get chopping]
   if { [string equal $chopping YES] } {
      $itk_component(chopping) configure -text "Chopping"
   } else {
      $itk_component(chopping) configure -text "Not Chopping"
   }

# Target info for the current target and chop throw
   switch $nod {
      A {
         set target [sa tcssad get targetA]
         set targetb [sa tcssad get targetB]
      }
      B {
         set target [sa tcssad get targetB]
         set targetb [sa tcssad get targetA]
      }
      C {
         set target [sa tcssad get targetC]
         set targetb [sa tcssad get targetA]
      }
      default {
         set target [sa tcssad get targetA]
         set targetb [sa tcssad get targetB]
      }
   }


# Offset and base and track rate
   set ra [slaDr2tf 3 [lindex $target 0]]
   set dec [slaDr2af 2 [lindex $target 1]]
   $itk_component(base1) configure -text \
         [format "%02d:%02d:%02d.%03d" [lindex $ra 1] [lindex $ra 2] \
         [lindex $ra 3] [lindex $ra 4]]
   $itk_component(base2) configure -text \
         [format "%s%02d:%02d:%02d.%02d" [lindex $dec 0] [lindex $dec 1] \
         [lindex $dec 2] [lindex $dec 3] [lindex $dec 4]]
   set off1 [expr {[lindex $target 2] * 206264.80624710}]
   if { $off1 > 648000.0 } {
      set off1 [expr { $off1 - 1296000.0 }]
   }
   set off1 [expr {$off1 * cos( [lindex $target 1] )}]
   $itk_component(off1) configure -text [format "%10.2f" $off1]
   $itk_component(off2) configure -text \
         [format "%10.2f" [expr {[lindex $target 3] * 206264.80624710}] ]
   $itk_component(rate1) configure -text [sa tcssad get sourceADiffRA value]
   $itk_component(rate2) configure -text [sa tcssad get sourceADiffDec value]

# Chop throw.
   set throw1 [expr {([lindex $targetb 0] + [lindex $targetb 2] - \
         [lindex $target 0] - [lindex $target 2]) * 206264.80624710 * \
         cos( [lindex $target 1] )}]
   if { $throw1 > 648000.0 } {
      set throw1 [expr { $throw1 - 1296000.0 }]
   }
   set throw2 [expr {([lindex $targetb 1] + [lindex $targetb 3] - \
         [lindex $target 1] - [lindex $target 3]) * 206264.80624710}]
   $itk_component(chop1) configure -text [format "%10.2f" $throw1]
   $itk_component(chop2) configure -text [format "%10.2f" $throw2]

   set xy [ast instrument A]
   $itk_component(instrx) configure \
         -text [format %.2f [expr {[lindex $xy 0] / 0.62056151}]]
   $itk_component(instry) configure \
         -text [format %.2f [expr {[lindex $xy 1] / 0.62056151}]]

# M2 tip/tilt/focus.
   set tip [expr { [sadVal m2ssad xtilt "0.0"] / 3.86956518 }]
   set tilt [expr { [sadVal m2ssad ytilt "0.0"] / 3.86956518 }]
   $itk_component(tip) configure -text [format %.2f $tip] -status ok
   if { $tip > 8.0 || $tip < -8.0 } {
      $itk_component(tip) configure -status error
   }
   $itk_component(tilt) configure -text [format %.2f $tilt] -status ok
   if { $tilt > 8.0 || $tilt < -8.0 } {
      $itk_component(tilt) configure -status error
   }
   $itk_component(focus) configure -text [sa m2ssad get focus]

# Time.
   $itk_component(utc) configure -text [tccTime utc]
   $itk_component(hst) configure -text [tccTime localtime -10]
   $itk_component(cst) configure -text [tccTime localtime -4]
   $itk_component(lst) configure -text [tccTime last]
}

itcl::body NumericDisplay::inPosition {rec value} {
#+
# Colour codes various widgets according to whether a sub-system is 
# in position and/or following.
#-

# Extract the subsystem and record from the name of the record that changed.
   foreach {subsys record} [split $rec .] {}

# Telescope position.
   if { [string equal $subsys tcssad] || [string equal $subsys mcssad] } {
      if { [isFollowing mcssad followS] } {
         if { [isInPosition tcssad inPosition] } {
            set status ok
         } else {
            set status warning
         }
      } else {
         set status error
      }
      $itk_component(telpos1) configure -status $status
      $itk_component(telpos2) configure -status $status
   }

# Telescope Az/El.
   if { [string equal $subsys mcssad] } {
      if { [isFollowing mcssad followS] } {
         if { [isInPosition mcssad inPositionAz] } {
               set azstat ok
         } else {
            set azstat warning
         }
         if { [isInPosition mcssad inPositionEl] } {
            set elstat ok
         } else {
            set elstat warning
         }
      } else {
         set azstat error
         set elstat error
      }
      $itk_component(telaz) configure -status $azstat
      $itk_component(azerr) configure -status $azstat
      $itk_component(telel) configure -status $elstat
      $itk_component(elerr) configure -status $elstat
   }

# Cass rotator position.
   if { [string equal $subsys crssad] } {
      if { [isFollowing crssad followS] } {
         if { [isInPosition crssad inPosition] } {
            set status ok
         } else {
            set status warning
         }
      } else {
         set status error
      }
      $itk_component(rot) configure -status $status
      $itk_component(roterr) configure -status $status
   }

# Dome az and shutter positions.
   if { [string equal $subsys tcssad] || [string equal $subsys ecssad] } {
      if { [string equal [sa tcssad get autoMoveDome] On ] } {
         if { [isInPosition ecssad domeInPos] } {
            set domestat ok
         } else {
            set domestat warning
         }
      } else {
         set domestat error
      }
      if { [string equal [sa tcssad get autoMoveShtrs] On ] } {
         if { [isInPosition ecssad topShtrInPos] } {
            set topstat ok
         } else {
            set topstat warning
         }
         if { [isInPosition ecssad botShtrInPos] } {
            set botstat ok
         } else {
            set botstat warning
         }
      } else {
         set topstat error
         set botstat error
      }
      $itk_component(domeaz) configure -status $domestat
      $itk_component(topshut) configure -status $topstat
      $itk_component(botshut) configure -status $botstat
   }
}

itcl::body NumericDisplay::noheartbeat {} {

# No heartbeat seen for 5 seconds so write a message to the status
# field and set it to the "error" colour.
   $itk_component(status) configure -text "NO HEARTBEAT" -status error
}

itcl::body NumericDisplay::heartbeat {rec value} {

# Cancel the pending noheartbeat call.
   after cancel $nohbid
   
# Get the state and health.
   set state [sa tcssad get state]
   set health [sa tcssad get health]

# Update the status widget.
   $itk_component(status) configure -text ${state}/${health}

# Set the widget status.
   if { [string compare $health BAD] == 0 } {
      $itk_component(status) configure -status error
   } elseif { [string compare $health WARNING] == 0 } {
      $itk_component(status) configure -status warning
   } elseif { [string compare $state RUNNING] != 0 } {
      $itk_component(status) configure -status warning
   } else {
      $itk_component(status) configure -status ok
   }

# Schedule the noheartbeat method again.
   set nohbid [after 5000 [code $this noheartbeat]]
}
