#+
#  NumericPanel.itk
#
#  Implements the NumericPanel widget. A Panel widget with a NumericsDisplay
#  widget packed into its interior
#
#  D Terrett 27 April 1999
#
#  Copyright CCLRC
#+

itcl::class NumericPanel {
   inherit Panel

   constructor args {}

   public method update 
}

itk::usual NumericPanel {
   keep -background -cursor
}

itcl::body NumericPanel::constructor args {

# Withdraw the top level window so that we don't see geometry changes 
# while waiting for sa to connect.
   set toplevel [winfo toplevel $itk_interior]
   wm withdraw $toplevel

   itk_component add control {
      NumericDisplay $itk_interior.control
   } {
      usual
      ignore -highlightcolor
      rename -font -numericfont numericFont Font
      rename -labelfont -numericfont numericFont Font
   }
   setWidgetColors "$itk_component(menubar) $itk_component(control)" \
         $itk_option(-background) $itk_option(-foreground)

   pack $itk_component(control) -fill both -expand y

   set itk_option(-windows) $itk_component(control)

   eval itk_initialize $args

   wm deiconify $toplevel
}

itcl::body NumericPanel::update {} {

# Update the control component.
   $itk_component(control) update
}
