#+
#  OpticsView <- itk:Widget
#
#  Implements the OpticsView widget.
#
#  Options:
#          -aofold            The position of the ao fold mirror (IN or OUT).
#
#          -aopresent         AO unit present (boolean).
#
#          -centralbaffle     The position of the central baffle (OPEN or
#                             CLOSED).
#
#          -calunit           Calibration unit shutter position (OPEN or CLOSE)
#
#          -deployablebaffle  The postion of the deployable baffle (RETRACTED,
#                             "NEAR IR", VISIBLE or EXTENDED).
#
#          -holecover         The position of the M1 central hole cover (OPENED,
#                             "MIDDLE POSITION" or CLOSED).
#
#          -hrwfs             The position of the HRWFS pickoff mirror (IN or
#                             OUT).
#
#          -m1cover           The position of the M1 cover (OPENED,
#                             "MIDDLE POSITION" or CLOSED).
#
#          -m2sstate          The follow/in position state of the m2
#                             system (OFF FOLLOWING or INPOSITION).
#
#          -port1label        The label for ISS port 1.
#
#          -port2label        The label for ISS port 2.
#
#          -port3label        The label for ISS port 3.
#
#          -port4label        The label for ISS port 4.
#
#          -port5label        The label for ISS port 5.
#
#          -pcsstate          The state of the PCS (OFF MOVING or OK)..
#
#          -scfold            The current science fold position.
#
#          -vignette          The fraction of vignetting by the enclosure.
#
#  Methods:
#          update             Redraws the active parts of the picture 
#                             according to the state of the configuration
#                             options.
#
#  D Terrett  24 April 2001
#
#  Copyright CCLRC
#-

itcl::class OpticsView {
   inherit itk::Widget
   constructor args {}
   itk_option define -m1cover m1Cover M1Cover CLOSED 
   itk_option define -holecover holeCover HoleCover CLOSED 
   itk_option define -centralbaffle centralBaffle CentralBaffle "" 
   itk_option define -deployablebaffle deployableBaffle DeployableBaffle 0 
   itk_option define -aofold aoFold AoFold out 
   itk_option define -scfold scFold ScFold 0 
   itk_option define -hrwfs hrwfs Hrwfs in 
   itk_option define -m2sstate m2sState M2sState OFF
   itk_option define -aopresent aoPresent AoPresent 0 {}
   itk_option define -vignette vignette Vignette 0 
   itk_option define -port1label port1Label Label "" "relabel 1"
   itk_option define -port2label port2Label Label "" "relabel 2"
   itk_option define -port3label port3Label Label "" "relabel 3"
   itk_option define -port4label port4Label Label "" "relabel 4"
   itk_option define -port5label port5Label Label "" "relabel 5"
   itk_option define -pcsstate pcsState PcsState OFF
   itk_option define -calunit calUnit CalUnit CLOSE
   public {
      method update {}
   }
   private {
      method relabel {port}
   }
}

itk::usual OpticsView {
   keep -aofold -aopresent -background -centralbaffle -cursor \
      -deployablebaffle -highlightcolor -highlightthickness -holecover \
      -hrwfs -insertbackground -insertborderwidth -insertwidth \
      -insertontime -insertofftime -m1cover -m2sstate -port1label -port2label \
      -port3label -port4label -port5label -scfold -selectbackground \
      -selectborderwidth -selectforeground -calunit -pcsstate
}

itcl::body OpticsView::constructor args {

# The picture is drawn to a scale of about 25 pixels per metre. The canvas
# is therefore 10m wide (8m + room for the AO box) and 20 meters high ( 4m 
# behind the primary + 12m separation between M1 and M2 + a bit of space
# above M2).
#
# Everything is created as if 0,0 was at the bottom left of the picture
# and then scaled by -1 in y to flip it the right way up and moved down by
# 570 pixels into their proper positions.

   itk_component add canvas {
      canvas $itk_interior.canvas -width 240 -height 570
   }
   pack $itk_component(canvas)
   set c $itk_component(canvas)

# M1 cover open
   $c create line -100 127 -100 150 -width 5 -tags M1coverOp
   $c create line 100 127 100 150 -width 5 -tags M1coverOp

# M1 cover closed
   $c create line -100 127  -80 143  -60 127  -40 143  -20 127  0 143  20 127 \
          40 143  60 127  80 143  100 127 -tags M1coverCl

# Central hole cover open
   $c create line -12 110  -12 122 -width 2 -tags holeCoverOp
   $c create line 12 110  12 122 -width 2 -tags holeCoverOp

# Central hole cover closed
   $c create line -12 110  12 110 -width 2 -tags holeCoverCl

# M2 deployable baffle in several positions
   $c create line -15 399 -15 378 -width 2 -tags deployableBaffle0
   $c create line 16 399 16 378 -width 2 -tags deployableBaffle0

   $c create line -15 399 -25 383 -width 2 -tags deployableBaffle1
   $c create line 16 399 26 383 -width 2 -tags deployableBaffle1

   $c create line -15 399 -31 390 -width 2 -tags deployableBaffle2
   $c create line 16 399 32 390 -width 2 -tags deployableBaffle2

   $c create line -15 399 -33 399 -width 2 -tags deployableBaffle3
   $c create line 16 399 34 399 -width 2 -tags deployableBaffle3

# M2 central baffle closed
   $c create line -9 405 9 410 -width 2 -tags centralBaffleCl

# M2 central baffle open
   $c create line -9 405 -9 427 -width 2 -tags centralBaffleOp

# M2 fixed stuff
   $c create line -9 400 -9 405 -fill black -width 2
   $c create line 9 400 9 410 -fill black -width 2
   $c create rectangle -14 400 14 381 -outline black -tags m2s

# Iss ports (shading of ao and cal unit ports removed for the moment).
#   $c create oval 35 70 65 40 -outline black -tags aoport -fill gray \
#         -stipple gray50
   $c create oval 35 70 65 40 -outline black -tags aoport
   $c create oval -35 70 -65 40 -outline black
   $c create oval 35 20 65 -10 -outline black
#   $c create oval -35 20 -65 -10 -outline black -fill gray -stipple gray50
   $c create oval -35 20 -65 -10 -outline black
   $c create oval -15 -85 15 -115 -outline black

# Iss port labels
   $c create text 0 -120 -anchor n -tags port1label
   $c create text 40 95 -anchor w -tags port2label
   $c create text -40 95 -anchor e -tags port3label
   $c create text -40 -35 -anchor e -tags port4label
   $c create text 40 -35 -anchor w -tags port5label

# A&G outline
   $c create arc -100 90 100 -30 -style arc -start -80 -extent 340 \
         -outline black -tags ag

# Aquisition TV / HRWFS
   $c create rectangle  80 -50 100 -70 -outline black
   $c create rectangle  75 -65 80 -55 -outline black
   $c create text 85 -80 -text AC/HRWFS -anchor c

# Incoming light beams
   $c create line -80 420 -80 143 -width 4 -tags SkyLight
   $c create line 80 420 80 143 -width 4 -tags SkyLight

# M1 to central hole cover
   $c create line -80 143 -80 111 -width 4 -tags {Light M1Light}
   $c create line 80 143 80 111 -width 4 -tags {Light M1Light}
   $c create line -80 111 -4 378 -width 4 -tags {Light M1Light}
   $c create line 80 111 4 378 -width 4 -tags {Light M1Light}
   $c create line 0 378 0 111 -width 6 -tags {Light M1Light}

# M2 to sky
   $c create line 0 378 0 420 -width 4 -tags {Light M2Light}

# Central hole cover to AO fold
   $c create line 0 111 0 65 -width 6 -tags {Light CHLight}

# AO to Science fold
   $c create line 0 65  80 95 -width 6 -tags {Light AoLight}
   $c lower \
         [$c create line 80 95  80 70  50 55 -width 6 -tags {Light AoLight}] \
         aoport
   $c create line 0 65  80 95  -width 6 -tags {Light AoLightNoAo}
   $c create line 0 65  0 30 -width 6 -tags {Light NotAoLight}

# Science fold to ISS face/HRWFS fold
   $c create line 0 30 0 -60 -width 6 -tags {Light IssLight1}
   $c create line 0 30 50 55 -width 6 -tags {Light IssLight2 AoLight}
   $c create line 0 30 -50 55 -width 6 -tags {Light IssLight3}
   $c create line 0 30 -50 5 -width 6 -tags {Light IssLight4}
   $c create line 0 30 50 5 -width 6 -tags {Light IssLight5}

# HRWFS fold to ISS face
   $c create line 0 -60 0 -100 -width 6 -tags {Light TvOutLight}

# HRWFS fold to HRWFS
   $c create line 0 -60 75 -60 -width 6 -tags {Light TvInLight}

# M1 (in 2 pieces, one each side of the central hole)
   $c create polygon \
          -100 115  -100 115  -100 127  -100 127 -75 123  -50 121 \
          -12 120  -12 120  -12 115  -12 115  \
          -smooth 1 -fill white -tags M1left
   $c create rectangle -12 110 -100 115 -outline black -tags {pcs pcsleft}

# The other half is created by reflecting in x
   eval $c create polygon [$c coords M1left] -smooth 1 -fill white -tags M1right
   $c scale M1right 0 0 -1 1
   eval $c create rectangle [$c coords pcsleft] -outline black \
         -tags [list {pcs pcsright}]
   $c scale pcsright 0 0 -1 1

# M2
   $c create arc -200 378 200 1380 -start 275 -extent -10 -style arc \
         -outline white -width 3 -tags M2

# AO fold
   $c create line -9 74 9 54 -width 2 -tags AoFold
   $c create line -11 72 7 53 -tags AoFoldBck

# Science fold in various positions
   $c create line -20 29 20 29 -width 2 -tags {ScFold ScFold32 ScFold23}
   $c create line -20 27 20 27 -tags {ScFold ScFold32bck scFold23bck}

   eval $c create line [$c coords ScFold32] -width 2 \
         -tags [list {ScFold ScFold54 scFold45}]
   eval $c create line [$c coords ScFold32bck] \
         -tags [list {ScFold ScFold54bck ScFold45bck}]
   $c scale ScFold54 0 30 1 -1
   $c scale ScFold54bck 0 30 1 -1

   $c create line -1 10 -1 50 -width 2 -tags {ScFold ScFold25 ScFold52}
   $c create line -3 10 -3 50 -tags {ScFold ScFold25bck ScFold52bck}

   eval $c create line [$c coords ScFold25] -width 2 \
         -tags [list {ScFold ScFold34 ScFold43}]
   eval $c create line [$c coords ScFold25bck] \
         -tags [list {ScFold ScFold34bck scFold43bck}]
   $c scale ScFold34 0 30 -1 1
   $c scale ScFold34bck 0 30 -1 1

   $c create line -10 13 10 47 -width 2 -tags {ScFold ScFold04 ScFold40}
   $c create line -9 11 11 45 -tags {ScFold ScFold04bck ScFold40bck}

   eval $c create line [$c coords ScFold04] -width 2 \
         -tags [list {ScFold ScFold05 ScFold50}]
   eval $c create line [$c coords ScFold04bck] \
         -tags [list {ScFold ScFold05bck ScFold50}]
   $c scale ScFold05 0 30 -1 1
   $c scale ScFold05bck 0 30 -1 1

   eval $c create line [$c coords ScFold04] -width 2 \
         -tags [list {ScFold ScFold31 ScFold13}]
   eval $c create line [$c coords ScFold04bck] \
         -tags [list {ScFold ScFold31bck ScFold13bck}]
   $c scale ScFold31 0 30 1 -1
   $c scale ScFold31bck 0 30 1 -1

   eval $c create line [$c coords ScFold31] -width 2 \
         -tags [list {ScFold ScFold21 ScFold12}]
   eval $c create line [$c coords ScFold31bck] \
         -tags [list {ScFold ScFold21bck ScFold12bck}]
   $c scale ScFold21 0 30 -1 1
   $c scale ScFold21bck 0 30 -1 1

   $c create line -17 20 17 40 -width 2 -tags {ScFold ScFold03 ScFold30}
   $c create line -15 19 19 39 -tags {ScFold ScFold03bck ScFold30bck}

   eval $c create line [$c coords ScFold03] -width 2 \
         -tags [list {ScFold ScFold02 ScFold20bck}]
   eval $c create line [$c coords ScFold03bck] \
         -tags [list {ScFold ScFold02bck ScFold20}]
   $c scale ScFold02 0 30 -1 1
   $c scale ScFold02bck 0 30 -1 1

   eval $c create line [$c coords ScFold03] -width 2 \
         -tags [list {ScFold ScFold41 ScFold14}]
   eval $c create line [$c coords ScFold03bck] \
         -tags [list {ScFold ScFold41bck ScFold14bck}]
   $c scale ScFold41 0 30 1 -1
   $c scale ScFold41bck 0 30 1 -1

   eval $c create line [$c coords ScFold41] -width 2 \
         -tags [list {ScFold ScFold51 ScFold15}]
   eval $c create line [$c coords ScFold41bck] \
         -tags [list {ScFold ScFold51bck ScFold15bck}]
   $c scale ScFold51 0 30 -1 1
   $c scale ScFold51bck 0 30 -1 1

# Science fold unknown
   $c create bitmap 0 30 -anchor c -foreground black -tags ScFoldUnknown 

# HRWFS fold when deployed
   $c create line -9 -51 9 -69 -width 2 -tags HrwfsFoldIn
   $c create line -11 -53 7 -70 -tags HrwfsFoldInBck

# HRWFS fold when retracted
   $c create line  41 -51 59 -69 -width 2 -tags HrwfsFoldOut
   $c create line  39 -53 57 -70 -tags HrwfsFoldOutBck

# ISS port numbers
   $c create text 0 -100 -anchor c -text 1
   $c create text 50 55 -anchor c -text 2
   $c create text -50 55 -anchor c -text 3
   $c create text -50 5 -anchor c -text 4
   $c create text 50 5 -anchor c -text 5

# Raise the a&g outline so that the front edge cuts the light beam.
   $c raise ag

# Flip and move
   $c scale all 0 0 1 -1
   $c move all 120 430

   eval itk_initialize $args
}

itcl::body OpticsView::update {} {

# Set the visibiliy of elements of the drawing according to the state of
# the configuration options.

   set c $itk_component(canvas)

# Configure the M1 cover
   switch $itk_option(-m1cover) {
      "CLOSED" {
         $c itemconfigure M1coverCl -fill black
         $c itemconfigure M1coverOp -fill ""
      }
      "MIDDLE POSITION" {
         $c itemconfigure M1coverCl -fill grey
         $c itemconfigure M1coverOp -fill ""
      }
      default {
         $c itemconfigure M1coverCl -fill ""
         $c itemconfigure M1coverOp -fill black
      }
   }

# Configure central hole cover
   switch $itk_option(-holecover) {
      "CLOSED" {
         $c itemconfigure holeCoverCl -fill black
         $c itemconfigure holeCoverOp -fill ""
      }
      "MIDDLE POSITION" {
         $c itemconfigure holeCoverCl -fill grey
         $c itemconfigure holeCoverOp -fill ""
      }
      default {
         $c itemconfigure holeCoverCl -fill ""
         $c itemconfigure holeCoverOp -fill black
      }
   }

# Configure the central baffle
   $c itemconfigure centralBaffleOp -fill ""
   $c itemconfigure centralBaffleCl -fill ""
   if { $itk_option(-centralbaffle) == "CLOSED" } {
      $c itemconfigure centralBaffleCl -fill black
   } else {
      if { $itk_option(-centralbaffle) == "OPEN" } {
         $c itemconfigure centralBaffleOp -fill black
      }
   }

# Configure the deployable baffle
   $c itemconfigure deployableBaffle0 -fill ""
   $c itemconfigure deployableBaffle1 -fill ""
   $c itemconfigure deployableBaffle2 -fill ""
   $c itemconfigure deployableBaffle3 -fill ""
   if { $itk_option(-deployablebaffle) == "RETRACTED " } {
      $c itemconfigure deployableBaffle0 -fill black
   } elseif { $itk_option(-deployablebaffle) == "NEAR IR" } {
      $c itemconfigure deployableBaffle1 -fill black
   } elseif { $itk_option(-deployablebaffle) == "VISIBLE" } {
      $c itemconfigure deployableBaffle2 -fill black
   } elseif { $itk_option(-deployablebaffle) == " EXTENDED " } {
      $c itemconfigure deployableBaffle3 -fill black
   }

# Set the M2 support colour.
   switch $itk_option(-m2sstate) {
      OFF {
         $c itemconfigure m2s -fill red
      }
      FOLLOWING {
         $c itemconfigure m2s -fill yellow
      }
      INPOSITION {
         $c itemconfigure m2s -fill green
      }
   }

# Set the PCS colour.
   switch $itk_option(-pcsstate) {
      OFF {
         $c itemconfigure pcs -fill red
      }
      MOVING {
         $c itemconfigure pcs -fill yellow
      }
      OK {
         $c itemconfigure pcs -fill green
      }
   }

# Configure the AO fold mirror
   if { $itk_option(-aofold) == "IN" } {
      $c itemconfigure AoFold -fill white
      $c itemconfigure AoFoldBck -fill black
   } else {
      $c itemconfigure AoFold -fill ""
      $c itemconfigure AoFoldBck -fill ""
   }

# Configure the science fold mirror
   $c itemconfigure ScFold -fill ""
   $c itemconfigure ScFoldUnknown -bitmap ""
   if { $itk_option(-scfold) == "PARK" } {
      set scfoldpos ""
   } else {
      set scfoldpos $itk_option(-scfold)
      if { $itk_option(-scfold) == "UNKNOWN" } {
         $c itemconfigure ScFoldUnknown -bitmap question
      } else {
         $c itemconfigure ScFold$itk_option(-scfold) -fill white
         $c itemconfigure ScFold$itk_option(-scfold)bck -fill black
      }
   }

# Configure the HRWFS fold mirror
   if { $itk_option(-hrwfs) == "IN" } {
      $c itemconfigure HrwfsFoldIn -fill white
      $c itemconfigure HrwfsFoldInBck -fill black
      $c itemconfigure HrwfsFoldOut -fill ""
      $c itemconfigure HrwfsFoldOutBck -fill ""
   } else {
      $c itemconfigure HrwfsFoldIn -fill ""
      $c itemconfigure HrwfsFoldInBck -fill ""
      $c itemconfigure HrwfsFoldOut -fill white
      $c itemconfigure HrwfsFoldOutBck -fill black
   }

# Configure the light path
   $c itemconfigure Light -fill ""
   if { $itk_option(-vignette) == 0 } {
      set l white
   } else {
      set l grey
   }
   $c itemconfigure SkyLight -fill $l

# Assume no light emerging from the ISS.
   set outport ""

   if { $itk_option(-m1cover) == "OPENED" } {
      $c itemconfigure M1Light -fill $l
      if { $itk_option(-holecover) == "OPENED" } {
         $c itemconfigure CHLight -fill $l

# Deal with the AO fold mirror position
         if { $itk_option(-aofold) != "IN" } {
            $c itemconfigure NotAoLight -fill $l
            set inport 0
         } else {
            if { $itk_option(-aopresent) == 1 } {
               $c itemconfigure AoLight -fill $l
               set inport 2
            } else {
               $c itemconfigure AoLightNoAo -fill $l
               set inport ""
            }
         }

# Determine which (if any) ISS port the beam emerges from
         if { $inport != "" } {
            if { $scfoldpos == "" } {
               if { $inport == "0" } {
                  set outport 1
               } else {
                  set outport 4
               }
            } elseif { $scfoldpos == "UNKNOWN"  || $scfoldpos == "MOVING" } {
                  set outport ""
            } else {
               if { $inport == [string index $scfoldpos 0] } {
                  set outport [string index $scfoldpos 1]
               } elseif { $inport == [string index $scfoldpos 1] } {
                  set outport [string index $scfoldpos 0]
               } else {
                  if { $inport == [string index $scfoldpos 1] } {
                     set outport [string index $scfoldpos 0]
                  } elseif { $inport == [string index $scfoldpos 0] } {
                     set outport [string index $scfoldpos 1]
                  }
               }
            }
         }
      }
   }

# Configure light from the calibration unit.
   if { [string equal $itk_option(-calunit) OPEN] } {
      $c itemconfigure IssLight4 -fill $l
      switch $scfoldpos {
         40 -
         04 {
            $c itemconfigure AoLight -fill $l
         }
         43 -
         34 {
            $c itemconfigure IssLight3 -fill $l
         }
         45 -
         54 {
            $c itemconfigure IssLight5 -fill $l
         }
         14 -
         41 {
            $c itemconfigure IssLight1 -fill $l
            set outport 1
         }
         "" {
            $c itemconfigure IssLight2 -fill $l
         }
      }
   }

# Configure the emerging beam
   if { $outport != "" } {
      $c itemconfigure IssLight${outport} -fill $l
   }

# Configure the beam from the HRWFS to the upward looking ISS face or HRWFS
   if { $outport == "1" } {
      if { $itk_option(-hrwfs) == "IN" } {
         $c itemconfigure TvInLight -fill $l
      } else {
         $c itemconfigure TvOutLight -fill $l
      }
   }

# Configure light from M2 to sky
   if { $itk_option(-centralbaffle) == "POSITION 2" } {
      $c itemconfigure M2Light -fill $l
   }
}

itcl::body OpticsView::relabel port {
   $itk_component(canvas) itemconfigure port${port}label \
         -text $itk_option(-port${port}label)
}

itcl::configbody OpticsView::aopresent {
   if { $itk_option(-aopresent) == 1 } {
      $itk_component(canvas) itemconfigure port2label -text AO
   } else {
      relabel 2
   }
}

itcl::configbody OpticsView::port2label {
   if { $itk_option(-aopresent) == 0 } {
      relabel 2
   }
}
