#+
#  ProbeView <- itk::Widget
#
#  Implements the ProbeView widget which displays the rotary table and
#  probe arm angle of a peripheral wave front sensor.
#
#  Options:
#           -probe       The probe being drawn (p1 or p2).
#
#  Methods:
#           update       Updates the display.
#
# D Terrett 13 September 2000
#
#  Copyright CCLRC
#-

itcl::class ProbeView {
   inherit itk::Widget

   constructor args {}

   public method update

   itk_option define -probe probe Probe 1 

   private method pivot {probe angle}
   private method xy {x y}
   private variable arm
   private variable ghost
   private variable piv
   private variable mirror
   private variable target
}

itk::usual ProbeView {
   keep -background -cursor -highlightcolor -highlightthickness \
         -insertbackground -insertborderwidth -insertwidth \
         -insertontime -insertofftime -selectbackground \
         -selectborderwidth -selectforeground
}

itcl::body ProbeView::constructor args {

   itk_component add canvas {
      canvas $itk_interior.canvas -width 120 -height 120
   }
   pack $itk_component(canvas)
   set c $itk_component(canvas)

# Probe arm.
   set arm [$c create line 0 0 0 0 -width 20 -capstyle projecting]

# Pickoff mirror
   set mirror [$c create oval 0 0 0 0 -fill white]

# Probe arm pivot
   set piv [$c create oval 0 0 0 0 -fill black]

# Guide Target.
   set target [$c create oval 0 0 0 0 -fill orange -outline ""]

# The shadow of the other Probe arm.
   set ghost [$c create line 0 0 0 0 -width 20 -capstyle projecting \
         -stipple gray25]

   eval itk_initialize $args
}

itcl::configbody ProbeView::probe {

# Generate a spiral polyline to represent the cable wrap.
   for { set a -220 } { $a < 220 } { incr a 10 } {
      eval lappend spiral [pivot $itk_option(-probe) $a]
   }
   set id [eval $itk_component(canvas) create line $spiral -width 5 -fill gray]
   $itk_component(canvas) lower $id $arm

# Label X & Y.
   eval $itk_component(canvas) create text [xy 490 0] -text +X -anchor c
   eval $itk_component(canvas) create text [xy -490 0] -text -X -anchor c
   eval $itk_component(canvas) create text [xy 0 490] -text +Y -anchor c
   eval $itk_component(canvas) create text [xy 0 -490] -text -Y -anchor c

# Set the stacking order of the arm and the ghost of the other arm.
   switch $itk_option(-probe) {
      p1 {
         $itk_component(canvas) lower $ghost $arm
      }
      p2 {
         $itk_component(canvas) raise $ghost $arm
      }
   }
}

itcl::body ProbeView::pivot {probe a} {
   switch $probe {
      p1 {
         set a1 [expr $a + 90.0]
      }
      p2 {
         set a1 [expr $a - 90.0]
      }
   }
   set r [expr 40.0  + $a / 50.0 ]
   set x [expr 60.0 + cos( $a1 / 57.296 ) * $r ]
   set y [expr 60.0 - sin( $a1 / 57.296 ) * $r ]
   return [list $x $y]
}

itcl::body ProbeView::xy {x y} {
   return [list [expr 60.0 + $x / 10.0] [expr 60.0 - $y / 10.0]]
}

itcl::body ProbeView::update {} {

# Update the coordinates of the arms according to the x/y of the wfs and 
# the angle of the pivot.
   switch $itk_option(-probe) {
      p1 {
         set p p1
         set g p2
        }
      p2 {
         set p p2
         set g p1
        }
      }
      set a [sadVal agssad ${p}TableAngle ""]
      set x [sadVal agssad ${p}X ""]
      set y [sadVal agssad ${p}Y ""]
      set ag [sadVal agssad ${g}TableAngle ""]
      set xg [sadVal agssad ${g}X ""]
      set yg [sadVal agssad ${g}Y ""]

   if { $a != "" && $x != "" && $y != "" } {
      foreach {x y} [xy $x $y] {}
      foreach {px py} [pivot $p $a] {}
      $itk_component(canvas) coords $arm $px $py $x $y

# Re-position the pickoff mirror and pivot.
      $itk_component(canvas) coords $mirror \
            [expr {$x - 7}] [expr {$y - 7}] \
            [expr {$x + 7}] [expr {$y + 7}] 
      $itk_component(canvas) coords $piv \
            [expr {$px - 3}] [expr {$py - 3}] \
            [expr {$px + 3}] [expr {$py + 3}] 

# Set the colour according to the follow and in position state.
      if { [isFollowing agssad $itk_option(-probe)FollowS] } {
         if { [isInPosition agssad $itk_option(-probe)InPosition] } {
            $itk_component(canvas) itemconfigure $arm -fill green
         } else {
            $itk_component(canvas) itemconfigure $arm -fill yellow
         }
      } else {
         $itk_component(canvas) itemconfigure $arm -fill red
      }
   } else {
      $itk_component(canvas) itemconfigure $arm -fill red

   }
   if { $ag != "" && $xg != "" && $yg != "" } {
      foreach {x y} [xy $xg $yg] {}
      foreach {px py} [pivot $g $ag] {}
      $itk_component(canvas) coords $ghost $px $py $x $y
    }

# Update target position.
   switch $itk_option(-probe) {
      p1 {
         set x [sadVal tcssad pwfs1XDemand ""]
         set y [sadVal tcssad pwfs1YDemand ""]
      }
      p2 {
         set x [sadVal tcssad pwfs2XDemand ""]
         set y [sadVal tcssad pwfs2YDemand ""]
      }
   }
   if { $x != "" && $y != "" } {
      foreach {x y} [xy $x $y] {}
      $itk_component(canvas) coords $target \
            [expr {$x - 3}] [expr {$y - 3}] \
            [expr {$x + 3}] [expr {$y + 3}] 
   }
}
