#+
#  RcPanel <- Panel
#
#  Implements the RcPanel widget. A Panel widget with a RemoteControl
#  widget packed into its interior
#
#  Options:
#           none
#
#  Methods:
#           none
#
#  D Terrett 13 August 1998
#
#  Copyright CCLRC
#+

itcl::class RcPanel {
   inherit Panel

   constructor args {}
}

itk::usual RcPanel {
   keep -activebackground -activeborderwidth -activeforeground \
        -background -borderwidth -cursor -disabledforeground \
        -foreground -font -highlightcolor -highlightthickness \
        -insertbackground -insertborderwidth -insertofftime -insertontime \
        -insertwidth -labelfont -popupcursor -selectbackground \
        -selectborderwidth -selectforeground -textbackground -textfont
}

itcl::body RcPanel::constructor args {

   itk_component add rc {
      RemoteControl $itk_interior.rc
   }

   pack $itk_component(rc) -fill both -expand y

   set itk_option(-windows) $itk_component(rc)

   eval itk_initialize $args
}
