#+
#  RemoteControl <- itk::widget
#
#  Implements the RemoteControl widget; a widget with controls for setting
#  the configurable aspects of the main status display.
#
#  Options:
#           none
#
#  Methods:
#           none
#
#  D Terrett 6 April 2000
#
#  Copyright CCLRC
#-

itcl::class RemoteControl {
   inherit itk::Widget

   constructor args {}

   private method config {}
}

itk::usual RemoteControl {
   keep -activebackground -activeborderwidth -activeforeground \
         -background -borderwidth -disabledforeground -cursor \
         -foreground -font -highlightcolor -highlightthickness \
         -popupcursor -labelfont
}

itcl::body RemoteControl::constructor args {

# Frame for target configuration controls.
   itk_component add target {
      frame $itk_interior.target -bd 2 -relief sunken
   }
   pack $itk_component(target) -padx 2 -pady 2 -fill x -expand y
   set w $itk_component(target)

   itk_component add tlabel {
      label $w.tlabel -text "Target Display"
   }
   itk_component add vt {
      iwidgets::optionmenu $w.vt -labeltext VT \
            -command [code $this config]
   }
   $itk_component(vt) insert end "Source A" "Source B"
   pack $itk_component(tlabel) -pady 4
   pack $itk_component(vt)

   eval itk_initialize $args
}


itcl::body RemoteControl::config {} {
   if [winfo exist .numericPanel] {
      switch [$itk_component(vt) get] {
         "Source A" {set vt sourceA}
         "Source B" {set vt sourceB}
         "Source C" {set vt sourceC}
         PWFS1 {set vt pwfs1}
         PWFS2 {set vt pwfs2}
         OIWFS {set vt oiwfs}
         Mount {set vt mount}
      }
      .numericPanel configure -vt $vt
   }
}
