#+
#  AoConfig <- itk::Widget
#
#  Implements the AoConfig widget that displays a summary of the state of
#  the acitve optics.
#
#  Methods:
#           update       Updates the display.
#
# D Terrett 21 January 2003
#
#  Copyright CCLRC
#-

itcl::class AoConfig {
   inherit itk::Widget
   constructor args {}
   public {
      method update {}
      method isLoopClosed {}
   }
   
   protected method isGuideActive {guideSA}
}

itk::usual AoConfig {
   keep -background -cursor -font 
   keep -background -cursor -foreground -font -labelfont
}

itcl::body AoConfig::constructor args {

# Create status acceptors.
   if { [catch {sa guideConfig info}] } {
      epics sa guideConfig
   }

   if { [catch {sa miscstatus info}] } {
      epics sa miscstatus
   }
   
   if { [catch {sa pwfs1Guide info}] } {
      epics sa pwfs1Guide
   }
   if { [catch {sa pwfs2Guide info}] } {
      epics sa pwfs2Guide
   }
   if { [catch {sa oiwfsGuide info}] } {
      epics sa oiwfsGuide
   }
   if { [catch {sa g1Guide info}] } {
      epics sa g1Guide
   }
   if { [catch {sa g2Guide info}] } {
      epics sa g2Guide
   }
   if { [catch {sa g3Guide info}] } {
      epics sa g3Guide
   }
   if { [catch {sa g4Guide info}] } {
      epics sa g4Guide
   }

# Frame for chop/nod border.
   itk_component add frame {
      frame $itk_interior.frame -borderwidth 2 -relief groove
   }
   set w $itk_component(frame)

# Chop/Nod state
   itk_component add chnod {
      StatusField $w.chnod -entryborder 1 -entryrelief sunken -labeltext "Chop/Nod:" -labelpos w
   }

# M1 figure.
   itk_component add m1fig {
      StatusField $w.m1fig -entryborder 1 -entryrelief sunken -labeltext "M1 Fig:" -labelpos w
   }

# M2 configuration in both chop states
   itk_component add ttf {
      StatusField $w.ttf -entryborder 1 -entryrelief sunken -labeltext "TTF:" -labelpos w
   }

# Coma correction.   
   itk_component add coma {
       StatusField $w.coma -entryborder 1 -entryrelief sunken -labeltext "Coma:" -labelpos w
   }

   grid $itk_component(chnod) -sticky e -row 0 -column 0 -padx 3 -pady 3
   grid $itk_component(ttf)   -sticky e -row 0 -column 1 -padx {0 3} -pady 3
   grid $itk_component(m1fig) -sticky e -row 1 -column 0 -padx 3 -pady {0 3}
   grid $itk_component(coma)  -sticky e -row 1 -column 1 -padx {0 3} -pady {0 3}

   pack $itk_component(frame) -fill x

# Inposition Override Enabled Message
   itk_component add aomesg {
      label $itk_interior.aomesg -borderwidth 0
   }

   itk_component add agmesg {
      label $itk_interior.agmesg -borderwidth 0
   }

   pack $itk_component(agmesg)
   pack $itk_component(aomesg)

   eval itk_initialize $args
}

# Check if guider is active for any nod/chop position
itcl::body AoConfig::isGuideActive {guideSA} {
   set ret false
   foreach ch {nodachopa nodachopb nodbchopa nodbchopb} {
      if {"[sa $guideSA get $ch]" eq "On"} {
         set ret true
         break
      }
   }
   return $ret
}

itcl::body AoConfig::update {} {

   # Chop/Nod
   set p1chnod [isGuideActive pwfs1Guide]
   set p2chnod [isGuideActive pwfs2Guide] 
   set oichnod [isGuideActive oiwfsGuide]
   
   if {[sa miscstatus get ao] eq "Yes"} {
      if {"$::env(GEMINI_SITE)" eq "CP"} {
         set aochnod false
         foreach {guider guiderMap} {g1Guide g1MapName g2Guide g2MapName g3Guide g3MapName g4Guide g4MapName } {
            if { "[sa tcssad get $guiderMap]" ne "NONE" && [isGuideActive $guider] } {
               set aochnod true
               break
            }
         }
      } else {
         set aochnod $p2chnod
      }
      set p2chnod false
   } else {
      set aochnod false
   }

   set source ""
   if { $aochnod } {
       set source "GAOS"
   }
   if { $p1chnod } {
      append source "P1" 
   }
   if { $p2chnod } {
      append source "P2"
   }
   if { $oichnod } {
      append source "OI"
   }

   if { $source eq "" } {
      $itk_component(chnod) configure -text "OFF" -status none
   } else {
      if { [isLoopClosed] } {
         $itk_component(chnod) configure -text "$source" -status ok
      } else {
         $itk_component(chnod) configure -text "$source" -status none
      }
   }

   # TTF
   set p1guide [sa m2ssad get p1GuideConfig value]
   set p2guide [sa m2ssad get p2GuideConfig value]
   set oiguide [sa m2ssad get oiGuideConfig value]
   set aoguide [sa m2ssad get aoGuideConfig value]

   set ttfSource ""
   if { [sa miscstatus get on value] == "On" } {
      if { [string match *A-AUTO* $p1guide] } {
         append ttfSource "P1" 
      }
      if { [string match *A-AUTO* $p2guide] } {
         append ttfSource "P2"
      }
      if { [string match *A-AUTO* $oiguide] } {
         append ttfSource "OI"
      }
      if { [string match *A-AUTO* $aoguide] } {
         append ttfSource "AO"
      }
      if { [isLoopClosed] } {
         $itk_component(ttf) configure -text "$ttfSource" -status ok
      } else {
         $itk_component(ttf) configure -text "$ttfSource" -status none
      }
   } else {
      $itk_component(ttf) configure -text "OFF" -status none
   }

   # aO
   if { [sa guideConfig get m1state value] == "On" } {
      set source "[sa guideConfig get m1GuideSource value]"
      switch $source {
      PWFS1 {set source P1}
      PWFS2 {set source P2}
      OIWFS {set source OI}
      HRWFS {set source HR}
      }
      $itk_component(m1fig) configure -text $source -status ok
   } else {
      $itk_component(m1fig) configure -text "OFF" -status none
   }

   # Coma
   set coma_status [sa guideConfig get coma value]

   if { $coma_status eq "On" } {
      if {[string match *P1* $ttfSource] || [string match *AO* $ttfSource] } {
         $itk_component(coma) configure -text "ON" -status ok
      } else {
         $itk_component(coma) configure -text "ON" -status none
      } 
      
   } else {
      $itk_component(coma) configure -text "OFF" -status none
   }

   # Inposition overrides enabled warnings
   if { ( $::env(GEMINI_SITE) eq "CP" && [sa miscstatus get aomov value] == "enabled" ) \
      || ( $::env(GEMINI_SITE) eq "MK" && [sa miscstatus get aoov value] == "enabled" ) } {
       $itk_component(aomesg) configure -text "AO Inpos Override Enabled" -background red
   } else {
       $itk_component(aomesg) configure -text "" -background [$itk_interior cget -background]
   }

   if { [sa miscstatus get agov value] == "enabled" } {
       $itk_component(agmesg) configure -text "A&G Inpos Override Enabled"
       $itk_component(agmesg) configure -background red
   } else {
       $itk_component(agmesg) configure -text ""
       $itk_component(agmesg) configure -background [$itk_interior cget -background]
   }
}

itcl::body AoConfig::isLoopClosed {} {
   #Check M2
   if { [sa guideConfig get m2state value] != "On" } {
         return false
   }
   #Check mount offload
   set flag [sa guideConfig get absorbtilt value]
   if { ![string is integer -strict $flag] || $flag <= 0 } {
      return false
   }
   return true
}
