#+
#  AoConfig <- itk::Widget
#
#  Implements the AoConfig widget that displays a summary of the state of
#  the acitve optics.
#
#  Methods:
#           update       Updates the display.
#
# D Terrett 21 January 2003
#
#  Copyright CCLRC
#-

itcl::class AoConfig {
   inherit itk::Widget
   constructor args {}
   public {
      method update {}
   }
}

itk::usual AoConfig {
   keep -background -cursor -font 
   keep -background -cursor -foreground -font -labelfont
}

itcl::body AoConfig::constructor args {

# Create status acceptors.
   if { [catch {sa guideConfig info}] } {
      epics sa guideConfig
   }

   if { [catch {sa miscstatus info}] } {
      epics sa miscstatus
   }

# Frame for chop/nod border.
   itk_component add frame {
      frame $itk_interior.frame -borderwidth 2 -relief ridge
   }
   set w $itk_component(frame)




# Chop/Nod state
   itk_component add chnod {
      StatusField $w.chnod -entryborder 3 -entryrelief groove -labeltext "Chop/Nod:" -labelpos w
   }





# M1 figure.
   itk_component add m1fig {
      StatusField $w.m1fig -entryborder 3 -entryrelief groove -labeltext "M1Fig:" -labelpos w
   }

# M2 configuration in both chop states
   itk_component add ttf {
      StatusField $w.ttf -entryborder 3 -entryrelief groove -labeltext "TTF:" -labelpos w
   }

# Coma correction.   
   itk_component add coma {
       StatusField $w.coma -entryborder 3 -entryrelief groove -labeltext "Coma:" -labelpos w
   }

   grid $itk_component(chnod) -sticky e -row 0 -column 0
   grid $itk_component(ttf)   -sticky w -row 0 -column 1 
   grid $itk_component(m1fig) -sticky e -row 1 -column 0
   grid $itk_component(coma)  -sticky w -row 1 -column 1

   pack $itk_component(frame)



# Inposition Override Enabled Message
   itk_component add aomesg {
      label $itk_interior.aomesg -borderwidth 0
   }

   itk_component add agmesg {
      label $itk_interior.agmesg -borderwidth 0
   }

   pack $itk_component(agmesg)
   pack $itk_component(aomesg)


   eval itk_initialize $args
}


itcl::body AoConfig::update {} {



   # Chop/Nod


   set p1chnod [sa miscstatus get p1 value]
   set p2chnod [sa miscstatus get p2 value]
   set oichnod [sa miscstatus get oi value]
   set aochnod [sa miscstatus get ao value]

   set source ""
   if { [string match *Yes* $aochnod] } {
       set source "GAOS"
   } else {
      if { [string match *On* $p1chnod] } {
         append source "P1" 
      }
      if { [string match *On* $p2chnod] } {
         append source "P2"
      }
      if { [string match *On* $oichnod] } {
         append source "OI"
      }
   }

   if { $source eq "" } {
      $itk_component(chnod) configure -text "OFF" -status none
   } else {
      $itk_component(chnod) configure -text "$source" -status ok
   }




   # TTF


   set p1guide [sa m2ssad get p1GuideConfig value]
   set p2guide [sa m2ssad get p2GuideConfig value]
   set oiguide [sa m2ssad get oiGuideConfig value]
   set aoguide [sa m2ssad get aoGuideConfig value]


   if { [sa miscstatus get on value] == "On" } {
      set source ""

      if { [string match *A-AUTO* $p1guide] } {
         append source "P1" 
      }
      if { [string match *A-AUTO* $p2guide] } {
         append source "P2"
      }
      if { [string match *A-AUTO* $oiguide] } {
         append source "OI"
      }
      if { [string match *A-AUTO* $aoguide] } {
         append source "AO"
      }
      $itk_component(ttf) configure -text "$source" -status ok
   } else {
      $itk_component(ttf) configure -text "OFF" -status none
   }





   # aO


   if { [sa guideConfig get m1state value] == "On" } {
      $itk_component(m1fig) configure -text "[sa guideConfig get m1GuideSource value]" -status ok
   } else {
      $itk_component(m1fig) configure -text "OFF" -status none
   }



   # Coma


   set coma_status [sa guideConfig get coma value]

   if { $coma_status eq "On" } {
      $itk_component(coma) configure -text "ON" -status ok
   } else {
      $itk_component(coma) configure -text "OFF" -status none
   }




   # Inposition overrides enabled warnings


   if { [sa miscstatus get aoov value] == "enabled" } {
       $itk_component(aomesg) configure -text "AO Inpos Override Enabled"
       $itk_component(aomesg) configure -background red
   } else {
       $itk_component(agmesg) configure -text ""
       $itk_component(agmesg) configure -background [$itk_interior cget -background]
   }

   if { [sa miscstatus get agov value] == "enabled" } {
       $itk_component(agmesg) configure -text "A&G Inpos Override Enabled"
       $itk_component(agmesg) configure -background red
   } else {
       $itk_component(aomesg) configure -text ""
       $itk_component(aomesg) configure -background [$itk_interior cget -background]
   }
}
