#+
#  DomeView <- itk:Widget 
#
#  Plots a view of the dome on a canvas.
#
#  Options:
#           none
#
#  Methods:
#           update          Updates the view with the current state of the
#                           telescope.
#
#  D Terrett 1 May 2001
#
#  Copyright CCLRC
#-

itcl::class DomeView {
   inherit itk::Widget
   constructor args {}
   public {
      method update {}
   }
}

itk::usual DomeView {
   keep -background -cursor -highlightcolor -highlightthickness \
         -insertbackground -insertborderwidth -insertwidth -insertontime \
         -insertofftime -selectbackground -selectborderwidth -selectforeground
}

itcl::body DomeView::constructor args {

   if { [catch {sa ecssad info}] } {
      epics sa ecssad
   }

   itk_component add ahus {
      frame $itk_interior.ahus
   }

   itk_component add ecsAhu2 {
      label $itk_interior.ahus.ecsAhu2 -text "AHU_2"
   }

   itk_component add ecsAhu3 {
      label $itk_interior.ahus.ecsAhu3 -text "AHU_3"
   }

   itk_component add ecsAhu4 {
      label $itk_interior.ahus.ecsAhu4 -text "AHU_4"
   }

   itk_component add ecsAhu5 {
      label $itk_interior.ahus.ecsAhu5 -text "AHU_5"
   }

   pack $itk_component(ecsAhu2) $itk_component(ecsAhu3) $itk_component(ecsAhu4) $itk_component(ecsAhu5) -side left -padx 5

   itk_component add vign {
      label $itk_interior.vign
   }
   
   itk_component add ecsFault {
      label $itk_interior.ecsFault
   }

   itk_component add domeview {
      canvas $itk_interior.domeview -width 340 -height 340
   }

# Create view of dome etc.
   $itk_component(domeview) create domeview 170 170 -tags domeview

# Create wind direction indicator.
   $itk_component(domeview) create line 0 0 0 0 -arrow first \
         -tags {wind arrow} -width 2
   $itk_component(domeview) create line 0 0 0 0 -arrow none -tags {wind bar} \
         -width 2
   $itk_component(domeview) create text 310 0 -anchor n -text WIND -tags wind

   pack $itk_component(ahus) $itk_component(domeview) $itk_component(vign) $itk_component(ecsFault)

   eval itk_initialize $args
}

itcl::body DomeView::update {} {



# Update dome view.
   $itk_component(domeview) itemconfigure domeview -display 1

# Redraw wind speed indicator.
   set wd [expr { [sadVal tcssad currentWindDir 0] / 57.29577951 }]
   set cwd [expr {cos($wd)}]
   set swd [expr {sin($wd)}]
   $itk_component(domeview) coords arrow [expr {310.0 - 25.0 * $swd}] \
         [expr {40.0 + 25.0 * $cwd}]  [expr {310.0 + 27.0 * $swd}] \
         [expr {40.0 - 27.0 * $cwd}]
   $itk_component(domeview) coords bar [expr {310.0 + 20.0 * $cwd}] \
         [expr {40.0 + 20.0 * $swd}]  [expr {310.0 - 20.0 * $cwd}] \
         [expr {40.0 - 20.0 * $swd}]

# Colour it red if the speed exceeds 80kmh (50mph).
   if { [sadVal tcssad currentWindSpeed 0] > 80.0 } {
      $itk_component(domeview) itemconfigure wind -fill red
   } else {
      $itk_component(domeview) itemconfigure wind -fill black
   }

# Determine whether there is any vignetting from the enclosure.
   set v [expr {[sadVal tcssad domeVignette -1] * 100.}]

   if { $v > 0.0 } {
      $itk_component(vign) configure -foreground black
      $itk_component(vign) configure -text "Dome Vignetting ${v} %"
      $itk_component(vign) configure -foreground red
   } elseif { $v == 0 } {
      $itk_component(vign) configure -foreground green
      $itk_component(vign) configure -text "No Dome Vignetting" 
      $itk_component(vign) configure -foreground green
   }

# ECS Faults
   set domeF [sa ecssad get domeFault ] 
   set evgF  [sa ecssad get evgFault ] 
   set wvgF  [sa ecssad get wvgFault ] 
   set tshF  [sa ecssad get tshFault ] 
   set bshF  [sa ecssad get bshFault ] 
   set fltMes ""
   if { $domeF == 4 } {
   	set fltMes "$fltMes Dome:OFL, "
   } elseif { $domeF == 5 } {
   	set fltMes "$fltMes Dome:ERR, "
   }
   if { $evgF == 4 } {
   	set fltMes "$fltMes EVG:OFL, "
   } elseif { $evgF == 5 } {
   	set fltMes "$fltMes EVG:ERR, "
   }
   if { $wvgF == 4 } {
   	set fltMes "$fltMes WVG:OFL, "
   } elseif { $wvgF == 5 } {
   	set fltMes "$fltMes WVG:ERR, "
   }
   if { $tshF == 4 } {
   	set fltMes "$fltMes TSH:OFL, "
   } elseif { $tshF == 5 } {
   	set fltMes "$fltMes TSH:ERR, "
   }
   if { $bshF == 4 } {
   	set fltMes "$fltMes BSH:OFL "
   } elseif { $bshF == 5 } {
   	set fltMes "$fltMes BSH:ERR "
   }
   if { $fltMes != "" } {
      $itk_component(ecsFault) configure -foreground red
   }       

   $itk_component(ecsFault) configure -text $fltMes

# Check that AHUs are turned OFF, otherwise, display warning in RED

   if {[string first "OFF" [sa ecssad get ahu2]] >= 0} {
       $itk_component(ecsAhu2) configure -text "    "
   } else {
       $itk_component(ecsAhu2) configure -text AHU_2
   }

   if {[string first "OFF" [sa ecssad get ahu3]] >= 0} {
       $itk_component(ecsAhu3) configure -text "    "
   } else {
       $itk_component(ecsAhu3) configure -text AHU_3
   }

   if {[string first "OFF" [sa ecssad get ahu4]] >= 0} {
       $itk_component(ecsAhu4) configure -text "    "
   } else {
       $itk_component(ecsAhu4) configure -text AHU_4
   }

   if {[string first "OFF" [sa ecssad get ahu5]] >= 0} {
       $itk_component(ecsAhu5) configure -text "    "
   } else {
       $itk_component(ecsAhu5) configure -text AHU_5
   }

   $itk_component(ecsAhu2) configure -foreground red
   $itk_component(ecsAhu3) configure -foreground red
   $itk_component(ecsAhu4) configure -foreground red
   $itk_component(ecsAhu5) configure -foreground red
}
