#+
#  NumericDisplay <- itk::widget
#
#  Implements the NumericDisplay widget.
#
#  Options:
#          none
#
#  Methods
#          update      Updates the display from the SAD
#
#  options
#
#  D Terrett 22 January 2004
#
#  Copyright CCLRC
#-

itcl::class NumericDisplay {
   inherit itk::Widget
   constructor args {}
   destructor {}
   itk_option define -eng eng Eng 0 {}
   itk_option define -dst dst DST 0 {}
   public {
      method update {}
   }
   private {
      method newtarget {record value}
      method newobject {record value}
      method inPosition {rec value}
      method noheartbeat {}
      method heartbeat {rec value}
      method inposreason {}
      variable nohbid
      variable hbid
      variable chopdead 0
      variable lastchop ""
   }
}

itk::usual NumericDisplay {
   keep -background -cursor -foreground -font -labelfont
   keep -highlightcolor -highlightthickness
   keep -background -cursor
   keep -highlightcolor -highlightthickness
}

itcl::body NumericDisplay::constructor args {

   # Frame for object & time display.
   set w $itk_interior
   itk_component add objtime {
      frame $w.objtime
   }
   set w $itk_component(objtime)

   # First row: TCS status and in position state
   itk_component add status {
      StatusField $w.status -entryborder 1 -entryrelief sunken \
            -labeltext "TCS STATUS:" -labelpos w
   }
   itk_component add inpos {
      StatusField $w.inpos -entryborder 1 -entryrelief sunken \
            -labeltext "IN POSITION:" -labelpos w
   }
   grid $itk_component(status) - $itk_component(inpos) -sticky ew -pady 3 -padx 3
   grid configure $itk_component(inpos) -padx {0 3}

   # Object name and wavelength.
   itk_component add objlab {
      label $w.objlab -text "OBJECT NAME:" -borderwidth 0
   }
   itk_component add objname {
      label $w.objname -anchor w -borderwidth 1 -relief sunken
   }
   itk_component add wavelab {
      label $w.wavelab -text "WAVELENGTH:" -borderwidth 0
   }
   itk_component add tarwavel {
      label $w.tarwavel -width 8 -borderwidth 1 -relief sunken
   }
   grid $itk_component(objlab) $itk_component(objname) - \
      $itk_component(wavelab) $itk_component(tarwavel) -sticky e -pady {0 3} -padx {0 3}
   grid configure $itk_component(objlab) -padx 3
   grid configure $itk_component(objname) -sticky ew
   grid configure $itk_component(tarwavel) -sticky w

   # Base position, LST and airmass and zenith distance.
   itk_component add baselab {
      label $w.baselab -text "BASE:" -borderwidth 0
   }
   itk_component add base1 {
      StatusField $w.base1 -labelmargin 5 -width 11 -entryborder 1 \
            -entryrelief sunken
   }
   itk_component add base2 {
      StatusField $w.base2 -labelmargin 5 -width 11 -entryborder 1 \
            -entryrelief sunken
   }

   itk_component add lst {
      StatusField $w.lst -labeltext LST: -labelmargin 5 -entryborder 1 \
            -entryrelief sunken
   }
   [$itk_component(lst) component label] configure -width 4 -anchor e
   itk_component add am {
      StatusField $w.am -labeltext AM: -labelmargin 5 -entryborder 1 \
            -entryrelief sunken
   }
   itk_component add zd {
      StatusField $w.zd -labeltext ZD: -labelmargin 5 -entryborder 1 \
            -entryrelief sunken
   }

   grid $itk_component(baselab) $itk_component(base1) $itk_component(base2) \
      $itk_component(lst) $itk_component(am) $itk_component(zd) \
      -sticky e -pady {0 3} -padx {0 3}
   grid configure $itk_component(baselab) -padx 3
   grid configure $itk_component(lst) $itk_component(am) $itk_component(zd) \
      -sticky w

   grid columnconfigure $w 6 -weight 1
   # Current position, hour angle and UTC.
   itk_component add tarlab {
      label $w.tarlab -text CURRENT: -borderwidth 0
   }
   itk_component add tar1 {
      StatusField $w.tar1 -labelmargin 5 -width 11 -entryborder 1 \
            -entryrelief sunken

   }
   itk_component add tar2 {
      StatusField $w.tar2 -labelmargin 5 -width 11 -entryborder 1 \
            -entryrelief sunken
   }

   itk_component add ha {
      StatusField $w.ha -labeltext HA: -labelmargin 5 -width 8 -entryborder 1 \
            -entryrelief sunken
   }
   [$itk_component(ha) component label] configure -width 4 -anchor e
   itk_component add utc {
      StatusField $w.utc -labeltext UTC: -labelmargin 5 -entryborder 1 \
            -entryrelief sunken
   }
   [$itk_component(utc) component label] configure -width 4 -anchor e
   grid $itk_component(tarlab) $itk_component(tar1) $itk_component(tar2) \
      $itk_component(ha) $itk_component(utc) - -sticky e -pady {0 3} -padx {0 3}
   grid configure $itk_component(tarlab) -padx 3
   grid configure $itk_component(utc) -sticky w

   # Offset position and HST.
   itk_component add offlab {
      label $w.offlab -text "OFFSET (arcsec):" -borderwidth 0
   }
   itk_component add off1 {
      StatusField $w.off1 -labelmargin 5 -width 8 -entryborder 1 \
            -entryrelief sunken -anchor e
   }
   itk_component add off2 {
      StatusField $w.off2 -labelmargin 5 -width 8 -entryborder 1 \
            -entryrelief sunken -anchor e
   }

   itk_component add hflag {
      label $w.hflag -image hawaii_flag -borderwidth 0
   }
   itk_component add hst {
      StatusField $w.hst -labeltext HST: -labelmargin 5 -entryborder 1 \
            -entryrelief sunken
   }
   [$itk_component(hst) component label] configure -width 4 -anchor e
   grid  $itk_component(offlab) $itk_component(off1) $itk_component(off2)\
      $itk_component(hflag) $itk_component(hst) - -sticky e -pady {0 3} -padx {0 3}
   grid configure $itk_component(offlab) -padx 3 
   grid configure $itk_component(hst) -sticky w

   # Track rates and Chilean local time.
   itk_component add ratelab {
      label $w.ratelab -text "TRACK RATE (arcsec/hr):" -borderwidth 0
   }
   itk_component add rate1 {
      StatusField $w.rate1 -labelmargin 5 -width 11 -entryborder 1 \
            -entryrelief sunken -anchor e
   }
   itk_component add rate2 {
      StatusField $w.rate2 -labelmargin 5 -width 11 -entryborder 1 \
            -entryrelief sunken -anchor e
   }
   itk_component add cflag {
      label $w.cflag -image chile_flag -borderwidth 0
   }
   itk_component add clt {
      StatusField $w.clt -labelmargin 5 -entryborder 1 \
            -entryrelief sunken
   }
   [$itk_component(clt) component label] configure -width 4 -anchor e
   grid $itk_component(ratelab) $itk_component(rate1) $itk_component(rate2) \
      $itk_component(cflag) $itk_component(clt) - -sticky e -pady {0 2} -padx {0 3}
   grid configure $itk_component(ratelab) -padx 3
   grid configure $itk_component(clt) -sticky w

   # Chop throw, IPA and seeing.
   itk_component add choplab {
      label $w.choplab -text "CHOP THROW (arcsec):" -borderwidth 0
   }
   itk_component add chop1 {
      StatusField $w.chop1 -labelmargin 5 -width 8 -entryborder 1 \
            -entryrelief sunken -anchor e
   }
   itk_component add chop2 {
      StatusField $w.chop2 -labelmargin 5 -width 8 -entryborder 1 \
            -entryrelief sunken -anchor e
   }
   itk_component add ipa {
      StatusField $w.ipa -width 6 -entryborder 1 \
            -entryrelief sunken -anchor e -labeltext IPA:
   }
   [$itk_component(ipa) component label] configure -width 4 -anchor e

   # Seeing estimate from WFS.
   itk_component add seeing {
      frame $w.seeing -borderwidth 2 -relief groove
   }
   set w $itk_component(seeing)
   itk_component add seelab {
      label $w.seelab -text "SEEING (V)" -borderwidth 0
   }
   itk_component add seep2 {
      StatusField $w.seep2 -labeltext P2 -labelpos w -entryborder 1 \
            -entryrelief sunken -width 5
   }
   [$itk_component(seep2) component label] configure -width 2 -anchor e
   itk_component add seeoi {
      StatusField $w.seeoi -labeltext OI -labelpos w -entryborder 1 \
            -entryrelief sunken -width 5
   }
   itk_component add seeao {
      StatusField $w.seeao -labeltext AO -labelpos w -entryborder 1 \
            -entryrelief sunken -width 5
   }
   [$itk_component(seeoi) component label] configure -width 2 -anchor e
   pack $itk_component(seelab) -padx 3 -pady 3
   pack $itk_component(seep2) $itk_component(seeoi) $itk_component(seeao) -side left \
      -pady {0 3} -padx {0 3}
   pack configure $itk_component(seep2) -padx 3
   #   grid $itk_component(seelab) - -sticky news
   #   grid $itk_component(seep2) $itk_component(seeoi) -sticky news
   #   grid $itk_component(seeao) - -sticky ns

   set w $itk_component(objtime)

   grid $itk_component(choplab) $itk_component(chop1) $itk_component(chop2) \
      $itk_component(ipa) $itk_component(seeing) - -sticky e -pady {0 3} -padx {0 3}
   grid configure $itk_component(choplab) -padx 3
   grid configure $itk_component(ipa) -sticky w

   # Instrument origin and IAA. and  P and Q, Observatory Mode

   itk_component add instrolab {
      label $w.instrolab -text "INSTR Origin (arcsec):" -borderwidth 0
   }
   itk_component add instrop {
      StatusField $w.instrop -labelmargin 5 -width 6 -entryborder 1 \
            -entryrelief sunken -anchor e -labeltext X
   }
   itk_component add instroq {
      StatusField $w.instroq -labelmargin 5 -width 6 -entryborder 1 \
            -entryrelief sunken -anchor e -labeltext Y
   }

   itk_component add instrlab {
      label $w.instrlab -text "INSTR Offset (arcsec):" -borderwidth 0
   }
   itk_component add iaa {
      StatusField $w.iaa -width 6 -entryborder 1 \
            -entryrelief sunken -anchor e -labeltext IAA:
   }
   [$itk_component(iaa) component label] configure -width 4 -anchor e

   itk_component add instrp {
      StatusField $w.instrp -labelmargin 5 -width 6 -entryborder 1 \
            -entryrelief sunken -anchor e -labeltext P
   }
   itk_component add instrq {
      StatusField $w.instrq -labelmargin 5 -width 6 -entryborder 1 \
            -entryrelief sunken -anchor e -labeltext Q
   }
   itk_component add obslab {
      label $w.obslab -text "ObsMode:" -borderwidth 1 -text "ObsMode: "
   }
   itk_component add obsmode {
      label  $w.obsmode -anchor e
   }

   grid $itk_component(instrolab) $itk_component(instrop) $itk_component(instroq) \
      $itk_component(iaa) -sticky e -pady {0 3} -padx {0 3}
   grid $itk_component(instrlab) $itk_component(instrp) $itk_component(instrq) x $itk_component(obslab) $itk_component(obsmode) -sticky e -pady {0 3} -padx {0 3}
   grid configure $itk_component(instrlab) -padx 3
   grid configure $itk_component(instrolab) -padx 3
   grid configure $itk_component(iaa) -sticky w
   grid configure $itk_component(obsmode) -sticky s



   eval itk_initialize $args

   if {$itk_option(-eng) == 1} {
      itk_component add instrx {
	   StatusField $w.instrx -labelmargin 5 -width 6 -entryborder 1 \
	       -entryrelief sunken -anchor e -labeltext X
       }
      itk_component add instry {
	   StatusField $w.instry -labelmargin 5 -width 6 -entryborder 1 \
	       -entryrelief sunken -anchor e -labeltext Y
       }
      grid x $itk_component(instrx) $itk_component(instry) -sticky e -pady {0 3} -padx {0 3}
      grid configure $itk_component(instrx) -padx 3
   }

   # Now that the grid is complete make adjustments to the row and column
   # spans.
   grid configure $itk_component(seeing) -rowspan 2
   grid configure $itk_component(inpos) -columnspan 7
   grid configure $itk_component(tarwavel) -columnspan 2

   # Frames for mechanism positions and M2.
   set w $itk_interior
   itk_component add mech {
      frame $w.mech -bd 2 -relief groove
   }
   itk_component add m2frame {
      frame $w.m2frame -borderwidth 2 -relief groove
   }

   # Telescope and Dome positions.
   set w $itk_component(mech)
   itk_component add mechlab {
      label $w.mechlab -text "Mechanical Positions" -borderwidth 0
   }
   itk_component add tellab {
      label $w.tellab -text Telescope: -borderwidth 0
   }
   itk_component add telaz {
      StatusField $w.telaz -labeltext Az -labelmargin 5 -width 13 \
            -entryborder 1 -entryrelief sunken
   }
   itk_component add telel {
      StatusField $w.telel -labeltext El -labelmargin 5 -width 13 \
            -entryborder 1 -entryrelief sunken
   }
   itk_component add rot {
      StatusField $w.rot -labeltext Rotator: -labelmargin 5 -width 10 \
            -entryborder 1 -entryrelief sunken
   }
   itk_component add errlab {
      label $w.errlab -text Errors: -borderwidth 0
   }
   itk_component add azerr {
      StatusField $w.azerr -width 13 -entryborder 1 -entryrelief sunken
   }
   itk_component add elerr {
      StatusField $w.elerr -width 13 -entryborder 1 -entryrelief sunken
   }
   itk_component add roterr {
      StatusField $w.roterr -width 10 -entryborder 1 -entryrelief sunken
   }
   itk_component add domelab {
      label $w.domelab -text Dome: -borderwidth 0
   }
   itk_component add domeaz {
      StatusField $w.domeaz -labeltext Az -labelmargin 5 -width 7 \
            -entryborder 1 -entryrelief sunken
   }
   itk_component add topshut {
      StatusField $w.topshut -labeltext Top -labelmargin 5 -width 5 \
            -entryborder 1 -entryrelief sunken
   }
   itk_component add botshut {
      StatusField $w.botshut -labeltext Bottom -labelmargin 5 -width 5 \
            -entryborder 1 -entryrelief sunken
   }
   grid $itk_component(mechlab) - - - -pady 3 -padx 3
   grid $itk_component(tellab) $itk_component(telaz) $itk_component(telel) \
      $itk_component(rot) -sticky e -pady {0 3} -padx {0 3}
   grid configure $itk_component(tellab) -padx 3 
   grid  $itk_component(errlab) $itk_component(azerr) $itk_component(elerr) \
      $itk_component(roterr) -sticky e -pady {0 3} -padx {0 3}
   grid configure $itk_component(errlab) -padx 3
   grid $itk_component(domelab) $itk_component(domeaz) \
      $itk_component(topshut) $itk_component(botshut) -sticky w -pady {0 3} -padx {0 3}
   grid configure $itk_component(topshut) -padx 3
   grid configure $itk_component(domelab) -sticky e

   # M2 tip/tilt & focus
   set w $itk_component(m2frame)
   #   itk_component add m2lab {
   #      label $w.m2lab -text M2
   #   }
   itk_component add ttlab {
      label $w.ttlab -text TIP/TILT: -borderwidth 0
   }
   itk_component add tip {
       StatusField $w.tip -labelmargin 2 -width 5 -entryborder 1 \
            -entryrelief sunken -labeltext X
   }
   itk_component add tilt {
       StatusField $w.tilt -labelmargin 2 -width 5 -entryborder 1 \
            -entryrelief sunken -labeltext Y
   }
   itk_component add poslab {
      label $w.poslab -text POSITION: -borderwidth 0
   }
   itk_component add xpos {
       StatusField $w.xpos -labelmargin 2 -width 5 -entryborder 1 \
            -entryrelief sunken -labeltext X
   }
   itk_component add ypos {
       StatusField $w.ypos -labelmargin 2 -width 5 -entryborder 1 \
            -entryrelief sunken -labeltext Y
   }

   itk_component add focus {
       StatusField $w.focus -labelmargin 2 -width 5 -entryborder 1 \
            -entryrelief sunken -labeltext "Focus (um):"
   }

   itk_component add comalab {
      label $w.comalab -text "Coma:" -borderwidth 0
   }
   itk_component add xcoma {
      StatusField $w.xcoma -labelmargin 2 -width 5 -entryborder 1 \
         -entryrelief sunken -labeltext X
   }
   itk_component add ycoma {
       StatusField $w.ycoma -labelmargin 2 -width 5 -entryborder 1 \
            -entryrelief sunken -labeltext Y
   }

   itk_component add vtklab {
      label $w.vtklab -text "VTK:" -borderwidth 0
   }
   itk_component add xvtk {
      StatusField $w.xvtk -labelmargin 2 -width 5 -entryborder 1 -entryrelief sunken -labeltext X
   }
   itk_component add yvtk {
       StatusField $w.yvtk -labelmargin 2 -width 5 -entryborder 1 -entryrelief sunken -labeltext Y
   }

   #   grid $itk_component(m2lab) -pady {0 3}
   grid $itk_component(ttlab) $itk_component(tip) $itk_component(tilt) -pady 3 -padx {0 3}
   grid configure $itk_component(ttlab) -padx 3
   grid $itk_component(poslab) $itk_component(xpos) $itk_component(ypos) -pady {0 3} -padx {0 3}
   grid configure $itk_component(poslab) -padx 3
      #   grid configure $itk_component(m2lab) -columnspan 3
   grid $itk_component(focus) - -sticky e -pady {0 3} -padx {0 3}
   grid $itk_component(comalab) $itk_component(xcoma) $itk_component(ycoma) -pady {0 3} -padx {0 3}
   grid configure $itk_component(comalab) -padx 3

   grid $itk_component(vtklab) $itk_component(xvtk) $itk_component(yvtk) -pady {0 3} -padx {0 3}
   grid configure $itk_component(vtklab) -padx 3

   # Pack the top level frames.
   pack $itk_component(objtime) -fill x -expand y
   pack $itk_component(mech) $itk_component(m2frame) -side left -anchor n \
      -padx 3 -pady 3 -expand y

   # Call newtarget whenever any of the tracking frame or wavelengths change.
   foreach vt {sourceA sourceB sourceC pwfs1 pwfs2 oiwfs mount} {
      catch {RecordMonitor tcssad.${vt}TrackFrame tcssad ${vt}TrackFrame}
      set hbid(${vt}TrackFrame) [tcssad.${vt}TrackFrame add \
         [itcl::code $this newtarget]]
      catch {RecordMonitor tcssad.${vt}TrackEq tcssad ${vt}TrackEq}
      set hbid(${vt}TrackEq) [tcssad.${vt}TrackEq add \
         [itcl::code $this newtarget]]
      catch {RecordMonitor tcssad.${vt}TrackWavelength tcssad \
            ${vt}TrackWavelength}
      set hbid(${vt}TrackWavelength) [tcssad.${vt}TrackWavelength add \
         [itcl::code $this newtarget]]
      catch {RecordMonitor tcssad.${vt}Wavelength tcssad ${vt}Wavelength}
      set hbid(${vt}Wavelength) [tcssad.${vt}Wavelength add \
         [itcl::code $this newtarget]]
   }

   # Call newobject whenever any of the input objects change.
   foreach vt {sourceA sourceB sourceC pwfs1 pwfs2 oiwfs mount} {
      catch {RecordMonitor tcssad.${vt}ObjectName tcssad ${vt}ObjectName}
      set hbid(${vt}ObjectName) [tcssad.${vt}ObjectName add \
         [itcl::code $this newobject]]
   }

   # Call inPosition whenever any of the inPosition or followS records change.
   foreach sa {mcssad mcssad mcssad crssad ecssad ecssad ecssad \
         tcssad mcssad crssad tcssad tcssad tcssad agssad aossad} \
      par {inPosition inPositionAz inPositionEl inPosition \
         domeInPos topShtrInPos botShtrInPos inPosition followS followS \
         autoMoveDome autoMoveShtrs tcsInPos InPosition inPosition} {
      catch {RecordMonitor $sa.$par $sa $par}
      set hbid($par) [$sa.$par add [itcl::code $this inPosition]]
   }

   # Execute the noheartbeat method in 5 seconds time (the heartbeat monitor
   # routine will cancel it if the heartbeat is running.
   set nohbid [after 5000 [itcl::code $this noheartbeat]]

   # Monitor the heartbeat sad record.
   catch {RecordMonitor tcssad.heartbeat tcssad heartbeat}
   set hbid(heartbeat) [tcssad.heartbeat add [itcl::code $this heartbeat]]

   # Trigger checks on the subsystem states
   inPosition mcssad.xxxx ""
   inPosition crssad.xxxx ""
   inPosition ecssad.xxxx ""

   # Update the display.
   newobject "" ""
   newtarget "" ""

   #   eval itk_initialize $args

}

itcl::body NumericDisplay::destructor {} {
   foreach vt {sourceA sourceB sourceC pwfs1 pwfs2 oiwfs mount} {
      tcssad.${vt}TrackFrame remove $hbid(${vt}TrackFrame)
      tcssad.${vt}TrackEq remove $hbid(${vt}TrackEq)
      tcssad.${vt}TrackWavelength remove $hbid(${vt}TrackWavelength)
      tcssad.${vt}ObjectName remove $hbid(${vt}ObjectName)
   }
   foreach sa {mcssad mcssad mcssad crssad ecssad ecssad ecssad \
         tcssad mcssad crssad tcssad agssad aossad} \
      par {inPosition inPositionAz inPositionEl inPosition \
         domeInPos topShtrInPos botShtrInPos inPosition \
         followS followS tcsInPos inPosition inPosition} {
      $sa.$par remove $hbid($par)
   }
   tcssad.heartbeat remove $hbid(heartbeat)
   after cancel $nohbid
}

itcl::body NumericDisplay::newtarget {record value} {
   # Updates the display when the tracking frame or wavelength changes.

   # Telescope position (in tracking frame of the mount).
   #   set system [sa tcssad get mountTrackFrame]
   #   set type ""
   #   set year ""
   #   scan [sa tcssad get mountTrackEq] "%c%d" type year
   #   set type [format "%c" $type]
   #   set wavel [sadVal tcssad mountWavelength ""]
   #   if { $wavel != "" } {
   #      set wavel "[expr {$wavel / 10000.0}] um"
   #   }
   #   if { $system == "AZEL_TOPO" } {
   #      $itk_component(telpos1) configure -labeltext Az
   #      $itk_component(telpos2) configure -labeltext El
   #   } else {
   #      $itk_component(telpos1) configure -labeltext RA
   #      $itk_component(telpos2) configure -labeltext Dec
   #   }

   # Target position.
   set system [sa tcssad get sourceATrackFrame]
   set type ""
   set year ""
   scan [sa tcssad get sourceATrackEq] "%c%d" type year
   set type [format "%c" $type]
   set wavel [sadVal tcssad sourceAWavelength ""]
   if { $wavel != "" } {
      set wavel "[expr {$wavel / 10000.0}] um"
   }
   if { $system == "AZEL_TOPO" } {
      $itk_component(tar1) configure -labeltext Az
      $itk_component(tar2) configure -labeltext El
   } else {
      $itk_component(tar1) configure -labeltext RA
      $itk_component(tar2) configure -labeltext Dec
   }
   #   switch $system {
   #      FK4 -
   #      FK5 {
   #         $itk_component(tarsys) configure -text "$system/$type$year"
   #      }
   #      APPT {
   #         $itk_component(tarsys) configure -text "Apparent"
   #      }
   #      default {
   #         $itk_component(tarsys) configure -text ""
   #      }
   #   }
   $itk_component(tarwavel) configure -text "$wavel"
}

itcl::body NumericDisplay::newobject {record value} {

   # Updates the display when the source changes.

   # Object name
   $itk_component(objname) configure \
      -text [sa tcssad get sourceAObjectName]
}

itcl::body NumericDisplay::update {} {

   # Telescope and dome position.
   #   $itk_component(telpos1) configure -text [sa tcssad get currentRA]
   #   $itk_component(telpos2) configure -text [sa tcssad get currentDec]
   #$itk_component(tar1) configure -text [sa tcssad get currentRA]
   #$itk_component(tar2) configure -text [sa tcssad get currentDec]
   #AWE: currentRA and currentDec are using channels telescopeRA and telescopeDec which are in degrees
   # Convert to human readable strings
   set ra [slaDr2tf 3 [expr [sa tcssad get currentRA]* 3.1415926 / 180]]
   set dec [slaDr2af 2 [expr [sa tcssad get currentDec]* 3.1415926 / 180]]	
   $itk_component(tar1) configure -text \
      [format "%02d:%02d:%02d.%03d" [lindex $ra 1] [lindex $ra 2] \
      [lindex $ra 3] [lindex $ra 4]]
   $itk_component(tar2) configure -text \
      [format "%s%02d:%02d:%02d.%02d" [lindex $dec 0] [lindex $dec 1] \
      [lindex $dec 2] [lindex $dec 3] [lindex $dec 4]]

   $itk_component(ipa) configure -text [sa tcssad get instrPA]
   $itk_component(iaa) configure -text [sa tcssad get instrAA]
   $itk_component(telaz) configure -text [sa tcssad get currentAz]
   $itk_component(azerr) configure -text [sa tcssad get azError]
   $itk_component(telel) configure -text [sa tcssad get currentEl]
   $itk_component(elerr) configure -text [sa tcssad get elError]
   $itk_component(rot) configure -text [sa crssad get currentRma]
   $itk_component(roterr) configure -text [sa tcssad get rmaError]
   $itk_component(domeaz) configure -text [sa ecssad get domePos]
   $itk_component(topshut) configure -text [sa ecssad get topShtrPos]
   $itk_component(botshut) configure -text [sa ecssad get botShtrPos]

   # Target
   set wavel [sadVal tcssad sourceAWavelength ""]
   if { ![catch {set demand [ast target A A [expr { $wavel / 10000.0 }] \
         [sa tcssad get sourceATrackFrame] \
         [sa tcssad get sourceATrackEq]]}] } {
      $itk_component(ha) configure -text [lindex $demand 2]
      $itk_component(zd) configure -text [lindex $demand 3]
      $itk_component(am) configure -text [lindex $demand 4]
   }

   # Observatory Mode (BFO)
   # AWE: catch if the sa does not exist (ie for GS until next year)

   if {! [catch {sa bfo info}]} {
	set baseMode [sa bfo get base]
        set summitMode [sa bfo get summit]
        set standbyMode [sa bfo get standby]
   	if ($baseMode) {$itk_component(obsmode) configure -text "Base" -foreground DarkGreen}
   	if ($summitMode) {$itk_component(obsmode) configure -text "Summit" -foreground red}
   	if ($standbyMode) {$itk_component(obsmode) configure -text "Standby" -foreground blue}
   }

   # Target info.
   set target [sa tcssad get targetA]
   set targetb [sa tcssad get targetB]

   # Offset and base and track rate
   set ra [slaDr2tf 3 [lindex $target 0]]
   set dec [slaDr2af 2 [lindex $target 1]]
   $itk_component(base1) configure -text \
      [format "%02d:%02d:%02d.%03d" [lindex $ra 1] [lindex $ra 2] \
      [lindex $ra 3] [lindex $ra 4]]
   $itk_component(base2) configure -text \
      [format "%s%02d:%02d:%02d.%02d" [lindex $dec 0] [lindex $dec 1] \
      [lindex $dec 2] [lindex $dec 3] [lindex $dec 4]]
   set off1 [expr {[lindex $target 2] * 206264.80624710}]
   if { $off1 > 648000.0 } {
      set off1 [expr { $off1 - 1296000.0 }]
   }
   set off1 [expr {$off1 * cos( [lindex $target 1] )}]
   $itk_component(off1) configure -text [format "%10.2f" $off1]
   $itk_component(off2) configure -text \
      [format "%10.2f" [expr {[lindex $target 3] * 206264.80624710}] ]
   set rate1 [expr { [sa tcssad get sourceADiffRA value] * \
         cos( [lindex $target 1] ) * 15.0 *3600}]
   set rate2 [expr { [sa tcssad get sourceADiffDec value] * 3600}]
   $itk_component(rate1) configure -text [format %.6f $rate1]
   $itk_component(rate2) configure -text [format %.6f $rate2]

   # Chop throw.
   set throw1 [expr {([lindex $targetb 0] + [lindex $targetb 2] - \
         [lindex $target 0] - [lindex $target 2]) * 206264.80624710 * \
         cos( [lindex $target 1] )}]
   if { $throw1 > 648000.0 } {
      set throw1 [expr { $throw1 - 1296000.0 }]
   }
   set throw2 [expr {([lindex $targetb 1] + [lindex $targetb 3] - \
         [lindex $target 1] - [lindex $target 3]) * 206264.80624710}]
   $itk_component(chop1) configure -text [format "%10.2f" $throw1]
   $itk_component(chop2) configure -text [format "%10.2f" $throw2]

   set xy [ast instrument A]
   if {$itk_option(-eng)} {
      $itk_component(instrx) configure \
         -text [format %.2f [expr {[lindex $xy 0] / 0.62056151}]]
      $itk_component(instry) configure \
         -text [format %.2f [expr {[lindex $xy 1] / 0.62056151}]]
   }

   # Calculate P and Q
   set instx [expr {[lindex $xy 0] / 0.62056151}]
   set insty [expr {[lindex $xy 1] / 0.62056151}]
   set iaa [expr [$itk_component(iaa) cget -text] * 3.1415926 / 180]

   #set instp [expr { - $instx * cos($iaa) + $insty * sin($iaa)}]
   #set instq [expr { - $instx * sin($iaa) - $insty * cos($iaa)}]
   #$itk_component(instrp) configure -text [format %.2f $instp]
   #$itk_component(instrq) configure -text [format %.2f $instq]

   set instop [expr {[lindex $target 4] / 0.62056151}]
   set instoq [expr {[lindex $target 5] / 0.62056151}]
   $itk_component(instrop) configure -text [format %.2f $instop]
   $itk_component(instroq) configure -text [format %.2f $instoq]

   #AWE: Offsets, need to convert to P,Q using IAA
   set instrx [expr {[lindex $target 6] / 0.62056151}]
   set instry [expr {[lindex $target 7] / 0.62056151}]
   set instrp [expr { - $instrx * cos($iaa) + $instry * sin($iaa)}]
   set instrq [expr { - $instrx * sin($iaa) - $instry * cos($iaa)}]
   $itk_component(instrp) configure -text [format %.2f $instrp]
   $itk_component(instrq) configure -text [format %.2f $instrq]

   # M2 tip/tilt/focus/X/Y.
   set tip [sa m2ssad get xtilt]
   if { [string is double -strict $tip] } {
      set tip [format %.2f [expr { $tip / 3.86956518 }]]
      $itk_component(tip) configure -text [format %.2f $tip] -status ok
      if { $tip > 8.0 || $tip < -8.0 } {
         $itk_component(tip) configure -status error
      }
   } else {
      $itk_component(tip) configure -text $tip -status error
   }
   set tilt [sa m2ssad get ytilt]
   if { [string is double -strict $tip] } {
      set tilt [format %.2f [expr { $tilt / 3.86956518 }]]
      $itk_component(tilt) configure -text [format %.2f $tilt] -status ok
      if { $tilt > 8.0 || $tilt < -8.0 } {
         $itk_component(tilt) configure -status error
      }
   } else {
      $itk_component(tilt) configure -text $tilt -status error
   }
   set xpos [sa tcssad get m2XPos]
   if { [string is double -strict $xpos] } {
      $itk_component(xpos) configure -text [format %.2f $xpos] -status ok
   } else {
      $itk_component(xpos) configure -text $xpos -status error
   }
   set ypos [sa tcssad get m2YPos]
   if { [string is double -strict $ypos] } {
      $itk_component(ypos) configure -text [format %.2f $ypos] -status ok
   } else {
      $itk_component(ypos) configure -text $ypos -status error
   }
   set focus [sa m2ssad get focus]
   if { [string is double -strict $focus] } {
      $itk_component(focus) configure -text [format %.2f $focus] -status ok
   } else {
      $itk_component(focus) configure -text $focus -status error
   }
   set xcoma [sa tcssad get m2XComaCorr]
   if { [string is double -strict $xcoma] } {
      $itk_component(xcoma) configure -text [format %.2f $xcoma] -status ok
   } else {
      $itk_component(xcoma) configure -text $xcoma -status error
   }
   set ycoma [sa tcssad get m2YComaCorr]
   if { [string is double -strict $ycoma] } {
      $itk_component(ycoma) configure -text [format %.2f $ycoma] -status ok
   } else {
      $itk_component(ycoma) configure -text $ycoma -status error
   }

   if { ![catch {set xv [sa vtk get xvtk]}] && [string is boolean -strict $xv] } {
      $itk_component(xvtk) configure -text $xv -status ok
   }

   if { ![catch {set yv [sa vtk get yvtk]}] && [string is boolean -strict $yv] } {
      $itk_component(yvtk) configure -text $yv -status ok
   }

   # Time.
   $itk_component(utc) configure -text [tccTime utc]
   $itk_component(hst) configure -text [tccTime localtime -10]
   if { $::CHILE_DAYLIGHT_SAVING || $itk_option(-dst) == 1} {
      $itk_component(clt) configure -text [tccTime localtime -3] \
         -labeltext CDT:
   } else {
      $itk_component(clt) configure -text [tccTime localtime -4] \
         -labeltext CST:
   }
   $itk_component(lst) configure -text [tccTime last]

   # Seeing
   set p1guide [sa m2ssad get p1GuideConfig]
   set p2guide [sa m2ssad get p2GuideConfig]
   set oiguide [sa m2ssad get oiGuideConfig]
   set aoguide [sa m2ssad get aoGuideConfig]

   set seeing [sa agssad get p2seeing]
   if { [string is double -strict $seeing] } {
      if { [string match *A-AUTO* $p2guide] } {
         $itk_component(seep2) configure -text [format %.2f $seeing] -status ok
      } else {
         $itk_component(seep2) configure -text [format %.2f $seeing] -status none
      }
   } else {
      $itk_component(seep2) configure -text $seeing -status error
   }

   set seeing [sa agssad get oiseeing]
   if { [string is double -strict $seeing] } {
      if { [string match *A-AUTO* $oiguide] } {
         $itk_component(seeoi) configure -text [format %.2f $seeing] -status ok
      } else {
         $itk_component(seeoi) configure -text [format %.2f $seeing] -status none
      }
   } else {
      $itk_component(seeoi) configure -text $seeing -status error
   }

   if { $::env(GEMINI_SITE) eq "CP" } {
      set r0 [sa gemssad get r0]
      if { [string is double -strict $r0] } {
         if { $r0 != 0.0 } {
            set seeing [expr "0.976 * 0.5e-6 / ( $r0 * 1e-2 ) * 206265.0"]
         } else {
            set seeing ""
         }
      } else {
         set seeing $r0
      }
   } else {
      set seeing [sa agssad get aoseeing]
   }
   if { [string is double -strict $seeing] } {
      if { [string match *A-AUTO* $aoguide] } {
         $itk_component(seeao) configure -text [format %.2f $seeing] -status ok
      } else {
         $itk_component(seeao) configure -text [format %.2f $seeing] -status none
      }
   } else {
      $itk_component(seeao) configure -text $seeing -status error
   }

   #FIXME: FR10305: It seems that sometimes the update signals that call
# newtarget
   #and newobject are lost. The refresh of both wavelength and object name is
# moved
   #here as a workaround.
   if { $wavel != "" } {
      set wavel "[expr {$wavel / 10000.0}] um"
   }
   $itk_component(tarwavel) configure -text "$wavel"
   $itk_component(objname) configure -text [sa tcssad get sourceAObjectName]
}

itcl::body NumericDisplay::inPosition {rec value} {
   #+
   # Colour codes various widgets according to whether a sub-system is
   # in position and/or following.
   #-

   # Extract the subsystem and record from the name of the record that changed.
   foreach {subsys record} [split $rec .] {}

   # Telescope position.
   if { [string equal $subsys tcssad] || [string equal $subsys mcssad] } {
      if { [isFollowing mcssad followS] } {
         if { [isInPosition tcssad inPosition] } {
            set status ok
            $itk_component(inpos) configure -text ""
         } else {
            set status warning
            $itk_component(inpos) configure -text [inposreason]
         }
      } else {
         set status error
      }
      $itk_component(inpos) configure -status $status
   }

   # Telescope Az/El.
   if { [string equal $subsys mcssad] } {
      if { [isFollowing mcssad followS] } {
         if { [isInPosition mcssad inPositionAz] } {
            set azstat ok
         } else {
            set azstat warning
         }
         if { [isInPosition mcssad inPositionEl] } {
            set elstat ok
         } else {
            set elstat warning
         }
      } else {
         set azstat error
         set elstat error
      }
      $itk_component(telaz) configure -status $azstat
      $itk_component(azerr) configure -status $azstat
      $itk_component(telel) configure -status $elstat
      $itk_component(elerr) configure -status $elstat
   }

   # Cass rotator position.
   if { [string equal $subsys crssad] } {
      if { [isFollowing crssad followS] } {
         if { [isInPosition crssad inPosition] } {
            set status ok
         } else {
            set status warning
         }
      } else {
         set status error
      }
      $itk_component(rot) configure -status $status
      $itk_component(roterr) configure -status $status
   }

   # Dome az and shutter positions.
   if { [string equal $subsys tcssad] || [string equal $subsys ecssad] } {
      if { [string equal [sa tcssad get autoMoveDome] On ] } {
         if { [isInPosition ecssad domeInPos] } {
            set domestat ok
         } else {
            set domestat warning
         }
      } else {
         set domestat error
      }
      if { [string equal [sa tcssad get autoMoveShtrs] On ] } {
         if { [isInPosition ecssad topShtrInPos] } {
            set topstat ok
         } else {
            set topstat warning
         }
         if { [isInPosition ecssad botShtrInPos] } {
            set botstat ok
         } else {
            set botstat warning
         }
      } else {
         set topstat error
         set botstat error
      }
      $itk_component(domeaz) configure -status $domestat
      $itk_component(topshut) configure -status $topstat
      $itk_component(botshut) configure -status $botstat
   }
}

itcl::body NumericDisplay::noheartbeat {} {

   # No heartbeat seen for 5 seconds so write a message to the status
   # field and set it to the "error" colour.
   $itk_component(status) configure -text "NO HEARTBEAT" -status error
}

itcl::body NumericDisplay::heartbeat {rec value} {

   # Cancel the pending noheartbeat call.
   after cancel $nohbid

   # Get the state and health.
   set state [sa tcssad get state]
   set health [sa tcssad get health]

   # Update the status widget.
   $itk_component(status) configure -text ${state}/${health}

   # Set the widget status.
   if { [string compare $health BAD] == 0 } {
      $itk_component(status) configure -status error
   } elseif { [string compare $health WARNING] == 0 } {
      $itk_component(status) configure -status warning
   } elseif { [string compare $state RUNNING] != 0 } {
      $itk_component(status) configure -status warning
   } else {
      $itk_component(status) configure -status ok
   }

   # Schedule the noheartbeat method again.
   set nohbid [after 5000 [itcl::code $this noheartbeat]]
}

itcl::body NumericDisplay::inposreason {} {
   # Determines the reason for the TCS being out of position.
   if { ! [sa tcssad get tcsInPos] } {
      return [sa tcssad get outPosReason]
   } elseif { [sa mcssad get inPositionAz] ne 1 && [string equal [sa tcssad get mcsInposOverr] disabled]} {
      return "Azimuth axis not in position"
   } elseif { [sa mcssad get inPositionEl] ne 1 && [string equal [sa tcssad get mcsInposOverr] disabled]} {
      return "Elevation axis not in position"
   } elseif { [sa tcssad get mcsInPosition] ne 1 } {
      return "Mount not in position"
   } elseif { [sa tcssad get crcsInPosition] ne 1 } {
      return "Rotator not in position"
   } elseif { [sa tcssad get agInPosition] ne 1 } {
      return "A&G or A&G Seq not in position"
   } elseif { [sa tcssad get aoInPosition] ne 1 } {
      return "Adaptive Optics not in position"
   } elseif { $::env(GEMINI_SITE) eq "CP" && \
         ( [string equal -nocase [sa aomsad get ngs1Follow] "On"] || \
      [string equal -nocase [sa aomsad get ngs2Follow] "On"] || \
      [string equal -nocase [sa aomsad get ngs3Follow] "On"] ) && \
      [sa aomsad get inPosition] ne 1 } {
      return "Canopus not in position"
   } else {
      return ""
   }
}
