All: tcccmn.so tccext.so tsdext.so tcctime.so slaext.so tcctelsim.so

TCL_VERS = 8.4

CC = gcc
LD = g++

include ${HLPG_INSTALL_BASE}/conf/gemini_env

CMNOBJ = tccDecode.o tccUtil.o tccAst.o
TCCOBJ = tccext.o autorepeat.o plosc.o 
TSDOBJ = tsdext.o tsdDomeView.o tsdWrapView.o tsdElView.o
TIMEOBJ = tccTime.o
SLAOBJ = slaext.o
TELSIMOBJ = tccTelSim.o

CFLAGS = -fPIC -Wall -DUSE_TCL_STUBS -DUSE_TK_STUBS \
         -I${HLPG_EXT_RUNTIME_BASE}/tcl$(TCL_VERS)/include \
         -I${EPICS}/modules/slalib/include \
         -I${EPICS}/modules/timelib/include \
         -I${EPICS}/modules/astlib/include -m32

LDFLAGS = -shared \
	  -L${EPICS}/modules/slalib/lib/${EPICS_HOST_ARCH} \
          -Wl,-rpath=${EPICS}/modules/slalib/lib/${EPICS_HOST_ARCH} \
          -L${EPICS}/modules/timelib/lib/${EPICS_HOST_ARCH} \
          -Wl,-rpath=${EPICS}/modules/timelib/lib/${EPICS_HOST_ARCH} \
          -L${EPICS}/modules/astlib/lib/${EPICS_HOST_ARCH} \
          -Wl,-rpath=${EPICS}/modules/astlib/lib/${EPICS_HOST_ARCH} \
          -L${EPICS}/base/lib/${EPICS_HOST_ARCH} \
          -Wl,-rpath=${EPICS}/base/lib/${EPICS_HOST_ARCH} \
          -L${HLPG_EXT_RUNTIME_BASE}/tcl$(TCL_VERS)/lib \
          -ltclstub$(TCL_VERS) -ltkstub$(TCL_VERS) -lregistryIoc -last -ltime -lsla -m32 #-lposix4

tcccmn.so : $(CMNOBJ)
	$(LD) -o $@ $(CMNOBJ) $(LDFLAGS) 

tccext.so : $(TCCOBJ) tcccmn.so
	$(LD) -o $@ $(TCCOBJ) $(LDFLAGS) tcccmn.so \
		-Wl,-rpath=lib/${HOST_ARCH}

tsdext.so : $(TSDOBJ) tcccmn.so
	$(LD) -o $@ $(TSDOBJ) $(CMNOBJ) $(LDFLAGS) tcccmn.so \
		-Wl,-rpath=lib/${HOST_ARCH}

tcctime.so : $(TIMEOBJ)
	$(LD) -o $@ $(TIMEOBJ) $(LDFLAGS) 

slaext.so : $(SLAOBJ) tcccmn.so
	$(LD) -o $@ $(SLAOBJ) $(LDFLAGS) tcccmn.so \
		-Wl,-rpath=lib/${HOST_ARCH}

tcctelsim.so : $(TELSIMOBJ)
	$(LD) -o $@ $(TELSIMOBJ) $(LDFLAGS)

tsdext.o : tccAst.h
tccext.o : tccAst.h autorepeat.h plosc.h
tccUtil.o : tccConstants.h tccUtil.h
tccTime.o : tccConstants.h
tccAst.o : tccConstants.h tccUtil.h tccAst.h tccDecode.h
slaext.o: tccDecode.h
tsdDomeview.o : tccConstants.h tccDecode.h tccUtil.h
tsdWrapview.o : tccConstants.h tccDecode.h tccUtil.h
tsdElview.o : tccConstants.h tccDecode.h tccUtil.h
plosc.o : plosc.h
tccTelSim.o : tccConstants.h tccDecode.h tccUtil.h


clean:
	-rm $(TCCOBJ) $(TSDOBJ) $(CMNOBJ) $(SLAOBJ) $(TELSIMOBJ) $(TIMEOBJ)
	-rm tcccmn.so tccext.so tsdext.so tcctime.so slaext.so tcctelsim.so
	-rm -rf ../tcclib/${HOST_ARCH}
	-rm -rf ../tsdlib/${HOST_ARCH}
	-rm -rf ../lib/${HOST_ARCH}

install: All
	mkdir -p ../tcclib/${HOST_ARCH}
	cp tccext.so ../tcclib/${HOST_ARCH}
	cp tcctelsim.so ../tcclib/${HOST_ARCH}
	mkdir -p ../tsdlib/${HOST_ARCH}
	cp tsdext.so ../tsdlib/${HOST_ARCH}
	mkdir -p ../lib/${HOST_ARCH}
	cp tcctime.so ../lib/${HOST_ARCH}
	cp slaext.so ../lib/${HOST_ARCH}
	cp tcccmn.so ../lib/${HOST_ARCH}
