#+
#  Action.itcl
#
#  Implements the seq::Action class.
#
#  seq::Action
#
#     Parameters:
#
#        psys   The principle system object associated with the system
#               that implements the command.
#
#     Methods:
#
#        set {cs par val}
#
#           Sets a parameter value for a command sender.
#
#        start
#
#           Starts the execution of the action.
#
#     Options:
#
#           -oktest
#
#              The tcl script to execute to determine if the action is
#              complete.
#
#           -onok
#
#              The tcl script to execute when the action completes succesfully.
#
#           -onerror
#
#              The tcl script to execute when the action completes 
#              unsuccesfully.
#
#           -ontimeout
#
#              The tcl script to execute if the action has not completed
#              within the timeout period.
#
#           -timeout
#
#              The timeout period in seconds.
#
#           -waitvar
#
#              The variable to wait on while waiting for the action to
#              complete.
#
#
#  D Terrett 27 October 2000
#
#  Copyright CCLRC
#+

itcl::class seq::Action {
   constructor {psys args} {}
   public {
      method set {cs {par dummy} {val mark}}
      method start {}
      variable oktest {}
      variable waitvar {}
      variable onok {}
      variable onerror {}
      variable ontimeout {}
      variable timeout 60
   }
   private {
      variable Psys
      variable ParList
   }
}

itcl::body seq::Action::constructor {psys args} {

# Save the name of the principal system.
   ::set Psys $psys

   eval configure $args
}

itcl::body seq::Action::set {cs {par dummy} {val mark}} {

# Make sure that the command sender exists and that it has the specified
# parameter.
   if { [catch {cs $cs info}] } {
      epics cs $cs
   }
   if { [catch {cs $cs info $par}] } {
      error "Command sender $cs does not have a parameter called $par"
   }

# Add the parameter settings to the list.
   ::set ParList($cs,$par) $val

   return
}

itcl::body seq::Action::start {} {

# Set the command parameters.
   if { [array exists ParList] } {
      foreach name [array names ParList] {
         foreach {cs par} [split $name ,] {}
         if { [$Psys cget -debug] } {
            puts "cs $cs set $par value \"$ParList($name)\""
         }
         cs $cs set $par value \"$ParList($name)\"
      }
   }

# Post the command to the principal system.
   $Psys post $this

   return
}
