#+
#  PrincipalSystem.itcl
#
#  Implements the PrincipalSystem class.
#
#  seq::PrincipalSystem
#
#     Parameters:
#
#        apply   The name of the principle system's apply record.
#
#     Methods:
#
#        post action
#
#           Posts an action.
#
#        cancel action
#
#           Cancels an action.
#
#  D Terrett 22 July 2000
#
#  Copyright CLRC
#+

itcl::class seq::PrincipalSystem {
   constructor {apply} {}
   destructor {}
   public method post {action}
   public method cancel {action}

   private method monitor {name status info}

   private variable Apply
   private variable CurrentAction ""
}

itcl::body seq::PrincipalSystem::constructor {apply} {

# Save the name of the apply
   set Apply $apply
}

itcl::body seq::PrincipalSystem::destructor {} {

# Release the command monitor.
   cm $Apply release
}

itcl::body seq::PrincipalSystem::monitor {name status info} {

# Ignore busy status messages.
   if { ![string equal $status busy] } {

# If there is a current action then if it has the appropriate option set,
# execute that option.
      if { [string length $CurrentAction] } {

         if { [string equal $status idle] } {

# Get the command associated with sucessful completion of the current command.
            set command [$CurrentAction cget -onok]

# Clear the current action so that we don't get reinvoked by a BUSY/IDLE
# transition while waiting for the in position record to be set.
            set curact $CurrentAction
            set waitvar [$curact cget -waitvar]
            set oktest [$curact cget -oktest]
            set CurrentAction ""

# Give the system time to set its in position record. This is a fudge until
# the TCS subsystem set their ApplyC records properly.
            after 2000

# Wait for the in position record to have the ok value.
            if { ![string is space $oktest] } {
               while { ![uplevel #0 $oktest] } {
                  if { ![string is space $waitvar] } {
                     vwait $waitvar
                  }
               }
            }

# Cancel the actions timeout handler.
            $curact  canceltimeout

# Evaluate the OK command.
            if { [string length $command] } {
               uplevel #0 $command
            }
         } else {

# Handle error completion.
            $CurrentAction canceltimeout
            set command [$CurrentAction cget -onerror]
            if { [string equal $status error] } {
               set message [sa $Apply get mess value]
            } else {
               set message "Command timed out"
            }
            set CurrentAction ""
            uplevel #0 $command $info \"$message\"
         }
      }
   }
}

itcl::body seq::PrincipalSystem::post {action} {

# Post the apply with our monitor method as callback.
   cs $Apply postCallback [itcl::code $this monitor] -save

# Save the name of the current action.
   set CurrentAction $action

   return
}

itcl::body seq::PrincipalSystem::cancel {action} {
   if { [string is space $action] || [string equal $action $CurrentAction] } {
      if { ![string is space $CurrentAction] } {
         $CurrentAction cancel
         set $CurrentAction ""
      }
   }
}
