#+
#  PrincipalSystem.itcl
#
#  Implements the PrincipalSystem class.
#
#  seq::PrincipalSystem
#
#     Parameters:
#
#        apply   The name of the principle system's apply record.
#
#     Methods:
#
#        post action
#
#           Posts an action.
#
#        cancel action
#
#           Cancels an action.
#
#  D Terrett 11 September 2000
#
#  Copyright CLRC
#+

itcl::class seq::PrincipalSystem {
   constructor {apply} {}
   destructor {}
   public method post {action}
   public method cancel {action}

   private method monitor {name status info}
   private method timeout 
   private method traceproc {name1 name2 op}
   private method cleanup

   private variable Apply
   private variable CurrentAction ""
}

itcl::body seq::PrincipalSystem::constructor {apply} {

# Save the name of the apply
   set Apply $apply
}

itcl::body seq::PrincipalSystem::destructor {} {

# Cancel any actions in progress.
   cleanup

# Release the command monitor.
   cm $Apply release

# Cancel the timeout handler
   after cancel [itcl::code $this timeout]
}

itcl::body seq::PrincipalSystem::monitor {name status info} {

# Ignore busy status messages.
   if { ![string equal $status busy] } {

# If there is a current action then if it has the appropriate option set,
# execute that option.
      if { [string length $CurrentAction] } {

         if { [string equal $status idle] } {
            set command [$CurrentAction cget -onok]
            set waitvar [$CurrentAction cget -waitvar]
            set oktest [$CurrentAction cget -oktest]

# Give the system time to set its in position record. This is a fudge until
# the TCS subsystem set their ApplyC records properly.
            after 2000

# Wait for the in position record to have the ok value.
            if { ![string is space $oktest] } {
               if { [uplevel #0 $oktest] } {
                 set ok 1
               } else {
                 if { ![string is space $waitvar] } {

# Check for the variable trace already having been set.
                    set tracing 0
                    foreach t [trace vinfo $waitvar] {
                       if { [string equal $t \
                             [list w [itcl::code $this traceproc]] ] } {
                          set tracing 1
                          break
                       }
                    }
                    if { !$tracing } {

# Set a trace on the wait variable.
                       trace variable $waitvar w [itcl::code $this traceproc]
                    }
                 }
                 set ok 0
               }
            } else {
               set ok 1
            }

            if { $ok } {
               cleanup

# Evaluate the OK command.
               if { [string length $command] } {
                  uplevel #0 $command
               }
            }
         } else {

# Handle error completion.
            set command [$CurrentAction cget -onerror]
            if { [string equal $status error] } {
               set message [sa $Apply get mess value]
            } else {
               set message "Command timed out"
            }
            cleanup
            uplevel #0 $command $info \"$message\"
         }
      }
   }
}

itcl::body seq::PrincipalSystem::post {action} {

# Post the apply with our monitor method as callback.
   cs $Apply postCallback [itcl::code $this monitor] -save

# Save the name of the current action.
   set CurrentAction $action

# Start the timeout handler
   set timeoutcommand [$CurrentAction cget -ontimeout]
   if { ![string is space $timeoutcommand] } {
      after [expr {[$action cget -timeout] * 1000}] [itcl::code $this timeout]
   }

   return
}

itcl::body seq::PrincipalSystem::cancel {action} {
   if { [string is space $action] || [string equal $action $CurrentAction] } {
      cleanup
   }
}

itcl::body seq::PrincipalSystem::timeout {} {
   set timeoutcommand [$CurrentAction cget -ontimeout]
   if { ![string is space $timeoutcommand] } {
      uplevel #0 $timeoutcommand
   }
   cleanup
}

itcl::body seq::PrincipalSystem::traceproc {name1 name2 op} {
   monitor "" idle ""
}

itcl::body seq::PrincipalSystem::cleanup {} {

   if { ![string is space $CurrentAction] } {

# Delete timeout handler.
      after cancel [itcl::code $this timeout]

# Remove ok trace procedure.
      set waitvar [$CurrentAction cget -waitvar]
      if { ![string is space $waitvar] } {
         trace vdelete $waitvar w [itcl::code $this traceproc]
      }

# Clear the current action.
      set CurrentAction ""
   }
}
